### ISSUE TITLE
[misc] Support access vector/matrix elements dynamically

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#1004]
**Concisely describe the proposed feature**

I found that the following code didn't work:

```py
import taichi as ti

ti.init(arch=ti.gpu)

@ti.func
def f():
    a = ti.Vector([0.0, 0.0, 0.0])
    # for i in ti.static(range(3)):  # OK
    for i in range(3):  # throw an exception!
        a[i] = i
    return a

@ti.kernel
def test():
    f()
 
test()
```

Running it will spit the following error:

```
Traceback (most recent call last):
  File "r2.py", line 17, in <module>
    test()
  File "/Users/yekuang/Github/taichi/python/taichi/lang/kernel.py", line 500, in wrapped
    return primal(*args, **kwargs)
  File "/Users/yekuang/Github/taichi/python/taichi/lang/kernel.py", line 430, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/Users/yekuang/Github/taichi/python/taichi/lang/kernel.py", line 310, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "/Users/yekuang/Github/taichi/python/taichi/lang/kernel.py", line 307, in taichi_ast_generator
    compiled()
  File "r2.py", line 15, in test
    f()
  File "/Users/yekuang/Github/taichi/python/taichi/lang/kernel.py", line 52, in __call__
    ret = self.compiled(*args)
  File "r2.py", line 10, in f
    a[i] = i
  File "/Users/yekuang/Github/taichi/python/taichi/lang/impl.py", line 93, in subscript
    return value.subscript(*indices)
  File "/Users/yekuang/Github/taichi/python/taichi/lang/matrix.py", line 221, in subscript
    return self(i, j)
  File "/Users/yekuang/Github/taichi/python/taichi/lang/matrix.py", line 192, in __call__
    return self.entries[self.linearize_entry_id(*args)]
TypeError: list indices must be integers or slices, not Expr
```

I initially thought this to be a bug. But then after looking at `Matrix` implementation,

https://github.com/taichi-dev/taichi/blob/91b8164e4a881d7d588daf02ca5083e097fa0fec/python/taichi/lang/matrix.py#L190-L192

 I saw that `entries` is a python list, so the index must be known at compile time?

So I think it will be great if we can support accessor index on `ti.Vector` and `ti.Matrix` at runtime.

**Comment by xumingkuan** [comment]
If users need to access vector/matrix elements dynamically, they can just use a tensor instead... But indeed, the compilation error message is confusing.

**Comment by yuanming-hu** [comment]
Thanks for raising this.

This is probably hard to implement given how CHI is designed. The SNode being accessed must be a compile-time constant. I don't have a perfect solution for this right now. `ti.static` is our friend in this case.

And yes, we should certainly improve the error message here...

**Comment by k-ye** [comment]
> If users need to access vector/matrix elements dynamically, they can just use a tensor instead...

But then they lose the ability to do matrix computation?

> ti.static is our friend in this case

Right, what I wanted to do was something below, so `ti.static` couldn't help here :(

```py
idx = 0
for i in ti.static(range(3)):
  if some_condition:
    idx = i

v = ti.Vector([0, 0, 0])
v[idx] = 42
```

**Comment by archibate** [comment]
> > If users need to access vector/matrix elements dynamically, they can just use a tensor instead...
> 
> But then they lose the ability to do matrix computation?

Disagree, they are suggested to use tensor dimension in dynamic-indexing purpose: https://taichi.readthedocs.io/en/latest/tensor_matrix.html#matrix-size

> Right, what I wanted to do was something below, so ti.static couldn't help here :(

You can help, by:
```py
v = ti.Vector([0, 0, 0])
for i in ti.static(range(3)):
  if some_condition:
    v[idx] = 42
```
I thought this is actually easier?

**Comment by archibate** [comment]
I think `ti.Array` in #777 can be used as dynamic-indexable-but-poor-performance matrices. Maybe you want to go for that approach and keep `ti.Matrix` statically-unrolled-and-high-performance?

**Comment by k-ye** [comment]
> Disagree, they are suggested to use tensor dimension in dynamic-indexing purpose:

The doc https://taichi.readthedocs.io/en/latest/tensor_matrix.html#tensors-of-matrices mentions that:

> As you may have noticed, there are two indexing operators [] when you load a matrix element from a global tensor of matrices: the first is for tensor indexing, the second for matrix indexing.

And I guess you're talking about the first tensor indexing, while what I was looking for was the second matrix indexing.

> I thought this is actually easier?

No it doesn't help the actual scenario i'm talking about. `some_condition` can change inside `ti.static(range(3))`, so we only know `idx` after the loop finishes.

**Comment by archibate** [comment]
> And I guess you're talking about the first tensor indexing? But what I was looking for was the second matrix indexing.

I mean by: `m[i, j][k, l]` -> `m[i, j, k, l]`, so `k, l` can be dynamic.

> No it doesn't help the actual scenario i'm talking about. some_condition can change inside ti.static(range(3)), so we only know idx after the loop finishes.

I don't understand... wans't static-range ensures idx to be compile-time constant?

**Comment by xumingkuan** [comment]
> > No it doesn't help the actual scenario i'm talking about. some_condition can change inside ti.static(range(3)), so we only know idx after the loop finishes.
> 
> I don't understand... wasn't static-range ensuring `idx` to be compile-time constant?

Suppose `some_condition` is always true.
```py
idx = 0
for i in ti.static(range(3)):
  if some_condition:
    idx = i

v = ti.Vector([0, 0, 0])
v[idx] = 42
```
results in `v[2] = 42`.

But
```py
v = ti.Vector([0, 0, 0])
for i in ti.static(range(3)):
  if some_condition:
    v[i] = 42
```
sets `v[0] = v[1] = v[2] = 42`.

**Comment by k-ye** [comment]
> I mean by: m[i, j][k, l] -> m[i, j, k, l], so k, l can be dynamic.

`m[i, j, k, l]` is not a valid syntax.

**Comment by strongoier** [comment]
Close as this has been finished.
