### ISSUE TITLE
[sparse] Skip listgen for dense SNode

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#1011]
**Concisely describe the proposed feature**

I think for `dense` SNode, we could fill its `ListManager` once at the initialization time, then skip the `clear/listgen` kernels for this SNode. Its size never changes, and its elements are always active.

**Describe the solution**

I think this cannot be easily unified for all backends, since different backends have very different initialization routines. So most likely, the IR passes would still need to retain these offloaded tasks, but then each backend can optionally choose to skip them.

**Comment by KLozes** [comment]
To add to this, I think we could sometimes skip list gen for sparse data structures too. Many algorithms iterate over the same list multiple times before the topology of the grid changes. If we flip a "changed" flag whenever we de/activate a bitmasked, pointer, or dynamic snode element, then we should be able to tell if the grid changed. So, if that flag is still false and we are iterating over the same variable as the previous kernel. Then skip we can skip list gen.

**Comment by k-ye** [comment]
Exactly. Actually, see https://github.com/taichi-dev/taichi/pull/986#issuecomment-630781542 :D

But I think @yuanming-hu has a systematic plan to fix this, so let me just close it now..
