### ISSUE TITLE
Copyright declaration format issue

### ISSUE THREAD

**Issue by Leedehai** [taichi-dev/taichi#1024]
**Describe the bug**

Hi, I believe the year number in the first line of copyright declaration should be `2016` or `2016-[year of the latest modification]`, not `2016- `.

If the year number is just `2016`, that means the copyright was declared initially from 2016. If the year number is `2016-XXX`, that means the copyright was declared initially from 2016 and a (major) modification was recently made in XXX. Note that `2016-XXX` does *not* mean the copyright ends in year XXX, and `2016- ` is not an accepted format.

[A post on stackexchange](https://opensource.stackexchange.com/a/6393).

Another minor issue is that, it's best practice to put the year number before the author name `Taichi Authors`, not after :)

点赞！

**Comment by Leedehai** [comment]
It is not a "potential bug", but that label was assigned automatically to this issue..

**Comment by archibate** [comment]
Cool! Thank for pointing out. Would you mind to make a PR to make things correct?

**Comment by yuanming-hu** [comment]
> If the year number is just `2016`, that means the copyright was declared initially from 2016. If the year number is `2016-XXX`, that means the copyright was declared initially from 2016 and a (major) modification was recently made in XXX. Note that `2016-XXX` does _not_ mean the copyright ends in year XXX, and `2016- ` is not an accepted format.



Thanks for pointing this out!

> Cool! Thank for pointing out. Would you mind to make a PR to make things correct?

I think we should first discuss if it is necessary to enforce the copyright notice as part of the code format requirements.

https://github.com/taichi-dev/taichi/blob/8efba16602bc8fe1e2700307dca3130899d1629d/taichi/common/core.h#L1-L4

At the moment most files don't have these lines.

**Comment by archibate** [comment]
> I think we should first discuss if it is necessary to enforce the copyright notice as part of the code format requirements.
> 
> https://github.com/taichi-dev/taichi/blob/8efba16602bc8fe1e2700307dca3130899d1629d/taichi/common/core.h#L1-L4
> 
> At the moment most files don't have these lines.

It seems that only the *legacy* parts have these lines? I personally don't like these lines, since that should be a `LICENCE` should do, not the source codes.

**Comment by Leedehai** [comment]
> I personally don't like these lines, since that should be a LICENCE should do, not the source codes.

I'd suggest keep the copyright notices in files, so that it is harder for a violator to claim "innocent infringement" because he/she would need to explicitly delete the notices.

Of course, I'm not a lawyer and this is not a legal advice.

**Comment by Leedehai** [comment]
I'll go ahead and make a PR.

**Comment by yuanming-hu** [comment]
Thanks! One file that may be useful: https://github.com/taichi-dev/taichi/blob/master/misc/add_copyright.py

**Comment by Leedehai** [comment]
Created [PR 1031](https://github.com/taichi-dev/taichi/pull/1031). Sorry I didn't notice your reply above (regarding [add_copyright.py](https://github.com/taichi-dev/taichi/blob/master/misc/add_copyright.py)), so I hand-rolled one myself.

The new script, however, can handle files in batch and can handle Python/Shell/.. style comments as well, so I think it's worthwhile to keep it (but feel free to say no) 😄 

Closing this issue. Let's followup on that PR.
