### ISSUE TITLE
[GUI] Draw text on canvas

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1045]
(This is an issue for GAMES 201 TAs.)

**Concisely describe the proposed feature**

Add method `text(context: str, pos: tuple, font_size: int)` to the [GUI class](https://github.com/taichi-dev/taichi/blob/6c02c401a60625f730aedd3c675974fc8efae1cd/python/taichi/misc/gui.py#L5) in Python.

**Describe the solution you'd like (if any)**
In C++ this is already implemented here:
https://github.com/taichi-dev/taichi/blob/6c02c401a60625f730aedd3c675974fc8efae1cd/taichi/gui/gui.h#L388-L396

Please bind the C++ method to Python using pybind11 here:
https://github.com/taichi-dev/taichi/blob/6c02c401a60625f730aedd3c675974fc8efae1cd/taichi/python/export_visual.cpp#L39

(Please see how `GUI.circle` is implemented.)

You may also need the font file (https://github.com/yuanming-hu/taichi_assets/tree/master/fonts/go).

In the end, make sure the font file is shipped with Taichi.

**Comment by archibate** [comment]
If nobody take this, I'll take this. It really a easy-to-implement issue and can be a great chance to understand Taichi codebase... what a pity.
