### ISSUE TITLE
[test] test_element_wise.py takes too long time

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1055]
`test_element_wise.py` takes so much time that the thread running it is always the bottleneck.
As mentioned in https://github.com/taichi-dev/taichi/pull/1032#issuecomment-632987002.
Let's make it slim and quick then.

**Comment by archibate** [comment]
It takes 87.3s (just for x64) in #1062 now. I guess it's taking up the half time of the current test.. maybe we should fuse some of these kernels to shorten compilation time? Inputs are welcome!

**Comment by xumingkuan** [comment]
In the master branch, it takes 193s on my laptop (all tests take 450s in total)...

**Comment by xumingkuan** [comment]
Do we need `for n, m in [(5, 4), (3, 1)]:` in `test_element_wise.py`?

**Comment by xumingkuan** [comment]
I found that `func()` in the test actually consists of ~1000 statements, and compiling ~100 such kernels is very slow...

**Comment by xumingkuan** [comment]
This test took 1458s just now (all tests took 2484s).
