### ISSUE TITLE
[Test] [refactor] Further refine C++ tests

### ISSUE THREAD

**Issue by TH3CHARLie** [taichi-dev/taichi#1067]
**Concisely describe the proposed feature**

As mentioned in discussions in #1058, C++ tests construct blocks and program separately and manually, which is different from the usual taichi approach, and this leads to no connection between the root block and the kernel.

For now, #1058 introduces a fake kernel to adapt to the IR system refactor. It would be reasonable to refine these C++ tests and remove these hacks. I assume that after this refinement, we'd have minimal work to do with tests when we are refactoring the IR system, instead of adding more hacks.

**Describe the solution you'd like (if any)**
I have no detailed solution yet but I'd like to investigate(if this is of high priority). The high-level approach would be finding out how program/kernel/ir is built through python AST and mimicking this in C++ tests.

**Comment by k-ye** [comment]
Covered in #2198

**Comment by TH3CHARLie** [comment]
cool!
