### ISSUE TITLE
[Refactor] Remove ti.layout in test cases

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1077]
**Description**
After #420, in most cases `ti.layout` is no longer necessary. It would be great to simplify the tests case, as there are lot of redundant `ti.layout`. For example,

https://github.com/taichi-dev/taichi/blob/6989c0e21d437a9ffdc0151cee9d3aa2aaa2241d/tests/python/test_ad_atomic.py#L12-L14

can be simplified into
```python
ti.root.place(loss, loss.grad).dense(ti.i, N).place(x, x.grad)
```

**Next step**
`ti.layout` should be deprecated.

**Comment by enmuser** [comment]
how to handle the "taichi.lang.exception.InvalidOperationError: layout(): Deprecated” the problem from the  @ti.layout

**Comment by shauiyang** [comment]
I have the same question

**Comment by k-ye** [comment]
In general, please just remove @ti.layout. (Or could you provide where you've run into this problem?)
