### ISSUE TITLE
[Installation] Could not find taichi with pip

### ISSUE THREAD

**Issue by SaltedReed** [taichi-dev/taichi#1097]
I'm using Python3.8 and tried to install taichi with pip, but an error occured:
![image](https://user-images.githubusercontent.com/51510811/83416820-d621c680-a453-11ea-8b9a-006efdcd29d8.png)
How to fix it or is there any other way to install taichi? Thanks for any help!

**Comment by rexwangcc** [comment]
Just for a sanity check, could you run `python` and :

```python
import os, sys
os.path.dirname(sys.executable)
```
as well as `python -m pip --version`

on your machine and paste the results here?

**Comment by SaltedReed** [comment]
yes, they work well. i've used pip to install several python packages before




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chengchen(Rex) Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 晚上10:20
收件人:&nbsp;"taichi-dev/taichi"<taichi@noreply.github.com&gt;;
抄送:&nbsp;"于凡"<1654937223@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taichi-dev/taichi] [Installation] Could not find taichi with pip (#1097)





 
Just for a sanity check, could you run python and :
 import os, sys os.path.dirname(sys.executable)
 
as well as python -m pip --version
 
on your machine and paste the results here?

**Comment by PeiqinSun** [comment]
+1.  I also failed.

**Comment by archibate** [comment]
Could you run the following two scripts in the shell and verify the output?
```bash
python3 -c "print(__import__('sys').version[:3])"
```
should obtain one of: 3.6, 3.7 or 3.8.

```bash
python3 -c "print(__import__('platform').architecture()[0])"
```
should obtain: 64bit.

Note that sometimes Windows Python installers are downloaded 32bit by default.

**Comment by SaltedReed** [comment]
I got 32bit from the 2nd statement. so should I uninstall python and reinstall a 64bit one?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"彭于斌"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 晚上11:15
收件人:&nbsp;"taichi-dev/taichi"<taichi@noreply.github.com&gt;;
抄送:&nbsp;"于凡"<1654937223@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taichi-dev/taichi] [Installation] Could not find taichi with pip (#1097)





 
Could you run the following two scripts in the shell and verify the output?
 python3 -c "print(__import__('sys').version[:3])"
 
should obtain one of: 3.6, 3.7 or 3.8.
 python3 -c "print(__import__('platform').architecture()[0])"
 
should obtain: 64bit.
 
Note that sometimes Windows Python installers are downloaded 32bit by default.

**Comment by archibate** [comment]
> I got 32bit from the 2nd statement. so should I uninstall python and reinstall a 64bit one?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"彭于斌"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月1日(星期一) 晚上11:15 收件人:&nbsp;"taichi-dev/taichi"<taichi@noreply.github.com&gt;; 抄送:&nbsp;"于凡"<1654937223@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [taichi-dev/taichi] [Installation] Could not find taichi with pip (#1097) Could you run the following two scripts in the shell and verify the output? python3 -c "print(__import__('sys').version[:3])" should obtain one of: 3.6, 3.7 or 3.8. python3 -c "print(__import__('platform').architecture()[0])" should obtain: 64bit. Note that sometimes Windows Python installers are downloaded 32bit by default. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes :) Taichi doesn't support 32bit for now.
