### ISSUE TITLE
[Bug] Cannot load taichi with opengl 4.6 > 4.3 on Ubuntu 20 (AMD card)

### ISSUE THREAD

**Issue by Eydcao** [taichi-dev/taichi#1106]
**Describe the bug**
Taichi fail to load in Ubuntu 20.04 with OpenGL 4.6 (AMD card). Related #958 
At that moment we simply disabled opengl in bash, and assume the problem can be solved if gl version > 4.3. Nonetheless, on my laptop with version 4.6, the problem still exists. My graphic card is AMD® Raven.

**Log/Screenshots**

The 4 screenshots of running examples/fractal.py

![1st](https://user-images.githubusercontent.com/48085697/83482642-589d9b00-a4d3-11ea-9d9b-845efbb781e6.png)

![2nd](https://user-images.githubusercontent.com/48085697/83482706-87b40c80-a4d3-11ea-87d6-9885e2ce999b.png)

![3rd](https://user-images.githubusercontent.com/48085697/83482760-af0ad980-a4d3-11ea-8f54-5501f334fd5a.png)

![image](https://user-images.githubusercontent.com/48085697/83482795-baf69b80-a4d3-11ea-80a0-233f391d1801.png)

The screenshot of gl version

![glVersion](https://user-images.githubusercontent.com/48085697/83483035-512ac180-a4d4-11ea-8acc-f4b0ea36528f.png)

**Comment by Eydcao** [comment]
I will try on the same device but with Windows soon

**Comment by senjay** [comment]
I meet the same error in IDE(pycharm) ,but it can run in terminal.I find it doesn't work when I set `export TI_ENABLE_OPENGL=0` in `~/.bashrc` .
My solution is to set the envirment variables in IDE or run in terminal .Maybe you can try the same way in vscode.
![图片](https://user-images.githubusercontent.com/23068172/83626755-7dc00580-a5c8-11ea-809f-826e251d7422.png)

**Comment by archibate** [comment]
A similar issue: http://www.mujoco.org/forum/index.php?threads/segmentation-fault-when-running-bin-simulate-on-ubuntu-16-04.3512/
Seems it's not the OpenGL vesion caused the issue, but the **lack of AVX support** according to the article?

**Comment by Eydcao** [comment]
> A similar issue: http://www.mujoco.org/forum/index.php?threads/segmentation-fault-when-running-bin-simulate-on-ubuntu-16-04.3512/
> Seems it's not the OpenGL vesion caused the issue, but the **lack of AVX support** according to the article?

I will give it a shot, :> amazing speed archibate!

**Comment by Eydcao** [comment]
> I meet the same error in IDE(pycharm) ,but it can run in terminal.I find it doesn't work when I set `export TI_ENABLE_OPENGL=0` in `~/.bashrc` .
> My solution is to set the envirment variables in IDE or run in terminal .Maybe you can try the same way in vscode.
> ![图片](https://user-images.githubusercontent.com/23068172/83626755-7dc00580-a5c8-11ea-809f-826e251d7422.png)

Thanks for sharing experience which may help others who have problem enforcing CPU mode. We are trying to fix is the openGL/GLX compability issue as mentioned in #1134 . After the fix you should be able to run the openGL mode under Linux.

**Comment by archibate** [comment]
A quick guess according to https://github.com/taichi-dev/taichi/issues/1325#issuecomment-649418562:
Does deleting `/lib/libLLVM-9.so` solve your problem? @Eydcao

**Comment by Eydcao** [comment]
> A quick guess according to [#1325 (comment)](https://github.com/taichi-dev/taichi/issues/1325#issuecomment-649418562):
> Does deleting `/lib/libLLVM-9.so` solve your problem? @Eydcao

Hi, Yubin,

I tested and encountered some errors. Please refer to #1326 for details.

I noticed that the library you mentioned is llvm-9, I am still running with llvm 8. Could that be the issue?

Thanks
