### ISSUE TITLE
[misc] Video generation tutorial 

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1116]
**Concisely describe the proposed feature**
A lot of people are having trouble making a video to demonstrate their Taichi programs.

Now we actually already have `GUI.show(filename)` to save the frames, `ti video` (frames to mp4) and `ti gif` (mp4 to GIF) command. We just need to add a tutorial on how to use these handy functions.

**Additional comments**
We may also need to briefly doc how to install `ffmpeg` on Windows/OS X. I guess most Linux releases come with `ffmpeg`.

**Comment by Rullec** [comment]
Great!
My plan is to add an **export_result.rst** doc that exaplains the usage of GUI.show, ti.video and ti.gif in our docs/ directory. Do you think it's ok?

**Comment by archibate** [comment]
Yes, please add a brief usage description for `ti video`, `ti video_xxx` and `ti gif` to export_result.rst, in the `Miscellaneous` section, thanks!

**Comment by archibate** [comment]
Also remember to mention ti.imread/imwrite/imshow :smile:

**Comment by archibate** [comment]
这里已经有一位热心的小朋友做好了：https://forum.taichi.graphics/t/homework-0-new-shader-ffmpeg-gif/469

**Comment by Rullec** [comment]
速度真的够快，，，那你感觉我们还需要加一个rst到仓库里面去吗？如果需要的话我晚上提一个PR

**Comment by yuanming-hu** [comment]
> 速度真的够快，，，那你感觉我们还需要加一个rst到仓库里面去吗？如果需要的话我晚上提一个PR

Yes, please. Providing `ti video` and `ti gif` is still very helpful. They are much easier to use than raw ffmpeg.
