### ISSUE TITLE
Why are the ti examples names directories rather than the names themselves?

### ISSUE THREAD

**Issue by EaryChow** [taichi-dev/taichi#1117]
**Describe the bug**
When using "ti example" in Windows cmd, the names showing are directories with double back slashes, I need to manually delete one of the two back slashes that appear in the directories for the program to recognize the names.

**Log/Screenshots**
Please post the full log of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening.
![image](https://user-images.githubusercontent.com/59176246/83594173-911d9300-a52c-11ea-9c83-ca10d3543a95.png)
![image](https://user-images.githubusercontent.com/59176246/83594907-73e9c400-a52e-11ea-8ece-f567be28542e.png)
![image](https://user-images.githubusercontent.com/59176246/83594972-ac899d80-a52e-11ea-9b20-9108a0a7cec2.png)

![image](https://user-images.githubusercontent.com/59176246/83595035-d2af3d80-a52e-11ea-9f26-41bf17cab4bc.png)

**To Reproduce**
Please post a sample code to reproduce the bug. The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the code short.

Just type "ti example" and hit enter.

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**

**Comment by archibate** [comment]
Thank for reporting this! It's fixed in #1085 and will be soon release in v0.6.8. For now you may walk around by manually copying example codes from https://github.com/taichi-dev/taichi/tree/master/examples.
