### ISSUE TITLE
[GUI] closing a window cause crash

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1118]
**Concisely describe the proposed feature**
Currently closing a window using the 'x' button right-top will cause the program to crash.
This confuses the jupyter users which doesn't re-import taichi after restart.
Also note that if user close window with 'esc', the window won't disappear for jupyter users due to the same reason.

**Describe the solution you'd like (if any)**
Make window close a event/exception. If the event is not processed/catched, automatically break-the-loop/exit-the-program.

**Additional comments**
As mentioned in the GAMES 201 WeChat group.

**Comment by liaopeiyuan** [comment]
Where may I find the entry point/invite link to GAMES 201 WeChat group?

**Comment by archibate** [comment]
@liaopeiyuan forum.taichi.graphics

**Comment by archibate** [comment]
Related thread: https://stackoverflow.com/questions/10792361/how-do-i-gracefully-exit-an-x11-event-loop
