### ISSUE TITLE
[BUG or Feature] gui.set_image should be invoked twice to show image?

### ISSUE THREAD

**Issue by the-butterfly** [taichi-dev/taichi#1122]
```python
# draw test
import taichi as ti

ti.init()
pix = ti.var(dt=ti.f32, shape=(200,100))
pix.fill(0.25)
gui = ti.GUI("Test", res=(200,100))
for _ in range(1):
    gui.set_image(pix)
    gui.show()
```
显示为全黑窗口... range(10) 正常

**Comment by archibate** [comment]
Thank for reporting this, the reason may because `gui.show` always clears the window after a frame done. We're using `ti.imshow(pix)` as a walk around for now.

**Comment by bobcao3** [comment]
Closing this issue as we are moving towards GGUI (where this is not an issue)
