### ISSUE TITLE
希望能在解释器中使用

### ISSUE THREAD

**Issue by lsysyem** [taichi-dev/taichi#1136]
解释器中使用提示找不到源码

**Comment by TH3CHARLie** [comment]
Please use IPython as an interactive tool. The reason that cannot find source code in python IDLE, if I recall correctly, is related to cpython's IDLE implementation that does not cache source code while taichi's JIT compilation requires that source code.

**Comment by lsysyem** [comment]
> 请使用IPython作为交互式工具。如果我没记错的话，在python IDLE中找不到源代码的原因与cpython的IDLE实现有关，该实现不缓存源代码，而taichi的JIT编译需要该源代码。

我其实想在houdini里试试，但是ipython不行

**Comment by TH3CHARLie** [comment]
> 我其实想在houdini里试试，但是ipython不行
>

Being able to use python within houdini would be a cool feature to have, I will mention this with other developers and see if there's anything we can do to improve this.

**Comment by liaopeiyuan** [comment]
Kinda tangent to this topic, I've had issues with Taichi while debugging in Jupyter Notebook, which I think has to do with the way jupyter's kernel is run. I feel like a lot of newbies (like me) tend to use Jupyter Notebook to play around with libraries, so maybe we can do something about it too.

**Comment by TH3CHARLie** [comment]
> Kinda tangent to this topic, I've had issues with Taichi while debugging in Jupyter Notebook, which I think has to do with the way jupyter's kernel is run. I feel like a lot of newbies (like me) tend to use Jupyter Notebook to play around with libraries, so maybe we can do something about it too.

Would you mind elaborate on what exactly happen when debugging in jupyter notebook? because there is another student reporting jupyter kernel fails after running taichi.

**Comment by liaopeiyuan** [comment]
I didn't remember the exact details to reproduce the errors, but the weird things include:

- Jupyter kernel dying instead of throwing error/exception
- Unable to execute different taichi kernels across cells (weird exceptions after executing the first cell)
- Unable to run a single taichi kernel (print statement has no effect/entries in matrices are not updated)

**Comment by TH3CHARLie** [comment]
> I didn't remember the exact details to reproduce the errors, but the weird things include:
> 
> * Jupyter kernel dying instead of throwing error/exception
> * Unable to execute different taichi kernels across cells (weird exceptions after executing the first cell)
> * Unable to run a single taichi kernel (print statement has no effect/entries in matrices are not updated)

Thanks for sharing, this is super useful for locating the bugs. I'll try them accordingly. And when next time these weird situations happen, please be sure to record them and open an issue on that.

**Comment by dongx17-THU** [comment]
> > 请使用IPython作为交互式工具。如果我没记错的话，在python IDLE中找不到源代码的原因与cpython的IDLE实现有关，该实现不缓存源代码，而taichi的JIT编译需要该源代码。
> 
> 我其实想在houdini里试试，但是ipython不行

同样遇到了houdini中跑taichi需要ipython的问题，请问楼主后边有好的解决方法么？
