### ISSUE TITLE
[GUI] cannot get keyboard events

### ISSUE THREAD

**Issue by JYLeeLYJ** [taichi-dev/taichi#1138]
**Describe the bug**
GUI could not make any reaction after I press any key . (I first encounter at example/keyboard )

**Log/Screenshots**
There is no such meaningful log to show . Directly give out my code to reproduce.

**To Reproduce**
my environment version :
* [OS] : win10
* [Python] : 3.7.3
* [Taichi] : 0.6.7

my simple test code :
```
import taichi as ti

x, y = 0.5, 0.5
gui = ti.GUI("event test")
while True :
    while gui.get_event(ti.GUI.PRESS):
        print("press key : {}".format(gui.event.key)) 

    if gui.is_pressed(ti.GUI.LMB , ti.GUI.RMB):
        x, y = gui.get_cursor_pos()
    gui.circle((x,y) , radius= 8)
    gui.show()
```
1. start running , and trigger any click event (LMB or RMB)
2. we can see that print correctly
3. but once we press any key 
4. there is no log 
5. **GUI cannot make reactions anymore , to neither clicking nor pressing keys** 

the example logs below : 
```
[Taichi] mode=release
[Taichi] version 0.6.7, supported archs: [cpu, cuda, opengl], commit ca4d9dda, python 3.7.3

 *******************************************
 **     Taichi Programming Language       **
 *******************************************

[Taichi] mode=release
[Taichi] version 0.6.7, supported archs: [cpu, cuda, opengl], commit ca4d9dda, python 3.7.3
press key : LMB
press key : LMB
press key : RMB
press key : RMB
press key : RMB
press key : LMB # ( and then I pressed any key )

>>> Running time: 10.72s 
```

PS. It looks like that ``` self.has_key_event() ``` ( in ``` gui.py , line 182 ``` ) always returns false  after the problem occurs ...

**Comment by archibate** [comment]
Thank for reporting! On my end, LMB&RMB is working properly, however the aswd key not working instead..

**Comment by archibate** [comment]
I found that changing `'a'` to `'A'` solve the problem?

**Comment by JYLeeLYJ** [comment]
> I found that changing `'a'` to `'A'` solve the problem?

My test code showed above is not relevant to any specific value .. But after once I press a key , even clicking or other event will fail to get

**Comment by archibate** [comment]
```
[Taichi] mode=release
[Taichi] version 0.6.7, supported archs: [cpu, cuda, opengl], commit ca4d9dda, python 3.7.6
press key : LMB
press key : LMB
press key : LMB
press key : RMB
press key : RMB
press key : D
press key : D
press key : F
press key : S
press key : LMB
press key : LMB
press key : LMB
press key :  
press key : RMB
press key : RMB
press key : LMB
press key : D
press key : S
press key : D
press key : F
press key : E
press key : T
press key : Escape
```
Failed to reproduce on:
+ [OS] : win10
+ [Python] : 3.7.6
+ [Taichi] : 0.6.7

**Comment by JYLeeLYJ** [comment]
More detailed tests.

I found that problem will occur on my win10 pro ( 2004 insider version ) , but works well on win10 home (1909)  .
* win10 pro 2004 insider ( wrong )
* win10 home 1909 ( correct )

The problem was located at ```gui/win32.cpp line 134``` :
```
  if (PeekMessage(&msg, hwnd, 0, 0, PM_REMOVE)) {
```
Triggered keyboard message cannot peek by this call  . Cause value ```msg.hwnd``` of the keyboard message is ```NULL``` on my win10 pro version  , but equals to current GUI's handle value on win10 home .

Modify ```hwnd``` to ```NULL``` is working well.

```
  if (PeekMessage(&msg, NULL, 0, 0, PM_REMOVE)) {
``` 
But I'm not sure if it's a bug of win10 OS .
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-peekmessagew

Maybe we should use ```NULL``` instead of ```hwnd``` in taichi ?

**Comment by archibate** [comment]
Thank for your patient inspection! The information sounds reasonable to me but I'm not a win expert.. sorry.. Would you mind to submit a PR to fix this? Many thanks :)
