### ISSUE TITLE
[Lang] Do we have a C/C++ Frontend?

### ISSUE THREAD

**Issue by liaopeiyuan** [taichi-dev/taichi#1142]
**Concisely describe the proposed feature**
I understand that AST transforms take place mainly in Python, but is there an incentive to develop a C/C++ frontend for those unfamiliar with Python/prefers a C++ environment? 

**Describe the solution you'd like (if any)**
Maintaining a cpp api that closely maps the Python life-cycle, and are kept only for advanced usage, while the recommended environment is still Python.

**Additional comments**
- cpp syntax may allow more possibilities for taichi
- but I'm not sure if this is actually doable

**Comment by rexwangcc** [comment]
related discussion: #439

**Comment by archibate** [comment]
We used to have a legacy C++ frontend, called `taichi.h`, now its code is out-of-date, but still lying in this repo, not sure it's still working, ask @yuanming-hu for more info.
