### ISSUE TITLE
[GUI] Add mouse wheel event

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1150]
**Concisely describe the proposed feature**
Mouse wheel should also be recognized by GUI as an event.
This could help students to zoom in/out their rendering result. e.g. `fractal.py`.

**Describe the solution you'd like (if any)**
Add `WHEELUP` and `WHEELDOWN` to event keys.
IIRC it's `WM_MOUSESCROLLUP` for win32.

**Additional comments**
More info about event keys at https://taichi.rtfd.io/en/latest/gui.html.

**Comment by JYLeeLYJ** [comment]
1. WHEEL message on [win32](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-mousewheel) is ```WM_MOUSEWHEEL``` . As for x11 , it seems to be mapped to [mouse button 4 and 5 ](https://stackoverflow.com/questions/15510472/scrollwheel-event-in-x11).

2. Usually , there is an extra parameter in WHEEL message represents the delta value of scrolling motion . So we might need to add an new data member for key event struct in ```gui.h```. Or we ignore this value and just send ```UP``` and ```down``` message to python , which only depends on whether ```delta``` value is negative.

3. How about sperate mouse event from key event ,and add another interface for mouse to python frontend ? It might lead to more modification.

**Comment by archibate** [comment]
IMHO that would be not so easy to create another event queue..
Let's simply reuse `KeyEvent::pos.x` as `delta`, or use a union to represent?
Alternative solution: send `n` UP message when `delta = n`, and send `n` DOWN message when `delta = -n`, not sure how big `n` could be.

**Comment by JYLeeLYJ** [comment]
> Alternative solution: send `n` UP message when `delta = n`, and send `n` DOWN message when `delta = -n`, not sure how big `n` could be.

Unfortunately , it's a short type value on Win32 ...

> Let's simply reuse `KeyEvent::pos.x` as `delta`, or use a union to represent?

I think union or std::variant will be a general solution . Pybind11 does support to export these type automatically.

An possible modification:

```
  struct KeyEvent {
    enum class Type { move, press, release };
    Type type;
    std::string key;
    union {int delta ; Vector2i pos;}; // or getting more type-safety with std::variant<int,Vector2i> ; 
  };
```
Further more, we can individually export the whole ```KeyEvent``` struct like :
```
py::class_<KeyEvent>(m,KeyEvent)
      ...
      .def("get_key" , ...)
      .def("get_type", ...)
      .def("get_pos", ...)
      .def("get_delta", ...)
```
to replace some function of ```GUI``` in ```export_visual.cpp``` : 
```
      .def("get_key_event_head_key", &GUI::get_key_event_head_key)
      .def("get_key_event_head_type", &GUI::get_key_event_head_type)
      .def("get_key_event_head_pos", &GUI::get_key_event_head_pos)
```
Upper functions are only called in ```def get_key_event(self): ```  , in ```gui.py``` .
It's just a simple work to make a little refactoring . I‘d love to finish it , if u think these are acceptable.

**Comment by archibate** [comment]
Exporting `KeyEvent` SGTM! We can finally systematically remove the ad-hoc `get_key_event_head_**`.

> union {int delta ; Vector2i pos;}

Why not simply use `pos.x` as `delta`? IMHO it's acceptable since mouse wheel is just one of the events.
But feel free to use `struct {int delta ; Vector2i pos;}` if you find it hard to implement ;)

**Comment by JYLeeLYJ** [comment]
> Why not simply use `pos.x` as `delta`? IMHO it's acceptable since mouse wheel is just one of the events.
> But feel free to use `struct {int delta ; Vector2i pos;}` if you find it hard to implement ;)

Yeah...I have recognized that I was overly focusing on some less important points. I was just thinking about how to make it looks clear. Let's feel free to implement it . This might not matter.

It 's also feasible to reuse both two dimensions of ``` pos``` vector to denote this delta . So that it can support scrolling message in two directions (horizontal-y and vertical-x).

More over , if necessary , it 's also easy to map this event to ```WHEELUP``` ,```WHEELDOWN``` , ```WHEELEFT``` and ```WHEELRIGHT``` in application layer.
