### ISSUE TITLE
Support selecting GPU devices

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#1154]
**Concisely describe the proposed feature**

This came up from #1139, where it might be useful for the users to be able to choose which GPU device to run.

One thing to point out is that, while CUDA/Metal (or probably any major GPU APIs for that matter) can do this without much efforts, it might be a lot harder for OpenGL. According to @archibate , currently for the Nvidia OpenGL driver, we need to prepend `optirun` to the command to make it run on Nvidia GPU. Another way I found that could set this programmatically is to use [`WGL_NV_gpu_affinity`](https://www.khronos.org/registry/OpenGL/extensions/NV/WGL_NV_gpu_affinity.txt), which is a Nvidia specific extension.

**Describe the solution you'd like (if any)**

* Via an environment variable, `TI_GPU_DEVICE=1`
* Via `ti.init()`, e.g. `ti.init(device='gpu:0')`
* ...?

**Comment by bobcao3** [comment]
There's no API within OpenGL to select a device. mac OSdevices usually don't have the need for selecting a device (usually there's only one). Vulkan has added device selection support, and CUDA can use the system device selection environment variable.

**Comment by chenzhekl** [comment]
Does this imply there is no way to utilize multiple GPUs in a single Taichi program?
