### ISSUE TITLE
[workflow] enforce PR title format by GitHub Acions/workflows

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1159]
**Concisely describe the proposed feature**
As mentioned in #1153, I merged a PR without a tag by accident: `Fix "unclosed file" in "ti regression" (#1147)`.
It would be great if we could enforce PR to be tagged & first-word-uppercase by GitHub workflow.

**Describe the solution you'd like (if any)**
Add a job to `.github/workflow/persubmit.yml`. If someone is expert on GitHub Actions, please go ahead :)

**Additional comments**
About PR title rules, please see https://taichi.readthedocs.io/en/latest/contributor_guide.html#prtag

**Comment by yuanming-hu** [comment]
Great proposal. We should also enforce: if there are more than two tags, there should be exactly one space between different tags. E.g. `[Lang] [ir]`.

Note that the uppercase condition should only be enforced when the first character is a letter (a-z, A-Z).
