### ISSUE TITLE
[Math] Quaternions

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1167]
**Concisely describe the proposed feature**
Add quaternions and implement their arithmetic operations.

**Describe the solution you'd like (if any)**
Just a class with a structure similar to `Matrix`.

**Additional comments**
I'm working on this on my own since there are too many design decisions to be made.

In the future, it would be good to have a `Rotation`class that unifies 2D and 3D rotations.

**Comment by archibate** [comment]
Thank for purposing this, this requires a lo t of refactor in Matrix tbd. Sth for you to consider:
1. Will we have TaichiClass as a common base?
2. Will we have Complex?
3. Will we allow **user custom taichi class**?

**Comment by archibate** [comment]
I think we can start with `Complex` as a exercise. I'm working on refactoring now.

**Comment by archibate** [comment]
Does Quaternion or Complex multiply use `@` or `*`? If `*`, we abandon element wise multiply then?
FYI I just work out with taichi_glsl.Complex with taichi_glsl.TaichiClass. Maybe Quaternion should be put in the extension libraries too to prevent complicity.

**Comment by yuanming-hu** [comment]
After long consideration it seems to me that the easiest way to implement this is to implement a `ti.quaternion_multiply` function, that takes in two 4-D vectors and returns the quaternion multiplication. This allows us to reuse Vector add and sub. We may also need misc utils such as conversion between quaternion and rotation matrices. Closing this since everyone can easily do that on their own if they want.

If there is a clear need, we may consider include that into the standard math library.

**Comment by xuhao1** [comment]
> After long consideration it seems to me that the easiest way to implement this is to implement a `ti.quaternion_multiply` function, that takes in two 4-D vectors and returns the quaternion multiplication. This allows us to reuse Vector add and sub. We may also need misc utils such as conversion between quaternion and rotation matrices. Closing this since everyone can easily do that on their own if they want.
> 
> If there is a clear need, we may consider include that into the standard math library.

@yuanming-hu Is this still underdeveloped? I have written a small library for transformations on taichi on my own... (QuaternionInverse, QuaternionMatrix, QuaternionMultiply, etc...)

**Comment by yuanming-hu** [comment]
@neozhaoliang is working on the math utils - maybe you guys can chat and figure out a way to include quaternion operations?

**Comment by neozhaoliang** [comment]
@xuhao1
Hi, thank you for contributing new functionalities to Taichi. Yes having quaternion support in Taichi would be a nice feature. I saw your implementation, it should be [here](https://github.com/xuhao1/TaichiSLAM/blob/main/taichi_slam/taichi_transformations.py), right?
There is a situation we'd like to let you know of (and it's a good one): we are considering adding glsl-style vector support in a future release, with that you can use `vec4` for the quaternion type and write [multiplication between quaternions](https://github.com/xuhao1/TaichiSLAM/blob/main/taichi_slam/taichi_transformations.py#L45) as

```
p * q = vec4(p.x*q.x, cross(p.yzw, q.yzw))
``` 

That would simplify the code a lot :) So do you mind waiting for the coming release, maybe for a few weeks (hopefully~), and then we will inform you and invite you contributing your module?

**Comment by xuhao1** [comment]
@neozhaoliang OK, I will come back for it one week later.

**Comment by neozhaoliang** [comment]
@xuhao1 Hi, what do you think about adding `qmul`, `qconj`, `qdiv` functions under the module `math`?

**Comment by xuhao1** [comment]
@neozhaoliang OK~ I will do it later this week

**Comment by kurt-rhee** [comment]
@neozhaoliang @xuhao1 

How is the addition of quaternions to taichi?  I checked the math documentation and help(ti.math) and I didn't see anything in there.  If possible I would like to use your implementation instead of writing my own :)

**Comment by kurt-rhee** [comment]
https://github.com/taichi-dev/taichi/pull/7139/commits/019b343263583ef9b28213a430000359fe00a621

It looks like there is a quaternion implementation in one of the examples as well
