### ISSUE TITLE
[Doc] [GUI] improving the export_results doc and make imwrite have the same behavior with ti.GUI.show(filename)

### ISSUE THREAD

**Issue by Rullec** [taichi-dev/taichi#1176]
**Concisely describe the proposed feature**
As @archibate mentioned before, I want to improve the docs for these 2 points:
1. More explanations for the datatypes used in `ti.imwrite`, note that `ti.f32` can also be used to export images.
2. Add some examples which use `ti.Matrix` and `ti.Vector` with `ti.imwrite()`, so that our user's mind won't be restricted in `ti.var`

**Besides, I also find that in our newest release**, `ti.imwrite` is changed to:

https://github.com/taichi-dev/taichi/blob/43904488fdaca626178d45b467aba6989ebe5fe8/python/taichi/misc/image.py#L5-L20

In these codes above, we first assert:
`assert len(img.shape) in [2, 3], "Image must be either RGB/RGBA or greyscale"`

But If the length of `image.shape` is really two, our second assertation will fail by out-of-bounds accessing for `img.shape`:

`assert img.shape[2] in [1, 3, 4], "Image must be either RGB/RGBA or greyscale" `

Maybe I can help to fix it.

**A clear and concise description of what you want.**

1. I will add some more examples and explanations in export_result.rst and gui.rst

2. Maybe I can help to do some minor revision in `ti.imwrite`

**Describe the solution you'd like (if any)**
in image.py, change the code so that we only have the second assertation (mentioned above) when `len(img.shape) == 3`.

**Additional comments**
Nothing more.

**Comment by archibate** [comment]
My fault, thank for pointing out! Maybe we should move the assert to L26 and change `shape[2]` to `comp`? Sorry about not testing before merge... I think the ultimate solution is to add a test for this, there's already one in `test_image_io.py`, but not strong enough.

**Comment by Rullec** [comment]
Thanks a lot for such a quick reply!

This bug is sooo secret.If I am not doing some test in it, I can not find it as well.

I agree! A test should be added in case we together introduce something risky again. Do you think it's proper for me to create a Draft PR and show my modified and test code in it?

**Comment by archibate** [comment]
Oh! That would be great, but I've already added a test now, would you mind review it?

**Comment by Rullec** [comment]
Amazing efficiency! Certainly! So that I can only focus on the doc :D
