### ISSUE TITLE
[Lang] [refactor] dt or dtype for data type?

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1181]
**Proposal**

Currently we use `dt` for **data type** throughout the system. It may make sense to use `dtype` instead for consistency with `numpy`, `TensorFlow` and `PyTorch`.

Also, for simulation people `dt` may sounds like delta T (time step size). 

I suggest that we deprecate `dt` and use `dtype` in future releases.

Inputs are welcome.

**Comment by rexwangcc** [comment]
+1 to `dtype` to remove ambiguity.
