### ISSUE TITLE
[Misc] Ensure benchmarks and tests do not use more than 1GB memory

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1197]
**Concisely describe the proposed feature**
Currently, there are a few tests and benchmarks that use more than 1GB memory. Note that for people without unified memory or with limited GRAM, this could be too much.

**Describe the solution you'd like (if any)**
Simply reduce the memory usage.

**Additional comments**
For benchmarks, pay attention to running times after memory usage reduction. We don't want cases to be too fine-grained for accurate timing.

**Comment by archibate** [comment]
Done in #1213 .
