### ISSUE TITLE
[RFC] [Workflow] Regular release cycle

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1198]
Given now we have an increasing amount of users, it's important to release Taichi more frequently and more regularly so that new versions are out in time and in a predictable manner.

## Schedule

We should do two releases per week, one during the middle (~Wednesday) of a week, the other during the weekends.

## Versioning
Since we are still < 1.0.0, we can use minor version bumps for breaking API changes. For example, from 0.6.x to 0.7.0

## Version shepherd

The version shepherd will be in charge of releasing new versions.s

In the past, version releases are mainly done by @yuanming-hu and @archibate. During the GAMES 201, @FantasyVR (Peng Yu) kindly offered his help to release new versions.

TODO: 
 - [ ] @yuanming-hu should document version release workflow and ask @archibate to review.

**Comment by rexwangcc** [comment]
It seems to me that we are using [SemVar](https://semver.org/) as version tags but not in practice: each patch version (e.g. v0.x.y -> v0.x.y+1) contains a mixture of both breaking API changes and bug fixes. While this is totally pragmatic and practical in pre-v1 development, it might be practice strict SemVer based release process in this early stage. 

Having release candidates might also help  prevent introducing bugs (like the one I introduced recently 😿  ) in major releases.

**Comment by yuanming-hu** [comment]
> each patch version e.g. v0.x.y -> v0.x.y+1 always contains a mixture of both breaking API changes and bug fixes.

Yeah, that should be avoided... For v0.x, we should only use minor versions instead of patch versions for breaking changes.
