### ISSUE TITLE
[Perf] Comparing Taichi with Numba

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1206]
A zhihu user commented at https://zhuanlan.zhihu.com/p/145222094 shows that using `numba` is much faster than `taichi` on GPUs for my `calc_pi` example. Also it's heard that numba support CUDA at some degree too.
Not sure if this also apply to other applications. If we can reproduce this performance de-boost on other examples, then that may warn us that we may lose users go for `numba` for python-embbed parallel computation.
Lack of numba knowledges, I failed to make a numba version for `simple_uv.py`.
Here's a numpy-only version:
```py
import taichi as ti
import numpy as np

res = 1280, 720


def paint():
    a = np.linspace(0, 1, res[1])
    b = np.linspace(0, 1, res[0])
    a, b = np.meshgrid(a, b)
    c = np.zeros((*res, 1))
    a = a.reshape((*res, 1))# + c
    b = b.reshape((*res, 1))# + c
    return np.concatenate((a, b, c), axis=2)


gui = ti.GUI('UV', res)
while not gui.get_event(ti.GUI.ESCAPE):
    pixels = paint()
    gui.set_image(pixels)
    gui.show()

```
gets ~ 32 fps on my machine, while Taichi/x64 gets ~ 51 fps, Taichi/OpenGL gets ~ 34 fps (because of copying overhead).
For numba parallelization example, see https://github.com/numba/numba/issues/3336.
For numba docs, see http://numba.pydata.org/numba-doc/latest.
An article about numba: https://www.jianshu.com/p/69d9d7e37bc5.

**Comment by lvjiahui** [comment]
I am also curious about  the advantage of taichi compared to numba.
As far as I know, taichi supports sparse computation, which is common and useful in simulation. But for now most examples don't seem to use sparse computation.

**Comment by mzy2240** [comment]
Execution speed, which can be categorized into two classes: non-parallel and parallel. For non-parallel, it could be a sequence of matrix multiplication and manipulation. Many people use numba with numpy for further acceleration so this could be a typical usage. For parallel cases, one thing I could think of is Gaussian elimination where each branch could be solved in parallel based on the factorization/elimination tree. This might also relate to the sparse matrix feature.

**Comment by bobcao3** [comment]
Hi, taichi is a very different programming model & language, it is not a
language designed to express matrix operations, so this is not a comparison
we can make. In taichi you write the loops and operate on individual
elements of a matrix, instead of doing macro operations on entire matrices

**Comment by mzy2240** [comment]
Yeah gaussuan elimination is exactly the operation you mentioned that work on individual elements.

**Comment by bobcao3** [comment]
There is not really a way to compare two different libraries with entirely
different programming model. So, we have not done a systematic performance
comparison against numba
