### ISSUE TITLE
How to detect nan

### ISSUE THREAD

**Issue by lvjiahui** [taichi-dev/taichi#1223]
Is there something like NumPy's `np.isnan()` that can be used in taichi scope?
I can't find it in the document.
Thanks!

**Comment by archibate** [comment]
Thank for purposing this! I think a quick solution could be:
```py
import taichi as ti
import math

@ti.func
def isnan(x):
    return not (x < 0 or 0 < x or x == 0)

@ti.kernel
def func(a: ti.f32, b: ti.f32) -> ti.i32:
    return isnan(a / b)

print(func(0, 0))  # 1
print(func(1, 0))  # 0
print(func(0, 1))  # 0
```
Question: should we move this to `ti.isnan`?

**Comment by lvjiahui** [comment]
That is a celver method, thanks!
Also, sometimes we need to detect if there is nan in a tensor.

**Comment by archibate** [comment]
That's also easy, just `isnan(tensor[i])`.
I think non-fudemental utility functions like this and `clamp`, `step`, etc. may be included in https://github.com/taichi-dev/taichi_glsl instead of taichi main package?
