### ISSUE TITLE
Installation of Legacy Taichi Fails with GIL Error on Mac OS

### ISSUE THREAD

**Issue by pearlli98** [taichi-dev/taichi#1230]
**Describe the bug**
Following the instructions to install Legacy Taichi, the error **_Fatal Python error: PyMUTEX_LOCK(_PyRuntime.ceval.gil.mutex) failed_** always appears in the end and installation failed. 

**Log/Screenshots**
![Screen Shot 2020-06-12 at 2 39 34 PM](https://user-images.githubusercontent.com/55597907/84548489-8eecce80-acba-11ea-8d53-296642daf10b.png)

**To Reproduce**
I follow this instructions: 
wget https://raw.githubusercontent.com/yuanming-hu/taichi/legacy/install.py
python3 install.py

**Comment by k-ye** [comment]
Hi, Taichi legacy is no longer being maintained (for a long time)
