### ISSUE TITLE
[Lang] Unexpected getting stuck when Taichi is used in a class

### ISSUE THREAD

**Issue by Rullec** [taichi-dev/taichi#1234]
**Describe the bug**
Hi all,

I am a C++ guy and using Taichi 0.6.9 in developer mode with Ubuntu 18.04 LTS. Basically I quite love with the OOP opinion from my heart. 

So today I begin to **use Taichi in a class** under the help of our doc https://taichi.readthedocs.io/en/stable/odop.html?highlight=class#objective-data-oriented-programming
   
But later I found that, if I forget to add the decorator `@ti.kernel` in front of the definition of a method, ``ti.Matrix`` assignment will get stuck with NO WARNING and NO ERROR in all arches. This unexpected behavior exists on all `ti.cpu` `ti.cuda` and `ti.opengl`, in my own test.

I think at least Taichi should report errors if I do something wrong.How can I try to debug it?
**Log/Screenshots**
```
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-gz5cebrx
[Taichi] <dev mode>, supported archs: [cpu, cuda, opengl], commit badd0be8, python 3.6.10
[D 06/13/20 14:44:58.078] [snode.cpp:create_node@51] Non-power-of-two node size 3 promoted to 4.
[D 06/13/20 14:44:58.078] [snode.cpp:create_node@51] Non-power-of-two node size 3 promoted to 4.
Now the 0th assignment begins
```

**To Reproduce**
```
import taichi as ti

@ti.data_oriented
class Simulator:
    def __init__(self):
        self.M = ti.Matrix(2, 2, dt = ti.f32, shape = (3, 3))

    # @ti.kernel
    def try_to_set(self):
        m = ti.Matrix(2, 2, dt = ti.f32)
        for i in range(3):
            print(f"Now the {i}th assignment begins")
            self.M[i, i] = m
        

if __name__ == "__main__":
    # ti.init(arch=ti.cpu)
    # ti.init(arch=ti.cuda)
    ti.init(arch=ti.opengl)
    ti.set_logging_level(ti.TRACE)
    sim = Simulator()
    sim.try_to_set()
```

**Comment by archibate** [comment]
Does #1188 solve your problem?

**Comment by Rullec** [comment]
Thanks for you comment! :D

Yes, it is! I still can remeber that our doc demonstate the difference between `ti.Matrix` as a global tensor of Matrix and `ti.Matrix` used as a local temporary variable. And if I want a temproray matrix, I should not declare it as what I did.

Maybe I misunderstood your meaning?

If my understanding as listed above is not wrong, then I simply felt a little upset that maybe we should add a warning or error for it :( Because for beginners It is not very easy to distinguish these 2 stuff clearly all them time, it will lead them to confusion. Or at least we can add a waning in the doc.

**Comment by archibate** [comment]
Yes, the API here is really confusing here. That's why we introduced `ti.Matrix.var` for *tensor of matrices*. You're understanding correct.
