### ISSUE TITLE
Block::kernel isn't set correctly in the async computation

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#1243]
**Describe the bug**

`Block::kernel` isn't set correctly in the async computation. In the default mode, this works because the root block maps to a Taichi kernel, which has its kernel set. In the async mode, however, the root block maps to an offloaded task.

Other problems so far:

* [ ] fuse need to respect memory barrier implicitly established by the kernel boundary.
* [ ] constant folding??

**Comment by k-ye** [comment]
One thing I forgot to mention: We should probably be a bit more careful when using default args, e.g. https://github.com/taichi-dev/taichi/blob/24f683655d82c47f9ca152a8994a284358189ad2/taichi/ir/transforms.h#L37

I feel like this has somehow complicated the code flow when debugging these things.

**Comment by xumingkuan** [comment]
I wonder why we still need to pass these parameters given that we can get the `Kernel *` from an `IRNode *`...

**Comment by k-ye** [comment]
> I wonder why we still need to pass these parameters given that we can get the Kernel * from an IRNode *...

Well, this is probably added before we added `IRNode::get_kernel()`? But given that it's not working reliably...

**Comment by k-ye** [comment]
This particular bug is fixed by #1245..
