### ISSUE TITLE
Postpone backend detection

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1258]
**Concisely describe the proposed feature**
Currently, we detect backend compatibility at startup time:
```
[Taichi] version 0.6.10, supported archs: [cpu, cuda, opengl], commit 1402c4e5, python 3.6.9
```

This can lead to unpredictable crashes, especially when people don't have good OpenGL support. It is also a surprise to many uses since Taichi tries to create a window at start-up time.

We should postpone the backend compatibility detection during `ti.init`, so at least Taichi doesn't crash during `import taichi as ti`

**Describe the solution you'd like (if any)**
When people import Taichi, print all the backends that are **shipped** with the package, instead of those **locally supported** by the current machine.

We should detect the backends only when people are using `ti.gpu`.

We should also add a `ti.supported_backends()` that returns a list of supported backends.

During OpenGL backend detection, it is fine to create a window, but we should avoid crashes (due to lack of X11 environment or the latest OpenGL version).

**Comment by archibate** [comment]
> It is also a surprise to many uses since Taichi tries to create a window at start-up time.

LOL, thought it just remain for in ~0.1s on windows :) And this may make **Linux without X11 fail to start**? E.g. headless graphics server?

> We should postpone the backend compatibility detection during ti.init, so at least Taichi doesn't crash during import taichi as ti

Agree, this enable user to choose `ti.init(ti.cpu)` before crash. 
But what about the examples with `ti.init(ti.gpu)`? If `ti.gpu` they still have to detect cuda, opengl, metal one-by-one and cause segf, maybe the ultimate solution is to **catch that segf, and return false**, though catching fault signal in pybind11 is not so easy IIRC..

**Comment by k-ye** [comment]
I'm curious what exactly was the reason for the crash? Random guess, was it because for users who didn't install OpenGL at all, Taichi couldn't load the necessary `.so` at execution time, but still had to call some OpenGL function to detect availability?

**Comment by isdanni** [comment]
> I'm curious what exactly was the reason for the crash? Random guess, was it because for users who didn't install OpenGL at all, Taichi couldn't load the necessary `.so` at execution time, but still had to call some OpenGL function to detect availability?

I agree with the **complete lack** of OpenGL but not really sure abt the `x11` part; My system has OpenGL v.3 but no `x11` and I could run the testing examples fine(esp gpu ones);

**Comment by Rullec** [comment]
> And this may make **Linux without X11 fail to start**? E.g. headless graphics server?

Just now I try it by connecting to a Linux remotely via ssh without x11 forwarding. I think in this case x11 is unavaliable and taichi can handle it correctly, as a very basic test. :)
