### ISSUE TITLE
[Doc] add more details for debug utils and developer utils

### ISSUE THREAD

**Issue by Rullec** [taichi-dev/taichi#1269]
**Concisely describe the proposed feature**
Sometimes I felt a little hard to develop Taichi because Our "developer utils" is not as powerful as we imagine.

For example `ti.info` this function lacks a clear statement, which means a fresh developer cannot learn from the doc for utils he may need. 

And I realize that there are lots of functions that haven't been documented well, for example, `ti.ti_print`.

**A clear and concise description of what you want.**

I hope to consummate the "developer utils" parts such as for `ti.info`, add more details in it so that new developer can feel easier

I don't know whether `ti.ti_print()` has been deprecated or not. If not, I can add some details to it.

Also, I have realized that the backend of `ti.info` is [spdlog](https://github.com/gabime/spdlog). I am using it as well in my own project. spdlog should also support logging to a `.log` file, do we need to come up with a way to enable this feature in Taichi python-binding? 

If we want to use Taichi in a big project, logging to file should be essential. Btw, if this has been supported, I can add a doc for it as well.

***
2020/06/18 update:

So after a brief discussion with @archibate , I realize that:

1. `ti_ti_print` is not a developer util but debug util. 
2. Maybe we can try to add a new section for debug util, including but not limited to `ti_print`, `ti_static_print` and others about `profiler`
3. I hope to add more details for `ti.info` in Developer util.

HDYT?

**Comment by archibate** [comment]
In fact, `ti.ti_print` should never be directly used, but in generated code from our AST transformer:
https://github.com/taichi-dev/taichi/blob/master/python/taichi/lang/transformer.py#L548-L561

**Comment by Rullec** [comment]
It looks nice, thanks! I will learn more about this AST system.

Btw, are there still any other utils for debug purpose in out whole system?

**Comment by archibate** [comment]
Yes, `assert` for example. (btw, do we have `ti.static_assert`? that can be useful)

**Comment by Rullec** [comment]
It seems...we don't have it at this moment. :( I search for the whole code repo, no.

Where should be a proper place to implement `ti.static_assert`?

**Comment by archibate** [comment]
I think the same place as ti.static_print should be good enough.

**Comment by Rullec** [comment]
Good, Thanks!

**Comment by archibate** [comment]
What's the progress? You may open a PR in *draft state* to share progress :)

**Comment by Rullec** [comment]
I will return to my dormitory 1 hour later and publish this *draft PR* ;-)
