### ISSUE TITLE
[Opt] Let the constant folding pass support OffsetAndExtractBitsStmt

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#1278]
**Concisely describe the proposed feature**
If there's an `OffsetAndExtractBitsStmt` with `input` being a `ConstStmt`, we can do constant folding.

**Describe the solution you'd like (if any)**
Add a `visit` function in `constant_fold.cpp`.

**Additional comments**
We may need to modify `hash<taichi::lang::JITEvaluatorId>` to let it support the case of an `OffsetAndExtractBitsStmt`.

Or maybe we can just calculate `(input + offset) & (((1u << (bit_end - bit_begin)) - 1) << bit_begin)` without doing JIT compilation?

**Comment by yuanming-hu** [comment]
> Or maybe we can just calculate `(input + offset) & (((1u << (bit_end - bit_begin)) - 1) << bit_begin)` without doing JIT compilation?

Now I actually think this is better: we probably don't want to instantiate JIT evaluators for all (`offset`, `bit_end`, `bit_begin`) tuple. For now, `OffsetAndExtractBitsStmt` works only on `i32`, so it's easy to implement via a special-purpose evaluator without using JIT.

**Comment by xumingkuan** [comment]
> `(input + offset) & (((1u << (bit_end - bit_begin)) - 1) << bit_begin)`

(Maybe `(input + offset) & ((1ull << bit_end) - (1ull << bit_begin))` to handle the `bit_begin == 0 && bit_end == 32` case better?)

**Comment by yuanming-hu** [comment]
It's actually something like https://github.com/taichi-dev/taichi/blob/d2f782bcde6eab2b757c1fe03992333e9398258a/taichi/backends/opengl/codegen_opengl.cpp#L266-L270

(Note we need an extra `>>`)

Another thing that worths discussion: Should we use a simple `add` for offset, and let the instruction deal with `bit_extract` only?

**Comment by xumingkuan** [comment]
> **Another thing that worths discussion:** Should we use a simple `add` for offset, and let the instruction deal with `bit_extract` only? Then `OffsetAndExtractBitsStmt` should be refactored into `BitExtractStmt`.

Sounds good. I see `offset==0` in most cases of `OffsetAndExtractBitsStmt` in the IR...

**Comment by archibate** [comment]
Thank for the discussions above. So should I refactor `OffsetAndExtractBitsStmt` into `BinaryOpStmt` and `BitExtractStmt` now, or let @xumingkuan takes that?

**Comment by yuanming-hu** [comment]
I think @xumingkuan should do that in the next week and ask @archibate to review. The related changes in optimization passes are more non-trivial than that in backends.

**Comment by archibate** [comment]
Another reason for OAEBS => BOS + BES:
`(input + offset) & (((1u << (bit_end - bit_begin)) - 1) << bit_begin)`
What if  `bit_end` and `bit_begin` is constant while `input + offset` is not?

---
@xumingkuan Should I add a pass to demote OAEBS => BOS + BES or remove OAEBS from ir.h completely?

**Comment by xumingkuan** [comment]
I think we should remove OAEBS from ir.h completely -- just to confirm, is OAEBS only introduced during IR passes? (i.e. Initial IR never contains `OffsetAndExtractBitsStmt`?)

**Comment by xumingkuan** [comment]
What's the difference between `IntegerOffsetStmt` and `BinaryOpStmt` with `op_type` is `add` and `rhs` is a `ConstStmt`?

**Comment by xumingkuan** [comment]
I found the *only* place assigning `OffsetAndExtractBitsStmt::offset` to a non-zero value is
https://github.com/taichi-dev/taichi/blob/824c94b3416510a01655afd91fe4f9c7355084f8/taichi/transforms/simplify.cpp#L761
and it's *not* covered by our unit tests. Shall I replace it with an `IntegerOffsetStmt` or a `BinaryOpStmt`?

**Comment by yuanming-hu** [comment]
We can just replace it using a binary add. `IntegerOffsetStmt` should be gradually replaced by binary adds to keep the instruction set simple.
