### ISSUE TITLE
[ir] Make sure "StmtFieldManager" to be correct if we modify some fields after the ctor

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#1286]
Discussion from: https://github.com/taichi-dev/taichi/pull/1285#discussion_r443096881

Currently, we seem to copy some non-operand (non-`Stmt *`) fields in the `StmtFieldManager`. If we modify some of them after the constructor of a `Stmt`, `irpass::same_statements` may not be correct.

For example, if two `RangeForStmt`s are the same when they are constructed, but one of them toggles `RangeForStmt::reversed` later, will they be recognized as the same by `irpass::same_statements`?

**Comment by TH3CHARLie** [comment]
Sorry for the late response(I've been too busy last week). I've checked our current usage of `StmtFieldManager`, its `operator()` makes no use of the key(the field's name):
https://github.com/taichi-dev/taichi/blob/c58a262f04f47389f5f91c1a3b93251b26b7ec0a/taichi/ir/ir.h#L1312-L1313

I think we'd modify `StmtFieldManager` to a dictionary to store those k-v pairs, and modify them in every non-const method accordingly.

**Comment by xumingkuan** [comment]
Sorry for not clarifying -- I think `key` is not a problem. Although it's unused, the only case that need `StmtFieldManager`, i.e., `irpass::same_statements` don't need the `key`, because the order of `value` is deterministic for each class of statement.

Concretely speaking, `irpass::same_statements` calls
https://github.com/taichi-dev/taichi/blob/c58a262f04f47389f5f91c1a3b93251b26b7ec0a/taichi/analysis/same_statements.cpp#L102
which is
https://github.com/taichi-dev/taichi/blob/c58a262f04f47389f5f91c1a3b93251b26b7ec0a/taichi/ir/ir.cpp#L197
and we automatically check the order in the `for` loop.

----

The issue is, this line
https://github.com/taichi-dev/taichi/blob/c58a262f04f47389f5f91c1a3b93251b26b7ec0a/taichi/ir/ir.h#L1346
seems to **copy** the `value`. So if a numeric field (e.g. `bool RangeForStmt::reversed`) is modified after the constructor, I'm afraid that
https://github.com/taichi-dev/taichi/blob/c58a262f04f47389f5f91c1a3b93251b26b7ec0a/taichi/ir/ir.h#L424
of the corresponding `StmtFieldNumeric` wouldn't change.

So I think we should modify `StmtFieldManager::operator()` and `StmtFieldNumeric` to let it hold a pointer and check the real-time value when `equal` is called.

For this case which is hard to get a pointer
https://github.com/taichi-dev/taichi/blob/c58a262f04f47389f5f91c1a3b93251b26b7ec0a/taichi/ir/ir.h#L1318
, we don't need to worry about it because all `vector`'s sizes are unchanged after the constructors.

**Comment by TH3CHARLie** [comment]
I see. That actually makes things simpler than what I purposed/imagined.

**Comment by TH3CHARLie** [comment]
Sorry for the late response...I've submitted #1587 for this issue.

**Comment by xumingkuan** [comment]
Closing via #1587.
