### ISSUE TITLE
[misc] Show LLVM version on startup

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1287]
**Concisely describe the proposed feature**
Since we are now upgrading from LLVM 8.0.1 to LLVM 10.0.0, it would be good to show the LLVM version when Taichi starts. For example, the startup message could be
```
[Taichi] <dev mode>, supported archs: [...], commit b62337c9, LLVM 10.0.0, python 3.6.9
```

**Describe the solution you'd like (if any)**
Just export macros such as `LLVM_VERSION_MAJOR` using pybind11. E.g., see `get_version_major`:
https://github.com/taichi-dev/taichi/blob/a4933395f994baf3b33ec68eb45ad3f7ba9f0272/taichi/python/export_lang.cpp#L536

**Comment by archibate** [comment]
I think the start up could become too long now...
Maybe we should use a separate command `ti diagnose` to show valuable system information including but not limited to:
- supported archs (which is removed from startup message in #1273)
- LLVM version (this issue)
- CUDA version (if available)
- NVIDIA card version (unified memory support? @yuanming-hu)
- OpenGL version & vendor (@archibate)
- OpenGL extensions available (@archibate)
- Metal API version (@k-ye)
- OS dist: Ubuntu, Arch Linux, Win 10 Professional (#1162), Mac OS X 10.11 (#1161)

**Comment by yuanming-hu** [comment]
> I think the start up could become too long now...
> Maybe we should use a separate command `ti diagnose` to show valuable system information including but not limited to:
> 
> * supported archs (which is removed from startup message in #1273)
> * LLVM version (this issue)
> * CUDA version (if available)
> * NVIDIA card version (unified memory support? @yuanming-hu)
> * OpenGL version & vendor (@archibate)
> * OpenGL extensions available (@archibate)
> * Metal API version (@k-ye)
> * OS dist: Ubuntu, Arch Linux, Win 10 Professional (#1162), Mac OS X 10.11 (#1161)

That's a good point. I think we can show all info that does not need run-time detection in the startup message. Yes, it may seem a bit too long, but it helps us diagnose bug reports much easier (note that it's hard to ask users run `ti diagnose` before they raise bug reports... We'd better print the info by default.)

**Comment by archibate** [comment]
But wasn't LLVM version always 10.1 in release mode since it's built-in from CI?

**Comment by yuanming-hu** [comment]
> But wasn't LLVM version always 10.1 in release mode since it's built-in from CI?

Currently we support both llvm 8.0.1 and llvm 10.0.0. 

Jenkins (Linux) uses llvm 10.0.0 and other buildbots use 8.0.1.
