### ISSUE TITLE
Document python interfaces

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#131]

**Comment by mirlip** [comment]
Hi,
to make the first steps easier for new comers like me, I think it would be good to have 3 good examples of how to visualize with:
- QT integrated viewer
- output to images or 3d-formats (png and obj for example) to disk
- output to numpy arrays to import the data in your prefered 3D package (Houdini, Blender, etc...)

Also having the images on your website/github to point to the according .py in the example folder would help quickly finding the right example for what people want to learn.

**Comment by yuanming-hu** [comment]
All good suggestions! I agree that dealing with outputs and finding the right examples are the biggest current issues :-)
