### ISSUE TITLE
taichi version 0.6.12 requires libm.so: version `GLIBC_2.27' which is unavailable on Ubuntu 16.04

### ISSUE THREAD

**Issue by jobesu14** [taichi-dev/taichi#1313]
After upgrading taichi to version 0.6.12 through  `pip install --upgrade taichi` on my Ubuntu 16.04 machine, I got the following error:

```
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /xxxxx/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so)
```

I looked a bit and apparently Ubuntu 16.04 supports glibc 2.23 only (see https://launchpad.net/ubuntu/xenial/+source/glibc).

Reverting to the previous version (`pip install --upgrade==0.6.11`) fixed the issue.

Do you still officially support Ubuntu 16.04?

**Comment by yuanming-hu** [comment]
Thanks for reporting. I took a look, and it seems that 
```
>>> objdump -T libtaichi_core.so| grep  GLIBC_2.27
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.27  log2f
```

It's probably a commit between v0.6.12 and v0.6.11 that uses `log2f` (directly or indirectly.)

**Comment by archibate** [comment]
Yes, I'm using LLVM 8. Didn't find any entry about either `GLIB_2.27` and `log2f`:
```
(depshapedimcall) [bate@archit taichi]$ objdump -T build/libtaichi_core.so | grep GLIBC_2.27
(depshapedimcall) [bate@archit taichi]$ objdump -T build/libtaichi_core.so | grep log2f
(depshapedimcall) [bate@archit taichi]$ 
```

**Comment by bobcao3** [comment]
A new cpu/cuda wheel has been added that should work on Ubuntu 16.04
