### ISSUE TITLE
[Bug] [IR] SSA is violated when assigning to ti.Matrix

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#1349]
**Describe the bug**

I've uncovered yet another bug when debugging https://github.com/taichi-dev/taichi/pull/1188#issuecomment-649510574.

Repro case:

```py
import taichi as ti

ti.init(arch=ti.x64, print_ir=True)

@ti.kernel
def foo():
  a = ti.Vector([1.0, 1.0])
  a = a.normalized()
  print(a)

foo()
```

This produces the following Frontend IR:

```
kernel {
  $0 = alloca @tmp0  <-- s1
  @tmp0 = 1.0
  $2 = alloca @tmp1
  @tmp1 = 1.0
  @tmp0 = ((1  ((sqrt (((@tmp0 pow 2) + (@tmp1 pow 2)) + 0)) + 0)) * @tmp0)  <-- s2
  @tmp1 = ((1  ((sqrt (((@tmp0 pow 2) + (@tmp1 pow 2)) + 0)) + 0)) * @tmp1)  <-- s3
  $6 = eval @tmp0
  $7 = eval @tmp1
  print "[", %6, ", ", %7, "]"
}
```

Pay close attention to `@tmp0`. It is a local variable (`s1`). `s2` reads `@tmp0` to compute the normalized x component, then **assigns it back to** `@tmp0`. In `s3`, it reads `@tmp0` again. But what it really should read is `1.0`.

As a result, the printed value is actually `[0.707107, 0.816497]`. Boom..!

I've tweaked `cornell_box.py` here https://github.com/taichi-dev/taichi/blob/c83a7e3df91019d035705ea1068a84f177e97a76/examples/cornell_box.py#L408-L415 by giving the initial `ray_dir` another name, e.g. `ray_dir_init`. The problem now went away at `HEAD`.

However, this is just a workaround, and we should have a real fix here.

While #1329  remains a problem, I don't think it directly contributed to the issue here. It seems to me that this has been a problem for a while, then #1188 exposed it by re-computing the `norm` for each component. That is,

* Before #1188, the denominator `1.0 / sqrt(x**2 + y**2 + ...)` was computed once, then re-used to normalize `x`, `y`, etc
* After that, for every component `x`, `y`, ..., the denominator was computed repeatedly.

**Log/Screenshots**

Rendering result looks good after renaming the variable to `ray_dir_init`:

<img width="912" alt="Screen Shot 2020-06-28 at 15 41 29" src="https://user-images.githubusercontent.com/7481356/85940188-e09d8600-b955-11ea-99a6-4b8a4d6789d9.png">

**Comment by k-ye** [comment]
@yuanming-hu @xumingkuan @archibate PTAL..

**Comment by k-ye** [comment]
FYI, changing `norm_sqr()` here https://github.com/taichi-dev/taichi/blob/c83a7e3df91019d035705ea1068a84f177e97a76/python/taichi/lang/matrix.py#L550-L551

to

```py
def norm_sqr(self):
    tmp = self.copy()
    return (tmp**2).sum()
```

**didn't** work. IIUC, `self.copy()` is still not a deepcopy. And we probably cannot even do a deepcopy inside Python, because it requires modifying the AST.

**Comment by archibate** [comment]
Does #1338 solve your problem?

**Comment by k-ye** [comment]
> Does #1338 solve your problem?

Yes, I'm writing some feedback on it.


I feel like this is just another symptom of #1329 , closing...
