### ISSUE TITLE
Can this library support double buffer

### ISSUE THREAD

**Issue by liyou54** [taichi-dev/taichi#1361]
**Concisely describe the proposed feature**
A clear and concise description of what you want. For example, 
> I would like to add an Apple Metal backend to the compiler so that my Macbook GPU can be utilized.

**Describe the solution you'd like (if any)**
A clear and concise description of what you want to achieve and implement.

**Additional comments**

**Comment by archibate** [comment]
Sorry, I didn't get the point, what does double buffer mean, double GUI display buffer or double tensor? Could you provide some details about this topic?
