### ISSUE TITLE
[example] Where are the equations of mpm128.py derived from?

### ISSUE THREAD

**Issue by j20232** [taichi-dev/taichi#1363]
Hi, I have a question about examples.

I don't understand codes of  [mpm128.py](https://github.com/taichi-dev/taichi/blob/master/examples/mpm128.py) from line 57 to line 65 .

```py
57  stress = 2 * mu * (F[p] - U @ V.T()) @ F[p].T() + ti.Matrix.identity(ti.f32, 2) * la * J * (J - 1)
58  stress = (-dt * p_vol * 4 * inv_dx * inv_dx) * stress
59  affine = stress + p_mass * C[p]
60  for i, j in ti.static(ti.ndrange(3, 3)): # Loop over 3x3 grid node neighborhood
61      offset = ti.Vector([i, j])
62      dpos = (offset.cast(float) - fx) * dx
63      weight = w[i][0] * w[j][1]
64      grid_v[base + offset] += weight * (p_mass * v[p] + affine @ dpos)
65      grid_m[base + offset] += weight * p_mass
```

Line 57 may come from derivatives of equation (5) of [[Stomakhin et al. TOG 2013](https://dl.acm.org/doi/abs/10.1145/2461912.2461948)] and Line 58 may come from [[Hu et al. TOG 2018](https://dl.acm.org/doi/10.1145/3197517.3201293)] ($Q_{p}$ written at *Algorithmic improvement* of **6 A HIGH PERFORMANCE IMPLEMENTATION**).

However, it's a bit unclear that  what `4 * inv_dx * inv_dx` and the loop part mean.

Could you tell me references and add comments  to the example?

**Comment by yuanming-hu** [comment]
Hi @j20232,

That's from `D` in the APIC paper: https://www.math.ucla.edu/~jteran/papers/JSSTS15.pdf section 5.3.

**Comment by j20232** [comment]
Thank you for your kindness!
Do you mean the loop part(L60-L65) is also derived from the `D`?

**Comment by j20232** [comment]
Oh! I've understood it!
The loop part is from equation (8) in the APIC paper!
Thank you!
