### ISSUE TITLE
PyPI support

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#14]
It would be great if users can install Taichi just by 
```
pip install taichi
```

Actually I had a try days ago but it's interesting that I can only package the *.py files in `taichi/python/`, even if I added the rest to MANIFEST.in.

If you have any idea on what's going on, please let me know.
Thanks!

**Comment by IteratorAdvance** [comment]
For users who do not want to build from scratch, we will also need wheels for releasing binary. If we can fetch binaries from Travis CI and submit them as wheels, that would be helpful.

**Comment by yuanming-hu** [comment]
I removed the dependency on boost, thus currently major labor on this topic is to ship `embree`, `tbb` and maybe `ffmpeg` binary along with wheels.
