### ISSUE TITLE
"mpm_lagrangian_forces.py" giving different results

### ISSUE THREAD

**Issue by squarefk** [taichi-dev/taichi#1408]
Example **mpm_lagrangian_forces.py** is giving visually different results on my MacBook (Retina, 12-inch, 2017).

![image](https://user-images.githubusercontent.com/9163305/86521933-b7cd3300-be24-11ea-9370-ad99a539e196.png)

![image](https://user-images.githubusercontent.com/9163305/86521936-c0256e00-be24-11ea-9b4f-15c0ca6655c6.png)

**Comment by yuanming-hu** [comment]
HI @squarefk, 

Welcome back! What if you run with `arch=ti.cpu`?

**Comment by k-ye** [comment]
This was a symptom of #1329. `v0.6.16` should contain the fix #1338 by @archibate  now..

**Comment by squarefk** [comment]
> HI @squarefk,
> 
> Welcome back! What if you run with `arch=ti.cpu`?

It was run with arch=ti.cpu.

**Comment by yuanming-hu** [comment]
Have you tried v0.6.16?

**Comment by squarefk** [comment]
> Have you tried v0.6.16?

It is fixed by v0.6.16. Thx!
