### ISSUE TITLE
Cant execute same cell in jupyter Notebook

### ISSUE THREAD

**Issue by tyoc213** [taichi-dev/taichi#1445]
AssertionError: No new variables can be declared after kernel invocations or Python-scope tensor accesses.

**To Reproduce**

In a cell execute two times this:

```
import taichi as ti

res = 1280, 720
pixels = ti.Vector(3, dt=ti.f32, shape=res)


@ti.kernel
def paint():
    for i, j in pixels:
        u = i / res[0]
        v = j / res[1]
        pixels[i, j] = [u, v, 0]
paint()
```
Firs time it runs without error, second time it prints this

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
 in 
      2 
      3 res = 1280, 720
----> 4 pixels = ti.Vector(3, dt=ti.f32, shape=res)
      5 
      6 

~/miniconda3/envs/fastai2/lib/python3.7/site-packages/taichi/lang/matrix.py in Vector(n, dt, shape, offset, **kwargs)
    806 
    807 def Vector(n, dt=None, shape=None, offset=None, **kwargs):
--> 808     return Matrix(n, 1, dt=dt, shape=shape, offset=offset, **kwargs)
    809 
    810 

~/miniconda3/envs/fastai2/lib/python3.7/site-packages/taichi/lang/matrix.py in __init__(self, n, m, dt, shape, offset, empty, layout, needs_grad, keep_raw, rows, cols)
     87                 assert not impl.inside_kernel()
     88                 for i in range(n * m):
---> 89                     self.entries.append(impl.var(dt))
     90                 self.grad = self.make_grad()
     91 

~/miniconda3/envs/fastai2/lib/python3.7/site-packages/taichi/lang/util.py in wrapped(*args, **kwargs)
    210         assert in_python_scope(), \
    211                 f'{func.__name__} cannot be called in Taichi-scope'
--> 212         return func(*args, **kwargs)
    213 
    214     return wrapped

~/miniconda3/envs/fastai2/lib/python3.7/site-packages/taichi/lang/impl.py in var(dt, shape, offset, needs_grad)
    281 
    282     assert not get_runtime(
--> 283     ).materialized, 'No new variables can be declared after kernel invocations or Python-scope tensor accesses.'
    284 
    285     # primal

AssertionError: No new variables can be declared after kernel invocations or Python-scope tensor accesses.
```

`taichi.__version__` (0, 6, 14)

**Comment by archibate** [comment]
Does adding
```py
ti.init()
```
right below `import taichi as ti` solve the problem?

**Comment by tyoc213** [comment]
Indeed it does, thought I need to re execute cells, it works.

Also if I try to `%%timeit` even if include `ti.init` and the function of "gray scale" https://github.com/tyoc213/blog/blob/master/__explorations__/taichi%20as%20img%20manipulation.ipynb it will be unable to find source code

What Im trying to do is test if feasible to use taichi for do some random modifications on images, but at less as Im doing it right now, it seems that the use case I have in mind will be slower than other ways? (just from the %time output at the bottom of the notebook)

**Comment by archibate** [comment]
I'm not surprised about the result.
First of all, simple kernels (~10 ms) could have more launch overhead than computation time.
Second, PIL is a professional package that aims on image processing and many optimizations could be done there.
I see that you're using `r * 0.2989 + g * 0.5870 + b * 0.1140` for creating gray scale, but in fact there's many more efficient way that does not involve `*` like `tab_r[r] + tab_g[g] + tab_b[b]`. I believe PIL has done such optimizations too.

**Comment by bobcao3** [comment]
This might be running on the CPU back end? I don't think our CPU backend has yet restored vectorization, so it's very possible that it's slower. However if you run it with the GPU backend it should be better. Closing this issue for now, seems to be a known problem
