### ISSUE TITLE
[Doc] typo

### ISSUE THREAD

**Issue by albine** [taichi-dev/taichi#1452]
I found a possible typo on page [](https://taichi.readthedocs.io/en/stable/syntax.html) when reading the document:
"kernels do support..."
could it be "kernels do not support..."?

**Comment by archibate** [comment]
Thank for your report, but which file is the typo occurred?
Would you open a pull request by editing files [here](https://github.com/taichi-dev/taichi/tree/master/docs)? Thanks :)
