### ISSUE TITLE
安装taichi时，出现error

### ISSUE THREAD

**Issue by cwh12355** [taichi-dev/taichi#1457]
C:\Users\xinqidian123>pip install taichi
Collecting taichi
  Using cached taichi-0.6.17-cp38-cp38-win_amd64.whl (19.6 MB)
Requirement already satisfied: setuptools in d:\lib\site-packages (from taichi) (41.2.0)
ERROR: Could not find a version that satisfies the requirement pytest (from taichi) (from versions: none)
ERROR: No matching distribution found for pytest (from taichi)

**Comment by archibate** [comment]
Thank for reporting. The error message looks strange... why pytest doesn't satisfy the version... maybe we should try this?
```py
pip uninstall pytest
pip uninstall taichi
pip uninstall pytest # sometimes pip needs uninstall twice to make it really removed from disk
pip uninstall taichi
pip install taichi==0.6.17
pip install pytest
pip install taichi==0.6.17
```

**Comment by k-ye** [comment]
Which python version are you using?

**Comment by archibate** [comment]
> Which python version are you using?

> taichi-0.6.17-cp38-cp38-win_amd64.whl

So, 3.8, I guess.
