### ISSUE TITLE
[Refactor] Simplify testing parameterization

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1458]
**Concisely describe the motivation**
Currently tests often have many layers of decorators. For example,

```python
@ti.require(ti.extension.assertion)
@ti.all_archs_with(debug=True)
@ti.must_throw(RuntimeError)
def test_assert_minimal():
    ti.set_gdb_trigger(False)
    
    @ti.kernel
    def func():
        assert 0

    func()
```
In practice, it's really hard to arrange the decorators in the correct order. Actually, the order shown above doesn't work correctly. The current implementation is not easy to debug.
 
The combination itself is limited. For example, there is `all_archs_with(debug=True)` but there is no `host_arch_with`.

**Describe the solution you'd like (if any)**
It would be good to have a unified `ti.test` decorator so that the above test can be written as

```python
@ti.test(archs=all, require=ti.extension.assertion, debug=True, gdb_trigger=False, must_throw=RuntimeError)
def test_assert_minimal():    
    @ti.kernel
    def func():
        assert 0

    func()
```

**Additional comments**
The current `ti.test` function should probably be renamed or removed.

This design should be thoroughly discussed before implementation.

**Comment by archibate** [comment]
Agree...

Just FYI, we don't need `@ti.must_throw(RuntimeError)` at all, the [`pytest.raises`](https://www.programcreek.com/python/example/81446/pytest.raises) can do that as well:
```py
@ti.require(ti.extension.assertion)
@ti.all_archs_with(debug=True, gdb_trigger=False)
def test_assert_minimal():
    @ti.kernel
    def func():
        assert 0

    with pytest.raises(RuntimeError):
      func()
```

**Comment by yuanming-hu** [comment]
> the [`pytest.raises`](https://www.programcreek.com/python/example/81446/pytest.raises) can do that as well:

Cool, that works. Thanks. The refactoring is still needed IMHO.

**Comment by archibate** [comment]
Also FYI: [`pytest.fixture`](https://docs.pytest.org/en/latest/fixture.html#usefixtures) can do the work of `ti.all_archs_with` and `ti.require` as well...
`pytest` is really a professional package in test, we should learn how to make use of it, instead of writing our ad-hoc decorators.
I believe all the problems we encounter here could be already meet by **many other python people** and `pytest` have systematically solutions for them, WDYT :)

**Comment by archibate** [comment]
In fact, if we make use of `pytest.fixture`, we can figure out which arch failed test. e.g.:

Before:
```
python/taichi/misc/test.py::test_this PASSED
python/taichi/misc/test.py::test_that FAILED  # Well... but which arch??
```
After:
```
python/taichi/misc/test.py::test_this[x64] PASSED
python/taichi/misc/test.py::test_that[x64] PASSED
python/taichi/misc/test.py::test_this[opengl] PASSED
python/taichi/misc/test.py::test_that[opengl] FAILED  # Oh! It's only OpenGL's fault!
```

**Comment by archibate** [comment]
Hi! @Rullec, the infrastructure is quite complete here. It's time to change the `@ti.all_archs` to `@ti.test(...)`! Would you like help me? We may use the same workflow as `rullec-field` did. For documentation about `@ti.test(...)`, see #1475.

**Comment by Rullec** [comment]
Nice, I would be happy to try this one. Thanks for your recommendation.

**Comment by archibate** [comment]
## What files to replace:
Please do replacement in `tests/python/test_XXX.py`.
Open PR one by one, e.g.: `[test] Replace to @ti.test decorator for tests starting with [a-c]`.

## What decorator to replace:
```py
@ti.all_archs
```
```py
@ti.test()
```
---
```py
@ti.all_archs_excluding(ti.opengl)
```
```py
@ti.test(exclude=ti.opengl)
# or equivalently: @ti.test(exclude=[ti.opengl])
```
---
```py
@ti.all_archs
@ti.require(ti.extension.data64)
```
```py
@ti.test(require=ti.extension.data64)
```

## What function to replace:
```py
@ti.all_archs
def test_XXX():  # all functions starting with `test_`, please replace me!
```
---
```py
@ti.all_archs
def _test_XXX():  # if starting with `_test`, don't replace, let @archibate fix these non-trivial ones
```
---
```py
@ti.all_archs
def some_other_even_strange_name_XXX():  # don't replace, let @archibate fix these non-trivial ones
```

**Comment by Rullec** [comment]
Thanks! I have been familiared with this workflow. 

Please give me some more time to investigate them carefully and have some PRs!

**Comment by yuanming-hu** [comment]
> Since tests are invisible to end-users, **we're OK to directly merge these PRs into `master`**, no `rullec-test` required, WDYT?

We should directly merge into `master`. It's fine if we use multiple PRs for the replacement.
