### ISSUE TITLE
[Bug] outer_product() get automatically truncated from v0.6.16

### ISSUE THREAD

**Issue by gmh14** [taichi-dev/taichi#1460]
From v0.6.16, the `outer_product()` operation will automatically truncate the output tensor. See results below,

![Screenshot 2020-07-11 at 14 37 57](https://user-images.githubusercontent.com/22349205/87218337-45a8a100-c384-11ea-8ab1-18b7a4f178bd.png)

The result should be `[[4.,  5.], [8., 10.], [12., 15.]]` in this case. I have also tested it on v0.6.17, and the problem still exists.

I am not sure if it is a proper change of the default behavior of `outer_product()`. Please check it out if it is an unintended bug. Thanks!

**Comment by archibate** [comment]
Thank for the patient test! I'm working on this right now..

**Comment by gmh14** [comment]
Thanks for your swift response! Seems that is the reason!
