### ISSUE TITLE
[Lang] [refactor] Implement "field" for Taichi tensors and variables

### ISSUE THREAD

**Issue by Rullec** [taichi-dev/taichi#1501]
It seems we have decided a new variables' naming rule in #1156 .

In order to track the progress and help us have a clear mind, I try to build a possible roadmap for what we need to do now. @yuanming-hu

# 1. Introduction about our new allocating API
The new naming mechanism can be formulated in these 3 rules:
- use ``ti.field(dtype, ...)`` to allocate a **global scalar**  field (tensors)
- use ``ti.Vector.field``/``ti.Matrix.field`` to allocate **global vector/matrix** fields (tensors)
- use `ti.Vector` and `ti.Matrix` for **local** variable

In one word, anything **involved in the name ``field``** must be a **global** stuff, and all others must be some **local** things.
The difference between old and new names are exposed below, in the following working plan.

# 2. Working plan

## 2.1 Support new interfaces
- [ ] Support `ti.field` to replace our old `ti.var`. Note that it can only be used for allocating **global scalar** fields.
- [ ] Support `ti.Vector.field` and `ti.Matrix.field`. They can only be usded for **global vector/matrix** fields.
- [ ] Support `ti.Vector` and `ti.Matrix` which can only be used for **local vector/matrix** variables
>  They have no `field` keywords, so these two `ti.Vector`  and `ti.Matrix` are local stuff.

## 2.2 Deprecate old interfaces
- [ ] deprecate ``ti.var`` for global vars
- [ ] deprecate `ti.Vector` and `ti.Matrix` usage for global stuff.

## 2.3 Add test for new interfaces
- [ ] test `ti.var` can not be used in any cases
- [ ] test `ti.field`, `ti.Vector.field` `ti.Matrix.field` can allocate global fileds
- [ ] test `ti.field`, `ti.Vector.field` and `ti.Matrix` are forbidden from being used in local scope.
- [ ] test `ti.Vector` and `ti.Matrix` can work for allocating local variables
- [ ] test `ti.Vector` and `ti.Matrix` are prohibted in global allocating work.

## 2.4 update our code examples
- [ ] update our codes in ``examples/`` and `tests/`

## 2.5 update the document
- [ ] rewrite the `API Interface` part in our [doc](https://taichi.readthedocs.io/en/stable/scalar_tensor.html)
- [ ] convert all examples in our document to new naming mechanism
- [ ] test all examples in doc. We should gurantee the offical examples is absolutely correct.

***
This plan is far from perfect, please feel free to add/delete items in this working plan :-)

**Comment by Rullec** [comment]
I believe that our @archibate can have a strong interset in this issue. :) Can I work together with you?

**Comment by archibate** [comment]
Oops! Duplicate #1500!

> Can I work together with you?

Of course!

**Comment by Rullec** [comment]
> Oops! Duplicate #1500!
> 
> > Can I work together with you?
> 
> Of course!

I will remove this issue after your response in 1501 :)

**Comment by Rullec** [comment]
Close for duplication
