### ISSUE TITLE
euler.py problem

### ISSUE THREAD

**Issue by CathKan** [taichi-dev/taichi#1524]
Hello, I may found some issue in euler.py file. After I copy pasted the code from webpage to my PyCharm, there are some places that cannot run properly, I am not very skillful to fix them my self, the error displayed is shown in the attached screenshot~ I do not quite understand how should the lines indented. Hope some one can help, I'd like to take a look at what visual effect this code simulates~ Thank you in advance!!

![Screenshot (132)](https://user-images.githubusercontent.com/68445924/87829681-82c1d700-c84d-11ea-9be6-4cf9758089ce.png)
![Screenshot (133)](https://user-images.githubusercontent.com/68445924/87829810-c3215500-c84d-11ea-95be-d853c662a984.png)

**Comment by archibate** [comment]
Hi, copy and paste from website will result in an extra newline between two lines so indents will be broken.
Please try copy from the raw content: https://raw.githubusercontent.com/taichi-dev/taichi/master/examples/euler.py
Or run this command in your shell: `python3 -m taichi example -s euler`.
