### ISSUE TITLE
Questions about mpm_lagrangianForce.py

### ISSUE THREAD

**Issue by CathKan** [taichi-dev/taichi#1549]
Hello,

I do not quite understand the logic behind this particle to grid and grid to particle functions, how these statement motivate the final animation effect? Hope someone can illustrate~ Also, I think the key point is that what is the tensor of matrices, C, defined as?

For n_element definition, I want to confirm that, the logic behind it assignment is that most vertices needed to be counted twice while building the mesh?

Thanks in advance!

![Screenshot (134)](https://user-images.githubusercontent.com/68445924/87998712-af345800-cac6-11ea-9ea1-fa376fdd43d7.png)

**Comment by tlow22** [comment]
@KathCan You may have gotten this answered yourself in your studies by now. The animation effect is really obtained by tracking the particle movements. What you're asking relates more to the calculation stages of the Material Point Method (MPM). 

MPM methods differ from other meshless/particle methods like SPH in that the calculations are not directly on the particles, but use an underlying grid as a sketchpad for performing those calculations. In other words, 

1) transfer quantities from particles-to-grid
2) perform calculations on grid
3) transfer quantities from grid-to-particle
4) move particles based of newly calculated quantities (advection step) 

C is an "affine matrix" that was discovered a while back to reduce the artificial/numerical dissipation of the movement of particles when describing fluid movement. It's "affine" in that it's an addition term to the original m*v momentum term. This is a simplified description, there's more to it from a continuum mechanics point of view.
