### ISSUE TITLE
Bug in summation for a 3D tensor

### ISSUE THREAD

**Issue by xu-xianghua** [taichi-dev/taichi#1555]
**Describe the bug**
When I sum a 3D dense tensor, an error result is got using GPU, while the result is correct using CPU. And no error occur for a 2D tensor.

**To Reproduce**

```
import taichi as ti

real = ti.f32
ti.init(arch=ti.gpu)

N = 100
T = ti.var(dt=real, shape=(N,N,N))
sum = ti.var(dt=real,shape=())
cnt = ti.var(dt=ti.i32,shape=())

@ti.kernel
def init(T0: real):
    for I in ti.grouped(T):
       T[I] = T0

@ti.kernel
def reduce():
    sum[None] = 0.
    cnt[None] = 0
    for I in ti.grouped(T):
        sum[None] += T[I]
        cnt[None] +=1

init(100)
reduce()
Tm = sum[None] / (N**3)
print(f'Tmean={Tm}, sum={sum[None]}, count={cnt[None]}') 
```

**Log/Screenshots**

Output:
```
[Taichi] mode=release
[Taichi] version 0.6.20, llvm 10.0.0, commit cc621a0c, python 3.7.6
[Taichi] Starting on arch=cuda
Tmean=99.947872, sum=99947872.0, count=1000000
```
Tmean should be 100, sum should be 100000000, and count is correct.

The result using CPU is correct.
```

[Taichi] mode=release
[Taichi] version 0.6.20, llvm 10.0.0, commit cc621a0c, python 3.7.6
[Taichi] Starting on arch=x64
Tmean=100.0, sum=100000000.0, count=1000000

```

GPU is 2080 ti, and nvidia-smi info:
```
Wed Jul 22 00:37:09 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 28%   36C    P8     2W / 260W |   1104MiB / 11016MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by archibate** [comment]
I can reproduce this. This could be due to the precision of floating-point operation on GPU is not so precise as the CPU one does... Users could use `i32` for these large integers or `f64` for large floats. (@yuanming-hu Maybe this is related to the recent added TLS?)

**Comment by yuanming-hu** [comment]
Thanks for the very well-written report. this is likely a float-point error instead of a bug in Taichi. Do you face the same issue when you use `real = ti.i32`?

**Comment by xu-xianghua** [comment]
Thanks. It really looks like a float-point error. When I change type to ti.i32, ti.f64, or enven only change sum to ti.f64, the result is correct. 

And the dimension is irrelevant, when size is large enough(699963 for the case), sum has a error for 1D tensor.
