### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [taichi-dev/taichi#156]
Would you like to [replace any double quotes](https://github.com/yuanming-hu/taichi/blob/e6e4bcdc09f3ec7ea5d6486d805eba25a2535122/include/taichi/taichi#L6 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by yuanming-hu** [comment]
Thanks for the advice. I would like to keep double quotes there since they search files using relative paths and thereby simplify factoring folder structures.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by yuanming-hu** [comment]
So the options here are 
```
#include <taichi/common/util.h>
```
and
```
#include "common/util.h"
```
I'm using the latter because the includer file is already in `include/taichi/`. I'm not sure if I understood you correctly, but I cannot see the "duplication" this can cause.

**Comment by elfring** [comment]
>`#include <taichi/common/util.h>`

Do you expect that your software library will be used from a storage location where it was installed?


>`#include "common/util.h"`

This variant can be appropriate (and also convenient) while such software is being developed.


>I'm not sure if I understood you correctly, but I cannot see the "duplication" this can cause.
 
There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with “the angle brackets inclusion method”?

**Comment by bobcao3** [comment]
closed for now
