### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [taichi-dev/taichi#157]
Would you like to add more error handling for return values from functions like the following?
* [fopen](https://en.cppreference.com/w/cpp/io/c/fopen "Opens a file") ⇒ [write_vector_to_disk](https://github.com/yuanming-hu/taichi/blob/bcdbb725cb8d5cceac8c8ba1f084894e0d082313/include/taichi/io/io.h#L37)
* [fclose](https://en.cppreference.com/w/cpp/io/c/fclose "Close a stream") ⇒ [Array2D<T>::write_text](https://github.com/yuanming-hu/taichi/blob/c3ce98421c1c7fdd43bbabc3464cd1165b2bafe9/include/taichi/visualization/image_buffer.cpp#L101)

**Comment by yuanming-hu** [comment]
Yeah, that's a good point. I believe there are similar usages of `fopen` and `fclose` in the project without error handling.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by yuanming-hu** [comment]
Thanks. Static source code analysis sounds good, and I'm glad to add such an automatic tool in the near future.

I'm not familiar with aspect-oriented software engineering. I tend to avoid complex designs in the software to keep things simple. What do you think can be the advantages of AOP? If that's just for encapsulating error detection I would feel like the complexity may overweight the advantage.

**Comment by bobcao3** [comment]
closed for now
