### ISSUE TITLE
[Infra] Use GitHub CI for osx/win test, replace Travis CI & AppVeyor

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1580]
**Concisely describe the proposed feature**
I'd like to replace the Travis CI & AppVeyor in pull request with GitHub CI.
That's because I found that GHCI is much more faster than travis / appveyor, which help us discover failures quicker.
(In fact GHCI is faster than my poor laptop...)

Given that our codebase is becoming larger and larger, the stupid travis can easily run out-of-time, see #1567 for example.

**Describe the solution you'd like (if any)**
We don't fully remove them yet, since they are **still necessary in buildbots**.

So here's my suggestion:
1. Use only GHCI (fast) in pull request build: linux+py3.7, osx+py3.7, win+py3.7.
2. Use Travis CI (slow) for `master` branch build: osx+py3.6, osx+py3.7, osx+py3.8.
3. Use AppVeyor (slow) for `master` branch build: win+py3.6, win+py3.7, win+py3.8.
3. Use Jeksins (slow) for `master` branch build: linux+py3.6, linux+py3.7, linux+py3.8.

**Additional comments**
TBD:
- [ ] GHCI for osx
- [ ] Remove Travis from PR build
- [ ] GHCI for win
- [ ] Remove AppVeyor from PR build
- [ ] AppVeyor all Python versions
- [ ] Jeksins automatically builds for `master`

WDYT? Inputs are welcome! @yuanming-hu @k-ye

**Comment by yuanming-hu** [comment]
Thanks for proposing. If this works then our workflow can be greatly simplified. I have one concern: is there a maximum number of GitHub CI servers that we can use simultaneously? It seems to be 20 (shared by all PRs?) according to https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions

![image](https://user-images.githubusercontent.com/6553256/88460980-4f470400-ce6e-11ea-8f1a-0453e3fb0007.png)

> 1. Use only GHCI (fast) in pull request build: linux+py3.7, osx+py3.7, win+py3.7.

Maybe we can do Linux+py3.6, OS X + py 3.7, Win + py 3.8 for better OS/Python coverage.
