### ISSUE TITLE
No advance_optimization

### ISSUE THREAD

**Issue by JerryYan97** [taichi-dev/taichi#1628]
AttributeError: 'taichi_core.CompileConfig' object has no attribute 'advance_optimization'

Code:
import taichi as ti
ti.init(advance_optimization=False)
...

I want to debug error like this:
RuntimeError: [verify.cpp:taichi::lang::IRVerifier::basic_verify@40] stmt 186 cannot have operand 107.
So I come to Taichi document and find the code above and it doesn't work.

**Comment by JerryYan97** [comment]
Oh, I forget updating the Taichi version :)
Sorry for that

**Comment by archibate** [comment]
Hi, thank for reporting! The error `RuntimeError: [verify.cpp:taichi::lang::IRVerifier::basic_verify@40] stmt 186 cannot have operand 107.` is likely a bug in the compiler's optimizer, would you mind post the code that caused this bug? This can help us improve, thanks in advance!

**Comment by xumingkuan** [comment]
It's `advanced_optimization`, not `advance_optimization`...

**Comment by xumingkuan** [comment]
Closing because it looks like just a typo :)
