### ISSUE TITLE
[SPIR] Add a SPIR backend (that can be exported and distributed to non-Python environment)

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1641]
**Concisely describe the proposed feature**
I'd like to add a SPIR backend, as someone may already issued somewhere in TaichiCon 0, time for opening an issue to track this.
The SPIR can be at least executed on OpenCL, Vulkan, OpenGL, according to this image:
![image](https://www.techpowerup.com/img/RyYhxKQxGUy0dp6g.jpg)
Not sure if they provide Direct3D support, which is expected to have a sightly better performance than OpenGL on Windows machine.
Note: SPIR-V = fragment shader, SPIR = compute shader, according to [8 reasons why SPIR-V makes a big difference](https://streamhpc.com/blog/2015-05-21/8-reasons-why-spir-v-makes-a-big-difference/).
Why SPIR superior than GLSL? They are said to provide more optimizations on SPIR-code, and it's portable, we can make use of our `ActionRecorder` for **exported but still portable** program.

**Describe the solution you'd like (if any)**
They already provide [SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools) that can compile GLSL, HLSL or even LLVM bitcode into SPIR-V. For Arch users, install it with `pacman -S spirv-tools`, not sure if this work for SPIR (no V) too.
So we may simply **feed our OpenGL compute shader backend output into SPIR compilers** for minimal efforts.

**Additional comments**
Feel free to close me if you find this useless, or SPIR is not that mature for us.

**Comment by yuanming-hu** [comment]
Thanks for the proposal!

Quick reply for now: a SPIR backend would be very meaningful, but we should do a design doc before starting the implementation, given its complexity.

**Comment by k-ye** [comment]
This is mostly done.
