### ISSUE TITLE
[Refactor] [lang] "x.to_numpy()" is deprecated, use "x.data" instead

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1648]
**Concisely describe the proposed feature**
I'd like to make use of the `@property` getter/setter, simplify
1. `arr = x.to_numpy()` -> `arr = x.data`.
1. `x.from_numpy(arr)` -> `x.data = arr`.

Pros:
This significantly make the API more **intuitive** and easy-to-type-and-memorize, reducing the learning barrier for beginners.

Cons:
Users could be confused if they perform `x.data[1:] = ...`, since `x.data` is not returned by reference... not sure if `numpy` could provide a *write-hook* for us.

**Describe the solution you'd like (if any)**
Currently there's only one argument `keep_dims=False` in `ti.Matrix.to_numpy()`, not sure if it's important at all.
IMO the `keep_dims=True` can be easily done by a **user mock**:
```
arr = np.array([x.data]) if x.m == 1 else x.data
```
So it's okay to use `x.data` without argument for API simplicity.

**Additional comments**
Some alternative names for `x.data`:
- `x.numpy`
- `x.content`
- `x.value`
- `x.array`
- `x.np`

But I think it's OK to keep `x.to_torch()` as is since **`numpy` is a hard dep, while `torch` is not**.
IMO we could **deprecate `to_torch`** if `torch` does provide a `numpy` interface for **reducing maintainance cost and simplify the API**, in fact it's not tested in CI at all since `torch` is not installed in `misc/ci_setup.py`, wdyt?

**Comment by yuanming-hu** [comment]
Thanks for the proposal.

I'm actually a little worried about the con you mentioned: people may tend to do `x.data[2, 3] = 4`...

At a higher level, I don't think there's any particular drawback of the current `to_numpy` design.

**Comment by archibate** [comment]
It would be great if we could **hook** the returned numpy array... While `to_numpy()` strongly convince people that it's returned-by-value...
