### ISSUE TITLE
[Refactor] Upgrade "ti.var" in Python tests

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1663]
## Description
Right now there are two closely related issues in many of the Python tests:
 1. "ti.var" is used in a lot of tests (also mentioned in #1500 but addressing them with the bullet below would be nice)
 2. Verbose data layout syntax such as `ti.root.dense(ti.i, N).place(x)` is used even for simple `dense` fields. We should use `shape=...` instead. (Fun fact: when I initially wrote these tests, Taichi doesn't support specifying `shape` at all...)

Both can be easily addressed and the clarity of the tests would be improved.

## Example
https://github.com/taichi-dev/taichi/blob/c6a3041f7b340ab5b53434593d2c87d13653b73b/tests/python/test_arg_load.py#L55-L71

should be changed into
```python
 @ti.all_archs 
 def test_ext_arr(): 
     N = 128 
     x = ti.field(dtype=ti.f32, shape=N) 
    
     @ti.kernel 
     def set_f32(v: ti.ext_arr()): 
         for i in range(N): 
             x[i] = v[i] + i 
```

## Difficulty

This is an easy but very meaningful task. Anyone who is interested is welcome to help! Thanks in advance :-)

**Comment by yuanming-hu** [comment]
@Rullec if you are still looking for issues to work on, this may be interesting to you. (Of course, if you have found other fun things to do, feel free to work on that instead.)

**Comment by Rullec** [comment]
> @Rullec if you are still looking for issues to work on, this may be interesting to you. (Of course, if you have found other fun things to do, feel free to work on that instead.)

Thanks for this recommendation... But yesterday @archibate has recommended some works for me, like #1458 or #1378 . I hope to devote my time in these 2 issues, do you think it's proper? :O.

In another word, hopefully I can finish this #1663 after or before #1458 ? they all belongs to some changes in `test` module.

**Comment by yuanming-hu** [comment]
> > @Rullec if you are still looking for issues to work on, this may be interesting to you. (Of course, if you have found other fun things to do, feel free to work on that instead.)
> 
> Thanks for this recommendation... But yesterday @archibate has recommended some works for me, like #1458 or #1378 . I hope to devote my time in these 2 issues, do you think it's proper? :O.
> 
> In another word, hopefully I can finish this #1663 after or before #1458 ? they all belongs to some changes in `test` module.

Sounds good! Deploying `@ti.test` (#1458) would be a very meaningful thing as well! Thanks.

**Comment by archibate** [comment]
> > @Rullec if you are still looking for issues to work on, this may be interesting to you. (Of course, if you have found other fun things to do, feel free to work on that instead.)
> 
> Thanks for this recommendation... But yesterday @archibate has recommended some works for me, like #1458 or #1378 . I hope to devote my time in these 2 issues, do you think it's proper? :O.
> 
> In another word, hopefully I can finish this #1663 after or before #1458 ? they all belongs to some changes in `test` module.

Hi, my suggestion is to complete #1663 first, since
1. `ti.field` is part of our public API, while `ti.test` is not, we're OK to postpone a bit in #1458.
2. `ti.var` will be soon deprecated in v0.7.0, if #1663 is not done, we can't fully deprecate it.
3. Since you've did the `ti.field` documentation refactor, it might be great for you to do this job :)

**Comment by Rullec** [comment]
Looks good, so I have enough purposes to finish #1663 at first!

彭于斌 <notifications@github.com> 于2020年8月8日周六 下午2:04写道：

**Comment by archibate** [comment]
```
(opengl-threads-per-group) [bate@archit taichi]$ grep -r '\.var' tests
(opengl-threads-per-group) [bate@archit taichi]$ grep -r 'ti\.Vector([0-9]' tests
(opengl-threads-per-group) [bate@archit taichi]$ grep -r 'ti\.Matrix([0-9]' tests
(opengl-threads-per-group) [bate@archit taichi]$ 
```
This issue has been resolved quickly by @Rullec's hard work, thanks!
