### ISSUE TITLE
Many of the examples doesn't work on Windows.  '...Cannot openfile .../cube.obj'

### ISSUE THREAD

**Issue by xvrsl** [taichi-dev/taichi#167]
It seems many examples has this problem (such as examples/rendering/trees.py)
This is the error that occurs when an example fails.
`[E 10/02/18 18:01:36.937] [scene.cpp:taichi::Mesh::load_from_file@34] Cannot open file [C:\Users\xavie\Documents\Libraries\taichi\/C:\Users\xavie\Documents\Libraries\taichi\assets\meshes/cube.obj]`

**Comment by yuanming-hu** [comment]
Thanks for the feedback. I think it is fixed just now in 39191e20cd264f041b2c228b83036229cd0e22d2. Would you have a try?

**Comment by xvrsl** [comment]
Dear Hu Yuanming,

Thank you very much.
I’m definitely gonna try it.

Wu Yueyang

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Yuanming Hu <notifications@github.com>
发送时间: Monday, October 15, 2018 6:59:06 AM
收件人: yuanming-hu/taichi
抄送: Xavier Seal; Author
主题: Re: [yuanming-hu/taichi] Many of the examples doesn't work on Windows. '...Cannot openfile .../cube.obj' (#167)


Thanks for the feedback. I think it is fixed just now in 39191e2<https://github.com/yuanming-hu/taichi/commit/39191e20cd264f041b2c228b83036229cd0e22d2>. Would you have a try?

―
