### ISSUE TITLE
[Workflow] Automatic version releases

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1674]
**Concisely describe the proposed feature**

The current [version release workflow](https://taichi.readthedocs.io/en/latest/versioning_releases.html#workflow-releasing-a-new-version) is mostly manual. It would be great to make it more automatic.

**Describe the solution you'd like (if any)**

I briefly investigated the ways to do the workflow more automatically. The key is to make use of the RESTful GitHub API. For example, 
 - Creating pull requests: https://docs.github.com/en/rest/reference/pulls#create-a-pull-request
 - Creating releases: https://docs.github.com/en/rest/reference/repos#releases

**First step**

Maybe the initial step is to implement a CLI system that creates a release PR automatically. 
Based on https://github.com/taichi-dev/taichi/blob/master/misc/format_server.py, we can perhaps we can create a "release server" that triggers releases twice a week.

**Additional comments**

Note that `git request-pull` is unrelated to opening a PR on GitHub: https://stackoverflow.com/questions/34945947/git-request-pull-how-to-create-a-github-pull-request-on-the-command-line

More investigation is needed to automatically trigger the CUDA build bot.

**Comment by archibate** [comment]
> The key is to make use of the RESTful GitHub API.

That would be helpful when releasing from CLI.
Alternative solution is to release via the official GitHub Action https://github.com/actions/create-release.

Would you mind provide more information about how PyPI packages currently? It's heard that you have a PyPI automation rule that detects GitHub release?

**Comment by yuanming-hu** [comment]
> Alternative solution is to release via the official GitHub Action https://github.com/actions/create-release.

Oh, that one looks nice! Is there a way to trigger it after the release PR is merged? (Something like post-commit action?)

> Would you mind provide more information about how PyPI packages currently? It's heard that you have a PyPI automation rule that detects GitHub release?

So basically every buildbot will try to upload. However, only the post-commit build bot has access to the PyPI password, so the pre-commit build will automatically fail to upload.

The other fact is that PyPI will just keep the first upload of a version, that's why only the release PR commit gets uploaded and later post-commit builds will fail to upload.
