### ISSUE TITLE
[Format] Use Unix line endings ("\n")

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1675]
**Describe the issue**

As we have more and more developers using different operating systems, line endings are becoming a somewhat annoying issue:
 - Windows uses `\r\n`
 - Unix (Linux and OS X) use `\n`

In fact, if you do `file **/*.cpp` under `/taichi/`, you'll find that we have been using different line endings for different files:
```
file **/*.cpp
analysis/alias_analysis.cpp:                 C source, ASCII text, with CRLF line terminators
analysis/build_cfg.cpp:                      C++ source, ASCII text, with CRLF line terminators
analysis/check_fields_registered.cpp:        C++ source, ASCII text
analysis/clone.cpp:                          C++ source, ASCII text, with CRLF line terminators
analysis/count_statements.cpp:               C++ source, ASCII text
analysis/data_source_analysis.cpp:           C source, ASCII text, with CRLF line terminators
analysis/detect_fors_with_break.cpp:         C++ source, ASCII text
analysis/gather_deactivations.cpp:           C++ source, ASCII text
analysis/gather_statements.cpp:              C++ source, ASCII text
...
```

("with CRLF line terminators" means `\r\n` is used, otherwise `\n`)

**Describe the solution you'd like (if any)**

I checked the LLVM and TensorFlow codebase, and they seem to be uniformly using Unix line endings (`\n`). **We should enforce Unix line endings as well.**

Here's what we should do
1. Update the `ti format` command to let it automatically convert all `\r\n` into `\n`.
2. Ensure the format checker fails on any appearance of `\r\n` in the codebase.

**Comment by xumingkuan** [comment]
I wonder why I was committing `\r\n` files with `git config core.autocrlf` being `true`...

**Comment by archibate** [comment]
Done in #1706.

**Comment by yuanming-hu** [comment]
Very well done by @archibate! Thanks for all the work here.
