### ISSUE TITLE
[CMake] Update the executable script in /bin/* when the environment vars is changed

### ISSUE THREAD

**Issue by Rullec** [taichi-dev/taichi#1702]
**Describe the bug**
Hi all,

I am debugging the failure of CI in #1698 .

But when I try to reproduce this case, I notice that: When the environment `python` is changed, `CMake` build didn't manage to detect it and generate a new executable script in `bin/*`. 

In one word, `./bin/ti` `./bin/tid` `./bin/taichi` stayed in the old configuration after the `python` changed in the environment.

**To Reproduce**
1. build `Taichi` and generate `./bin/ti` shown below
```
#!/home/xudong/.conda/envs/general/bin/python

import taichi
exit(taichi.main())
```
2. change to another conda env
```
conda create -n py371  python=3.7.1
conda activate py371
```

3. rebuild Taichi and check the environment
```
make

which python3
```

4. check out `./bin/ti`, it still stayed in the old python configuration
```
#!/home/xudong/.conda/envs/general/bin/python

import taichi
exit(taichi.main(debug=True))
```

5. **but what I expected is**
```
#!/home/xudong/.conda/envs/py371/bin/python

import taichi
exit(taichi.main(debug=True))
```
**A possible solution?**
I notice that these executables are generated automatically by cmake file `cmake/PythonNumpyPybind11.cmake` L15
```
# Creating python enters
file(MAKE_DIRECTORY bin)
file(WRITE ${CMAKE_SOURCE_DIR}/bin/ti "#!${PYTHON_EXECUTABLE_PATH}\nimport taichi\nexit(taichi.main())")
execute_process(COMMAND chmod +x ${CMAKE_SOURCE_DIR}/bin/ti)
execute_process(COMMAND cp ${CMAKE_SOURCE_DIR}/bin/ti ${CMAKE_SOURCE_DIR}/bin/taichi)
```
Do we need to fix it? 

if so, maybe we can find a way to fix it here.

HDYT?

**Comment by archibate** [comment]
> rebuild Taichi and check the environment
```
make
which python3
```

Does
```
cmake -Bbuild -S. # re-cmake
make
which python3
```
work for you?
If it works, we are good enough. I don't think CMake is able to include such high-level mocks in its output Makefile.

**Comment by Rullec** [comment]
Thanks! It works fine enough.

I will rebuild `Taichi` after the change of environment.
