### ISSUE TITLE
Can't install via pip on OS X 10.11

### ISSUE THREAD

**Issue by nathanielvirgo** [taichi-dev/taichi#1711]
I'm unable to install via pip, and I don't think it's due to the issues that are mentioned on the troubleshooting page or #405 .

```
$ python3.6 -m pip install taichi
Collecting taichi
  Could not find a version that satisfies the requirement taichi (from versions: )
No matching distribution found for taichi
```
```
$ python3.7 -m pip install taichi
Collecting taichi
  Could not find a version that satisfies the requirement taichi (from versions: )
No matching distribution found for taichi
```
```
$ python3.8 -m pip install taichi
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement taichi (from versions: none)
ERROR: No matching distribution found for taichi
```

These are installed via macports, and I've checked they're all 64 bit.

I am running OS X 10.11. Could the old OS version cause this problem? (It's an old machine but it works well, so I don't want to rock the boat by upgrading the OS unless I have to.)

**Comment by thinking-tower** [comment]
@nathanielvirgo might be helpful to note that [here](https://github.com/taichi-dev/taichi/blame/caf1a57e947ba0fc477f33e65a4abfb75fc65f3f/README.md#L55), `OS X (10.14+)` is supported.

**Comment by nathanielvirgo** [comment]
Ah right, I'd managed to miss that. (It's in the table, but not in the list of requirements at the start of the "installation" section at https://github.com/taichi-dev/taichi.) I guess this can be closed, then. I'll be back if I take the plunge and upgrade the OS.

**Comment by thinking-tower** [comment]
@nathanielvirgo there's also 🐳&nbsp; [Docker](https://hub.docker.com/r/taichidev/taichi) 🐳 &nbsp; if it comes to it!
