### ISSUE TITLE
[Perf] [CUDA] snode_reader/writer causes slowdown of following kernel

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#1715]
**Describe the bug**
I noticed that python scope field accesses can cause pretty big slowdowns with the cuda backend (and probably opengl and metal). I believe this is likely due to synchronize() calls associated with snode_readers and snode_writer. Is there some way we can get around this? I don't think synchronization is always necessary when using cuda with unified memory because it has page fault handling. This is particularly important for shapeless fields (ie. a = field(ti.f32, ()) since they're frequently read/written in python scope after global reductions. 

**To Reproduce**
This script hows how to setting ```c``` in python scope instead of a dedicated kernel can a big slowdown of the following  ```copy()```

``` python 
import taichi as ti

real = ti.f32
ti.init(arch=ti.cuda, default_fp=real, kernel_profiler=True)

fast = True
N = 1024

a = ti.field(real)
b = ti.field(real)
c = ti.field(real, ())

ti.root.dense(ti.ij, N).place(a)
ti.root.dense(ti.ij, N).place(b)

@ti.kernel
def copy():
    for I in ti.grouped(a):
        b[I] = a[I]

@ti.kernel
def copy2():
    for I in ti.grouped(a):
        b[I] = a[I]

@ti.kernel
def set_c():
    c[None] = 1.0

for i in range(10000):
    if fast:
        set_c()
    else:
        # this may cause a cuda sync that makes copy() slower
        c[None] = 1.0
    copy()
    copy2()

ti.kernel_profiler_print()

```

**Log/Screenshots**
using snode_writer
```
CUDA Profiler
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
[ 78.98%   2.972 s  10000x |    0.115     0.297     1.696 ms] copy_c4_0_kernel_1_range_for
[ 21.02%   0.791 s  10000x |    0.074     0.079     0.294 ms] copy2_c6_0_kernel_2_range_for
-------------------------------------------------------------------------
[100.00%] Total kernel execution time:   3.763 s   number of records: 2
=========================================================================
```

using kernel
```
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
[ 49.28%   0.796 s  10000x |    0.077     0.080     1.091 ms] copy2_c6_0_kernel_2_range_for
[ 49.05%   0.792 s  10000x |    0.077     0.079     0.824 ms] copy_c4_0_kernel_1_range_for
[  1.67%   0.027 s  10000x |    0.002     0.003     0.354 ms] set_c_c8_0_kernel_0_serial
-------------------------------------------------------------------------
[100.00%] Total kernel execution time:   1.616 s   number of records: 3
=========================================================================
```

**Comment by archibate** [comment]
> and probably opengl and metal

In fact, the OpenGL backend doesn't support `sync()` at all, so it's likely not affected.

> ```py
> real = ti.f32
> ti.init(arch=ti.cuda, default_fp=real, kernel_profiler=True)
> 
> a = ti.field(real)
> ```

Btw, just FYI: we now support `float`/`int` as an alias of default_fp/ip:

```py
ti.init(arch=ti.cuda, default_fp=ti.f32, kernel_profiler=True)

a = ti.field(float)
```
Hope that would be helpful for your works :heart:

**Comment by archibate** [comment]
Ultimate solution: move snode_rw to lang/meta.py instead of C++ side. This helps consistance between accessor kernels and megakernels, easy-to-maintain. Not sure why we didn't move it to Py side at the early age of development in Taichi.py, is there a reason? @yuanming-hu
