### ISSUE TITLE
[Bug] [lang] Wrong result of SNode shape

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1720]
**Describe the bug**
SNodes with child have wrong shape.
It seems the shape of a SNode is **dependent** on the shape of all it's children?

**To Reproduce**
```py
import taichi as ti
ti.init()

x = ti.field(int)
y = ti.field(int)

blk1 = ti.root.dense(ti.ij, (2, 2))
blk2 = blk1.dense(ti.j, 4)
blk1.place(x)
blk2.place(y)

print(x.shape, y.shape)
```

**Log/Screenshots**
I expect:
```
(2, 2), (2, 8)
```
I got
```
(2, 8), (2, 8)
```

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**
@yuanming-hu Is this expected behavior or bug? Do we have a test on this?

**Comment by yuanming-hu** [comment]
This is expected due to the trailing bits mechanism. I'll document that when I have a chance.
