### ISSUE TITLE
[refactor] Remove Context in the singleton Program

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#1722]
**Concisely describe the proposed feature**

Right now `Program` holds a `Context` object https://github.com/taichi-dev/taichi/blob/58b9cde8650baddacdb3ccbbb82c56e095904954/taichi/program/program.h#L134-L137

All kernel **launches** have to write to this single context (possibly also read from it, if there are return values). This greatly couples the kernel launches with the singleton program.

**Describe the solution you'd like (if any)**

We can have a kernel launch context builder. Every time we call a kernel, a new context builder is created, which does all the scalar or array args settings, then builds a fresh new `Context`. However, since certain backends still uses the Context to read back the return value, we have to do this conditionally on selected backends as a start.

**Additional comments**

We should probably also rename `Context` to something more meaningful, e.g. `LaunchArgsContext`?

**Comment by archibate** [comment]
> certain

opengl. I generally trust your decision, would you let me know what can I do? I'll be available until 9.1.

**Comment by yuanming-hu** [comment]
> We should probably also rename `Context` to something more meaningful, e.g. `LaunchArgsContext`?

Agreed! Maybe `TaskLaunchContext` is a better name since there's also a pointer to the `LLVMRuntime` struct. Let's do the renaming after we rigorously define the concepts of `Kernel` and `Task` (`OffloadedStmt`) :-)

**Comment by k-ye** [comment]
> opengl.

And CC? I think #1724 is good enough. If all the backends switch to `result_buffer`, we can get rid of `Program::Context` completely.
