### ISSUE TITLE
[Refactor] Use switch-case instead of "static std::map" in taichi/lang_util.cpp

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1750]
**Where to refactor**
`taichi/lang_util.cpp` has quite a few functions (e.g., `data_type_name`, `data_type_format`) that uses a `static std::map` to store input-output mapping.

https://github.com/taichi-dev/taichi/blob/a58a9af78b3c2708178db11499ff0796f8ce338f/taichi/lang_util.cpp#L67-L88

**What's wrong with the current design**
When multiple threads are calling the function with the static map uninitialized, there will be parallel writes to the "std::map". This may cause a segmentation fault.

**How to refactor**
 - Simply use C-syntax switch-case instead of "std::map"
 - Still make use of macros to minimize changes

**Example**
The code above should be changed into something like
```C++
std::string data_type_name(DataType t) {
  switch (t) {
    
#define REGISTER_DATA_TYPE(i, j) \
  case DataType::i:              \
    return #j;

    REGISTER_DATA_TYPE(f16, float16);
    REGISTER_DATA_TYPE(f32, float32);
    REGISTER_DATA_TYPE(f64, float64);
    REGISTER_DATA_TYPE(u1, int1);
    REGISTER_DATA_TYPE(i8, int8);
    REGISTER_DATA_TYPE(i16, int16);
    REGISTER_DATA_TYPE(i32, int32);
    REGISTER_DATA_TYPE(i64, int64);
    REGISTER_DATA_TYPE(u8, uint8);
    REGISTER_DATA_TYPE(u16, uint16);
    REGISTER_DATA_TYPE(u32, uint32);
    REGISTER_DATA_TYPE(u64, uint64);
    REGISTER_DATA_TYPE(gen, generic);
    REGISTER_DATA_TYPE(unknown, unknown);
#undef REGISTER_DATA_TYPE
    default:
      TI_NOT_IMPLEMENTED
  }
}
```

**Additional comments**

This is a good starting point for newcomers. Please leave a note if you have contributed < 3 PRs and to take this :-)
Open a draft PR if you want early feedback. It is suggested to ask for a review from me after the first function is refactored before apply your modification to all functions in that file.

**Comment by yuanming-hu** [comment]
A lot of thanks to @aryansoman for refactoring most of the functions! Now we are almost there, the only function left is 

https://github.com/taichi-dev/taichi/blob/c3f1a5d1899500eb08facca78fa1373e279cb692/taichi/lang_util.cpp#L306-L336

We need a nested switch-case statement there. If anyone is interested, go ahead :-)

**Comment by Hanke98** [comment]
Hi, I think it is not a difficult work, let me take it! :)

**Comment by yuanming-hu** [comment]
This is fully done. A lot of thanks to @Hanke98 and @aryansoman!
