### ISSUE TITLE
NAN check and throw exception on debug mode

### ISSUE THREAD

**Issue by g1n0st** [taichi-dev/taichi#1777]
**Concisely describe the proposed feature**
I found it's hard to locate where the first NAN was calculated when I use Taichi to write MPM simulation code, once a NAN exist, the calculation iterations will spread it to everywhere. It seems Taichi hasn't included NAN judge function and because of parallelism and numbers of particles, locate the problem is still challenging for me.

**Describe the solution you'd like (if any)**
Add library functions like insan(), isinf().
Throw reasonable exception information in debug mode when encountered NAN.

**Additional comments**
My Macbook system version is OS X 10.11.6, for some reasons it can't update but have enough calculation resources, could Taichi support OS X 10.11.6 next time? :P

**Comment by archibate** [comment]
For the `isnan` and `isinf`, consider install [`taichi_glsl`](https://github.com/taichi-dev/taichi_glsl), an extension library:
```bash
pip install taichi_glsl
```
For the `throw exception when NAN detected on debug mode`, use the `assert` statement with `ts.isnan`:
```py
import taichi as ti
import taichi_glsl as ts

ti.init(arch=ti.cpu, debug=True)  # `assert` only works in debug mode and CPU backend for now

@ti.kernel
def substep():
  ...
  assert not ts.isnan(x), "some message"   # insert this statement to some critical points
  ...
```
For the `OS X 10.11.6`, sorry about the trouble, @yuanming-hu would you mind help to support `taichi` on 10.11.6?

**Comment by g1n0st** [comment]
It works. Thanks! : )

**Comment by yuanming-hu** [comment]
Glad that this issue has been resolved.

> For the `OS X 10.11.6`, sorry about the trouble, @yuanming-hu would you mind help to support `taichi` on 10.11.6?

Sorry, but we have to prioritize on supporting OS X 10.14+...
