### ISSUE TITLE
[CLI] Add Python executable path to "ti diagnose"

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1792]
**Concisely describe the proposed feature**
Currently "ti diagnose" prints Python version info:
```
Taichi system diagnose:

python: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0]
system: linux
...
```

It would be nice to print Python executable path there as well, e.g.,
```
python path: /usr/bin/python3
```

**Describe the solution you'd like (if any)**
Use `sys.executable` near 
https://github.com/taichi-dev/taichi/blob/c0c5a57646217f946e9f92096fa634bda0a83bda/python/taichi/diagnose.py#L11

**Additional comments**
Newcomer only. Please leave a note here if you want to contribute :-)

**Comment by archibate** [comment]
Nice issue! It would also be great to include some locale informations.

**Comment by chengluyu** [comment]
Hi, I'd like to work on this.
