### ISSUE TITLE
[PyPI] Linux wheel is not uploaded since 0.6.29

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1813]
**Describe the bug**
Linux wheel is not uploaded for 0.6.29 and 0.6.30, while OS X and Windows wheels are uploaded.

**To Reproduce**
See:
https://pypi.org/project/taichi/0.6.30/#files (no linux package)
https://pypi.org/project/taichi/0.6.29/#files (no linux package)
https://pypi.org/project/taichi/0.6.28/#files (everything fine)
I can't download latest 0.6.30 via `pip install taichi` too.

**Log/Screenshots**
```
[bate@archit ~]$ pip install taichi==0.6.30 -i https://pypi.org/simple
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement taichi==0.6.30 (from versions: 0.5.11, 0.5.12, 0.5.13, 0.5.14, 0.5.15, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10, 0.6.11, 0.6.12, 0.6.13, 0.6.14, 0.6.15, 0.6.16, 0.6.17, 0.6.18, 0.6.19, 0.6.20, 0.6.21, 0.6.22, 0.6.23, 0.6.24, 0.6.25, 0.6.26, 0.6.27, 0.6.28)
ERROR: No matching distribution found for taichi==0.6.30
[bate@archit ~]$
```

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**
@yuanming-hu We'd better add a GitHub workflow for **downloading the latest release and run test** after uploaded to PyPI so that no such issue will be silently passed.

**Comment by yuanming-hu** [comment]
Yeah that's why we stop releasing new versions. The Linux buildbot is down and I need to go to MIT to fix it. However access to MIT needs COVID testing so ti takes time.

**Comment by archibate** [comment]
Is that possible for you to build it from your laptop and release it before it finish?

**Comment by yuanming-hu** [comment]
We will release v0.6.31 on Wednesday.
