### ISSUE TITLE
[doc] Use "atan2(y, x)" instead of "atan2(x, y)"

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1816]
**Describe the bug**
`atan2` takes `y` and then `x` by convention. In the documentation `atan2(x, y)` was used. This should be corrected.

Thank @squarefk for reporting.

**To Reproduce**
Search `atan2(x` and you will find a few places that use `atan2(x, y)`. Place change that to `atan2(y, x)`.

![Screenshot from 2020-08-31 15-04-38](https://user-images.githubusercontent.com/6553256/91756950-99bd4e00-eb9b-11ea-90f9-7d8c1804df4a.png)

**This is a new-comer-only issue. You will only need to modify documentation files and don't need to compile Taichi locally. Thank you!**

**Comment by new-TonyWang** [comment]
I am a fresh man of taichi programming and I want to help.
