### ISSUE TITLE
[Lang] Confusing behavior when functions have multiple returns

### ISSUE THREAD

**Issue by Eydcao** [taichi-dev/taichi#1840]
**Describe the bug**
When using the `all(stmt)` judgment in taichi scope and the result is `False`, the function seems to stop unexpectedly. Please see the screenshots and code below.

**To Reproduce**
```python
import taichi as ti

@ti.func
def is_in_bound(vec: ti.template(), AABB_min: ti.template(), AABB_max: ti.template()):
    if all(AABB_min <= vec) and all(vec <= AABB_max):
        print('all judge is True')
        return 1
    else:
        print('all judge is False')
        return 0

@ti.kernel
def test():
    x_inside = ti.Vector([0.5, 0.5, 2.5])
    x_outside = ti.Vector([0.5, 0.5, 3.5])
    AABB_min = ti.Vector([0, 0, 0])
    AABB_max = ti.Vector([1, 2, 3])
    print('test inside point', is_in_bound(x_inside, AABB_min, AABB_max))
    print('---')
    print('test outside point', is_in_bound(x_outside, AABB_min, AABB_max))

test()
```
**Log**
![image](https://user-images.githubusercontent.com/48085697/92309118-48ff8800-efd5-11ea-8544-9bb67b74f75a.png)

**Comment by Eydcao** [comment]
The problem is concerning multiple returns. Thankx~~~but you may find it useful to give out a warning here.

![image](https://user-images.githubusercontent.com/48085697/92309264-a34d1880-efd6-11ea-98c9-27c1fc7d81df.png)

**Comment by yuanming-hu** [comment]
Thanks for reporting! The frontend compiler should generate a `SyntaxError` in this case. If anyone is interested in implement this, please go ahead. Thanks!

**Comment by archibate** [comment]
In fact we have two solutions:
1. Give out an `SyntaxError` or warning in this case.
2. Support multiple `return` in functions ultimately.

If 2 is easy, we'd better go for 2 directly, WDYT?

**Comment by yuanming-hu** [comment]
Thanks for the proposals! I suggest we go 1 at this moment. Solution 2 is likely not easy - that needs us to somehow implement real functions (instead of inlined ones).
