### ISSUE TITLE
taichi_core release build error on windows 10 with LLVM 12.0.0git and clang 10

### ISSUE THREAD

**Issue by nealleehit** [taichi-dev/taichi#1851]
**Describe the bug**
taichi_core release build error on windows 10 with LLVM 12.0.0git and clang 10.

**To Reproduce**
2020-0907 21:17 the git nightly version of taichi

**Log/Screenshots**
error output for taichi_core project when building the INSTALL project.

“C:\workspace\taichi\build\taichi.sln”(默认目标) (1) ->
       “C:\workspace\taichi\build\taichi_core.vcxproj.metaproj”(默认目标) (5) ->
       “C:\workspace\taichi\build\taichi_core.vcxproj”(默认目标) (11) ->
       (ClCompile 目标) ->
         C:\workspace\taichi\taichi/llvm/llvm_codegen_utils.h(72,1): error C2664: “void llvm::AllocaInst::setAlignment(
       llvm::Align)”: 无法将参数 1 从“llvm::MaybeAlign”转换为“llvm::Align” (编译源文件 C:\workspace\taichi\taichi\codegen\codegen_llv
       m.cpp) [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\codegen\codegen_llvm.cpp(638,50): error C2664: “llvm::CallInst *llvm::IRBuilderBase
       ::CreateCall(llvm::FunctionCallee,llvm::ArrayRef<llvm::Value *>,llvm::ArrayRef<llvm::OperandBundleDef>,const llv
       m::Twine &,llvm::MDNode *)”: 无法将参数 1 从“llvm::Value *”转换为“llvm::FunctionType *” [C:\workspace\taichi\build\taichi
       _core.vcxproj]
         C:\workspace\taichi\taichi\codegen\codegen_llvm.cpp(665,60): error C2664: “llvm::CallInst *llvm::IRBuilderBase
       ::CreateCall(llvm::FunctionCallee,llvm::ArrayRef<llvm::Value *>,llvm::ArrayRef<llvm::OperandBundleDef>,const llv
       m::Twine &,llvm::MDNode *)”: 无法将参数 1 从“llvm::Value *”转换为“llvm::FunctionType *” [C:\workspace\taichi\build\taichi
       _core.vcxproj]
         C:\workspace\taichi\taichi\codegen\codegen_llvm.cpp(775,40): error C2664: “llvm::CallInst *llvm::IRBuilderBase
       ::CreateCall(llvm::FunctionCallee,llvm::ArrayRef<llvm::Value *>,llvm::ArrayRef<llvm::OperandBundleDef>,const llv
       m::Twine &,llvm::MDNode *)”: 无法将参数 1 从“llvm::Value *”转换为“llvm::FunctionType *” [C:\workspace\taichi\build\taichi
       _core.vcxproj]
         C:\workspace\taichi\taichi\llvm\llvm_codegen_utils.h(72,1): error C2664: “void llvm::AllocaInst::setAlignment(
       llvm::Align)”: 无法将参数 1 从“llvm::MaybeAlign”转换为“llvm::Align” (编译源文件 C:\workspace\taichi\taichi\llvm\llvm_codegen_u
       tils.cpp) [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi/llvm/llvm_codegen_utils.h(72,1): error C2664: “void llvm::AllocaInst::setAlignment(
       llvm::Align)”: 无法将参数 1 从“llvm::MaybeAlign”转换为“llvm::Align” (编译源文件 C:\workspace\taichi\taichi\program\program.cpp
       ) [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\llvm\llvm_context.cpp(494,53): error C2664: “void std::vector<std::string,std::allo
       cator<std::string>>::push_back(_Ty &&)”: 无法将参数 1 从“llvm::StringRef”转换为“const _Ty &” [C:\workspace\taichi\build\t
       aichi_core.vcxproj]
         C:\workspace\taichi\taichi\llvm\llvm_context.cpp(537,44): error C2440: “初始化”: 无法从“llvm::StringRef”转换为“std::bas
       ic_string<char,std::char_traits<char>,std::allocator<char>>” [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\llvm\llvm_context.cpp(715,1): error C2664: “_Ret std::_Func_class<_Ret,const std::s
       tring &>::operator ()(const std::string &) const”: 无法将参数 1 从“llvm::StringRef”转换为“const std::string &” [C:\worksp
       ace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi/llvm/llvm_codegen_utils.h(72,1): error C2664: “void llvm::AllocaInst::setAlignment(
       llvm::Align)”: 无法将参数 1 从“llvm::MaybeAlign”转换为“llvm::Align” (编译源文件 C:\workspace\taichi\taichi\struct\struct_llvm.
       cpp) [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi/llvm/llvm_codegen_utils.h(72,1): error C2664: “void llvm::AllocaInst::setAlignment(
       llvm::Align)”: 无法将参数 1 从“llvm::MaybeAlign”转换为“llvm::Align” (编译源文件 C:\workspace\taichi\taichi\backends\cpu\codege
       n_cpu.cpp) [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi/llvm/llvm_codegen_utils.h(72,1): error C2664: “void llvm::AllocaInst::setAlignment(
       llvm::Align)”: 无法将参数 1 从“llvm::MaybeAlign”转换为“llvm::Align” (编译源文件 C:\workspace\taichi\taichi\backends\cuda\codeg
       en_cuda.cpp) [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\backends\cpu\codegen_cpu.cpp(119,1): error C2664: “llvm::CallInst *llvm::IRBuilderB
       ase::CreateCall(llvm::FunctionCallee,llvm::ArrayRef<llvm::Value *>,llvm::ArrayRef<llvm::OperandBundleDef>,const
       llvm::Twine &,llvm::MDNode *)”: 无法将参数 1 从“llvm::Value *”转换为“llvm::FunctionType *” [C:\workspace\taichi\build\tai
       chi_core.vcxproj]
         C:\workspace\taichi\taichi\backends\cuda\jit_cuda.cpp(166,34): error C2664: “std::string taichi::lang::convert
       (std::string)”: 无法将参数 1 从“llvm::StringRef”转换为“std::string” [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\backends\cuda\jit_cuda.cpp(168,34): error C2664: “std::string taichi::lang::convert
       (std::string)”: 无法将参数 1 从“llvm::StringRef”转换为“std::string” [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\backends\cuda\jit_cuda.cpp(182,11): error C2039: "PrintMachineCode": 不是 "llvm::Targ
       etOptions" 的成员 [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\backends\cpu\jit_cpu.cpp(113,11): error C2039: "addGenerator": 不是 "llvm::Expected<l
       lvm::orc::JITDylib &>" 的成员 [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\backends\cpu\jit_cpu.cpp(119,27): error C2664: “llvm::Error llvm::orc::IRLayer::add
       (llvm::orc::JITDylib &,llvm::orc::ThreadSafeModule,llvm::orc::VModuleKey)”: 无法将参数 1 从“llvm::Expected<llvm::orc::
       JITDylib &>”转换为“llvm::orc::JITDylib &” [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\backends\cpu\jit_cpu.cpp(121,1): error C2664: “void std::vector<T,std::allocator<T>
       >::push_back(_Ty &&)”: 无法将参数 1 从“llvm::Expected<llvm::orc::JITDylib &> *”转换为“const _Ty &” [C:\workspace\taichi\b
       uild\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\backends\cpu\jit_cpu.cpp(181,11): error C2039: "PrintMachineCode": 不是 "llvm::Target
       Options" 的成员 [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\backends\cpu\jit_cpu.cpp(202,37): error C2039: "getHostCPUName": 不是 "llvm::sys" 的成员
        [C:\workspace\taichi\build\taichi_core.vcxproj]
         C:\workspace\taichi\taichi\backends\cpu\jit_cpu.cpp(202,51): error C3861: “getHostCPUName”: 找不到标识符 [C:\workspa
       ce\taichi\build\taichi_core.vcxproj]

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**

**Comment by archibate** [comment]
> taichi_core release build error on windows 10 with LLVM 12.0.0git and clang 10.

IIRC taichi only support LLVM 10 for now? See https://taichi.readthedocs.io/en/stable/dev_install.html for the full workflow of building from source.

**Comment by yuanming-hu** [comment]
Thanks for reporting. At this point, we only support LLVM 10. If you make Taichi work with LLVM 12, please feel free to open a PR :-)

**Comment by nealleehit** [comment]
ok, understand.
