### ISSUE TITLE
Missing packages for installation 

### ISSUE THREAD

**Issue by virusvn** [taichi-dev/taichi#188]
These packages are being missed, and need to be installed for install taichi successfully:
`pip install numpy Pillow scipy pybind11 flask flask_cors gitpython yapf colorama psutil requests PyQt5`

Note: I tried to run `python3 install.py` many times but unsuccessful without pre-install above packages.

**Comment by japrogramer** [comment]
Thanks, same issue. Manually installed those modules and now it is building.
