### ISSUE TITLE
TAICHI Performance is significantly slower since version 0.6.21 (Jul 22, 2020)

### ISSUE THREAD

**Issue by dodydharma** [taichi-dev/taichi#1932]
**Describe the bug**
I have tested different version of Taichi and I found that   Since  [version 0.6.21  (Jul 22, 2020)](https://pypi.org/project/taichi/0.6.21/), Taichi is significantly slower even in GPU.  I am using 64 GB of RAM with Double Titan Xp GPU. The frame rate even drops between 7 - 25 fps.

[Version 0.6.20](https://pypi.org/project/taichi/0.6.20/) is the latest Fastest Taichi. We are still able to achieve 60 fps on GPU.

What happen?
Please help

Thank you, best regards

**Comment by archibate** [comment]
Hi, thank for reporting. Would you mind provide me a sample code to reproduce this? If you're using CUDA, then #1548 is likely the problem.

**Comment by dodydharma** [comment]
> Hi, thank for reporting. Would you mind provide me a sample code to reproduce this? If you're using CUDA, then #1548 is likely the problem.
Hi archibate, thanks for the response.
Yes I am using CUDA in ubuntu.  You can try with the example  [mpm128.py](https://github.com/taichi-dev/taichi/blob/master/examples/mpm128.py) , run it with Taichi Version 0.6.20  and  version 0.6.21, you will see the difference.

**Comment by archibate** [comment]
On my GeForce 940MX, I get `Segmentation fault` in 0.6.20, and get 60 fps in 0.6.21. I'm sorry.. @yuanming-hu seems to upgrade CUDA PTX 6.3 in version 0.6.21, any idea if that is the cause of the segfault and fps regression?
Also, would you mind provide the full log of executing mpm128.py? Did it say `Warning: CUDA not supported, fallback to CPU`?

**Comment by dodydharma** [comment]
> On my GeForce 940MX, I get `Segmentation fault` in 0.6.20, and get 60 fps in 0.6.21. I'm sorry.. @yuanming-hu seems to upgrade CUDA PTX 6.3 in version 0.6.21, any idea if that is the cause of the segfault and fps regression?
> Also, would you mind provide the full log of executing mpm128.py? Did it say `Warning: CUDA not supported, fallback to CPU`?

Hi @archibate and @yuanming-hu, previously I uses CUDA 10 on my ubuntu. Now, after upgrading to CUDA 11, it seems the problem solved.  Now, I have updated to the latest Taichi 0.7.2 . And the simulation runs fast 60 fps on my GPU.

Thank you very much for the response.

**Comment by yuanming-hu** [comment]
Cool! We will set up performance regression tests relatively soon to prevent future performance drops. Thanks for reporting!

**Comment by dodydharma** [comment]
> Cool! We will set up performance regression tests relatively soon to prevent future performance drops. Thanks for reporting!
Nice, You're welcome.  
Also can't wait for example of Taichi Sparse Grid on MPM.

**Comment by yuanming-hu** [comment]
> > Cool! We will set up performance regression tests relatively soon to prevent future performance drops. Thanks for reporting!
> 
> Nice, You're welcome.
> Also can't wait for example of Taichi Sparse Grid on MPM.

We already have a sparse grid mpm here: https://github.com/taichi-dev/taichi_elements ：-）

**Comment by dodydharma** [comment]
> > > Cool! We will set up performance regression tests relatively soon to prevent future performance drops. Thanks for reporting!
> > 
> > 
> > Nice, You're welcome.
> > Also can't wait for example of Taichi Sparse Grid on MPM.
> 
> We already have a sparse grid mpm here: https://github.com/taichi-dev/taichi_elements :-)

Wow, Cool. Thanks @yuanming-hu .
