### ISSUE TITLE
[Refactor] [Lang] Deprecate ti.float32, use ti.f32 instead... or reverse?

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1934]
**Why refactor**
Currently we have both `ti.f32` and `ti.float32` for 32-bit floating-point number. This violates the `There should be one-- and preferably only one --obvious way to do it` principle of Python. So we'd better deprecate one of them for clarity.

Advantages of deprecating `ti.float32`:
Currently in our codebase, `ti.f32` is widely accepted while `ti.float32` is almost never occurs.
If we silently deprecate `ti.float32`, (almost) nobody knows. No codebase would be modified.

Advantages of deprecating `ti.f32`:
But I think `ti.float32` is actually clearer than `ti.f32` despite it's longer in length. Otherwise why not numpy-dev use `np.f32`?
I vote for `ti.float32` as it benefits in the long run, just like we did for `ti.var` -> `ti.field` (#1500).
People who felt `ti.float32` too long name should use `float` as shortcut, and set `default_fp` accordingly.
The same applys to `ti.int32`.

**Where to refactor**
See `python/lang/util.py`:
```py
# Real types

float32 = taichi_lang_core.DataType_float32
f32 = float32
float64 = taichi_lang_core.DataType_float64
f64 = float64

real_types = [f32, f64, float]
real_type_ids = [id(t) for t in real_types]
```

**Additional comments**
We should reach an agreement on wheater to deprecate `f32` or `float32` before begin to do it.
What's your idea? Inputs are welcome! @yuanming-hu @Rullec

**Comment by yuanming-hu** [comment]
Good ideal. Let's remove `ti.float32` etc. and use `ti.f32` instead.

See also Rust: https://doc.rust-lang.org/book/ch03-02-data-types.html#integer-types

**Comment by archibate** [comment]
> See also Rust: https://doc.rust-lang.org/book/ch03-02-data-types.html#integer-types

See also NumPy: https://www.numpy.org.cn/user/basics/types.html

I personally think the ultra-short-name `ti.f32` is confusing to beginners. Clarity matters, that's why numpy-devs choose `np.float32` instead of `np.f32`.

**Comment by yuanming-hu** [comment]
> > See also Rust: https://doc.rust-lang.org/book/ch03-02-data-types.html#integer-types
> 
> See also NumPy: https://www.numpy.org.cn/user/basics/types.html
> 
> I personally think the ultra-short-name `ti.f32` is confusing to beginners. Clarity matters, that's why numpy-devs choose `np.float32` instead of `np.f32`.

Thanks for the suggestions. It's true that either solution has pros and cons, but as the BDFL I decide that we should use `ti.f32`.
