### ISSUE TITLE
[IR] [Opt] Demote `range(begin, end)` to `range(0, end - begin)` to make dynamic range easiler for backends?

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1954]
**Concisely describe the proposed feature**
I'd like to demote:
```py
for i in range(a, b):
  print(i)
```
into:
```py
for i in range(b - a):
  print(a + i)
```
in our optimization passes.
This would allows backend to obtain the range easier. Otherwise we have to look up 4 variables and 2 ternary operators when calculating num_groups (`const_begin ? range_begin : gtmp[range_begin]`).

**Describe the solution you'd like (if any)**
As it always, write an pass in `taichi/transforms/demote_operation.cpp`.

**Additional comments**
The current design also leads to a force sync for each dynamic-for loops as it has to copy-back the gtmp buffer for 2 values.
If we can demote into 1 value for the range, we could be easier to make use of [`glDispatchComputeIndirect`](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDispatchComputeIndirect.xhtml) which doesn't require sync, directly fetch `num_groups` from GPU memory.

**Comment by yuanming-hu** [comment]
Thanks for the proposal! I did consider this design last year, but ended up with the current solution which is simpler.
