### ISSUE TITLE
ti.GUI(fast_gui=True) keeps showing black screen on Mac(it functions on Windows)

### ISSUE THREAD

**Issue by Jack12xl** [taichi-dev/taichi#1976]
Describe the bug
A clear and concise description of what the bug is, ideally within 20 words.

RT

To Reproduce
Please post a minimal sample code to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code short and representative.

    # run the example fullscreen.py
    ti example fullscreen.py

Log/Screenshots
Please post the full log of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

    ti example fullscreen
    [Taichi] mode=release
    [Taichi] preparing sandbox at /var/folders/3x/ywf3g_zd6qq1xgbqvnkrfcyc0000gn/T/taichi-2r92gt5n
    [Taichi] version 0.7.0, llvm 10.0.0, commit 0298bca3, osx, python 3.8.3
    
    ...

Additional comments
If possible, please also consider attaching the output of command ti diagnose. This produces the detailed environment information and hopefully helps us diagnose faster.

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

    $ ti diagnose             
    [Taichi] mode=release
    [Taichi] preparing sandbox at /var/folders/3x/ywf3g_zd6qq1xgbqvnkrfcyc0000gn/T/taichi-8b69l12w
    [Taichi] version 0.7.0, llvm 10.0.0, commit 0298bca3, osx, python 3.8.3
    
    *******************************************
    **      Taichi Programming Language      **
    *******************************************
    
    Docs:   https://taichi.rtfd.io/en/stable
    GitHub: https://github.com/taichi-dev/taichi
    Forum:  https://forum.taichi.graphics
    
    Taichi system diagnose:
    
    python: 3.8.3 (default, May 19 2020, 13:54:14) 
    [Clang 10.0.0 ]
    system: darwin
    executable: /Users/xieling/anaconda3/envs/taichi/bin/python
    platform: macOS-10.14.6-x86_64-i386-64bit
    architecture: 64bit 
    uname: Darwin Jack12MacBook.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
    
    locale: en_US.UTF-8
    PATH: /Users/xieling/anaconda3/envs/taichi/bin:/usr/local/opt/llvm/bin:/Users/xieling/anaconda3/bin:/Users/xieling/.autojump/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/aria2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
    
    `lsb_release` not available: [Errno 2] No such file or directory: 'lsb_release'
    TAICHI_REPO_DIR=
    
    
    import: <module 'taichi' from '/Users/xieling/anaconda3/envs/taichi/lib/python3.8/site-packages/taichi/__init__.py'>
    
    cc: False
    cpu: True
    metal: True
    opengl: False
    cuda: False
    
    `glewinfo` not available: [Errno 2] No such file or directory: 'glewinfo'
    
    `nvidia-smi` not available: [Errno 2] No such file or directory: 'nvidia-smi'
    [Taichi] mode=release
    [Taichi] preparing sandbox at /var/folders/3x/ywf3g_zd6qq1xgbqvnkrfcyc0000gn/T/taichi-ojvdor5y
    [Taichi] version 0.7.0, llvm 10.0.0, commit 0298bca3, osx, python 3.8.3
    
    [Taichi] mode=release
    [Taichi] preparing sandbox at /var/folders/3x/ywf3g_zd6qq1xgbqvnkrfcyc0000gn/T/taichi-ze7uu1lo
    [Taichi] version 0.7.0, llvm 10.0.0, commit 0298bca3, osx, python 3.8.3
    [Taichi] Starting on arch=x64
    
    [W 10/21/20 01:05:16.355] [__init__.py:adaptive_arch_select@558] Arch=[Arch.opengl] is not supported, falling back to CPU
    [Taichi] mode=release
    [Taichi] preparing sandbox at /var/folders/3x/ywf3g_zd6qq1xgbqvnkrfcyc0000gn/T/taichi-2o3p16yy
    [Taichi] version 0.7.0, llvm 10.0.0, commit 0298bca3, osx, python 3.8.3
    [Taichi] Starting on arch=x64
    
    [W 10/21/20 01:05:16.765] [__init__.py:adaptive_arch_select@558] Arch=[Arch.cuda] is not supported, falling back to CPU
    [Taichi] mode=release
    [Taichi] preparing sandbox at /var/folders/3x/ywf3g_zd6qq1xgbqvnkrfcyc0000gn/T/taichi-1_2dubgi
    [Taichi] version 0.7.0, llvm 10.0.0, commit 0298bca3, osx, python 3.8.3
    [Taichi] Starting on arch=x64
    
    [Taichi] mode=release
    [Taichi] preparing sandbox at /var/folders/3x/ywf3g_zd6qq1xgbqvnkrfcyc0000gn/T/taichi-wqar_uuv
    [Taichi] version 0.7.0, llvm 10.0.0, commit 0298bca3, osx, python 3.8.3
    
    *******************************************
    **      Taichi Programming Language      **
    *******************************************
    
    Docs:   https://taichi.rtfd.io/en/stable
    GitHub: https://github.com/taichi-dev/taichi
    Forum:  https://forum.taichi.graphics
    
    Running example minimal ...
    [Taichi] Starting on arch=x64
    [Taichi] materializing...
    >>> Running time: 0.37s
    42
    
    Consider attaching this log when maintainers ask about system information.
    >>> Running time: 5.30s
    (taichi)

**Comment by archibate** [comment]
Hi, thank for reporting, this is because fast_gui is not implemented on mac yet. I believe @k-ye will add this support soon.
