### ISSUE TITLE
[Question] printing the gradient value inside or outside of the ti.Tape behave different

### ISSUE THREAD

**Issue by Rullec** [taichi-dev/taichi#1979]
**Describe the bug**

Hello, I am trying to use the autodiff system of `Taichi`. But when I print the gradient value inside or outside of the `ti.Tape` group, it gives the different behaviors.

Why they are different? Must I put the print outside of the `ti.Tape`?

Thanks for your attention in advance.

**To Reproduce**
```py
import taichi as ti
ti.init(arch=ti.cpu)

x = ti.field(float, shape=(), needs_grad=True)
y = ti.field(float, shape=(), needs_grad=True)


@ti.kernel
def compute_y():
    y[None] = ti.sin(x[None])


with ti.Tape(y):
    compute_y()

    print(f"inside time dy/dx = {x.grad[None]} at x = {x[None]}")
print(f"outside time dy/dx = {x.grad[None]} at x = {x[None]}")
```

**Log/Screenshots**
```
[Taichi] Starting on arch=x64
[Taichi] materializing...
inside time dy/dx = 0.0 at x = 0.0
outside time dy/dx = 1.0 at x = 0.0
```

**Comment by k-ye** [comment]
Tape records all the `ti.kernel`s launched within its `with` clause, and reverses them to compute the gradients. So gradient computation can only be done outside the `with` clause.

**Comment by k-ye** [comment]
Closing, please feel free to reopen if you have any other questions :)
