### ISSUE TITLE
[refactor] Remove "taichi::parse_param"

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1997]
**Describe refactoring**

Function `inline Dict parse_param(std::vector<std::string> cli_param)` is no longer used and can be removed. 

**Additional comments**
Newcomer only. Try this if you want to familiarize yourself with our PR workflow :-)

**Comment by Hilbert-Yaa** [comment]
Hi Yuanming, I thought this refactor has already been done by now?

**Comment by yuanming-hu** [comment]
That's true. I should have closed this issue :-) Thanks for the reminder.

If you are interested in contributing, please find the list of issues here: https://github.com/taichi-dev/taichi/issues/3151#issuecomment-956049040
