### ISSUE TITLE
[refactor] Rename "ti.cache_shared" to "ti.block_local"

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#2001]
**Concisely describe the refactoring**

Since now we have a block-local storage abstraction for CUDA shared memory and CPU L1-$ in the future, the CUDA-specific word `shared` should no longer be exposed to the users. Therefore, let's deprecate `ti.cache_shared` and use `ti.block_local` instead.

For deprecation, see here as an example:

https://github.com/taichi-dev/taichi/blob/e922c9e192c8237547b73bc34a0934330f22d408/python/taichi/lang/__init__.py#L27

We should also replace the existing 7 usages of `ti.cache_shared` in the Python tests.

**Additional comments**
Newcomer only :-) You don't even need to build Taichi from the source. As long as you can modify the Python scripts this task can be nicely done.

**Comment by zhiyaluo** [comment]
Hi all,
I'm qualified for it.
