### ISSUE TITLE
[lang] Add a "name" parameter to fields

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#2006]
**Concisely describe the proposed feature**
Currently, if we write something like
```python
a = ti.field(ti.i32)
ti.root.dense(ti.i, 8).place(a)
```
, Taichi doesn't know that the field's name is `a`, and doesn't know that the `place` SNode's name is `a`.

So when users encounter some compilation error or developers want to print out some field's name, the Taichi compiler can only print out something like `S2place_i32`, which is not intuitive for debugging.

**Describe the solution you'd like (if any)**
We can add a `name` parameter to fields (including `ti.field, ti.Vector.field, ti.Matrix.field`), and pass it into `SNode`s. Then we can acquire the field's name through a `SNode *` in the codebase. The code above can be modified into
```python
a = ti.field(ti.i32, name='a')
ti.root.dense(ti.i, 8).place(a)
```
for printing out the field's name.

**Additional comments**
This feature is especially useful when a Taichi program has too many fields and a developer wants to locate a specific one.

**Comment by archibate** [comment]
Just FYI we already have introduced `a.declaration_tb` in #1734, which is a traceback to the location where `ti.field` is declared.

**Comment by xumingkuan** [comment]
> Just FYI we already have introduced `a.declaration_tb` in #1734, which is a traceback to the location where `a = ti.field` is declared.

Oh great! So does it record the name `a` in the `ti.field` when there is an `a = ti.field(...)`? For example, if someone writes
```python
a = ti.field(ti.i32)
b = ti.field(ti.i32)
a, b = b, a
```
then `a.declaration_tb` will be `'b'`?

**Comment by yuanming-hu** [comment]
It's great that stack backtrace provides some clue on where the fields are defined, but I believe we still need to have a `name` argument to `field`s since there are harder cases where manually specifying a field name is very necessary. One example is
```python
a = []
for i in range(10):
    a.append(ti.field(dtype=ti.f32, name=f'a{i}')
```
