### ISSUE TITLE
'Error: Build failed' when installing

### ISSUE THREAD

**Issue by vv-99** [taichi-dev/taichi#203]
I tried the installation on a relatively fresh Ubuntu 19.04 system. The following was the output:(I did not include all of the compiler warnings.) What could be the issue here? I especially don't understand the m_(0,0) etc. part.

Current directory: /home/vv
Cloning taichi from github...
Executing command: git clone https://github.com/yuanming-hu/taichi.git
Cloning into 'taichi'...
remote: Enumerating objects: 130, done.
remote: Counting objects: 100% (130/130), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 15731 (delta 60), reused 79 (delta 37), pack-reused 15601
Receiving objects: 100% (15731/15731), 15.47 MiB | 1.73 MiB/s, done.
Resolving deltas: 100% (10658/10658), done.
Fetching taichi runtimes...
Executing command: git clone https://github.com/yuanming-hu/taichi_runtime external/lib -b linux --depth 1
Cloning into 'external/lib'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Executing command: git submodule update --init --recursive
Submodule 'assets' (https://github.com/yuanming-hu/taichi_assets) registered for path 'assets'
Submodule 'external/glfw' (https://github.com/glfw/glfw) registered for path 'external/glfw'
Cloning into '/home/vv/taichi/assets'...
Cloning into '/home/vv/taichi/external/glfw'...
Submodule path 'assets': checked out 'a08a714972bb8efc3250924f19fc2f7286b85c9a'
Submodule path 'external/glfw': checked out '999f3556fdd80983b10051746264489f2cb1ef16'
Executing command: echo "export TAICHI_NUM_THREADS=8" >> ~/.bashrc
Executing command: echo "export TAICHI_REPO_DIR=/home/vv/taichi" >> ~/.bashrc
Executing command: echo "export PYTHONPATH=\$TAICHI_REPO_DIR/python/:\$PYTHONPATH" >> ~/.bashrc
Executing command: echo "export PATH=\$TAICHI_REPO_DIR/bin/:\$PATH" >> ~/.bashrc
PYTHONPATH=/home/vv/taichi/python/:
Executing command: echo $PYTHONPATH
/home/vv/taichi/python/:
Running cmake...
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Using C++ compiler: /usr/bin/c++
-- target changed from "" to "auto"
-- Detected CPU: kaby-lake
-- Performing Test check_cxx_compiler_flag__march_skylake
-- Performing Test check_cxx_compiler_flag__march_skylake - Success
-- Performing Test check_cxx_compiler_flag__msse2
-- Performing Test check_cxx_compiler_flag__msse2 - Success
-- Performing Test check_cxx_compiler_flag__msse3
-- Performing Test check_cxx_compiler_flag__msse3 - Success
-- Looking for C++ include pmmintrin.h
-- Looking for C++ include pmmintrin.h - found
-- Performing Test check_cxx_compiler_flag__mssse3
-- Performing Test check_cxx_compiler_flag__mssse3 - Success
-- Looking for C++ include tmmintrin.h
-- Looking for C++ include tmmintrin.h - found
-- Performing Test check_cxx_compiler_flag__msse4_1
-- Performing Test check_cxx_compiler_flag__msse4_1 - Success
-- Looking for C++ include smmintrin.h
-- Looking for C++ include smmintrin.h - found
-- Performing Test check_cxx_compiler_flag__msse4_2
-- Performing Test check_cxx_compiler_flag__msse4_2 - Success
-- Performing Test check_cxx_compiler_flag__mavx
-- Performing Test check_cxx_compiler_flag__mavx - Success
-- Looking for C++ include immintrin.h
-- Looking for C++ include immintrin.h - found
-- Performing Test check_cxx_compiler_flag__mfma
-- Performing Test check_cxx_compiler_flag__mfma - Success
-- Performing Test check_cxx_compiler_flag__mbmi2
-- Performing Test check_cxx_compiler_flag__mbmi2 - Success
-- Performing Test check_cxx_compiler_flag__mavx2
-- Performing Test check_cxx_compiler_flag__mavx2 - Success
-- Performing Test check_cxx_compiler_flag__mno_sse4a
-- Performing Test check_cxx_compiler_flag__mno_sse4a - Success
-- Performing Test check_cxx_compiler_flag__mno_xop
-- Performing Test check_cxx_compiler_flag__mno_xop - Success
-- Performing Test check_cxx_compiler_flag__mno_fma4
-- Performing Test check_cxx_compiler_flag__mno_fma4 - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512f
-- Performing Test check_cxx_compiler_flag__mno_avx512f - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512vl
-- Performing Test check_cxx_compiler_flag__mno_avx512vl - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512pf
-- Performing Test check_cxx_compiler_flag__mno_avx512pf - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512er
-- Performing Test check_cxx_compiler_flag__mno_avx512er - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512cd
-- Performing Test check_cxx_compiler_flag__mno_avx512cd - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512dq
-- Performing Test check_cxx_compiler_flag__mno_avx512dq - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512bw
-- Performing Test check_cxx_compiler_flag__mno_avx512bw - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512ifma
-- Performing Test check_cxx_compiler_flag__mno_avx512ifma - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512vbmi
-- Performing Test check_cxx_compiler_flag__mno_avx512vbmi - Success
**************************************************
* CPU feature detection done.
* Using Instruction Set Externsion: [AVX2]
**************************************************

Using float32 (single) precision as real
Using -D_GLIBCXX_USE_CXX11_ABI=0
Using /usr/bin/python3 as python executable.
Python 3.7.3
    version: 3.7
    include: /usr/include/python3.7m
    library: /usr/lib/x86_64-linux-gnu/libpython3.7m.so
    numpy include: /home/vv/.local/lib/python3.7/site-packages/numpy/core/include
    pybind11 include: /usr/local/include/python3.7;/home/vv/.local/include/python3.7m
Runtimes exist.
PYTHON_LIBRARIES/usr/lib/x86_64-linux-gnu/libpython3.7m.so

---------------------------------------------------------------
Ignoring project examples. (No CMakeLists.txt.)

---------------------------------------------------------------
C++ Flags:  -DTC_ISE_AVX2 -std=c++14 -march=native         -DGL_DO_NOT_WARN_IF_MULTI_GL_VERSION_HEADERS_INCLUDED -Wall -DTC_PASS_EXCEPTION_TO_PYTHON -DTC_INCLUDED -D_GLIBCXX_USE_CXX11_ABI=0 -g
Project libraries: 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vv/taichi/build
Building taichi...
Scanning dependencies of target taichi_core
[  1%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/dynamics/fluid2d/euler_smoke.cpp.o
[  2%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/dynamics/fluid2d/flip_liquid.cpp.o
[  3%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/common/asset_manager.cpp.o
[  4%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/dynamics/fluid2d/apic.cpp.o
[  5%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/dynamics/fluid2d/euler_liquid.cpp.o
[  6%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/dynamics/fluid2d/fluid.cpp.o
[  7%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/dynamics/rigid_body.cpp.o
[  8%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/geometry/factory.cpp.o
[  9%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/image/operations.cpp.o
In file included from /home/vv/taichi/include/taichi/math/geometry_util.h:11,
                 from /home/vv/taichi/include/taichi/math/math.h:9,
                 from /home/vv/taichi/include/taichi/common/dict.h:17,
                 from /home/vv/taichi/include/taichi/common/interface.h:8,
                 from /home/vv/taichi/include/taichi/geometry/factory.h:8,
                 from /home/vv/taichi/include/taichi/geometry/factory.cpp:6:
/home/vv/taichi/include/taichi/math/linalg.h: In instantiation of ‘taichi::VectorND<dim__, T, ISE>& taichi::VectorND<dim__, T, ISE>::operator=(const taichi::VectorND<dim__, T, ISE>&) [with int dim__ = 3; T = float; taichi::InstSetExt ISE = (taichi::InstSetExt)3]’:
/home/vv/taichi/include/taichi/math/linalg.h:1729:19:   required from here
/home/vv/taichi/include/taichi/math/linalg.h:372:11: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct taichi::VectorND<3, float, (taichi::InstSetExt)3>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy(this, &o, sizeof(*this));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/home/vv/taichi/include/taichi/math/linalg.h:154:8: note: ‘struct taichi::VectorND<3, float, (taichi::InstSetExt)3>’ declared here
 struct VectorND : public VectorNDBase<dim__, T, ISE> {
        ^~~~~~~~
In file included from /home/vv/taichi/external/include/tbb/tbb.h:42,
                 from /home/vv/taichi/include/taichi/system/threading.h:21,
                 from /home/vv/taichi/include/taichi/visualization/image_buffer.h:11,
                 from /home/vv/taichi/include/taichi/dynamics/fluid2d/fluid.h:8,
                 from /home/vv/taichi/include/taichi/dynamics/fluid2d/euler_liquid.h:9,
                 from /home/vv/taichi/include/taichi/dynamics/fluid2d/flip_liquid.h:8,
                 from /home/vv/taichi/include/taichi/dynamics/fluid2d/apic.h:8,
                 from /home/vv/taichi/include/taichi/dynamics/fluid2d/apic.cpp:6:
/home/vv/taichi/external/include/tbb/concurrent_hash_map.h: In static member function ‘static void tbb::interface5::internal::hash_map_base::init_buckets(tbb::interface5::internal::hash_map_base::segment_ptr_t, tbb::interface5::internal::hash_map_base::size_type, bool)’:
/home/vv/taichi/external/include/tbb/concurrent_hash_map.h:158:68: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct tbb::interface5::internal::hash_map_base::bucket’ with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
             if( is_initial ) std::memset(ptr, 0, sz*sizeof(bucket) );
                                                                    ^
/home/vv/taichi/include/taichi/common/meta.h:96:24: error: ‘taichi::STATIC_IF::statement<Cond> taichi::STATIC_IF::static_if(const F&) [with bool Cond = false; F = taichi::Rotation<dim>::get_rotation_matrix() const [with int dim = 3; taichi::Rotation<dim>::Matrix = taichi::MatrixND<3, float, (taichi::InstSetExt)3>]::<lambda(const auto:36&)>]’, declared using local type ‘const taichi::Rotation<dim>::get_rotation_matrix() const [with int dim = 3; taichi::Rotation<dim>::Matrix = taichi::MatrixND<3, float, (taichi::InstSetExt)3>]::<lambda(const auto:36&)>’, is used but never defined [-fpermissive]
 inline statement<Cond> static_if(F const &f) {
                        ^~~~~~~~~
/home/vv/taichi/include/taichi/common/meta.h:90:8: error: ‘void taichi::STATIC_IF::statement<false>::else_(const F&) [with F = taichi::Rotation<dim>::get_rotation_matrix() const [with int dim = 3; taichi::Rotation<dim>::Matrix = taichi::MatrixND<3, float, (taichi::InstSetExt)3>]::<lambda(const auto:37&)>]’, declared using local type ‘const taichi::Rotation<dim>::get_rotation_matrix() const [with int dim = 3; taichi::Rotation<dim>::Matrix = taichi::MatrixND<3, float, (taichi::InstSetExt)3>]::<lambda(const auto:37&)>’, is used but never defined [-fpermissive]
   void else_(const F &f) {
        ^~~~~
[ 12%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/nearest_neighbour/nnkdtree_2d.cpp.o
make[2]: *** [CMakeFiles/taichi_core.dir/build.make:141: CMakeFiles/taichi_core.dir/include/taichi/dynamics/rigid_body.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/vv/taichi/include/taichi/math/geometry_util.h:11,
                 from /home/vv/taichi/include/taichi/math/math.h:9,
                 from /home/vv/taichi/include/taichi/nearest_neighbour/nnkdtree_2d.cpp:9:
/home/vv/taichi/include/taichi/math/linalg.h: In instantiation of ‘taichi::VectorND<dim__, T, ISE>& taichi::VectorND<dim__, T, ISE>::operator=(const taichi::VectorND<dim__, T, ISE>&) [with int dim__ = 3; T = float; taichi::InstSetExt ISE = (taichi::InstSetExt)3]’:
/home/vv/taichi/include/taichi/math/linalg.h:1729:19:   required from here
/home/vv/taichi/include/taichi/math/linalg.h:372:11: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct taichi::VectorND<3, float, (taichi::InstSetExt)3>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy(this, &o, sizeof(*this));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/home/vv/taichi/include/taichi/math/linalg.h:154:8: note: ‘struct taichi::VectorND<3, float, (taichi::InstSetExt)3>’ declared here
 struct VectorND : public VectorNDBase<dim__, T, ISE> {
        ^~~~~~~~
/home/vv/taichi/include/taichi/math/linalg.h: In instantiation of ‘taichi::VectorND<dim__, T, ISE>& taichi::VectorND<dim__, T, ISE>::operator=(const taichi::VectorND<dim__, T, ISE>&) [with int dim__ = 4; T = float; taichi::InstSetExt ISE = (taichi::InstSetExt)3]’:
/home/vv/taichi/include/taichi/math/linalg.h:1042:9:   required from ‘taichi::MatrixND<dim__, T, ISE>::Vector taichi::MatrixND<dim__, T, ISE>::operator*(const Vector&) const [with int dim_ = 4; T_ = float; taichi::InstSetExt ISE_ = (taichi::InstSetExt)3; typename std::enable_if<(SIMD_4_32F<dim_, T_, ISE_> && (dim_ == 4)), int>::type <anonymous> = 0; int dim__ = 4; T = float; taichi::InstSetExt ISE = (taichi::InstSetExt)3; taichi::MatrixND<dim__, T, ISE>::Vector = taichi::VectorND<4, float, (taichi::InstSetExt)3>]’
/home/vv/taichi/include/taichi/math/linalg.h:1644:34:   required from here
/home/vv/taichi/include/taichi/math/linalg.h:372:11: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct taichi::VectorND<4, float, (taichi::InstSetExt)3>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy(this, &o, sizeof(*this));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/home/vv/taichi/include/taichi/math/linalg.h:154:8: note: ‘struct taichi::VectorND<4, float, (taichi::InstSetExt)3>’ declared here
 struct VectorND : public VectorNDBase<dim__, T, ISE> {
        ^~~~~~~~
In file included from /home/vv/taichi/include/taichi/math/geometry_util.h:11,
                 from /home/vv/taichi/include/taichi/math/math.h:9,
                 from /home/vv/taichi/include/taichi/common/dict.h:17,
                 from /home/vv/taichi/include/taichi/common/interface.h:8,
                 from /home/vv/taichi/include/taichi/common/loader.h:8,
                 from /home/vv/taichi/include/taichi/util.h:7,
                 from /home/vv/taichi/include/taichi/math/eigen.h:7,
                 from /home/vv/taichi/include/taichi/math/svd.cpp:10:
/home/vv/taichi/include/taichi/math/linalg.h: In instantiation of ‘taichi::VectorND<dim__, T, ISE>& taichi::VectorND<dim__, T, ISE>::operator=(const taichi::VectorND<dim__, T, ISE>&) [with int dim__ = 3; T = float; taichi::InstSetExt ISE = (taichi::InstSetExt)3]’:
/home/vv/taichi/include/taichi/math/linalg.h:1729:19:   required from here
/home/vv/taichi/include/taichi/math/linalg.h:372:11: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct taichi::VectorND<3, float, (taichi::InstSetExt)3>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy(this, &o, sizeof(*this));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/home/vv/taichi/include/taichi/math/linalg.h:154:8: note: ‘struct taichi::VectorND<3, float, (taichi::InstSetExt)3>’ declared here
 struct VectorND : public VectorNDBase<dim__, T, ISE> {
        ^~~~~~~~
/home/vv/taichi/include/taichi/math/svd.cpp: In instantiation of ‘void taichi::imp_svd(const taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&) [with int dim = 2; T = double]’:
/home/vv/taichi/include/taichi/math/svd.cpp:248:1:   required from here
/home/vv/taichi/include/taichi/math/svd.cpp:64:25: error: no matching function for call to ‘svd<5>(const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&)’
       SifakisSVD::svd<5>(
       ~~~~~~~~~~~~~~~~~~^
            m_(0, 0),
            ~~~~~~~~~     
            m_(0, 1),
            ~~~~~~~~~     
            m_(0, 2),
            ~~~~~~~~~     
            m_(1, 0),
            ~~~~~~~~~     
            m_(1, 1),
            ~~~~~~~~~     
            m_(1, 2),
            ~~~~~~~~~     
            m_(2, 0),
            ~~~~~~~~~     
            m_(2, 1),
            ~~~~~~~~~     
            m_(2, 2),
            ~~~~~~~~~     
            u(0, 0),
            ~~~~~~~~      
            u(0, 1),
            ~~~~~~~~      
            u(0, 2),
            ~~~~~~~~      
            u(1, 0),
            ~~~~~~~~      
            u(1, 1),
            ~~~~~~~~      
            u(1, 2),
            ~~~~~~~~      
            u(2, 0),
            ~~~~~~~~      
            u(2, 1),
            ~~~~~~~~      
            u(2, 2),
            ~~~~~~~~      
            v(0, 0),
            ~~~~~~~~      
            v(0, 1),
            ~~~~~~~~      
            v(0, 2),
            ~~~~~~~~      
            v(1, 0),
            ~~~~~~~~      
            v(1, 1),
            ~~~~~~~~      
            v(1, 2),
            ~~~~~~~~      
            v(2, 0),
            ~~~~~~~~      
            v(2, 1),
            ~~~~~~~~      
            v(2, 2),
            ~~~~~~~~      
            s(0, 0),
            ~~~~~~~~      
            s(1, 1),
            ~~~~~~~~      
            s(2, 2)
            ~~~~~~~       
       );
       ~                  
In file included from /home/vv/taichi/include/taichi/math/svd.cpp:13:
/home/vv/taichi/include/taichi/math/sifakis_svd.h:58:22: note: candidate: ‘template<int sweeps> void SifakisSVD::svd(float, float, float, float, float, float, float, float, float, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&)’
 TC_FORCE_INLINE void svd(const float a11,
                      ^~~
/home/vv/taichi/include/taichi/math/sifakis_svd.h:58:22: note:   template argument deduction/substitution failed:
/home/vv/taichi/include/taichi/math/svd.cpp:64:25: note:   cannot convert ‘u(0, 0)’ (type ‘double’) to type ‘float&’
       SifakisSVD::svd<5>(
       ~~~~~~~~~~~~~~~~~~^
            m_(0, 0),
            ~~~~~~~~~     
            m_(0, 1),
            ~~~~~~~~~     
            m_(0, 2),
            ~~~~~~~~~     
            m_(1, 0),
            ~~~~~~~~~     
            m_(1, 1),
            ~~~~~~~~~     
            m_(1, 2),
            ~~~~~~~~~     
            m_(2, 0),
            ~~~~~~~~~     
            m_(2, 1),
            ~~~~~~~~~     
            m_(2, 2),
            ~~~~~~~~~     
            u(0, 0),
            ~~~~~~~~      
            u(0, 1),
            ~~~~~~~~      
            u(0, 2),
            ~~~~~~~~      
            u(1, 0),
            ~~~~~~~~      
            u(1, 1),
            ~~~~~~~~      
            u(1, 2),
            ~~~~~~~~      
            u(2, 0),
            ~~~~~~~~      
            u(2, 1),
            ~~~~~~~~      
            u(2, 2),
            ~~~~~~~~      
            v(0, 0),
            ~~~~~~~~      
            v(0, 1),
            ~~~~~~~~      
            v(0, 2),
            ~~~~~~~~      
            v(1, 0),
            ~~~~~~~~      
            v(1, 1),
            ~~~~~~~~      
            v(1, 2),
            ~~~~~~~~      
            v(2, 0),
            ~~~~~~~~      
            v(2, 1),
            ~~~~~~~~      
            v(2, 2),
            ~~~~~~~~      
            s(0, 0),
            ~~~~~~~~      
            s(1, 1),
            ~~~~~~~~      
            s(2, 2)
            ~~~~~~~       
       );
       ~                  
/home/vv/taichi/include/taichi/math/svd.cpp: In instantiation of ‘void taichi::imp_svd(const taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&) [with int dim = 3; T = double]’:
/home/vv/taichi/include/taichi/math/svd.cpp:249:1:   required from here
/home/vv/taichi/include/taichi/math/svd.cpp:64:25: error: no matching function for call to ‘svd<5>(const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&)’
In file included from /home/vv/taichi/include/taichi/math/svd.cpp:13:
/home/vv/taichi/include/taichi/math/sifakis_svd.h:58:22: note: candidate: ‘template<int sweeps> void SifakisSVD::svd(float, float, float, float, float, float, float, float, float, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&)’
 TC_FORCE_INLINE void svd(const float a11,
                      ^~~
/home/vv/taichi/include/taichi/math/sifakis_svd.h:58:22: note:   template argument deduction/substitution failed:
/home/vv/taichi/include/taichi/math/svd.cpp:64:25: note:   cannot convert ‘u(0, 0)’ (type ‘double’) to type ‘float&’
       SifakisSVD::svd<5>(
       ~~~~~~~~~~~~~~~~~~^
            m_(0, 0),
            ~~~~~~~~~     
            m_(0, 1),
            ~~~~~~~~~     
            m_(0, 2),
            ~~~~~~~~~     
            m_(1, 0),
            ~~~~~~~~~     
            m_(1, 1),
            ~~~~~~~~~     
            m_(1, 2),
            ~~~~~~~~~     
            m_(2, 0),
            ~~~~~~~~~     
            m_(2, 1),
            ~~~~~~~~~     
            m_(2, 2),
            ~~~~~~~~~     
            u(0, 0),
            ~~~~~~~~      
            u(0, 1),
            ~~~~~~~~      
            u(0, 2),
            ~~~~~~~~      
            u(1, 0),
            ~~~~~~~~      
            u(1, 1),
            ~~~~~~~~      
            u(1, 2),
            ~~~~~~~~      
            u(2, 0),
            ~~~~~~~~      
            u(2, 1),
            ~~~~~~~~      
            u(2, 2),
            ~~~~~~~~      
            v(0, 0),
            ~~~~~~~~      
            v(0, 1),
            ~~~~~~~~      
            v(0, 2),
            ~~~~~~~~      
            v(1, 0),
            ~~~~~~~~      
            v(1, 1),
            ~~~~~~~~      
            v(1, 2),
            ~~~~~~~~      
            v(2, 0),
            ~~~~~~~~      
            v(2, 1),
            ~~~~~~~~      
            v(2, 2),
            ~~~~~~~~      
            s(0, 0),
            ~~~~~~~~      
            s(1, 1),
            ~~~~~~~~      
            s(2, 2)
            ~~~~~~~       
       );
       ~                  
In file included from /home/vv/taichi/include/taichi/math/geometry_util.h:11,
                 from /home/vv/taichi/include/taichi/math/math.h:9,
                 from /home/vv/taichi/include/taichi/common/dict.h:17,
                 from /home/vv/taichi/include/taichi/common/interface.h:8,
                 from /home/vv/taichi/include/taichi/common/loader.h:8,
                 from /home/vv/taichi/include/taichi/util.h:7,
                 from /home/vv/taichi/include/taichi/math/eigen.h:7,
                 from /home/vv/taichi/include/taichi/math/svd.cpp:10:
/home/vv/taichi/include/taichi/math/linalg.h: In instantiation of ‘taichi::VectorND<dim__, T, ISE>& taichi::VectorND<dim__, T, ISE>::operator=(const taichi::VectorND<dim__, T, ISE>&) [with int dim__ = 4; T = float; taichi::InstSetExt ISE = (taichi::InstSetExt)3]’:
/home/vv/taichi/include/taichi/math/linalg.h:1042:9:   required from ‘taichi::MatrixND<dim__, T, ISE>::Vector taichi::MatrixND<dim__, T, ISE>::operator*(const Vector&) const [with int dim_ = 4; T_ = float; taichi::InstSetExt ISE_ = (taichi::InstSetExt)3; typename std::enable_if<(SIMD_4_32F<dim_, T_, ISE_> && (dim_ == 4)), int>::type <anonymous> = 0; int dim__ = 4; T = float; taichi::InstSetExt ISE = (taichi::InstSetExt)3; taichi::MatrixND<dim__, T, ISE>::Vector = taichi::VectorND<4, float, (taichi::InstSetExt)3>]’
/home/vv/taichi/include/taichi/math/linalg.h:1644:34:   required from here
/home/vv/taichi/include/taichi/math/linalg.h:372:11: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct taichi::VectorND<4, float, (taichi::InstSetExt)3>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy(this, &o, sizeof(*this));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/home/vv/taichi/include/taichi/math/linalg.h:154:8: note: ‘struct taichi::VectorND<4, float, (taichi::InstSetExt)3>’ declared here
 struct VectorND : public VectorNDBase<dim__, T, ISE> {
        ^~~~~~~~
In file included from /home/vv/taichi/include/taichi/common/util.h:264,
                 from /home/vv/taichi/include/taichi/util.h:6,
                 from /home/vv/taichi/include/taichi/math/eigen.h:7,
                 from /home/vv/taichi/include/taichi/math/svd.cpp:10:
/home/vv/taichi/include/taichi/common/meta.h:79:8: error: ‘void taichi::STATIC_IF::statement<Cond>::else_(const F&) [with F = taichi::imp_svd(const taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&) [with int dim = 2; T = double]::<lambda(const auto:25&)>; bool Cond = true]’, declared using local type ‘const taichi::imp_svd(const taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&) [with int dim = 2; T = double]::<lambda(const auto:25&)>’, is used but never defined [-fpermissive]
   void else_(const F &) {
        ^~~~~
/home/vv/taichi/include/taichi/common/meta.h:90:8: error: ‘void taichi::STATIC_IF::statement<false>::else_(const F&) [with F = taichi::imp_svd(const taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&) [with int dim = 3; T = double]::<lambda(const auto:25&)>]’, declared using local type ‘const taichi::imp_svd(const taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&, taichi::MatrixND<n, T>&) [with int dim = 3; T = double]::<lambda(const auto:25&)>’, is used but never defined [-fpermissive]
   void else_(const F &f) {
        ^~~~~
make[2]: *** [CMakeFiles/taichi_core.dir/build.make:193: CMakeFiles/taichi_core.dir/include/taichi/math/svd.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/taichi_core.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
  Error: Build failed.
  Error: installation failed.

**Comment by daef** [comment]
bump: got the same error installing on 5.1.12-arch1-1-ARCH using Python 3.7.3

**Comment by daef** [comment]
this actually seems like a dup of https://github.com/yuanming-hu/taichi/issues/200 ( and therefore https://github.com/yuanming-hu/taichi/issues/202 )
