### ISSUE TITLE
[refactor] Remove legacy C++ frontend macros

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#2036]
**What to refactor**

The old C++ frontend is abandoned after we migrate to Python. A few related macros can be removed:  
https://github.com/taichi-dev/taichi/blob/414b0ebe790a4cd66d8635a6c391eb9a88ed99c4/taichi/ir/frontend.h#L64-L79

**Additional comments**
This issue can be done by completed by simply deleting the code above. Newcomer only :-)

**Comment by archibate** [comment]
Btw, will we restore a new C++ frontend in future, or completely embed into Python?

**Comment by yuanming-hu** [comment]
Good question. I don't think we will do a new C++ frontend in the near future.
