### ISSUE TITLE
Cannot use ti.f64 and ti.random() together. 

### ISSUE THREAD

**Issue by JerryYan97** [taichi-dev/taichi#2045]
Hello!

I am trying to use ti.random() when I am using default_fp=ti.64 as init, but it looks like it would report error like this:
`python3.8: /home/yuanming/repos/llvm-10.0.0.src/lib/IR/Instructions.cpp:1358: void llvm::StoreInst::AssertOK(): Assertion `getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"' failed.
`

Here is the minimum code block to reproduce this problem:
`
# Test random number
import taichi as ti
ti.init(arch=ti.gpu, default_fp=ti.f64)

@ti.kernel
def rand_generator():
    for i in range(100):
        print(ti.random())

rand_generator()
`

**Comment by yuanming-hu** [comment]
Thanks for reporting! I believe this should have been fixed in v0.7.6 - could you have a try? Related: #2023

**Comment by yuanming-hu** [comment]
I confirm that this is fixed with v0.7.8.
