### ISSUE TITLE
mass_spring_3d.py can't runing 

### ISSUE THREAD

**Issue by chongxian** [taichi-dev/taichi#2053]
TypeError: __init__() got an unexpected keyword argument 'faces_n'

**Comment by archibate** [comment]
What Taichi THREE version are you using? It almost change its API on each version.

Consider run `python3 -m pip install taichi_three==0.0.5`.
&nbsp;


双笙子佯谬
1931127624@qq.com

上海拆桥学院
桥梁爆破小组首席执行官


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年11月19日(星期四) 晚上7:17
收件人: "taichi-dev/taichi"<taichi@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [taichi-dev/taichi] mass_spring_3d.py can&#39;t runing  (#2053)





 
TypeError: init() got an unexpected keyword argument 'faces_n'

**Comment by chongxian** [comment]
Thanks for your reply, the code can run


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taichi-dev/taichi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 晚上7:37
收件人:&nbsp;"taichi-dev/taichi"<taichi@noreply.github.com&gt;;
抄送:&nbsp;"虫子君"<1079795307@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taichi-dev/taichi] mass_spring_3d.py can't runing  (#2053)





 What Taichi THREE version are you using? It almost change its API on each version. 
 
 Consider run `python3 -m pip install taichi_three==0.0.5`. 
 &amp;nbsp; 
 
 
 双笙子佯谬 
 1931127624@qq.com 
 
 上海拆桥学院 
 桥梁爆破小组首席执行官 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "notifications"<notifications@github.com&amp;gt;;  
 发送时间: 2020年11月19日(星期四) 晚上7:17 
 收件人: "taichi-dev/taichi"<taichi@noreply.github.com&amp;gt;;  
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;;  
 主题: [taichi-dev/taichi] mass_spring_3d.py can&amp;#39;t runing  (#2053) 
 
 
 
 
 
   
 TypeError: init() got an unexpected keyword argument 'faces_n'
