### ISSUE TITLE
之前Taichi运行正常，突然就没法运行了。显示错误： ti.init(arch=ti.gpu) AttributeError: module 'taichi' has no attribute 'init'

### ISSUE THREAD

**Issue by ben100118** [taichi-dev/taichi#2072]
import taichi as ti

ti.init(arch=ti.gpu)

n=320
pixels=ti.var(dt=ti.f32,shape=(n*2,n))

@ti.func
def complex_sqr(z):
    return ti.Vector([z[0]**2-z[1]**2,z[1]*z[0]*2])

@ti.kernel
def paint(t:ti.f32):
    for i,j in pixels:
        c=ti.Vector([-0.8,ti.cos(t)*0.2])
        z=ti.Vector([i/n-1,j/n-0.5])*2
        iterations=0
        while z.norm() <20 and iterations < 50:
            z=complex_sqr(z)+c
            iterations+=1
        pixels[i,j]=1-iterations*0.02

gui=ti.GUI("Julia Set",res=(n*2,n))

for i in range(1000000):
    paint(i*0.03)
    gui.set_image(pixels)
    gui.show()

**Comment by archibate** [comment]
你的文件名是不是taichi.py？

**Comment by ben100118** [comment]
不是，我的文件名是2.py

**Comment by archibate** [comment]
你的太极版本是多少？能否试试看以下三行代码：
import taichi as ti
print(dir(ti))
print(ti.__file__, ti.__version__)
并告诉我结果？
&nbsp;


双笙子佯谬
1931127624@qq.com

上海拆桥学院
桥梁爆破小组首席执行官


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年12月1日(星期二) 上午9:57
收件人: "taichi-dev/taichi"<taichi@noreply.github.com&gt;; 
抄送: "双笙子佯谬"<1931127624@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [taichi-dev/taichi] 之前Taichi运行正常，突然就没法运行了。显示错误： ti.init(arch=ti.gpu) AttributeError: module &#39;taichi&#39; has no attribute &#39;init&#39; (#2072)





 
不是，我的文件名是2.py

**Comment by ben100118** [comment]
输出结果：['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
Traceback (most recent call last):
  File "E:/python program/taichi/try.py", line 3, in <module>
    print(ti._file_,ti._version_)
AttributeError: module 'taichi' has no attribute '_file_'

我的taichi版本为0.7.9

**Comment by archibate** [comment]
同一个文件夹中有没有taichi.py或者名为taichi的目录？python会优先从当前目录搜索模块。
&nbsp;


双笙子佯谬
1931127624@qq.com

上海拆桥学院
桥梁爆破小组首席执行官


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年12月1日(星期二) 上午9:57
收件人: "taichi-dev/taichi"<taichi@noreply.github.com&gt;; 
抄送: "双笙子佯谬"<1931127624@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [taichi-dev/taichi] 之前Taichi运行正常，突然就没法运行了。显示错误： ti.init(arch=ti.gpu) AttributeError: module &#39;taichi&#39; has no attribute &#39;init&#39; (#2072)





 
不是，我的文件名是2.py

**Comment by archibate** [comment]
`print(ti.__path__)`呢？

**Comment by ben100118** [comment]
['E:\\python program\\taichi']

**Comment by archibate** [comment]
把这个文件夹重命名为其他任何名字试试？比如`E:\python program\taichi demo`&nbsp;


双笙子佯谬
1931127624@qq.com

上海拆桥学院
桥梁爆破小组首席执行官


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年12月1日(星期二) 中午12:46
收件人: "taichi-dev/taichi"<taichi@noreply.github.com&gt;; 
抄送: "双笙子佯谬"<1931127624@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [taichi-dev/taichi] 之前Taichi运行正常，突然就没法运行了。显示错误： ti.init(arch=ti.gpu) AttributeError: module &#39;taichi&#39; has no attribute &#39;init&#39; (#2072)





 
['E:\python program\taichi']

**Comment by ben100118** [comment]
不是，我的文件名是3.py



---原始邮件---
发件人: &quot;彭于斌&quot;<notifications@github.com&gt;
发送时间: 2020年11月30日(周一) 晚上11:49
收件人: &quot;taichi-dev/taichi&quot;<taichi@noreply.github.com&gt;;
抄送: &quot;ben100118&quot;<1501037322@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [taichi-dev/taichi] 之前Taichi运行正常，突然就没法运行了。显示错误： ti.init(arch=ti.gpu) AttributeError: module 'taichi' has no attribute 'init' (#2072)




 
你的文件名是不是taichi.py？
 
&mdash;

**Comment by asurada404** [comment]
我也碰到同意的问题，检查了文件名和路径

```python

Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taichi as ti
>>> ti.__path__
_NamespacePath(['/home/username/.local/lib/python3.6/site-packages/taichi'])
>>> ti.init(ti.cpu)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'taichi' has no attribute 'init'
>>> ti.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'taichi' has no attribute '__version__'
>>> dir(ti)
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> ti.__name__
'taichi'

```

**Comment by asurada404** [comment]
Yes, the folder is not empty, the content is as follow:
```
username@username-ThinkPad-X1-Carbon-Gen-8:~/.local/lib/python3.6/site-packages/taichi$ pwd
/home/username/.local/lib/python3.6/site-packages/taichi
username@username-ThinkPad-X1-Carbon-Gen-8:~/.local/lib/python3.6/site-packages/taichi$ tree -L 3
.
├── assets
│   └── Go-Regular.ttf
├── examples
│   ├── algorithm
│   │   ├── invert_image_color.py
│   │   ├── laplace.py
│   │   ├── marching_squares.py
│   │   ├── mciso_advanced.py
│   │   ├── mgpcg_advanced.py
│   │   ├── mgpcg.py
│   │   ├── print_offset.py
│   │   ├── __pycache__
│   │   └── quadtree.py
│   ├── autodiff
│   │   ├── minimization.py
│   │   ├── mnist_download_data.py
│   │   ├── mnist.py
│   │   ├── __pycache__
│   │   ├── regression.py
│   │   └── simple_derivative.py
│   ├── features
│   │   ├── gui
│   │   ├── io
│   │   └── sparse
│   ├── minimal.py
│   ├── __pycache__
│   │   └── minimal.cpython-36.pyc
│   ├── rendering
│   │   ├── cornell_box.py
│   │   ├── particle_renderer.py
│   │   ├── __pycache__
│   │   ├── rasterizer.py
│   │   ├── renderer_utils.py
│   │   ├── sdf2d.py
│   │   ├── sdf_renderer.py
│   │   ├── simple_uv.py
│   │   └── taichi_logo.py
│   └── simulation
│       ├── ad_gravity.py
│       ├── cg_possion.py
│       ├── comet.py
│       ├── euler.py
│       ├── fem128.py
│       ├── fem99.py
│       ├── fractal.py
│       ├── game_of_life.py
│       ├── mass_spring_3d.py
│       ├── mass_spring_game.py
│       ├── math_utils.py
│       ├── mpm128.py
│       ├── mpm3d.py
│       ├── mpm88.py
│       ├── mpm99.py
│       ├── mpm_lagrangian_forces.py
│       ├── nbody_oscillator.py
│       ├── odop_solar.py
│       ├── pbf2d.py
│       ├── physarum.py
│       ├── __pycache__
│       ├── stable_fluid.py
│       ├── tree_gravity.py
│       ├── vortex_rings.py
│       └── waterwave.py
└── lib
    ├── runtime_cuda.bc
    ├── runtime_x64.bc
    ├── slim_libdevice.10.bc
    └── taichi_core.so

16 directories, 52 files


```

**Comment by k-ye** [comment]
Sorry, please keep using 0.7.26 for now until https://github.com/taichi-dev/taichi/issues/2642 gets resolved. Thanks!

**Comment by asurada404** [comment]
Thanks for the reply,   0.7.26 works for me.
