### ISSUE TITLE
CentOS installation issue

### ISSUE THREAD

**Issue by hygge-beaker** [taichi-dev/taichi#209]
There was chatter about this error in another thread but the solution there didn't unblock me.
using >python36 install.py 
A sample of the errors:
- -- Performing Test check_cxx_compiler_flag__mno_avx512f - Failed
- -- Performing Test check_cxx_compiler_flag__mno_avx512vl
- [  5%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/dynamics/fluid2d/euler_smoke.cpp.o
- c++: error: unrecognized command line option ‘-std=c++14’
ending with:
make[2]: *** [CMakeFiles/taichi_core.dir/include/taichi/dynamics/rigid_body.cpp.o] Error 1
[  8%] Building CXX object CMakeFiles/taichi_core.dir/include/taichi/geometry/factory.cpp.o
c++: error: unrecognized command line option ‘-std=c++14’
make[2]: *** [CMakeFiles/taichi_core.dir/include/taichi/geometry/factory.cpp.o] Error 1
make[1]: *** [CMakeFiles/taichi_core.dir/all] Error 2
make: *** [all] Error 2
  Error: Build failed.
  Error: installation failed.

CPU:  Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz

Full build output can be found in the python3_install_build.failure.txt
[python3_install_build_failure.txt](https://github.com/yuanming-hu/taichi/files/3602251/python3_install_build_failure.txt)

Thanks in advance!

**Comment by pianshi** [comment]
It seems that Windows is not supported for the time being, but can be installed on Ubuntu os
