### ISSUE TITLE
[Lang] [IR] [Type] Support allocating thread-local arrays

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#2100]
**Concisely describe the proposed feature**
I'd like to dynamically allocate arrays locally within the current thread so that we have local stack and enumerate tree-like structures without recursion.

**Describe the solution you'd like (if any)**
First of all, the usage of local arrays must not share between offloads.

This should adds several backend IR statements:
- `arr = ArrayAllocStmt(size)` allocates a new local array with fixed constant size
- `ArrayPtrStmt(arr, index)` gives the pointer to `arr[index]`.

For the OpenGL backend, it support allocating local arrays by simply `int arr[size];`, it is thread-private.

**Additional comments**
After having local arrays, users may self-define a `top` variable to implement stacks.

Btw, how does our research project (the type system) helps? Is local array be considered as a non-primitive type IIUC?
Also, will fixed-length local array be the future of `ti.Vector` after the research project is done? Or this is actually already in your TODO items?

**Comment by archibate** [comment]
Or, more conveniently, will we have built-in octree or bvh tree with dynamic depth as a new kind of sparse data structure?

**Comment by k-ye** [comment]
Thanks for writing this up!

> Btw, how does our research project (the type system) helps? Is local array be considered as a non-primitive type IIUC?

It's more like the element type of the local array should also support the new custom types, whereas the array itself is just a container. I assume the local array will be accessed with `LocalLoad`/`LocalStore`, so this shouldn't complicate the alias analysis (@xumingkuan  to confirm).

> Also, will fixed-length local array be the future of ti.Vector after the research project is done? 

I think the local array can be a prototype of how we can implement `ti.Vector` in the future. However, eventually we should still keep `ti.Vector`, because users are more familiar with this concept. After all, the only thing that prevents us from using `ti.Vector` as a local array is because of the lack of dynamic indexing?

---

Because of the tight deadline of these research projects, it's better not to have big feature designs in the meantime... I feel like this won't be a big feature. However, note that eventually the local array IRs may be deprecated in favor of supporting dynamic indexing in `ti.Vector`.

**Comment by xumingkuan** [comment]
> > Btw, how does our research project (the type system) helps? Is local array be considered as a non-primitive type IIUC?
> 
> It's more like the element type of the local array should also support the new custom types, whereas the array itself is just a container. I assume the local array will be accessed with `LocalLoad`/`LocalStore`, so this shouldn't complicate the alias analysis (@xumingkuan to confirm).

I agree that local arrays accessed with `LocalLoad`/`LocalStore` would not complicate the alias analysis.

**Comment by archibate** [comment]
> However, note that eventually the local array IRs may be deprecated in favor of supporting dynamic indexing in ti.Vector (that said, ti.Vector's implementation can definitely re-use the outcome from local array).

IMO `supporting dynamic indexing in ti.Vector` is impossible without any changes in IR and type system, why?

Consider a vector `a = ti.Vector([1, 2, 3])`, translated to backend source codes, it becomes, say:
```cpp
int tmp35 = 1;
int tmp36 = 2;
int tmp37 = 3;
```
Then I want to access `a[i]` where `i` is a dynamic index, what can I do? You can do nothing but a switch case to enumerate all these three variables as they are defined separately:
```cpp
int tmp99 = i;
if (tmp99 == 0)
  return tmp35;
else if (tmp99 == 1)
  return tmp36;
else if (tmp99 == 2)
  return tmp37;
else
  throw RuntimeError;
```
See? The current implementation of `ti.Vector` make it impossible for dynamic indexing **efficiently**.

So what's the solution? Here's my solution, use an array of integers when defining the vector, instead of many separate integers:
```cpp
int tmp35[3] = {1, 2, 3};
```
Then, using dynamic indices become straightforward:
```cpp
int tmp99 = i;
return tmp35[tmp99];
```

See? To make vectors support dynamic indexing, the only efficient solution is to add support of local arrays in backend and middle-end.

FYI I've been long use the switch-case method for dynamic indexing in Taichi-Blend:
```py
@ti.func
def list_subscript(a, i):
    '''magic method to subscript a list/vector with dynamic index'''
    ret = sum(a) * 0
    for j in ti.static(range(len(a))):
        if i == j:
            ret = a[j]
    return ret
```
But it won't work for larger list/vectors as it is `O(n)` for each access, not sure if you mean to use this for `ti.Vector`.

**Comment by archibate** [comment]
> > > Btw, how does our research project (the type system) helps? Is local array be considered as a non-primitive type IIUC?
> > 
> > 
> > It's more like the element type of the local array should also support the new custom types, whereas the array itself is just a container. I assume the local array will be accessed with `LocalLoad`/`LocalStore`, so this shouldn't complicate the alias analysis (@xumingkuan to confirm).
> 
> I agree that local arrays accessed with `LocalLoad`/`LocalStore` would not complicate the alias analysis.

Great, so our plan is to add array types to type system and access it with `LocalLoad` and `LocalStore`?

Btw currently I see:
```
kernel {
  <i32> $0 = alloca
  <i32> $1 = const [1]
  <i32> $2 : local store [$0 <- $1]
  <i32> $3 = local load [ [$0[0]]]
  print $3, "\n"
}
```
Does the `$0[0]` here mean that we also have `$0[1]` and `alloca` actually already support allocating more than one elements?

**Comment by xumingkuan** [comment]
> > I agree that local arrays accessed with `LocalLoad`/`LocalStore` would not complicate the alias analysis.
> 
> Great, so our plan is to add array types to type system and access it with `LocalLoad` and `LocalStore`?
> 
> Btw currently I see:
> 
> ```
> kernel {
>   <i32> $0 = alloca
>   <i32> $1 = const [1]
>   <i32> $2 : local store [$0 <- $1]
>   <i32> $3 = local load [ [$0[0]]]
>   print $3, "\n"
> }
> ```
> 
> Does the `$0[0]` here mean that we also have `$0[1]` and `alloca` actually already support allocating more than one elements?

Cool! IIRC we only have `$0[0], $0[1], ...` with constant subscripts now, and this was for SIMD. We may need to handle something like `$0[$1]` in local arrays.

**Comment by k-ye** [comment]
https://github.com/taichi-dev/taichi/issues/2100#issuecomment-747913814

I'm pretty sure we are talking about the same thing, and I saw your point in the very beginning. When I say supporting dynamic indexing, I didn't mean that we would keep the way how `ti.Vector` is implemented now (i.e. all those scalars you've pointed out). Instead, `ti.Vector` will adapt to how local array is supported. Therefore "the local array can be a prototype of how we can implement ti.Vector in the future."

There are a few things that I can think of, where local array *alone* can't make `ti.Vector` work completely.

1. `ti.Vector` can be in a global SNode.
2. How can we support slicing?
3. How can we pass `ti.Vector` or local arrays to functions, assuming we will have real functions later.
 
My rough guess is that vector can be translated into something like

```cpp
// I know that this won't work for OpenGL, but it will likely work on other backends.
class VecView {
  Elem* data;
  int size;
};
```

**Comment by archibate** [comment]
> I didn't mean that we would keep the way how ti.Vector is implemented now

IMO we can still keep the old `ti.Vector` implementation for a bit longer time, and experimentally support `ti.Array` for dynamic indexing. This prevents possible issues in the new local array system causing API break.

> ti.Vector can be in a global SNode.

We may utilize the new type system so that `ti.Vector`'s may be completely share the same API with `ti.field`:
```
vec3 = ti.type_factory.make_vector(ti.f32, 3)
x = ti.field(dtype=vec3, shape=(3, 4))
```

> How can we support slicing?

Adding some IRs like `ArraySliceStmt` would work, structure may like the `VecView` you mentioned below.

> How can we pass ti.Vector or local arrays to functions, assuming we will have real functions later.

Good question, for local arrays we may want to **pass by reference by default** as arrays can be huge, for `ti.Vector`'s we may want to **pass by value by default** to prevent confusing errors. That's also my point why we'd separate `ti.Vector` and `ti.Array`.

> // I know that this won't work for OpenGL, but it will likely work on other backends.

It actually works for OpenGL, it may supports pointers at most times using my ad-hoc method :rofl:
```
int data_f32[];

class VecView {
  int data;
  int size;
};

int tmp2 = data_f32[tmp1.data >> 2];  // simulating *tmp1.data
```

**Comment by k-ye** [comment]
Having local array strictly scoped to primitive types should be good enough. It solves the non-recursion problem, and sheds some light on how `ti.Vector` can be implemented in the future.

However, there are things you might want to be aware of:

1.  People are working on projects that are deadlined in the next month or so. Unfortunately, adding the local array type might conflict with the ongoing code changes. (The research projects have much higher priorities now.)
2. While the local array shows the futures of `ti.Vector`, it is meant to be a temporary solution. That is:

```py
@ti.kernel
def foo():
  top = 0
  v = ti.Vector([1, 2, 3, 4, 5])  # eventually, |v| can be used just as a local array
  v[top] = 10
  top += 1
```

**Comment by archibate** [comment]
> People are working on projects that are deadlined in the next month or so.

What is the accurate time of it? Before that, does adding `ti.get_linear_thread_id()` conflict with your research project? It at least make this walkaround profitable on CPUs.
Also, does making use of already-existing ad-stack system for local-stacks make sense to you as a walk around before your deadline is gone? If you agrees, I'll proceed to inspect stuffs.

**Comment by bobcao3** [comment]
Thread local tensors and tensor dynamic indexing is effectively the feature requested here.
