### ISSUE TITLE
Pass an integer into the kernel and use this variable as an index to report an error

### ISSUE THREAD

**Issue by liyou54** [taichi-dev/taichi#2104]
I want to get an value by passing a index but it has an err,saying the var is an expr not an int ,i don,t how can i get the value

Here is my function :

def perlin_kernel(x:float, y:float, z:float,xi:int,yi:int,zi:int)->float:
    xf = x - xi;
    yf = y - yi;
    zf = z - zi;
    u = fade(xf);
    v = fade(yf);
    w = fade(zf);
    aaa = RANDOM_INDEX[RANDOM_INDEX[RANDOM_INDEX[xi    ] + yi    ] + zi    ];
    aba = RANDOM_INDEX[RANDOM_INDEX[RANDOM_INDEX[xi    ] + yi + 1] + zi    ];
    aab = RANDOM_INDEX[RANDOM_INDEX[RANDOM_INDEX[xi    ] + yi    ] + zi + 1];
    abb = RANDOM_INDEX[RANDOM_INDEX[RANDOM_INDEX[xi    ] + yi + 1] + zi + 1];   
    baa = RANDOM_INDEX[RANDOM_INDEX[RANDOM_INDEX[xi + 1] + yi    ] + zi    ];
    bba = RANDOM_INDEX[RANDOM_INDEX[RANDOM_INDEX[xi + 1] + yi + 1] + zi    ];
    bab = RANDOM_INDEX[RANDOM_INDEX[RANDOM_INDEX[xi + 1] + yi    ] + zi + 1];
    bbb = RANDOM_INDEX[RANDOM_INDEX[RANDOM_INDEX[xi + 1] + yi + 1] + zi + 1];

Log:
File "d:\work\code\taichi\test.py", line 111, in <module>
    perlin(1,2,3)
  File "d:\work\code\taichi\test.py", line 107, in perlin
    return perlin_kernel(x,y,z,xi,yi,zi)
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel.py", line 571, in wrapped
    return primal(*args, **kwargs)
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel.py", line 499, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel.py", line 368, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel.py", line 365, in taichi_ast_generator
    compiled()
  File "d:\work\code\taichi\test.py", line 68, in perlin_kernel
    aaa = RANDOM_INDEX[RANDOM_INDEX[RANDOM_INDEX[xi    ] + yi    ] + zi    ];
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\util.py", line 201, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\impl.py", line 102, in subscript
    return value[indices[0]]
TypeError: list indices must be integers or slices, not Expr

**Comment by archibate** [comment]
This is because Taichi doesn't like Python lists as data storage. The `Expr` here is acutually a Taichi integer, not Python integer, therefore cannot ass as index to a Python list.
As a replacement, you can use Taichi fields which support Taichi integers as index.

So solutions are:

1. use a field to store RANDOM_INDEX:
```
import numpy as np
RANDOM_INDEX = ti.field(int, 12345)  # declare the field
RANDOM_INDEX.from_numpy(np.random.rand(12345) * 255)  # initialize the field with a randomized numpy array
```

2. if your xi, yi, zi is constant, use templates for xi, yi, zi:
```
def perlin_kernel(xi:ti.template(),yi:ti.template())
```
But the kernel will recompile on every different values of xi, yi, zi.

**Comment by liyou54** [comment]
Thanks .the problem has resolve ;

**Comment by liyou54** [comment]
And I have an another question ,I want to use floor() but it can,t

@ti.func
def perlin(x, y, z):

    xi = int(ti.floor(x)) & 255
    yi = int(ti.floor(y)) & 255
    zi = int(ti.floor(z)) & 255

    xi = math.floor(x) & 255
    yi = math.floor(y) & 255
    zi = math.floor(z) & 255

this is log:

RuntimeError: [type_check.cpp:taichi::lang::TypeCheck::visit@202] [$582] floor/ceil takes real inputs only. At   File "d:\work\code\taichi\test.py", line 132, in DrawLine
    temp = perlin(line[change,i,0],line[change,i,1],k  )*30*3.1415926

  File "d:\work\code\taichi\test.py", line 75, in perlin
    xi = math.floor(x) & 255
TypeError: must be real number, not Expr

**Comment by liyou54** [comment]
@ti.kernel
def DrawLine(k:int,change:int):
    for i in range(LINE_COUNT):
        temp = perlin(line[change,i,0],line[change,i,1],k  )*30*3.1415926
        line[abs(1-change),i,0] += ti.sin(temp)*0.0001
        line[abs(1-change),i,1] += ti.cos(temp)*0.0001

**Comment by archibate** [comment]
> floor/ceil takes real inputs only.

This is likely becase the `x` in `ti.floor(x)` is already an integer type.
To force `ti.floor` work for integers, you may try `ti.floor(float(x))`:
xi = int(ti.floor(float(x))) & 255
yi = int(ti.floor(float(y))) & 255
zi = int(ti.floor(float(z))) & 255

**Comment by advaitjawaji** [comment]
Hi, 
I am trying to do a similar thing where i am passing a taichi float to a from inside a taichi function to a python function but it is getting converted to a ti.Expr, how did you fix it?
