### ISSUE TITLE
Files Indented Using Tabs Fails to Materialize

### ISSUE THREAD

**Issue by lukedan** [taichi-dev/taichi#2108]
Taichi kernels that are indented using tabs (e.g., in `@ti.data_oriented` classes) fails to materialize. This is due to the fact that `remove_indent()` in kernel.py only checks for spaces.

**To Reproduce**
The following snippet uses tabs. Convert the indentation to spaces and it will run fine.
```py
import taichi as ti

@ti.data_oriented
class Test:
	@ti.kernel
	def test(self):
		pass

ti.init(ti.gpu)
test_obj = Test()
test_obj.test()
```

**Comment by archibate** [comment]
Yes, thank for reporting! Would you mind send us a solution by opening a [pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests)? Many thanks!

**Comment by lukedan** [comment]
I'll see what I can do after finishing my final projects in a week or two.

**Comment by lukedan** [comment]
Got this error while compiling on Windows using MSVC:
```
D:\Documents\Projects\taichi\taichi\python\export_lang.cpp : fatal error C1128: number of sections exceeded object file
 format limit: compile with /bigobj [D:\Documents\Projects\taichi\build\taichi_core.vcxproj]
```
The developer installation instructions said that clang should be used, so that may be the issue. However, it was compiling fine before this point, and this does not seem to be a problem that can be fixed by simply switching to clang (unless it uses the 
`/bigobj` option by default)
