### ISSUE TITLE
How can i input a vector as function parameter 

### ISSUE THREAD

**Issue by liyou54** [taichi-dev/taichi#2124]
I want to define quaternion multiplication. I need to pass in two vectors, but the kernel does not support the input vector parameter and the output vector. What should I do

**Comment by liyou54** [comment]
I tried to solve this problem, but I could not call it in the kernel.

`@ti.impl.pyfunc
def QuaternionMUL(p, q):
    ret = ti.Vector([
        p[0] * q[0] - p[1] * q[1] - p[2] * q[2] - p[3] * q[3],
        p[1] * q[0] + p[0] * q[1] + p[2] * q[3] - p[3] * q[2],
        p[2] * q[0] + p[0] * q[2] + p[3] * q[1] - p[1] * q[3],
        p[3] * q[0] + p[0] * q[3] + p[1] * q[2] - p[2] * q[1],
    ])
    return ret


def QuaternionRotationByRadis(point: ti.Vector, up: ti.Vector, r: float):
    p = ti.Vector([0, point[0], point[1], point[2]])
    w = ti.normalized(up) * ti.sin(r / 2)
    q = ti.Vector([ti.cos(r / 2), w[0], w[1], w[2]])
    q_ = ti.Vector([ti.cos(r / 2), -w[1], -w[1], -w[2]])
    ret = QuaternionMUL((QuaternionMUL(q, p)), q_)
    # return ti.Vector([ret[1],ret[2],ret[3],0])
    return ret`
    
    Traceback (most recent call last):
  File "D:/work/code/BilinPhon/data.py", line 198, in <module>
    DrawPix()
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel.py", line 571, in wrapped
    return primal(*args, **kwargs)
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel.py", line 499, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel.py", line 368, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel.py", line 365, in taichi_ast_generator
    compiled()
  File "D:/work/code/BilinPhon/data.py", line 177, in DrawPix
    QuaternionRotationByRadis(ti.Vector([1, 1, 1]), ti.Vector([0, 0, 1]), PAI / 4))
  File "D:/work/code/BilinPhon/data.py", line 83, in QuaternionRotationByRadis
    p = ti.Vector([0, point[0], point[1], point[2]])
  File "C:\Users\liyou\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\util.py", line 213, in wrapped
    f'{func.__name__} cannot be called in Taichi-scope'
AssertionError: __getitem__ cannot be called in Taichi-scope

Process finished with exit code 1

**Comment by archibate** [comment]
> input

You may pass vectors using a vector field with shape `()`:
```py
vec = ti.Vector.field(3, dtype=float, shape=())  # a 3D vector field with empty shape

@ti.kernel
def func():
  v = vec[None]
  print('the vector is:', v)

vec[None] = [3, 4, 5]
func()
vec[None] = [9, 8, 7]
func()
```

> output

This method can also be used for output vectors:
```py
vec = ti.Vector.field(3, dtype=float, shape=())  # a 3D vector field with empty shape

@ti.kernel
def func():
  vec[None] = [1, 2, 3]

func()
v = vec[None].value
print(v)  # [1. 2. 3.]
```

**Comment by liyou54** [comment]
You mean using global variables, but I need to call many times this method, maybe in ndarrange (), so it doesn't seem to work. I saw the implementation of dot such as source code, and then tried to write one. As mentioned above, he could not call in the kernel.

**Comment by liyou54** [comment]
Thanke, I've solved it 

```
@ti.impl.pyfunc
def QuaternionMUL(p, q):
    ret = ti.Vector([
        p[0] * q[0] - p[1] * q[1] - p[2] * q[2] - p[3] * q[3],
        p[1] * q[0] + p[0] * q[1] + p[2] * q[3] - p[3] * q[2],
        p[2] * q[0] + p[0] * q[2] + p[3] * q[1] - p[1] * q[3],
        p[3] * q[0] + p[0] * q[3] + p[1] * q[2] - p[2] * q[1],
    ])
    return ret

@ti.impl.pyfunc
def QuaternionRotationByRadis(point, up, r):
    p = ti.Vector([0, point[0], point[1], point[2]])
    w = ti.normalized(up) * ti.sin(r / 2)
    q = ti.Vector([ti.cos(r / 2), w[0], w[1], w[2]])
    q_ = ti.Vector([ti.cos(r / 2), -w[1], -w[1], -w[2]])
    ret = QuaternionMUL((QuaternionMUL(q, p)), q_)
    # return ti.Vector([ret[1],ret[2],ret[3],0])
    return ret
```
