### ISSUE TITLE
After running for a while, FPS will drop, and finally the GUI will crash.

### ISSUE THREAD

**Issue by tsotfsk** [taichi-dev/taichi#2181]
Starting
![image](https://user-images.githubusercontent.com/41030789/106999486-3e822e00-67c1-11eb-8847-0d31e0de505e.png)

Crashing
![image](https://user-images.githubusercontent.com/41030789/106999726-a9336980-67c1-11eb-99c3-9f338d490d7b.png)

My environment
System: win 10 19042
![image](https://user-images.githubusercontent.com/41030789/106999542-5b1e6600-67c1-11eb-8b14-289c173bd423.png)

**Comment by archibate** [comment]
Did it show any error message on crash? Thanks!

**Comment by tsotfsk** [comment]
No, it didn't. My computer will run at a slow speed and the demo's screen will freeze before crashing. 

I find that if I just run this demo and step away from keyboard, it will crash after running about 7 minutes, the FPS will drop from 58 to 46 slowly, the window will disappear for a while without leaving any message. 

However, if I do mouse operations frequently, it will crash soon, maybe thirty seconds?

I also find that after running this demo, it's RAM usage will increase from 92.8MB to 96.3MB, the window will disappear at nearly 96.3MB.

**Comment by k-ye** [comment]
Hi,

Just an idea. If you completely disable the GUI and run it for a while, will it still crash? How about memory consumption? (I'm wondering if that's a memory leak in the GUI)

**Comment by tsotfsk** [comment]
@k-ye I use the method you said and find the usage of RAM will always at 86.8MB. The program will not crash again. Thanks for your help, maybe I should use other GUI libraries as a temporary replacement.

**Comment by k-ye** [comment]
Ah OK, thanks for the confirmation! Yeah the GUI part probably didn't release some mouse/keyboard event objects..
