### ISSUE TITLE
Improt Error :module 'sourceinspect' has no attribute 'stack'

### ISSUE THREAD

**Issue by Wallelhw** [taichi-dev/taichi#2194]
The vs 2019 report the import error(Title) when just run the demo at  _Overview_ of Doc.
I'm sure that install [Microsoft Visual C++ Redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe) ,and python 3.7.8(64bit).
logs follows:
[Taichi] mode=release
[Taichi] version 0.7.14, llvm 10.0.0, commit 58feee37, win, python 3.7.8
module 'sourceinspect' has no attribute 'stack'
堆栈跟踪:
 >  File "C:\Wallelhw\physical\PythonApplication1\PythonApplication1.py", line 2, in <module>
 >    import taichi as ti
已加载“__main__”
已加载“runpy”

I have been tried my dest for this question!please,thanks many.

**Comment by archibate** [comment]
Sorry! This is an bug of `sourceinspect` v0.0.5, which is my fault. For now, please run this command to downgrade it:
```py
python -m pip install sourceinspect==0.0.4
```








双笙子佯谬
1931127624@qq.com

上海拆桥学院
桥梁爆破小组首席执行官

---Original---

**Comment by Wallelhw** [comment]
The question sloved,Thanks

> Sorry! This is an bug of `sourceinspect` v0.0.5, which is my fault. For now, please run this command to downgrade it: ```py python -m pip install sourceinspect==0.0.4 ``` 双笙子佯谬 1931127624@qq.com 上海拆桥学院 桥梁爆破小组首席执行官
> […](#)
> ---Original--- From: "Wallelhw"<notifications@github.com&gt; Date: Tue, Mar 2, 2021 11:06 AM To: "taichi-dev/taichi"<taichi@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: [taichi-dev/taichi] Improt Error :module 'sourceinspect' has no attribute 'stack' (#2194) The vs 2019 report the import error(Title) when just run the demo at Overview of Doc. I'm sure that install Microsoft Visual C++ Redistributable ,and python 3.7.8(64bit). logs follows: [Taichi] mode=release [Taichi] version 0.7.14, llvm 10.0.0, commit [58feee3](https://github.com/taichi-dev/taichi/commit/58feee3753a76f276bd25dd00ab13eb311a2e60e), win, python 3.7.8 module 'sourceinspect' has no attribute 'stack' 堆栈跟踪: File "C:\Wallelhw\physical\PythonApplication1\PythonApplication1.py", line 2, in import taichi as ti 已加载“main” 已加载“runpy” I have been tried my dest for this question!please,thanks many. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
