### ISSUE TITLE
[example] Usage of grid variable in mgpcg example

### ISSUE THREAD

**Issue by houkensjtu** [taichi-dev/taichi#2215]
In the original version of mgpcg, the author seems to use the "grid" as an intermediate variable to place his fields:

```Python
grid = ti.root.pointer(ti.ijk, [N_tot//4]).dense(ti.ijk,4)
grid.place(x)
grid.place(p)
grid.place(Ap)
```
However, after some refactoring of code, the place() function was concatenated to the "pointer", which made the existence of the grid variable kind of unnecessary:

```Python
grid = ti.root.pointer(ti.ijk, [N_tot // 4]).dense(ti.ijk, 4).place(x, p, Ap)
# Why not just do follows
ti.root.pointer(ti.ijk, [N_tot // 4]).dense(ti.ijk, 4).place(x, p, Ap)
```

I can create a pull request if you agree with my understanding. thx

**Comment by yuanming-hu** [comment]
Good point - the `self.grid` variable is no longer needed. Please PR with your changes :-) Thanks!

**Comment by houkensjtu** [comment]
Thanks! I might add some other minor code refactoring and combine them into one PR :hatched_chick:
