### ISSUE TITLE
[stacktrace] with stackprinter

### ISSUE THREAD

**Issue by WangWei90** [taichi-dev/taichi#2216]
**Describe the bug**
Maybe the following issue is related with taichi's python ast parser. I am not clear. 

https://github.com/cknd/stackprinter/issues/45

> (Interestingly, I could only reproduce this bug with taichi so far, so I assume it's an edge case where the interpreter confuses itself during the heavy introspection & dynamic rewriting of the stack that taichi seems to be doing.)

**To Reproduce**
I make two minimal examples in the link. 

https://github.com/cknd/stackprinter/issues/45

----
Thank you for making the taichi language, I am shifting my computations from numpy to taichi now. 

I also code in julia, but python ecosystem is hard to leave. I hope taichi's error message will be more concise 😃

**Comment by k-ye** [comment]
I haven't looked too deep in this problem. But as explained in the other question in #2217, because of the heavy manipulation of the Python AST, it is likely that the stack trace is modified at some point..
