### ISSUE TITLE
failed installation of taichi program

### ISSUE THREAD

**Issue by gugeyao** [taichi-dev/taichi#2237]
**Describe the bug**
With python 3.8 and gcc 7.5.0 on  CentOS/Red Hat, taichi program cannot run properly.

**Log/Screenshots**

```

[*** ~]$ python3
Python 3.8.0 (default, Mar 25 2021, 20:52:06)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taichi as ti
[Taichi] mode=release
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/taichi/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python3.8/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import *
  File "/usr/local/lib/python3.8/site-packages/taichi/core/util.py", line 168, in <module>
    os.symlink(link_src, link_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so' -> '/usr/local/lib/python3.8/site-packages/taichi/core/../lib/libtaichi_core.so'
>>>
[*** ~]$ sudo /usr/local/bin/python3
Python 3.8.0 (default, Mar 25 2021, 20:52:06)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taichi as ti
[Taichi] mode=release
Share object taichi_core import failed, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/taichi/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python3.8/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import *
  File "/usr/local/lib/python3.8/site-packages/taichi/core/util.py", line 169, in <module>
    import_ti_core()
  File "/usr/local/lib/python3.8/site-packages/taichi/core/util.py", line 46, in import_ti_core
    raise e from None
  File "/usr/local/lib/python3.8/site-packages/taichi/core/util.py", line 34, in import_ti_core
    import taichi_core as core
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /usr/local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so)
Consider installing libtinfo5: sudo apt-get install libtinfo5
```

**Additional comments**
If I can run taichi on the machine, can I export taichi kernels to C source code?

**Comment by k-ye** [comment]
Hi,

Could you set `LD_LIBRARY_PATH` as suggested by https://stackoverflow.com/a/20357035/12003165? You can also check if your `libstdc++.so` has the correct CXXABI version by doing `strings /path/to/libstdc++.so.6 | grep CXXABI_1.3.11` (https://stackoverflow.com/q/49875588/12003165)

> If I can run taichi on the machine, can I export taichi kernels to C source code?

Yep, there is a `ti.cc` (C99 compatible) backend :) See https://taichi.readthedocs.io/en/stable/export_kernels.html

**Comment by gugeyao** [comment]
> Hi,
> 
> Could you set `LD_LIBRARY_PATH` as suggested by https://stackoverflow.com/a/20357035/12003165? You can also check if your `libstdc++.so` has the correct CXXABI version by doing `strings /path/to/libstdc++.so.6 | grep CXXABI_1.3.11` (https://stackoverflow.com/q/49875588/12003165)
> 
> > If I can run taichi on the machine, can I export taichi kernels to C source code?
> 
> Yep, there is a `ti.cc` (C99 compatible) backend :) See https://taichi.readthedocs.io/en/stable/export_kernels.html

Thanks for the quick reply!
I had added lines below to ~/.bashrc before.
```bash
export PATH=/usr/local/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
```
I just tried the command below.
```
[*** ~]$ strings /usr/local/lib/libstdc++.so.6 | grep CXXABI_1.3.11
strings: '/usr/local/lib/libstdc++.so.6': No such file
```

**Comment by k-ye** [comment]
It seems like your gcc 7.5.0 not been properly installed. There was such an issue in the forum before: https://forum.taichi.graphics/t/import-taichi-version-cxxabi-1-3-11-not-found/367, where the solution was to install gcc/g++ 6. 

1. You can ` find / -name 'libstdc++.so.6'` to see where all the `libstdc++.so` are on your system.
2. You can also use `ld --verbose | grep SEARCH_DIR` to see what the default linker search paths are.

**Comment by zhangyuannie** [comment]
Hi,

Could you try `sudo yum install ncurses-compat-libs`?

**Comment by gugeyao** [comment]
Thanks! problem solved.
