### ISSUE TITLE
[security] CodeCov's Bash Uploader Security Mitigations

### ISSUE THREAD

**Issue by rexwangcc** [taichi-dev/taichi#2267]
**Describe the bug**

**Note: This is not a bug of taichi**

Recently CodeCov made an annoucement that their bash uploader was attacked and injected, the full report can be found [here](https://about.codecov.io/security-update/), the consequence is that anyone who have used the bash uploader since Jan 31, 2021 is at a potential credential leak risk.

It seems taichi is using the bash uploader in serveral places in the CI pipelines. So we need to take proper actions according to the CodeCov guide to mitigate the issue ASAP.

Potential actions maybe:

- Update secrets in main repo that are used in the same Actions/CI that's calling the CodeCov Uploader, such as `secrets.PYPI_PWD`, `travis.secure`, etc.
- Scan other repositories under the `taichi-dev` org that are using codecov and update the credentials accordingly, such as [taichi_elements](https://github.com/taichi-dev/taichi_elements), [taichi_glsl](https://github.com/taichi-dev/taichi_glsl), [test_actions](https://github.com/taichi-dev/test_actions), etc.

**Comment by k-ye** [comment]
Thanks for catching this! Fixed
