### ISSUE TITLE
[attribute error] module 'taichi' has no attribute 'warning'

### ISSUE THREAD

**Issue by jakoaltrd** [taichi-dev/taichi#2285]
[bug report] when I run the examples in taichi , it occurs that "module 'taichi' has no attribute 'warning' "

[sample] diffmpm3d.py

[log]
Traceback (most recent call last):
  File "difftaichi/examples/diffmpm3d.py", line 60, in <module>
    def place():
  File "/home/deve/.local/lib/python3.8/site-packages/taichi/lang/util.py", line 174, in wrapped
    return func(*args, **kwargs)
  File "/home/deve/.local/lib/python3.8/site-packages/taichi/lang/impl.py", line 451, in layout
    ti.warning(
AttributeError: module 'taichi' has no attribute 'warning'

[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-hbpg97dd
[Taichi] version 0.7.16, llvm 10.0.0, commit bca037cf, linux, python 3.8.5
[Taichi] Starting on arch=opengl

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by ryanaltair** [comment]
workaround is add 
`setattr(ti,'warning',ti.warn)` before `ti.init()`
