### ISSUE TITLE
Add Vulkan backend

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#2298]
**Concisely describe the proposed feature**

This is a collaborated efforts between @g1n0st and I. We have finished the implementation locally and will upstream the code back. It is based on SPIR-V. As always, the Vulkan backend starts simple and only supports `dense`.

**Describe the solution you'd like (if any)**

**Additional comments**

**Comment by bobcao3** [comment]
#1641 #992 & GL backend. Given there are multiple on-going backend effort, would it possible to build a code generator that targets the "Logical" memory model in SPIR-V so that GL, Vulkan, Metal, and DX backends can all use SPIR-V? It should be possible to directly translate CHI to SPIR-V, or translate LLVM IR to SPIR-V (the problem here is probably the memory model).

**Comment by k-ye** [comment]
Thanks for the comments!

> would it possible to build a code generator that targets the "Logical" memory model in SPIR-V so that GL, Vulkan, Metal, and DX backends can all use SPIR-V?

Good point. Being able to unify the codegens is definitely a great thing to have. If it were to only support `dense`, SPIR-V is likely the solution for all. But as soon as we want to support sparse data structures (particularly `pointer`, which requires some sort of device-side memory management), the different levels of expressiveness of these backend APIs could make the  unification rather difficult.

1. As you've pointed out, memory model is a major issue here. The SPIR-V codegen needs to know how to generate instructions depending on whether the physical memory model is supported or not. 
2. Sparse data structure requires not only a codegen, but also a small runtime system to track various states. For example, https://github.com/taichi-dev/taichi/blob/master/taichi/runtime/llvm/runtime.cpp is the LLVM's sparse runtime implementation. I doubt if it is possible to re-write this in SPIR-V using only the logical memory model. But even if it is, it is not going to be very maintainable.

> It should be possible to directly translate CHI to SPIR-V, or translate LLVM IR to SPIR-V 

Precisely! I'm not too sure how mature the LLVM -> SPIR-V path is, but it's not too difficult to directly translate CHI to SPIR-V. Actually, @g1n0st has already implemented a huge amount of works for SPIR-V :-)

I think once @g1n0st 's SPIR-V codegen gets merged, we can try to get it working on other backends by supporting just `dense`.  The situation may be a bit different for Metal, though, since Metal backend does have a sparse runtime implementation as well. However, if all the SNodes are `dense`, we can see if the SPIR-V cross compiled MSL has an advantage over the existing Metal source code codegen :)

Also I wonder if it is possible to translate SPIR-V targeting the "physical" memory model back to MSL, given that Metal is closer to CUDA/OpenCL rather than OpenGL?

**Comment by bobcao3** [comment]
I have some temporary SPIR-V work in this branch: https://github.com/bobcao3/taichi/tree/vulkan

I'm just hijacking the entire OpenGL backend but also generate a list of SPIR-V assemblies at the same time. I have tried to compile these assemblies back to GLSL and substituted them using NSight, they mostly work but there are some bugs and a lot of not implemented stuff.

**Comment by bobcao3** [comment]
I think SPIR-V Cross is capable of translating the Physical memory model, not quite sure as I haven't really tried. It is definitely possible, just that I'm not sure whether we need to roll our own one. Since there's also work going on targeting DirectX, and the possibilities of future console ports, I think it is needed to maintain two common runtimes: one for logical, one for physical. Maybe the runtime can be written in glsl or hlsl and compile those to SPIR-V functions (instead of what I'm doing in my branch, which is basically hand writing assemblies).

**Comment by bobcao3** [comment]
I also wonder in terms of performance, does physical memory model introduce additional overhead? It seems like in a few examples, the use of physical memory in CUDA is seemingly dragging it down compared to OpenGL. #2324 It could be a LLVM issue there. Something for sure is that the fixed function GPU hardware will provide additional bandwidth or lower latency if we use the image samples (on GPUs, images and buffers have separate cache and load store pipelines), and these fixed function image load store pipeline is not available in physical memory model.

**Comment by k-ye** [comment]
> Maybe the runtime can be written in glsl or hlsl and compile those to SPIR-V functions 

I think that's an ambitious goal... Right now I can think of these complexities:

1. atomic lock implementation: we need to make sure that there is no deadlock.
2. Following 1, we need to make sure there is no memory order issue.
3. GPU side memory allocator + in-place constructor. Not sure how feasible it is to express these using GLSL/HLSL.

> I also wonder in terms of performance, does physical memory model introduce additional overhead?

It could be, although I doubt if that is going to be a major bottleneck. #2324 seems to imply that the CUDA backend implementation results in lots of unnecessary memory accesses. As for the image samplers, note that the OpenGL backend still uses compute shader + SSBO (you've probably figured this out yourself).

**Comment by bobcao3** [comment]
What I mean is the possibility to have some of the load stores be on the
image pipeline. From my experience with compute shaders, maximal throughput
is achieved when both the image pipe (TEX on Nvidia) and buffer pipe (MEM,
sometimes just L1 / L2 on Nvidia)

For the runtime part, I'm not very familiar with the requirements needed
and structures used within taichi. Is there some C code for the CUDA side
runtime to look at? Another thing is I know systems out there that builds
octree on GPU with just graphics compute API (Vulkan, DX, GL), so at least
that and the relavent block allocation is possible. However it could be
hard if the blocks are arbitrary sized or shaped. (I don't believe there's
dynamic allocation where the allocation block size is not known at compile
time?)

**Comment by bobcao3** [comment]
Some reference: https://www.khronos.org/opengl/wiki/Atomic_Counter

If some atomic value is global, and if every thread is potentially using
it, using an atomic counter instead of generic atomic instructions would
bring huge performance benefits

**Comment by k-ye** [comment]
> What I mean is the possibility to have some of the load stores be on the
image pipeline.

I see. It's a bit confusing because originally I thought you were referring to https://www.khronos.org/opengl/wiki/Image_Load_Store. We have considered the possibility to use the rasterization pipeline for GPGPU tasks a while back. It might not fit Taichi's design space very well due to a  number of factors: 1) atomics, 2) memory order, 3) texture load/store is not as handy as directly accessing the SSBO.  Of course this might not be as challenging as it seems. It will be great if someone could actually try implementing a basic part of Taichi using the graphics pipeline and demonstrate the performance advantages.

> Is there some C code for the CUDA side runtime to look at? 

https://github.com/taichi-dev/taichi/blob/master/taichi/runtime/llvm/runtime.cpp is written in C and is for both CUDA and the CPU backend. This CPP is first compiled to LLVM bitcode.

> I don't believe there's dynamic allocation where the allocation block size is not known at compile time?

There actually is on CUDA and Metal. However, this is  backend- and author-dependent. So it is possible to implement memory allocator based on GLSL/HLSL as well.

Memory allocation by itself is not that difficult, as you can basically simulate it with an atomic counter + a huge preallocated buffer. The tricky part is likely how you're gonna layout the data nicely in the allocated area. From my experience so far, this is quite complicated if the shader language cannot express the notion to "re-interprecast this pointer".

> If some atomic value is global, and if every thread is potentially using
it, using an atomic counter instead of generic atomic instructions would
bring huge performance benefits

Most of Taichi's atomics operate on *floating point numbers* that are stored in a buffer, since arithmetics on a Taichi `field` is designed to be atomic. As for the global atomic counter, Taichi already does a thread-local storage optimization (but sure, if we need to optimize for a specific use case, there's still a big headroom.)

**Comment by k-ye** [comment]
Closing this one. Will track the release work in https://github.com/taichi-dev/taichi/issues/2607
