### ISSUE TITLE
[LLVM] compile_runtime_bitcode does not work when file path includes space

### ISSUE THREAD

**Issue by bobcao3** [taichi-dev/taichi#2317]
**Describe the bug**
When `void compile_runtime_bitcode(Arch arch)` is generating commands to run clang or llvm-as, if the path contains a space, the path will be considered as multiple arguments to the programs. 

**To Reproduce**
Use a taichi source installation from a folder containing spaces (e.g. `C:\Users\Cheng Cao\source\repos\taichi\`) and run any example.

**Additional comments**
Fix: https://github.com/bobcao3/taichi/commit/afdefbe76c7764cbc58f28700d1c9d23c4b5cfce

**Comment by bobcao3** [comment]
PR: https://github.com/taichi-dev/taichi/pull/2318

**Comment by k-ye** [comment]
Fixed by #2318
