### ISSUE TITLE
taichi-nightly package that automatically detects environment

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#233]
Two motivations:
 - For most users, it is a bit troublesome to determine which one among `taichi-nightly`, `taichi-nightly-cuda-10-0`, `taichi-nightly-10-1` to install
 - If another Python project depends on, say, `taichi-nightly-10-1`, the project developer would add `taichi-nightly-10-1` into his `requirements.txt` or `setup.py`. This breaks his package on an environment without `CUDA 10.1`

**Comment by yuanming-hu** [comment]
...and rename taichi-nightly to taichi-nightly-cpu

**Comment by archibate** [comment]
I notice that with `taichi-nightly-cuda-10-0` installed, simply `ti.init(arch=ti.x86_64)` can run taichi on cpu.

**Comment by yuanming-hu** [comment]
Yeah, but it will first look for `libcudart.so` (which is probably installed on your system but not other systems without CUDA)
