### ISSUE TITLE
Coud Taichi support micropython env?

### ISSUE THREAD

**Issue by tim3385** [taichi-dev/taichi#2331]
micropython is embedded into our software. our software could run on wasm/windows/android/ios/macos/linux and etc.
note. real multi-thread is not a standard in wasm since "shared worker" feature is not supported in many browsers.
谢谢

**Comment by bobcao3** [comment]
We are binding to python using pybind and I don't think micro python has all the required features to support this. I don't think it's really possible, maybe AOT is a better solution in these cases. Closing this issue for now
