### ISSUE TITLE
global running time setting error , with ti.init(random_seed=)

### ISSUE THREAD

**Issue by spdcoding** [taichi-dev/taichi#2333]
[Taichi] version 0.7.18, llvm 10.0.0, commit 9a31814b, linux, python 3.6.7
It seems like that "random_seed" parameter has been deprecated in the newest version of taichi. Maybe, related documentation should be updated

reproduce:
python3 -c "import taichi as ti; ti.init(random_seed=1)"

result:
[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-on5gm_8n
[Taichi] version 0.7.18, llvm 10.0.0, commit 9a31814b, linux, python 3.6.7
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/taichi/lang/__init__.py", line 202, in init
    f'Unrecognized keyword argument(s) for ti.init: {", ".join(unexpected_keys)}'
KeyError: 'Unrecognized keyword argument(s) for ti.init: random_seed'

**Comment by BillXu2000** [comment]
Could you please make a clearer description about this bug?
A sample code or log, for example, will be helpful to reproduce and fix the bug.

**Comment by victoriacity** [comment]
The `random_seed` argument is a feature added by #2297. I don't know why its documentation gets merged by 0.7.18 in advance. I tested with 0.7.19 and it should be working fine.
