### ISSUE TITLE
[Perf] Avoid unnecessary cuMemcpy in to_numpy()

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#2344]
**Concisely describe the proposed feature**
`to_numpy()` is sometimes too slow now on GPUs. This is because `to_numpy()` calls `tensor_to_ext_arr()`, which doesn't have the information that we don't need the original value of the newly created numpy array. So we have an unnecessary copy from host to device here:
https://github.com/taichi-dev/taichi/blob/c824a8b145c2d09d52dc7c0a65b91a102e451cc9/taichi/backends/cuda/codegen_cuda.cpp#L71-L72

We can remove this CUDA memcpy to accelerate it.

**Describe the solution you'd like (if any)**
Add a compiler hint to `tensor_to_ext_arr()` when called by `to_numpy()` (or `to_torch()`), that we will fully write the values in the external array. Then we can remove the unnecessary copy in codegen_cuda.cpp.

**Additional comments**
See also `ti.loop_unique(covers=...)`, but that one only supports SNodes now.

Shall we add the new hint to the CHI IR or to the kernel?

**Comment by k-ye** [comment]
Sounds great. Note that GLSL has type qualifiers like `in`, `out` or `inout`, which is a more generic approach than hinting `tensor_to_ext_arr()`. We can also analyze each kernel itself to see if the kernel only reads the external array, or does both read and write to it.

**Comment by bobcao3** [comment]
Merging with #4048
