### ISSUE TITLE
libtinfo installation signature issue on Arch

### ISSUE THREAD

**Issue by ifsheldon** [taichi-dev/taichi#2347]
**Describe the bug**
Cannot install required `libtinfo` with the guide in [trouble shooting](https://taichi.readthedocs.io/en/stable/install.html).
I have edited `/etc/pacman.conf` according to the guide but when I tried `sudo pacman -Syy ncurses5-compat-libs`, an error occurred, implying the signature is wrong (`invalid or corrupted package (PGP signature)`)

**Log/Screenshots**

```
~/ sudo pacman -Syy ncurses5-compat-libs
:: Synchronizing package databases...
 core                                                                                                          165.5 KiB   742 KiB/s 00:00 [####################################################################################] 100%
 extra                                                                                                        1968.1 KiB  8.47 MiB/s 00:00 [####################################################################################] 100%
 community                                                                                                       6.6 MiB  27.8 MiB/s 00:00 [####################################################################################] 100%
 multilib                                                                                                      180.5 KiB  0.00   B/s 00:00 [####################################################################################] 100%
 archlinuxcn                                                                                                  1618.0 KiB   642 KiB/s 00:03 [####################################################################################] 100%
resolving dependencies...
looking for conflicting packages...

Packages (1) ncurses5-compat-libs-6.2-1

Total Download Size:   0.22 MiB
Total Installed Size:  0.59 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 ncurses5-compat-libs-6.2-1-x86_64                                                                             223.8 KiB  6.43 MiB/s 00:00 [####################################################################################] 100%
(1/1) checking keys in keyring                                                                                                             [####################################################################################] 100%
(1/1) checking package integrity                                                                                                           [####################################################################################] 100%
error: ncurses5-compat-libs: signature from "lilac (build machine) <lilac@build.archlinuxcn.org>" is unknown trust
:: File /var/cache/pacman/pkg/ncurses5-compat-libs-6.2-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
```

**Additional comments**
It seems irrelevant to Taichi itself, but please consider reproducing it, fixing this issue and updating the documentation. I fixed this problem by `link`ing `libtinfo.so.6` according to [this post](https://stackoverflow.com/questions/60714842/manjaro-install-ncurses5-compat-libs). It seems working and I can import Taichi now in Python. In the post, the answer said libtinfo6 is back-ward compatible with libtinfo5 that is required in Taichi, but I'm not sure since I am new to Taichi. So, if it's okay, please check your test cases using libtinfo6. If everything goes just right, I think you can just update the dependency and the documentation to use libtinfo6. Thanks!

**Comment by k-ye** [comment]
Thanks for reporting this. The doc is actually around https://github.com/taichi-dev/taichi/blame/master/docs/install.rst#L143-L150, would you be interested in sending a PR to update it :-) ?

**Comment by ifsheldon** [comment]
Yeah, sure. But, before that, I'd like to double check whether using a newer version of `libtinfo` will break anything?

**Comment by k-ye** [comment]
> Yeah, sure. But, before that, I'd like to double check whether using a newer version of `libtinfo` will break anything?

It's pretty safe :-)

**Comment by ifsheldon** [comment]
Well then I can make an ad-hoc quick fix to the doc, but I think a better solution is to change this dependency to not depend on a specific version of `libtinfo`. Any suggestions?
