### ISSUE TITLE
Python 3.9 support on Linux

### ISSUE THREAD

**Issue by PumpkinCheshire** [taichi-dev/taichi#2359]
**Concisely describe the proposed feature**
 Release the python 3.9 support for Linux. I noticed there is no 0.7.20-cp39-manylinux1 wheels in pypi, therefore i received
```
ERROR: Could not find a version that satisfies the requirement taichi (from versions: none)
ERROR: No matching distribution found for taichi 
```

**Describe the solution you'd like (if any)**
Release the latest cp39-manylinux wheels on pypi

**Additional comments**
Thanks

**Comment by Leonz5288** [comment]
We just released version 0.7.21 which supports python 3.9! Feel free to upgrade and try it out.

**Comment by PumpkinCheshire** [comment]
Sorry to interrupt. It seems the taichi-0.7.25-cp39-cp39-manylinux1_x86_64.whl is missing.. again. Is this intentional or an unexpected error. 
If this is intentional, and the update around linux python 3.9 will reappear in the next version, I will not ask this question again.

**Comment by k-ye** [comment]
Hey @PumpkinCheshire 

It's a limitation in our Linux release pipeline, where it's quite hard to restart a failed release. Hopefully the next release 
 will cover all the Python versions. Sorry about  the inconvenience
