### ISSUE TITLE
 Cooridnate offset on SNode data structures

### ISSUE THREAD

**Issue by xuhao1** [taichi-dev/taichi#2360]
**Concisely describe the proposed feature**
Coordinate offset is a nice feature, however it current only support field with fix shape. coordinate offset for SNode structures will be very convenient.

For example
```python
v = ti.field(dtype=ti.i32, shape=(), offset = (-1000, -1000, -1000))
B = ti.root.pointer(ti.ijk, (200, 200, 200))
B = B.dense(ti.ijk, (10, 10, 10))
B.place(v)
```

and access by
```python
v[-1, -400, 4] = 12345
```

**Comment by k-ye** [comment]
Hi, `place()` does have an `offset` argument: https://github.com/taichi-dev/taichi/blob/6d09eea34c108d98dfe97d805e4356a1b515b166/python/taichi/lang/snode.py#L60

**Comment by xuhao1** [comment]
@k-ye Thanks!
