### ISSUE TITLE
Fix CI auto formatter

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#2369]
**Concisely describe the proposed feature**

Trigger heavy CI tests only when specific keyworks are used in a PR

**Describe the solution you'd like (if any)**

Use existing Github Actions to detect specific keyword

**Comment by k-ye** [comment]
We can now trigger auto format via `/format`

**Comment by xumingkuan** [comment]
https://github.com/taichi-dev/taichi/pull/2438/commits/65e8ec4edeacc9eeb1b779595a09636b479b5b6c looks somewhat correct but horrible...
