### ISSUE TITLE
Get wrong minimum in GPU parallelized loop

### ISSUE THREAD

**Issue by xchhuang** [taichi-dev/taichi#2378]
**Describe the bug**
I found the result wrong when I tried to get the minimum of a `ti.field` on GPU parallelized loop.

**To Reproduce**
Here is an example:

```py
import numpy as np
import taichi as ti

np.random.seed(123)
real = ti.f32
ti.init(ti.gpu)  # cpu works

n = 10000
a = ti.field(dtype=real, shape=n)
a.from_numpy(np.random.rand(n))


@ti.kernel
def find_minimum_serialized():
    min_error = np.inf
    min_index = 0
    for _ in range(1):
        for i in ti.ndrange((0, n)):
            if min_error > a[i]:
                min_error = a[i]
                min_index = i
    print('Minimum(serialized):', min_error, min_index)


@ti.kernel
def find_minimum_parallelized():
    min_error = np.inf
    min_index = 0
    for i in ti.ndrange((0, n)):
        # min_error = min(min_error, a[i])
        if min_error > a[i]:
            min_error = a[i]
            min_index = i
    print('Minimum(parallelized):', min_error, min_index)


find_minimum_serialized()       # correct
find_minimum_parallelized()     # wrong
```

**Log/Screenshots**

```
[Taichi] mode=release
[Taichi] version 0.7.14, llvm 10.0.0, commit 58feee37, win, python 3.7.10
[I 05/29/21 08:46:18.648] [shell.py:_shell_pop_print@31] Graphical python shell detected, using wrapped sys.stdout
[Taichi] Starting on arch=cuda
[Taichi] materializing...
Minimum(serialized): 0.000068 2583
Minimum(parallelized): 0.951559 8128
```

**Comment by k-ye** [comment]
You need to use `atomic_min()`  in parallel kernels, or there will be data races. That said, I don't think it's feasible to store both the value and the index, as that would require some sort of mutex/critical section.

**Comment by xchhuang** [comment]
I see. Would it make sense to support returning both value and index in the near future? Thank you.

**Comment by k-ye** [comment]
> Would it make sense to support returning both value and index in the near future? Thank you.

Ah that's an interesting idea, although we haven't really thought about this in the near future. At a higher level, it would require Taichi to support some kind of more complicated atomic data structures.

**Comment by xchhuang** [comment]
> > Would it make sense to support returning both value and index in the near future? Thank you.
> 
> Ah that's an interesting idea, although we haven't really thought about this in the near future. At a higher level, it would require Taichi to support some kind of customizable atomic data structures.

Good to know, thanks!
