### ISSUE TITLE
Bundled issues of `cannot have oprand ***` and `break` with autodiff 

### ISSUE THREAD

**Issue by ifsheldon** [taichi-dev/taichi#2387]
**Describe the bug**
Seems somehow assigning new values to a local variable and using `break` in a kernel with `Tape` are not supported. 

**To Reproduce**
My kernel code is a bit long so I give a brief version here. 

```py
@ti.kernel
def DVR_differender_pass(cam_pos_x: float, cam_pos_y: float, cam_pos_z: float, view_u: float, view_v: float):
    # static preparations
    # -- some variable declarations here
    # -- zipped
    for x, y in differender_pixels:
        # preparations
        # some variable declarations here
        #  zipped
        # some numerical computations here
        #  zipped
       
        # test ray intersection
        in_pos, out_pos, intersected = calc_in_out(view_pos, looking_direction)
        if intersected:
            # some numerical computations here
            # zipped
            composite_color = tl.vec4(0.0)
            tex_position = tex_in_pos
            for step in range(max_marching_steps):
                # some numerical computations here
                # zipped

                # compositing
                # composite_color = (1.0 - composite_color.w) * shading_color + composite_color  # 1
                # if composite_color.w > opacity_threshold:  # 2, for early stopping
                #     break  # 2
                # tex_position += ray_direction * step_size  # 3
            differender_pixels[x, y] = composite_color.xyz
            differender_pixels[x, y] = differender_transfer_function[1].xyz  # FIXME: only temp use
            l2loss[None] += (differender_pixels[x, y] - reference_pixels[x, y]).norm_sqr()
        else:
            differender_pixels[x, y] = tl.vec3(0.0)
```
The above code compiles all right, but I need the code marked by `1`, `2` and `3`. If I uncomment line `1` alone, there is a runtime error `RuntimeError: [verify.cpp:basic_verify@57] IR broken: stmt 30054 cannot have operand 23023. If you are using autodiff, please check ... Thanks in advance!`

If I uncomment lines `2` alone, I got `Internal error occurred. Check out this page for possible solutions: ...`.

If I uncomment line `3` alone, I got `RuntimeError: [verify.cpp:basic_verify@57] IR broken: stmt 24930 cannot have operand 20473. If you are using autodiff, please check ... Thanks in advance!`

For the 1st and 3rd one, the error messages suggested me take a look at `Kernel Simplicity Rule` in the doc, but I don't think I have broken any rules stated there. 

As for the 2nd one, maybe now `break` with autodiff is not yet supported? `break` without autodiff is for sure supported, though.

For the full logs, see attached files here.
[uncomment1.txt](https://github.com/taichi-dev/taichi/files/6571601/uncomment1.txt)
[uncomment2.txt](https://github.com/taichi-dev/taichi/files/6571602/uncomment2.txt)
[uncomment3.txt](https://github.com/taichi-dev/taichi/files/6571603/uncomment3.txt)

If these 3 are expected, I think you should definitely update your documentation on Autodiff.

**Additional comments**
The full code of my kernel is here
```python
@ti.kernel
def DVR_differender_pass(cam_pos_x: float, cam_pos_y: float, cam_pos_z: float, view_u: float, view_v: float):
    # static preparations
    psfx = ti.static(float(differender_pixels.shape[0]))
    psfy = ti.static(float(differender_pixels.shape[1]))
    I_ambient = ti.static(tl.vec3(ambient))
    I_diffuse = ti.static(tl.vec3(diffuse))
    I_specular = ti.static(tl.vec3(specular))
    shape = ti.static(tl.vec3(data_field.shape[0], data_field.shape[1], data_field.shape[2]))
    for x, y in differender_pixels:
        # preparations
        cam_position = tl.vec3(cam_pos_x, cam_pos_y, cam_pos_z)
        looking_direction = (cam_center - cam_position).normalized()
        right_dir = tl.cross(looking_direction, cam_up).normalized()
        up_dir = tl.cross(right_dir, looking_direction).normalized()
        right_axis_len_vec = right_dir * view_u
        up_axis_len_vec = up_dir * view_v
        # orthogonal projection
        view_pos = cam_position - 0.5 * up_axis_len_vec - 0.5 * right_axis_len_vec
        view_pos += float(x) / psfx * right_axis_len_vec
        view_pos += float(y) / psfy * up_axis_len_vec
        # test ray intersection
        in_pos, out_pos, intersected = calc_in_out(view_pos, looking_direction)
        if intersected:
            tex_in_pos = in_pos * 0.5 + 0.5
            tex_out_pos = out_pos * 0.5 + 0.5
            max_marching_steps = int((tex_in_pos - tex_out_pos).norm() / step_size)
            ray_direction = (tex_in_pos - tex_out_pos).normalized()
            composite_color = tl.vec4(0.0)
            tex_position = tex_in_pos
            for step in range(max_marching_steps):
                unnormalized_tex_pos = tex_position * shape
                scalar = sample_volume_trilinear(unnormalized_tex_pos.x, unnormalized_tex_pos.y,
                                                 unnormalized_tex_pos.z)
                src_color = sample_transfer_function(scalar)
                opacity = src_color.w
                new_src = tl.vec4(src_color.xyz * opacity, opacity)
                # shading
                normal = get_normal(unnormalized_tex_pos.x, unnormalized_tex_pos.y, unnormalized_tex_pos.z)
                dir_dot_norm = ray_direction.dot(normal)
                diffuse_color = max(dir_dot_norm, 0.0) * I_diffuse
                v = -tex_position.normalized()
                r = tl.reflect(-ray_direction, normal)
                r_dot_v = max(r.dot(v), 0.0)
                pf = pow(r_dot_v, shininess)
                specular_color = I_specular * pf
                shading_color = tl.vec4(I_ambient + diffuse_color + specular_color, 1.0) * new_src
                # compositing
                # composite_color = (1.0 - composite_color.w) * shading_color + composite_color  # 1
                # if composite_color.w > opacity_threshold:  # 2, for early stopping
                #     break  # 2
                # tex_position += ray_direction * step_size  # 3
            differender_pixels[x, y] = composite_color.xyz
            differender_pixels[x, y] = differender_transfer_function[1].xyz  # FIXME: only temp use
            l2loss[None] += (differender_pixels[x, y] - reference_pixels[x, y]).norm_sqr()
        else:
            differender_pixels[x, y] = tl.vec3(0.0)
```
For the full source code, please see [this](https://github.com/nanovis/Differender/blob/autodiff_debug/src/hello.py). I think you can fully reproduce these issues with the source code, but if I have time, I'll try to find another example that can reproduce these issues.

I don't know if I should separately file a couple of issues, but if you want, I can do that.

Thanks a lot!

**Comment by xumingkuan** [comment]
Actually the code breaks the Kernel Simplicity Rule here:
```python
    for x, y in differender_pixels:
        ...
        if intersected:
            ...
            for step in range(max_marching_steps):
```
"each for-loop can either contain exactly one (nested) for-loop (and no other statements), or a group of statements without loops" means that, the for-loop `for x, y in differender_pixels` cannot contain the loop `for step in range(max_marching_steps)` (even indirectly!).

Consider using `for step in ti.static(range(max_marching_steps))` instead (if `max_marching_steps` is not too large to compile). This unrolls the loop, and thus does not break the Kernel Simplicity Rule.

**Comment by ifsheldon** [comment]
OK..... But it compiled if I don't uncomment any of the three marked parts. So, it can be a bug in your context if the inner loop is not aggressively optimized out. 

In my case, the max step number is around 10 - 500, so it is not so viable to statically unroll the inner loop even if it is possible.

Besides that, can please you give a temporary workaround other than loop unrolling? I can get rid of two `if` part, although with some performance penalty. However, I cannot get away from the preparations before the inner for loop. Further more, if it is not rude, I'd like to question a bit on why we enforce this restrictive rule. I can see, and surely you can as well, that such a rule greatly reduces the expressiveness of a kernel, like in my case. I can see some reasons why you enforce Global Data Access Rules, but I don't see any steps in my case will break the gradient tracking, so I don't see the reason, in my case, why Kernel Simplicity Rule should get in my way.

**Comment by k-ye** [comment]
> I'd like to question a bit on why we enforce this restrictive rule (i.e., the Kernel Simplicity Rule). I can see, and surely you can as well, that such a rule greatly reduces the expressiveness of a kernel, like in my case.

Yeah, we should remove or at least relax this rule. (That said, we don't have enough people to move this forward yet)

**Comment by xumingkuan** [comment]
> Besides that, can please you give a temporary workaround other than loop unrolling? I can get rid of two `if` part, although with some performance penalty. However, I cannot get away from the preparations before the inner for loop.

I think you can put the preparations inside the inner for loop (while putting the declarations of these variables outside the outer for loop), and use `if step == 0:` for the preparations. The inner for loop is serial so I think this will be fine.

**Comment by ifsheldon** [comment]
Setting them as global fields works, but ..... now the problem is autodiff seems to take computations but there's no gradient, and I don't know how to debug it.

**Comment by erizmr** [comment]
Hi @ifsheldon , sorry for the late reply. I am reviewing this issue and try to reproduce the bug using the legacy commit on around Jun 1st 2021 of https://github.com/nanovis/Differender but still failed to reproduce. I am wondering if you could recall and provide more description about it ? Many thanks.

**Comment by ifsheldon** [comment]
I think this issue is mainly about some subtleties that broke the Kernel Simplicity Rule, which should be strictly enforced but was not comprehensively checked by Taichi compiler. I was new to Taichi, so you can see I unintentionally broke the rules at many places. 

So, regarding this issue, I think it was mainly due to rule breaking and premature error messages. And you can safely close this issue since I managed to change the algorithm to strictly follow the kernel simplicity rules, and it works well now. 

But if you want to know more about the original algorithm, I'm happy to help as well, since you are trying to relax the kernel simplicity rules (as I understand) and this original algorithm is a excellent test case I think.

**Comment by erizmr** [comment]
Hi @ifsheldon, thanks for getting back to us. As for the Kernel Simplicity Rule (KSR), we have removed it in the recent PRs. ( Please check issue #3912 for more details.) I am interested and happy to know more about the original algorithm. It would be great if we can add it as a test case for the KSR as you have mentioned it is excellent.

**Comment by erizmr** [comment]
Closed due to that the problem mentioned in this issue has been sorted.
