### ISSUE TITLE
print formatting in kernel

### ISSUE THREAD

**Issue by ifsheldon** [taichi-dev/taichi#2396]
**Concisely describe the proposed feature**
Add support for print formatting in kernels

**Describe the solution you'd like (if any)**
Support str.format() and fstring in kernels. I'd like to see the below code work correctly.
```python
import taichi as ti

ti.init(arch=ti.cuda)
field = ti.Vector.field(3, dtype=ti.float32, shape=5)


@ti.kernel
def test_print_format():
    for i in field:
        print("{}".format(i))
        print(i)
        print(f"{i}")


test_print_format()
```

**Comment by Leonz5288** [comment]
@ifsheldon Hi there, we have just release taichi 0.7.29 which includes string.format() as a new feature. Feel free to test it out. f"string" is not supported yet but we will implement this very soon.
