### ISSUE TITLE
libtinfo6 required when installing from pip (v. 0.7.21)

### ISSUE THREAD

**Issue by marekjg** [taichi-dev/taichi#2417]
**Describe the bug**
When installing default version on pip (0.7.21), libtaichi_core.so is linked with libtinfo6 not libtinfo5 ausing problems on systems with libtinfo5 only. 

**To Reproduce**
Install taichi on ubuntu 18.04 and try to load the library. 

**Log/Screenshots**
```
ldd libtaichi_core.so
	linux-vdso.so.1 (0x00007fff74ff5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb673241000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb6730f2000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fb672fb5000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb672f99000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb672f93000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007fb672f63000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb672f3e000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb672d5d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb672b6b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb6766bb000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fb672b41000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb672b26000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fb672b1e000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fb672b16000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fb672afc000)
```

**Comment by k-ye** [comment]
* A hack fix: https://github.com/taichi-dev/taichi/issues/2347
* Also what happens if you `sudo apt install libtinfo-dev`? Will that install `libtinfo6` in `/lib/x86_64-linux-gnu`?
* Ultimately, we should release a prebuilt LLVM that sets `LLVM_ENABLE_TERMINFO=OFF` (https://github.com/taichi-dev/taichi/issues/791#issuecomment-615364660), given how many times this issue has bitten us

**Comment by Leonz5288** [comment]
We have updated llvm-10 binaries for Linux and llvm installation instruction to remove lintinfo.
