### ISSUE TITLE
Documentation: what is ti.root.lazy_grad()?

### ISSUE THREAD

**Issue by ifsheldon** [taichi-dev/taichi#2423]
When I read the `difftaichi` example code, I found code like
```python
ti.root.dense(ti.ijk, volume_dimension).place(density)
ti.root.dense(ti.l, n_views).dense(ti.ij, render_resolution).place(target_images, images)
ti.root.place(loss)
ti.root.lazy_grad()
```
Then later in the code, we can access `.grad` attributes while no `needs_grad` was set to `True`. So, I wonder if `ti.root.lazy_grad()` has to do something with gradients but you missed this when you wrote the chapter of Advanced dense layouts, so please add more details on that. Thanks!

**Comment by victoriacity** [comment]
The explanation for `ti.root.lazy_grad()` is presented in Page 4 of [DiffTaichi Paper](https://arxiv.org/pdf/1910.00935.pdf): 

> We also provide `ti.root.lazy_grad()` to automatically place the adjoint tensors following the layout of their primals.

**Comment by ifsheldon** [comment]
OK, thanks! Please consider adding it to your documentation.
