### ISSUE TITLE
taichi version 0.7.21 requires libm.so.6: version `GLIBC_2.29' which is unavailable on Ubuntu 18.04.5

### ISSUE THREAD

**Issue by Rashfu** [taichi-dev/taichi#2439]
After installing latest taichi through `pip install --upgrade taichi` on my Ubuntu 18.04 machine, I got the following error in 'import taichi_core as core':

```
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by  home/dell/anaconda3/envs/physics/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so)
Consider installing libtinfo5: sudo apt-get install libtinfo5
```
But I have already installed libtinfo5.
I use `strings /lib/x86_64-linux-gnu/libm.so.6 | grep GLIBC_` and apparently Ubuntu 18.04 supports glibc up to version 2.27.

Reverting to the previous version `pip install taichi==0.7.16` fixed the issue.

**Comment by k-ye** [comment]
Thanks for reporting this. `libtinfo` will be removed in the release next week.

**Comment by dhl2011dj** [comment]
I meet this error also. I updated the glibc to 2.29 on my ubuntu 18.04 but found no help, and the update will cause problems on the ubuntu 18.04.

**Comment by k-ye** [comment]
Hmm, sorry I misread the issue. Right now we only have a 20.04 buildbot. Let us investigate some docker solution.

**Comment by cloudhan** [comment]
@k-ye I met the same issue.  
`strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_` gives
```
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_PRIVATE
```
so the pip package cannot work on my machine. To my knowledge,  you should follow PEP 513/571/599 to build you package.

**Comment by dhl2011dj** [comment]
> @k-ye I met the same issue.
> `strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_` gives
> 
> ```
> GLIBC_2.2.5
> GLIBC_2.2.6
> GLIBC_2.3
> GLIBC_2.3.2
> GLIBC_2.3.3
> GLIBC_2.3.4
> GLIBC_2.4
> GLIBC_2.5
> GLIBC_2.6
> GLIBC_2.7
> GLIBC_2.8
> GLIBC_2.9
> GLIBC_2.10
> GLIBC_2.11
> GLIBC_2.12
> GLIBC_2.13
> GLIBC_2.14
> GLIBC_2.15
> GLIBC_2.16
> GLIBC_2.17
> GLIBC_2.18
> GLIBC_2.22
> GLIBC_2.23
> GLIBC_2.24
> GLIBC_2.25
> GLIBC_2.26
> GLIBC_2.27
> GLIBC_PRIVATE
> ```
> 
> so the pip package cannot work on my machine. To my knowledge, you should follow PEP 513/571/599 to build you package.

我刚试过，Ubuntu 18.04 上装0.7.16的Taichi可以用，不用升级GLIBC库

**Comment by cloudhan** [comment]
We are talking about version after 0.7.21. I am trying out newly added AOT feature.

**Comment by k-ye** [comment]
Hi, we've released v0.7.23. Could you confirm if this is fixed? Thx!

**Comment by Rashfu** [comment]
> Hi, we've released v0.7.23. Could you confirm if this is fixed? Thx!

Hi, @k-ye :
Error about `GLIBC` disappear, but an error still exists. The information change as below：
```
ImportError: libz3.so.4: cannot open shared object file: No such file or directory.
Consider installing libtinfo5: sudo apt-get install libtinfo5
```

**Comment by k-ye** [comment]
Hmm, it seems that `libz3` was accidentally introduced by the LLVM-10 lib we used since v0.7.22, which should be off by default ( [`LLVM_ENABLE_Z3_SOLVER:BOOL`](https://llvm.org/docs/CMake.html)). We'll fix the prebuilt LLVM here. Meanwhile could you try https://www.howtoinstall.me/ubuntu/18-04/z3/ ?

**Comment by Rashfu** [comment]
I tried  https://www.howtoinstall.me/ubuntu/18-04/z3/ , but the error still the same:joy: .

**Comment by dhl2011dj** [comment]
> Hi, we've released v0.7.23. Could you confirm if this is fixed? Thx!

Hi, @k-ye . Since I broke my ubuntu system by updating GLIBC to 2.29 :-( , I tested taichi 0.7.23 on the subsystem(ubuntu 18.04 LTS, GLIBC 2.27) of windows. When I run examples, taichi 0.7.23 gives the error below
```
[Taichi] mode=release
Share object taichi_core import failed, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```
whereas taichi 0.7.16 went well.

**Comment by k-ye** [comment]
Sorry about the breakage :-( 

As for WSL, it sounds like "Python is not linking correctly against the shared libraries. " according to https://stackoverflow.com/questions/58596701/unable-to-connect-to-a-mysql-db-with-peewee. Is it possible to do a fresh Python installation?

> Turns out that upgrading to Python 3.7 (probably setting up Python 3.6 from scratch should've also worked) solved the issue for me - thanks a lot for having pointed me in the right direction 

```
nm taichi_core.so | grep clock_gettime
                 U clock_gettime@@GLIBC_2.17
```

**Comment by dhl2011dj** [comment]
> Sorry about the breakage :-(
> 
> As for WSL, it sounds like "Python is not linking correctly against the shared libraries. " according to https://stackoverflow.com/questions/58596701/unable-to-connect-to-a-mysql-db-with-peewee. Is it possible to do a fresh Python installation?
> 
> > Turns out that upgrading to Python 3.7 (probably setting up Python 3.6 from scratch should've also worked) solved the issue for me - thanks a lot for having pointed me in the right direction
> 
> ```
> $ nm taichi_core.so | grep clock_gettime
>                  U clock_gettime@@GLIBC_2.17
> ```

after updating to python 3.7, taichi 0.7.23 meet such error
```
[Taichi] mode=release
Share object taichi_core import failed, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "./autodiff_minimization.py", line 1, in <module>
    import taichi as ti
  File "/home/hanlin/.local/lib/python3.7/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.core import *
  File "/home/hanlin/.local/lib/python3.7/site-packages/taichi/core/__init__.py", line 1, in <module>
    from taichi.core.logging import *
  File "/home/hanlin/.local/lib/python3.7/site-packages/taichi/core/logging.py", line 4, in <module>
    from taichi.core import util
  File "/home/hanlin/.local/lib/python3.7/site-packages/taichi/core/util.py", line 171, in <module>
    import_ti_core()
  File "/home/hanlin/.local/lib/python3.7/site-packages/taichi/core/util.py", line 48, in import_ti_core
    raise e from None
  File "/home/hanlin/.local/lib/python3.7/site-packages/taichi/core/util.py", line 36, in import_ti_core
    import taichi_core as core
ImportError: libz3.so.4: cannot open shared object file: No such file or directory
Consider installing libtinfo5: sudo apt-get install libtinfo5
```
installing z3 do no help.

**Comment by cloudhan** [comment]
@Rashfu  @dhl2011dj you should install `libz3-4`

@k-ye
the same error is still there
`ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /<mask_out>/python3.9/site-packages/taichi/core/../lib/taichi_core.so)`
 
```
ldd /<mask_out>/python3.9/site-packages/taichi/core/../lib/taichi_core.so
/<mask_out>/python3.9/site-packages/taichi/core/../lib/taichi_core.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /<mask_out>/python3.9/site-packages/taichi/core/../lib/taichi_core.so)
/<mask_out>/python3.9/site-packages/taichi/core/../lib/taichi_core.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /<mask_out>/python3.9/site-packages/taichi/core/../lib/taichi_core.so)
        linux-vdso.so.1 (0x00007ffea29fd000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb601a9e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb601700000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fb6013c8000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb6011ab000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb600fa7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb600d88000)
        libz3.so.4 => /usr/lib/x86_64-linux-gnu/libz3.so.4 (0x00007fb5ffb77000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb5ff7ee000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb5ff3fd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb6052a7000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fb5ff1d5000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fb5fefa6000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb5fed8e000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fb5feb8a000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fb5fe984000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fb5fe76f000)
```

**Comment by k-ye** [comment]
@cloudhan  Do you have python3.6-3.8 installed? We encountered a bit problem and had to build 3.9 wheel in an 20.04 environment.

**Comment by cloudhan** [comment]
OK, it works now with 3.8.10. So it should only specific to 3.9.

**Comment by dhl2011dj** [comment]
@k-ye @cloudhan After installing `libz3-4`, taichi could work with python 3.6/3.7/3.8 on my WSL now.

**Comment by k-ye** [comment]
Great. We will get rid of `libz3-4` dependency later, and will try to make python3.9 build on an older Ubuntu.
