### ISSUE TITLE
ti.init reports that CUDA 11.0 is not supported on Windows Subsytem for Linux (WSL)

### ISSUE THREAD

**Issue by lester0866** [taichi-dev/taichi#2460]
I am using the windows subsystem for Linux (wsl) with cuda=11.0, where I followed the official [cuda installation guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#running-cuda) and made sure I pass the sample tests. However, when I try to run `ti.init(arch=ti.cuda)`, I am told that my current cuda version is not supported by taichi. How could I fix this?

```
$ipython
In [1]: import taichi as ti
[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-e_w8j06h
[Taichi] version 0.7.23, llvm 10.0.0, commit 0b89df86, linux, python 3.8.8

In [2]: ti.init(arch=ti.cuda)
[W 06/24/21 15:54:08.105 4009] [__init__.py:adaptive_arch_select@656] Arch=[<Arch.cuda: 5>] is not supported, falling back to CPU
[Taichi] Starting on arch=x64

$nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0

$cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
```
Thanks for your time,

Lester

**Comment by AmesingFlank** [comment]
Hi!

The reason for this is that taichi uses the CUDA driver APIs (instead of the runtime APIs), and the dynamic library for this set of APIs is stored in a weird location on WSL.

Please try adding 
```export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH````
to your `~/.bashrc` file.

**Comment by lester0866** [comment]
Yup, that works. Thanks!
