### ISSUE TITLE
Unable to find the example smoke_renderer

### ISSUE THREAD

**Issue by hooyuser** [taichi-dev/taichi#2467]
**Describe the bug**
Unable to find the example `smoke_renderer` mentioned in the article [Taichi: A Language for High-Performance Computation on Spatially Sparse Data Structures](https://arxiv.org/pdf/1804.09293.pdf).

**To Reproduce**

```py
ti example
```

**Log/Screenshots**

```
[Taichi] mode=release
[Taichi] version 0.7.20, llvm 10.0.0, commit 284f75ed, win, python 3.7.6

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://taichi.rtfd.io/zh_CN/latest
GitHub: https://github.com/taichi-dev/taichi
Forum:  https://forum.taichi.graphics

usage: ti example [-h] [-p] [-P] [-s]
                  {ad_gravity,autodiff_minimization,autodiff_regression,cg_possion,comet,cornell_box,euler,export_mesh,export_ply,export_videos,fem128,fem99,fractal,fullscreen,game_of_life,gui_image_io,gui_widgets,keyboard,laplace,mass_spring_3d,mass_spring_game,mciso,mciso_advanced,mgpcg,mgpcg_advanced,minimal,mnist,mnist_download_data,mpm128,mpm3d,mpm88,mpm99,mpm_lagrangian_forces,nbody_oscillator,odop_solar,particle_renderer,pbf2d,physarum,quadtree,rasterizer,renderer_utils,revert_image_color,sdf2d,sdf_renderer,simple_uv,stable_fluid,taichi_autodiff,taichi_bitmasked,taichi_dynamic,taichi_logo,taichi_sparse,tree_gravity,vortex_rings,waterwave}
ti example: error: the following arguments are required: name
```
It seems there is no example named `smoke_renderer`.

**Additional comments**

I'm not sure whether this issue can be categorized into "Bug report". I just take an interest in the example `smoke_renderer` and really wonder how to get access to this file. Any help would be appreciated.

**Comment by k-ye** [comment]
That's probably one of the legacy examples (Not sure if it's even written in Python or CPP...) Check out https://github.com/taichi-dev/quantaichi/tree/main/eulerian_fluid for some new smoke simulations using quantaichi :-D
