### ISSUE TITLE
Clean up _taichi_skip_traceback

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#2489]
`_taichi_skip_traceback` was added to skip a few non-important Taichi internal stack frames. This is way too ad-hoc. We should modularize Taichi itself, and remove this.

**Comment by ailzhang** [comment]
cc: @turbo0628 This issue is fairly simple in the sense that it just need to grep and delete all the _taichi_skip_traceback lines. But it might give you some sense how the frontend works :D

**Comment by turbo0628** [comment]
Thanks! It's pretty interesting to trace the code execution path :)

**Comment by strongoier** [comment]
Closed via #3902.
