### ISSUE TITLE
ti.sqrt on Matrix

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#249]
per element operation

**Comment by znah** [comment]
Also on ti.Vector and with other functions (ti.exp, ti.log, ...). How difficult can it be to implement?

**Comment by yuanming-hu** [comment]
This for raising this - implementing these is not hard, but if we should implement these needs discussions. The discussions have been moved here: https://github.com/taichi-dev/taichi/issues/833 Welcome to participate!
