### ISSUE TITLE
Rename `ti.Index` to `ti.Axis`

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#2516]
Index is a slightly oversubscribed terminology, let's switch to "Axis" to denote things like `ti.ijk`.

https://github.com/taichi-dev/taichi/blob/f276de47518d900282ccaede5c1fe0a6f6170087/taichi/ir/snode.h#L13-L30

https://github.com/taichi-dev/taichi/blob/cd96133e9e45df588c53042099a0b8b37b6c75e1/python/taichi/lang/impl.py#L592-L593

**Comment by Patil2099** [comment]
I would love to work on this

**Comment by cruedo** [comment]
Can I also try to work on it ? or can only 1 person do it at any given point of time? :)

**Comment by Patil2099** [comment]
We could have worked together but the work is finished. @cruedo

**Comment by k-ye** [comment]
> We could have worked together but the work is finished and waiting for a review.

It's not finished yet. We've replied in the PR that there are more usages of `Index` than the places you've changed, please consider fixing the PR or transferring this to others. Thanks!

**Comment by ljcc0930** [comment]
PR #2517 was closed because there has been no response for a long time. Contributions are still welcome~ @cruedo

**Comment by cruedo** [comment]
I would love to work on it. Hope I don't cause any problems. Thanks :)

**Comment by k-ye** [comment]
@cruedo would you also be interested in adding a `def axes()` function after this :-)?

https://github.com/taichi-dev/taichi/blob/fbc1f43db67de7e29b2b94b396b1c6c6b4c40d74/python/taichi/lang/impl.py#L639-L640

**Comment by cruedo** [comment]
Yeah , Sure :) 
So this function named `indices` has to be renamed to `axes` . right ?

**Comment by k-ye** [comment]
We have to keep both `indices` and `axes` for a while to give people a window for migration. Otherwise it would break everyone's code once this change gets released :-)

**Comment by cruedo** [comment]
I should have asked first. But I already created a new PR by the time I realized.

**Comment by k-ye** [comment]
Thank you @cruedo!

**Comment by cruedo** [comment]
Always , happy to help.
Thank You really, it was a fun learning experience for a beginner like me.
