### ISSUE TITLE
z level support for GUI?

### ISSUE THREAD

**Issue by mzy2240** [taichi-dev/taichi#2526]
Is there any way to assign a z level to each GUI component (let's say two scenarios for now: static-static overlap and static-dynamic overlap)? Just try to ensure a correct overlapping relationship. Thanks in advance!

**Comment by k-ye** [comment]
Hey @mzy2240 , thanks for asking this. Right now there's no explicitly support for z level. Basically the later draws would overlay on top of the former ones.

**Comment by mzy2240** [comment]
OK good to know. Maybe it is worth considering adding such a feature. Thanks anyway!
