### ISSUE TITLE
Allow taichi to use GPU on WSL2 ?

### ISSUE THREAD

**Issue by HuntFeng** [taichi-dev/taichi#2537]
I successfully install taichi on WSL2 and it runs normally when using CPU. However, when it comes to GPU (for example, CUDA), taichi seems not recognizing my CUDA on WSL2.

**Comment by AmesingFlank** [comment]
Hi.

Thanks for submitting this issue.

Taichi should work in WSL2. If you have correctly installed CUDA on WSL2, please try adding
```
export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
```
to your `~/.bashrc` file. And then run the command
```
source ~/.bashrc
```

Taichi should then be able to use CUDA without any problems.

Also see #2460

**Comment by HuntFeng** [comment]
This is super helpful. Everything works!
