### ISSUE TITLE
image in gui looks different compared to matplotlib

### ISSUE THREAD

**Issue by mzy2240** [taichi-dev/taichi#2553]
Trying to learn Taichi starting from interfacing with matplotlib, but then observe the image in GUI looks different compared to matplotlib. Since I just get my hands on Taichi so not sure whether it is a bug. Please see attached images and the minimal reproduction code. Thank you in advance! 

![image](https://user-images.githubusercontent.com/18620336/126258650-67fab819-29a4-4ea1-adbf-4b3d9ae9c3a1.png)

Code to reproduce:
```
import numpy as np
import taichi as ti
import matplotlib.pyplot as plt
import matplotlib.cm as cm

ti.init(arch=ti.cpu)

x = np.random.randn(200000)
y = np.random.randn(200000)

heatmap, xedges, yedges = np.histogram2d(x, y, bins=500)
cmap = cm.get_cmap('viridis')

pixels = ti.field(dtype=float, shape=(500, 500))
pixels.from_numpy(heatmap)

arr = pixels.to_numpy()
plt.imshow(arr, cmap=cmap)
plt.show(block=False)

gui = ti.GUI('Heatmap', res=500)
while gui.running:
    gui.set_image(cmap(arr))
    gui.show()
```

**Comment by ljcc0930** [comment]
Hi, I've tried `cv2.imwrite("heatmap.png", cmap(arr)[:, :, :3][:, :, ::-1] * 255)` and get the similar result as Taichi GUI's output. I think the reason may be the implementation of `cmap` in `plt.imshow` is different from `cmap(arr)`?

`cv2` output image:
![heatmap](https://user-images.githubusercontent.com/19147848/126265883-33b14ba6-45bd-4129-92df-36a06e17ac22.png)

**Comment by mzy2240** [comment]
@ljcc0930 Thanks! Yeah plt.imshow might be the reason. What should I do if let's say I want the Taichi GUI to match the current matplotlib plot? The major difference seems to be that here matplotlib uses a continuous color range while Taichi here only has yellow and purple.

**Comment by mzy2240** [comment]
Did not know why but runnning the following script seems to give a similar result as matplotlib output:
`gui.set_image(cmap(arr/25))`

**Comment by mzy2240** [comment]
Change the imshow function to `plt.imshow(arr, cmap=cmap, vmin=0, vmax=0.1)` solve the problem. The example here [Sharing data with other packages](https://docs.taichi.graphics/zh-Hans/docs/#sharing-data-with-other-packages) could consider an update.
