### ISSUE TITLE
[Lang] Support customized struct in a SNode container?

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#2614]
**Concisely describe the proposed feature**

Make Taichi support user-defined struct (similar to a `namedtuple`). E.g.

```py
st = ti.types.make_struct(a=ti.i32, b=ti.f32, ...)
f = ti.field(st, shape=(8, 8))

@ti.kernel
def run():
  for i in f:
    f[i].b = f[i].a
```

**Describe the solution you'd like (if any)**

Right now one can achieve the same thing by separately defining `a` and `b` in the above example. However, supporting named struct would make the code more intuitive.

**Comment by victoriacity** [comment]
Will be happy to look into this! This allows for users to create AOS fields without being exposed to advanced layouts.
