### ISSUE TITLE
Is there any way to evaluate an entire tensor or subtensor at once, other than looping through every element?

### ISSUE THREAD

**Issue by aespielberg** [taichi-dev/taichi#262]

**Comment by yuanming-hu** [comment]
You mean something like `x[1:200, 3:4, 5]`?

**Comment by aespielberg** [comment]
I was thinking more like x.eval() in tf, but that would be very useful too.

**Comment by yuanming-hu** [comment]
I see. You want a numpy ndarray out of a taichi tensor. I can add support for this later.

**Comment by aespielberg** [comment]
Thanks!
