### ISSUE TITLE
[refactor] Make Callable::Args/Ret serializable

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#2625]
https://github.com/taichi-dev/taichi/blob/471e3882ee7893234fd38c7589a0a2360cd960f2/taichi/program/callable.h#L16-L33

Right now it isn't serializable yet because of `dt`. That is, `DataType` itself is a wrapper around a polymorphic pointer, which isn't trivially serializable.

To make this work, we can  replace the usage of `DataType` with `PrimitiveTypeID` (not to be confused with `PrimitiveType`): https://github.com/taichi-dev/taichi/blob/471e3882ee7893234fd38c7589a0a2360cd960f2/taichi/ir/type.h#L8-L12 This refactor is OK because kernel arg/return vale types are unlikely to be customized. (If we ever need to quantize the kernel args type, we should make Taichi's serialization utility support runtime polymorphism first.)

**Comment by k-ye** [comment]
Hi @imdouyu , thanks for expressing the interest! Assigned to you & let us know if you need more help

**Comment by uancen** [comment]
Kindly to ask if an issue here that need to be addressed? 
If there is, please explain it further and I'm glad to undertake it.
