### ISSUE TITLE
Unify the Windows CI platform

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#2634]
Let's aim for deprecating Appveyor. Also we should trigger the nightly release more often to ensure the entire release pipeline works well.

**Comment by Leonz5288** [comment]
Now windows & macos both release through github action. I guess there is still one more place that uses appveyor?

**Comment by k-ye** [comment]
> I guess there is still one more place that uses appveyor?

Yeah, every PR-merge triggers a appveyor build. Once we have a cron job to release nightly, we can deprecate that

**Comment by Leonz5288** [comment]
> > I guess there is still one more place that uses appveyor?
> 
> Yeah, every PR-merge triggers a appveyor build. Once we have a cron job to release nightly, we can deprecate that

Great! I think we are very close to this!
