### ISSUE TITLE
PLEASE STOP UPGRADING TO v0.7.28

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#2642]
Recently Taichi's build processed has been streamlined. Unfortunately, this has resulted in the wheel not being correctly built. Please keep your Taichi version at `v0.7.26` at this moment. Thanks for your patience!

**Comment by squarefk** [comment]
I encounter the same problem when creating a new acc in Linux and trying to run some taichi programs XD

**Comment by k-ye** [comment]
Yanked `v0.7.28`
