### ISSUE TITLE
Make python setup.py clean work

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#2680]
Currently `python setup.py clean` doesn't actually clean anything :P
It should at least remove build/ folder, might also clean up a few additional files generated in the build process.
This can be done by overwriting clean command in setup.py, see some examples in https://github.com/taichi-dev/taichi/blob/master/setup.py#L213.

**Comment by matanster** [comment]
And as I understand currently it only cleans the build/ folder, but not build targets in their target directory, at least not when --inplace is used in the build.
