### ISSUE TITLE
Deprecate Expr::operator=

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#2684]
Replace `Expr::operator=` with a more meaningful function name: https://github.com/taichi-dev/taichi/blob/6fd5a864f3c325e14fa4833336e12de096519800/taichi/ir/expr.h#L75

This overloading can be confusing, e.g. (L202)

https://github.com/taichi-dev/taichi/blob/6fd5a864f3c325e14fa4833336e12de096519800/taichi/ir/expr.cpp#L198-L204

**Comment by jaygala223** [comment]
Hello, I would like to work on this issue. Could you please explain it further?

**Comment by k-ye** [comment]
Hi @jaygala223 , thanks for the help! We can simply replace `operator=` with a more explicit function name, e.g. `set_or_insert_assignment()`.

If `Expr::operator=`'s call sites aren't that many, we should just inline the `get_current_program().current_callable` check, and wrap up each branch with a separate function. 


https://github.com/taichi-dev/taichi/blob/6fd5a864f3c325e14fa4833336e12de096519800/taichi/ir/expr.cpp#L58-L73

**Comment by lucywsq** [comment]
Hi, @Xander23333  if you're working on this issue, please let us know, thanks!

**Comment by Xander23333** [comment]
@lucywsq Hello, I met some difficulties in setting up the development environment. I failed in the recursive clone taichi repo step due to network reasons. Please assign this feature to other partners first. I will follow up on other features later. Sorry for the delay in development.

**Comment by WenheLI** [comment]
After a brief investigation, I think we might need to know how many codes are depending on the `= operator override`. If the number is really big, this PR could be a tricky and cumbersome one. 
Also, this seems like a breaking change since after this PR is landed. Previous code may not fully work.

**Comment by WenheLI** [comment]
It seems we still need to implement `=` for Expr since its original `=` has been deleted as 'Expr' has a user-declared move constructor.
In this case, what semantic we should give for `Expr's =`?

**Comment by k-ye** [comment]
> It seems we still need to implement `=` for Expr since its original `=` has been deleted as 'Expr' has a user-declared move constructor. In this case, what semantic we should give for `Expr's =`?

Hey, sorry about the delayed reply. What we'd like here is really just to replace `operator=` with a named function. The fact that `a = b` has meanings other than copy/move is quite confusing.

**Comment by k-ye** [comment]
> It seems we still need to implement `=` for Expr since its original `=` has been deleted as 'Expr' has a user-declared move constructor. In this case, what semantic we should give for `Expr's =`?

Hey, sorry about the delayed reply. What we'd like here is really just to replace `operator=` with a named function. The fact that `a = b` has meanings other than copy/move is quite confusing.

**Comment by junaire** [comment]
Is there anyone still working on this? I guess I know how to do this :-)

**Comment by k-ye** [comment]
@WenheLI are you still working on this? If not, we will pass this to @junaire , thanks :-)

**Comment by WenheLI** [comment]
Sorry just saw this thread. And I am kinda busy recently. @junaire feel free to take it over!
