### ISSUE TITLE
Put repeating code blocks in Github CI workflows into scripts.

### ISSUE THREAD

**Issue by Leonz5288** [taichi-dev/taichi#2715]
Currently we have several ci workflows running every PR/release, and considerate amount of code in these workflows are repeating(having the same functionality).

For example, basically every workflows requires we build taichi from source. Therefore, if these kinds of code can be put into bash/shell scripts, the readability of these workflows can be much higher and they can also be much more easier to fix/debug.

To begin this work, files under `.github/workflows/` can be a place to start.

**Comment by lucywsq** [comment]
Hi, @frostming  please join this slack channel, then we would respond to your problems on time. We can communicate faster as well.

**Comment by ailzhang** [comment]
Closing as this is mostly done, thanks!
