### ISSUE TITLE
[Doc] Improve documentation for developer installation 

### ISSUE THREAD

**Issue by qiao-bo** [taichi-dev/taichi#2719]
The [Developer Installation](https://docs.taichi.graphics/docs/lang/articles/contribution/dev_install#linux) page has a few points could be improved. Following the page step-by-step might still encounter some installation errors. Take Linux/Ubuntu as an example:

- Additional dependencies: The following packages are needed when building Taichi (v0.7.26) on a freshly installed Ubuntu 20.04.2 LTS. `libxi-dev` `libxcursor-dev` `libxinerama-dev` `libxrandr-dev` `libx11-dev` `libgl-dev`. Based on errors from CMakeLists.txt.
- Setting up CUDA: On machines with existing installations and/or older GPUs, pay attention to Application/Driver/Runtime/CC compatibility. Suggest to at least point to the [Nvidia CUDA Installation Guide](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) and [The Compatibility Document](https://docs.nvidia.com/deploy/cuda-compatibility/).

**Comment by KuribohG** [comment]
Also, `libtinfo5` is missing. `libtinfo-dev` in the documentation is not working for me.
