### ISSUE TITLE
A way to handle list indices in a kernel

### ISSUE THREAD

**Issue by bsavery** [taichi-dev/taichi#2733]
**Concisely describe the proposed feature**
I would like a way to access python lists in a kernel.  Is there any way this would be possible?

Here's a simple example:
``` Python
import taichi as ti

ti.init(arch = ti.gpu)
choices = [0, 1]

@ti.kernel
def do_choice() -> ti.i32:
    i = ti.random()
    n = 0 if i < 0.5 else 1
    return choices[n]

print("Choice is", do_choice())
```

A more complex example I run into with my raytracer code:  https://github.com/bsavery/ray-tracing-one-weekend-taichi
In particular we keep a list of materials and want to look up the material based on an index in the ray hit.  

My workaround is to basically do a big if / else statement in the tai chi function but that can be quite limiting:

``` Python
if mat_index == 0:
    do_metal()
elif mat_index == 1:
    do_diffuse()
elif mat_index == 2:
....
```

**Describe the solution you'd like (if any)**
A suggestion of another way to work around this or some way to access python lists in a kernel by index.

**Additional comments**

**Comment by k-ye** [comment]
`choices` is a Python-scope object, and would no longer exist after the JIT compilation. Would it be helpful if you store that list as a `ti.field`?

**Comment by bsavery** [comment]
Of course that could be a ti.field.  But maybe the example is too simple here.  

Imagine `choices = [Color.red, Color.blue]` where it is objects, or functions.  Really what we need here is the option to select function pointers from a list...

**Comment by bsavery** [comment]
Bumping this issue and giving an alternative.  Could we add `@ti.func` functions to struct types?  Something like this: 

`
import taichi as ti


ti.init(arch=ti.gpu)
choices = [0, 1]


@ti.func
def add(self):
    return self.x + self.y


my_type = ti.types.struct(x=ti.i32, y=ti.i32)
my_type.add = add
my_list = my_type.field(shape=1)
my_list[0] = my_type(x=1, y=2)

@ti.kernel
def test() -> ti.i32:
    return my_list[0].add()


print("Value is", test())
`

would be really handy.

**Comment by bsavery** [comment]
Your response might be "well why not use `@ti.data_oriented` classes?  Well, getting back to the root of this problem, _I can't use a list of objects in Taichi scope_. 

However I can make a field of a struct type which is quite handy.  It just would be nice do run functions on the struct type without doing something like 

```
@ti.func
def my_type.add(my_type):
    return my_type.x + my_type.y


my_type = ti.types.struct(x=ti.i32, y=ti.i32)
```

**Comment by bsavery** [comment]
Basically a similar problem to this:  https://stackoverflow.com/questions/27030046/glsl-passing-functions
