### ISSUE TITLE
Come join us at TaichiCon 02! 欢迎参加TaichiCon 02开发者大会！

### ISSUE THREAD

**Issue by lucywsq** [taichi-dev/taichi#2740]
Hi everyone，

We will host TaichiCon 02 at 10 am on September 4th (Sept 3, Pacific Time) in Beijing (Building No. 6 floor B1, Haidian District, Beijing). We will host sessions both online and offline.

For online participation, please complete [this survey](https://taichigraphics.wjx.cn/vj/wyeuM3K.aspx) and we will send you a link to the VooV meeting. Welcome : )

(The speakers will share their contents in Mandarin, but all slides will be in English. We will host the slides online after the event.)

Hi 各位，大家期待已久的TaichiCon 02来了～ 欢迎世界各地的开源爱好者们（计算机图形学、编译器、高性能计算等方向）参加！
本次活动将在**北京时间9月4日上午10:00**正式开始，举办地点在**北京中关村创业大街6号楼全球创新社区B1层**。

活动日程将贯穿全天，同样将为大家带来太极编程语言的的核心进展（TaichiZoo, GGUI, Packed Mode, Dynamic indexing, CI/CD system, Dynamic SNode, etc.），现场Taichi的研发同学也将带领大家动手体验Taichi，具体日程请见下方议程海报。

我们非常期待每一位关注Taichi的朋友们来到现场交流，但考虑防疫政策，本次活动线下参会人数不得不控制在60人以内，敬请谅解。同时，为方便国内京外地区、海外的朋友们参与讨论，我们保留线上参会的惯例，并在活动现场设置腾讯会议室直播，具体的参会方式将于9月2日向大家同步。

同时本次特别感谢 @xuhao1 @lyd405121 @houkensjtu 三位朋友成为 **TaichiCon 02的特邀嘉宾**，分享使用太极做出的精彩项目，非常期待三位的分享。（排名不分先后）

广告：我们欢迎各位同学加入Taichi社区一起开发、学习、成长。给Taichi贡献的方式不一定是写代码

- 修正文档里面的Typos
- 贡献examples
- 甚至点一下Star

都是对Taichi有意义的贡献。

![议程长图改后版-github](https://user-images.githubusercontent.com/38712162/130216600-7d47da8a-0875-4d77-b6ab-c3fda6b86973.jpg)

**Comment by mgttt** [comment]
可否开直播频道？

**Comment by lucywsq** [comment]
For slides of TaichiCon 02, please click [here](https://github.com/taichi-dev/taichicon) for more information
TaichiCon 02的回顾内容已经转移到 [taichicon](https://github.com/taichi-dev/taichicon) 感兴趣可以收藏哦
