### ISSUE TITLE
[m1 mac install]Is there any possible way to run taichi on m1 mac?

### ISSUE THREAD

**Issue by Sishxo** [taichi-dev/taichi#2763]

**Comment by bobcao3** [comment]
From the readme: Please build from source for other configurations (e.g., your CPU is ARM, or you want to try out our experimental C backend).

I'm pretty sure m1 is supported, just that CI is not set up for it to build the pip packages (maybe this recently has changed, not quite sure, needs checking with others). You can always build it yourself.

**Comment by yuanming-hu** [comment]
You need to build from source for now. @ljcc0930  is working on releasing M1 binary builds so that you can install `taichi` via `pip`. We plan to release it before Sept 4th.

I have an M1 Macbook Pro and have been using a version built from source for a few months.

**Comment by Sishxo** [comment]
helpful! thanks!
