### ISSUE TITLE
"ImportError" at windows

### ISSUE THREAD

**Issue by mgttt** [taichi-dev/taichi#2765]
**Describe the bug**
"ImportError: DLL load failed while importing taichi_core"
**Pretty sure that vc_redist.x64.exe is installed and system rebooted, but this error still occurr when "import taichi"**

**To Reproduce**

```py
import taichi
```

**Log/Screenshots**
```
>>> import taichi
[Taichi] mode=release
[33mShare object taichi_core import failed, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting[39m
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\app\Anaconda3\lib\site-packages\taichi\__init__.py", line 1, in <module>
    from taichi.core import *
  File "C:\app\Anaconda3\lib\site-packages\taichi\core\__init__.py", line 1, in <module>
    from taichi.core.logging import *
  File "C:\app\Anaconda3\lib\site-packages\taichi\core\logging.py", line 4, in <module>
    from taichi.core import util
  File "C:\app\Anaconda3\lib\site-packages\taichi\core\util.py", line 168, in <module>
    import_ti_core()
  File "C:\app\Anaconda3\lib\site-packages\taichi\core\util.py", line 45, in import_ti_core
    raise e from None
  File "C:\app\Anaconda3\lib\site-packages\taichi\core\util.py", line 33, in import_ti_core
    import taichi_core as core
ImportError: DLL load failed while importing taichi_core: 找不到指定的程序。
Consider installing Microsoft Visual C++ Redistributable: https://aka.ms/vs/16/release/vc_redist.x64
.exe
...
```

**Additional comments**
Tried at windows7pro or windows2012server.

**Comment by mgttt** [comment]
by debugging with "ctypes.WinDL()", it found that 
user32.SetThreadDpiAwarenessContext() is missing on win7. not solution to fix yet.

**Comment by mgttt** [comment]
Found some possible solution (divert codes when win7/win2012)
https://github.com/SteveSandersonMS/WebWindow/issues/83
wishes that help and patches will come asap, thanks taichi team

**Comment by k-ye** [comment]
@bobcao3 This seems like the Win DPI stuff?

**Comment by bobcao3** [comment]
I thought there was a patch detecting the NT version. Which version is this?

**Comment by mgttt** [comment]
@k-ye @bobcao3  I think the problem can be fixed on win7/win2012 which missing SetThreadDpiAwarenessContext() by using loading the user32 api with GetProcAddress() instead of static link?  (at taichi/taichi/gui/win32.cpp)

**Comment by bobcao3** [comment]
I think I have a patch already fixing this, so I need to confirm which
version of Taichi this is?

**Comment by k-ye** [comment]
https://github.com/taichi-dev/taichi/blob/7ccbfab2d63362dc36f69cf58dcef27be2a73365/taichi/gui/win32.cpp#L167-L170

I think `SetThreadDpiAwarenessContext` is dynamically linked (instead of dynamically loaded)? If so, since your check is done at runtime, it would still require the corresponding DLL to be linked with Taichi itself.

**Comment by bobcao3** [comment]
We can just remove it for now since this will not be needed for GGUI. Or we
probably need to use the GetProcAddress call

**Comment by k-ye** [comment]
Yeah, let's just remove it
