### ISSUE TITLE
When using a bit masked field in Metal, number of activated masks can be wrong

### ISSUE THREAD

**Issue by bsavery** [taichi-dev/taichi#2804]
**Describe the bug**
On metal, 2D bit masks don't seem to activate all coordinates

**To Reproduce**
So I noticed this when trying to bit mask a 2D image.  Hopefully this example will be clear.  I start by activating the whole 2D field, then just check how many are active.  

```py
import taichi as ti

ti.init(arch=ti.gpu)

some_val = ti.field(dtype=float)
width, height = 10, 10
ptr = ti.root.bitmasked(ti.ij, (width, height))
ptr.place(some_val)
num_active = ti.field(dtype=int, shape=())

@ti.kernel
def init():
    num_active[None] = 0
    for x, y in ti.ndrange(width, height):
        ti.activate(ptr, [x, y])
        some_val[x, y] = 5
        num_active[None] += 1

@ti.kernel
def run():
    num_active[None] = 0
    for x, y in some_val:
        num_active[None] += 1
        

init()
print('num activated', num_active[None])
run()
print("active = ", num_active[None])
```

**Log/Screenshots**
5x5:
num activated 25
active =  16

6x6:
num activated 36
active =  28

10x10:
num activated 100
active =  64

**Additional comments**
CPU seems to do the right thing FYI.

**Comment by k-ye** [comment]
Not sure if this is relevant: https://github.com/taichi-dev/taichi/issues/2260, but I'll just link here for future reference

**Comment by bsavery** [comment]
I'm not sure.  I removed the "sibling field" in this case `num_active` but still got the same result.  Unless it's the same bug as #2260 but deeper.

**Comment by k-ye** [comment]
Oops, short term solution is to use `ti.init(..., packed=True)`.

Long answer: By default Taichi pads a field to a power-of-two shape. So (10, 10) becomes (16, 16), so only the upper-left 10x10 region of the 16x16 is valid, meaning that the linearized indices are no longer consecutive. However, when iterating over a sparse field, we still used the linearized indices in [0, 100), so it checked for a few invalid places..

**Comment by k-ye** [comment]
This should be fixed by the next release :-)
