### ISSUE TITLE
Re-enable test_remove_clear_list_from_fused_serial on CUDA backend

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#2847]
This is a flaky test on GPU CI so we disabled it: https://pipelines.actions.githubusercontent.com/FbByQYkP8Upm7Ytd8H6oTOQALwY9F2xlXc4iGS6gaDqx1Yahr3/_apis/pipelines/1/runs/13359/signedlogcontent/23?urlExpires=2021-08-30T07%3A25%3A09.8417842Z&urlSigningMethod=HMACV1&urlSignature=oNiUWK9jPo83M1H1HahyJwHm8fbo7KlQhJmt8PffpNU%3D

**Comment by qiao-bo** [comment]
If this is not urgent, I would like to have a look. Would you indicate which example is this? I cannot open the link.

**Comment by ailzhang** [comment]
Thanks @qiao-bo ! Yea please feel free to take it!

**Comment by qiao-bo** [comment]
Some findings:

- single thread: local test ok, CI test ok
- two threads: local test ok, CI test ok
- four threads: local test ok, CI test fails as follows
```
=========================== short test summary info ============================
FAILED ../../../../.local/lib/python3.8/site-packages/taichi/tests/test_torch_ad.py::test_torch_ad
FAILED ../../../../.local/lib/python3.8/site-packages/taichi/tests/test_torch_io.py::test_io_3d
FAILED ../../../../.local/lib/python3.8/site-packages/taichi/tests/test_while.py::test_while
FAILED ../../../../.local/lib/python3.8/site-packages/taichi/tests/test_torch_ad.py::test_torch_ad_gpu
FAILED ../../../../.local/lib/python3.8/site-packages/taichi/tests/test_torch_io.py::test_io_zeros
====== 5 failed, 879 passed, 2 skipped, 36 warnings in 809.56s (0:13:29) =======
``` 
@ailzhang Interestingly, the sfg test hasn't failed yet. comments are appreciated.

**Comment by ailzhang** [comment]
This test is enabled back since it's not easy to reproduce. We'll keep an eye on it and reopen this issue if it happens again in the future.
