### ISSUE TITLE
Crash when generating many ti.FieldBuilder

### ISSUE THREAD

**Issue by beginlner** [taichi-dev/taichi#2889]
Run this code and it crashes.
```
import taichi as ti

ti.init()
for i in range(100):
    field = ti.field(dtype=ti.f32)
    fb = ti.FieldsBuilder()
    fb.dense(ti.ij, (1, 1)).place(field)
    fb.finalize()

```

**Comment by k-ye** [comment]
Could you paste the stack trace?

**Comment by strongoier** [comment]
I guess it is because `constexpr int taichi_max_num_snode_trees = 32;`

**Comment by beginlner** [comment]
> Could you paste the stack trace?

ljss@ljss:~/project-tai$ /bin/python3 /home/ljss/Desktop/1.py
[Taichi] version 0.7.31, llvm 10.0.0, commit 59a434ec, linux, python 3.8.10
[Taichi] Starting on arch=x64
double free or corruption (!prev)
[E 09/08/21 14:26:02.133 116979] Received signal 6 (Aborted)
