### ISSUE TITLE
[Docs] There is no section about Vulkan installation in dev_install documentation

### ISSUE THREAD

**Issue by gaocegege** [taichi-dev/taichi#2896]
There is no section about Vulkan installation in  [`docs/lang/articles/contribution/dev_install.md`](https://github.com/taichi-dev/taichi/blob/master/docs/lang/articles/contribution/dev_install.md). But the cmake raises an error `VULKAN_SDK is not found.` when I followed the doc.

Should we document how to install vulkan in the doc?

**Comment by ailzhang** [comment]
Thanks for reporting! cc @AmesingFlank who was planning to add a section about Vulkan installation ;)

**Comment by AmesingFlank** [comment]
Thanks! Submitted a PR just now.
@gaocegege please see  https://github.com/taichi-dev/taichi/pull/2897

**Comment by ailzhang** [comment]
Closed by @AmesingFlank 's #2897 , thanks!
