### ISSUE TITLE
Sparse tensor using pointers with llvm ptx backend not working correctly

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#295]
Sparse tensor element activation using pointers does not seem to working correctly when using the llvm ptx backend. The script below is tripping the assert. It seems to work when pointer is changed to bitmasked() or the arch is changed to x86_64. 

``` python
import taichi as ti
#ti.cfg.arch = ti.x86_64
ti.cfg.arch = ti.cuda

a =  ti.var(dt=ti.f32);

N = 8

@ti.layout
def place():
  ti.root.dense(ti.ijk, N).pointer().dense(ti.ijk, 4).place(a)

@ti.kernel
def init():
  for k in range(N*4):
    for j in range(N*4):
      for i in range(N*4):
        a[i,j,k] = 1.0

init()

ti.runtime.sync()

for k in range(N*4):
  for j in range(N*4):
    for i in range(N*4):
      assert(a[i,j,k] == 1.0)
```

**Comment by yuanming-hu** [comment]
Hi @KLozes,

Sorry about that. Pointer activation on GPU hasn't been implemented in the LLVM backend. The old CUDA backend does support it. I've been traveling recently and have no access to a GPU, and I'll fix this once I'm back to the US.

**Comment by KLozes** [comment]
Hi @yuanming-hu 

I figured that was the case. I haven't had much luck with the legacy backend since you switched to llvm. It errors at the #include <taichi/legacy_backend> when using the wheels package.  And the cuda backend always seg faults when using the compiled dev package. x86_64 works though.

Thanks,
Ken

**Comment by yuanming-hu** [comment]
The CUDA backend is super hard to configure and shipping it with a python wheel is almost impossible. LLVM is much easier to ship, yet I have to re-implement a lot of things...
