### ISSUE TITLE
Test_mpm88_numpy_and_ndarray reports different running time

### ISSUE THREAD

**Issue by qiao-bo** [taichi-dev/taichi#2954]
In `test_mpm88_numpy_and_ndarray`, `test_numpy()` and `test_ndarray()` should have similar execution time, but `ti test` reports differently using CUDA.

To reproduce:
`ti test -v -t1 -a cuda mpm88 -k "mpm88_numpy_and_ndarray"`, comment out `test_numpy()` or `test_ndarray()` to get isolated execution time.

Using CUDA 11.4, the time of 3 runs are:
`test_numpy()`: 5.91s, 5.95s, 5.89s
`test_ndarray()`: 14.43s, 13.38s, 13.34s

**Comment by bobcao3** [comment]
Just tested on my end and I can't seem to reproduce this as of the current master branch, so I think we can call this fixed?

One thing does concern me, on my RTX3080, Nvidia Driver 472.12, Cuda 11.4, I'm seeing around 16 to 17s for both `numpy` and `ndarray`, this seems quite a bit slow
