### ISSUE TITLE
The latest Docker image is broken and the Dockerfile built with error: No module named taichi_core

### ISSUE THREAD

**Issue by wuhanstudio** [taichi-dev/taichi#3016]
**Describe the bug**

The latest docker image on Docker Hub was pushed 2 months ago, and it is broken.

```
$ docker run -it taichidev/taichi:latest /bin/bash

# Inside the container
root@0a46ea7585f6:/taichi-dev/taichi# taichi
bash: taichi: command not found

# Empy taichi folder inside the container
root@0a46ea7585f6:/taichi-dev/taichi# ls
# Empty folder
```

Thus I built the image using the Dockerfile from latest source code, but failed to execute `taichi` and `ti` in the docker container.

**To Reproduce**

- Ubuntu 20.04
- Docker 19.03.13

```bash
# After cloning the latest version from github master branch
$ docker build -t taichi:latest .
$ docker run -it taichi:latest /bin/bash
root@e7a6a7986674 # taichi
```

**Log/Screenshots**
```
root@e7a6a7986674:/taichi-dev/taichi# taichi
Share object taichi_core import failed, check this page for possible solutions:
https://docs.taichi.graphics/docs/lang/articles/misc/install
Traceback (most recent call last):
  File "/taichi-dev/taichi/bin/taichi", line 3, in <module>
    import taichi
  File "/taichi-dev/taichi/python/taichi/__init__.py", line 3, in <module>
    from taichi.core import *
  File "/taichi-dev/taichi/python/taichi/core/__init__.py", line 1, in <module>
    from taichi.core.logging import *
  File "/taichi-dev/taichi/python/taichi/core/logging.py", line 4, in <module>
    from taichi.core import util
  File "/taichi-dev/taichi/python/taichi/core/util.py", line 127, in <module>
    import_ti_core()
  File "/taichi-dev/taichi/python/taichi/core/util.py", line 45, in import_ti_core
    raise e from None
  File "/taichi-dev/taichi/python/taichi/core/util.py", line 33, in import_ti_core
    import taichi_core as core
ModuleNotFoundError: No module named 'taichi_core'
Consider installing libtinfo5: sudo apt-get install libtinfo5
```

**Comment by qiao-bo** [comment]
Hi, thanks for filing this issue. Our docker image requires indeed some update, especially for our latest v0.8.0 release. I will try to reproduce your issue. Meanwhile, maybe you can try to use our [pip package](https://docs.taichi.graphics/docs/) or directly [build from source](https://docs.taichi.graphics/docs/lang/articles/contribution/dev_install).  Thx ; ☺️

**Comment by qiao-bo** [comment]
Hi @wuhanstudio, i got some update here:

- The image with the latest tag (taichidev/taichi:latest) on our Dockerhub is indeed broken. Sorry on that, we will fix the issue. As an alternative, you can play with the v0.7.26 tag by `docker run -it taichidev/taichi:v0.7.26 /bin/bash`. You can run `ti diagnose` to inspect available targets. Or run `ti test -t2 -v` to test the samples. If you are interested in a specific example, you can just execute for example `python3 -m taichi examples/algorithm/laplace.py`.
- When you build the Dockerfile on the latest source, you will indeed get the above error. In that case, please run `python3 setup.py develop --user` in the container. After that, the steps mentioned above should also work.

Hope it (at least partially) solves your problem ;-). Thanks.

**Comment by wuhanstudio** [comment]
> Hi @wuhanstudio, i got some update here:
> 
> * The image with the latest tag (taichidev/taichi:latest) on our Dockerhub is indeed broken. Sorry on that, we will fix the issue. As an alternative, you can play with the v0.7.26 tag by `docker run -it taichidev/taichi:v0.7.26 /bin/bash`. You can run `ti diagnose` to inspect available targets. Or run `ti test -t2 -v` to test the samples. If you are interested in a specific example, you can just execute for example `python3 -m taichi examples/algorithm/laplace.py`.
> * When you build the Dockerfile on the latest source, you will indeed get the above error. In that case, please run `python3 setup.py develop --user` in the container. After that, the steps mentioned above should also work.
> 
> Hope it (at least partially) solves your problem ;-). Thanks.

Hi, @qiao-bo ,

Thanks a lot for your help, and `python3 setup.py develop --user` works for me.

I just created a PR that made several improvements for the Dockerfile :

- Reduce the docker image size from 6GB to 0.6GB by removing temporary build caches from the final image
- Upgrade from Ubuntu 18.04 to Ubuntu 20.04

**Comment by qiao-bo** [comment]
Hi, @wuhanstudio, thanks a lot. This is really helpful. We will have a look at the PR ASAP.
