### ISSUE TITLE
[Documentation update request]: Clang dependence of Arch Linux building guide

### ISSUE THREAD

**Issue by Axe-hyx** [taichi-dev/taichi#3039]
**Describe the problem**
Currently clang-10 is not available in pacman package repository, so [the building guide](https://github.com/taichi-dev/docs.taichi.graphics/blob/master/website/docs/lang/articles/contribution/dev_install.md#installing-dependencies) of Arch Linux is not correct.
> (`On Arch Linux, execute sudo pacman -S clang. (This is clang-10) `)

**Solve issue**
I successfully built `taichi==0.8.0` with clang and llvm prebuild with [this](https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz) release pack.

**Comment by ailzhang** [comment]
Hey @Axe-hyx, thanks a lot for reporting! Would you like to send the fix btw? ;)
