### ISSUE TITLE
Refactor the LLVM backend memory allocator

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#3060]
**Concisely describe the proposed feature**

This refactor is mostly targeted at the CUDA backend

* [x] Remove the unified memory allocator. It's difficult to work reliably across all the platforms.
* [x] Create a memory manager that can both allocate and recycle memory. `NodeManager` has a similar utility (implemented using the free list approach) https://github.com/taichi-dev/taichi/blob/ae08ddcf0d692fe63c1ea58f976663525caca525/taichi/runtime/llvm/runtime.cpp#L629-L640

**Comment by qiao-bo** [comment]
Update: our own memory allocator is enabled since v0.8.8 [3843](https://github.com/taichi-dev/taichi/pull/3843)
