### ISSUE TITLE
Drawing lines with `canvas.lines()` does not work as expected

### ISSUE THREAD

**Issue by bcolloran** [taichi-dev/taichi#3110]
**Describe the bug**

I've been having trouble drawing lines with `canvas.lines()`.

The short script below defines 10 points in a semicircle around one point at the center of the semicircle, and then defines edges between the central point and all others. Only five of the expected 10 lines are drawn.

**To Reproduce**
```python
import numpy as np
import taichi as ti

ti.init(arch=ti.gpu)

x_np = np.pi * np.arange(0, 1, 0.1)
x_np = np.vstack([np.cos(x_np), np.sin(x_np)])
x_np = np.hstack([[[0], [0]], x_np]).T
x_np = 0.3 * x_np + 0.5

edges_np = np.array([[0, i] for i in range(1, x_np.shape[0])])

n_vertices = x_np.shape[0]
n_edges = edges_np.shape[0]

x = ti.Vector.field(2, shape=n_vertices, dtype=float)
x.from_numpy(x_np)

edges = ti.Vector.field(2, shape=n_edges, dtype=int)
edges.from_numpy(edges_np)

print(edges) # output included below

window = ti.ui.Window("draw lines", res=(512, 512))
canvas = window.get_canvas()

while window.running:
    canvas.lines(vertices=x, indices=edges, width=0.002)
    canvas.circles(centers=x, radius=0.005)
    window.show()
```

**Log/Screenshots**
here is the full terminal output when i run this script:

```
[Taichi] version 0.8.0, llvm 10.0.0, commit 181c9039, linux, python 3.9.7
[Taichi] Starting on arch=cuda
[[ 0  1]
 [ 0  2]
 [ 0  3]
 [ 0  4]
 [ 0  5]
 [ 0  6]
 [ 0  7]
 [ 0  8]
 [ 0  9]
 [ 0 10]]
[W 10/07/21 22:54:13.619 48481] [vulkan_device.cpp:buffer@526] Overriding last binding
[W 10/07/21 22:54:13.626 48481] [vulkan_device.cpp:buffer@526] Overriding last binding
```

Note that the list of `edges` that is printed includes an edge from point zero to all 10 other points, but in the screenshot below only 5 lines are drawn:
![image](https://user-images.githubusercontent.com/2380975/136505737-94999dae-aa9f-4cd0-b2a0-531c2eb2aa90.png)

**Additional comments**
I have just recently discovered Taichi and I *love it*. Thank you, and keep up the amazing work!

**Comment by k-ye** [comment]
@AmesingFlank could you help take a look :sweat_smile:

**Comment by AmesingFlank** [comment]
Hi!

The `indices` argument of `canvas.lines` should be a `ti.field` of shape `n_edges * 2`, instead of a 2D `ti.Vector.field`

The following code does what you want:

```python
import numpy as np
import taichi as ti

ti.init(arch=ti.gpu)

x_np = np.pi * np.arange(0, 1, 0.1)
x_np = np.vstack([np.cos(x_np), np.sin(x_np)])
x_np = np.hstack([[[0], [0]], x_np]).T
x_np = 0.3 * x_np + 0.5

n_vertices = x_np.shape[0]
n_edges = n_vertices - 1

x = ti.Vector.field(2, shape=n_vertices, dtype=float)
x.from_numpy(x_np)

edges = ti.field( shape=n_edges * 2, dtype=int)

@ti.kernel
def set_edges():
    for i in range(n_edges):
        edges[i*2 + 0] = 0
        edges[i*2 + 1] = i+1

set_edges()

window = ti.ui.Window("draw lines", res=(512, 512))
canvas = window.get_canvas()

while window.running:
    canvas.lines(vertices=x, indices=edges, width=0.002)
    canvas.circles(centers=x, radius=0.005)
    window.show()
```
![Screenshot 2021-10-09 031515](https://user-images.githubusercontent.com/16066115/136640421-aafa88b4-e031-441c-b39d-2afbf082dfe2.png)

I do apologise for the confusion caused. GGUI should probably support both ways of expressing indices, or at least throw an error.
