### ISSUE TITLE
Errors in installing process

### ISSUE THREAD

**Issue by fengzekang** [taichi-dev/taichi#312]
Hello,everyone
I followed the command (as below) on my ubuntu16.04
wget https://raw.githubusercontent.com/yuanming-hu/taichi/legacy/install.py
python3 install.py
but in the process "python3 install.py", there is an error occured 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/feng/GPUmpm/taichi/python/taichi/__init__.py", line 1, in <module>
    from taichi.main import main
  File "/home/feng/GPUmpm/taichi/python/taichi/main.py", line 6, in <module>
    from taichi.tools.video import make_video, interpolate_frames
  File "/home/feng/GPUmpm/taichi/python/taichi/tools/video.py", line 3, in <module>
    import taichi.core as core
  File "/home/feng/GPUmpm/taichi/python/taichi/core/__init__.py", line 1, in <module>
    from .util import tc_core, build, format, load_module, start_memory_monitoring, \
  File "/home/feng/GPUmpm/taichi/python/taichi/core/util.py", line 161, in <module>
    assert os.path.exists(os.path.join(bin_dir, 'libtaichi_core.so'))
AssertionError
  Error: installation failed.
I do not know how to use the os.path.join, and how can I solve this problem.
Thanks a lot.
Best regards.
Feng

**Comment by yuanming-hu** [comment]
Sorry, I recently broke the legacy taichi installation. My bad.

The issue should be fixed now. Please do the following:

1. In your ~/.bashrc or ~/.zshrc, remove the following lines:
```
export TAICHI_NUM_THREADS=8                              
export TAICHI_REPO_DIR=/home/test/taichi
export PYTHONPATH=$TAICHI_REPO_DIR/python/:$PYTHONPATH
export PATH=$TAICHI_REPO_DIR/bin/:$PATH
``` 
2. Delete the existing taichi folder created by `install.py` and the `install.py` script itself.
3. Open a new terminal (to get rid of the old environment variables).
4. Redo the [instructions](https://taichi.readthedocs.io/en/latest/installation.html) again. (I updated install.py and the issue should have been fixed.)

Let me know if it works for you guys. Sorry about the trouble!

**Comment by fengzekang** [comment]
Thanks for the reply. 
Of course, I will redo this following your step. I will tell you the results.
In the meanwhile, I am compiling the taichi-CUDA10.0 based on [Developer installation](https://taichi.readthedocs.io/en/latest/dev_install.html).  any differents about these two taichi? maybe I will use GPU to do the mpm caculation. Thanks a lot
Best regards
Feng

**Comment by fengzekang** [comment]
As what I did just now, 
(1) I followed the steps you presented, and now just waiting for the 
Fetching runtimes..
Cloning into '/home/fengzk/GPUmpm/taichi/external/lib'...  and later any progress I will update.
(2) I followed the Developer installation, and I got messages after make
Scanning dependencies of target taichi_core
[  0%] Building CXX object CMakeFiles/taichi_core.dir/taichi/core/core.cpp.o
[  0%] Linking CXX shared library libtaichi_core.so
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[  0%] Built target taichi_core
and I search the solutions to solve the clang:warning but I did not figure out.
Any suggestions on this? @yuanming-hu  Thanks a lot
Best regards
Feng

**Comment by fengzekang** [comment]
Until now, I have compiled the taichi using the instructions steps. I have tried the examples using python3 file_name. some errors occurred, 
I will check these later. any process I will present. Thanks a lot

**Comment by fengzekang** [comment]
Hello @yuanming-hu 
I used two way to compile the taichi. and I don't know the difference about these two taichi/
(1)After I followed the [Developer installation](https://taichi.readthedocs.io/en/latest/dev_install.html#dev-install),  after I run the make, there are message:
Scanning dependencies of target taichi_core
[  1%] Building CXX object CMakeFiles/taichi_core.dir/taichi/core/core.cpp.o
[  2%] Linking CXX shared library libtaichi_core.so
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[100%] Built target taichi_core
But when I run the example, there is Traceback (most recent call last):
  File "fractal.py", line 4, in <module>
    pixels = ti.var(dt=ti.f32, shape=(n * 2, n))
AttributeError: module 'taichi' has no attribute 'var'
(2) I used the "python3 install.py"
there are errors about qt. I am trying to solve this.
 
Best regards

**Comment by yuanming-hu** [comment]
Hi @fengzekang, do you plan to develop the Taichi compiler or just use Taichi to run taichi_mpm?

**Comment by fengzekang** [comment]
Dear @yuanming-hu . I am planing to mpm in the Geotechnique field. And I think what you did is really good and I want to learn the mpm part and use it.
First I want to compile it and run a example successfully. But now I didn't got it.
Best regards

**Comment by yuanming-hu** [comment]
If that is the case, please just use [taichi_mpm](https://github.com/yuanming-hu/taichi_mpm). You will have to install [the legacy Taichi library](https://taichi.readthedocs.io/en/latest/installation.html#ubuntu-arch-linux-and-mac-os-x). Thanks.

**Comment by fengzekang** [comment]
Dear @yuanming-hu 
I have compiled the taichi-mpm successfully. And I test the smoke3d model. 
Are there other tests about fluid looks like following
![Screenshot from 2020-01-04 01-55-49](https://user-images.githubusercontent.com/38140045/71761148-d6626980-2e95-11ea-8191-429bd0166a86.png)
![Screenshot from 2020-01-04 01-56-03](https://user-images.githubusercontent.com/38140045/71761151-dbbfb400-2e95-11ea-86b2-9c39190c5457.png)
In addition, does taichi-mpm work on GPU or only based on CPU? 
Best regards.

**Comment by yuanming-hu** [comment]
Hi @fengzekang 

Thanks for asking. The script to reproduce the upper demo: https://github.com/yuanming-hu/taichi_mpm/blob/master/scripts/mls-cpic/water_wheel.py
the lower demo: https://github.com/yuanming-hu/taichi_mpm/blob/master/scripts/mls-cpic/buoyancy.py
