### ISSUE TITLE
performance improve suggest: from_numpy()

### ISSUE THREAD

**Issue by mgttt** [taichi-dev/taichi#3134]
problem description:

when copy bigger data(1GB above) from cpu to gpu by using ti.from_numpy(), it would take more than one second which seems slow.

suggestion:

after reviewing source code, should have a kind of batch copying instead of parrellel copy cell by cell?

**Comment by k-ye** [comment]
> after reviewing source code, should have a kind of batch copying instead of parrellel copy cell by cell?

Good observation! Cell-by-cell copying is probably inevitable in certain cases, e.g., when you are copying into a sparse field.

That said, we should figure out where the bottleneck is. Care to share your code so that we can do a repro?
