### ISSUE TITLE
Deploy Dockerfile on Linux CI

### ISSUE THREAD

**Issue by qiao-bo** [taichi-dev/taichi#3150]
Tasks following #2970 
- [x] Test on Ubuntu 18.04
- [x] Create non-root user for container access
- [x] Install Conda to enable multiple Python environment
- [x] Remove Taichi build and test, fetch Taichi from the corresponding Github PR
- [ ] <s>Reduce the image size</s> tracked in https://github.com/taichi-dev/taichi/issues/3275
- [ ] <s>Update doc</s>

**Comment by k-ye** [comment]
Closing this one, as the remaining tasks are not urgent
