### ISSUE TITLE
Add image I/O for GGUI

### ISSUE THREAD

**Issue by pollywaik** [taichi-dev/taichi#3201]
**Concisely describe the proposed feature**
Currently, GGUI does not seem to support image I/O, like `ti.GUI.show(filename)` in GUI. Or other methods to export images of canvas on the screen

**Comment by tczhangzhi** [comment]
I have the same problem but I suppose `ti.GUI`'s behavior should be somehow consistent with `ti.ui.Window` in `GGUI`. But there already exists API called `window.show()` to rander results.

I wonder are we supposed to have a `window.savefig(file)` here:
https://github.com/taichi-dev/taichi/blob/master/taichi/python/export_ggui.cpp#L253-L255
to obtain a `VkBuffer` in RGBA format and save the image using `imwrite` here:
https://github.com/taichi-dev/taichi/blob/master/taichi/util/image_io.cpp#L9-L46

**Comment by AmesingFlank** [comment]
> I have the same problem but I suppose `ti.GUI`'s behavior should be somehow consistent with `ti.ui.Window` in `GGUI`. But there already exists API called `window.show()` to rander results.
> 
> I wonder are we supposed to have a `window.savefig(file)` here: https://github.com/taichi-dev/taichi/blob/master/taichi/python/export_ggui.cpp#L253-L255 to obtain a `VkBuffer` in RGBA format and save the image using `imwrite` here: https://github.com/taichi-dev/taichi/blob/master/taichi/util/image_io.cpp#L9-L46

This is already implemented. The API is `window.write_image()`. You can find more info here: https://docs.taichi.graphics/lang/articles/misc/ggui

**Comment by AmesingFlank** [comment]
Closed by related PRs: #3333  #3348  #3357 #3359

**Comment by tczhangzhi** [comment]
Good job, dude! You save my day, m just trying to save the visualization results!
