### ISSUE TITLE
Small 3d arrays

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#324]
Hi Yuanming, 

Do you plan to implement a structure like ti.Vector and ti.Matrix for small 3d arrays? right now I just need local storage in kernels. It seems that a python multi-d list can be used for this purpose, but it doesn't work perfectly. 

Thanks,
Ken

**Comment by yuanming-hu** [comment]
Hi KLozes, thanks for the feature request. Yes, I'm planning to add support for stack-allocated small arrays. However this will need some nontrivial IR modification, and I wouldn't do it right now.  Maybe some time in late next January.

**Comment by KLozes** [comment]
Thanks!

**Comment by KLozes** [comment]
just a thought.  Why not implement small arrays along side ```ti.Matrix```? I imagine adding a few more dimensions would be easy.  Of course they wouldn't support dynamic indexing and can only be worked on by a single thread, but I think they could be useful to some users nonetheless.
