### ISSUE TITLE
Investigate Vulkan Issues on macOS

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#3240]
There were a few issues with vulkan on macOS, as discussed in #3231:

* The memory alloc params and flags required are different. More specifically, when either host read or host write is required, the `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT` bit must be a required flag, and the `VK_MEMORY_PROPERTY_HOST_COHERENT_BIT` must be a preferred flag. 

* In vulkan GGUI, changing particle size sometimes doesn't work.

* In mpm3d example, sometimes the fluid goes missing.

* Not all vulkan tests are passing.

**Comment by bobcao3** [comment]
Seems like all the issues in here are fixed at this point. With regard to the vulkan test one, #3456 enabled vulkan test and it seems they are all passing. Closing this issue for now
