### ISSUE TITLE
Avoid duplicate evaluations in chaining comparison 

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#327]
What's the behavior of `1 < ti.append(x, [], 1) < 10`?

**Comment by archibate** [comment]
Behaves bad:
```
>>> 1 < 233 < 10
False
```
You may want to define a function, whose parameter holds temp value:
```python
def between(a, x, b):
  return a < x and x < b
```
Or try `ti.append(x, [], 1) in range(0, 10)` if integer for elegence.

**Comment by yuanming-hu** [comment]
Yeah, call a function is a good solution as the result of `ti.append` is now passed by value instead of getting evaluated twice. Given that the chain can be rather long (e.g. `a < b < c < d < e`), it's better to modify the frontend compiler to cache the results of comparators:  

https://github.com/taichi-dev/taichi/blob/0e5b3e5a44971ab1602192a1079ff0ebbff8361b/python/taichi/lang/transformer.py#L533

Assigning this to @xumingkuan since only a little bit of Python engineering is needed.

**Comment by yuanming-hu** [comment]
Well done by @xumingkuan. Closing.
