### ISSUE TITLE
Ndarray for the OpenGL backend

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#3280]
**Concisely describe the proposed feature**

We need to support `Ndarray` on non-LLVM backends as well. This would greatly simplify the AOT works.

**Describe the solution you'd like (if any)**

Right now Ndarray still stores its memory in a pointer: https://github.com/taichi-dev/taichi/blob/1d85e8f835b08990a824ab79e67e83d3fd9d7f4b/taichi/program/ndarray.h#L31

We need to switch this to `DeviceAllocation`, so that memory representation can be unified across all the backends: https://github.com/taichi-dev/taichi/blob/1d85e8f835b08990a824ab79e67e83d3fd9d7f4b/taichi/backends/device.h#L42-L57

Note that the `Device` interface has provided a method `allocate_memory()` for mem allocation: https://github.com/taichi-dev/taichi/blob/1d85e8f835b08990a824ab79e67e83d3fd9d7f4b/taichi/backends/device.h#L362

Related issue: https://github.com/taichi-dev/taichi/issues/3278

**Comment by ailzhang** [comment]
Closing via https://github.com/taichi-dev/taichi/pull/3555
