### ISSUE TITLE
Python-style mod operator

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#331]
Currently the `%` operator in Taichi follows the `C` style, e.g. `-5%3=-2`
However, in Python `%` is defined as
```
a % b = a - b * (a // b)
```
so `-5%3=1`.

We should make the semantics of `%` follow the Python convention, and introduce `ti.raw_mod` as the `C-style` modular operator.

**This issue can be resolved by modifying the Python code only. Simply replace `__mod__` as `a % b = a - b * (a // b)` and then we are done.**

**Comment by Psycho7** [comment]
I'd like to take it if no one has yet.

**Comment by yuanming-hu** [comment]
Thanks! Please go ahead. Let me know if you run into any issues.

**Comment by Psycho7** [comment]
Made a PR :)

While working on this, found out the floor_div op `//` isn't python-style either. 
Right now `-10 // 3` would give you `-3` instead of `-4`.
So I wrote `floor(truediv(a, b))` instead. Do you want to make `//` pythonic as well?

**Comment by yuanming-hu** [comment]
Thank you so much for pointing this out! I didn't consider too much about the negative inputs. In order to fix this, the internal intermediate representation will need some modification, and I'll do that later today.

**Comment by yuanming-hu** [comment]
Done.
