### ISSUE TITLE
[GGUI] GGUI program cann't run on 0.8.4.

### ISSUE THREAD

**Issue by 0xzhang** [taichi-dev/taichi#3327]
**Describe the bug**
0.8.3 works fine.
```
[Taichi] version 0.8.4, llvm 10.0.0, commit 895881b5, win, python 3.8.10
```

**To Reproduce**
```py
# pip install taichi==0.8.4
# ti example fractal3d_ggui
```

**Log/Screenshots**
![image](https://user-images.githubusercontent.com/33616362/139519395-acf4584c-10e7-4982-8c41-e234e5737439.png)

**Comment by AmesingFlank** [comment]
This is a bug. I noticed it yesterday as well. Will fix soon.
