### ISSUE TITLE
taichi linux wheels are not manylinux1 compliant

### ISSUE THREAD

**Issue by messense** [taichi-dev/taichi#3332]
**Describe the bug**
taichi linux wheels published on PyPI aren't [manylinux1](https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy) compliant.

**To Reproduce**

```bash
# ls
taichi-0.8.4-cp38-cp38-manylinux1_x86_64.whl
# auditwheel show taichi-0.8.4-cp38-cp38-manylinux1_x86_64.whl

taichi-0.8.4-cp38-cp38-manylinux1_x86_64.whl is consistent with the
following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these
system-provided shared libraries: libz.so.1 with versions
{'ZLIB_1.2.0'}, libpthread.so.0 with versions {'GLIBC_2.12',
'GLIBC_2.2.5'}, libm.so.6 with versions {'GLIBC_2.29', 'GLIBC_2.27',
'GLIBC_2.2.5'}, libc.so.6 with versions {'GLIBC_2.9', 'GLIBC_2.6',
'GLIBC_2.17', 'GLIBC_2.14', 'GLIBC_2.11', 'GLIBC_2.16', 'GLIBC_2.15',
'GLIBC_2.7', 'GLIBC_2.3.4', 'GLIBC_2.2.5', 'GLIBC_2.4', 'GLIBC_2.3'},
libdl.so.2 with versions {'GLIBC_2.2.5'}, libstdc++.so.6 with versions
{'GLIBCXX_3.4.22', 'GLIBCXX_3.4.17', 'CXXABI_1.3.2', 'GLIBCXX_3.4.15',
'GLIBCXX_3.4.26', 'GLIBCXX_3.4.9', 'GLIBCXX_3.4.14', 'CXXABI_1.3.7',
'GLIBCXX_3.4.20', 'GLIBCXX_3.4', 'GLIBCXX_3.4.18', 'CXXABI_1.3.11',
'CXXABI_1.3.5', 'CXXABI_1.3.9', 'GLIBCXX_3.4.21', 'CXXABI_1.3',
'CXXABI_1.3.3', 'GLIBCXX_3.4.11', 'GLIBCXX_3.4.19'}

This constrains the platform tag to "linux_x86_64". In order to
achieve a more compatible tag, you would need to recompile a new wheel
from source on a system with earlier versions of these libraries, such
as a recent manylinux image.
```

while manylinux1 policy requires

```
GLIBC <= 2.5
CXXABI <= 3.4.8
GLIBCXX <= 3.4.9
```

**Comment by k-ye** [comment]
Thanks! We are containerizing our CI/CD pipeline, which hopefully will fix this problem.

**Comment by messense** [comment]
Containerization doesn't magically ensures manylinux compliant. As the [auditwheel](https://github.com/pypa/auditwheel) error message suggests, taichi and it's dependencies should be compiled on a [manylinux](https://github.com/pypa/manylinux) docker image.

Note that I don't think taichi needs to be **manylinux1** aka `manylinux_2_5` compliant, it's really old(CentOS 5 released in 2007). I think manylinx2014 aka `manylinux_2_17` is a reasonable choice, then it can run on systems with GLIBC version >= 2.17 for example CentOS 7, Ubuntu 14.04 and later.

**Comment by bobcao3** [comment]
We will try to make our container environment align with the requirements.
Ubuntu 14.04 still does seem quite old, is there a even newer version
target?

**Comment by messense** [comment]
There is `manylinux_2_24` which runs on Ubuntu 18.04 and later, but it won't run on CentOS 7 then as CentOS 7 only has glibc 2.17, could be a problem since CentOS 7 is a quite popular linux distribution in China.

Note that Ubuntu 18.04 itself contains glibc 2.27 so you can't build a manylinux_2_24 compliant wheel on it, [manylinux_2_24 docker images](https://quay.io/repository/pypa/manylinux_2_24_x86_64) are required.

BTW, adopting manylinux2014 and later also enables wheels for architectures other than x86_64 for example aarch64 and armv7l etc.

**Comment by qiao-bo** [comment]
@messense, thanks for the info. These are interesting inputs.

**Comment by ailzhang** [comment]
@messense do you happen to know if the current taichi wheel support ubuntu16.04 or not? :P (we don't have a ubuntu16 machine here but can add one into CI if it's supported) :D Thanks!

**Comment by messense** [comment]
> @messense do you happen to know if the current taichi wheel support ubuntu16.04 or not? :P (we don't have a ubuntu16 machine here but can add one into CI if it's supported) :D Thanks!

No it doesn't work on Ubuntu 16.04

```bash
root@8bd269638e7c:~# python3.8 -m pip install taichi
Collecting taichi
  Downloading taichi-0.8.4-cp38-cp38-manylinux1_x86_64.whl (26.6 MB)
     |████████████████████████████████| 26.6 MB 9.8 MB/s
Collecting pybind11>=2.5.0
  Downloading pybind11-2.8.1-py2.py3-none-any.whl (208 kB)
     |████████████████████████████████| 208 kB 10.7 MB/s
Collecting sourceinspect>=0.0.4
  Downloading sourceinspect-0.0.4-py3-none-any.whl (3.5 kB)
Collecting astor
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting numpy
  Downloading numpy-1.21.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 15.2 MB/s
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting dill
  Downloading dill-0.3.4-py2.py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 6.8 MB/s
Installing collected packages: pybind11, dill, sourceinspect, astor, numpy, colorama, taichi
Successfully installed astor-0.8.1 colorama-0.4.4 dill-0.3.4 numpy-1.21.3 pybind11-2.8.1 sourceinspect-0.0.4 taichi-0.8.4
WARNING: You are using pip version 20.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.
root@8bd269638e7c:~# python3.8
Python 3.8.9 (default, Apr  3 2021, 01:02:10)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taichi
Share object taichi_core import failed, check this page for possible solutions:
https://docs.taichi.graphics/lang/articles/misc/install
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/taichi/__init__.py", line 3, in <module>
    import taichi.ad as ad
  File "/usr/local/lib/python3.8/dist-packages/taichi/ad.py", line 1, in <module>
    from taichi.lang import impl
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/__init__.py", line 10, in <module>
    import taichi.lang.linalg_impl
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/linalg_impl.py", line 1, in <module>
    from taichi.core.util import ti_core as _ti_core
  File "/usr/local/lib/python3.8/dist-packages/taichi/core/__init__.py", line 1, in <module>
    from taichi.core.util import *
  File "/usr/local/lib/python3.8/dist-packages/taichi/core/util.py", line 107, in <module>
    ti_core = import_ti_core()
  File "/usr/local/lib/python3.8/dist-packages/taichi/core/util.py", line 52, in import_ti_core
    raise e from None
  File "/usr/local/lib/python3.8/dist-packages/taichi/core/util.py", line 43, in import_ti_core
    from taichi.lib import taichi_core as core  # pylint: disable=C0415
ImportError: libX11.so.6: cannot open shared object file: No such file or directory
```

**Comment by qiao-bo** [comment]
Thx for the info. I think Ubuntu 16.04 comes with glibc 2.23. ;)

**Comment by k-ye** [comment]
Some updates here: the current Vulkan lib we're using has introduced a dependency on GLIBC_2.29. We will see if downgrading Vulkan could solve this problem.

**Comment by messense** [comment]
It may not  be necessary to downgrade Vulkan, the key is to compile in a manylinux compatible build environment, for example, https://github.com/pypa/manylinux docker images.

**Comment by k-ye** [comment]
> It may not be necessary to downgrade Vulkan, the key is to compile in a manylinux compatible build environment, for example, https://github.com/pypa/manylinux docker images.

We've tried that approach, and found many toolchain required for compiling Taichi missing (e.g. too low gcc version, etc). It's  likely that Vulkan is the blocker here.

**Comment by messense** [comment]
Right, the gcc version thing is annoying, but it's actually high in manylinux2014 (GCC 10) than in manylinux_2_24 (GCC 6.3) though, see https://github.com/pypa/manylinux/issues/1012

```bash
❯ docker run --rm -it quay.io/pypa/manylinux2014_x86_64
[root@129daad4cd25 /]# gcc --version
gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by qiao-bo** [comment]
I am a bit confused here. The [manylinux2014](https://www.python.org/dev/peps/pep-0599/) policy states the max version for GCC is 4.8. But now we have a docker image that is manylinux2014 compliant and with gcc 10 ?(thinking face...)

**Comment by messense** [comment]
It's something **magic** with Red Hat devtoolset-10 that I don't understand.

**Comment by messense** [comment]
See also https://github.com/pypa/manylinux/issues/1141

**Comment by qiao-bo** [comment]
Just want to update here that we managed to build Taichi for CPU (#3542), using the image `quay.io/pypa/manylinux2014_x86_64` based on CentOS 7. The result from auditwheel-symbols indicates the wheel is fully manylinux2014 compliant. Thanks a lot @messense for the useful information discussed here. We will have to see in the future what we can do for the other backends, in particular Vulkan is a bit tricky.

**Comment by GostInShell** [comment]
So is Tachi officially compatible with Ubuntu 16.04 Now？I ran into the following error
``ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by  /xxxxx/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so)``
which is also mentioned in #1313. I am just wondering if the latest tachi still support Ubuntu 16.04 with `GLIBC_2.23'.

**Comment by messense** [comment]
How about distributing a CPU only version of taichi with the name `taichi-cpu` on PyPI? Just like tensorflow has a [tensorflow-cpu](https://pypi.org/project/tensorflow-cpu/) package on PyPI.

**Comment by GostInShell** [comment]
Thanks for the quick reply! I will try to build from source first.

**Comment by qiao-bo** [comment]
> How about distributing a CPU only version of taichi with the name `taichi-cpu` on PyPI? Just like tensorflow has a [tensorflow-cpu](https://pypi.org/project/tensorflow-cpu/) package on PyPI.

That is indeed a viable alternative. Currently we assume most our users employ Ubuntu 18/20.04 for linux OS. If the demand of manylinux CPU-only is there, it should be no problem to have such a version on PyPI. @k-ye @ailzhang WDYT?

**Comment by k-ye** [comment]
Closing this in favor of #4395.
