### ISSUE TITLE
`ti.append` only support `i32`.

### ISSUE THREAD

**Issue by FantasyVR** [taichi-dev/taichi#3337]
**Concisely describe the proposed feature**

The user in the forum wants to use `ti.append` with `float` data type. [Forum link](https://forum.taichi.graphics/t/ti-append/1940/3)
 
However, Taichi doesn't support that according to [here](https://github.com/taichi-dev/taichi/blob/3b179fb0b127d5662fb4f0a29d848fb5efc880ee/taichi/codegen/codegen_llvm.cpp#L1075).

Should we support more data types?

**Comment by k-ye** [comment]
+1. Let's support f32 as a start :-)

**Comment by FantasyVR** [comment]
@k-ye Do you have some ideas about how to implement this feature?

Now, a hack solution is that I could simply change the signature of function `Dynamic_append`:
https://github.com/taichi-dev/taichi/blob/3b179fb0b127d5662fb4f0a29d848fb5efc880ee/taichi/runtime/llvm/node_dynamic.h#L61

as 

```
i32 Dynamic_append(Ptr meta_, Ptr node_, f32 data) {
```

**Comment by WenheLI** [comment]
It seems like we need to wrap the above function signature with a template to allow it?

**Comment by k-ye** [comment]
Templatizing this SGTM! Feel free to take this over, you likely need to spend some time dealing with template functions in LLVM :-) @WenheLI

**Comment by FantasyVR** [comment]
Hi @WenheLI, sorry to bother you. Is there any progress on this issue?
