### ISSUE TITLE
taichi failed to build on Windows with MSVC of win32 "error LNK2019: unresolved external symbol __imp__PyRun_SimpleFileExFlags referenced in function _main" ""

### ISSUE THREAD

**Issue by YangYang129** [taichi-dev/taichi#3362]
Hello All,

taichi failed to build on Windows with MSVC of win32  "error LNK2019: unresolved external symbol __imp__PyRun_SimpleFileExFlags referenced in function _main". It can reproduces on version [82f0705](https://github.com/taichi-dev/taichi/commit/82f07054f15d34756866df47bf28429b2faa269f) on master branch. Could you please help look at this issue?

**Environment:**
VS 2019 + Windows Server 2016

**Reproduce steps:**
1. git clone https://github.com/taichi-dev/taichi F:\project
2. cd taichi
3. git submodule update --init --recursive
4. mkdir build_x86 & cd build_x86
5. download dependencies https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/clang-10.0.0-win.zip and https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/taichi-llvm-10.0.0-msvc2019.zip to folder F:\gitP\taichi-dev\tools
6. set PATH=F:\gitP\taichi-dev\tools\taichi-llvm-10.0.0-msvc2019\bin;%PATH%
7. set PATH=F:\gitP\taichi-dev\tools\clang-10.0.0-win\bin;%PATH%
8. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DTI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -Dgtest_force_shared_crt=TRUE ..
9. msbuild /p:Configuration=Release;Platform=Win32 taichi.sln /t:Rebuild /m

**Error log:**
[msbuild_x86.log](https://github.com/taichi-dev/taichi/files/7465279/msbuild_x86.log)

**Error info:**
23>ti.obj : error LNK2019: unresolved external symbol __imp__PyRun_SimpleFileExFlags referenced in function _main [F:\project\taichi\build_x86\ti.vcxproj]
    23>ti.obj : error LNK2019: unresolved external symbol __imp__Py_Initialize referenced in function _main [F:\project\taichi\build_x86\ti.vcxproj]
    23>ti.obj : error LNK2019: unresolved external symbol __imp__Py_Finalize referenced in function _main [F:\project\taichi\build_x86\ti.vcxproj]
    23>ti.obj : error LNK2019: unresolved external symbol __imp__Py_SetProgramName referenced in function _main [F:\project\taichi\build_x86\ti.vcxproj]
    23>ti.obj : error LNK2019: unresolved external symbol __imp__PySys_SetArgv referenced in function _main [F:\project\taichi\build_x86\ti.vcxproj]
    23>C:\Python39\Lib\site-packages\..\..\libs\python39.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86' [F:\project\taichi\build_x86\ti.vcxproj]
    23>F:\project\taichi\bin\ti.exe : fatal error LNK1120: 5 unresolved externals [F:\project\taichi\build_x86\ti.vcxproj]
37>F:\project\taichi\taichi/common/platform_macros.h(18,15): error C2338: 32-bit Windows systems are not supported (compiling source file F:\project\taichi\taichi\analysis\bls_analyzer.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/platform_macros.h(18,15): error C2338: 32-bit Windows systems are not supported (compiling source file F:\project\taichi\taichi\analysis\alias_analysis.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/platform_macros.h(18,15): error C2338: 32-bit Windows systems are not supported (compiling source file F:\project\taichi\taichi\analysis\cfg_analysis.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/platform_macros.h(18,15): error C2338: 32-bit Windows systems are not supported (compiling source file F:\project\taichi\taichi\analysis\gather_deactivations.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/platform_macros.h(18,15): error C2338: 32-bit Windows systems are not supported (compiling source file F:\project\taichi\taichi\analysis\data_source_analysis.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/core.h(128,11): error C2144: syntax error: 'void' should be preceded by ';' (compiling source file F:\project\taichi\taichi\analysis\bls_analyzer.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/platform_macros.h(18,15): error C2338: 32-bit Windows systems are not supported (compiling source file F:\project\taichi\taichi\analysis\build_cfg.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/core.h(128,11): error C2144: syntax error: 'void' should be preceded by ';' (compiling source file F:\project\taichi\taichi\analysis\alias_analysis.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/core.h(128,11): error C2144: syntax error: 'void' should be preceded by ';' (compiling source file F:\project\taichi\taichi\analysis\cfg_analysis.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/core.h(128,11): error C2144: syntax error: 'void' should be preceded by ';' (compiling source file F:\project\taichi\taichi\analysis\gather_deactivations.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/core.h(128,11): error C2144: syntax error: 'void' should be preceded by ';' (compiling source file F:\project\taichi\taichi\analysis\data_source_analysis.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/platform_macros.h(18,15): error C2338: 32-bit Windows systems are not supported (compiling source file F:\project\taichi\taichi\analysis\count_statements.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]
    37>F:\project\taichi\taichi/common/core.h(128,11): error C2144: syntax error: 'void' should be preceded by ';' (compiling source file F:\project\taichi\taichi\analysis\build_cfg.cpp) [F:\project\taichi\build_x86\taichi_isolated_core.vcxproj]

**Comment by sjwsl** [comment]
As you can see in the logs, taichi does not support 32-bit Windows now :)
