### ISSUE TITLE
GGUI Not Available

### ISSUE THREAD

**Issue by cftcn** [taichi-dev/taichi#3368]
when running ggui example, python raised "GGUI Not Available"

![image](https://user-images.githubusercontent.com/58070700/140093619-0050c364-452d-4752-bafb-567b0073c66e.png)

```
$ ti example mass_spring_3d_ggui
[Taichi] version 0.8.4, llvm 10.0.0, commit 895881b5, osx, python 3.9.7
[Taichi] Starting on arch=metal

**Comment by sjwsl** [comment]
GGUI is currently only supported on the x64 and CUDA backends on Windows and Linux. See https://docs.taichi.graphics/lang/articles/misc/ggui for more details. Thanks!
