### ISSUE TITLE
[misc] New issue templates

### ISSUE THREAD

**Issue by sjwsl** [taichi-dev/taichi#3385]
Should we have more issue templates? I think many of our issues are neither a 'bug report' nor a 'feature request'. At least I can think of:
1. Enhancement: An enhancement makes some existing functionalities better, e.g. in performance, useability. While a feature is a new functionality i.e. a user hopes to do something new with taichi. 
2. Question: Ask anything about taichi.
3. Document: Any issues/confusion about documents.

For example, this issue itself clearly isn't about a bug or feature.

Some examples of famous opensource projects:
https://github.com/flutter/flutter/issues/new/choose
https://github.com/kubernetes/kubernetes/issues/new/choose
https://github.com/facebook/react-native/issues/new/choose
https://github.com/pytorch/pytorch/issues/new/choose
https://github.com/tensorflow/tensorflow/issues/new/choose

**Comment by k-ye** [comment]
Sounds great! I believe 2 and 3 can be a very good start here :-)
