### ISSUE TITLE
Create a bash script for windows dev install 

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#3391]
Steps to build taichi from source is a bit complicated, we should consider providing a script to do the work
- download llvm , add to path
- download clang, add to path
- download vulkan (optional)
- clone taichi and build
It'll also simplify our windows ci worflow

**Comment by frostming** [comment]
I would like to help, do we have such script for Unix systems?

And `.ps1` might be better for Windows。

**Comment by ailzhang** [comment]
@frostming go for it! We don't have such script for Linux as well so it'll be nice to have them too.  But we do have a unix_build.sh that we use in CI(missing some download pieces which is in Dockerfile). IMHO the windows one is higher pri since it'll be useful to CI as well. Thanks a lot!

**Comment by frostming** [comment]
Sorry i didn't link it with the PR but this issue seems ok to be closed.
