### ISSUE TITLE
Do the test time out from time to time?

### ISSUE THREAD

**Issue by SuchtyTV** [taichi-dev/taichi#3411]
Hey,

I've made a pull request who passes all tests except the Macos Testing (Intel).
However, I have checked the "cancelled" test. It has (seemingly) nothing to do with my commit and furthermore there is no reason this test should have failed on Macos but passed on all the other platforms.
Therefore I am wondering if the Test maybe just took so long and timed out?

Thanks!
Niclas

**Comment by SuchtyTV** [comment]
I just pushed again. Works now...

**Comment by k-ye** [comment]
Sorry, sometimes the CI tests can get flaky 😂
