### ISSUE TITLE
Taichi LLVM installation

### ISSUE THREAD

**Issue by NiclasSchwalbe** [taichi-dev/taichi#3413]
I do not seem to get LLVM to work with CMake. I already massacred google because of it.

I downloaded llvm via git and put it into the Programm(x86) folder
In the llvm-repo I made a build folder and wrote

cmake ..\llvm\

Then I went into VS2019 and "Build all targets" 
Which was a huge task and I froze once...
In Taichi we have this requirement in the CMake:

find_package(LLVM REQUIRED CONFIG)

This fails, LLVM is not found.
So I try to add LLVM_INCLUDE_DIRS manually. But this does not seem to work...

What would my  LLVM_INCLUDE_DIRS be? Considering I built in  Programm(x86) folder

http://llvm.org/docs/CMake.html#embedding-llvm-in-your-project

_________________________________________________________________________________

With the help of the LLVM Guys, I have brought it to work.
I made a PULL - Request. But I am not 100% this will do it...

**Comment by sjwsl** [comment]
Hi! Could you try adding `-DLLVM_DIR=C:/Program Files(x86)/LLVM/build/installed/lib/cmake/llvm` when running cmake for taichi?

**Comment by sjwsl** [comment]
Or you can download our [prebuilt LLVM](https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/taichi-llvm-10.0.0-msvc2019.zip). Then use `LLVM_DIR={prebuilt_llvm_directory}/lib/cmake/llvm python3 setup.py develop --user` to build taichi.
