### ISSUE TITLE
A cleaner error report mechanism

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#3422]
#3345 makes error messages for type errors much more user-friendly. However, the mechanism of implementing this is a bit ad-hoc: https://github.com/taichi-dev/taichi/blob/0e4ca37c2581f6e449c193612e77657c4dd87865/python/taichi/lang/expr.py#L41-L54

Here, we extracts parts of the backtrace stack, manually prints them and `sys.exit(1)`. The main concern is that this is no longer a Python `Exception`, which makes it hard to fit in other places (e.g. testing frameworks which needs to catch the `Exception`). We need to figure out a way to modify the backtrace stack of an `Exception` in Python 3.6.

**Comment by frostming** [comment]
If we are to raise an exception, it can only be done at high level apis, since an error thrown by a lower level function can't discard the stacks above it.

May be `_kernel_impl` is a proper place.
