### ISSUE TITLE
Move python/build.py to misc

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#3423]
`python/build.py` is the entry point where we build python wheels, it should live in misc instead of `python` folder. 
Fixing this might require making some changes to CI as well, e.g. https://github.com/taichi-dev/taichi/blob/master/.github/workflows/presubmit.yml#L425

**Comment by frostming** [comment]
In the latest PR #3410 I replaced the usage of `build.py` in favor of calling `setup.py` directly. So IMO we can get rid of that file entirely.

It has two responsibilities: build and upload, for build we can move it into dedicated scripts(like `win_build.ps1` and upload we can make use of GitHub action.

**Comment by ailzhang** [comment]
@frostming I'd be happy to get rid of the file! ;) Yea then the tasks become: 
- move linux & mac jobs to setup.py instead of build.py
- create a github action for upload 
Are you interested in helping on these btw? :D

**Comment by frostming** [comment]
Yes, it is a continuation of #3410
