### ISSUE TITLE
Skip a test with walrus operator in pytest when python version is below 3.8

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#3425]
**Concisely describe the proposed feature**
When I was writing tests of walrus operator, I found that pytest fails to collect the files containing the walrus operator when python version is below 3.8. Adding `@pytest.mark.skipif(sys.version_info < (3, 8))` or defining the function inside `if sys.version_info >= (3, 8)` does not help. It seems that pytest compiles the whole file when collecting tests and the compilation fails when there is a syntax error, e.g. a walrus operator in python 3.6, in any place of the file.

**Describe the solution you'd like (if any)**
The only solution I can think of is separating the test into a new file and letting ti test skip the file when python version is below 3.8.

**Additional comments**
![image](https://user-images.githubusercontent.com/90667349/140707013-29f87d81-49cb-4cf1-80dd-2d5e943f0fea.png)

**Comment by ailzhang** [comment]
Closing as this is worked around by creating a python38 folder
