### ISSUE TITLE
Creating tapes on elements of tensors as losses

### ISSUE THREAD

**Issue by aespielberg** [taichi-dev/taichi#344]
I'm not sure if I'm doing something dumb here or if this is unsupported, but for some reason, the following code gives me the errror:

```
Traceback (most recent call last):
  File "bug_test.py", line 52, in <module>
    with ti.Tape(loss):
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/__init__.py", line 77, in Tape
    assert loss.snode().ptr.has_grad(), "gradient for loss not allocated"
AttributeError: 'float' object has no attribute 'snode'
```

```
import numpy as np
import taichi as ti

@ti.data_oriented
class MLP: 
  
  def __init__(self, num_steps, num_inputs, num_outputs, hidden_layers = (), activations=(ti.tanh,)):
    assert len(activations) == len(hidden_layers) + 1 
    self.k = 0
    self.activations = activations
    self.sizes = [num_inputs] + [layer for layer in hidden_layers] + [num_outputs]
    self.weights = []
    self.biases = []
    self.hiddens = [] 
    
    for pair in zip(self.sizes[:-1], self.sizes[1:]):
      self.weights.append(ti.var(dt=ti.f32, shape=pair, needs_grad=True))
      self.biases.append(ti.var(dt=ti.f32, shape=pair[1:], needs_grad=True))
      self.hiddens.append(ti.var(dt=ti.f32, shape=(num_steps, pair[1]), needs_grad=True)) #note that the last hidden is the final actuation  

  def forward(self, obs, s):
    self.forward_input(obs, s)
    
  @ti.classkernel
  def forward_input(self, obs: ti.template(), s: ti.i32):
    #s is the step number
    in_size = self.sizes[0]
    out_size = self.sizes[1]    
    for i in range(out_size):
      output = 0.0
      for j in range(in_size):
        output += self.weights[0][i, j] * obs[j]      
      output += self.biases[0][i]
      activated_output = self.activations[0](output)
      self.hiddens[0][s, i] = activated_output #the last "hidden" is the output
      

#For testing only!         
if __name__ == '__main__':
  @ti.layout
  def place():
    ti.root.lazy_grad()
  
  nn = MLP(10, 2, 4, (), (ti.tanh,))    
  obs = ti.var(dt=ti.f32, shape=(2,), needs_grad=True)

  for i in range(2):
    obs[i] = np.random.rand()
  
  with ti.Tape(nn.hiddens[0][0, 0]):
    nn.forward(obs, 0)
  
  out = nn.get_output()
  print(out.to_numpy())
  for weights in nn.weights:
    print(weights.grad.to_numpy())
```

**Comment by yuanming-hu** [comment]
Hi Andy,

ti.Tape takes only a 0-D global tensor variable as input. Please declare
loss = ti.var(ti.f32, shape=(), needs_grad=True)

and do a kernel to copy nn.hiddens[0][0, 0] to loss.
And finally use loss as the ti.Tape argument.

Best,
Yuanming

**Comment by aespielberg** [comment]
This causes a gdb trigger:

import numpy as np
import taichi as ti

@ti.data_oriented
class MLP:

  def __init__(self, num_steps, num_inputs, num_outputs, hidden_layers =
(), activations=(ti.tanh,)):
    assert len(activations) == len(hidden_layers) + 1
    self.k = 0
    self.activations = activations
    self.sizes = [num_inputs] + [layer for layer in hidden_layers] +
[num_outputs]
    self.weights = []
    self.biases = []
    self.hiddens = []
    self.loss =  ti.var(ti.f32, shape=(), needs_grad=True)

    for pair in zip(self.sizes[:-1], self.sizes[1:]):
      self.weights.append(ti.var(dt=ti.f32, shape=pair, needs_grad=True))
      self.biases.append(ti.var(dt=ti.f32, shape=pair[1:], needs_grad=True))
      self.hiddens.append(ti.var(dt=ti.f32, shape=(num_steps, pair[1]),
needs_grad=True)) #note that the last hidden is the final actuation


  def forward(self, obs, s):
    self.forward_input(obs, s)
    self.loss[None] = nn.hiddens[0][0, 0]


  @ti.classkernel
  def forward_input(self, obs: ti.template(), s: ti.i32):
    #s is the step number
    in_size = self.sizes[0]
    out_size = self.sizes[1]
    for i in range(out_size):
      output = 0.0
      for j in range(in_size):
        output += self.weights[0][i, j] * obs[j]
      output += self.biases[0][i]
      activated_output = self.activations[0](output)
      self.hiddens[0][s, i] = activated_output #the last "hidden" is the
output


#For testing only!
if __name__ == '__main__':
  @ti.layout
  def place():
    ti.root.lazy_grad()

  nn = MLP(10, 2, 4, (), (ti.tanh,))
  obs = ti.var(dt=ti.f32, shape=(2,), needs_grad=True)

  for i in range(2):
    obs[i] = np.random.rand()

  with ti.Tape(nn.loss):
    nn.forward(obs, 0)


  out = nn.get_output()
  print(out.to_numpy())
  for weights in nn.weights:
    print(weights.grad.to_numpy())

**Comment by yuanming-hu** [comment]
Hi Andy,

So sorry about the delay. I had to deal with some urgent stuff. Here's the working version: 
```
import numpy as np
import taichi as ti

@ti.data_oriented
class MLP:

  def __init__(self, num_steps, num_inputs, num_outputs, hidden_layers =
(), activations=(ti.tanh,)):
    assert len(activations) == len(hidden_layers) + 1
    self.k = 0
    self.activations = activations
    self.sizes = [num_inputs] + [layer for layer in hidden_layers] + [num_outputs]
    self.weights = []
    self.biases = []
    self.hiddens = []
    self.loss =  ti.var(ti.f32, shape=(), needs_grad=True)

    for pair in zip(self.sizes[:-1], self.sizes[1:]):
      self.weights.append(ti.var(dt=ti.f32, shape=pair, needs_grad=True))
      self.biases.append(ti.var(dt=ti.f32, shape=pair[1:], needs_grad=True))
      self.hiddens.append(ti.var(dt=ti.f32, shape=(num_steps, pair[1]),
needs_grad=True)) #note that the last hidden is the final actuation


  def forward(self, obs, s):
    self.forward_input(obs, s)
    self.loss[None] = nn.hiddens[0][0, 0]


  @ti.classkernel
  def forward_input(self, obs: ti.template(), s: ti.i32):
    #s is the step number
    for i in range(self.sizes[1]):
      out_size = self.sizes[1]
      output = 0.0
      for j in ti.static(range(self.sizes[0])):
        output += self.weights[0][i, j] * obs[j]
      output += self.biases[0][i]
      activated_output = self.activations[0](output)
      self.hiddens[0][s, i] = activated_output #the last "hidden" is the output


#For testing only!
if __name__ == '__main__':
  @ti.layout
  def place():
    ti.root.lazy_grad()

  nn = MLP(10, 2, 4, (), (ti.tanh,))
  obs = ti.var(dt=ti.f32, shape=(2,), needs_grad=True)

  for i in range(2):
    obs[i] = np.random.rand()

  with ti.Tape(nn.loss):
    nn.forward(obs, 0)


  out = nn.get_output()
  print(out.to_numpy())
  for weights in nn.weights:
    print(weights.grad.to_numpy())
```
Just two things:
 - Please keep the kernel structure simple: declaring `out_size=self.sizes[1]` outside the loop body may confuse the compiler. This is an implementation limitation and I'll try to improve this.
 - Add `ti.static` to 
```python
for j in ti.static(range(self.sizes[0])):
  output += self.weights[0][i, j] * obs[j]
```
so that local variable mutation gets unrolled and simplified, into a form that can be automatically differentiated. Again, I'll try to make the compiler smarter to autodiff this pattern.

**Comment by aespielberg** [comment]
Hi Yuanming,

Thank you for this.  Is there any way to do this without ti.static,
though?  These loops can be very large, so fully unrolled, they are taking
a VERY long time to compile as I generalize this.  I know in one of your
examples, you have an nn1 and an nn2, and this didn't require a ti.static,
so I'm wondering why this is needed here?

-Andy S.

**Comment by yuanming-hu** [comment]
I think it's fine if the number of neurons is < 128.
In nn1 and nn2, the contributions are accumulated to a global tensor instead of a local variable. Differentiating global tensor atomic add is supported so you don't need unrolling.

**Comment by aespielberg** [comment]
Sorry, one additional question.  For some reason, the gradients are all 0.
But, this clearly should not be.  Do you have any idea as to what would
cause this?

-Andy S.

**Comment by aespielberg** [comment]
I see, so if I create a global tensor in the class, this should work?

Right now I have an example with (64, 32) hidden neurons and it's causing
the system to have very long compilation issues, so I'll add a global
tensor for the intermediate.

**Comment by aespielberg** [comment]
Adding the global tensor self.outputs and storing to that did not allow me
to remove the ti.static :-/

**Comment by aespielberg** [comment]
Ah, I have to apologize - I see that the static is only needed on the inner
loop.  I thought it was needed on both.  What is the reason for this?

In that case, this works, although I don't know why the gradients are all
0s.

**Comment by yuanming-hu** [comment]
Hi Andy,

Sorry about the confusion. You only need static for loops for the inner loop, because only the inner loop interacts with the mutable local variable.

**Comment by yuanming-hu** [comment]
I can take a look at your code to learn about why the gradients are zero, if you post your code here.

**Comment by aespielberg** [comment]
The same code you posted should show, just remove the lines:

out = nn.get_output()
 print(out.to_numpy())

Which I had forgotten to delete.

**Comment by yuanming-hu** [comment]
Hi Andy, please copy the loss using a Taichi kernel. Operations in Python scope is not captured for autodiff:

```
import numpy as np
import taichi as ti

@ti.data_oriented
class MLP:

  def __init__(self, num_steps, num_inputs, num_outputs, hidden_layers =
(), activations=(ti.tanh,)):
    assert len(activations) == len(hidden_layers) + 1
    self.k = 0
    self.activations = activations
    self.sizes = [num_inputs] + [layer for layer in hidden_layers] + [num_outputs]
    self.weights = []
    self.biases = []
    self.hiddens = []
    self.loss =  ti.var(ti.f32, shape=(), needs_grad=True)

    for pair in zip(self.sizes[:-1], self.sizes[1:]):
      self.weights.append(ti.var(dt=ti.f32, shape=pair, needs_grad=True))
      self.biases.append(ti.var(dt=ti.f32, shape=pair[1:], needs_grad=True))
      self.hiddens.append(ti.var(dt=ti.f32, shape=(num_steps, pair[1]),
needs_grad=True)) #note that the last hidden is the final actuation


  def forward(self, obs, s):
    self.forward_input(obs, s)
    self.copy_loss()

  @ti.classkernel
  def copy_loss(self):
    self.loss[None] = nn.hiddens[0][0, 0]


  @ti.classkernel
  def forward_input(self, obs: ti.template(), s: ti.i32):
    #s is the step number
    for i in range(self.sizes[1]):
      out_size = self.sizes[1]
      output = 0.0
      for j in ti.static(range(self.sizes[0])):
        output += self.weights[0][i, j] * obs[j]
      output += self.biases[0][i]
      activated_output = self.activations[0](output)
      self.hiddens[0][s, i] = activated_output #the last "hidden" is the output


#For testing only!
if __name__ == '__main__':
  @ti.layout
  def place():
    ti.root.lazy_grad()

  nn = MLP(10, 2, 4, (), (ti.tanh,))
  obs = ti.var(dt=ti.f32, shape=(2,), needs_grad=True)

  for i in range(2):
    obs[i] = np.random.rand()

  with ti.Tape(nn.loss):
    nn.forward(obs, 0)

  for weights in nn.weights:
    print(weights.grad.to_numpy())
```

**Comment by aespielberg** [comment]
Ahh, it works, okay.  Sorry for the confusion!  Thank you for the help and
for the clarification on static loops as well.

-Andy S.

**Comment by yuanming-hu** [comment]
Cool!

**Comment by aespielberg** [comment]
Actually, I want to ask one follow-up question.  I am trying to incorporate more layers, to make this a full MLP.  I defined another kernel that does anything past the first layer.  I now initialize the weights to be nontrivial, and make the loss dependent on the output of the last layer.  For some reason, now all the gradients are 0 again :(

```
import numpy as np
import taichi as ti

@ti.data_oriented
class MLP:

  def __init__(self, num_steps, num_inputs, num_outputs, hidden_layers =
(), activations=(ti.tanh,)):
    assert len(activations) == len(hidden_layers) + 1
    self.k = 0
    self.activations = activations
    self.sizes = [num_inputs] + [layer for layer in hidden_layers] + [num_outputs]
    self.weights = []
    self.biases = []
    self.hiddens = []
    self.loss =  ti.var(ti.f32, shape=(), needs_grad=True)

    for pair in zip(self.sizes[:-1], self.sizes[1:]):
      self.weights.append(ti.var(dt=ti.f32, shape=pair, needs_grad=True))
      self.biases.append(ti.var(dt=ti.f32, shape=pair[1:], needs_grad=True))
      self.hiddens.append(ti.var(dt=
ti.f32, shape=(num_steps, pair[1]),
needs_grad=True)) #note that the last hidden is the final actuation
    
    for i, pair in enumerate(zip(self.sizes[:-1], self.sizes[1:])):
      
      for j in range(pair[1]):
        self.biases[i][j] = np.random.rand()
        for k in range(pair[0]):
          self.weights[i][j, k] = np.random.rand()

  def forward(self, obs, s):
    self.forward_input(obs, s)
    for k in range(1, len(self.weights)):
      self.forward_other(s, k)
    self.copy_loss()
    
  @ti.classkernel
  def copy_loss(self):
    self.loss[None] = nn.hiddens[-1][0, 0]

  @ti.classkernel
  def forward_input(self, obs: ti.template(), s: ti.i32):
    #s is the step number
    for i in range(self.sizes[1]):
      out_size = self.sizes[1]
      output = 0.0
      for j in ti.static(range(self.sizes[0])):
        output += self.weights[0][i, j] * obs[j]
      output += self.biases[0][i]
      activated_output = self.activations[0](output)
      self.hiddens[0][s, i] = activated_output #the last "hidden" is the output
      
  @ti.classkernel
  def forward_other(self, s: ti.i32, k: ti.template()):    
    for i in range(self.sizes[k + 1]):
      output = 0.0
      for j in ti.static(range(self.sizes[k])):
        input_value = self.hiddens[k - 1][s, j]
        output += self.weights[k][i, j] * input_value
      
      output += self.biases[k][i]
      activated_output = self.activations[k](output)
      self.hiddens[k][s, i] = activated_output #the last "hidden" is the output
    


#For testing only!
if __name__ == '__main__':
  @ti.layout
  def place():
    ti.root.lazy_grad()

  obs = ti.var(dt=ti.f32, shape=(2,), needs_grad=True)
  nn = MLP(10, 2, 4, (64, 64), (ti.tanh, ti.tanh, ti.tanh))
  

  for i in range(2):
    obs[i] = np.random.rand()

  with ti.Tape(nn.loss):
    nn.forward(obs, 0)


  print('loss is ', nn.loss[None])
  for weights in nn.weights:
    print('weight grad is ', weights.grad.to_numpy())
```
