### ISSUE TITLE
example of TAI_CMAKE_ARGS seems to be wrong

### ISSUE THREAD

**Issue by junaire** [taichi-dev/taichi#3481]
I'm trying to customize `TAI_CMAKE_ARGS` when building taichi, and I found a possible mistake in [https://docs.taichi.graphics/zh-Hans/lang/articles/contribution/dev_install#installing-dependencies](https://docs.taichi.graphics/zh-Hans/lang/articles/contribution/dev_install#installing-dependencies). 

```
export TAICHI_CMAKE_ARGS="-DCMAKE_CXX_COMPILER=<path_to_llvm_folder>/bin/clang++:$TAICHI_CMAKE_ARGS"
```
It failed with errors:
```
....
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/jun/dev/cpp-projects/taichi', '-DCMAKE_CXX_COMPILER=~/dev/llvm/build/bin/clang++:', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/jun/dev/cpp-projects/taichi/build', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DTI_VERSION_MAJOR=0', '-DTI_VERSION_MINOR=8', '-DTI_VERSION_PATCH=6', '-DCMAKE_BUILD_TYPE=Debug']' returned non-zero exit status 1.

```

So I tried:
```
unset TAI_CMAKE_ARGS
export TAICHI_CMAKE_ARGS="-DCMAKE_CXX_COMPILER=~/dev/llvm/build/bin/clang++ $TAICHI_CMAKE_ARGS"
```
**I removed the `:`**

Then here we go.

So I guess the doc should be corrected like:
```
export TAICHI_CMAKE_ARGS="-DCMAKE_CXX_COMPILER=<path_to_llvm_folder>/bin/clang++ $TAICHI_CMAKE_ARGS"
```
Or we can split the string by `:` in https://github.com/taichi-dev/taichi/blob/28c450fd445cc44ecfdcc8be9f873cd8cb5476f8/setup.py#L113

**Comment by sjwsl** [comment]
Great! Would you mind submitting a PR for this?

**Comment by junaire** [comment]
> Great! Would you mind submitting a PR for this?

My pleasure!

**Comment by junaire** [comment]
close via #3485
