### ISSUE TITLE
Workflow for complex kernels

### ISSUE THREAD

**Issue by aespielberg** [taichi-dev/taichi#350]
This is a feature request or a clarification, not sure which.

Right now, if you define a complex kernel with a custom gradient, you need to manually specify the gradient of the entire kernel.  That's fine - but the kernel may be very complex, and launch many sub-kernels, for instance.  Those sub-kernels may be packaged into bigger functions, for convenience; e.g. a function that does a forward pass of a neural network by launching a bunch of sub-kernels (while the complex kernel may be a simulation that surrounds the network).

For convenience and clarity, there may be a lot of such functions in the complex kernel.  It would be extremely annoying to have to suddenly define the backward pass of every function called by the complex kernel.  As far as I can see, there are three options:

1. Manually define the backward pass of every non-kernel.
2. Package the functions called into their own complex kernels.  This may or may not be doable, depending on the structure.  This only helps, though, if two things are true: a). complex kernels can call other complex kernels; b) complex kernels have a default gradient that's created.  I don't know if either of these conditions are true.
3. Have some way of automatically generating the backward pass of non-kernels, maybe with a unique decorator.  However, I suspect this is a ton of work.

I'm not sure if there is any solution here other than the cumbersome 1., but I'm wondering if there is any option to make working with complex_kernels easier.

**Comment by yuanming-hu** [comment]
In my opinion complex kernels are seldom used as small components of a large kernel. The only situation may be differentiating SVD. Do you have other concrete use cases? Thanks.

**Comment by aespielberg** [comment]
Well, in context of MPM and the MLP class I've posted here, let's say I
want to put an MLP inside the simulation directly.

The MLP has a regular function to do the forward pass, which contains
layer-wise kernels.  This could be converted to a complexkernel, but either
way, the gradients need to be defined.

In MPM, there's a complexkernel for the forward advance.  That means the
gradients need to be manually specified, which would require manually
specifying the gradients of literally anything that goes in it, if I
understand correctly.

-Andy S.
