### ISSUE TITLE
Automatically approve first time contributor's workflow

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#3514]
Looks like this will help: https://github.com/mheap/automatic-approve-action

**Comment by yihong0618** [comment]
Seems not a good idea, actions may cause some security issue. 

like: 
https://medium.com/cider-sec/bypassing-required-reviews-using-github-actions-6e1b29135cc7
https://nova.moe/steal-credentials-from-ci-agents/

**Comment by ailzhang** [comment]
@yihong0618 hmmm yea that makes sense, sure let's put it aside then. (we were a bit overwhelmed by these "approve and run"s during the pylint activity :P but yea I do agree the security concern is valid.
