### ISSUE TITLE
clear_data_and_deactivate

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#352]
Hi Yuanming, 

This may have slipped through the cracks. Do you intend to implement this feature soon?

Thanks,
Ken L

**Comment by yuanming-hu** [comment]
Yes, but I need to first think about memory allocation/gc as a whole...

**Comment by yuanming-hu** [comment]
@KLozes thanks for closing this. Note: although this is implemented, the performance still needs optimization...
