### ISSUE TITLE
How to handle type polymorphism in structs or data orientated classes

### ISSUE THREAD

**Issue by bsavery** [taichi-dev/taichi#3543]
Zooming out from my issue on #2733 I'd like a better way to handle function polymorphism on custom types.  For example, let's say I have a type A, and type B.  Both with different `compute()` methods.  There is no clean way to execute the correct compute method without injecting all the code or a big ugly if/else statement.  But I'm looking for suggestions.  Maybe this comes down to having function pointers?

Here's how I currently solve something like this:

```python
@ti.func
def typeA_compute(obj):
     # in reality this is more complex
     return obj.x + obj.y
typeA = ti.types.struct(x=ti.i32, y=ti.i32)

@ti.func
def typeB_compute(obj):
    return obj.x + obj.y + obj.z
typeB = ti.types.struct(x=ti.f32, y=ti.f32, z=ti.f32)


@ti.kernel
def my_kernel():
     some_obj = get_some_typeA_or_B()
     if is_type_A(some_obj):
         typeA_compute(some_obj)
     else:
         typeB_compute(some_obj)
```

This is obviously a simple example, but the problem here is in a more complex example that you're injecting a lot of "dead" code since the ti.func is getting inlined.  
So this is where we could use `@ti.data_oriented` for our type A/B definitions?  But then we can't have a array of data_orientated objects.  (array of structures)

So if I could do 

```python
@ti.data_oriented
class TypeA:
  def __init__(self, x, y, n):
    self.x = ti.field(ti.i32, shape=())
    self.y = ti.field(ti.i32, shape=())
    self.x = x
    self.y = y

  @ti.func
  def compute(self):
     return self.x + self.y


@ti.data_oriented
class TypeB:
  def __init__(self, x, y, z, n):
    self.x = ti.field(ti.i32, shape=())
    self.y = ti.field(ti.i32, shape=())
    self.z= ti.field(ti.i32, shape=())
    self.x = x
    self.y = y
    self.z = z

  @ti.func
  def compute(self):
     return self.x + self.y + self.z


my_objs = [TypeA(1,2), TypeB(2,3,4), TypeC(3,4,5)]

@ti.kernel
def kernel(I = ti.i32) -> ti.i32:
    obj = my_objs[I]
    return obj.compute()
```
     
this would be fine too, but I can't make list of disparate types and access them.  

So I'm looking for ideas here.  My thoughts are:
1.  Allow binding functions to structs 
2. function pointers?
3. Arrays of data oriented classes

**Comment by k-ye** [comment]
Thanks! This is still blocked on the real function support: https://github.com/taichi-dev/taichi/issues/602. 

As for `@ti.data_oriented`, this is actually meant to be used on the host side. It is designed to modularize the code, by grouping kernels and fields within a class. So binding functions to structs sounds like a more reasonable approach.

**Comment by bsavery** [comment]
Great.  I'll follow that issue #602 and close this, rename the other issue to request for binding functions to structs.
