### ISSUE TITLE
How to build taichi from source

### ISSUE THREAD

**Issue by tisonkun** [taichi-dev/taichi#3550]
Neither CONTRIBUTING.md nor [docs](https://docs.taichi.graphics/lang/articles/contribution/contributor_guide) gives instructions to get started with taichi by firstly building taichi from source.

**Comment by tisonkun** [comment]
Found https://docs.taichi.graphics/lang/articles/contribution/dev_install#setting-up-taichi-for-development ...

Let me give it a try.

**Comment by skyzh** [comment]
In fact, I feel the development guide confusing at first. I spent about 2 hours installing the correct version of clang.

The document didn't mention the difference of LLVM and clang. At first I thought I only need to install Taichi's custom version of LLVM. Lately I found that the prebuilt LLVM doesn't contain clang++. Then I installed llvm@11 from brew, and the CMake complains about unsupported asm syntax. Only then did I find out that I need to install both Taichi's LLVM 10 and brew's LLVM 11 (which contains clang++).

**Comment by tisonkun** [comment]
@skyzh thanks for your information. Yes this part is a bit tricky.

Finally, I made it. I think it's worth a section to elaborate on how to config taichi's specific LLVM. And separate by platform, not step by step expanding multiple platforms and many "Notes". For example, working on a darwin OS, I don't care about notes on arch linux.
