### ISSUE TITLE
Low FPS of ray_tracer

### ISSUE THREAD

**Issue by bolin12** [taichi-dev/taichi#3566]
FPS of https://github.com/taichiCourse01/taichi_ray_tracing/blob/master/4_0_path_tracing.py is merely 20FPS

Settings:
RTX2080
[Taichi] version 0.8.3, llvm 10.0.0, commit 021af5d2, win, python 3.8.10
[Taichi] Starting on arch=cuda

Taichi system diagnose:
```
python: 3.8.10 | packaged by conda-forge | (default, Sep 13 2021, 21:12:34) [MSC v.1916 64 bit (AMD64)]
system: win32
executable: C:\ProgramData\Miniconda3\python.exe
platform: Windows-10-10.0.19042-SP0
architecture: 64bit WindowsPE
uname: uname_result(system='Windows', node='MSI', release='10', version='10.0.19042', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 10, GenuineIntel')
locale: zh_CN.cp936

PATH: C:\ProgramData\Miniconda3;C:\ProgramData\Miniconda3\Library\mingw-w64\bin;C:\ProgramData\Miniconda3\Library\usr\bin;C:\ProgramData\Miniconda3\Library\bin;C:\ProgramData\Miniconda3\S
cripts;C:\ProgramData\Miniconda3\bin;C:\ProgramData\Miniconda3\condabin;D:\software\vmware\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin;C:\Program Files\NVIDIA GPU Com
puting Toolkit\CUDA\v11.1\libnvvp;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS;C:\Windows\syst
em32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\P
rogram Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Compo
nents\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\Syst
em32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\nodejs;C:\Program Files (x86)\Wolfram Research\WolframScript;C:\Users\lbl\AppData\Local\Programs\Python\Python38-3
2;C:\Users\lbl\AppData\Local\Programs\Python\Python38-32\Scripts;C:\Program Files (x86)\Google\Chrome\Application;C:\mingw64\bin;D:\software\matlab2020b\bin;D:\library\opencv\opencv\build
\bin;D:\library\opencv\opencv\build\x64\vc15\bin;D:\software\cmake\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System
32\OpenSSH;C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.2.0;D:\software\anaconda;D:\software\anaconda\Library\bin;D:\software\anaconda\Scripts;D:\software\xshell;C:\Program Fil
es\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64;C:\Program Files\Wolfram Research\WolframScript;D:\software\xftp;C:\User
s\lbl\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\lbl\AppData\Local\Programs\Python\Python38;C:\Users\lbl\AppData\Local\Microsoft\WindowsApps;C:\Users\lbl\AppData\Roaming\npm;
C:\Users\lbl\AppData\Local\GitHubDesktop\bin;C:\mingw64\bin;D:\library\opencv\opencv\build\bin;D:\library\opencv\opencv\build\x64\vc15\bin;D:\software\vscode\Microsoft VS Code\bin;D:\soft
ware\cmake\bin;D:\software\pycharm\PyCharm Community Edition 2021.1\bin;.;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64;.;C:\User
s\lbl\AppData\Roaming\Python\Python38\site-packages\taichi\core\../lib
PYTHONPATH: ['C:\\ProgramData\\Miniconda3\\Scripts\\ti.exe', 'C:\\ProgramData\\Miniconda3\\python38.zip', 'C:\\ProgramData\\Miniconda3\\DLLs', 'C:\\ProgramData\\Miniconda3\\lib', 'C:\\Pro
gramData\\Miniconda3', 'C:\\Users\\lbl\\AppData\\Roaming\\Python\\Python38\\site-packages', 'C:\\Users\\lbl\\AppData\\Roaming\\Python\\Python38\\site-packages\\win32', 'C:\\Users\\lbl\\Ap
pData\\Roaming\\Python\\Python38\\site-packages\\win32\\lib', 'C:\\Users\\lbl\\AppData\\Roaming\\Python\\Python38\\site-packages\\Pythonwin', 'C:\\ProgramData\\Miniconda3\\lib\\site-packa
ges', 'C:\\ProgramData\\Miniconda3\\lib\\site-packages\\win32', 'C:\\ProgramData\\Miniconda3\\lib\\site-packages\\win32\\lib', 'C:\\ProgramData\\Miniconda3\\lib\\site-packages\\Pythonwin'
, 'C:\\Users\\lbl\\AppData\\Roaming\\Python\\Python38\\site-packages\\taichi\\core\\../lib']

`lsb_release` not available: [WinError 2] 系统找不到指定的文件。


import: <module 'taichi' from 'C:\\Users\\lbl\\AppData\\Roaming\\Python\\Python38\\site-packages\\taichi\\__init__.py'>

cc: False
cpu: True
metal: False
opengl: True
cuda: True
vulkan: True

`glewinfo` not available: [WinError 2] 系统找不到指定的文件。

Sat Nov 20 20:33:12 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 496.13       Driver Version: 496.13       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8    15W /  N/A |    476MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+


[Taichi] version 0.8.3, llvm 10.0.0, commit 021af5d2, win, python 3.8.10

[Taichi] version 0.8.3, llvm 10.0.0, commit 021af5d2, win, python 3.8.10
[Taichi] Starting on arch=x64

[Taichi] version 0.8.3, llvm 10.0.0, commit 021af5d2, win, python 3.8.10
[Taichi] Starting on arch=opengl

[Taichi] version 0.8.3, llvm 10.0.0, commit 021af5d2, win, python 3.8.10
[Taichi] Starting on arch=cuda

[Taichi] version 0.8.3, llvm 10.0.0, commit 021af5d2, win, python 3.8.10
```

**Comment by strongoier** [comment]
cc: @erizmr

**Comment by erizmr** [comment]
Thanks for reporting this and sorry for late reply. 
I have tested the example on cuda backend using my Linux machine with RTX 2060. The FPS is typically ~40Fps.
Would you mind providing the profiling info shown below?

To print these info, there are two lines to modify/add:
```
# Add kernel_profiler=True in the ti.init()
ti.init(arch=ti.gpu, kernel_profiler=True)
...

# Add print profile info at the end of the program
ti.print_kernel_profile_info()
```

Sample profiling info output on my machine:
```
[Taichi] version 0.8.3, llvm 10.0.0, commit 2680dabd, linux, python 3.8.10
[Taichi] Starting on arch=cuda
=========================================================================
Kernel Profiler(count) @ CUDA on GeForce RTX 2060
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
-------------------------------------------------------------------------
[ 96.65%   4.171 s    535x |    6.938     7.797    16.925 ms] render_c40_0_kernel_10_range_for
[  2.14%   0.093 s      1x |   92.566    92.566    92.566 ms] runtime_initialize
[  1.18%   0.051 s    535x |    0.055     0.095     1.206 ms] matrix_to_ext_arr_c20_0_kernel_11_range_for
[  0.01%   0.000 s     37x |    0.004     0.011     0.013 ms] jit_evaluator_0_kernel_0_serial
[  0.01%   0.000 s     21x |    0.004     0.011     0.013 ms] jit_evaluator_2_kernel_2_serial
[  0.00%   0.000 s     14x |    0.003     0.009     0.014 ms] jit_evaluator_3_kernel_3_serial
[  0.00%   0.000 s      6x |    0.004     0.019     0.085 ms] jit_evaluator_6_kernel_7_serial
[  0.00%   0.000 s      3x |    0.012     0.037     0.085 ms] jit_evaluator_5_kernel_5_serial
[  0.00%   0.000 s      1x |    0.108     0.108     0.108 ms] runtime_memory_allocate_aligned
[  0.00%   0.000 s      1x |    0.059     0.059     0.059 ms] runtime_initialize_snodes
[  0.00%   0.000 s      1x |    0.040     0.040     0.040 ms] fill_matrix_c28_0_kernel_8_range_for
[  0.00%   0.000 s      2x |    0.012     0.012     0.012 ms] jit_evaluator_4_kernel_4_serial
[  0.00%   0.000 s      2x |    0.006     0.009     0.012 ms] jit_evaluator_7_kernel_9_serial
[  0.00%   0.000 s      1x |    0.013     0.013     0.013 ms] reset_c38_0_kernel_6_serial
[  0.00%   0.000 s      1x |    0.013     0.013     0.013 ms] jit_evaluator_1_kernel_1_serial
-------------------------------------------------------------------------
[100.00%] Total execution time:   4.316 s   number of results: 15
=========================================================================

```

**Comment by bolin12** [comment]
> Thanks for reporting this and sorry for late reply. @bolin12 I have tested the example on cuda backend using my Linux machine with RTX 2060. The FPS is typically ~40Fps. Would you mind providing the profiling info shown below?
> 
> To print these info, there are two lines to modify/add:
> 
> ```
> # Add kernel_profiler=True in the ti.init()
> ti.init(arch=ti.gpu, kernel_profiler=True)
> ...
> 
> # Add print profile info at the end of the program
> ti.print_kernel_profile_info()
> ```
> 
> Sample profiling info output on my machine:
> 
> ```
> [Taichi] version 0.8.3, llvm 10.0.0, commit 2680dabd, linux, python 3.8.10
> [Taichi] Starting on arch=cuda
> =========================================================================
> Kernel Profiler(count) @ CUDA on GeForce RTX 2060
> =========================================================================
> [      %     total   count |      min       avg       max   ] Kernel name
> -------------------------------------------------------------------------
> [ 96.65%   4.171 s    535x |    6.938     7.797    16.925 ms] render_c40_0_kernel_10_range_for
> [  2.14%   0.093 s      1x |   92.566    92.566    92.566 ms] runtime_initialize
> [  1.18%   0.051 s    535x |    0.055     0.095     1.206 ms] matrix_to_ext_arr_c20_0_kernel_11_range_for
> [  0.01%   0.000 s     37x |    0.004     0.011     0.013 ms] jit_evaluator_0_kernel_0_serial
> [  0.01%   0.000 s     21x |    0.004     0.011     0.013 ms] jit_evaluator_2_kernel_2_serial
> [  0.00%   0.000 s     14x |    0.003     0.009     0.014 ms] jit_evaluator_3_kernel_3_serial
> [  0.00%   0.000 s      6x |    0.004     0.019     0.085 ms] jit_evaluator_6_kernel_7_serial
> [  0.00%   0.000 s      3x |    0.012     0.037     0.085 ms] jit_evaluator_5_kernel_5_serial
> [  0.00%   0.000 s      1x |    0.108     0.108     0.108 ms] runtime_memory_allocate_aligned
> [  0.00%   0.000 s      1x |    0.059     0.059     0.059 ms] runtime_initialize_snodes
> [  0.00%   0.000 s      1x |    0.040     0.040     0.040 ms] fill_matrix_c28_0_kernel_8_range_for
> [  0.00%   0.000 s      2x |    0.012     0.012     0.012 ms] jit_evaluator_4_kernel_4_serial
> [  0.00%   0.000 s      2x |    0.006     0.009     0.012 ms] jit_evaluator_7_kernel_9_serial
> [  0.00%   0.000 s      1x |    0.013     0.013     0.013 ms] reset_c38_0_kernel_6_serial
> [  0.00%   0.000 s      1x |    0.013     0.013     0.013 ms] jit_evaluator_1_kernel_1_serial
> -------------------------------------------------------------------------
> [100.00%] Total execution time:   4.316 s   number of results: 15
> =========================================================================
> ```
thanks for replying.

to begin with:




[Taichi] version 0.8.3, llvm 10.0.0, commit 021af5d2, win, python 3.8.10
[Taichi] Starting on arch=cuda
=========================================================================
Kernel Profiler(count) @ CUDA
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
-------------------------------------------------------------------------
[ 62.40%   0.236 s      1x |  235.519   235.519   235.519 ms] render_c44_0_kernel_10_range_for
[ 36.79%   0.139 s      1x |  138.842   138.842   138.842 ms] runtime_initialize
[  0.25%   0.001 s      6x |    0.014     0.155     0.768 ms] jit_evaluator_6_kernel_7_serial
[  0.15%   0.001 s     37x |    0.014     0.016     0.035 ms] jit_evaluator_0_kernel_0_serial
[  0.13%   0.001 s      3x |    0.014     0.167     0.466 ms] jit_evaluator_5_kernel_5_serial
[  0.10%   0.000 s     21x |    0.013     0.018     0.037 ms] jit_evaluator_2_kernel_2_serial
[  0.07%   0.000 s     14x |    0.014     0.018     0.039 ms] jit_evaluator_3_kernel_3_serial
[  0.03%   0.000 s      1x |    0.109     0.109     0.109 ms] fill_matrix_c22_0_kernel_8_range_for
[  0.02%   0.000 s      1x |    0.058     0.058     0.058 ms] matrix_to_ext_arr_c14_0_kernel_11_range_for
[  0.01%   0.000 s      1x |    0.056     0.056     0.056 ms] runtime_memory_allocate_aligned
[  0.01%   0.000 s      1x |    0.050     0.050     0.050 ms] runtime_initialize_snodes
[  0.01%   0.000 s      2x |    0.014     0.024     0.034 ms] jit_evaluator_4_kernel_4_serial
[  0.01%   0.000 s      2x |    0.020     0.024     0.027 ms] jit_evaluator_7_kernel_9_serial
[  0.01%   0.000 s      1x |    0.028     0.028     0.028 ms] jit_evaluator_1_kernel_1_serial
[  0.01%   0.000 s      1x |    0.026     0.026     0.026 ms] reset_c42_0_kernel_6_serial
-------------------------------------------------------------------------
[100.00%] Total execution time:   0.377 s   number of results: 15



several seconds later:



[      %     total   count |      min       avg       max   ] Kernel name
-------------------------------------------------------------------------
[ 90.70%   3.652 s    224x |    6.138    16.302   235.519 ms] render_c44_0_kernel_10_range_for
[  5.78%   0.233 s    224x |    0.057     1.038     1.543 ms] matrix_to_ext_arr_c14_0_kernel_11_range_for
[  3.45%   0.139 s      1x |  138.842   138.842   138.842 ms] runtime_initialize
[  0.02%   0.001 s      6x |    0.014     0.155     0.768 ms] jit_evaluator_6_kernel_7_serial
[  0.01%   0.001 s     37x |    0.014     0.016     0.035 ms] jit_evaluator_0_kernel_0_serial
[  0.01%   0.001 s      3x |    0.014     0.167     0.466 ms] jit_evaluator_5_kernel_5_serial
[  0.01%   0.000 s     21x |    0.013     0.018     0.037 ms] jit_evaluator_2_kernel_2_serial
[  0.01%   0.000 s     14x |    0.014     0.018     0.039 ms] jit_evaluator_3_kernel_3_serial
[  0.00%   0.000 s      1x |    0.109     0.109     0.109 ms] fill_matrix_c22_0_kernel_8_range_for
[  0.00%   0.000 s      1x |    0.056     0.056     0.056 ms] runtime_memory_allocate_aligned
[  0.00%   0.000 s      1x |    0.050     0.050     0.050 ms] runtime_initialize_snodes
[  0.00%   0.000 s      2x |    0.014     0.024     0.034 ms] jit_evaluator_4_kernel_4_serial
[  0.00%   0.000 s      2x |    0.020     0.024     0.027 ms] jit_evaluator_7_kernel_9_serial
[  0.00%   0.000 s      1x |    0.028     0.028     0.028 ms] jit_evaluator_1_kernel_1_serial
[  0.00%   0.000 s      1x |    0.026     0.026     0.026 ms] reset_c42_0_kernel_6_serial
-------------------------------------------------------------------------
[100.00%] Total execution time:   4.026 s   number of results: 15
=========================================================================

Process finished with exit code -1

**Comment by erizmr** [comment]
It looks like the max runtime of kernel `render_c44_0_kernel_10_range_for` on Windows is extremely larger that on Linux.
cc: @yolo2themoon

**Comment by bolin12** [comment]
> It looks like the max runtime of kernel `render_c44_0_kernel_10_range_for` on Windows is extremely larger that on Linux. cc: @yolo2themoon

I switched to ubuntu20, and FPS reached 35+
