### ISSUE TITLE
[Windows] Failed to get physical memory size

### ISSUE THREAD

**Issue by kipa200** [taichi-dev/taichi#357]
run hello world in this site  
https://taichi.readthedocs.io/en/latest/hello.html
![image](https://user-images.githubusercontent.com/46548932/71964349-5bec6d80-3238-11ea-8bbf-7c0076370255.png)
# fractal.py

import taichi as ti

ti.cfg.arch = ti.cuda # Run on GPU by default

n = 320
pixels = ti.var(dt=ti.f32, shape=(n * 2, n))

@ti.func
def complex_sqr(z):
  return ti.Vector([z[0] * z[0] - z[1] * z[1], z[1] * z[0] * 2])

@ti.kernel
def paint(t: ti.f32):
  for i, j in pixels: # Parallized over all pixels
    c = ti.Vector([-0.8, ti.sin(t) * 0.2])
    z = ti.Vector([float(i) / n - 1, float(j) / n - 0.5]) * 2
    iterations = 0
    while z.norm() < 20 and iterations < 50:
      z = complex_sqr(z) + c
      iterations += 1
    pixels[i, j] = 1 - iterations * 0.02

gui = ti.GUI("Fractal", (n * 2, n))

for i in range(1000000):
  paint(i * 0.03)
  gui.set_image(pixels)
  gui.show()

**Comment by Moluth** [comment]
我也遇到这个错误了，没有解决

**Comment by yuanming-hu** [comment]
It seems that we should check the return value of at `GetPhysicallyInstalledSystemMemory`
https://github.com/taichi-dev/taichi/blob/master/taichi/unified_allocator.cpp#L87

This function sometimes fails. If it fails, we should use other approaches to get the amount of available memory, or simply allocate e.g. 4GB memory. 

If would be great if someone on Windows could help with this. Thanks!

**Comment by Psycho7** [comment]
I'm on my way to resolve this. It should be easy and quick, but I got stuck setting up the build env LOL.

**Comment by yuanming-hu** [comment]
Please check out https://github.com/taichi-dev/taichi/blob/master/appveyor.yml#L27 for building instructions on Windows :-)

**Comment by yuanming-hu** [comment]
Hi guys,

Chujie (@Psycho7) implemented an experimental fix for this, and v0.3.22 (which will be automatically released in ~30 minutes) includes this patch. Could you guys upgrade and let us know if the fix is effective? Thank you so much!

**Comment by yuanming-hu** [comment]
I believe this is systematically resolved after switching to the new memory allocator.
