### ISSUE TITLE
Support short-circuiting logical expressions

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#3572]
The following code snippet,
```python
import taichi as ti

ti.init(debug=True)

a = ti.field(ti.i32, shape=10)

@ti.kernel
def func(i: ti.i32):
    if i >= 0 and a[i] != 0:
        print(a[i])

func(-1)
```
will give a runtime error due to negative indices. This is because in Taichi, logical expressions are completely evaluated anyway. However, most programming languages are using short-circuiting logical expressions, so this behavior difference may cause confusion to newcomers.

I suggest that Taichi can support short-circuiting logical expressions. To avoid affecting performance of existing code, we can have an option in compiler configurations to decide whether to enable the new behavior.

**Comment by re-xyr** [comment]
To implement this in the frontend, I think we can translate `a and b` into the semantics of `if a then b else False` and `a or b` into the semantics of `if a then True else b`. We can use the logic in `IRBuilder.build_IfExp()`; not sure what the performance impact is going to be.

**Comment by strongoier** [comment]
The solution makes sense to me!

Regarding the performance impact, branches are considered harmful in GPU programming :-( Therefore, as the first step, I suggest adding an option like `ti.init(short_circuit=True)` to enable the new behavior. In the future, we may apply more optimizations to it (e.g. automatically switching back to the non-short-circuiting case if it is definitely safe and faster) to make it the default behavior.
