### ISSUE TITLE
[build] CMake on macOS can not find the right compiler

### ISSUE THREAD

**Issue by bobcao3** [taichi-dev/taichi#3578]
I'm on a M1 Macbook Air, macOS 11.6.1, I also installed the latest XCode from the AppStore.

This is my env:
```bash
LC_TERMINAL_VERSION=3.4.12
COLORFGBG=15;0
ITERM_PROFILE=Default
XPC_FLAGS=0x0
LANG=en_US.UTF-8
PWD=/Users/bobcao3/taichi
SHELL=/bin/zsh
__CFBundleIdentifier=com.googlecode.iterm2
SECURITYSESSIONID=186b8
TERM_PROGRAM_VERSION=3.4.12
TERM_PROGRAM=iTerm.app
PATH=/Users/bobcao3/local_bin/llvm-10.0.0-m1/bin:/opt/homebrew/opt/llvm@11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/bobcao3/miniforge3/bin:/Users/bobcao3/miniforge3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
LC_TERMINAL=iTerm2
COLORTERM=truecolor
COMMAND_MODE=unix2003
TERM=xterm-256color
HOME=/Users/bobcao3
TMPDIR=/var/folders/zd/dxxvfjsn56n46bmrm23_0k980000gn/T/
USER=bobcao3
XPC_SERVICE_NAME=0
LOGNAME=bobcao3
LaunchInstanceID=8FA7BF68-53B7-4EA7-8897-4EAB29E3FAB3
__CF_USER_TEXT_ENCODING=0x0:0:0
ITERM_SESSION_ID=w0t0p0:0A0E76C1-88CB-4B22-B619-CFED0BD626BB
SHLVL=1
OLDPWD=/Users/bobcao3
ZSH=/Users/bobcao3/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
CONDA_EXE=/Users/bobcao3/miniforge3/bin/conda
_CE_M=
_CE_CONDA=
CONDA_PYTHON_EXE=/Users/bobcao3/miniforge3/bin/python
CONDA_SHLVL=1
CONDA_PREFIX=/Users/bobcao3/miniforge3
CONDA_DEFAULT_ENV=base
CONDA_PROMPT_MODIFIER=(base)
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
HOMEBREW_SHELLENV_PREFIX=/opt/homebrew
MANPATH=/opt/homebrew/share/man::
INFOPATH=/opt/homebrew/share/info:
LLVM_DIR=/Users/bobcao3/local_bin/llvm-10.0.0-m1
TAICHI_CMAKE_ARGS=-DTI_WITH_VULKAN:BOOL=ON
_=/usr/bin/env
```

When I run `clang --version` directly from the shell, I get:
```bash
Homebrew clang version 11.1.0
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm@11/bin
```

This means I have the right PATH setup. However when I run cmake / `python setup.py develop`, I get this sequence:

```
---------- Running CMake prepare ----------------------------------------
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
...
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Taichi Version 0.8.6
       Commit 03a6da0716cf84ccc10568037314ef5c89d2cc42
Using /Users/bobcao3/miniforge3/bin/python as python executable.
Python 3.9.7
    version: 3.9
    include: /Users/bobcao3/miniforge3/include/python3.9
    library: /Users/bobcao3/miniforge3/lib/libpython3.9.dylib
    numpy include: /Users/bobcao3/miniforge3/lib/python3.9/site-packages/numpy/core/include
    pybind11 include: /Users/bobcao3/miniforge3/lib/python3.9/site-packages/pybind11/include;/Users/bobcao3/miniforge3/lib/python3.9/site-packages/pybind11/include
Using C++ compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
Clang compiler detected. Using std=c++17.
Building for processor arm64
...
C++ Flags:  -DTI_ISE_NONE -std=c++17 -fsized-deallocation -Wall  -DTI_ARCH_ARM -DTI_PASS_EXCEPTION_TO_PYTHON -DTI_INCLUDED -DTI_WITH_LLVM -DTI_WITH_METAL -DTI_WITH_VULKAN
Build type: Release
clang --version: 13.0.0
CMake Error at CMakeLists.txt:106 (message):

  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
  version: 13.0.0, required: <=12.  Condider passing
  -DCLANG_PATH=/path/to/clang to cmake to use a specific clang.
```

And if I force the build it will error out. If I manually set CLANG_EXECUTABLE to `clang`, I can build taichi correctly. It seems like on macOS, CMake's FindCXXCompiler.cmake automatically pick xcode's toolchain instead of using the one in the path.

**Comment by sjwsl** [comment]
> It seems like on macOS, CMake's FindCXXCompiler.cmake automatically pick xcode's toolchain instead of using the one in the path.

This is a known issue. Our CI machine has exactly the same issue before and it was fixed by setting the environment variable `CXX=clang` after #3379. Could you try it on your mac?

**Comment by bobcao3** [comment]
> > It seems like on macOS, CMake's FindCXXCompiler.cmake automatically pick xcode's toolchain instead of using the one in the path.
> 
> This is a known issue. Our CI machine had exactly the same issue before and it was fixed by setting the environment variable `CXX=clang` after #3379. Could you try it on your mac?

Yes it works. However I do see this problem being prevalent on macOS, maybe default CXX to clang-11 or clang?

**Comment by sjwsl** [comment]
I think the point is that the detection of the compiler in cmake doesn't consider `PATH`. It's actually the expected workflow to set `CXX` instead of `PATH` so we are not doing wrong IMHO.

https://stackoverflow.com/questions/45933732/how-to-specify-a-compiler-in-cmake

But it'd still be useful to explain this in the docs.

**Comment by bobcao3** [comment]
> I think the point is that the detection of the compiler in cmake doesn't consider `PATH`. It's actually the expected workflow to set `CXX` instead of `PATH` so we are not doing wrong IMHO.
> 
> https://stackoverflow.com/questions/45933732/how-to-specify-a-compiler-in-cmake
> 
> But it'd still be useful to explain this in the docs.

Actually, it does not compile. There's a compilation error. Seems like it's using a wrong linker or C compiler

**Comment by sjwsl** [comment]
Sorry, which compilation error are you talking about?

**Comment by bobcao3** [comment]
I have a super long error message, something about can not find things like `new` and `delete`. Basically everything is not found

**Comment by bobcao3** [comment]
So with `CXX=clang` it does not work, only works when setting `CLANG_EXECTUABLE` to clang

**Comment by strongoier** [comment]
> I have a super long error message, something about can not find things like `new` and `delete`. Basically everything is not found

What about using `clang++` instead of `clang`?

**Comment by sjwsl** [comment]
> > I have a super long error message, something about can not find things like `new` and `delete`. Basically everything is not found
> 
> What about using `clang++` instead of `clang`?

Ah right, I forgot that `clang` will miss C++ headers. `clang++` should work.
