### ISSUE TITLE
Add higher-level FAQ questions

### ISSUE THREAD

**Issue by DomHudson** [taichi-dev/taichi#358]
## Summary
Hi! I enjoyed the FAQ but  I did find it a bit amusing that the first question is "Can a user iterate over irregular topology instead of grids, such as tetrahedra meshes, line segment vertices?"
I think it would be nice to add some more basic FAQ questions such as:
- What is taichi?
- What problems does taichi solve?
- Why should I use taichi?
- How do I install taichi?
- How do I contribute to the taichi community?
etc

**Comment by yuanming-hu** [comment]
Hi @DomHudson, thanks for the constructive suggestions! I added a [contributor guide](https://taichi.readthedocs.io/en/latest/contributor_guide.html) (if you have any suggestions on this, please let me know). More high-level FAQs can be found in the documentation.

Ultimately I plan to move these low-level FAQ to the documentation as well.

Thanks.
