### ISSUE TITLE
Test examples in CI

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#3580]
Currently, we only run `ti example laplace` in CI, which cannot prevent us from breaking other examples in PRs. This leads to occasionally unstable releases of Taichi.

The main blocker is that most of the examples require GUI, and we need to add a CI mode for them to only verify correctness.

**Comment by strongoier** [comment]
I've found a way to test examples in CI without modifying the original examples too much. See #3721 as an example. 

Basically, we can:
- Wrap the original main procedure of an example (which often involves GUI) into `main()`;
- Write a test which imports the example and runs correctness checks.

However, it is not easy to verify correctness of most examples. For them, as a first step, I think we can run the calculation of a couple of frames by providing some random info (e.g. positions of the mouse) without involving GUI. This can at least ensure that the examples can successfully run, i.e., no compilation or runtime errors will occur.

If we want to fully make sure the results of the examples are also correct, for now I think it is inevitable to manually run them to check the results before a release. That said, adding the tests described above can still help reduce the chances of breaking the examples, which will certainly ease the burden before a release.

After skimming through all the examples, I think we can start with the following:
- *examples/algorithm/*
    - [x] laplace
    - [ ] marching_squares
    - [ ] mgpcg
    - [ ] mgpcg_advanced
    - [ ] print_offset
- *examples/autodiff/*
    - [ ] minimization
- *examples/features/sparse/*
    - [ ] explicit_activation
    - [ ] taichi_bitmasked
    - [ ] taichi_dynamic
    - [ ] taichi_sparse
    - [ ] tutorial
- *examples/rendering/*
    - [ ] cornell_box
    - [ ] rasterizer
    - [ ] sdf_renderer
    - [ ] simple_uv
    - [ ] taichi_logo
- *examples/simulation/*
    - [ ] ad_gravity
    - [ ] comet
    - [ ] fem99
    - [ ] fractal
    - [ ] game_of_life
    - [ ] initial_value_problem
    - [ ] mass_spring_game
    - [ ] mpm99
    - [ ] mpm_lagrangian_forces
    - [ ] nbody
    - [ ] odop_solar
    - [ ] pbf2d
    - [ ] physarum
    - [ ] vortex_rings
    - [ ] waterwave

Contributions are highly welcome!

**Comment by ReFantasy** [comment]
I would like to help "fractal"

**Comment by Zydiii** [comment]
I would like to help "minimization"

**Comment by nasnoisaac** [comment]
I would like to help with "taichi_logo"

**Comment by 0xzhang** [comment]
I would like to help with "game_of_life" and "nbody".

**Comment by LittleFall** [comment]
I would like to help with "print_offset".

**Comment by cyberkillor** [comment]
I would like to help with "ad_gravity"

**Comment by randosrandom** [comment]
Hi there,

First, I am marveled by your library and I am amazed that you managed to create this giant. I hope to help in my small, starting from this "welcome contribution".  

I would like begin with `examples/simulation/vortex_rings`. The original procedure is already mapped into `main()` but the test is missing. Do you still need it? Thank you!

**Comment by ailzhang** [comment]
Hey @randosrandom thank you for the kind words! We indeed have added all current examples into CI and it runs on every commit merged into master branch (thanks @feisuzhu !) so we should close this issue as completed. Examples covered can be found at in cast you're interestd! https://github.com/taichi-dev/taichi-release-tests/tree/master/truths/taichi 
You're more thank welcome to take a look at https://github.com/taichi-dev/taichi/labels/welcome%20contribution and we'd love to help if you're interested in those!
