### ISSUE TITLE
[Question] Proper formulation for matrix and vector artithmetic

### ISSUE THREAD

**Issue by jparr721** [taichi-dev/taichi#3582]
I have recently discovered Taichi and have been making an earnest attempt to replace it in my usual numpy workflow. However, something that stands out to me is the documentation around scalar fields and their ergonomics and intended uses. For example, let's take the following trivial situation with linear FEA:

```python
import taichi as ti
ti.init()

E = 210e6
v = 0.3

mul = (E / ((1 + v) * (1 - 2 * v)))

a = ti.Matrix([
                [1 - v, v, v, 0, 0, 0],
                [v, 1 - v, v, 0, 0, 0],
                [v, v, 1 - v, 0, 0, 0],
                [0, 0, 0, (1 - 2 * v) / 2, 0, 0],
                [0, 0, 0, 0, (1 - 2 * v) / 2, 0],
                [0, 0, 0, 0, 0, (1 - 2 * v) / 2],
            ]
        )


mul * a
```

To initialize an isotropic material matrix, you might do something like this. In numpy, this is trivial, and I just need to replace `ti.Matrix` with `np.array` for this to work. However, while this _does_ work with Taichi, it comes with the following warning:

```
[Taichi] Starting on arch=x64
UserWarning: Taichi matrices/vectors with 6x6 > 32 entries are not suggested. Matrices/vectors will be automatically unrolled at compile-time for performance. So the compilation time could be extremely long if the matrix size is too big. You may use a field to store a large matrix like this, e.g.:
    x = ti.field(ti.f32, (6, 6)).
 See https://docs.taichi.graphics/lang/articles/basic/field#matrix-size for more details.

  File "C:\tools\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\tools\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\tools\Anaconda3\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
    self.io_loop.start()
  File "C:\tools\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\tools\Anaconda3\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\tools\Anaconda3\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\tools\Anaconda3\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\tools\Anaconda3\lib\site-packages\tornado\ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
show more (open the raw output data in a text editor) ...

  File "C:\tools\Anaconda3\lib\site-packages\taichi\lang\matrix.py", line 456, in empty_copy
    return Matrix.empty(self.n, self.m)
  File "C:\tools\Anaconda3\lib\site-packages\taichi\lang\matrix.py", line 1106, in empty
    return cls([[None] * m for _ in range(n)], disable_local_tensor=True)
```

I understand the premise here, but what's confusing is the recommended alternative. It says to use a regular scalar field, but this is unable to be multiplied, so I can't actually do anything with this advice. 

My question is: How can I achieve similar ergonomics of the numpy container types in taichi? Things like matrix multiplication etc which seem like they should be intuitive are, unfortunately, eluding my understanding.

I have done my best to read code as well as scour google, but it's still not clear how these types are supposed to work together; looking up phrasing like "matrix multiplication" in the docs does not boast any useful information for this particular situation. 

Lastly, I did come across plenty of examples of what might constitute the "right way" to do this, for example from `examples/fem99.py` we have the following:

```python
@ti.kernel
def update_U():
    for i in range(NF):
        ia, ib, ic = f2v[i]
        a, b, c = pos[ia], pos[ib], pos[ic]
        V[i] = abs((a - c).cross(b - c))
        D_i = ti.Matrix.cols([a - c, b - c])
        F[i] = D_i @ B[i]
    for i in range(NF):
        F_i = F[i]
        log_J_i = ti.log(F_i.determinant())
        phi_i = mu / 2 * ((F_i.transpose() @ F_i).trace() - 2)
        phi_i -= mu * log_J_i
        phi_i += lam / 2 * log_J_i**2
        phi[i] = phi_i
        U[None] += V[i] * phi_i
```

Where F is a matrix field (which seems overkill if I just want a flat matrix, but, perhaps I am wrong about that?). It looks like the value of phi is just being unrolled and each element is being multiplied by the scalar value. Is the intention for the user to unroll their objects manually like this and use matrix fields to hold this data? If I just wanted a flat matrix to perform operations on, say, 3000x3000 in dimensions, what is the ideal way to work with this object? Do I need to implement my own matrix multiplication, etc for this to work?

Thank you!

**Comment by strongoier** [comment]
Hi @jparr721. Welcome to the Taichi community! We are currently on our way to improve the `ti.Matrix/Vector` implementations, and the goal is to make them as easy to use as `np.array`. If you would like to automatically parallelize a large number of tasks where matrix operations may be parts of a task, then feel free to ignore the warnings. If you would like to conduct a parallelized single matrix multiplication for huge matrices, then there is no already existing implementation in Taichi now, and you have to use `ti.field` to manually implement your stuff.

**Comment by jparr721** [comment]
That's about what I expected. I'm highly excited about Taichi and would love to help if I can. Are some of the new matrix/vector roadmaps available?

**Comment by strongoier** [comment]
Thanks for your interest in Taichi! We are making more and more RFCs publicly available now. Matrix/vector roadmaps will also come out soon :-)
