### ISSUE TITLE
how to `.place()` a field of `ti.type.struct`?

### ISSUE THREAD

**Issue by bcolloran** [taichi-dev/taichi#3593]
Hi there, I have a hopefully quick question about how to use advanced memory layouts for `ti.type.struct` objects.

I've been playing with the mpm examples, and I'm able to get my code working with AoS memory layout like the following:

``` python
grid_v = ti.Vector.field(2, dtype=float)
grid_v0 = ti.Vector.field(2, dtype=float)
grid_m = ti.field(dtype=float)

ti.root.dense(ti.ijk, (8, 16, 32)).dense(ti.ijk, (4, 4, 4)).place(
    grid_v, grid_v0, grid_m
)
```

But the call signatures and access patterns in the rest of my code quickly becomes cumbersome when I have to manage references to these three separate arrays. What I'd really love to be able to do is to just pass around a single object called `grid` and to access the elements as e.g. `grid[i].v`.

I thought I should be able to accomplish this with a field of `ti.types.struct` objects. I've tried several variations of code like this:

``` python
grid_type = ti.types.struct(
    v=ti.types.vector(2, float), v0=ti.types.vector(2, float), m=float
)

grid = ti.field(dtype=grid_type)

ti.root.dense(ti.ijk, (8, 16, 32)).dense(ti.ijk, (4, 4, 4)).place(grid)
```

...and this:

``` python
grid_type = ti.types.struct(
    v=ti.types.vector(2, float), v0=ti.types.vector(2, float), m=float
)
ti.root.dense(ti.ijk, (8, 16, 32)).dense(ti.ijk, (4, 4, 4)).place(grid_type)
```

...and several other things.

So far I've gotten errors for everything I've tried. Is this not possible currently, or did I just miss it in the docs? (I spent time looking for examples of how to do this and I could not find anything)

Really loving Taichi! Thank you for the incredible library! :-)

**Comment by strongoier** [comment]
According to https://docs.taichi.graphics/lang/articles/basic/field#struct-fields, there are two ways to declare struct fields:
```python
grid_type = ti.types.struct(
    v=ti.types.vector(2, float), v0=ti.types.vector(2, float), m=float
)
grid = grid_type.field()
```
or
```python
grid = ti.Struct.field({
    "v": ti.types.vector(2, float),
    "v0": ti.types.vector(2, float),
    "m": float
})
```
Then you can do
```python
ti.root.dense(ti.ijk, (8, 16, 32)).dense(ti.ijk, (4, 4, 4)).place(grid)
```

**Comment by bcolloran** [comment]
Ah fantastic, thanks very much @strongoier! :-)
