### ISSUE TITLE
Draw the arrow in GGUI

### ISSUE THREAD

**Issue by wangfeng70117** [taichi-dev/taichi#3595]
When debugging a 3D vector field, you need to draw arrows to test correctness, which I think is very useful feature.

**Comment by strongoier** [comment]
cc: @AmesingFlank

**Comment by AmesingFlank** [comment]
Hmm, I think as a feature it is too specific to be included in the core GGUI API. I suggest generating meshes that represent arrows for this type of debugging.

Also I doubt how useful would arrows be for debugging. Imagine if you have a 100x100x100 discrete velocity field (which is not a lot). Thats would already be 10^6 arrows stuffed inside one image. I don't think this image would be very helpful lol.

**Comment by bobcao3** [comment]
I think usually people just draw lines with different color on each end. (e.g. white to red, the red tip points to the vector direction) You can write a simple helper function of your own to invoke the line drawing routine.
