### ISSUE TITLE
Internal research project: ti.Mesh

### ISSUE THREAD

**Issue by g1n0st** [taichi-dev/taichi#3608]
We are developing an internal research project ti.Mesh (#3567). It offers first-class support for triangular/tetrahedral meshes and allows efficient computation on these irregular data structures. Now it's an early-stage prototype in progress, so we keep it undiscussed. We will soon release more details and welcome contributions from the community. : )

**Comment by yang-si-hang** [comment]
I want to generate a Tetrahedral Mesh from vertices.
I don't know how to use the Function "taichi.TetMesh()". Have you accomplished this Function?
Thanks!

**Comment by g1n0st** [comment]
@yang-si-hang  Thank you for being so interested in our work! The work about `ti.Mesh` has recently been accepted by SIGGRAPH Asia 2022, and we are refactoring APIs and example cases. We will release complete examples at https://github.com/taichi-dev/meshtaichi and provide documentation in the following days.

**Comment by yang-si-hang** [comment]
> @yang-si-hang Thank you for being so interested in our work! The work about `ti.Mesh` has recently been accepted by SIGGRAPH Asia 2022, and we are refactoring APIs and example cases. We will release complete examples at https://github.com/taichi-dev/meshtaichi and provide documentation in the following days.

Thanks for your reply! I look forward to reading your paper.

**Comment by g1n0st** [comment]
Since the internal research project ti.Mesh will make it public soon, so I will close this issue. New problems related to MeshTaichi could open with a new thread or move to https://github.com/taichi-dev/meshtaichi. Any discussions and contributions from the community are welcomed!
