### ISSUE TITLE
[RFC] Add a JIT compilation optimization level

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#3611]
**Concisely describe the proposed feature**

Right now we've observed very slow JIT compilation speed on some large Taichi programs. Specifically, two of the most time-consuming optimizations are:

* CFG
* Whole kernel CSE

A JIT optimization level config (like C++'s `-O`) can help decide which set of IR opts to run. This could be very useful when Taichi users are iterating their programs and do not care too much about the codegen quality/runtime performance.

**Describe the solution you'd like (if any)**

```py
ti.init(opt_level={0, 1, 2, 3...})
```

Then `opt_level` will be passed down into the IR pass infrastructure and decide the optimizations to run

**Additional comments**

**Comment by strongoier** [comment]
What is the relationship between this issue and #2658?

**Comment by k-ye** [comment]
Huh, I forgot about that. The PR wasn't associated with any issue so I created this one.
