### ISSUE TITLE
Print the related source code and its position in the file when an error occurs

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#3612]
**Concisely describe the proposed feature**
I would like to add the feature that prints the related source code and its position in the file when an error occurs when building the AST.

**Describe the solution you'd like (if any)**
Keep a copy of the source code of the taichi kernel/function inside the context and utilize the position information in the AST node to find out the source code related to the node. When an exception is thrown, we can catch it in the transformer and add the extra information in the error message and then throw it.

**Comment by sjwsl** [comment]
Definitely need this!
