### ISSUE TITLE
Question on Taichi (SIGGRAPH ASIA 2019) paper’s Fig. 6-(c)

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#362]
Sorry I’m abusing Github for paper questions, but I’m trying to understand the hierarchical data structure.

In the original Taichi 2019 paper, Fig. 6-(c)’s example, the hierarchy definition is

```cpp
// Ignored |child2| and decorators for simplicity
root
  .hash(ij, 8)
  .dense(ij, {16, 8})
  .dense(ij, {4, 8})
  .place(grid_vx, grid_vy);
```

So the combined dimension is `512x512`, with the top-level hash table being `8x8`. Then it seems like each element in this hash table should cover a range of `64x64`, yet the range in Fig 6-(c) is `256x256` (e.g. `i  = [256, 512), j = [0, 256)` for the highlighted range).  Did I misunderstand something here?

Thanks!

**Comment by yuanming-hu** [comment]
Thanks so much for letting me know! You are right, there's a typo: the highest level block coverage is `512x512`. I'm fixing that now. Thanks again for pointing this out!

**Comment by k-ye** [comment]
Sweet, thank you for the confirmation!
