### ISSUE TITLE
benchmarks mislabeled in fill_dense.py

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#363]
Hi Yuanming, 
Almost all of your benchmarks are mislabeled in fill_dense.py. The struct_for named kernels have range for loops in them and visa versa.

**Comment by yuanming-hu** [comment]
OMG, what a mistake. Thanks for pointing this out!

**Comment by yuanming-hu** [comment]
Thank you so much @KLozes! Your comment has saved me a lot of time.

**Comment by KLozes** [comment]
No problem! I figured it could give you a lot of trouble it it went unnoticed.
