### ISSUE TITLE
[IR] Building CHI IR examples 

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#3630]
I'm trying to lean to use CHI IR builder, but I'm having some troubles building `chi_examples`. From what I can tell

* The include paths aren't set up correctly. This is likely because we have added quite a few dependencies.
* The build args aren't set-up correctly.  The cmake file seem to be linux-specific, and on windows, I'm getting things like "ERROR: C++ 14 required". I'm trying to fix it but I could use some help. @BillXu2000

**Comment by BillXu2000** [comment]
Dependency: #3636

**Comment by AmesingFlank** [comment]
Instead of fixing this CMakeList, I suggest we move it under `cmake` and add a `TI_BUILD_CHI_EXAMPLE` to optionally enable it (similar to how taichi cpp tests are handled). This way, we can share all the build configurations of the main taichi library.

**Comment by BillXu2000** [comment]
`chi_examples` was supposed to be an example to show how to independently compile and run taichi kernels in cpp with an exported taichi core shared library, decoupled from cmake settings in Taichi repository. Though it seems difficult now to maintain its availability while Taichi is developing so fast. I am considering whether deleting this `chi_examples` or not after fix bugs for current Taichi version.

By the way, [this test](https://github.com/taichi-dev/taichi/blob/master/tests/cpp/ir/ir_builder_test.cpp#L87-L119) might be useful  as an example to construct and run kernels in cpp.

**Comment by AmesingFlank** [comment]
It would indeed be more ideal if the example can be built separately. But if this is difficult, then having it coupled with the main taichi library is still better then deleting it completely... Even leaving it as its current state would be better than having it deleted i would say, because people can still use it as a reference.

**Comment by k-ye** [comment]
Let's just add this to CI, which is the best way to prevent regression :-)
