### ISSUE TITLE
Support frontend type check for If/While statements

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#3633]
**Concisely describe the proposed feature**
We have the following test: https://github.com/taichi-dev/taichi/blob/21d9048d8ce03d0c8257775f33d360656dd5f949/tests/python/test_type_check.py#L30-L41, which was commented in #3441. This was because `IfExp` was expanded to regular `If` statements in our new AST builder in #3299, and we didn't have type checks for the conditions of `If/While` statements.

To make the type error messages for `If/While` statements as easy to read as normal expressions, and to uncomment the above test, we'd better support frontend type check for `If/While` statements.

**Comment by re-xyr** [comment]
Do we also need to typecheck other statements such as `FrontendSNodeOpStmt` or `FrontendForStmt`?

**Comment by re-xyr** [comment]
I found that Chi IR also has a typechecking pass in `transforms/type_check.cpp`. Does this mean after adding typechecking for frontend IR, we'll have two sets of typechecking mechanisms? This looks kind of redundant.

**Comment by strongoier** [comment]
Currently `transforms/type_check.cpp` does the following:
1. Check type errors;
2. Add implicit casting;
3. Fix some wrong types set by other passes.

However, we need to clearly separate user errors from compiler internal errors. Otherwise, neither users nor compiler developers can easily diagnose problems they meet.

Currently we are moving 1 to the frontend, and we just align the behavior with `transforms/type_check.cpp` for now. For example, `begin/end` of `FrontendForStmt` will be automatically cast, so we don't force them to be integers.

I believe in the next step we also need to move 2 to the frontend. And for 3, we need to fix our compiler implementation and finally turn this pass into an optional pure verification pass.
