### ISSUE TITLE
using Taichi natively in MSVC 2017

### ISSUE THREAD

**Issue by amir90** [taichi-dev/taichi#365]
Hello, I am looking in to using Taichi to speed up voxel simulations in MSVC 2017.

Since the Documentation does not say so explicitly, and I didn't see an include folder - Is it possible to use the current build of Taichi in c++ natively (without calling from python)?

**Comment by yuanming-hu** [comment]
Hi @amir90 , currently Python is the only interface, but we plan to support C++ API as well. However, the C++ support will not happen very soon since we have a lot of more urgent development to do now.
