### ISSUE TITLE
GGUI Rendering question

### ISSUE THREAD

**Issue by GrapixLeGrand** [taichi-dev/taichi#3656]
Hello,

I can't find in the doc what is the rendering technique of GGUI. Is this reasterized? Moreover, is there more doc than this [page](https://docs.taichi.graphics/lang/articles/misc/ggui)? I was wondering what was happening under the hood because I'm aiming to get real time performances (or the most performance that I can) and by looking at the particles (3D geometry), they look like perfect spheres and my framerate would vary if I zoom toward them (they occupy a larger part of my screen). Are they raymarched?

Best,
Quentin

**Comment by ailzhang** [comment]
cc: @AmesingFlank ;)

**Comment by AmesingFlank** [comment]
Hi. Yes, GGUI uses a rasterization-based render pipeline written in Vulkan. There's no ray-marching, though I wish there is. The page that you mentioned is all the doc we have, but if you want to know more about, I suggest
1. Looking at the examples `python/taichi/examples/ggui_examples`
2. Read the source code.  The C++ code for ggui are located in `taichi/ui` and `taichi/backend/vulkan`, and the python side in `python/ui`. You can also find the shaders in `python/shaders`.
3. Ask me anything you wanna know via github issues, I'm usually quite responsive. If you want, we can also add you to a Slack channel we created for the github community.

**Comment by AmesingFlank** [comment]
Regarding particle rendering, it is done by first emitting `Point` primitives in the vertex shader, which are essentially squares with controllable sizes. Then, in the fragment shader, we `discard` the pixels in each square that's outside of circle inscribed in the square. The reason that the framerate drops when you zoom is because of something called "overdraw".

**Comment by GrapixLeGrand** [comment]
Hello,

Thanks a lot for the answer and sorry for the late reply (busy studies). I'll have a look a the sources.
Best,
Quentin

**Comment by ailzhang** [comment]
Cool we'll close this issue for now, please feel free to reopen if you have any followup questions!
