### ISSUE TITLE
A new commit in a PR will not cancel previous CI

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#3663]
Example:
https://github.com/taichi-dev/taichi/actions/runs/1524659906
https://github.com/taichi-dev/taichi/actions/runs/1524673049
https://github.com/taichi-dev/taichi/actions/runs/1524685711
are all running at the same time.

**Comment by strongoier** [comment]
cc: @frostming

**Comment by frostming** [comment]
It is missing the authentication info, I've fixed in the linked PR.
