### ISSUE TITLE
Not able to reproduce sparse convolution performance

### ISSUE THREAD

**Issue by aaroey** [taichi-dev/taichi#367]
**Describe the bug**
I was not able to reproduce the numbers mentioned in the Taichi paper section `6.4 3D Convolutional Neural Networks`.

**Screenshots**
```
$ pip install taichi-nightly-cuda-10-0    
$ ti cnn opt=[t/f] cache_l1=[t/f]
[Release mode]
[T 01/09/20 15:17:10.485] [logging.cpp:Logger@68] Taichi core started. Thread ID = 134274
[Taichi version 0.3.20, cuda 10.0, commit 1c85d8e1]
...                                                    
[E 01/09/20 15:17:10.496] [task.h:create@29] Implementation [task::cnn] not found!
```

**To Reproduce**
The commands to reproduce are listed above. I also realized that sparse computation is [not available](https://taichi.readthedocs.io/en/latest/sparse.html#sparse) at the moment at head, so I also tried to install the legacy version by following [this doc](https://taichi.readthedocs.io/en/latest/installation.html), but got similar problem.

**Comment by yuanming-hu** [comment]
Hi @aaroey 

We are migrating to a new LLVM backend, and the performance numbers in the SIGGRAPH Asia paper are obtained using the legacy clang/nvcc backends. We have removed the legacy backends to make way for LLVM. To reproduce those numbers, please checkout commit #dc162e11 and follow https://github.com/taichi-dev/taichi/tree/dc162e11988f3b1053c36826f82704b82fce9d0c/lang#installation to install (You don't have to checkout llvm since you only need the legacy backends). The old version is kind of troublesome to build, which is one of the motivations for the LLVM migration.

I don't plan to improve the installation experience of the legacy version, since the LLVM version will soon be optimized and ideally have a performance matching the legacy backends. However, for reproducibility, I understand sometimes it is necessary to build the legacy version. I'm happy to help you deploy the old version. If you run into any compilation issues, please feel free to let me know.

Best,
Yuanming

**Comment by aaroey** [comment]
Hi @yuanming-hu,

Thanks for the quick response. I tried that but still not able to get things working. What I did are:

```
python3 -m pip install astpretty astor pytest opencv-python pybind11==2.2.4
wget https://raw.githubusercontent.com/yuanming-hu/taichi/legacy/install.py
python3 install.py
ti install https://github.com/yuanming-hu/taichi_lang
source ~/.bashrc
export PYTHONPATH=$TAICHI_REPO_DIR/projects/taichi_lang/python:$PYTHONPATH
ti test  # The tests passed.
```

However when I tried `ti cnn opt=[t/f] cache_l1=[t/f]` I still get the same `cnn not found` error.

I realized that install.py will check out the `legacy` branch, so I tried to manually checkout #dc162e11 and run `python3 install.py` again but then I got:

```
Warning: module [lang_core] loading failed: /home/taichi/build/libtaichi_lang_core.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):          
  File "<string>", line 1, in <module>      
  File "/home/taichi/python/taichi/__init__.py", line 13, in <module>
    from taichi.lang import *               
  File "/home/taichi/python/taichi/lang/__init__.py", line 1, in <module>
    from .impl import *                                                                               
  File "/home/taichi/python/taichi/lang/impl.py", line 2, in <module>
    from .core import taichi_lang_core                                                                
  File "/home/taichi/python/taichi/lang/core.py", line 12, in <module>
    import taichi_lang_core                                                                           
ImportError: No module named 'taichi_lang_core'                                                       
  Error: installation failed. 
```

I tried the installation script from head and [dc162e11](https://raw.githubusercontent.com/taichi-dev/taichi/dc162e11988f3b1053c36826f82704b82fce9d0c/install.py), the outcome is the same.

I understand the difficulty of making a legacy installation work, so I'm happy to wait. Do you have an estimation on when it'll be ready again with the new backend?

Thanks.

**Comment by yuanming-hu** [comment]
I guess it's easier if we can wait until the end of Jan. I'm planning to finalize LLVM performance tuning by that time. I'll also translate the old cnn script (https://github.com/taichi-dev/taichi/blob/dc162e11988f3b1053c36826f82704b82fce9d0c/lang/cpp_examples/cnn.cpp) into the new python frontend.

**Comment by aaroey** [comment]
@yuanming-hu any update on this?

**Comment by yuanming-hu** [comment]
Still finalizing the LLVM performance tuning. The memory allocator is being redesigned and we are very close.

**Comment by yuanming-hu** [comment]
I still need a few days to finalize performance tuning. In the past a few days I prioritized redesigning the memory allocator since the old benchmarks rely on an efficient memory allocator.

**Comment by aaroey** [comment]
Thanks for the update. Looking forward to the new backend!

**Comment by yuanming-hu** [comment]
Update: I fixed quite a few performance bugs in the new LLVM backend (https://github.com/taichi-dev/taichi/issues/333). I will set up the sparse convolution and MLS-MPM benchmarks next week. I think we are very close. Thank you for your patience!

**Comment by aaroey** [comment]
Thanks for the update! Will try it out once its ready.

**Comment by ykdu** [comment]
Any update?

**Comment by bobcao3** [comment]
closed for now

**Comment by YouJiacheng** [comment]
Any update? Is there a sparse conv example in the master branch?
