### ISSUE TITLE
[examples] Rasterizer & cornell_box broke

### ISSUE THREAD

**Issue by bobcao3** [taichi-dev/taichi#3675]
For cornell_box.py
```
  File "/home/bobcao3/taichi/python/taichi/lang/ast/ast_transformer.py", line 869, in build_If
    node.test = build_stmt(ctx, node.test)
  File "/home/bobcao3/taichi/python/taichi/lang/ast/ast_transformer_utils.py", line 26, in __call__
    raise e
  File "/home/bobcao3/taichi/python/taichi/lang/ast/ast_transformer_utils.py", line 23, in __call__
    return method(ctx, node)
  File "/home/bobcao3/taichi/python/taichi/lang/ast/ast_transformer.py", line 277, in build_Call
    node.args = build_stmts(ctx, node.args)
  File "/home/bobcao3/taichi/python/taichi/lang/ast/ast_transformer.py", line 1017, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/bobcao3/taichi/python/taichi/lang/ast/ast_transformer_utils.py", line 32, in __call__
    raise TaichiCompilationError(msg)
taichi.lang.exception.TaichiCompilationError: On line 61 of file "/home/bobcao3/taichi/python/taichi/lang/meta.py":
        if ti.static(img.dtype in [ti.f32, ti.f64]):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TaichiSyntaxError: "In" is not supported in Taichi kernels.
```

For rasterizer:
```
Traceback (most recent call last):
  File "python/taichi/examples/rendering/rasterizer.py", line 23, in <module>
    class TriangleRasterizer:
  File "python/taichi/examples/rendering/rasterizer.py", line 69, in TriangleRasterizer
    def tile_culling(self):
  File "/home/bobcao3/taichi/python/taichi/lang/kernel_impl.py", line 736, in kernel
    return _kernel_impl(fn, level_of_class_stackframe=3)
  File "/home/bobcao3/taichi/python/taichi/lang/kernel_impl.py", line 668, in _kernel_impl
    primal = Kernel(_func, is_grad=False, _classkernel=is_classkernel)
  File "/home/bobcao3/taichi/python/taichi/lang/kernel_impl.py", line 347, in __init__
    self.extract_arguments()
  File "/home/bobcao3/taichi/python/taichi/lang/kernel_impl.py", line 399, in extract_arguments
    raise KernelDefError(
taichi.lang.kernel_impl.KernelDefError: Taichi kernels parameters must be type annotated
```

**Comment by strongoier** [comment]
I will take a look at the error of `cornell_box.py`. However, I cannot reproduce the error of `rasterizer.py`. Would you pull master and try again?

**Comment by strongoier** [comment]
The problem of `cornell_box.py` is simply as the error message states. However, whether to support this operator, or modify this example, requires careful discussion.

One purpose of the AST refactoring is to standardize which subset of Python Taichi should support. Allowing things is easy, but IMO it is much more important to have a clear specification of what users can/cannot do. As the `in` operator can be evaluated nowhere but on specific Python objects, should we just ban it? Keeping this operator will easily give users a wrong impression that Taichi supports the `in` operator. @k-ye @ailzhang @lin-hitonami WDYT?

**Comment by k-ye** [comment]
> it is much more important to have a clear specification of what users can/cannot do.

+1. In general, I don't think `in` is of significant value for Taichi's programs. That said, I thought that expressions inside `ti.static()` are evaluated at Python?

**Comment by lin-hitonami** [comment]
ti.static now is evaluated at compile time (in the ast transformer) but it is still processed by the transformer. Maybe we can enable more functionalities inside the ti.static scope?

**Comment by strongoier** [comment]
> expressions inside ti.static() are evaluated at Python?

Just as @lin-hitonami said, all evaluations are controlled by the transformer now. So we can completely determine what to support.

> one of the main functions of ti.static is allowing users to evaluate python objects inside taichi kernels.

Currently `ti.static` is mainly for the so-called meta-programming (https://docs.taichi.graphics/lang/articles/advanced/meta). Although all features are controlled by the transformer, Python object evaluation is enabled everywhere (e.g. a simplest expression like `1 + 2`, or subscripting a Python list `a[3]`). It's OK because it's pretty hard to enforce users to use `ti.static` for each Python object evaluation, which will make Taichi kernels unreadable. Therefore IMHO we shouldn't let `ti.static` carry the semantics of Python object evaluation.

**Comment by ailzhang** [comment]
Totally agree that we should be clear on what want to support. If we're going to ban `in`, shall we update the error message suggesting adding a few words about how to rewrite the user program?

**Comment by k-ye** [comment]
I see. Supporting bool + all sorts of basic arithmetics could be a good start? (I wonder what happens if we mix Python scope and Taichi scope concepts, e.g. `ti.static(ti.Vector([0, 1]).normalized())`)
