### ISSUE TITLE
AttributeError: module 'taichi' has no attribute 'cuda'

### ISSUE THREAD

**Issue by WSFeng** [taichi-dev/taichi#368]
when i run 'python3 fractal.py'
I got the error message like follow:

> [T 01/10/20 15:38:18.243] [logging.cpp:Logger@67] Taichi core started. Thread ID = 34659
> Traceback (most recent call last):
> File "fractal.py", line 7, in
> ti.cfg.arch = ti.cuda
> AttributeError: module 'taichi' has no attribute 'cuda'

--
eg: i saw the web 2020-01-10 , i think it's Newest

**Comment by yuanming-hu** [comment]
Hi @WSFeng ,

Did you install taichi via pip? It seems to me that you are using legacy Taichi.

**Comment by WSFeng** [comment]
i Had installed pip, my MacOS is 10.15.2
