### ISSUE TITLE
Move testing C++ from unix_docker_build to unix_docker_test

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#3682]
As @BillXu2000 found out, it's a bit confusing that we currently run C++ tests in the build stage. https://github.com/taichi-dev/taichi/pull/3680/files#diff-038b990ab4476a55a74bb7ed8ed7e10231567d52310b620b5a2884d1faa40dacL48 

And we didn't run C++ tests in tests stage since the taichi_cpp_tests binary was not copied over. I gave a quick try fixing this in #3680 but hit some docker related errors. 

I'll leave it here just in case anyone has bandwidth to improve it, as this issue isn't blocking right now.

**Comment by knight42** [comment]
@ailzhang Hi, I would like to help!

**Comment by ailzhang** [comment]
Hey @knight42 , go for it! Thanks a ton!!
