### ISSUE TITLE
taichi failed to run test on Windows with MSVC

### ISSUE THREAD

**Issue by YangYang129** [taichi-dev/taichi#3683]
taichi failed to run test on Windows with MSVC. It can reproduces on version https://github.com/taichi-dev/taichi/commit/3951c087438a697fc17a14bf603e61d69a2da0cd. Could you please help look at this issue? Thank you very much

**Environment**
Compiler version: VS2019 (16.11.5)
Operating system: Windows server 2019

**Reproduce steps:**
1. git clone https://github.com/taichi-dev/taichi c:/
2. cd taichi 
3. git submodule update --init --recursive
4. mkdir bin & cd bin
5. C:\Python39\python.exe -m pip install --upgrade pip
6. set PATH=C:\Users\CPPTESTLOCAL\AppData\Roaming\Python\Python39\Scripts;%PATH%
7. pip3 install --user gitpython
8. pip3 install --user pybind11
9. set PATH={taichi-llvm-10.0.0-msvc2019 dir}\bin;%PATH%
10. set PATH={clang-10.0.0-win dir}\bin;%PATH%
11. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DTI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -Dgtest_force_shared_crt=TRUE ..
12. msbuild /p:Configuration=Release;Platform=x64 taichi.sln /t:Rebuild /m
13. cd ..
14. python -m pip install -r requirements_dev.txt
15. python -m pip install -r requirements_test.txt
16. python -c "import taichi"
17. python -m pip install taichi
18. python tests/run_tests.py

**Error log:**
[test.log](https://github.com/taichi-dev/taichi/files/7640862/test.log)

**Error info:**
[W 12/01/21 23:05:00.730 3312] [run_tests.py:_test_cpp@24] C++ tests are skipped due to missing taichi_cpp_tests in C:\taichi\tests\../build
[Taichi] version 0.8.6, llvm 10.0.0, commit d5f18ffd, win, python 3.9.7
Namespace(files=[], cpp=True, show_output=False, verbose=False, rerun=None, keys=None, marks=None, failed_first=None, fail_fast=None, coverage=None, cov_append=None, threads=None, arch=None, exclusive=False)
Running C++ tests...

Running Python tests...

Starting 8 testing thread(s)...
============================= test session starts =============================
platform win32 -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: C:\taichi
.................................
ERROR tests/python/test_numpy.py - AttributeError: module 'taichi' has no att...
ERROR tests/python/test_nested_kernel_error.py - AttributeError: module 'taic...
ERROR tests/python/test_numpy.py - AttributeError: module 'taichi' has no att...
ERROR tests/python/test_return.py - AttributeError: module 'taichi' has no at...
ERROR tests/python/test_runtime.py - AttributeError: module 'taichi' has no a...
ERROR tests/python/test_return.py - AttributeError: module 'taichi' has no at...
ERROR tests/python/test_runtime.py - AttributeError: module 'taichi' has no a...
ERROR tests/python/test_syntax_errors.py - AttributeError: module 'taichi' ha...
ERROR tests/python/test_tuple_assign.py - AttributeError: module 'taichi' has...
ERROR tests/python/test_syntax_errors.py - AttributeError: module 'taichi' ha...
ERROR tests/python/test_tuple_assign.py - AttributeError: module 'taichi' has...
ERROR tests/python/test_assert.py - AttributeError: module 'taichi' has no at...
ERROR tests/python/test_for_group_mismatch.py - AttributeError: module 'taich...
ERROR tests/python/test_nested_kernel_error.py - AttributeError: module 'taic...
ERROR tests/python/test_numpy.py - AttributeError: module 'taichi' has no att...
ERROR tests/python/test_return.py - AttributeError: module 'taichi' has no at...
ERROR tests/python/test_runtime.py - AttributeError: module 'taichi' has no a...
ERROR tests/python/test_syntax_errors.py - AttributeError: module 'taichi' ha...
ERROR tests/python/test_tuple_assign.py - AttributeError: module 'taichi' has...
= 32 failed, 1102 passed, 6 skipped, 53 warnings, 104 errors in 246.37s (0:04:06) =

**Comment by ailzhang** [comment]
@YangYang129 would you mind adding more information about the error message? They're truncated in the description above :P

**Comment by k-ye** [comment]
Actually there's a log file attached :-)

```
=================================== ERRORS ====================================
________________ ERROR collecting tests/python/test_assert.py _________________
tests\python\test_assert.py:94: in <module>
    ???
C:\Python39\lib\site-packages\taichi\__init__.py:34: in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
E   AttributeError: module 'taichi' has no attribute 'TaichiCompilationError'
________________ ERROR collecting tests/python/test_assert.py _________________
tests\python\test_assert.py:94: in <module>
    ???
C:\Python39\lib\site-packages\taichi\__init__.py:34: in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
E   AttributeError: module 'taichi' has no attribute 'TaichiCompilationError'
__________ ERROR collecting tests/python/test_for_group_mismatch.py ___________
tests\python\test_for_group_mismatch.py:5: in <module>
    @ti.must_throw(ti.TaichiCompilationError)
C:\Python39\lib\site-packages\taichi\__init__.py:34: in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
E   AttributeError: module 'taichi' has no attribute 'TaichiCompilationError'
__________ ERROR collecting tests/python/test_for_group_mismatch.py ___________
tests\python\test_for_group_mismatch.py:5: in <module>
    @ti.must_throw(ti.TaichiCompilationError)
C:\Python39\lib\site-packages\taichi\__init__.py:34: in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
E   AttributeError: module 'taichi' has no attribute 'TaichiCompilationError'
```

Could be due to the frontend refactor? @lin-hitonami @strongoier

**Comment by lin-hitonami** [comment]
>  [Taichi] version 0.8.6, llvm 10.0.0, commit d5f18ff, win, python 3.9.7
d5f18ff is committed 10 days ago, have you installed taichi before? It seems that python is using the old taichi instead the one you just built.

**Comment by YangYang129** [comment]
@lin-hitonami I  cloned the latest source code and ran command "python -m pip install taichi", I find default installed v0.8.6 https://github.com/taichi-dev/taichi/releases/tag/v0.8.6, commit of this version is older d5f18ff . How can I install taichi of the one I built. Could you please help me look at this question? Thank you very much

**Comment by qiao-bo** [comment]
@YangYang129, can you uninstall the taichi from pip first? by `pip uninstall taichi`. You need either `pip install taichi` OR build from source. Either is fine, you don't need both. If you want to build from source, follow the build Taichi from source (Windows) part of [this doc](https://docs.taichi.graphics/lang/articles/contribution/dev_install). We provided some scripts that should automate the process for you. Let us know.

**Comment by lin-hitonami** [comment]
Maybe uninstalling the old taichi by `python -m pip uninstall taichi` and following the instructions on https://docs.taichi.graphics/lang/articles/contribution/dev_install will help. Also, please notice that this is for taichi developers to install taichi, and if you use it in production, you can simply just `python -m pip install taichi` without cloning the repo. Also, the tests are considered not needed for end users, so it is not included in the production release.

**Comment by YangYang129** [comment]
@qiao-bo @lin-hitonami I create a machine, taichi still failed to run test on Windows with MSVC. It can reproduces on version 3951c08. 
**Reproduce steps:**
1. git clone https://github.com/taichi-dev/taichi F:\gitP\taichi-dev
2. cd F:\gitP\taichi-dev\taichi
3. git reset --hard 3951c087438a697fc17a14bf603e61d69a2da0cd
4. git submodule update --init --recursive
5. mkdir bin & cd bin
6. pip3 install --user gitpython
7. pip3 install --user pybind11
8. set PATH=${taichi-llvm-10.0.0-msvc2019 dir}\bin;%PATH%
9. set PATH=${clang-10.0.0-win dir}\bin;%PATH%
10. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DTI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -Dgtest_force_shared_crt=TRUE ..
11. msbuild /p:Configuration=Release;Platform=x64 taichi.sln /t:Rebuild /m
12. cd ..
13. python -m pip install -r requirements_dev.txt
14. python -m pip install -r requirements_test.txt
15. python -c "import taichi"
16. python -m pip install -v .
17. python tests/run_tests.py

**Error log:**
[taichi_test.log](https://github.com/taichi-dev/taichi/files/7660042/taichi_test.log)


**Error info:**
[W 12/06/21 02:07:31.511 5096] [run_tests.py:_test_cpp@24] C++ tests are skipped due to missing taichi_cpp_tests in F:\gitP\taichi-dev\taichi\tests\../build
[Taichi] version 0.8.7, llvm 10.0.0, commit 3951c087, win, python 3.9.7
Namespace(files=[], cpp=True, show_output=False, verbose=False, rerun=None, keys=None, marks=None, failed_first=None, fail_fast=None, coverage=None, cov_append=None, threads=None, arch=None, exclusive=False)
Running C++ tests...

Running Python tests...

Starting 8 testing thread(s)...
============================= test session starts =============================
platform win32 -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: F:\gitP\taichi-dev\taichi
....
FAILED tests/python/test_types.py::test_type_field64[dt2] - urllib.error.URLE...
FAILED tests/python/test_types.py::test_overflow[dt1-8] - urllib.error.URLErr...
FAILED tests/python/test_types.py::test_overflow[dt0-8] - urllib.error.URLErr...
FAILED tests/python/test_types.py::test_overflow[dt3-16] - urllib.error.URLEr...
FAILED tests/python/test_types.py::test_overflow[dt2-16] - urllib.error.URLEr...
FAILED tests/python/test_types.py::test_overflow[dt4-32] - urllib.error.URLEr...
FAILED tests/python/test_types.py::test_overflow[dt5-32] - urllib.error.URLEr...
FAILED tests/python/test_types.py::test_overflow64[dt0-64] - urllib.error.URL...
FAILED tests/python/test_types.py::test_overflow64[dt1-64] - urllib.error.URL...
FAILED tests/python/test_types.py::test_uint_max[dt1-18446744073709551615] - ...
FAILED tests/python/test_types.py::test_uint_max[dt0-4294967295] - urllib.err...
FAILED tests/python/test_unary_ops.py::test_f64_trig - urllib.error.URLError:...
FAILED tests/python/test_while.py::test_while - urllib.error.URLError: <urlop...
FAILED tests/python/test_while.py::test_break - urllib.error.URLError: <urlop...
FAILED tests/python38/test_ast_refactor.py::test_namedexpr - urllib.error.URL...
==== 1175 failed, 48 passed, 10 skipped, 32 warnings in 240.40s (0:04:00) =====

**Comment by lin-hitonami** [comment]
This is a known bug and it should already be fixed in the latest master branch.
