### ISSUE TITLE
[0.8.6]: Run Code and get Checking version error

### ISSUE THREAD

**Issue by SoTosorrow** [taichi-dev/taichi#3710]
**Describe the bug**
Desc:
I used taichi==0.8.6 to run a simple taichi-demo, it will report a error at "Checking your Taichi version..."
(the error detail will as follows)
then i re-install the taichi0.8.6 and it get wrong again.
then i close the net-connect and it get wrong again.
then i open the vpn and run again, i'll get nothing wrong.
then i change the version to 0.8.5 and get nothing wrong.
maybe the question is due to the net?
however it is strange.

env:
python 3.7.2
taichi 0.8.6
win10

error:
Traceback (most recent call last):
  File "D:\Python\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "D:\Python\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Python\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Python\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Python\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "D:\Python\lib\http\client.py", line 956, in send
    self.connect()
  File "D:\Python\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "D:\Python\lib\socket.py", line 727, in create_connection
    raise err
  File "D:\Python\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cuimi\Desktop\TAICHI\JuliaSet.py", line 2, in <module>
    ti.init(arch=ti.gpu)
  File "D:\Python\lib\site-packages\taichi\lang\__init__.py", line 540, in init
    if check_version():
  File "D:\Python\lib\site-packages\taichi\lang\__init__.py", line 479, in check_version
    with request.urlopen(req, data=payload, timeout=1.5) as response:
  File "D:\Python\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\Python\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "D:\Python\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Python\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "D:\Python\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

```
$ python my_sample_code.py
import taichi as ti
ti.init()
print(1)
```

**Comment by petergu684** [comment]
Same issue here. Looks like the `http://ec2-54-90-48-192.compute-1.amazonaws.com/check_version` is not responding.

**Comment by SoTosorrow** [comment]
> Same issue here. Looks like the `http://ec2-54-90-48-192.compute-1.amazonaws.com/check_version` is not responding.
yes, I have been sought the similar issue but not found that i push this issue.
Beg a pardon for your link? I can not into any valid address

**Comment by yihong0618** [comment]
> Same issue here. Looks like the `http://ec2-54-90-48-192.compute-1.amazonaws.com/check_version` is not responding.

Beause its a remote api, I think its better give a warning instead of raise an error

**Comment by SoTosorrow** [comment]
> > Same issue here. Looks like the `http://ec2-54-90-48-192.compute-1.amazonaws.com/check_version` is not responding.
> 
> Beause its a remote api, I think its better give a warning instead of raise an error

why did taichi have this remote api? maybe just like "wait a minute, I am looking for the new version"? hahhahaha
And it has some bad influence for the offline code
maybe i should peek the source code

**Comment by SoTosorrow** [comment]
> > Same issue here. Looks like the `http://ec2-54-90-48-192.compute-1.amazonaws.com/check_version` is not responding.
> 
> Beause its a remote api, I think its better give a warning instead of raise an error

I just find the source code and it have been fixed
The issues is outdate! sorry! i'll close the issues

**Comment by Leonz5288** [comment]
Hi, this is my problem, I assigned the server to a new domain and didn't expected that the old IP is down. Also the error handling was not handled appropriately in the last version. v0.8.6 would be deleted shortly. Sorry for all the inconvenience.

**Comment by SoTosorrow** [comment]
> Hi, this is my problem, I assigned the server to a new domain and didn't expected that the old IP is down. Also the error handling was not handled appropriately in the last version. v0.8.6 would be deleted shortly. Sorry for all the inconvenience.

Thx for your replay!
by the way, I have expected this is a chance to commit a PR, but I just found the bug had been fixed by yourself 
hhahhhah

**Comment by Leonz5288** [comment]
> > Hi, this is my problem, I assigned the server to a new domain and didn't expected that the old IP is down. Also the error handling was not handled appropriately in the last version. v0.8.6 would be deleted shortly. Sorry for all the inconvenience.
> 
> Thx for your reply! by the way, I have thought this is a chance to commit a PR, but I just found the bug had been fixed by yourself hhahhhah

No worries! This API is just a simple version checking function for reminding users about the new versions of Taichi. It was my fault that it accidentally raised an error instead of giving a warning. Already fixed tho.
