### ISSUE TITLE
Syntax sugars for ti.types.vector and ti.types.matrix

### ISSUE THREAD

**Issue by stamnug** [taichi-dev/taichi#3717]
ti.vec2 for ti.types.vector(2, ti.float)
ti.vec3 for ti.types.vector(3, ti.float)
ti.vec4 for ti.types.vector(4, ti.float)
ti.mat2 for ti.types.matrix(2,2, ti.float)
ti.mat3 for ti.types.matrix(3,3, ti.float)
ti.mat4 for ti.types.matrix(4,4, ti.float)

**Comment by ailzhang** [comment]
@stamnug Could you elaborate a bit on your use case and why `ti.field(ti.u8, shape=(x,y))` isn't good enough? ;)
Btw would you mind if we update the title to English so that it's easily searchable on search engines? Thanks!

**Comment by stamnug** [comment]
> @stamnug Could you elaborate a bit on your use case and why `ti.field(ti.u8, shape=(x,y))` isn't good enough? ;) Btw would you mind if we update the title to English so that it's easily searchable on search engines? Thanks!

标量还好,  向量和矩阵就有点烦了, vec =  ti.Vector.field(n=3, dtype=ti.f32, shape=(x, y, z))  ;  mat = ti.Matrix.field(n=3, m=3, dtype=ti.f32, shape=(x, y, z))  , 而且我个人觉得参数里面填dtype的时候会卡脑子, 我脑子比较简单,三个以上参数就乱,开头ti.Vector或者ti.Matrix相比"vector = ti.i32filed(3, shape=(x,y,z)) ;mat = ti.f64field(4,4, shape=(x,y,z))"这么写估计每个定义要浪费2秒吧,  当然只是个人感觉....   
再比如定义复合类型
my_vec2i = ti.types.vector(2, ti.i32)
my_vec3f = ti.types.vector(3, float)
my_mat2f = ti.types.matrix(2, 2, float)
my_ray3f = ti.types.struct(ro=my_vec3f, rd=my_vec3f, l=ti.f32)
相比
my_vec2i = ti.i32field(2)
my_vec3f = ti.f32field(3)
my_mat2f = ti.ffield(3)  #加个Ffield Ifiled或者f_filed,i_field的糖也行

问题倒是微不足道, 但是码起来  我觉得每句都能省个0.5s出来... 

标题随意了

**Comment by bobcao3** [comment]
Maybe something like vec3 in taichi_glsl?

**Comment by stamnug** [comment]
> @stamnug Could you elaborate a bit on your use case and why `ti.field(ti.u8, shape=(x,y))` isn't good enough? ;) Btw would you mind if we update the title to English so that it's easily searchable on search engines? Thanks!

i change this content, the field is ok, i were confused between the field and the type. now , using ti.vec2, ti.mat3 alias for ti.types.vector(2, ti.float) , ti.types.matrix(3,3, ti.float) is fine.
