### ISSUE TITLE
CUDA Support for Windows

### ISSUE THREAD

**Issue by weignv** [taichi-dev/taichi#372]
Sorry for the spam but I didn't find a place for the feature requests. Please help me to submit requests at the correct place.

OS: Windows 10 Preview Build
Driver version: TOT
Taichi version: 0.3.20
GPU: 2080Ti

C:\Python3dot7>python -m pip install taichi-nightly
Collecting taichi-nightly
  Downloading https://files.pythonhosted.org/packages/19/e1/2ae937db0dc0b238b2c026959552e257c236a76c1433d400fc96486474df/taichi_nightly-0.3.20-cp37-cp37m-win_amd64.whl (15.2MB)

Repro step:
E:\Experiments\taichi-master\examples>mpm99.py
[Release mode]
[T 01/10/20 00:59:07.754] [logging.cpp:taichi::Logger::Logger@68] Taichi core started. Thread ID = 12140
[Taichi version 0.3.20, cpu only, commit 1c85d8e1]
[W 01/10/20 00:59:07.778] [program.cpp:taichi::Tlang::Program::Program@158] Taichi is not compiled with CUDA.

**Comment by yuanming-hu** [comment]
Please also see this: https://github.com/taichi-dev/taichi/issues/424
