### ISSUE TITLE
Why not use mpi as one parallelization option when using cpu backend?

### ISSUE THREAD

**Issue by GumpXiaoli** [taichi-dev/taichi#3739]
Hello,

I'm an algorithm developer from CAE industry. We usually use mpi as the default parallelizaiton method, especially when two or more computing nodes are needed. In general, MPI+X is the common scheme., and X can be openmp, pthread(rarely used), GPU, etc.

Is there any problem to implement mpi codes in Taichi, or other concerns that i don't know.

Thanks!

**Comment by turbo0628** [comment]
X can be Taichi in the MPI + X common scheme. In the current version, you can temporarily solve this problem by combining MPI4py + Taichi. This solution should work well with coarse-grained parallelism (many processes, each process can be solved with an independent smaller Taichi kernel),  but shall not tackle with fine-grained parallelism (grand taichi field distributed over a large compute cluster). The latter parallelization pattern is obviously complex for Taichi: Taichi would have to automatically analyze and parallelize with the right multi-level parallel scheme (MPI + CPU + GPU, for example). 

I guess you might want to manually embedding MPI code into Taichi scope? It is neither a reasonable implementation: the compiler cannot override hand-written grids, so it's a great challenge to keep it consistent between the compiler's parallelization strategy and the user specified grids.

Therefore, I would suggest that you try out small taichi kernels and use some forms of MPI for cluster parallelization. I believe that the fine-grained scale-out implementation is something on the distant roadmap :)

**Comment by qiao-bo** [comment]
We close this for now, please reopen this if you have further questions.
