### ISSUE TITLE
[MSVC][std:c++latest] error C2666: '!=': 3 overloads have similar conversions

### ISSUE THREAD

**Issue by QuellaZhang** [taichi-dev/taichi#3745]
Taichi failed to build with /std:c++latest on MSVC. Could you please help look at this issue or provide some workarounds? Thanks in advance.

**Environment**
Compiler version: VS2019 (16.11.5)
Operating system: Windows server 2019

**Reproduce steps:**

1. git clone https://github.com/taichi-dev/taichi c:/
2. cd taichi
3. git submodule update --init --recursive
4. mkdir bin & cd bin
5. C:\Python39\python.exe -m pip install --upgrade pip
6. set PATH=C:\Users\CPPTESTLOCAL\AppData\Roaming\Python\Python39\Scripts;%PATH%
7. pip3 install --user gitpython
8. pip3 install --user pybind11
9. set PATH={taichi-llvm-10.0.0-msvc2019 dir}\bin;%PATH%
10. set PATH={clang-10.0.0-win dir}\bin;%PATH%
11. set _CL_=/std:c++latest /D_HAS_DEPRECATED_RESULT_OF=1 /D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING
12. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DTI_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -Dgtest_force_shared_crt=TRUE ..
13. msbuild /p:Configuration=Release;Platform=x64 taichi.sln /t:Rebuild /m

**Build log:** [Taichi_build.log](https://github.com/taichi-dev/taichi/files/7673836/Taichi_build.log)

**Build error:**
codegen_metal.cpp
F:\gitP\taichi-dev\Taichi\taichi\backends\metal\codegen_metal.cpp(1003,1): error C2666: '!=': 3 overloads have similar conversions
F:\gitP\taichi-dev\Taichi\taichi/ir/expression_ops.h(94,1): note: could be 'taichi::lang::Expr taichi::lang::operator !=(const taichi::lang::Expr &,const taichi::lang::Expr &)'
F:\gitP\taichi-dev\Taichi\taichi/ir/type.h(64,8): note: or 'bool taichi::lang::DataType::operator ==(const taichi::lang::DataType &) const' [synthesized expression '!(y == x)']
F:\gitP\taichi-dev\Taichi\taichi/ir/expression_ops.h(93,1): note: or 'taichi::lang::Expr taichi::lang::operator ==(const taichi::lang::Expr &,const taichi::lang::Expr &)' [rewritten expression '!(x == y)']
F:\gitP\taichi-dev\Taichi\taichi/ir/expression_ops.h(93,1): note: or 'taichi::lang::Expr taichi::lang::operator ==(const taichi::lang::Expr &,const taichi::lang::Expr &)' [synthesized expression '!(y == x)']
F:\gitP\taichi-dev\Taichi\taichi\backends\metal\codegen_metal.cpp(1003,1): note: or       'built-in C++ operator!=(T *, T *)'
        with
        [
            T=taichi::lang::PrimitiveType
        ]
F:\gitP\taichi-dev\Taichi\taichi\backends\metal\codegen_metal.cpp(1003,1): note: or       'built-in C++ operator!=(const taichi::lang::Type *, const taichi::lang::Type *)'
F:\gitP\taichi-dev\Taichi\taichi\backends\metal\codegen_metal.cpp(1003,1): note: or       'built-in C++ operator!=(taichi::lang::Type *, taichi::lang::Type *)'
F:\gitP\taichi-dev\Taichi\taichi\backends\metal\codegen_metal.cpp(1003,1): note: while trying to match the argument list '(T *, taichi::lang::DataType)'
        with
        [
            T=taichi::lang::PrimitiveType
        ]

**Comment by bobcao3** [comment]
Hello! Does this happen when you use `c++17`? We have not tried the latest C++ yet, it seems like some operator overload is actually added or something to the latest c++

**Comment by QuellaZhang** [comment]
Sorry for the late reply. Verified with /std:c++17 there was no error. So these issues only occur on C++20.

**Comment by rexwangcc** [comment]
@QuellaZhang Hi, we haven't officially supported `C++20` yet, for now, if possible, could you stick with `C++17` for your use cases?
