### ISSUE TITLE
Remove `print_preprocessed` which is no longer used. 

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#3748]
After the ast generator refactor `print_preprocessed` is no longer used(replaced by `print_preprocessed_ir`). We should remove it as well as `print_ast` here. https://github.com/taichi-dev/taichi/blob/master/python/taichi/lang/ast/ast_transformer_utils.py#L199-L204 
This task should be as simple as removing all of `print_preprocessed` and `print_ast`s. 
cc: @lin-hitonami

**Comment by JawadurRahman** [comment]
I would like to make my first contribution hence, I would like to help!

**Comment by mzmzm** [comment]
Maybe I can try to take over this.
