### ISSUE TITLE
Reduce windows build script to minimal dependencies

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#3754]
`install_deps.ps1` in https://docs.taichi.graphics/lang/articles/contribution/dev_install#build-taichi-from-source requires downloading a full vs build tools package which takes ~40mins on my machine. We should identify what're the minimal deps to speed up the build process for windows 
cc: @frostming Do you have any insights what can be improved in the script by any chance? ;)

**Comment by frostming** [comment]
First, conda is not necessary at all, at least I haven't used conda in either m1 mac or windows 10 to have taichi build successfully. The vanilla Python interpreter should work fine, and we can assume the users already have one on their system.

Second, the only needed dependency is MSVC build tools. We can direct users to the download link, the installer is very user-friendly and IMO it doesn't need other instructions, moreover, the build tool is essential to compile C extensions and would benefit users installing not only taichi.

**Comment by qiao-bo** [comment]
The question here is whether we automate the process or provide the information to the user. IIUC the choice of Conda is not to install a python environment, but to suggest a convenient way to isolate Taichi python environment with other apps.  Although end users may or may not need this. 

Choco is indeed not necessary here (it was needed when we are developing Dockerfile, there using Choco is more convenient). Without Choco, we can also manually download from a link and install, which i doubt the total time can be anywhere faster. But worth a try.

The current script has many places to improve. We can check the availability of the executables before install, skip if already found. IMHO stuff like git, cmake are indeed our dependencies, it is a bit strange to leave them away in the script.

**Comment by frostming** [comment]
> but to suggest a convenient way to isolate Taichi python environment with other apps

I recommend using a virtualenv, in fact, the win build script [is already using it](but to suggest a convenient way to isolate Taichi python environment with other apps). We can extend it to UNIX builds to get rid of the `pip uninstall taichi taichi-nightly` stuff.

> IMHO stuff like git, cmake are indeed our dependencies, it is a bit strange to leave them away in the script.

git is a basic tool that we can assume users have it. `cmake` is a build requirements and will be installed by `pip install -r requirements_dev.txt`(The prebuilt binary is shipped as a PyPI package and can be installed with `pip`)

**Comment by ailzhang** [comment]
@frostming I'm curious if downloading the whole of msvc build tools is necessary for building taichi. My main concern here is downloading that takes 40+mins :P

**Comment by bobcao3** [comment]
Even if we avoid MSVC we can't avoid Win 10 SDK.

**Comment by bobcao3** [comment]
Unless we switch to mingw, but I think that's more trouble than what its worth. I still recommend windows developers just install the full Visual Studio, it ships with many useful tools (CMake, MSVC, optionally Clang 13, Win 10 SDK, Ninja, git, etc.) Also when we later add DirectX back end, having the full SDK is quite beneficial.

**Comment by bobcao3** [comment]
In addition, if a developer wishes to build Taichi from source, it's highly likely that the developer also wants debugging capabilities. Visual Studio's debugger is quite good and quite convenient. If the SDK and compilers are installed manually, the user will need to install a debugger as well and in my experience those are really hard to install and use

**Comment by bobcao3** [comment]
As for Chocolatey, I don't think we should use it. The user can decide to use it to install stuff if they want, but we shouldn't just by default install an entire package system. For individual developers (instead of CI environments), Visual Studio GUI installer is great.

**Comment by qiao-bo** [comment]
agree, then should we still keep this `install_deps.ps1`?

**Comment by qiao-bo** [comment]
To summarize, the `install_dep.ps1` can be deleted. Instead, we add requirements to build Taichi from source, i.e., VS and Python. We recommend full version of VS and Conda. This can go to some requirements section of the dev install page?

**Comment by frostming** [comment]
Close this issue since `install_dep.ps1` has been deleted.
