### ISSUE TITLE
GGUI canvas.set_image() not working on taichi 0.8.6~0.8.7

### ISSUE THREAD

**Issue by cflw** [taichi-dev/taichi#3765]
examples: 
https://github.com/taichi-dev/taichi/blob/master/python/taichi/examples/ggui_examples/fractal3d_ggui.py
https://github.com/taichi-dev/taichi/blob/master/python/taichi/examples/ggui_examples/stable_fluid_ggui.py

```
[Taichi] version 0.8.7, llvm 10.0.0, commit 88d81df6, win, python 3.9.9
[Taichi] Starting on arch=cuda
```

the window is black.

![python_20211209223827](https://user-images.githubusercontent.com/17311509/145416789-0d658277-02de-4875-8a61-5cd4821e6162.png)

**Comment by AmesingFlank** [comment]
Hi!

This is indeed a bug. I submitted #3767 to fix it, and we should be able to release the fix in the next version. Until then, the workaround would be to always call `set_image` with a `ti.vector.field(4,...)`, where the 4th channel (alpha channel) is set to 1.0 (for float) or 255 (for u8).
