### ISSUE TITLE
NVIDIA Jetson (ARM + CUDA) Support

### ISSUE THREAD

**Issue by hgnan** [taichi-dev/taichi#377]
**Describe the bug**
 My environment is as blow：
```
jetson@jetson-nano:/taichi/build$ jetson_release 
 - NVIDIA Jetson NANO/TX1
   * Jetpack 4.2.1 [L4T 32.2.0]
   * CUDA GPU architecture 5.3
 - Libraries:
   * CUDA 10.0.326
   * cuDNN 7.5.0.56-1+cuda10.0
   * TensorRT 5.1.6.1-1+cuda10.0
   * Visionworks 1.6.0.500n
   * OpenCV 4.1.0 compiled CUDA: YES
 - Jetson Performance: inactive
```

**Log/Screenshots**

```
/taichi/build$ cmake .. -DPYTHON_EXECUTABLE=python3.6 -DCMAKE_C_COMPILER=/usr/local/clang-8.0.1/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/clang-8.0.1/bin/clang++ 
Taichi Version 0.3.20
       Commit 04d78bf8f5dc660a3e3dc61d4305166bfe346243
Using C++ compiler: /usr/local/clang-8.0.1/bin/clang++
Clang compiler detected. Using std=c++17.
Using float32 (single) precision as real
Using python3.6 as python executable.
Python 3.6.9
    version: 3.6
    include: /usr/include/python3.6m
    library: PYTHON_LIBRARY-NOTFOUND
    numpy include: /usr/local/lib/python3.6/dist-packages/numpy/core/include
    pybind11 include: /usr/local/include/python3.6;/home/jetson/.local/include/python3.6m
Building with CUDA 10.0
Found CUDA. Arch = 61
-- Found LLVM 8.0.1
-- Using LLVMConfig.cmake in: /usr/local/clang-8.0.1/lib/cmake/llvm
llvm include dirs /usr/local/clang-8.0.1/include
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_CXX_FOUND) 
OpenMP not found.
PYTHON_LIBRARIESPYTHON_LIBRARY-NOTFOUND
C++ Flags:  -DTC_ISE_NONE -std=c++17 -fsized-deallocation -Wall  -DTC_PASS_EXCEPTION_TO_PYTHON -DTC_INCLUDED -g -DCUDA_FOUND -DTLANG_WITH_CUDA -D TLANG_CUDA_VERSION='"10.0"'
Build type: RelWithDebInfo
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jetson/taichi/build

jetson@jetson-nano: /taichi/build$ make
Scanning dependencies of target taichi_core
[  1%] Building CXX object CMakeFiles/taichi_core.dir/taichi/analysis/value_diff.cpp.o
In file included from /home/jetson/taichi/taichi/analysis/value_diff.cpp:3:
In file included from /home/jetson/taichi/taichi/analysis/../ir.h:6:
In file included from /home/jetson/taichi/taichi/util.h:7:
In file included from /home/jetson/taichi/taichi/common/loader.h:8:
In file included from /home/jetson/taichi/taichi/common/interface.h:8:
In file included from /home/jetson/taichi/taichi/common/dict.h:17:
In file included from /home/jetson/taichi/taichi/math/math.h:9:
In file included from /home/jetson/taichi/taichi/math/geometry_util.h:11:
In file included from /home/jetson/taichi/taichi/math/linalg.h:13:
In file included from /usr/local/clang-8.0.1/lib/clang/8.0.1/include/immintrin.h:28:
**/usr/local/clang-8.0.1/lib/clang/8.0.1/include/mmintrin.h:47:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?**
    __builtin_ia32_emms();
    ^
/usr/lib/gcc/aarch64-linux-gnu/7/../../../../include/c++/7/cmath:743:12: note: '__builtin_isless' declared here
  { return __builtin_isless(__x, __y); }
           ^
In file included from /home/jetson/taichi/taichi/analysis/value_diff.cpp:3:
In file included from /home/jetson/taichi/taichi/analysis/../ir.h:6:
In file included from /home/jetson/taichi/taichi/util.h:7:
In file included from /home/jetson/taichi/taichi/common/loader.h:8:
In file included from /home/jetson/taichi/taichi/common/interface.h:8:
In file included from /home/jetson/taichi/taichi/common/dict.h:17:
In file included from /home/jetson/taichi/taichi/math/math.h:9:
In file included from /home/jetson/taichi/taichi/math/geometry_util.h:11:
In file included from /home/jetson/taichi/taichi/math/linalg.h:13:
In file included from /usr/local/clang-8.0.1/lib/clang/8.0.1/include/immintrin.h:28:
/usr/local/clang-8.0.1/lib/clang/8.0.1/include/mmintrin.h:47:25: error: too few arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
                        ^
/usr/local/clang-8.0.1/lib/clang/8.0.1/include/mmintrin.h:64:19: error: use of undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                  ^
/usr/local/clang-8.0.1/lib/clang/8.0.1/include/mmintrin.h:81:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
.....
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
CMakeFiles/taichi_core.dir/build.make:62: recipe for target 'CMakeFiles/taichi_core.dir/taichi/analysis/value_diff.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/taichi/analysis/value_diff.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/taichi_core.dir/all' failed
make[1]: *** [CMakeFiles/taichi_core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
Can anyone tell me how to solve it?

**Comment by yuanming-hu** [comment]
Let me try to remove the dependency on the x86 intrinsics which don't exist on ARM. I'm happy to help you resolve this. However, we've never compiled our system on jetson, so the process might not be smooth. Do you still wish to try given the potential challenges?

**Comment by hgnan** [comment]
Come on!    If the  cross-platform version is released, I would be happy to try it.

**Comment by yuanming-hu** [comment]
@hgnan I have removed the dependency on x86_64 SIMD intrinsics. Not sure if it compiles on your end now. (I don't have a Jetson so I can't test.) I guess making it work on Jetson is not too hard, but I'll need your help to provide feedback (compilation errors, runtime errors, etc.).

**Comment by hgnan** [comment]
I am glad to hear from you.    I try to compile the code that removed the dependency on x86_64 SIMD intrinsics.    The compilation progress has been advanced to 50%.  

`[ 50%] Building CXX object CMakeFiles/taichi_core.dir/taichi/system/timer.cpp.o
/home/jetson/taichi/taichi/system/timer.cpp:159:34: error: invalid output constraint '=a' in asm
  __asm__ __volatile__("rdtsc" : "=a"(lo), "=d"(hi));
                                 ^
1 error generated.
CMakeFiles/taichi_core.dir/build.make:1070: recipe for target 'CMakeFiles/taichi_core.dir/taichi/system/timer.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/taichi/system/timer.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/taichi_core.dir/all' failed
make[1]: *** [CMakeFiles/taichi_core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

The attach file is the compilation's log  
[taichi_ARM_Error.txt](https://github.com/taichi-dev/taichi/files/4053589/taichi_ARM_Error.txt)

BTW:    Before running  make ，I need remove " -march=nehalem " in ./cmake/TaichiCXXFlags.cmake.

**Comment by yuanming-hu** [comment]
Oh I forgot to remove `rdtsc` which is an x86 instruction. I haven't found a replacement on ARM but this function is almost never used anyway. Now it should work.

PS: I likely need your help on `TaichiCXXFlags.cmake`. I'm not sure if it really works on ARM, since I have no idea what `${CMAKE_SYSTEM_PROCESSOR}` returns. I guess it is `arm`, but it could also be `ARM`, `Arm`, `Arm32` etc.

I removed `-march=nehalem` on Arm.

Please take a look at the changeset of this commit: https://github.com/taichi-dev/taichi/commit/24dee98bc97089249977c5d79c44bcd2a06787e4

**Comment by hgnan** [comment]
$ cmake ..  -DCMAKE_C_COMPILER=/usr/local/clang-8.0.1/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/clang-8.0.1/bin/clang++ 
Taichi Version 0.3.21
       Commit 5a4b80cce5bfb3ae14dcbb7d58dba7a90dbc05a3
Using C++ compiler: /usr/local/clang-8.0.1/bin/clang++
Clang compiler detected. Using std=c++17.
**Building for processor aarch64**
CMake Error at cmake/TaichiCXXFlags.cmake:45 (message):
  **Unknown processor type aarch64**
Call Stack (most recent call first):
  CMakeLists.txt:61 (include)


-- Configuring incomplete, errors occurred!
The cmake is pass when I  have changed "arm" to  "aarch64" at  ./cmake/TaichiCXXFlags.cmake:45.

$ cmake ..  -DCMAKE_C_COMPILER=/usr/local/clang-8.0.1/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/clang-8.0.1/bin/clang++ 
Taichi Version 0.3.21
       Commit 5a4b80cce5bfb3ae14dcbb7d58dba7a90dbc05a3
Using C++ compiler: /usr/local/clang-8.0.1/bin/clang++
Clang compiler detected. Using std=c++17.
Building for processor aarch64
Using float32 (single) precision as real
Using 'python3' as python interpreter.
Python 3.6.9
    version: 3.6
    include: /usr/include/python3.6m
    library: PYTHON_LIBRARY-NOTFOUND
    numpy include: /usr/local/lib/python3.6/dist-packages/numpy/core/include
    pybind11 include: /usr/local/include/python3.6;/home/jetson/.local/include/python3.6m
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "10.0", minimum required is "10.0") 
Building with CUDA 10.0
Found CUDA. Arch = 61
-- Found LLVM 8.0.1
-- Using LLVMConfig.cmake in: /usr/local/lib/cmake/llvm
llvm include dirs /usr/local/include
-- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
Found OpenMP.
PYTHON_LIBRARIESPYTHON_LIBRARY-NOTFOUND
**C++ Flags:  -DTC_ISE_NONE -std=c++17 -fsized-deallocation -Wall  -DTI_ARCH_ARM -DTC_PASS_EXCEPTION_TO_PYTHON -DTC_INCLUDED -g -DCUDA_FOUND -DTLANG_WITH_CUDA -D TLANG_CUDA_VERSION='"10.0"' -DOPENMP_FOUND -DTLANG_WITH_OPENMP**
Build type: RelWithDebInfo
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jetson/taichi/build

-------------------------------------------------------------------------------------------
But  the error occurred during the linking phase.

$make 
.......
[100%] Linking CXX shared library libtaichi_core.so
**/usr/bin/ld: libtaichi_core.so: No symbol version section for versioned symbol `powf@GLIBC_2.2.5'
/usr/bin/ld: final link failed: Nonrepresentable section on output**
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/taichi_core.dir/build.make:2343: recipe for target 'libtaichi_core.so' failed
make[2]: *** [libtaichi_core.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/taichi_core.dir/all' failed
make[1]: *** [CMakeFiles/taichi_core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

[detail log taichi_ARM_Error-clang8.txt](https://github.com/taichi-dev/taichi/files/4057599/taichi_ARM_Error-clang8.txt)

**Comment by yuanming-hu** [comment]
I think we are very close to having taichi compiled and linked. I just now pushed commit 8e8ab842 that will resolve the linking issue you mentioned. Please pull and try.

Btw, could you make a PR on the `aarch64` fix? Thanks!

**Comment by hgnan** [comment]
I use the commit  [8e8ab84](https://github.com/taichi-dev/taichi/commit/8e8ab8428a9e4820a5c21761d8b3833f46f6bf39)  ，but still encounter errors. 


```
[100%] Linking CXX shared library libtaichi_core.so
/usr/bin/ld: libtaichi_core.so: No symbol version section for versioned symbol `**expf@GLIBC_2.2.5**'
/usr/bin/ld: final link failed: Nonrepresentable section on output
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/taichi_core.dir/build.make:2343: recipe for target 'libtaichi_core.so' failed
make[2]: *** [libtaichi_core.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/taichi_core.dir/all' failed
make[1]: *** [CMakeFiles/taichi_core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by yuanming-hu** [comment]
Hi @hgnan,

Sorry about the incomplete linking fix. Could you try 0726d495?

Thanks!

**Comment by hgnan** [comment]
_#if defined(TC_PLATFORM_LINUX) && !ARCH_cuda && defined(TI_ARCH_x86_64)_   error is as blow

```
[ 94%] Linking CXX shared library libtaichi_core.so
/usr/bin/ld: libtaichi_core.so: No symbol version section for versioned symbol `expf@GLIBC_2.2.5'
```

_#if defined(TC_PLATFORM_LINUX) && !ARCH_cuda_     error is  as blow
```
[ 94%] Linking CXX shared library libtaichi_core.so
/usr/bin/ld: libtaichi_core.so: No symbol version section for versioned symbol `powf@GLIBC_2.2.5'
```

**Comment by yuanming-hu** [comment]
Hi @hgnan 

Thanks for trying. I believe all the symbol versioning instructions (https://github.com/taichi-dev/taichi/search?q=GLIBC_2.2.5&unscoped_q=GLIBC_2.2.5) have been safeguarded by `defined(TI_ARCH_x86_64)` - could you clear the build folder and retry?

If you still have this error, please try directly removing the 6 lines of `__asm__ ...` and let me know if it works on Jetson.

Best,
Yuanming

**Comment by hgnan** [comment]
When I use the latest commit （bb6f6bbce7fcfc4706ba6d2cd6de86cfa29d4c2d）, The make  was completed successfully on Jetson platform.   
[taichi_ARM_make.txt](https://github.com/taichi-dev/taichi/files/4080759/taichi_ARM_make.txt)

When I tried to run  the demo of 99 line  ， error as blow：

`jetson@jetson-nano:~/taichi$ python3 mpm.py 
[T 01/18/20 21:48:35.502] [logging.cpp:Logger@68] Taichi core started. Thread ID = 7748
[Taichi version 0.3.22, cuda 10.0, commit bb6f6bbc]
Using CUDA Device [0]: NVIDIA Tegra X1
Device Compute Capability: 5.3
[E 01/18/20 21:48:35.615] [unified_allocator.cpp:UnifiedAllocator@23] Cuda Error cudaErrorMemoryAllocation: out of memory
[E 01/18/20 21:48:35.616] Received signal 6 (Aborted)
***********************************
* Taichi Compiler Stack Traceback *
***********************************
/home/jetson/taichi/build/taichi_core.so: taichi::signal_handler(int)
linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7fb1a046c0]
/lib/aarch64-linux-gnu/libc.so.6: raise



GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 7748
[New LWP 7751]
[New LWP 7752]
[New LWP 7753]
[New LWP 7754]
[New LWP 7756]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
0x0000007fb18eb2e0 in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc@entry=0x7fe25b9078, options=options@entry=0)
    at ../sysdeps/unix/sysv/linux/waitpid.c:30
30      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
(gdb) 
(gdb) quit
A debugging session is active.

        Inferior 1 [process 7748] will be detached.

Quit anyway? (y or n) y
Detaching from program: /usr/bin/python3.6, process 7748`

BTW ，The Jetson Nano has 4 GB of RAM for both the GPU and the CPU.

**Comment by yuanming-hu** [comment]
Glad that it builds! Taichi probably asks for too much memory for Jetson Nano. I just now pushed d09eea9d which reduces the memory allocation requests on mobile devices - could you have a try? Thanks for your patience!

**Comment by hgnan** [comment]
When I use the latest commit  

`jetson@jetson-nano:~/taichi$ python3 mpm.py 
[T 01/19/20 17:49:39.893] [logging.cpp:Logger@68] Taichi core started. Thread ID = 11267
[Taichi version 0.3.23, cuda 10.0, commit 138d104d]
Using CUDA Device [0]: NVIDIA Tegra X1
Device Compute Capability: 5.3
[E 01/19/20 17:49:42.179] [unified_allocator.cpp:UnifiedAllocator@28] Cuda Error cudaErrorInvalidDevice: invalid device ordinal
[E 01/19/20 17:49:42.179] Received signal 6 (Aborted)
***********************************
* Taichi Compiler Stack Traceback *
***********************************
/home/jetson/taichi/build/taichi_core.so: taichi::signal_handler(int)
linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7f795716c0]
/lib/aarch64-linux-gnu/libc.so.6: raise
`

The error seems to be originating from a missing device capability. As the CUDA documentation for the cudaMemAdvise function states:

If device is a GPU, then it must have a non-zero value for the device attribute cudaDevAttrConcurrentManagedAccess.

You should call the following code to make sure that the device is OK for concurrent managed use:

int device_id = 0, result = 0;
cudaDeviceGetAttribute (&result, cudaDevAttrConcurrentManagedAccess, device_id);
if (result) {
    // Call cudaMemAdvise
}
Quoted from ：[https://stackoverflow.com/questions/41058748/how-to-specify-gpu-id-for-cudamemadvisesetpreferredlocation/41071688](url) .     I'm not a coding guy,  but I hope the url help for you.

**Comment by yuanming-hu** [comment]
I guess `cudaMemAdvise` is probably redundant here and maybe not supported on Jetson. Could you try commenting that line (`unified_allocator.cpp:UnifiedAllocator@Line 28`) out? Thanks so much for your patience!

**Comment by hgnan** [comment]
When I remove the line (unified_allocator.cpp:UnifiedAllocator@Line 28),   'invalid device ordinal' was disappear.    But still haven't run the demo successfully. 


`jetson@jetson-nano:~/taichi$ python3 mpm.py       
[T 01/20/20 21:45:43.819] [logging.cpp:Logger@68] Taichi core started. Thread ID = 8423
[Taichi version 0.3.23, cuda 10.0, commit 138d104d]
Using CUDA Device [0]: NVIDIA Tegra X1
Device Compute Capability: 5.3
[I 01/20/20 21:45:45.814] [taichi_llvm_context.cpp:TaichiLLVMContext@59] Creating llvm context for arch: x86_64
[I 01/20/20 21:45:45.882] [/home/jetson/taichi/python/taichi/lang/impl.py:materialize@124] Materializing layout...
[D 01/20/20 21:45:45.883] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/20/20 21:45:45.883] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/20/20 21:45:45.883] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/20/20 21:45:45.883] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/20/20 21:45:45.883] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/20/20 21:45:45.883] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/20/20 21:45:45.900] [taichi_llvm_context.cpp:find_existing_command@92] 
commands: [
  [0]: clang-7
  [1]: clang
]
**[E 01/20/20 21:45:45.900] [taichi_llvm_context.cpp:find_existing_command@93] No command found.
[E 01/20/20 21:45:45.901] Received signal 6 (Aborted)**
***********************************
* Taichi Compiler Stack Traceback *
***********************************
/home/jetson/taichi/build/taichi_core.so: taichi::signal_handler(int)
linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7f81f9c6c0]
/lib/aarch64-linux-gnu/libc.so.6: raise



GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 8423
[New LWP 8426]
[New LWP 8427]
[New LWP 8428]
[New LWP 8429]
[New LWP 8431]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
0x0000007f81e832e0 in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc@entry=0x7fdc8694e8, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
(gdb) `

**Comment by yuanming-hu** [comment]
Cool! I think we are very close. I need a deeper investigation into this `LLVM Fatal Error: Cannot select: intrinsic %llvm.nvvm.atomic.add.gen.i.sys`, but before I find out a solution, could you try removing `ti.cfg.arch = ti.cuda` so that we can see it the program runs on ARM cpu only?

**Comment by hgnan** [comment]
I try removed 'ti.cfg.arch = ti.cuda' ，  the demo no longer reports any error.   

`jetson@jetson-nano:~/taichi$ python3 mpm.py       
[T 01/21/20 09:38:50.728] [logging.cpp:Logger@68] Taichi core started. Thread ID = 20441
[Taichi version 0.3.23, cuda 10.0, commit 138d104d]
Using CUDA Device [0]: NVIDIA Tegra X1
Device Compute Capability: 5.3
[I 01/21/20 09:38:50.833] [taichi_llvm_context.cpp:TaichiLLVMContext@59] Creating llvm context for arch: x86_64
[I 01/21/20 09:38:50.898] [/home/jetson/taichi/python/taichi/lang/impl.py:materialize@124] Materializing layout...
[D 01/21/20 09:38:50.898] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/21/20 09:38:50.898] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/21/20 09:38:50.898] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/21/20 09:38:50.898] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/21/20 09:38:50.898] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[D 01/21/20 09:38:50.899] [snode.cpp:create_node@48] Non-power-of-two node size 9000 promoted to 16384.
[T 01/21/20 09:38:50.918] [taichi_llvm_context.cpp:compile_runtime_bitcode@112] Compiling runtime module bitcode...
[I 01/21/20 09:38:52.594] [struct_llvm.cpp:operator()@276] Allocating data structure of size 1114112 B
Initializing runtime with 26 elements
Runtime initialized.
[I 01/21/20 09:38:58.120] [/home/jetson/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel substep_c4_0_...
[I 01/21/20 09:39:01.379] [/home/jetson/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel matrix_to_ext_arr_c12_0_...
[I 01/21/20 09:39:01.735] [/home/jetson/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel tensor_to_ext_arr_c8_0_...
`
Jetson benchmark is 2.16 FPS  at CPU only mode.   
![taichi-cpu_only](https://user-images.githubusercontent.com/34827518/72768376-2da46000-3c32-11ea-9216-f5da3aebb213.jpg)

Looking forward to your release of GPU accelerated version！

**Comment by yuanming-hu** [comment]
Awesome!!! Let's track the CUDA issue in this thread: https://github.com/taichi-dev/taichi/issues/397
