### ISSUE TITLE
Add support for operator "in"

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#3783]
**Concisely describe the proposed feature**
Taichi itself does not support operator `in`. However, before the refactoring of the AST transformer, code like `if ti.static(dtype in [ti.f32, ti.f64]):` can run perfectly because they were handled by Python instead of taichi AST transformer. Sadly, these code can no longer run after the refactoring because all the expressions are evaluated by the AST transformer now. Similar usages are widely used by the users, so operator `in` should be supported in taichi. 

The current implementation of `list` as a taichi variable does not support `in` because it converts all the variables it contains to taichi objects when it is assigned. so we should only allow operator `in` on normal `list`s and `dict`s.

**Describe the solution you'd like (if any)**
We can wrap the `list`s in a new wrapper class in `expr_init`, an disallow operator `in` on that class. (Maybe throw an exception in \_\_contains\_\_)

**Comment by yuanming-hu** [comment]
Sorry I'm a little confused - are you talking about supporting `in` in `ti.static(...)` only, so that the expression can be evaluated at compile-time, or further adding such support to normal Taichi code which is later run-time evaluated (e.g., on GPUs)?

**Comment by lin-hitonami** [comment]
The evaluation of operator `in` is handled at compile-time now, and it does not matter whether it is in `ti.static`. Maybe we should limit it only inside `ti.static`.

**Comment by lin-hitonami** [comment]
However, it can work on code like `if 1 in [1, 2]`, it simply translate it to `if True`

**Comment by strongoier** [comment]
> it converts all the variables it contains to taichi objects when it is assigned

IMHO the main question here is whether we are going to support a list of Taichi objects (say `Expr`s).

**Comment by yuanming-hu** [comment]
> Maybe we should limit it only inside `ti.static`.

Agreed. We can stick to the old behavior before the AST refactoring.



> However, it can work on code like `if 1 in [1, 2]`, it simply translate it to `if True`. I don't know if we should also add support for that.

IMHO testing if a number is within a list is not really a frequent use case. If that need happens users can simply translate that into something like `a == 1 or a == 2`.

**Comment by lin-hitonami** [comment]
Another solution may be adding support to runtime-evaluation. We can translate `a in b` to `a == b[0] or a == b[1] or ...`. (though this is a little time-consuming if the list is too long)

**Comment by yuanming-hu** [comment]
> Another solution may be adding support for runtime-evaluation when the content of the list is taichi object. We can translate `a in b` to `a == b[0] or a == b[1] or ...`. (though this is a little time-consuming if the list is too long)

That could be one solution, but then you need to define clearly its behavior: if someone writes `a in [b(), c()]`, and `a == b()`, would the system still execute `c()`? I feel like adding syntax sugars like this needs cautious considerations, so I suggest that we don't do it for now.

**Comment by lin-hitonami** [comment]
So, let's just limit it in `ti.static` and stick to the old behavior for now.
