### ISSUE TITLE
Cornell box example is broken on opengl backend

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#3796]
It's shows below on current master. I've confirmed it was correct on 0.8.5 release so we need to do a bisect. 
![image](https://user-images.githubusercontent.com/5248122/145943531-7d033a87-687a-4967-9a52-bc9a1f19601d.png)

**Comment by strongoier** [comment]
It seems that it is caused by #3517. However, I haven't figured out the relationship between this PR and the opengl backend yet :-(

**Comment by k-ye** [comment]
I just remembered https://github.com/taichi-dev/taichi/issues/1349, maybe it is relevant?
