### ISSUE TITLE
Failed to install taichi-nightly with pip on macOS 10.14.6

### ISSUE THREAD

**Issue by JasVixBan** [taichi-dev/taichi#380]
**Describe the bug**
Failed to install taichi-nightly with pip on macOS 10.14.6
Python: 3.6.5
CPU: i9-8950HK CPU @ 2.90GHz
OS: macOS 10.14.6

**Log/Screenshots**
Das:~ callue$ pip search taichi
taichi-nightly (0.3.21)            - The Taichi Programming Language
taichi-gpu-nightly (0.0.59)        - The Taichi Programming Language
taichi (0.0.30)                    - Computer Graphics R&D Infrastructure
taichi-nightly-cuda-10-0 (0.3.21)  - The Taichi Programming Language
taichi-nightly-cuda-10-1 (0.3.20)  - The Taichi Programming Language
Das:~ callue$
Das:~ callue$ pip install taichi-nightly
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting taichi-nightly
  ERROR: Could not find a version that satisfies the requirement taichi-nightly (from versions: none)
ERROR: No matching distribution found for taichi-nightly
WARNING: You are using pip version 19.2.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**To Reproduce**
pip install Taichi-nightly

**Comment by yuanming-hu** [comment]
It seems to be caused by the usage of tune.tsinghua indexes.
You can find the official packages here: https://pypi.org/project/taichi-nightly/

**Comment by yuanming-hu** [comment]
It seems that the tuna source at Tsinghua has only taichi-nightly version up to 0.3.9, which is released 20 days ago... https://pypi.tuna.tsinghua.edu.cn/simple/taichi-nightly/

**Comment by zhaohongda1987** [comment]
> It seems that the tuna source at Tsinghua has only taichi-nightly version up to 0.3.9, which is released 20 days ago... https://pypi.tuna.tsinghua.edu.cn/simple/taichi-nightly/

Hi yuanming-hu, I used pip install Taichi-nightly==0.3.9 and it's also not work
ERROR: Could not find a version that satisfies the requirement taichi-nightly==0.3.9 (from versions: none)
ERROR: No matching distribution found for taichi-nightly==0.3.9

**Comment by yuanming-hu** [comment]
Did you manually set the source to `pypi.tuna.tsinghua`?

**Comment by yuanming-hu** [comment]
I believe using the official pypi source will solve your issue. A lot of users from China reported similar situations.

**Comment by zhaohongda1987** [comment]
> Did you manually set the source to `pypi.tuna.tsinghua`?

Hi @yuanming-hu , Do you means like " pip install -i https://pypi.tuna.tsinghua.edu.cn/simple taichi-nightly  ", i try to do it but also
ERROR: Could not find a version that satisfies the requirement taichi-nightly (from versions: none)
ERROR: No matching distribution found for taichi-nightly

**Comment by JasVixBan** [comment]
Thanks. But I found that Python3.6 on macOS is not provided. So I installed Python3.7 and I can install taichi-nightly with pip now.
<img width="812" alt="image" src="https://user-images.githubusercontent.com/11515318/72241186-232a0b00-3621-11ea-93cb-cf0f0a720edb.png">

**Comment by yuanming-hu** [comment]
Sounds good. It seems hard to make Travis work with Python3.6. Giving up support for Python3.6 on OS X.

**Comment by fei2020** [comment]
I use Python3.7 to install on Windows10:

```
C:\>pip install taichi-nightly
ERROR: Could not find a version that satisfies the requirement taichi-nightly (from versions: none)
ERROR: No matching distribution found for taichi-nightly
```


I
