### ISSUE TITLE
Add require_version configuration in ti.init()

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#3847]
There is a legacy `require_version` function in Taichi:
https://github.com/taichi-dev/taichi/blob/7bae9c77f69e4215e809ee6ddcfeb9f45c724842/python/taichi/_lib/utils.py#L127-L139
This is not exposed to users anymore, which breaks the following code in the *taichi_elements* project: https://github.com/taichi-dev/taichi_elements/blob/818b88ef2e65bec474f19b156f49dba3727aa108/engine/mpm_solver.py#L10

In normal Python projects, versions of dependencies are ensured with `requirements.txt`. However, many existing Taichi programs are standalone files. To give these programs an opportunity to set version requirements, we hope to move the functionality of `require_version` into `ti.init()` by adding a `require_version` configuration. After having this configuration, the broken usage of `require_version` in the *taichi_elements* project needs to be fixed accordingly.

**Comment by tczhangzhi** [comment]
This sounds reasonable and I'd like to be assigned to this issue!

**Comment by tczhangzhi** [comment]
My only concern is to remain the old fashion API after modifying `ti.init()`, otherwise it would be a breaking change and we should note it in the document?

**Comment by strongoier** [comment]
Thanks for your interest in this issue! I have assigned it to you.

Regarding your concern, we hope to keep a stable set of APIs starting from Taichi v1.0 and we are on our way to pick that set. In this process, there must be some breaking changes and we will explicitly state them in our future release notes.

**Comment by ailzhang** [comment]
Closing via #4151
