### ISSUE TITLE
Is ti possible to do a second derivative?

### ISSUE THREAD

**Issue by shaiay** [taichi-dev/taichi#385]
Form many problems, having the Hessian and using a Newton-Raphson solver will greatly decrease the number of iterations needed to converge.

Is it possible to to auto Hessian calculations, mush like the auto gradient calculation now available?

Thanks,
Shai

**Comment by yuanming-hu** [comment]
Hi @shaiay 

In the current version, not yet. We plan to add this feature, but this will not happen very soon (i.e. within 2020)...

**Comment by MarisaKirisame** [comment]
Hi, I am confused. If taichi do automatic differentiation via source code transformation, cant you simply take the resulting source code and feed it in the automatic differentiation algorithm again?
