### ISSUE TITLE
AttributeError: module 'taichi' has no attribute 'complex_kernel'

### ISSUE THREAD

**Issue by YunchuZhang** [taichi-dev/taichi#3851]
As title, I search the issue and it show the complex_kernel  was changed to'grad_replaced' as mentioned here:
[https://github.com/taichi-dev/taichi/pull/3035]. But it still does not have the attribute.

I am in version 0.8.8 and llvm 10.0.0 python 3.6.13

**Comment by ailzhang** [comment]
@YunchuZhang Hey thanks! This API lives at `ti.ad.grad_replaced` :P Let us know if that works for you!

**Comment by YunchuZhang** [comment]
thanks

**Comment by EricCousineau-TRI** [comment]
for those wondering, it was removed in 07d8193188

found via:
```
$ cd taichi
$ git log -S'complex_kernel'
```
