### ISSUE TITLE
IfStmt simplification did not handle AtomicOp correctly?

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#387]
**Describe the bug**

I think there is a bug when simplifying `IfStmt`, around how it handles atomics. See the screenshots below when running `renderer.py` for a difference.

If I disable the simplification when there is an `AtomicOp` inside `IfStmt`, the bug gets resolved.

I.e., change [this line in `simplify.cpp`](https://github.com/taichi-dev/taichi/blob/0726d495c92c30568e3055ba688294e42808a624/taichi/transforms/simplify.cpp#L805) from

```cpp
  if (is_global_write(clause[i].get()) ||
```

to

```cpp
  if (clause[i]->is<GlobalStoreStmt>() ||
```

I'm running the CPU version on `macOS Catalina 10.15.2`.

**Log/Screenshots**

This is the result I got when running the renderer example on the head release `0.3.21` or the master branch 0726d495c92c30568e3055ba688294e42808a624:

<img width="1280" alt="Screen Shot 2020-01-15 at 22 28 12" src="https://user-images.githubusercontent.com/7481356/72437912-19ea9b00-37e7-11ea-9943-949095646275.png">

And if I patch in the fix, the rendered result will show the taichi logo

<img width="1281" alt="Screen Shot 2020-01-15 at 22 29 06" src="https://user-images.githubusercontent.com/7481356/72438027-58805580-37e7-11ea-8d42-d0ad5a50c227.png">

**To Reproduce**

`python examples/renderer.py`

**Comment by yuanming-hu** [comment]
Refactoring `simplify.cpp` to fix this and make the correctness more trivial...

**Comment by yuanming-hu** [comment]
The minimal script to reproduce this issue:
```python
@ti.all_archs
def test_local_atomic_with_if():
  ret = ti.var(dt=ti.i32, shape=())
  ti.cfg.print_ir = True

  @ti.kernel
  def test():
    if True:
      x = 0
      x += 1
      ret[None] = x

  test()
  assert ret[None] == 1
```

**Comment by yuanming-hu** [comment]
Fixed for now by adding https://github.com/taichi-dev/taichi/blob/b34fc92a9d2de5053235ac92c20fd3e7101eea21/taichi/transforms/simplify.cpp#L814
in `is_atomic_value_used`. Will take a deeper look into the whole `simplify.cpp` file tomorrow to figure out more systematic solutions. Releasing v0.3.22 with these improvements. Thanks!

**Comment by yuanming-hu** [comment]
Since no related issues have been raised about the simplified pass, I assume `simplify.cpp` works with no problem...
