### ISSUE TITLE
(Long term speaking, will Taichi replace numpy or be used with numpy together?) Taichi未来会取代numpy还是打算和numpy长期混用?

### ISSUE THREAD

**Issue by stamnug** [taichi-dev/taichi#3882]
Taichi未来会取代numpy还是打算和numpy长期混用?

**Comment by k-ye** [comment]
There's no plan for Taichi to replace Numpy. Numpy's has a great ecosystem, so Taichi does provide a pair of convenient interfaces to convert Taichi fields to/from numpy arrays. 

(Note that we do keep an English-only environment on Github. For other languages, you can file an issue in the forum instead https://forum.taichi.graphics/ :-) )
