### ISSUE TITLE
Add per_vertex_radius for GGUI particles

### ISSUE THREAD

**Issue by CitrusDusk** [taichi-dev/taichi#3888]
When drawing particles in a 3D scene using the GGUI system:

`scene.particles(vertices, radius, color, per_vertex_color)`,

currently, it can only draw a group of particles with the same radius, but I want to draw a bunch of particles where each particle has a different radius.

I wish a `per_vertex_radius` parameter could be added so that we can specify the radius for each individual particle (like how we can set the color for each particle using `per_vertex_color`).

**Comment by qiao-bo** [comment]
CC @AmesingFlank

**Comment by AmesingFlank** [comment]
This sounds a like reasonable and useful feature to have. I will try to find some time to add it, and I'd also be happy to review if someone else from the open source community wants to give it a try.

**Comment by Bl00per72** [comment]
I'd like to be assigned to this issue if possible.

**Comment by AmesingFlank** [comment]
> I'd like to be assigned to this issue, if possible.

Sure.

**Comment by Bl00per72** [comment]
Thanks! @AmesingFlank

**Comment by Bl00per72** [comment]
I'm having trouble finding the file in which this code is located. Could you let me know where I should start working? Much appreciated! @AmesingFlank

**Comment by Bl00per72** [comment]
@AmesingFlank I just got around to taking a look at the issue, but I'm not too familiar with the code base and this is my first time contributing to an open source project. So far, I've taken a look at scene.py, where the code for creating particles is, and that led me to take a look at staging_buffer.py, where the utilized functions in particles() are imported from. I understand the structure, but I am not familiar with the concept behind the code. Would you be able to provide me with some guidance on how to approach this problem? It would be greatly appreciated as I would like to provide a solution!

**Comment by AmesingFlank** [comment]
@Bl00per72  Hey! Glad to know that you're getting started and making progress. Here're some suggestions.

Firstly, you'll need modify the vertex shader for rendering particles. (If you aren't familiar with shaders, have a look at this [link](https://learnopengl.com/Getting-started/Shaders)). In taichi, the vertex shader for particles are at 
https://github.com/taichi-dev/taichi/blob/master/python/taichi/shaders/Particles_vk.vert
Notice how the `radius` property is in a `uniform` block. This means the radius is uniform across all vertices. To enable `per_vertex_radius`, you'll need to define and retrieve radius as a vertex attribute. Luckily, we have the `texcoord` attribute, which is not used by particles at all, I suggest that we just use `texcoord` to pass in radius data. This is a little bit hacky, but it saves you a lot of work (and it saves a bit of memory as well). 

You'll need to modify the following things:
1. Modify the vertex shader. Add an additional uniform input that informs the shader whether or not the `per_vertex_radius` data is provided. Let's call it `has_per_vertex_radius`. If this is true, then use `in_texcoord.x` as the radius.
2. Modify https://github.com/taichi-dev/taichi/blob/master/taichi/ui/common/scene_base.h to also include the `has_per_vertex_radius` property. 
3. In Python side, if `per_vertex_radius` is specified as true by the user, then use `staging_buffer.py` to store the data inside the tex_coords component. Then, you need to pass `has_per_vertex_radius=True` to C++ and then to the shader. This is a bit too complicated to be elaborated here, I suggest you try and understand how the other properties of `ParticlesInfo` are passed from Python -> C++ -> Shader.

I hope this helps. And good luck!

**Comment by Bl00per72** [comment]
Thanks! @AmesingFlank This helps a lot. I'll keep you updated on my work.

**Comment by Bl00per72** [comment]
Quick question: how do you open .vert files? I'm trying to open it in a Spyder IDE, but it's not showing up. @AmesingFlank

**Comment by Bl00per72** [comment]
@AmesingFlank All done with my edits. Is there anything else I need to do before I file a pull request?

**Comment by Bl00per72** [comment]
@AmesingFlank All done with my edits! Filing a PR now.

**Comment by bobcao3** [comment]
Moving to #6999
