### ISSUE TITLE
Unstable Frame Rate

### ISSUE THREAD

**Issue by NPC2048** [taichi-dev/taichi#389]
在控制台发现
[Taichi version 0.3.21, cpu only, commit 8f36125f]

指定 ti.cfg.arch = ti.cuda
也还是 cpu only, 不知道这是我使用问题还是提示信息没有改还是bug?

**Comment by k-ye** [comment]
Several things I could think of.

1. What's your OS? [The doc]((https://taichi.readthedocs.io/en/latest/hello.html)) says that CUDA is only supported on Linux. And if your OS doesn't have CUDA, taichi will fall back to CPU.
1. Another thing to check is that you need to install either `taichi-nightly-cuda-10-0` or `taichi-nightly-cuda-10-1`, not `taichi-nightly`.

**Comment by Psycho7** [comment]
I also found this issue (now sure, as I'm new to taichi).

Ran [fractal.py](https://taichi.readthedocs.io/en/latest/hello.html) on windows 10, at first the frame rate was alright but after few minutes (2 or 3) FPS dropped to around 40 and the screen got stuck.
Not sure if it's desired behavior or not.

**Comment by yuanming-hu** [comment]
v0.4.2 has an update (https://github.com/taichi-dev/taichi/commit/ead173f1f1d6269a5a45feb96924feef36b73ea9) that might have improved frame rate stableness. Please have a try if you are still interested in this issue. Thanks.
