### ISSUE TITLE
Initial matrix type argument support for @ti.kernel

### ISSUE THREAD

**Issue by mzmzm** [taichi-dev/taichi#3904]
**Concisely describe the proposed feature**
We should support that  `ti.Matrix` and `ti.Vector` can be arguments in `@ti.kernel`.  If we can do this, we provide coder with a convenient way to work with `Matrix` and `Vector`.

**Describe the solution you'd like (if any)**
Currently, `ti.kernel` doesn't support `ti.Matrix` or `ti.Vector` as its argument to pass.
Maybe we can pass a copy of this variable (pass-by-value) from Python-scope to Taichi-scope.

Because the Taichi AST haven't support `Matrix` or `Vector` yet, we need take some tricks to solve this problem.
We can use some scalar variables to take the place of matrix, instead of putting the value of argument as constant to compile which is just like in `@ti.func`. Putting the value as constant will result in re-compile when every time you call the kernel function.

Example:
```python3
@ti.kernel
def foo(mat: ti.types.matrix(2, 2, ti.i32)):
    for i in ti.static(range(2)):
        for j in ti.static(range(2)):
            mat[i, j] += mat[i, j]
```
convert to IR
```
kernel {
  $0 = alloca @tmp0
  $1 = alloca @tmp1
  $2 = alloca @tmp2
  $3 = alloca @tmp3
  @tmp0 = arg[0] (dt=i32)
  @tmp1 = arg[1] (dt=i32)
  @tmp2 = arg[2] (dt=i32)
  @tmp3 = arg[3] (dt=i32)
  $8 = alloca @tmp4
  @tmp4 = atomic_add(@tmp0, @tmp0)
  $10 = alloca @tmp5
  @tmp5 = atomic_add(@tmp1, @tmp1)
  $12 = alloca @tmp6
  @tmp6 = atomic_add(@tmp2, @tmp2)
  $14 = alloca @tmp7
  @tmp7 = atomic_add(@tmp3, @tmp3)
}

```

**Comment by strongoier** [comment]
Close via #3905
