### ISSUE TITLE
python 3.10 support?

### ISSUE THREAD

**Issue by PumpkinCheshire** [taichi-dev/taichi#3936]
Hi, thanks for your brilliant work.

May I ask is there any plan to add python 3.10 support?

**Comment by k-ye** [comment]
Hi @PumpkinCheshire , if possible, would you try the developer installation (https://docs.taichi.graphics/lang/articles/contribution/dev_install) and see what kind of errors you get when running 3.10 :-) It would help us move things faster, thanks!

**Comment by qiao-bo** [comment]
Hi, we have just released Taichi v0.9.2 with python 3.10 support. Feel free to try it out!
