### ISSUE TITLE
Build on MSVC failed because of C4819

### ISSUE THREAD

**Issue by PGZXB** [taichi-dev/taichi#3937]
Build on MSVC failed. Fail in the step [Build taichi from source](https://docs.taichi.graphics/lang/articles/contribution/dev_install#build-taichi-from-source)(select windows).

### Environment
* Compiler version : VS2022 17.0.0
* Operating system : Windows 10 20H2

### Reproduce steps
* Refer to [Developer installation | Taichi Docs](https://docs.taichi.graphics/lang/articles/contribution/dev_install). Fail in the step [Build taichi from source](https://docs.taichi.graphics/lang/articles/contribution/dev_install#build-taichi-from-source)(select windows).

### Build error
When building extension [SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools), error : 
```shell
Building CXX object external\SPIRV-Tools\...PIRV-Tools-static.dir\val\validate_image.cpp.obj
FAILED: external/SPIRV-Tools/source/CMakeFiles/SPIRV-Tools-static.dir/val/validate_image.cpp.obj
D:\programming_tools_\VS2022\Community\VC\Tools\MSVC\14.30.30705\bin\Hostx64\x64\cl.exe  /nologo /TP -DSPIRV_COLOR_TERMINAL -DSPIRV_WINDOWS -ID:\programming_tools_\Anaconda\include -IC:\Users\42025\AppData\Roaming\Python\Python37\site-packages\numpy\core\include -IC:\Users\42025\AppData\Roaming\Python\Python37\site-packages\pybind11\include -ID:\CODE\Taichi-Infra-MyWorkspace\taichi -ID:\CODE\Taichi-Infra-MyWorkspace\taichi\external\include -ID:\CODE\Taichi-Infra-MyWorkspace\taichi\external\spdlog\include -ID:\programming_tools_\taichi-llvm-10.0.0-msvc2019\include -ID:\CODE\Taichi-Infra-MyWorkspace\taichi\external\SPIRV-Tools -ID:\CODE\Taichi-Infra-MyWorkspace\taichi\external\SPIRV-Tools\include -ID:\CODE\Taichi-Infra-MyWorkspace\taichi\build\external\SPIRV-Tools -ID:\CODE\Taichi-Infra-MyWorkspace\taichi\external\SPIRV-Headers\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc -DTI_ISE_NONE /Zc:__cplusplus /std:c++17 /bigobj /wd4244 /wd4267 /nologo /Zi /D "_CRT_SECURE_NO_WARNINGS" /D "_ENABLE_EXTENDED_ALIGNED_STORAGE" /D "TI_ARCH_x64" -DTI_PASS_EXCEPTION_TO_PYTHON -DTI_INCLUDED -DTI_WITH_LLVM -DTI_WITH_CUDA -DTI_WITH_METAL -DTI_WITH_OPENGL /MD /O2 /Ob2 /DNDEBUG   -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DUNICODE -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS /MP4 -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS /wd4800 /WX /EHs /showIncludes /Foexternal\SPIRV-Tools\source\CMakeFiles\SPIRV-Tools-static.dir\val\validate_image.cpp.obj /Fdexternal\SPIRV-Tools\source\CMakeFiles\SPIRV-Tools-static.dir\SPIRV-Tools-static.pdb /FS -c D:\CODE\Taichi-Infra-MyWorkspace\taichi\external\SPIRV-Tools\source\val\validate_image.cpp
D:\CODE\Taichi-Infra-MyWorkspace\taichi\external\SPIRV-Tools\source\val\validate_image.cpp(1529): error C2220: the following warning is treated as an error
D:\CODE\Taichi-Infra-MyWorkspace\taichi\external\SPIRV-Tools\source\val\validate_image.cpp(1529): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
```
We can see the [warning C4819](https://docs.microsoft.com/zh-cn/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4819?view=msvc-170) when compiling [validate_image.cpp](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/val/validate_image.cpp). The [C4819](https://docs.microsoft.com/zh-cn/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4819?view=msvc-170) is why taichi built failed. After I insert ```#pragma warning(disable: 4819)``` into the beginning of [validate_image.cpp](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/val/validate_image.cpp), building is successful.
I don't know the reason of appearance of the warning. At first, I thought that it is the problem of third-party [SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools). But I clone the third-party and build it using VS2022. Successful! **WHY?!**

**Comment by k-ye** [comment]
Hmm, could you try the exact commit of SPIRV-Tools at https://github.com/KhronosGroup/SPIRV-Tools/tree/b46995741b97c714e211fe5df8590991ae998475? We probably need to upgrade this repo, if necessary @bobcao3

**Comment by PGZXB** [comment]
> Hmm, could you try the exact commit of SPIRV-Tools at https://github.com/KhronosGroup/SPIRV-Tools/tree/b46995741b97c714e211fe5df8590991ae998475? We probably need to upgrade this repo, if necessary @bobcao3

I try build the the exact commit of SPIRV-Tools at https://github.com/KhronosGroup/SPIRV-Tools/tree/b46995741b97c714e211fe5df8590991ae998475. **Fail in error C4819.** After I insert #pragma warning(disable: 4819) into the beginning of validate_image.cpp, building is successful.

YES! This repo should be upgraded.

**Comment by k-ye** [comment]
Thanks. Would you like to help submit a PR for this upgrade :-) ?

**Comment by PGZXB** [comment]
@k-ye What tag should I use in the PR for this upgrade?

**Comment by strongoier** [comment]
I suggest using `[build]`.
