### ISSUE TITLE
Linking got slower on my m1 mac 

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#3939]
Building from source spent a lot time at `Linking CXX shared library libtaichi_core.dylib` (more than 2min) and I'm pretty sure it was only a few secs before. 

We'll need to further investigate this regression but I'll leave this issue here first.

**Comment by turbo0628** [comment]
Also true for Intel Mac w/ clang-11 and llvm 10.0.0 (conda version).

Linux with similar CPU works fine. The dylib on mac is only slightly fatter than Linux version (71MB vs 53MB).

We can look into this some time later.
