### ISSUE TITLE
[ci] Support more comment commands for CI bot

### ISSUE THREAD

**Issue by frostming** [taichi-dev/taichi#3950]
**Concisely describe the proposed feature**

- [x] `/format`: Format code
- [x] `/benchmark`: Run benchmark suite
- [x] `/rebase`: Rebase the current branch
- [x] `/rerun`: Rerun last failed run
- [x] automatically adding the PR to the project based on its tag in the PR title

Please add more items to the list

**Comment by ailzhang** [comment]
Just thought of another super useful command would be "automatically adding the PR to the project based on its tag in the PR title" :P cc: @k-ye @rexwangcc

**Comment by frostming** [comment]
@ailzhang what is the behavior when the user changes the PR title (with possible tag changes)? Should we move the card to the correct board?

**Comment by ailzhang** [comment]
@frostming yea that'll be perfect! (we're also fine with not changing for now if it's too hard to implement ;)
