### ISSUE TITLE
more lagre dependency version range

### ISSUE THREAD

**Issue by rayfalling** [taichi-dev/taichi#398]
**Is your feature request related to a problem? Please describe.**
well, I found the dependency version range is low than my package manager provided. so, if i can update the dependency version range? 
In cmake file request clang version 8.0 but my installed version is 9.0.1, so can you only set the minimum version, not specify the only one version.
I need python 3.8 package :)

**Describe the solution you'd like**
update cmake file to enable large dependency version range.

**Comment by yuanming-hu** [comment]
It seems that you are using pretty new packages :-)
Taichi is built with llvm 8.0.1, and we don't plan to upgrade to llvm 9.0.0 within 6 months.

However, any clang with version 6+ should be supported. Does CMake complain anything about your clang version?

Regarding Python 3.8, let's track that in this issue: https://github.com/taichi-dev/taichi/issues/400

**Comment by wanghaiwei** [comment]
well, my llvm version is 9.0.1 :(
i'll try to build with llvm 9.0
