### ISSUE TITLE
Modify the shape of the ndarray returned by field.to_numpy() method

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#3997]
The shape of the `numpy.ndarray` returned by `field.to_numpy()` method is `(width, height)`, which has `width` rows and `height` columns. This is the transposed version of the usual convention. Shall we do this transpose internally so that the returned shape is `(height, width)`?

For example:

```python
import taichi as ti
ti.init(arch=ti.cpu)
import matplotlib.pyplot as plt

resolution = (400, 200)  # image width, image height
x = ti.Vector.field(3, ti.f32, shape=resolution)
x.fill(0)

arr = x.to_numpy()
print(arr.shape)
plt.imshow(arr)
plt.show()
```
shows the following image, which is the transposition of the intended image:

![Figure_1](https://user-images.githubusercontent.com/23307174/149057613-4df280d3-a104-495e-9756-db1106223c48.png)

**Comment by ailzhang** [comment]
@neozhaoliang would you mind showing a small example code for this?

**Comment by neozhaoliang** [comment]
@ailzhang  Example code and image are added.

**Comment by ifsheldon** [comment]
The "usual convention" you said is not a usual convention in linear algebra. The dimension convention for images happens to be the transposed generic 2D matrix. For general linear algebra use cases, the first dimension of a matrix (generally a tensor) is just the first dimension and nothing else. Even if you see the convention in CV applications of PyTorch, it's not like what you usually expect to represent images.
