### ISSUE TITLE
[llvm] build without llvm option fails

### ISSUE THREAD

**Issue by xwang186** [taichi-dev/taichi#3999]
**Building option -DTI_WITH_LLVM:BOOL=OFF is broken**
Due to some recent changes, this option raises build errors. At this moment, ndarray and JITSession are using "LlvmProgramImpl", which will raise not defined error in the latest build system.

**Comment by qiao-bo** [comment]
Hi, thanks, we will take a look at this.

**Comment by k-ye** [comment]
Is there any specific reason you need to turn off LLVM? Unfortunately, I don't think Taichi is at a state that can be built easily without LLVM at all..

**Comment by xwang186** [comment]
> Is there any specific reason you need to turn off LLVM? Unfortunately, I don't think Taichi is at a state that can be built easily without LLVM at all..
Taichi supports this feature since November.
And also, I am currently exporting Taichi core for external use, which currently needs to disable llvm to avoid crash.

**Comment by k-ye** [comment]
I see. Out of curiosity, is it possible to share the crash errors, if any?

**Comment by xwang186** [comment]
> I see. Out of curiosity, is it possible to share the crash errors, if any?

I am actually on the AOT thread. Related issues: #3704  #3702 #3507 #3679

My building command:
`TAICHI_CMAKE_ARGS="-DTI_WITH_VULKAN:BOOL=ON -DTI_WITH_CUDA:BOOL=ON -DTI_WITH_OPENGL:BOOL=ON -DTI_EXPORT_CORE:BOOL=ON" python3 setup.py install --user`

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3167700 (LWP 338033)]
: CommandLine Error: Option 'help-list' registered more than once!

Disable llvm can always solve this issue.

**Comment by ailzhang** [comment]
@PGZXB would you mind help fixing the build with `TAICHI_CMAKE_ARGS="-DTI_WITH_VULKAN:BOOL=ON -DTI_WITH_CUDA:BOOL=ON -DTI_WITH_OPENGL:BOOL=ON -DTI_EXPORT_CORE:BOOL=ON" python3 setup.py install --user` ? ;) Thanks!

**Comment by PGZXB** [comment]
@xwang186  Hi. Could you tell me which commit did you successfully build with  ` -DTI_WITH_LLVM:BOOL=OFF`?

**Comment by xwang186** [comment]
@PGZXB 
7bae9c77f69e4215e809ee6ddcfeb9f45c724842 <- this works for me with LLVM OFF.

**Comment by PGZXB** [comment]
> @PGZXB [7bae9c7](https://github.com/taichi-dev/taichi/commit/7bae9c77f69e4215e809ee6ddcfeb9f45c724842) <- this works for me with LLVM OFF.

Are you sure you built successfully with `-DTI_WITH_LLVM:BOOL=OFF`?
I try on https://github.com/taichi-dev/taichi/commit/7bae9c77f69e4215e809ee6ddcfeb9f45c724842. But I get error : 
```shell
ndarray.h:57:3: error: unknown type name 'LlvmProgramImpl'; did you mean 'ProgramImpl'?
  LlvmProgramImpl *prog_impl_{nullptr};
  ^~~~~~~~~~~~~~~
  ProgramImpl
```

**Comment by PGZXB** [comment]
> @PGZXB [7bae9c7](https://github.com/taichi-dev/taichi/commit/7bae9c77f69e4215e809ee6ddcfeb9f45c724842) <- this works for me with LLVM OFF.

I solved this problem by using simple and direct solution. You can try build latest commit again after my PR #4043 is merged. However, I agree https://github.com/taichi-dev/taichi/issues/3999#issuecomment-1010536736. We don't think Taichi is at a state that can be built easily without LLVM at all. Currently, the `-DTI_WITH_LLVM=OFF` doesn't mean that Taichi will be built without using LLVM at all. Fixing the problem completely in the future version is that we will consider.

**Comment by xwang186** [comment]
@PGZXB Thanks a lot. I manually tested on your change, and yes no build error on LLVM:OFF.
I see that somehow llvm is not totally ignored but I think your commit makes pretty much sense on what we need at this moment!
