### ISSUE TITLE
[Discussion] Should we drop support for Python 3.5?

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#402]
Currently, Taichi supports Python 3.5 yet users have to build from source.

It seems to me that people who are asking for supporting Python 3.8 are more than those for Python 3.5. 

So I'm considering dropping Python 3.5 support and then we can embrace some new language features in Python 3.6, such as f-strings.

What do you guys think? Inputs are welcome :-)

**Comment by Psycho7** [comment]
Agree. I'd like to share my 2 cents here.

Python 3.5 was out when Python 2 was still prevailing, but as Python 2 doesn't update anymore people are turning to Python 3, and most likely the latest version. No wonder why more are asking for Python 3.8 than 3.5.
Besides, it's better for Taichi to adopt new language features at its early stage.

**Comment by yuanming-hu** [comment]
Thanks. I agree with your opinions. Let's keep this thread here for one week and if no one objects we'll drop Python 3.5 support.

**Comment by yuanming-hu** [comment]
Since there's no objection, we will drop Python 3.5 support.
