### ISSUE TITLE
Support multiple snode trees on opengl backend

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#4040]
Hi, I have a script runs correctly with `arch=cpu` and `arch=cuda` but fails with `arch=opengl`. The code may be too long to be posted here, the error message is quite short:

```
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 715, in wrapped
    return primal(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 644, in __call__
    return self.compiled_functions[key](*args)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 595, in func__
    t_kernel(launch_ctx)
IndexError: _Map_base::at
```
No hints what it's about. Any suggestions?

**Comment by ailzhang** [comment]
@neozhaoliang would you mind adding a minimal repro script so that I can take a look? Thanks!

**Comment by ailzhang** [comment]
FYI a minimal repro for this issue is 
```
import taichi as ti
import numpy as np

ti.init(arch=ti.cuda, print_ir=False)

resolution = (800, 600)
pixels = ti.Vector.field(3, ti.f32, shape=resolution)

H, W = 800, 800

image = np.random.rand(W, H, 3)
woodTex = ti.Vector.field(3, ti.f32, shape=(W, H))
woodTex.from_numpy(image)

skyboxTex = ti.Vector.field(3, ti.f32, shape=(W, H))

if __name__ == "__main__":
    print(pixels)
```
And the root cause here is calling `from_numpy`(a taichi kernel) triggers snodetree finalization so we have multiple snode trees in this program. But multi snode trees are only supported on LLVM-based backends for now.
