### ISSUE TITLE
I can't install taichi by pip

### ISSUE THREAD

**Issue by fei2020** [taichi-dev/taichi#405]
**Describe the bug**
I can't install taichi by pip

**Log/Screenshots**
```
C:\Users\work>pip install taichi-nightly
ERROR: Could not find a version that satisfies the requirement taichi-nightly (from versions: none)
ERROR: No matching distribution found for taichi-nightly

C:\Users\work>pip3 install -i https://pypi.org/project/ taichi-nightly
Looking in indexes: https://pypi.org/project/
ERROR: Could not find a version that satisfies the requirement taichi-nightly (from versions: none)
ERROR: No matching distribution found for taichi-nightly

C:\Users\work>pip3 install -i https://pypi.org/project/ taichi-nightly==0.3.9
Looking in indexes: https://pypi.org/project/
ERROR: Could not find a version that satisfies the requirement taichi-nightly==0.3.9 (from versions: none)
ERROR: No matching distribution found for taichi-nightly==0.3.9

C:\Users\work>pip install -i https://pypi.tuna.tsinghua.edu.cn/simple taichi-nightly
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement taichi-nightly (from versions: none)
ERROR: No matching distribution found for taichi-nightly

C:\Users\work>pip install -i https://pypi.tuna.tsinghua.edu.cn/simple taichi-nightly==0.3.9
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement taichi-nightly==0.3.9 (from versions: none)
ERROR: No matching distribution found for taichi-nightly==0.3.9
```

**Comment by yuanming-hu** [comment]
Hi, could you please let me know your OS?

**Comment by jiujiangxueyuan** [comment]
The OS should be Windows by file directory.

**Comment by Erhannis** [comment]
I, too, have this problem.
Windows 10 Enterprise
Python 3.7.4
Pip 20.0.2

**Comment by yuanming-hu** [comment]
This is weird. Are you guys using Windows with ARM or 32bit CPUs?

**Comment by alex-shortt** [comment]
Getting the same issue on Mac 10.14.6 with python 3.6.8 and pip 20.0.2

**Comment by yuanming-hu** [comment]
@alex-shortt python3.6 on OS X is not supported. Please use Python3.7 (or contribute to https://github.com/taichi-dev/taichi/issues/409 so that Taichi with 3.6/3.8 will be built as well.)

**Comment by Erhannis** [comment]
Nope; x64

**Comment by Erhannis** [comment]
Ahhh, wait.  My OS is 64-bit, but my python i s 32-bit.  I suspect that's my problem.

**Comment by yuanming-hu** [comment]
@Erhannis Yeah only 64-bit python is supported.

**Comment by bluevisor** [comment]
I have the same problem on macOS 10.15.3, Python 3.8.1

$ python3 -m pip install taichi-nightly
ERROR: Could not find a version that satisfies the requirement taichi-nightly (from versions: none)
ERROR: No matching distribution found for taichi-nightly

**Comment by yuanming-hu** [comment]
@bluevisor please see https://github.com/taichi-dev/taichi/issues/409

**Comment by Eason-zz** [comment]
> I, too, have this problem.
> Windows 10 Enterprise
> Python 3.7.4
> Pip 20.0.2

me，too

**Comment by pancymon** [comment]
I just found that if you are on a windows platform and if you install python from windows store, it installs python 32 bit by default. You have to install [python 64 bit](https://www.python.org/ftp/python/3.8.7/python-3.8.7-amd64.exe) manually and add it to your system path, than you can install taichi.

**Comment by starInEcust** [comment]
@jim6677 I'm having the same problem in both macos(11.6, python3.6) and window 11(python3.10)

**Comment by Viranchee** [comment]
I am having the same problem Macos 13.2.1 python 3.6 
Machine: Macbook Air M1

**Comment by Terraform05** [comment]
I am having the same problem - MacOS Ventura 13.3.1 - Python 3.11.3 - Macbook Air M2

**Comment by feisuzhu** [comment]
@Terraform05

Python 3.11 will be supported at v1.6.0, for now please use a lower Python version (3.10 is ok)

@Viranchee 

Please use at lease Python 3.7 for M1.
