### ISSUE TITLE
Incorporating surface tension into MLS-MPM

### ISSUE THREAD

**Issue by RussellZhangYo** [taichi-dev/taichi#4072]
I would like to ask if it is possible to incorporate surface tension of fluids into MLS-MPM.

**Comment by erizmr** [comment]
Hi, I think the paper below may provide some insights:
https://cs.dartmouth.edu/~bozhu/papers/codimensional_mls_particle.pdf

**Comment by qiao-bo** [comment]
Hi, would you mind close this issue if your question has been answered?  thanks

**Comment by RussellZhangYo** [comment]
Thank you！
