### ISSUE TITLE
Docker build is broken due to PPA removed

### ISSUE THREAD

**Issue by jackalcooper** [taichi-dev/taichi#408]
**Describe the bug**
The ppa used in Dockerfile is no longer available. This breaks the docker build.
News: [Jonath F. removed ppas](https://www.reddit.com/r/linux/comments/eamh3n/jonathon_f_removed_his_popular_ppas_from_public/)

**Log/Screenshots**
```
...
Reading package lists...
W: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y     build-essential     python3.6     python3.6-dev     python3-pip     python3.6-venv     git     cmake     libtinfo-dev     wget     libx11-dev     libsm6     libxext6     libxrender-dev     zlib1g-dev     xz-utils     curl     libomp5     libomp-dev' returned a non-zero code: 100
```
**To Reproduce**
build with dockerfile

**Comment by yuanming-hu** [comment]
Oh no... The Dockerfile has not been updated for a while and I believe it will run into more problems than this one. The Jenkinsfile (https://github.com/taichi-dev/taichi/blob/master/Jenkinsfile#L119) can be used as a reference to fix it.

**Comment by jackalcooper** [comment]
glad to help. I managed to build the .so but I am not sure what to do next.
[dockerfile](https://github.com/taichi-dev/taichi/pull/410/files)

**Comment by yuanming-hu** [comment]
Great! You can add `/app/taichi/bin` to `PATH` and then execute
```
ti test
```
to run all the unit tests.

**Comment by jackalcooper** [comment]
Discussion moved to [this PR](https://github.com/taichi-dev/taichi/pull/410).
