### ISSUE TITLE
More explanation on extensions of backends

### ISSUE THREAD

**Issue by ifsheldon** [taichi-dev/taichi#4083]
In the documentation `Taichi Language Basic Concepts/Type System/Supported premitive types on each backend`, `f64` support on the Vulkan backend is marked as "Requiring extensions of the backend". But I don't know what you mean by "extensions of the backend". I found `ti.extension.data64`, but I'm not sure whether it is the correct extension nor do I know how to enable this extension except `ti.test(require=ti.extension.data64)`. "extension" could mean vulkan extensions or `ti.extension`, but I don't know which one it is

## More Context
I need to use `f64` with vulkan backend but when I try to run my program, it gives me this error
```
RuntimeError: [kernel_utils.cpp:KernelContextAttributes@59] SPIRV kernel only supports less than 32-bit arguments, got f64
```

**Comment by ifsheldon** [comment]
Can I somehow get rid of this limitation? I think my RTX8000 can support 64bit data on Vulkan. I think maybe you can write a small function to detect whether a device support 64bit data on Vulkan. And if not, give a better error message like "GPU not support 64bit data on Vulkan"

**Comment by k-ye** [comment]
Yeah, @bobcao3 @g1n0st could you help take a look some time?

**Comment by bobcao3** [comment]
f64 should be properly supported now in Vulkan.
