### ISSUE TITLE
[Vulkan] Memory leak is observed only on vulkan backend

### ISSUE THREAD

**Issue by xwang186** [taichi-dev/taichi#4088]
**Vulkan backend has memory leak**
After comparing different backends in example mpm88.py, I think vulkan backends has memory leak during execution. At head (9643518d59e05a0030b6e1a1614d9bb06091318a)

**To Reproduce**
First, compile taichi source codes to support opengl, cuda, (as compare) and vulkan.
My build command for example:
 TAICHI_CMAKE_ARGS="-DTI_WITH_VULKAN:BOOL=ON -DTI_WITH_CUDA:BOOL=ON -DTI_WITH_OPENGL:BOOL=ON" python3 setup.py install --user

Go to file python/taichi/examples/simulation/mpm88.py,
we can change the backend type at 
ti.init(arch=ti.gpu), to ti.init(arch=ti.vulkan), ti.init(arch=ti.opengl) ti.init(arch=ti.cuda)
Then when you run that script, you can observe the memory usage by some system tools.
I am under linux desktop for example, using "System Monitor", you can check the memory usage of a "python3" process.

**Screenshots**
Under Vulkan backend:
Screenshot right after running:
![image](https://user-images.githubusercontent.com/39249169/150613163-3d5dc225-5726-4a6a-a9ec-e03bc01e351a.png)
After several seconds running:
![image](https://user-images.githubusercontent.com/39249169/150613246-fdc3bd79-d6e3-435c-8254-ceec175018d9.png)
And will keep increasing before exit.

Under other backends like(cuda, opengl), the memory usage is always quite stable.

**Additional Info**
I detect this issue while measuring CPU execution time for vulkan backend, using exported taichi core binary. Then I verified that python frontend has this issue as well. Thus, I think the issue is that taichi/backend/vulkan has memory leak somewhere. Will keep it updated if I have more observations.

**Comment by bobcao3** [comment]
This has been fixed
