### ISSUE TITLE
[Travis CI] Build Taichi on OS X with Python 3.6 and 3.8

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#409]
Currently, Travis only builds Taichi on OS X with Python 3.7, the default Python with OS X 10.14.

I tried to add Python 3.6 & 3.8 to Travis for our OS X releases yet had no success. If someone familiar with OS X/Travis can help with [this](https://github.com/taichi-dev/taichi/blob/master/.travis.yml) file, that's greatly appreciated!

My failure attempts: 4093c67fec14a3fa223e95afbf182fea8a10d6d6 8650dce048726a77b5d7f718a0bbb2a01a51ede9 57115356b04cca7bb98d7dd3ab809296ee431774 8481bb08492c56839a197009c784c3f42efd527e

This issue is installing Python 3.6/3.8 in a C++ Travis OS X project seems tricky.

**Comment by yuanming-hu** [comment]
This issue is resolved thanks to the great contribution of @Detavern.

**Comment by squarefk** [comment]
I solved the issue by updating OS X version from high sierra to catalina.
