### ISSUE TITLE
能在网页里使用太极吗 (Can Taichi be used on webpages) ？

### ISSUE THREAD

**Issue by gzll** [taichi-dev/taichi#4102]
看到有太极ZOO，希望能在网站里使用太极生成3D图形，也试图网上搜寻关于太极WASM的资料，但是没有找到什么。
有哪位大神使用太极做过网页，放些资料哈，谢谢了。

**Comment by k-ye** [comment]
BTW, 你可以在创建 Taichi AOT module 时指定 webassembly backend，这样就会生成一系列 webassembly kernels, i.e.,

```py
m = ti.aot.Module(ti.wasm)
m.add_kernel(fn)
m.save(...)
```

**Comment by ailzhang** [comment]
Closing via https://github.com/taichi-dev/taichi/issues/4102#issuecomment-1020291163, please feel free to reopen if you have other questions!
