### ISSUE TITLE
make_changelog.py doesn't work well with cherry-picked branch

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#4118]
To repro, please checkout and build `rc-v0.8.11` from source and then run
```
python misc/make_changelog.py
```
Then you'll notice that the generated changelog contains commits not in this branch. 

cc: @frostming would you mind help taking a look?

**Comment by frostming** [comment]
According to the code it seems to default to `master` branch when no pos args are given.
https://github.com/taichi-dev/taichi/blob/e7f674eb5e7b7478712345f70d0bbdf7ff4fa6cd/misc/make_changelog.py#L81-L83
