### ISSUE TITLE
Coexistence of operator! and operator bool in lang::Expr is very likely to cause wrong use

### ISSUE THREAD

**Issue by PGZXB** [taichi-dev/taichi#4119]
### Background
The `operator!` and `operator bool` coexist in `lang::Expr`. The `operator bool` means if the expr holds a nonnull ptr to `lang::Expression`. The `operator!` will return a new Expr which holds a `logic_not`-`UnaryOpExpression` of `this->expr`.

I used like :
```C++
// expr is a instance of lang::Expr
if (!expr) {
  // do somthing
}
```
The meaning I thought : `if (!expr.operator bool()) { ... }`
True meaning     : `if (expr.operator!().operator bool()) { ... }`

Because of this, I spent nearly half a day in debuging😭.

### My thought
Coexistence of `operator!` and `operator bool` in `lang::Expr` is very likely to cause wrong use when coding. Maybe we can remove one which is not or rarely used, and reset it to a normal member function instead of operator overloading if necessary?

(**At least, the contributors who see the issue will be vigilant when using like `if(!expr)`**:stuck_out_tongue_closed_eyes:.

**Comment by re-xyr** [comment]
IMO using operator overloading to create target language level terms is almost always guaranteed to go wrong. I'm for deleting all such operator overloads completely.

**Comment by k-ye** [comment]
+1 for removing these overloaded operators
