### ISSUE TITLE
Legacy install script doesn't recognize macOS 10.15

### ISSUE THREAD

**Issue by bluevisor** [taichi-dev/taichi#414]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

in line 58 of install.py:

`  if name.lower().startswith('darwin'):`

The actual string starts with "macos" instead of "darwin". 

**Log/Screenshots**
Please post the full log of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening.

```
$ python3 install.py 
* Taichi Installer
('64bit', '')
Traceback (most recent call last):
  File "install.py", line 235, in <module>
    installer.run()
  File "install.py", line 143, in run
    assert get_os_name() in ['linux', 'osx', 'win'], \
  File "install.py", line 64, in get_os_name
    assert False, "Unknown platform name %s" % name
AssertionError: Unknown platform name macOS-10.15.3-x86_64-i386-64bit
```

**To Reproduce**
Please post a sample code to reproduce the bug. The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the code short.

```
1: wget https://raw.githubusercontent.com/yuanming-hu/taichi/legacy/install.py
2: python3 install.py
```

**Comment by jonasenander** [comment]
What is the status of this? It is fixed in the a later branch but not added to the legacy branch... planned action?
