### ISSUE TITLE
[ci] Properly clean up self-hosted runners

### ISSUE THREAD

**Issue by qiao-bo** [taichi-dev/taichi#4161]
For self-hosted runners, at the moment Taich does not have (and Github does not provide? [similar question here](https://github.community/t/how-to-properly-clean-up-self-hosted-runners/128909)) built-in methods to clean up the working directory e.g., `actions-runner\_work\taichi\taichi`. This leaves our CI in a undefined state and may lead to errors such as `Error: fatal: Needed a single revision`. Happened in our Windows buildbot recently. 

It would be nice to have a property clean up mechanism.

**Comment by qiao-bo** [comment]
@ailzhang @frostming any thoughts on this?

**Comment by rexwangcc** [comment]
It seems that we can create a systemd timer or crontab to periodically remove everything under `actions-runner\_work\taichi\taichi`?
