### ISSUE TITLE
Question about the example 'mpm88.py' or 'mpm99.py' 2D TO 3D

### ISSUE THREAD

**Issue by fengzekang** [taichi-dev/taichi#417]
Dear Developer, I am using your python script to learn the taichi code. And I am doing transfer from 2D to 3D based on the 'mpm88.py' or 'mpm99.py'. And also I added the .vtu format outputs files to achieve the paraview visualization. 
But I got problems in the output files, after the substep, the results of x v and other matriax are nan nan... I have checked many times and I am confused. If you have time, could you please point out. 
Thanks a lot~ 
The code what I added are ugly... (and .py file cannot be attached so I just use the .txt)
[mpm88-2.txt](https://github.com/taichi-dev/taichi/files/4137424/mpm88-2.txt)
[mpm99-2.txt](https://github.com/taichi-dev/taichi/files/4137425/mpm99-2.txt)

**Comment by yuanming-hu** [comment]
Sorry we probably won't have the time to debug code with > 20 LoC, but you can checkout https://github.com/taichi-dev/taichi_elements and https://github.com/taichi-dev/taichi_elements/blob/master/mpm_solver.py for a working 3D implementation.

**Comment by fengzekang** [comment]
Thanks a lot. I will try it.

**Comment by yuanming-hu** [comment]
I took a quick look anyway...
```
new_C += 8 * weight * ti.outer_product(g_v, dpos) * inv_dx
```
Why is here `8`? It should be `4` :-)

**Comment by fengzekang** [comment]
Thanks for your review. Yesterday I have checked the script totally and I changed some errors. Now it's successful and I am trying to add the Drucker-Prager constitutive. Thanks again!

**Comment by yuanming-hu** [comment]
Awesome!

**Comment by fengzekang** [comment]
Hi, dear @yuanming-hu 
You are busy and have lots of work to do. And I think this issue is not useful for any other people, so I comment hear.
I have added the code of 'sand' model (according to taichi-mpm) [,](https://github.com/yuanming-hu/taichi_mpm/blob/master/src/particles.cpp) but the results of the 'slope failure' are not right. I am currently thinking that if this sand model is the Drucker-Prager constitutive (elastoplastic constitutive in soil mechanics). Or can you explain the meaning of this model briefly?
On the other hand, I will add the code of the 'Material' module and 'Input' model based on your code. I think it is useful to debug and develop in the future.
Thanks a lot.

**Comment by yuanming-hu** [comment]
Hi @fengzekang 

Here are MPM sand papers:
 - https://www.seas.upenn.edu/~cffjiang/research/sand/paper.pdf
 - https://www.seas.upenn.edu/~cffjiang/research/wetsand/wetsand_siggraph17.pdf
 - https://www.seas.upenn.edu/~cffjiang/research/sediment/gao2018sediment.pdf
