### ISSUE TITLE
misc/code_format.py does not format correctly with clang-format-11

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#4196]
**Describe the bug**
I'm using m1 mac, and I've got clang-format 11 on my mac, and misc/code_format.py doesn't format correctly. According to the doc, the required clang-format version is 10 but homebrew does not provide clang-format-10.  It will be great if we can support clang-format-11 as well.

**Comment by ailzhang** [comment]
How about giving this a try? If it works we can add it somewhere in the contribution guide. https://o9ixctz0o7.feishu.cn/wiki/wikcn2mq0ZBtKdwl1FJqZ2C1rkg#j8AENG

**Comment by lin-hitonami** [comment]
> How about giving this a try? If it works we can add it somewhere in the contribution guide. https://o9ixctz0o7.feishu.cn/wiki/wikcn2mq0ZBtKdwl1FJqZ2C1rkg#j8AENG

It works!

**Comment by lin-hitonami** [comment]
I'll add it to the contribution guideline.
