### ISSUE TITLE
Principled C++ side Expr construction helpers

### ISSUE THREAD

**Issue by re-xyr** [taichi-dev/taichi#4199]
Following #4119, I searched for similar helper functions and operations for constructing frontend `Expr`s.

- Most operators are in `ir/expression_ops.h`. This file is included by `ir/expression.h`, however not many files are actually using these operators.
- Some others are in `ir/expr.h`
- A few are in `ir/frontend.h`, which appears to be legacy

I propose that we

- Remove the `#include` of `ir/expression_ops.h` from `ir/expression.h` so that new codes have less chance of misusing them. If any file still needs to construct large amount of ASTs they can still include it separately
- Helpers in seem to have two naming conventions (`helper_name` and `HelperName`) - decide on one (I prefer `HelperName`)
- Remove `ir/frontend.h`, move any helpers still in use to `ir/expr.h`

**Comment by k-ye** [comment]
> Helpers in seem to have two naming conventions (helper_name and HelperName) - decide on one (I prefer HelperName)

Hmm, which exactly helper is using `HelperName`? In general, our coding convention is that: use `helper_name` if it is a function, use `HelperName` if it is a class/struct.
