### ISSUE TITLE
Views of PyTorch tensors are not observed in `ti.any_arr()` access

### ISSUE THREAD

**Issue by victoriacity** [taichi-dev/taichi#4208]
### **Describe the bug**
When accessing a PyTorch tensor using `ti.any_arr()`, the tensor is always **indexed using its internal memory layout instead of its viewed shape.** This results in unintuitive behavior in a Taichi kernel operating on PyTorch tensors.

### **To Reproduce**
For example, this piece of test does not pass:
```python
import taichi as ti
import torch
ti.init()
@ti.kernel
def copy(x: ti.any_arr(), y: ti.any_arr()):
    for i, j in x:
        y[i, j] = x[i, j]
x = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]]).T
y = ti.ndarray(int, (3, 3))

copy(x, y)

for i in range(3):
    for j in range(3):
        assert x[i, j] == y[i, j]
```
This is because transposing a PyTorch tensor creates an alternate view of the tensor instead of changing its memory layout, making `x[i, j]` in python scope being column-major (w.r.t. memory). In contrast, `x[i, j]` in the Taichi kernel is still row-major. Changing line of the kernel invocation to `copy(x.contiguous(), y)`, of course, makes the test pass.

### **Additional comments**
I'm not sure whether this needs to be fixed as a bug. Alternatively, we can prompt this behavior to users in the documentation of `ti.any_arr()` so that they are aware that PyTorch tensors are always accessed by the actual memory layout in Taichi kernels.

**Comment by ailzhang** [comment]
Nice catch! IMHO the best way to warn users here is that we throw an error when the input tensor is a view and ask users to explicitly call `tensor.clone()` before passing it to taichi kernels. We can tell if a pytorch tensor is a view by calling `t._is_view()`.
