### ISSUE TITLE
False warnings on unsigned integer overflow

### ISSUE THREAD

**Issue by igor-elovikov** [taichi-dev/taichi#4210]
**Describe the bug**
Weird warnings about unsigned integer exceeding the range

**To Reproduce**

```py
import taichi as ti

ti.init(arch=ti.gpu)

@ti.kernel
def u32_test():
    x: ti.u32 = 2891336453
    print("x = ", x)

u32_test()
```

**Log/Screenshots**
```
[Taichi] version 0.8.11, llvm 10.0.0, commit 9d0973e5, win, python 3.7.8
[Taichi] Starting on arch=cuda
[W 02/04/22 20:57:53.169 24856] [impl.py:_clamp_unsigned_to_range@395] Constant 2891336453 has exceeded the range of 32 int, clamped to -1403630843
x =  2891336453
```

**Additional comments**
It wasn't actually clamped and kernel works correctly as far as I can tell, so basically it's just about false warnings

**Comment by ailzhang** [comment]
Thanks for reporting! This warning is produced since we created `x` first as i32 and then cast it to u32. so the warning was actually for the first cast. We'll look into a fix to create annotated `x` properly.
