### ISSUE TITLE
Type check warning failed to locate the code who raising the warning

### ISSUE THREAD

**Issue by erizmr** [taichi-dev/taichi#4250]
**Describe the bug**
Type check warning failed to locate the code who raising the warning.

**To Reproduce**

```py
import taichi as ti

ti.init(debug=True)

x = ti.field(dtype=ti.i32, shape=())
y = ti.field(dtype=ti.f32, shape=())
@ti.kernel
def bug_gen():
    x[None] += ti.cast(1.3, ti.f64)
    y[None] += ti.cast(2.5, ti.f64)
bug_gen()
```

**Log/Screenshots**
![image](https://user-images.githubusercontent.com/33411325/153334434-594b1a24-9cbd-44fe-b5bd-b93faf0363e1.png)

**Comment by lin-hitonami** [comment]
Yes, but it seems that we are passing the traceback info to the Expr class in C++? https://github.com/taichi-dev/taichi/blob/master/python/taichi/lang/expr.py#L37

**Comment by strongoier** [comment]
Yes the missing info can be fixed. However, even if it is fixed, the result info will be the traceback mostly inside the ASTTransformer instead of anything locating source code.
