### ISSUE TITLE
Feature request: matrix slicing

### ISSUE THREAD

**Issue by xuhao1** [taichi-dev/taichi#4257]
Hi there, my program needs to create an array to store some data, it looks like
```python
#Marching...
...
    vertlist = [[0, 0, 0] for i in range(12)]
    for _i in ti.static(range(12)):
        if edges & 2**_i:
            _p0 = ti.static(edges_grid_xyz)[_i][0]
            _p1 = ti.static(edges_grid_xyz)[_i][1]
            p0 = [i + _p0[0]*step, j + _p0[1]*step, k + _p0[2]*step]
            p1 = [i + _p1[0]*step, j + _p1[1]*step, k + _p1[2]*step]
            p = self.vertexInterp(p0, p1, tsdf[p0], tsdf[p1], isolevel)
            vertlist[_i][0] = p[0]
            vertlist[_i][1] = p[1]
            vertlist[_i][2] = p[2]
    
    _i = 0
    while triTable[cubeindex, _i] != -1:
        self.add_triangle(vertlist[triTable[cubeindex, _i]], 
            vertlist[triTable[cubeindex, _i + 1]], vertlist[triTable[cubeindex, _i +2]], triangle_idx)
        triangle_idx += 1
        _i += 3
```

If a use a normal list here for vertlist, it will raise:
```
TypeError: list indices must be integers or slices, not Expr
```

If I change vertlist to
```
                    vertlist = ti.Matrix([[0, 0, 0] for i in range(12)])
```
It will raise

```
                        self.add_triangle(vertlist[triTable[cubeindex, _i], 0],
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The 0-th index of a Matrix/Vector must be a compile-time constant integer, got <class 'taichi.lang.expr.Expr'>.
This is because matrix operations will be **unrolled** at compile-time for performance reason.
If you want to *iterate through matrix elements*, use a static range:
  for i in ti.static(range(3)):
    print(i, "-th component is", vec[i])
See https://docs.taichi.graphics/lang/articles/advanced/meta#when-to-use-for-loops-with-tistatic for more details.

```
I hope to parallelize this piece of code so the vertlist should not be a global accessible field, so how should I make this code works?

**Comment by strongoier** [comment]
Could you try `ti.init(dynamic_index=True)` and then use `vertlist = ti.Matrix([[0, 0, 0] for i in range(12)])`? Allowing variable indices of vectors/matrices is still an experimental feature and not officially released yet. You may observe performance regression for now, but it should work properly. We are actively working on it, so feedback is highly welcome!

**Comment by xuhao1** [comment]
@strongoier Thanks for your help! By enabling the dynamics index, the error disappears. But another problem arise.
vertlist[i] does give an element of the matrix, but not a column of the matrix, how can I pass a column of the matrix to some function?

**Comment by strongoier** [comment]
Oops, matrix slicing is not supported yet. Could you use a helper function for now? We will add it soon.

**Comment by xuhao1** [comment]
@strongoier Thanks! I am writing in  __ti.Vector([vertlist[i, 0], vertlist[i, 1], vertlist[i, 2]])__ style now. Looking forward for this feature.
