### ISSUE TITLE
Rewrite the functions in tools.image using PLI.Image module

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#4304]
**Concisely describe the proposed feature**

I suggest we use `PIL.Image` to handle image io in taichi. The benefits are:

1. Clean and readable code.
2. Don't reinvent the wheel.
2. The `imresize()` function does not handle image interpolations and clamp mode. 
3. The `imwrite()` function clamps float arrays to be within the range [0.0. 1.0], but scales int arrays to be within the range [0, 255], causes an inconsistent behavier.

**Comment by qiao-bo** [comment]
@neozhaoliang this has been fixed, right? can you mention this issue in the fix PR and close this one. Thanks!

**Comment by neozhaoliang** [comment]
It has not been fixed yet,  but not of high priority.
