### ISSUE TITLE
Can only iterate through Taichi fields/snodes

### ISSUE THREAD

**Issue by lyd405121** [taichi-dev/taichi#4314]
- My project can not compile if taichi>=0.8.6, error info is "Can only iterate through Taichi fields/snodes"
- https://github.com/lyd405121/ti-raytrace
- So I do some tests to understand that:

```python
import taichi as ti
import taichi_glsl as ts

ti.init(arch=ti.gpu)

@ti.func
def unroll(v):
    for i in ti.static(range(3)):
        v[i]= 0

@ti.data_oriented
class Test:
    def __init__(self):
        self.v  = ti.Vector.field(3, dtype=ti.f32)
        ti.root.dense(ti.i, 100 ).place(self.v) 

    @ti.kernel
    def test(self):
        for  i in self.v:
            unroll(self.v[i])

test1 = Test()
test1.test()
```
- I find if I use ti.static to unroll the code in a template class,  the error is caught. 
- Should I manully unroll my code or I wirte something wrong, or just some new feature?

**Comment by lyd405121** [comment]
- Found a interest thing
- If I comment "import taichi_glsl as ts"
- The code works!

**Comment by bobcao3** [comment]
`taichi_glsl` is not actively maintained and it might be broken, let me check!

**Comment by lyd405121** [comment]
> `taichi_glsl` is not actively maintained and it might be broken, let me check!

Thanks! :)

**Comment by bobcao3** [comment]
Hello! Can you try it again on Taichi 0.9.0? This might be related to the new frontend API

**Comment by lyd405121** [comment]
> Hello! Can you try it again on Taichi 0.9.0? This might be related to the new frontend API

## 0.9.0 sovle the taichi-glsl probelm，but another static problem I found：

```python
import taichi as ti
ti.init(arch=ti.gpu)

@ti.data_oriented
class Tool:
    @ti.func
    def unroll(self, v):
        for i in ti.static(range(3)):
            v[i]= 0


@ti.data_oriented
class Test:
    def __init__(self, tool):
        self.v  = ti.Vector.field(3, dtype=ti.f32)
        ti.root.dense(ti.i, 100 ).place(self.v) 
        self.tool = tool

    @ti.kernel
    def test(self):
        tool = ti.static(self.tool)
        for  i in self.v:
            tool.unroll(self.v[i])

tool = Tool()
test1 = Test(tool)
test1.test()
```
## error info
tool = ti.static(self.tool)
Traceback (most recent call last):
File "e:\anaconda3\lib\site-packages\taichi\lang\ast\ast_transformer_utils.py", line 20, in __call__
    return method(ctx, node)
  File "e:\anaconda3\lib\site-packages\taichi\lang\ast\ast_transformer.py", line 397, in build_Call
    node.ptr = func(*args, **keywords)
  File "e:\anaconda3\lib\site-packages\taichi\lang\impl.py", line 851, in static
    f'Input to ti.static must be compile-time constants or global pointers, instead of {type(x)}'
ValueError: Input to ti.static must be compile-time constants or global pointers, instead of <class '__main__.Tool'>

**Comment by lyd405121** [comment]
- I make a tool class as a series of function
- Then I pass the tool class to other class for reducing code reuse rate
- “tool = ti.static(self.tool)” just want to make code shorter which is one of taichi's syntactic sugar

**Comment by strongoier** [comment]
@lin-hitonami Did we ban this behavior?

**Comment by lin-hitonami** [comment]
It seems that it was banned at least two years ago... You should only use the syntax sugar `a = ti.static(b)` on fields and functions according to the [documentation](https://docs.taichi.graphics/lang/articles/advanced/syntax_sugars).

**Comment by lin-hitonami** [comment]
It seems that it was banned at least two years ago... Maybe we assumed that class members are all scalars or fields...

**Comment by lyd405121** [comment]
> 

Ok，I see
```python
import taichi as ti
ti.init(arch=ti.gpu)

@ti.data_oriented
class Tool:
    @ti.func
    def unroll(self, v):
        for i in ti.static(range(3)):
            v[i]= 0


@ti.data_oriented
class Test:
    def __init__(self, tool):
        self.v  = ti.Vector.field(3, dtype=ti.f32)
        ti.root.dense(ti.i, 100 ).place(self.v) 
        self.tool = tool

    @ti.kernel
    def test(self):
        #tool = ti.static(self.tool)
        tool = self.tool
        for  i in self.v:
            tool.unroll(self.v[i])

tool = Tool()
test1 = Test(tool)
test1.test()

```
I just change "tool = ti.static(self.tool)" to "tool = self.tool"
