### ISSUE TITLE
taichi-nightly can't install as expected

### ISSUE THREAD

**Issue by lyd405121** [taichi-dev/taichi#4319]
![TAICHI-NIGHTLY](https://user-images.githubusercontent.com/16344694/154433523-9f94e247-a603-4e18-bb7b-5923d965e6d2.png)

**Comment by strongoier** [comment]
What is your Python version?

**Comment by lyd405121** [comment]
> What is your Python version?

3.7.6

**Comment by strongoier** [comment]
Unfortunately, taichi-nightly only provides Python 3.8 wheels for now :-(

**Comment by lyd405121** [comment]
> Unfortunately, taichi-nightly only provides Python 3.8 wheels for now :-(

Get it!
