### ISSUE TITLE
Loop inside a if statement is identified as an outermost loop

### ISSUE THREAD

**Issue by erizmr** [taichi-dev/taichi#4324]
**Describe the bug**
The loop inside a if statement is identified as an outermost loop, which is incompatible with the current doc.
![image](https://user-images.githubusercontent.com/33411325/154607949-be4512ff-0882-43e1-be05-d2b5eef893b6.png)

According to the current doc, it is the loop at the outermost scope that gets parallelized, not the outermost loop.
https://docs.taichi.graphics/#parallel-for-loops

**To Reproduce**

```py
import taichi as ti
ti.init()

x = ti.field(dtype=int, shape=())
x[None] = 1

@ti.kernel
def test_break():
    if x[None] > 0:
        for i in range(5):
            x[None] += 1
            break
test_break()

```
```py
import taichi as ti
ti.init()

@ti.kernel
def test_break_2(x:int):
    if x > 0:
        for i in range(5):
            x = 1
            break
	
test_break_2(2)
```

**Log/Screenshots**
![image](https://user-images.githubusercontent.com/33411325/154607442-2cace3c8-35e3-45ec-9cab-c6a8c9568241.png)

**Comment by lin-hitonami** [comment]
I've spotted it in #4238. I will take a look at the code and determine whether we change the code or the documentation.

**Comment by qiao-bo** [comment]
Did we change the doc or had a fix already? can we close this issue?

**Comment by lin-hitonami** [comment]
The outermost loop which is not in the outermost scope is not parallelized. We should change the code to allow `break` in these loops.
