### ISSUE TITLE
Matrix AttributeError: 'int' object has no attribute 'assign'

### ISSUE THREAD

**Issue by chuiliuyiyi** [taichi-dev/taichi#4331]
```python
@ti.data_oriented
class juzhen:
A = ti.Matrix([[2,3,4],[3,4,5]])
@ti.kernel
def bljzxc(self,A: ti.template(),b:ti.f64):#()
	for i in ti.static(range(A.n)):
		for j in ti.static(range(A.m)):
			A[i,j] = A[i,j] + 1#error

AttributeError: 'int' object has no attribute 'assign'
```

**Comment by bobcao3** [comment]
Can you give us an example where you called this kernel?

**Comment by chuiliuyiyi** [comment]
![image](https://user-images.githubusercontent.com/75259241/154780374-58dac69e-7089-486d-ab42-ed86811188ef.png)

**Comment by bobcao3** [comment]
Hello! `global A` would not work. Taichi kernel are executed in its own scope, and global variables are understood as compile time constants. If you want a kernel to interact with the python scope, such as modifying two matrices, please pass in these matrices as `ti.any_arr()` or using a field.

**Comment by bobcao3** [comment]
You can refer to `https://docs.taichi.graphics/lang/articles/basic/field`

**Comment by chuiliuyiyi** [comment]
I see，think you very much！

**Comment by bobcao3** [comment]
Closing for now, if you have any questions feel free to reopen the issue!
