### ISSUE TITLE
Shall we install requirements for "Build and Test (GPU)" in CI?

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#4335]
According to https://github.com/taichi-dev/taichi/blob/66161d52c0aca4dec41f4d3b1c5b0d322cdbedd8/.github/workflows/scripts/unix_test.sh#L21-L27, `requirements_test.txt` was not used for  "Build and Test (GPU)" . Is this behavior intentional or accidental? This prevents #4322 from passing CI because the PR adds a new requirement (`matplotlib`) for testing.

**Comment by qiao-bo** [comment]
Ii could be that the requirements_test.txt was pre-built into the docker image (v0.1.0 -> v0.1.1) to avoid the long pip installation time (download torch etc.). @Leonz5288 Can you confirm this?

**Comment by qiao-bo** [comment]
Please use #4336 to temporally unblock the user's PRs for now.
