### ISSUE TITLE
GGUI example is not working on linux 

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#4342]
I'd assume `python python/taichi/examples/simulation/implicit_mass_spring.py --use-ggui` should work similarly as `python python/taichi/examples/simulation/implicit_mass_spring.py` but the spring doesn't move.

**Comment by ailzhang** [comment]
Also `stable_fluid_ggui.py` only works intermittently for me (as fluid showed up roughly 1 out of 6 times when clicked)

**Comment by AmesingFlank** [comment]
@FantasyVR for the implicit mass spring example.

for `stable_fluid_ggui` does it work if you drag instead of click? clicking alone isn't supposed to produce any new colored fluid, it's the dragging that produces them.

**Comment by ailzhang** [comment]
@AmesingFlank sorry I was dumb lol ... yea stable_fluid_ggui works for me!
