### ISSUE TITLE
compare n! times each other among n data

### ISSUE THREAD

**Issue by stamnug** [taichi-dev/taichi#4357]
#4381 i give a solution about this problem.

Is there a algorithm that is able to process n data comparing n! times each other to filter some faster? 

If there is, a funtion that get only value in f feild may be such that:
```python
f  = ti.field(int, shape=(10,10))

@ti.func
def filter_repeat(a, b):
    return (a,b) if a == b else None

@ti.kernel
def test():
    for i, j in f:
        result = ti.filter(f[i, j], filter_repeat)
        #if f[i, j] is only in the f field, the result will be f[i,j] else None.
        if result: 
            ...
```
For using the result later , the interface of the ti.filter may be  **ti.filter(f[i,j], filter_cond, no_shape_field)** , the no_shape_field used for making a new field that save the result. the code may be such that:
```python
f  = ti.field(int, shape=(10,10))
g = ti.field(int)
...
    for i,j in f:
        result = ti.filter(f[i,j], filter_repeat, g)
        if result:
            ...
    for i,j in g:  #it is debatable that keep index of the f field for the g field 
        ....
...
```
now it can also get max of f , this only is a example, we can implement all comparison problem among n data by giving a judge funtion :
```python
...
@ti.func
def max(a, b):
    return b if a>=b else a

@ti.kernel
def test():
    for i, j in f:
        ti.filter(f[i, j], max, g)
...
```

**Comment by stamnug** [comment]
@k-ye 来捧个场 /doge

**Comment by k-ye** [comment]
I think you're basically looking for `dynamic` SNode for the field `g` in your example? https://docs.taichi.graphics/lang/articles/advanced/sparse#dynamic-snode

> @k-ye 来捧个场 /doge

It's OK to occasionally express in non-English language when you want to better convey your idea, but please do stick with our community policy and communicate in English whenever possible. Thanks.

**Comment by stamnug** [comment]
> I think you're basically looking for `dynamic` SNode for the field

No, g is a field waiting for ti.filter to generate a filtered result.
it always is should that there is a variable to save filtered result.

**Comment by k-ye** [comment]
I don't have a better answer in mind for the n! comparison issue, given that the `filter` func is very generic. Summoning the literal strong OIer @strongoier (and maybe @xumingkuan)  for algorithm questions...

As for your `no_shape_field`, I believe the dynamic SNode is a nice fit here.

**Comment by stamnug** [comment]
> As for your `no_shape_field`, I believe the dynamic SNode is a nice fit here.

i cannot get your deep mind. i tend to keep struct same to f field for keeping original index. even the g can be considered as a reference copy of f, just deactivate(or clear) filtered data. it is high probability that not change the data of g. and this can get more performance. if the data of g will be changed, we can use copy-on-write. 

To implement this, we need a mask to mask real deactive status of f. when using for-loop for g according to the mask Traverse rather than real deactive status.

if there is no a high performance algorithm, we have to implement it using direct manner. below is a simple pseudo code for 2-D int field. of course, any types is no problem for c++.
```python
typedef int(*cond)(int, int)
class Filter:
    def __init__(int i, int j, cond condition):
        self.array = molloc(value=None, size=i*j , type=int)
        self.condition = condition

    def fill_data(int data, int index):
        int* ptr = self.array
        *(ptr+index) = data

    def filter(int indexA):
        indexB = indexA + 1
        while indexB - self.array != field.i * field.j:  #not over array bound.
            index_of_filted = self.condition(indexA, indexB)
            if index_of_filted:
                *(ptr+index_of_filted) = MASKED.
            indexB++

def filter_condition(int a, int b):

    if (*a) == None or (*b) == None:  #not fill_data to array
        wait()

    if (*a) == MASKED or (*b) == MASKED: #have been filted.
        return -1

    #filter not max value
    if (*a) < (*b):
        return a
        
def kernel():
...
    filter = Filter(field.i , field.j, filter_condition)
    threads = create_thread(field.i * field.j)
    for t in threads:
        #parallel excute, t.i, t.j stand for the index of current data in parallel-for-loop.
        filter.fill_data(t.data, t.i * field.j + t.j)
        filter.filter(t.i * field.j + t.j)
...
```

**Comment by xumingkuan** [comment]
I don't understand. Isn't comparing n numbers to each other only O(n^2) because you will just call `a[i] < a[j]` for all `0 <= i, j < n`?

**Comment by stamnug** [comment]
> I don't understand. Isn't comparing n numbers to each other only O(n^2) because you will just call `a[i] < a[j]` for all `0 <= i, j < n`?

I also don't understand , Is O(n^2) a good performance? Maybe my poor engine make some misunderstand?

**Comment by xumingkuan** [comment]
> > I don't understand. Isn't comparing n numbers to each other only O(n^2) because you will just call `a[i] < a[j]` for all `0 <= i, j < n`?
> 
> I also don't understand , Is O(n^2) a good performance? Maybe my poor engine make some misunderstand?

Oh it's not a good performance if you want to compute max of n elements. This can be computed in O(n) by reduction (see also: https://en.cppreference.com/w/cpp/algorithm/reduce). I feel like the situation can differ a lot when your objective differ.

Maybe one kind of thing you might be interested in is you want to do some operation among n elements and the operator is associative. "+" and "max" satisfy this property: a+(b+c) = (a+b)+c, and max(max(a, b), c) = max(a, max(b, c)). So we can do a1+a2+...+an or max(a1, a2, ..., an) in a linear amount of work and in parallel, which is very fast.

**Comment by stamnug** [comment]
> Maybe one kind of thing you might be interested in is you want to do some operation among n elements and the operator is associative. "+" and "max" satisfy this property: a+(b+c) = (a+b)+c, and max(max(a, b), c) = max(a, max(b, c)). So we can do a1+a2+...+an or max(a1, a2, ..., an) in a linear amount of work and in parallel, which is very fast.

No, i really interesting is the shelter of each other of some object, but the comparison among n data still is a generic problem. we can abstract the form of comparison, then give a judge funtion to solve this type of problem. 
额, 我也不知道我哪里描述有问题, 有问题再说吧....

**Comment by stamnug** [comment]
@xumingkuan  
Any quesiton? i need this feature, so i hope it has no any problem except no man to implement it.

**Comment by xumingkuan** [comment]
For example,
```python
f  = ti.field(int, shape=(10,10))

@ti.func
def filter_repeat(a, b):
    return (a,b) if a == b else None

@ti.kernel
def test():
    for i, j in f:
        result = ti.filter(f[i, j], filter_repeat)
        #if f[i, j] is only in the f field, the result will be f[i,j] else None.
        if result: 
            ...
```
you can simplify this into
```python
@ti.kernel
def test():
    for i, j in f:
        if i == j: 
            ...
```
and I don't think the simplified version is slow if `f` is sparse. If `f` is dense, why not just write
```python
@ti.kernel
def test():
    for i in range(10):
        j = i
        if f[i, j]:
            ...
```
?

To better convey your idea, you might want to give a concrete example that runs slowly and cannot be rewritten to run faster in the current version of Taichi, and propose a way to make it run faster.

**Comment by stamnug** [comment]
> I still don't know what's the feature you want. Is there any example that you need to compare among n elements but not for computing the maximum/minimum value and unable to rewrite the program into a simple for loop?

比如在某个视角下判定一个范围内物体哪些物体被遮挡, 嵌套两层for确实能实现, 但是O(n^2)的效率是难以接受的. 比较逻辑不是一个简单的运算, 不过这与运算无关, 简单的运算也可以. 核心的问题是, n个物体第一轮提取2个物体出来比较时, 不符合条件的物体就能被过滤, 使得其不会被选取作为下一轮被比较的元素.

**Comment by stamnug** [comment]
套用到最大值的问题上来描述, 就是0-9十个数字, 第一轮(0,1),(1,2),(2,3) ... (8,9)同时比较, 将较小数字过滤掉, 这是一个全局过滤, 第二轮就只剩9 了...

**Comment by xumingkuan** [comment]
> > I still don't know what's the feature you want. Is there any example that you need to compare among n elements but not for computing the maximum/minimum value and unable to rewrite the program into a simple for loop?
> 
> 
> 
> 比如在某个视角下判定一个范围内物体哪些物体被遮挡, 嵌套两层for确实能实现, 但是O(n^2)的效率是难以接受的. 比较逻辑不是一个简单的运算, 不过这与运算无关, 简单的运算也可以. 核心的问题是, n个物体第一轮提取2个物体出来比较时, 不符合条件的物体就能被过滤, 使得其不会被选取作为下一轮被比较的元素.

Maybe you can try to use another field as the mask. In the first round, you can set `mask[i, j] = 1` for each object satisfying the condition and locating at `i, j`. In the second round, you can just write `for i, j in mask:`.

**Comment by stamnug** [comment]
> Maybe you can try to use another field as the mask. In the first round, you can set `mask[i, j] = 1` for each object satisfying the condition and locating at `i, j`. In the second round, you can just write `for i, j in mask:`.

对, 我就是这个意思, 但是它能在前端直接写出来吗? 我直觉是不行...可能我要考虑一段时间....如果它将掩码写入另一个field的同时仍然还要执行两次for循环, 这岂不是多此一举

**Comment by xumingkuan** [comment]
> > Maybe you can try to use another field as the mask. In the first round, you can set `mask[i, j] = 1` for each object satisfying the condition and locating at `i, j`. In the second round, you can just write `for i, j in mask:`.
> 
> 
> 
> 对, 我就是这个意思, 但是它能在前端直接写出来吗? 我直觉是不行...可能我要考虑一段时间....如果它将掩码写入另一个field的同时仍然还要执行两次for循环, 这岂不是多此一举

Let's say the grid size is m and the number of objects satisfying some conditions is n (n<=m because there might be some cells activated but without a valid object; for 100x100 grid with 5000 cells activated, m is 5000).

If you want to loop over object1 and then loop over object2 and compare object1 and object2 if they satisfy some conditions, it worths writing the mask into another field beforehand because you will be only looping over useful objects in this way. This will accelerate it from O(m^2) to O(n^2+m).

If you want to loop over the objects only once, then you cannot know which are the objects satisfying conditions beforehand, and you can only loop over them in O(m). You cannot do better because you're only given the grid of size m.

If you want to loop over the objects multiple times but not in nested loops, you may also want to use the mask field. The first loop is still O(m), but all following loops become O(n).

BTW, Taichi might run faster if you place the mask field and the data together. You can search "data layout" in the document to learn more.

**Comment by stamnug** [comment]
> 

thanks for your reply, this problem has not only been a algorithm problem, but also been a engineering problem. 
the time complexity is same between single cpu and multi-cpu. it is a good implement that i am looking for.
