### ISSUE TITLE
how to build the ut for the interactive samples?

### ISSUE THREAD

**Issue by Tiny-Box** [taichi-dev/taichi#4359]
For some interactive samples, such as mciso_advanced and marching_squares, they build a canvas and then move the mouse to observe the demo effect.
In simple terms it seems to output the image directly (give up the interaction?) or maybe use the mock interface to mock the mouse from top to bottom once and finally build a video output?

**Comment by strongoier** [comment]
I suggest mocking the mouse from top to bottom.

**Comment by Tiny-Box** [comment]
get it, then later I will figure out how to do, I first pick the simple to
do

Yi Xu ***@***.***> 于2022年2月22日周二 16:20写道：
