### ISSUE TITLE
dynamics attribute

### ISSUE THREAD

**Issue by zixichen007115** [taichi-dev/taichi#4364]
I install taichi 0.8.11 and try to install the High-Performance 3D Solver in Ubuntu, but when run 'ti install mpm' in command line, I get 'install is not a valid command!'.

Also. when I try to run https://github.com/yuanming-hu/taichi_mpm/blob/master/scripts/mls-cpic/banana.py, I get 'AttributeError: module 'taichi' has no attribute 'dynamics''.

**Comment by bobcao3** [comment]
Hi, I don't think there is ever something mentioning you can do `ti install`. What are you trying to get? There is an solver package here: `https://github.com/taichi-dev/taichi_elements`. As for the example code, it might not be able to run in the newer version of taichi, but I'm not sure. @yuanming-hu

**Comment by yuanming-hu** [comment]
Hi @zixichen007115, you need the legacy version of Taichi. Please see this page for more details: https://github.com/taichi-dev/taichi/blob/5ab90f03ef37701506c7034c3f1955d225b39957/docs/installation.rst.

**Comment by zixichen007115** [comment]
Thank you for your reply. I have written code for mpm with the newest taichi to escape this problem.
