### ISSUE TITLE
Weird data shuffeling with sparse tensors

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#437]
**Describe the bug**
Now that the zero filling bug is fixed. I have now running into an even weirder bug with (de)activating sparse tensors. Essentially its looks like data is getting shuffled around when copying one sparse tensor to another. The seemingly important part is that x in fill2() is only activated at indices according to some conditional statement on x_temp. This works fine, but then when I repeatedly copy and clear the x and x_temp fields back and forth to each other, the data get shuffled after a few iterations. 

**Log/Screenshots**
in my program I am initializing a field to this:
![image](https://user-images.githubusercontent.com/39635884/73815196-71ef3e80-47a2-11ea-8c53-2ddba47cee2b.png)

I am then copying it back and forth to a temp array and deactivating them after the copy like in the test script below
after a few iterations (seems like its always 3rd or 4th) a defect pops up:
![image](https://user-images.githubusercontent.com/39635884/73815392-107b9f80-47a3-11ea-8d53-e3b66d6fb48a.png)

which gets worse and worse with more iterations:
![image](https://user-images.githubusercontent.com/39635884/73815439-3acd5d00-47a3-11ea-9cfa-bd68e2866a92.png)

**To Reproduce**
``` python
import taichi as ti

x = ti.var(ti.f32)
x_temp = ti.var(ti.f32)

n = 8

@ti.layout
def place():
  ti.root.dense(ti.ijk, n).pointer().dense(ti.ijk, n).place(x)
  ti.root.dense(ti.ijk, n).pointer().dense(ti.ijk, n).place(x_temp)

@ti.kernel
def fill():
  for k in range(n*n):
    for j in range(n*n):
      for i in range(n*n):
        x[i,j,k] = i+j+k

@ti.kernel
def fill2():
  for i,j,k in x_temp:
    if x_temp[i,j,k] < 100:
      x[i,j,k] = x_temp[i,j,k]

@ti.kernel
def copy_to_temp():
  for i,j,k in x:
    x_temp[i,j,k] = x[i,j,k]

@ti.kernel
def copy_from_temp():
  for i,j,k in x_temp:
    x[i,j,k] = x_temp[i,j,k]

@ti.kernel
def clear():
  for i,j,k in x.parent().parent():
    ti.deactivate(x.parent().parent(),[i,j,k])

@ti.kernel
def clear_temp():
  for i,j,k in x_temp.parent().parent():
    ti.deactivate(x_temp.parent().parent(),[i,j,k])

fill()
copy_to_temp()
clear()
fill2()
clear_temp()


for iter in range(100):
  print(iter)
  copy_to_temp()
  clear()
  copy_from_temp()
  clear_temp()

  for k in range(n * n):
    for j in range(n * n):
      for i in range(n * n):
        if i+j+k < 100:
          assert x[i,j,k] == i+j+k
```

**Comment by yuanming-hu** [comment]
Thanks for reporting! Sorry about the trouble. I'll take a look tomorrow.

**Comment by KLozes** [comment]
No Problem! glad to help.

**Comment by yuanming-hu** [comment]
Fixed in https://github.com/taichi-dev/taichi/commit/606e8db91b577316b45000cbabe544a8a28c6ed2.

Thanks for helping with testing. I'm working on optimizing/testing the sparse data structures right now. If you can add this test case to the tests, that would be great!
