### ISSUE TITLE
Can not upgrade GLIBC_2.27 on CentOS 7 or other previous OS. Its common for cloud develop enviroments using old GLIBC.

### ISSUE THREAD

**Issue by AAUfoa** [taichi-dev/taichi#4377]
How to solve the dependency on GLIBC 2.27

**Comment by bobcao3** [comment]
@qiao-bo Have we solved the glibc 2.27 dependency or is it temporarily on hold?

**Comment by qiao-bo** [comment]
It is pending at the moment. Our previous efforts to pin GLIBC back to 2.2.5 resulted in Vulkan test failures. see [#3552](https://github.com/taichi-dev/taichi/issues/3552). However, we can have a CPU-only version that uses 2.2.5. You can use [this dockerfile](https://github.com/taichi-dev/taichi/blob/master/ci/Dockerfile.manylinux2014.cpu) to build from source. Hope it helps

**Comment by AAUfoa** [comment]
I want to use GPU with devcloud, so CPU-only version may not helpful. I still can not find a way to install on tlinux 2.3, and there are also othere problems in trying. But gratefully thanks for quick reply, hope it will be solved.

**Comment by bobcao3** [comment]
Can you try to build from source anyways? i.e. using the developer installation ( https://docs.taichi.graphics/lang/articles/contribution/dev_install ) This might work with the GPU.

**Comment by k-ye** [comment]
> Our previous efforts to pin GLIBC back to 2.2.5 resulted in Vulkan test failures. see https://github.com/taichi-dev/taichi/issues/3552. However, we can have a CPU-only version that uses 2.2.5.

If the problem is only with Vulkan, we can release a special version that is `manylinux2014` compatible, but only ships CPU/CUDA backend. WDYT?

**Comment by qiao-bo** [comment]
> > Our previous efforts to pin GLIBC back to 2.2.5 resulted in Vulkan test failures. see #3552. However, we can have a CPU-only version that uses 2.2.5.
> 
> If the problem is only with Vulkan, we can release a special version that is `manylinux2014` compatible, but only ships CPU/CUDA backend. WDYT?

that should be possible

**Comment by AAUfoa** [comment]
>

**Comment by AAUfoa** [comment]
> > > Our previous efforts to pin GLIBC back to 2.2.5 resulted in Vulkan test failures. see #3552. However, we can have a CPU-only version that uses 2.2.5.
> > 
> > 
> > If the problem is only with Vulkan, we can release a special version that is `manylinux2014` compatible, but only ships CPU/CUDA backend. WDYT?
> 
> that should be possible

That would be great! Cant wait to try it.

**Comment by qiao-bo** [comment]
> Also I try pip install taichi=0.9.0 and 0.8.3 on my local machine with Ubuntu 18.04.5 LTS, got same GLIBC error. Wish a fix for this. I think it is common for users using ubuntu 16/18 as their deep learning GPU.

Can you post the error here or in a separate issue? Our release should work with 18.04.

**Comment by AAUfoa** [comment]
> > Also I try pip install taichi=0.9.0 and 0.8.3 on my local machine with Ubuntu 18.04.5 LTS, got same GLIBC error. Wish a fix for this. I think it is common for users using ubuntu 16/18 as their deep learning GPU.
> 
> Can you post the error here or in a separate issue? Our release should work with 18.04.

Sorry for my negligence. I got the failure because I try 'pip install ' directly. When using "python3 -m pip install taichi", it works well.

**Comment by strongoier** [comment]
Hi @AAUfoa. We now have a manylinux2014-compatible wheel, which should work on CentOS 7. Feel free to try it out by `pip install -i https://test.pypi.org/simple/ taichi-nightly` and provide some feedback :-)
