### ISSUE TITLE
Prevent CI from triggering on forked branches

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#4383]
I kept getting these CI status on my forks.

**Comment by knight42** [comment]
@qiao-bo Yes! This issue has been addressed by #4215.

**Comment by k-ye** [comment]
Why am I still getting emails on my own fork :joy:

**Comment by knight42** [comment]
> Why am I still getting emails on my own fork 😂

@k-ye More precisely, only disable scheduled workflows are disabled on forks now, did you want to disable all tests on forks?

**Comment by k-ye** [comment]
Yep :-) I think we can disable `Build and Test` and `Performance Monitoring`, there's no point running them on forked branches?

**Comment by knight42** [comment]
> Yep :-) I think we can disable `Build and Test` and `Performance Monitoring`, there's no point running them on forked branches?

I think it is reasonable, these workflows could be disabled as well. I will file another PR to disable them.
