### ISSUE TITLE
How to import pictures

### ISSUE THREAD

**Issue by chuiliuyiyi** [taichi-dev/taichi#4385]
A = ti.field.from_numpy(ti.imread('296363.jpg'))

report：
AttributeError: 'function' object has no attribute 'from_numpy'

**Comment by bobcao3** [comment]
The `from_numpy` function only works on fields. You should declare a field first and then load the image:

```python
A = ti.Vector.field(n=3, dtype=ti.f32, shape=(width, height))
A.from_numpy(ti.imread('296363.jpg'))
```

The other option is to use `ti.ext_arr` and directly use the numpy array as input field to kernel. (This will be slower if you need to use the image multiple times)

**Comment by chuiliuyiyi** [comment]
think you very much
