### ISSUE TITLE
[Kernel] print more detailed information in ti.profiler.print_kernel_profiler_info

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#4388]
**Feature description**

I want to show more detailed information of a kernel function in `ti.profiler.print_kernel_profiler_info`, for example:

+ number of cpu cores used.
+ number of grids/threads allocated.
+ number of iters (in a top-level for loop) assigned to a thread.
+ or even better, show the average execution time of the threads.

**Comment by qiao-bo** [comment]
Hi, did you try the trace mode? `ti.print_kernel_profile_info('trace')`. The trace mode works with GPU only at the moment.

**Comment by neozhaoliang** [comment]
@qiao-bo It works, thanks!
