### ISSUE TITLE
C/C++ bindings

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#439]
**Concisely describe the proposed feature**
A few users want to ship compiled Taichi kernels, so that they can run it without Python

**Describe the solution you'd like**
We can add a method like `ti.export_all(lang='C'/'C++')`, to dump
 - A header that contains all the interfaces 
 - A shared object with all compiled kernels

Then users can basically do something like
```C
#include "mpm99_exported.h"

int main() {
  initialize_taichi();
  mpm99_substep();
  finalize_taichi();
}
```
... or using a more OOP C++ version.

**Additional comments**
If you also need this or have any suggestions, please feel free to comment! :-)

**Comment by archibate** [comment]
Anything in common with #394?

**Comment by samuela** [comment]
I would really like the ability to do this, esp. with rust support.

**Comment by yuanming-hu** [comment]
Yeah I think we can start with a standard C  interface and most other languages like C++/rust/go/Ruby can make use of it as well.

**Comment by samuela** [comment]
Makes sense. I'd be happy to help out with this but I'm personally not sure where to start.

**Comment by yuanming-hu** [comment]
For CPU code we can just dump LLVM IR and use `llc` to compile it into a .obj. Not sure what else we should do to make it a loadable shared object. The place where the optimized LLVM IR is emitted: https://github.com/taichi-dev/taichi/blob/abbf5b13537ab5e0f1d951fb3502b65a4f509bb1/taichi/backends/codegen_llvm_x86.cpp#L104

We should explore this direction and a good starting point is to compile a simple taichi kernel, such as
```python
for i in range(n):
  a[i] += 1
```
Some related discussions on SO: https://stackoverflow.com/questions/22956761/generate-binary-code-shared-library-from-embedded-llvm-in-c

For GPU code we can simply dump the compiled PTX and invoke the CUDA runtime to load and run the PTX code.

**Comment by archibate** [comment]
Possible solution:
First, dump `llvm::errs()` into `/tmp/a.ll`.
Second, call `llc /tmp/a.ll -o /tmp/a.o`.
Third, call `gcc -fPIC -shared -o /tmp/a.so /tmp/a.o`.

**Comment by archibate** [comment]
How to convert `llvm::errs()` into `std::string`?

**Comment by archibate** [comment]
#1332 could be a systematic solution for this.
Note: Currently the experimental C backend is already capable of creating `.so`, which could be later linked into user programs.
