### ISSUE TITLE
Difference between `FrontendSNodeOpStmt` and `SNodeOpExpression`

### ISSUE THREAD

**Issue by re-xyr** [taichi-dev/taichi#4399]
These two constructs have identical structures, so it would be ideal to merge them into one `SNodeOpExpression`; do they have any functional difference?

What I've noticed is that `SNodeOpExpression::flatten` does not account for all cases of `SNodeOpType`. Are those operations only expected to be used with `FrontendSNodeOpStmt`? Is this also true vice versa?

**Comment by qiao-bo** [comment]
cc @strongoier

**Comment by strongoier** [comment]
IIUC `SNodeOpExpression` is for snode ops with return values, while `FrontendSNodeOpStmt` is for snode ops with no return values. Currently only `activate` and `deactivate` are handled by  `FrontendSNodeOpStmt`.
