### ISSUE TITLE
Windows build source failed.

### ISSUE THREAD

**Issue by stamnug** [taichi-dev/taichi#4407]
不搞了, 不搞了.    🛌摆烂
![QQ截图20220301005715](https://user-images.githubusercontent.com/21006005/156025107-4aea4071-621e-42a3-8c2f-d4b3f52d41c8.png)

**Comment by qiao-bo** [comment]
Hi, it seems like your "path:pattern" env has some invalid address. Maybe you can double check that? In addition, could you please adhere to our policy to use English language in public issues? thanks.

**Comment by bobcao3** [comment]
It seems CMake generated file outputs correctly but there is something about "Error: could not load cache", not really sure where did that come from

**Comment by stamnug** [comment]
i modify subprocess.check_call to subprocess.run solve it. 
now this problem same turned to #4408 
![Uploading QQ截图20220301162623.png…]()
