### ISSUE TITLE
An error when build from source on Windows

### ISSUE THREAD

**Issue by 0xzhang** [taichi-dev/taichi#4408]
I got an error when build from source on Windows.

![微信图片_20220228222737](https://user-images.githubusercontent.com/33616362/156000012-4b9fdaaa-9f6e-44bd-a384-5a6af9d31a80.png)

I have tried commands `python setup.py install` or `python setup.py develop`. Both get this error.

Actually `taichi_core.dll` exists, but in `./runtimes/Release/taichi_core.dll`. After moved `taichi_core.dll` under directory `runtimes`, build process continue and success.

**Comment by bobcao3** [comment]
Follow the latest build guide on the docs. We now require Ninja, which can be found if you are using the x64 developer shell

**Comment by stamnug** [comment]
are you solved it? can you upload your taichi_core.dll to me? i have same error, but it is really no exist.

**Comment by 0xzhang** [comment]
@stamnug Maybe you could found it under `runtimes/Release/`.

**Comment by stamnug** [comment]
@0xzhang  no, it is really no exist. Can you send a copy to me?  987004590@qq.com

**Comment by bobcao3** [comment]
Is it running from the x64 developer shell? If it is, can you try directly running the command `ninja` to check whether that is there or not?

**Comment by 0xzhang** [comment]
Yes

> Is it running from the x64 developer shell? If it is, can you try directly running the command `ninja` to check whether that is there or not?

Yes. I have confirmed this problem. I havn't notice the command enviroment described in docs. I used PowerShell and got this error. Previously, the generator is `Visual Studio 16 2019`. Switch to `Ninja` gonna be ok.
