### ISSUE TITLE
Remove LLVM logic from the generic Device interface

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#4426]
I'm talking about this part https://github.com/taichi-dev/taichi/blob/1915a80272ac7e7008c8b22b2a1eb5f67fd54202/taichi/backends/device.h#L397-L414

We can see if there's a  better way to avoid specific backend info from being leaked into this generic interface.

**Comment by qiao-bo** [comment]
Perhaps an extra layer such as llvm_device or spirv_device between the generic device interface and all backends?  Currently, anything shared between cpu and cuda will probably go to the generic device interface, which yields leak.

**Comment by k-ye** [comment]
> Perhaps an extra layer such as llvm_device

+1, sounds like the right direction.

**Comment by PGZXB** [comment]
I would like to work on this. @k-ye

**Comment by k-ye** [comment]
Thanks, your now :-)

**Comment by strongoier** [comment]
Closed via #4470.
