### ISSUE TITLE
how to draw lines in GGUI? 

### ISSUE THREAD

**Issue by ZeyingXuHuaWei** [taichi-dev/taichi#4434]
Hi,   I want to display line segments in 3D space. I guess that ggui scene can only draw mesh and particles, then how to draw line segments?    Sometimes we just want to visualize the edges of a mesh instead of faces. Thank you.

**Comment by qiao-bo** [comment]
Hi, have you checked the GUI doc? https://docs.taichi.graphics/lang/articles/gui/ggui

**Comment by qiao-bo** [comment]
cc @AmesingFlank

**Comment by AmesingFlank** [comment]
We don't have support for lines in 3D scenes yet :<
