### ISSUE TITLE
affine velocity in mpm

### ISSUE THREAD

**Issue by zixichen007115** [taichi-dev/taichi#4450]
In [mpm99.py,](https://github.com/taichi-dev/taichi/blob/master/python/taichi/examples/simulation/mpm99.py) C is updated by 4 * inv_dx * weight * g_v.outer_product(dpos). However, according to the paper '[The Affine Particle-In-Cell Method](https://www.math.ucla.edu/~jteran/papers/JSSTS15.pdf)', C = B * (D)^-1, and B=weight * g_v.outer_product(dpos), D=inv_dx * inv_dx / 4. A 'inv_dx' is missing.

**Comment by qiao-bo** [comment]
cc @FantasyVR

**Comment by AmesingFlank** [comment]
The `dpos` in `mpm99.py` is in grid coordinate space:
```
dpos = ti.Vector([i, j]).cast(float) - fx
```
This means that it is contains a factor of `inv_dx`

In the APIC paper, the outer product is written as
```
v (x_i - x_p^n)^T
```
The `x` here are all world-space coordinates.

**Comment by k-ye** [comment]
Closing, feel free to reopen if  you have additonal questions thx!
