### ISSUE TITLE
ti.atomic_min gives wrong result when an argument is a matrix

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#4455]
For all atomic operations `ti.atomic_min`, `ti.atomic_max`, `ti.atomic_add`, `ti.atomic_sub`, `ti.atomic_and`, `ti.atomic_xor`, they always return the first argument when this argument is a matrix, and raises error if the first argument is a scalar and the second one is a matrix:

```python
import taichi as ti
ti.init()

@ti.kernel
def foo():
    x = ti.Vector([0, 1, 2])
    z = ti.atomic_min(x, 1)  # [0, 1, 2]
    z = ti.atomic_min(1, x)  # TaichiSyntaxError

foo()
```

**Comment by strongoier** [comment]
1. According to https://docs.taichi.graphics/lang/articles/basic/operator#supported-atomic-operations, the return value of an atomic operation is the old value of first argument.
2. The first argument must be some writable destination, so using a constant doesn't make sense.

**Comment by neozhaoliang** [comment]
Thanks, just learned that.

**Comment by ailzhang** [comment]
Closing via https://github.com/taichi-dev/taichi/issues/4455#issuecomment-1060193714

**Comment by ailzhang** [comment]
Reopening since the error message here can be improved indeed, I currently get `cannot augassign taichi class <class taichi.lang.matrix.Matrix> to scalar expr` which is less obvious to users what they did wrong. Will send a PR for it.
