### ISSUE TITLE
Undefined reference to backend-specific symbols

### ISSUE THREAD

**Issue by qiao-bo** [taichi-dev/taichi#4464]
Currently, compiling Taichi with a specific backend can be enabled/disabled by `TI_WITH_{CUDA,VULKAN,METAL...}=ON/OFF`. However, this env also controls the inclusion of source files (particular headers) in CMake.

For example Vulkan
https://github.com/taichi-dev/taichi/blob/0a1b9a63f1c9468c008658b4140919b59e0ebd78/cmake/TaichiCore.cmake#L178-L181
https://github.com/taichi-dev/taichi/blob/0a1b9a63f1c9468c008658b4140919b59e0ebd78/cmake/TaichiCore.cmake#L84

Problem arises when other code makes explicit backend-specific function calls (especially when a backend is disabled by the env). Such as 
https://github.com/taichi-dev/taichi/blob/0a1b9a63f1c9468c008658b4140919b59e0ebd78/taichi/llvm/llvm_program.cpp#L190-L198

As a result, we need to use these conditional inclusion to be able to compile, otherwise, we will get `undefined reference to xxx` when building target `taichi_core`. 

This could be one of a series of steps towards a better CMakefile.

**Comment by qiao-bo** [comment]
compiling current master with `-DTI_WITH_METAL:BOOL=OFF` yields the following error:
```
[ 97%] Linking CXX shared library libtaichi_core.so
/usr/bin/ld: CMakeFiles/taichi_isolated_core.dir/taichi/program/program.cpp.o: in function `taichi::lang::Program::Program(taichi::Arch)':
program.cpp:(.text+0x561): undefined reference to `taichi::lang::metal::is_metal_api_available()'
/usr/bin/ld: program.cpp:(.text+0x581): undefined reference to `taichi::lang::MetalProgramImpl::MetalProgramImpl(taichi::lang::CompileConfig&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by ailzhang** [comment]
Closing via #4469
