### ISSUE TITLE
How to slice

### ISSUE THREAD

**Issue by chuiliuyiyi** [taichi-dev/taichi#4466]
How to slice
for example
a = ti.field(ti.f32,10)
b = a[0:9]

**Comment by ailzhang** [comment]
@chuiliuyiyi I believe this only works after https://github.com/taichi-dev/taichi/pull/4420/files, so might be give nightly a try? 
`pip install -i https://test.pypi.org/simple/ taichi-nightly`

**Comment by strongoier** [comment]
@ailzhang That PR is about matrix slicing instead of field slicing :-(

**Comment by ailzhang** [comment]
Aha right, thanks for reminding! yea field slicing is not supported yet....

**Comment by strongoier** [comment]
I will close this for now because it can be merged with #2669.
