### ISSUE TITLE
ti.ndrange accepts float arguments

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#4478]
`ti.ndrange` also accepts float arguments, which causes undesired behavier:

```python
import taichi as ti
ti.init()

@ti.kernel
def test():
    for i in ti.ndrange((1.1, 2.2)):
        print(i)

test()  # will print 1.1
```

**Comment by yuanming-hu** [comment]
We should probably through an error in this case. Welcome contribution!

**Comment by neozhaoliang** [comment]
PR [4636](https://github.com/taichi-dev/taichi/pull/4636) to fix this.
