### ISSUE TITLE
【PaddlePaddle Hackathon 2】Taichi 任务合集

### ISSUE THREAD

**Issue by TCChenlong** [taichi-dev/taichi#4483]
大家好，非常高兴地告诉大家，第二期 [PaddlePaddle Hackathon](https://www.paddlepaddle.org.cn/PaddlePaddleHackathon-2022-03?fr=paddleg) 开始了。PaddlePaddle Hackathon 是面向全球开发者的深度学习领域编程活动，鼓励开发者了解与参与 PaddlePaddle 开源社区。本次共有四大专区：PaddlePaddle、Paddle Family、Paddle Friends、Paddle Eval，共计100+个任务供大家认领。详细信息可以参考 [PaddlePaddle Hackathon 说明](https://www.paddlepaddle.org.cn/contributionguide?docPath=hackathon_cn)。大家是否已经迫不及待了呢~

本 ISSUE 是 Paddle Friends 专区 Taichi 方向任务合集。具体任务列表如下：

| 序号 | 难度 | 任务 ISSUE |
| ---- | ---- | --- | 
| 88 | ⭐️⭐️  | [实现 Taichi 和 PaddlePaddle 之间的无拷贝交互](https://github.com/taichi-dev/taichi/issues/4482) |
| 89 | ⭐️⭐️ | [增加 Taichi 和 PaddlePaddle 高效结合的案例](https://github.com/taichi-dev/taichi/issues/4480) |

若想要认领本次活动任务，请至 [PaddlePaddle Hackathon 2 Pinned ISSUE](https://github.com/PaddlePaddle/Paddle/issues/40234) 完成任务 ISSUE 认领。

活动官网：[PaddlePaddle Hackathon 2](https://www.paddlepaddle.org.cn/PaddlePaddleHackathon?fr=FTaichi)

**Comment by Zheaoli** [comment]
Hi, we do require issues in this repo to be related to Taichi development and/or bug reports. We will migrate this issue to the hackathons repo (link to the issue), and close this one. Thanks for your understanding!
