### ISSUE TITLE
vulkan loading error when 'arch=cuda'

### ISSUE THREAD

**Issue by optimono** [taichi-dev/taichi#4501]
**Describe the bug**
Tried `examples/mass_spring_3d_ggui.py` without vulkan preinstalled, received `vulkan loading error`

**To Reproduce**
 `python .\mass_spring_3d_ggui.py`

**Log/Screenshots**
```
PS E:\code\taichi\python\taichi\examples\ggui_examples> python .\mass_spring_3d_ggui.py
[Taichi] version 0.9.0, llvm 10.0.0, commit 0c432a37, win, python 3.7.6
[W 03/10/22 14:11:34.741 15612] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_loader.cpp:check_vulkan_device@39] Can not create Vulkan instance
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File ".\mass_spring_3d_ggui.py", line 83, in <module>
    window = ti.ui.Window("Cloth", (800, 800), vsync=True)
  File "D:\Python\Python37\lib\site-packages\taichi\ui\window.py", line 28, in __init__
    is_packed)
RuntimeError: Error loading vulkan
```

**Additional comments**
some `ti diagnose` info:
```
[Taichi] version 0.9.0, llvm 10.0.0, commit 0c432a37, win, python 3.7.6

Taichi system diagnose:

python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
system: win32
executable: d:\python\python37\python.exe
platform: Windows-10-10.0.19041-SP0
architecture: 64bit WindowsPE

cc: False
cpu: True
metal: False
opengl: True
cuda: True
vulkan: False
```

**Comment by k-ye** [comment]
Did you install Vulkan? You can find the installation steps in https://docs.taichi.graphics/lang/articles/contribution/dev_install (Search for "Install Vulkan")

**Comment by optimono** [comment]
> Hi! Did you install Vulkan? You can find the installation steps in https://docs.taichi.graphics/lang/articles/contribution/dev_install (Search for "Install Vulkan")

Hi, @k-ye Thanks for your reply! I have not installed vulkan yet. 
So taichi version 0.9.0 ggui relies  on vulkan? I thought vulkan was not indispensable.

**Comment by ailzhang** [comment]
@optimono GGUI depends on vulkan so it's needed to run mass_spring_3d_ggui.py ;)

**Comment by strongoier** [comment]
I will close it for now because the question is answered. Feel free to open a new one if you have other questions :-)

**Comment by optimono** [comment]
Thanks guys for your replies and instructions! Problem solved. 
However, vulkan **SDK** is not necessary, but **vulkan driver support** in my case.
In any case someone could encouter the same issue, Nvidia GPU users could find the driver [here](https://developer.nvidia.com/vulkan-driver).
