### ISSUE TITLE
cannot break in the second cycle  Double  “if” error 

### ISSUE THREAD

**Issue by chuiliuyiyi** [taichi-dev/taichi#4502]
import taichi as ti
ti.init(arch=ti.cpu,debug = True)

F = ti.Vector.field(n = 1,dtype = ti.f32,shape=(100000000))
j0 = ti.field(dtype = ti.i32,shape=(1))

@ti.kernel
def COS(y :ti.f32,z :ti.f32):
	j0[0] = -1
	j1 = 10
	for waiceng in range(0,1):
		for x0 in range(50,100):
			j0[0] += 1
			j1 -= 1
			F[j0[0]] = ti.Vector([j1])
			print(z,j0[0],F[j0[0]])
			if  j0[0]>2:
				if F[j0[0]][0]*F[j0[0]-1][0]<0:#It can't be determined here     Double "if "error
					break

for z00 in range(1,10):
	z = z00/10
	x = COS(0,z)

**Comment by ailzhang** [comment]
cc: @lin-hitonami

**Comment by chuiliuyiyi** [comment]
what is lin hitonami

**Comment by ailzhang** [comment]
haha @lin-hitonami is the developer who wrote the break support so I cc'ed him :P 
But in your example it seems like 
```
			if  j0>2:
				if F[j0][1]*F[j0-1][1]<0:
					x1 = j0
					break#here here here
```
is run at compile time ( `j0` is a python value so this got evaluated  to false by python at taichi compilation) Thus taichi actually didn't see this break stmt at all. If you want to make sure taichi is aware of `j0`'s mutation, consider putting it in a taichi field?

**Comment by chuiliuyiyi** [comment]
The first time, and the next cycle will be interrupted. What's going on?

**Comment by chuiliuyiyi** [comment]
j0 = ti.field(dtype = ti.i32,shape=(1))
..........
			F[j0[0]] = ti.Vector([x,-Fc+Fy])
			print(z,j0[0],F[j0[0]])
			if  j0[0]>2:
				if F[j0[0]][1]*F[j0[0]-1][1]<0:
					x1 = j0[0]
					break
It still won't break the second time

**Comment by ailzhang** [comment]
@chuiliuyiyi This seems to be working as expected (like break works no matter how many times it's called), see the minimal repro below: 

```
import taichi as ti
ti.init()
j = ti.field(dtype=ti.f32, shape=(1))

@ti.kernel
def f():
    j[0] = -1
    for i in range(0, 1):
        for x0 in range(50):
            j[0] += 1
            if j[0] > 2:
                print('hello')
                break

for i in range(1, 10):
    f()
```
If this doesn't explain your issue, would you mind adding a **minimal** repro script as well? Thanks a lot!

**Comment by chuiliuyiyi** [comment]
Double “ if ” error 

import taichi as ti
ti.init(arch=ti.cpu,debug = True)

F = ti.Vector.field(n = 2,dtype = ti.f32,shape=(100000000))
j0 = ti.field(dtype = ti.i32,shape=(1))

@ti.kernel
def COS(y :ti.f32,z :ti.f32) ->ti.f32:
	j0[0] = -1
	x1 = 0
	j1 = 10
	for waiceng in range(0,1):
		for x0 in range(int(Cr2+Or2+1)*50,1000):
			j0[0] += 1
			x = x0/50
			j1 -= 1
			F[j0[0]] = ti.Vector([x,j1])
			print(z,j0[0],F[j0[0]])
			if  j0[0]>2:
				if F[j0[0]][1]*F[j0[0]-1][1]<0:#It can't be determined here     Double layer if error reporting
					x1 = j0[0]
					break
	return F[x1][0]


for z00 in range(1,10):
	z = z00/10
	x = COS(0,z)

**Comment by lin-hitonami** [comment]
Does your program indent like this?
```python
import taichi as ti
ti.init(arch=ti.cpu,debug = True)

F = ti.Vector.field(n = 1,dtype = ti.f32,shape=(100000000))
j0 = ti.field(dtype = ti.i32,shape=(1))

@ti.kernel
def COS(y :ti.f32,z :ti.f32):
    j0[0] = -1
    j1 = 10
    for waiceng in range(0,1):
        for x0 in range(50,100):
            j0[0] += 1
            j1 -= 1
            F[j0[0]] = ti.Vector([j1])
            print(z,j0[0],F[j0[0]])
            if j0[0]>2:
                if F[j0[0]][0]*F[j0[0]-1][0]<0:#It can't be determined here Double "if "error
                    break

for z00 in range(1,10):
    z = z00/10
    x = COS(0,z)

```

I've read the program and if I understand correctly, `F[j0[0]][0]*F[j0[0]-1][0]` is never less than zero according to the logic of this program, so it shouldn't break at all?

**Comment by chuiliuyiyi** [comment]
Thank you very much for your answer.
Unexpectedly, I ignored that in the loop, there is a value equal to 0 So I won't interrupt.
Thank you again for your answer

**Comment by ailzhang** [comment]
Closing via https://github.com/taichi-dev/taichi/issues/4502#issuecomment-1064919679
