### ISSUE TITLE
Follow the XDG Base Directory Specification

### ISSUE THREAD

**Issue by RuRo** [taichi-dev/taichi#4504]
## Concisely describe the proposed feature

Currently, Taichi creates a hardcoded `~/.taichi` directory in the home directory. As far as I am concerned, random programs putting their files in my home directory is a cardinal sin. Taichi should follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) instead of polluting the user home directory.

## Describe the solution you'd like

Before choosing the solution, we need to consider 3 questions:

1) Does `~/.taichi` currently contain configuration files?
2) Does `~/.taichi` currently contain data, that **needs** to be persisted across reboots?
3) Will changing the location of `~/.taichi` break anything for current users?

For now, I am going to assume that the answer to all 3 questions is "No". If that is the case, then we can just change the path to `${XDG_CACHE_HOME}/taichi` without any extra compatibility logic. In practice, this would mean changing the non-windows part of the [`get_repo_dir` function](https://github.com/taichi-dev/taichi/blob/570c39d935ac621f4e44eb79fb5fb37c919d6d65/taichi/common/core.cpp#L35) from

```cpp
auto home = std::getenv("HOME");
TI_ASSERT(home != nullptr);
return std::string(home) + "/.taichi/";
```

to

```cpp
auto xdg_cache = std::getenv("XDG_CACHE_HOME");

std::string xdg_cache_str;
if (xdg_cache != nullptr) {
  xdg_cache_str = xdg_cache;
} else {
  // XDG_CACHE_HOME is not defined, defaulting to ~/.cache
  auto home = std::getenv("HOME");
  TI_ASSERT(home != nullptr);
  xdg_cache_str = home;
  xdg_cache_str += "/.cache";
}

return xdg_cache_str + "/taichi/";
```

---

If the answer to (1) or (2) is "Yes", then just use `XDG_CONFIG` or `XDG_DATA` instead of `XDG_CACHE`.

If the answer to (3) is "Yes", then we need to check if `~/.taichi` already exists and either move the folder to the XDG location or just returning the old path from `get_repo_dir`.

**Comment by ailzhang** [comment]
Hey @RuRo , thanks a lot for proposing this! IMHO the answer to all three questions above is no so it should be safe to switch to XDG. Would you mind sending a PR for it? 

cc: @Leonz5288 just in case the version check service need any updates.

**Comment by Leonz5288** [comment]
I think the answer to Q2 is yes. We kind of need to remember user's current version and the time we check user's version in order to not frequently checking user's version. However, the answers to Q1 and Q3 are no, so I believe it's safe to move .taichi under XDG_DATA.

**Comment by RuRo** [comment]
XDG_DATA is for stuff that you can't generate on your own without the users input (passwords, api keys, preferences, favourites, application state etc). If you can safely delete `~/.taichi` and the only side effect is that the next run is a bit slower, then it is a cache by XDG standards.

Sure, I'll make a PR tomorrow.

**Comment by yuanming-hu** [comment]
Just a reminder that Taichi will support compilation cache (similar to `__pycache__`), and the cache files would be put under the `.taichi` folder too.

**Comment by strongoier** [comment]
Regarding compilation cache paths cc: @PGZXB
