### ISSUE TITLE
`ti.static_assert` silently succeeds with non-static information

### ISSUE THREAD

**Issue by RuRo** [taichi-dev/taichi#4540]
```python
import taichi as ti

ti.init(debug=True)

@ti.kernel
def foo():
    value = False
    ti.static_assert(value, "Oh, no!")

foo()
```

**Actual behaviour:**

Nothing happens.

**Expected behaviour:**

Either one of these would be fine

- `AssertionError: Oh, no!` (if you can automatically infer that `value = False` is a constant/static expression)
- `TaichiCompilationError: static_assert with non-static condition.`

**Comment by strongoier** [comment]
Thanks for reporting this! This is indeed a bug.
@lin-hitonami Do you think we should keep `ti.static_assert()` or extend `ti.static` to an environment which accepts Python statements?

**Comment by lin-hitonami** [comment]
> Thanks for reporting this! This is indeed a bug. @lin-hitonami Do you think we should keep and fix `ti.static_assert()`, or extend `ti.static` to an environment which accepts Python statements?

Assert statement as a function argument is not syntactically correct in Python, so maybe we need to keep it and fix it.

**Comment by lin-hitonami** [comment]
Or can we assert like `assert ti.static(x)`?
