### ISSUE TITLE
RuntimeError: [llvm_context.cpp:clone_runtime_module@268]Assertion failure: std::this_thread::get_id() == main_thread_id_

### ISSUE THREAD

**Issue by yooooyooo** [taichi-dev/taichi#4542]
When I call taichi with fastapi, i got a RuntimeError, but success when run python files directly

**Comment by yooooyooo** [comment]
[E 03/15/22 21:12:32.985 50198] [llvm_context.cpp:clone_runtime_module@268] Assertion failure: std::this_thread::get_id() == main_thread_id_

                            * Taichi Core - Stack Traceback *                             
==========================================================================================
|                       Module |  Offset | Function                                      |
|----------------------------------------------------------------------------------------|
*               taichi_core.so |     126 | taichi::Logger::error(std::__1::basic_string< |
                                         | char, std::__1::char_traits<char>, std::__1:: |
                                         | allocator<char> > const&, bool)               |
*               taichi_core.so |     842 | taichi::lang::TaichiLLVMContext::clone_runtim |
                                         | e_module()                                    |
*               taichi_core.so |     121 | taichi::lang::LlvmProgramImpl::compile_snode_ |
                                         | tree_types(taichi::lang::SNodeTree*, std::__1 |
                                         | ::vector<std::__1::unique_ptr<taichi::lang::S |
                                         | NodeTree, std::__1::default_delete<taichi::la |
                                         | ng::SNodeTree> >, std::__1::allocator<std::__ |
                                         | 1::unique_ptr<taichi::lang::SNodeTree, std::_ |
                                         | _1::default_delete<taichi::lang::SNodeTree> > |
                                         |  > >&)                                        |
*               taichi_core.so |      25 | taichi::lang::LlvmProgramImpl::materialize_sn |
                                         | ode_tree(taichi::lang::SNodeTree*, std::__1:: |
                                         | vector<std::__1::unique_ptr<taichi::lang::SNo |
                                         | deTree, std::__1::default_delete<taichi::lang |
                                         | ::SNodeTree> >, std::__1::allocator<std::__1: |
                                         | :unique_ptr<taichi::lang::SNodeTree, std::__1 |
                                         | ::default_delete<taichi::lang::SNodeTree> > > |
                                         |  >&, unsigned long long*)                     |
*               taichi_core.so |     345 | taichi::lang::Program::add_snode_tree(std::__ |
                                         | 1::unique_ptr<taichi::lang::SNode, std::__1:: |
                                         | default_delete<taichi::lang::SNode> >, bool)                                               |
*               taichi_core.so |     196 | void pybind11::cpp_function::initialize<taich |
                                         | i::export_lang(pybind11::module_&)::$_84, tai |
                                         | chi::lang::SNodeTree*, taichi::lang::SNodeReg |
                                         | istry*, taichi::lang::SNode const*, taichi::l |
                                         | ang::Program*, bool, pybind11::name, pybind11 |
                                         | ::scope, pybind11::sibling, pybind11::return_ |
                                         | value_policy>(taichi::export_lang(pybind11::m |
                                         | odule_&)::$_84&&, taichi::lang::SNodeTree* (* |
                                         | )(taichi::lang::SNodeRegistry*, taichi::lang: |
                                         | :SNode const*, taichi::lang::Program*, bool), |
                                         |  pybind11::name const&, pybind11::scope const |
                                         | &, pybind11::sibling const&, pybind11::return |
                                         | _value_policy const&)::'lambda'(pybind11::det |
                                         | ail::function_call&)::__invoke(pybind11::deta |
                                         | il::function_call&)                           |
*               taichi_core.so |    4691 | pybind11::cpp_function::dispatcher(_object*,  |
                                         | _object*, _object*)                           |
*                    python3.8 |     122 | (null)                                        |
*                    python3.8 |     374 | (null)                                        |
*                    python3.8 |     652 | (null)                                        |
*                    python3.8 |   29782 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     171 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   30158 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     171 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   30158 | (null)                                        |
*                    python3.8 |     237 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   29782 | (null)                                        |
*                    python3.8 |     237 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   29753 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     171 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   30158 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     461 | (null)                                        |
*                    python3.8 |     100 | (null)                                        |
*                    python3.8 |   30644 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     128 | (null)                                        |
*                    python3.8 |     131 | (null)                                        |
*                    python3.8 |     169 | (null)                                        |
*                    python3.8 |     171 | (null)                                        |
*                    python3.8 |   30644 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   29962 | (null)                                        |
*                    python3.8 |     237 | (null)                                        |
*                    python3.8 |     100 | (null)                                        |
*                    python3.8 |   30644 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   29753 | (null)                                        |
*                    python3.8 |     237 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   29962 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   29962 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   30158 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   29962 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   29962 | (null)                                        |
*                    python3.8 |    3287 | (null)                                        |
*                    python3.8 |     253 | (null)                                        |
*                    python3.8 |     128 | (null)                                        |
*                    python3.8 |     418 | (null)                                        |
*                    python3.8 |     374 | (null)                                        |
*                    python3.8 |     240 | (null)                                        |
*                    python3.8 |     130 | (null)                                        |
*                    python3.8 |     217 | (null)                                        |
*                    python3.8 |     130 | (null)                                        |
*                    python3.8 |     100 | (null)                                        |
*                    python3.8 |   31095 | (null)                                        |
*                    python3.8 |     237 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   29753 | (null)                                        |
*                    python3.8 |     237 | (null)                                        |
*                    python3.8 |     354 | (null)                                        |
*                    python3.8 |   29753 | (null)                                        |
*                    python3.8 |     237 | (null)                                        |
*                    python3.8 |     322 | (null)                                        |
*                    python3.8 |     100 | (null)                                        |
*                    python3.8 |      74 | (null)                                        |
*                    python3.8 |      25 | (null)                                        |
*      libsystem_pthread.dylib |     224 | (null)                                        |
*      libsystem_pthread.dylib |      15 | (null)                                        |
==========================================================================================

**Comment by strongoier** [comment]
Currently Taichi cannot be used in a multi-threading environment (#2022). Sorry that we don't have enough bandwidth to solve that problem immediately, but we definitely would like to support it in the future.

**Comment by mushroomfire** [comment]
Any progress now?
