### ISSUE TITLE
`taichi.lang.util.warning` doesn't respect stdlib `warnings` filters

### ISSUE THREAD

**Issue by RuRo** [taichi-dev/taichi#4543]
The [`taichi.lang.util.warning`](https://github.com/taichi-dev/taichi/blob/e56ac6a94ed686ac2c855cf44420b8938c53c39f/python/taichi/lang/util.py#L231) function just prints the warning without consulting the current state of pythons standard library `warnings` module.

For example:
```python
import warnings
import taichi as ti

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    ti.lang.util.warning("Oh, no!") # This line shouldn't print anything

with warnings.catch_warnings():
    warnings.simplefilter("error")
    ti.lang.util.warning("Oh, no!") # This line should raise the warning as an exception
```

You should either

1) use `warnings.warn` instead of `print` (preferable, imho)
2) reimplement the standard filtering logic (see [here](https://github.com/python/cpython/blob/ea786a882b9ed4261eafabad6011bc7ef3b5bf94/Lib/warnings.py#L351))

Additionally, `ti.lang.util.warning` prints the errors to `stdout` instead of the `stderr`, which is also wrong.

**Comment by strongoier** [comment]
Thanks for pointing this out! Option 1 looks good to me.
wdyt @ailzhang @frostming

**Comment by frostming** [comment]
I agree to use the standard `warnings.warn` and `Warning` subclasses

**Comment by ailzhang** [comment]
Option 1 sounds great to me! @RuRo would you mind sending a PR to update this function? Thanks a lot!

**Comment by RuRo** [comment]
Hi, sorry for the delayed reply. Unfortunately, I am kind of busy lately, so I won't be able to contribute anything in the forceable future. I'll keep submitting issues as I run into them while using taichi and I might revisit them once I get some free time. No promises tho, so if anyone wants to contribute it, that would be great.

**Comment by pigletfly** [comment]
I'd like to take a shot on this @ailzhang

**Comment by ailzhang** [comment]
@pigletfly Awesome it's yours! Please don't hesitate to ping us here if you have any questions!
