### ISSUE TITLE
[RFC] Taichi Language Reference

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#4602]
**Concisely describe the proposed feature**
A programming language needs a specification. Both users and developers need to refer to it to determine whether a certain behavior is *correct*, *buggy*, or *undefined*.

The specification needs to be documented. It should not only stay in someone's mind. Otherwise, there will always be issues around language behavior, and maintainers have to guess who knows or can make the decision. Different maintainers have different minds, and people forget things from time to time. As a result, the language might go back-and-forth.

To avoid the above problems and standardize Taichi starting from v1.0, I propose to write a specification for Taichi.

**Describe the solution you'd like (if any)**
Because the syntax of Taichi is a subset of that of Python, I propose to model the specification after the [Python language reference](https://docs.python.org/3/reference/index.html). This route is also what [TorchScript](https://pytorch.org/docs/stable/jit_language_reference_v2.html) takes.

Roadmap:

- [x] Introduction
- [x] Basic concepts
    - [x] Values and types
    - [x] Naming and scope
- [x] Expressions
    - [x] Atoms
        - [x] Identifiers (Names)
        - [x] Literals
        - [x] Parenthesized forms
        - [x] List and dictionary displays
    - [x] Primaries
        - [x] Attribute references
        - [x] Subscriptions
        - [x] Slicings
        - [x] Calls
    - [x] The power operator
    - [x] Unary arithmetic and bitwise operations
    - [x] Binary arithmetic operations
    - [x] Shifting operations
    - [x] Binary bitwise operations
    - [x] Comparisons
        - [x] Value comparisons
        - [x] Membership test operations
    - [x] Boolean operations
    - [x] Assignment expressions 
    - [x] Conditional expressions
    - [x] Static expressions
    - [x] Expression lists
- [x] Simple statements
    - [x] Expression statements
    - [x] Assignment statements
        - [x] Augmented assignment statements
        - [x] Annotated assignment statements
    - [x] The `assert` statement
    - [x] The `pass` statement
    - [x] The `return` statement
    - [x] The `break` statement
    - [x] The `continue` statement
- [x] Compound statements
    - [x] The `if` statement
    - [x] The `while` statement
    - [x] The `for` statement

**Comment by AmesingFlank** [comment]
Highly relevant discussion: https://github.com/taichi-dev/taichi/discussions/4594

**Comment by lin-hitonami** [comment]
`6.12. Assignment expressions` seems to be missing, Taichi supports it.

**Comment by strongoier** [comment]
> `6.12. Assignment expressions` seems to be missing, Taichi supports it.

Ah nice catch! Fixed.

**Comment by lin-hitonami** [comment]
Also, we may also need a chapter for static expressions (expressions wrapped by `ti.static()`). (updated the task list)

**Comment by k-ye** [comment]
Shall we close this one :-)?

**Comment by strongoier** [comment]
> This is huge progress! Can we close this one now :-)?

Sure!
