### ISSUE TITLE
A vote to change license to Apache-2.0

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#4607]
Dear contributors, 

We are calling a majority vote to change Taichi license from MIT to Apache-2.0. The vote will be valid from today (March 23rd, 2022) until March 30th, 2022. Taichi contributor can approve this proposal by commenting "I approve the license change to Apache-2.0." or a simple thumb-up.

**Why changing the license?**

Apache-2.0 is also a permissive software license similar to MIT. Compared to MIT, Apache-2.0 has a clearer definition of patent rights and trademarks. One advantage of Apache-2.0 is its explicitly grants of patent rights. In essence, this frees our users from worrying about getting lawsuits because of potential patent rights dispute.

**Comment by knight42** [comment]
I approve the license change to Apache-2.0.

**Comment by yuanming-hu** [comment]
Sounds good to me!
I approve the license change to Apache-2.0.

**Comment by k-ye** [comment]
I approve the license change to Apache-2.0.

**Comment by Zheaoli** [comment]
I approve the license change to Apache-2.0.
