### ISSUE TITLE
python3 examples/simulation/mpm128.py is not working on Developer installation

### ISSUE THREAD

**Issue by DongqiShen** [taichi-dev/taichi#4637]
**Describe the bug**
The Document in the Developer installation may not be updated. There is no 'examples' folder in the directory.

**Log/Screenshots**
```
$   ~/GitSpace/taichi:  python3 examples/simulation/mpm128.py
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: can't open file '/Users/dongqishen/GitSpace/taichi/examples/simulation/mpm128.py': [Errno 2] No such file or directory
...
```

**Additional comments**
I checked the root directory and I didn't find the 'examples' folder. I guess the fold was removed in some commits but the doc was not updated?

**Comment by bobcao3** [comment]
Sorry we missed that in the docs. The examples are now in `python/taichi/examples` folder

**Comment by yuanming-hu** [comment]
Fixed in https://github.com/taichi-dev/taichi/pull/4640. Thank you @DongqiShen!
