### ISSUE TITLE
"Smart" thread-local reduction only works with 0D fields

### ISSUE THREAD

**Issue by RuRo** [taichi-dev/taichi#4660]
Consider the following code:
```python
import taichi as ti
    
ti.init(
    ti.gpu,
    print_kernel_nvptx=True,
    print_kernel_llvm_ir_optimized=True,
)
    
@ti.kernel
def reduce(rr: ti.template()):
    for I in ti.grouped(f):
        ti.atomic_add(rr[None], f[I])
r = ti.field(ti.f32, ())

f = ti.field(ti.f32, (2**22,))
reduce(r)
```

You can inspect the generated `ll` and `ptx` files and verify the thread-local reduction is used:
1) The value is accumulated locally using regular, non-atomic `fadd`
2) The values in each warp are aggregated using `@llvm.nvvm.shfl.sync.down.f32` and regular non-atomic `fadd`
3) The final value is aggregated using `atomicrmw fadd`

However, this optimization is very fragile and gets disabled in a lot of circumstances. You can tell, that the optimization is disabled, because the 3 steps above are replaced by a single `atomicrmw fadd` operation.

For example, any of the following changes will turn off the thread-local reduction, even though they really shouldn't (IMO).
 
Using a non-0D field
```diff
-        ti.atomic_add(rr[None], f[I])
+        ti.atomic_add(rr[0], f[I])

-r = ti.field(ti.f32, ())
+r = ti.field(ti.f32, (1,))
```

Using an ndarray instead of a field
```diff
-def reduce(rr: ti.template()):
+def reduce(rr: ti.any_arr()):

-r = ti.field(ti.f32, ())
+r = ti.ndarray(ti.f32, ())
```

Note, that this doesn't seem to be a fundamental limitation. For example, reducing into a 0D Vector field still compiles to the optimized thread-local version:
```diff
-        ti.atomic_add(rr[None], f[I])
+        ti.atomic_add(rr[None][0], f[I])

-r = ti.field(ti.f32, ())
+r = ti.Vector.field(7, ti.f32, ())
```

**Comment by turbo0628** [comment]
This is true. Thread local storage optimization is skipped in such scenarios. See [here](https://github.com/taichi-dev/taichi/blob/7027cc300cf459f57dcc882dd5ddcae14ae7281e/taichi/transforms/make_thread_local.cpp#L103-L121). 

Are you interested in contributing a more generalized TLS?

**Comment by RuRo** [comment]
I am implementing some image processing routines in taichi.
Currently, I am using global reductions in 2 places:

1) A simple scalar reduction (sum `scalar_func(img[I])` over all `I`).
2) A histogram reduction. Something like
```python
@ti.kernel
def histogram(img: ti.any_arr(), ret: ti.template()):
    for I in ti.grouped(img):
        bucket = img[I] // R
        for val in ti.static(range(256 // R)):
            ti.atomic_add(ret[None][v], val == bucket)
```

I don't actually care about the `(1,)`-sized `ti.field` case all that much, that was just something I found while experimenting.

What I really care about is the 0D `ti.ndarray` case. I am currently using `ti.ndarray` almost everywhere in my code as it seems to be consistently faster than the equivalent `ti.field` code. And so I initially used `ti.ndarray(ti.i32, ())` instead of `ti.field(ti.i32, ())` for the accumulation variable and was really surprised that it compiled to plain atomic ops without any accumulation or smart reduction.

**Comment by RuRo** [comment]
My main motivation for opening this issue is to follow the principle of least astonishment. I am totally okay with either accumulating the result in a temporary or with mixing `field` and `ndarrays`. I just think, that the current behaviour of the TLS reduction optimization is not very intuitive.

***I*** can read llvm/nvptx, and so ***I*** am able to debug such performance issues. But you shouldn't expect the average user to be able to read assembly (imho).

I can see 3 things, which could help with this situation:

1) Document the fact that the TLS reduction doesn't work on dynamically-sized data (works on scalars, vectors and matrices, doesn't work on fields of dimensionality > 0D)
2) Either document the fact that the TLS reduction doesn't work on 0D Ndarrays, or (preferably) fix it.
3) Add some way for the user to

    a) explicitly request an optimization
    b) fail or warn the user, if the explicitly requested optimization is not possible

The last point doesn't only apply to TLS reductions, btw. It can be really hard to figure out at times, which optimizations are working and which are not and even very small changes to the source code can drastically change the generated IR/assembly.

**Comment by bobcao3** [comment]
> My main motivation for opening this issue is to follow the principle of least astonishment. I am totally okay with either accumulating the result in a temporary or with mixing `field` and `ndarrays`. I just think, that the current behaviour of the TLS reduction optimization is not very intuitive.
> 
> _**I**_ can read llvm/nvptx, and so _**I**_ am able to debug such performance issues. But you shouldn't expect the average user to be able to read assembly (imho).
> 
> I can see 3 things, which could help with this situation:
> 
>     1. Document the fact that the TLS reduction doesn't work on dynamically-sized data (works on scalars, vectors and matrices, doesn't work on fields of dimensionality > 0D)
> 
>     2. Either document the fact that the TLS reduction doesn't work on 0D Ndarrays, or (preferably) fix it.
> 
>     3. Add some way for the user to
>        a) explicitly request an optimization
>        b) fail or warn the user, if the explicitly requested optimization is not possible
> 
> 
> The last point doesn't only apply to TLS reductions, btw. It can be really hard to figure out at times, which optimizations are working and which are not and even very small changes to the source code can drastically change the generated IR/assembly.

Strongly agree. I was working on the pointer alias analysis a bit earlier for NDArrays, will probably look into these further. For now, the best course of action is to first document the behavior, then unify all the pointer statements in the IR (currently a major pain for pointer analysis), then finally fix the problem entirely.
