### ISSUE TITLE
`v0.9.2` release notes and code mismatch

### ISSUE THREAD

**Issue by RuRo** [taichi-dev/taichi#4675]
It seems to me that both the `v0.9.2` PyPI release and the `v0.9.2` git tag don't actually match the [release notes](https://github.com/taichi-dev/taichi/releases/tag/v0.9.2) for this version.

I think, that the following PRs are missing from the `v0.9.2` release:
- [Lang] Deprecate ext_arr/any_arr in favor of types.ndarray (#4598) (by Yi Xu)
- [lang] Fix vector matrix ndarray to numpy layout (#4597) (by Bo Qiao)
- [bug] Fix bug that caching kernels with same AST will fail (#4582) (by PGZXB)
- [Doc] Refactored Type system. (#4584) (by Vissidarte-Herman)
- [Doc] Adjust CPU GUI document layout (#4605) (by Peng Yu)

They are listed in the release notes, but don't actually appear to be present in the PyPI release or in the [`v0.9.2` tag](https://github.com/taichi-dev/taichi/commits/v0.9.2) branch.

**Comment by strongoier** [comment]
Thanks for reporting this! The release notes is now fixed.
