### ISSUE TITLE
[Doc] GGUI should already support Mac OS X since v0.9?

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#4691]
![image](https://user-images.githubusercontent.com/6553256/161097949-91e32b86-1c0e-42da-bfc6-9e01df9d7cc8.png)

I believe it supports Mac OS X and the Vulkan backend. The doc needs an update.

**Comment by k-ye** [comment]
cc @Vissidarte-Herman

**Comment by Vissidarte-Herman** [comment]
Updated in https://github.com/taichi-dev/taichi/pull/4676
