### ISSUE TITLE
Pass in printf as a function pointer on CPU runtime

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#470]
It seems that relying on clang to compile `printf` from `cstdio` leads to a lot of portability issues (e.g. https://github.com/taichi-dev/taichi/issues/458, https://github.com/taichi-dev/taichi/issues/435#issuecomment-582202843). We should consider passing the function in as a function body for more compatibility, just like the way we pass in`assert_failed` in `runtime.cpp`.

**Comment by Psycho7** [comment]
I'm interested in this one. But how could one reproduce that error?

**Comment by yuanming-hu** [comment]
I guess you need a specific clang version to reproduce that (e.g. the one used by @archibate 
 in https://github.com/taichi-dev/taichi/issues/458). However, fortunately as long as the function definition of `printf` in runtime.cpp is replaced by a function pointer in the `Runtime` structure, then we are good.

**Comment by archibate** [comment]
I have this error, env:
```
[bate@archit taichi]$ clang --version
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm70/bin
```

**Comment by archibate** [comment]
local fix: https://github.com/taichi-dev/taichi/pull/477/commits/fdf38efa7809603f511f29d49c635ba0e8696a56

**Comment by yuanming-hu** [comment]
Just a notice that this issue is probably already resolved (with lightning speed) by @archibate in PR https://github.com/taichi-dev/taichi/pull/477

Going to bed now and will take care of the PR first thing tomorrow!

**Comment by archibate** [comment]
Good night!

**Comment by yuanming-hu** [comment]
This is resolved thanks to @archibate !
