### ISSUE TITLE
hunger for ti.log2()

### ISSUE THREAD

**Issue by mgttt** [taichi-dev/taichi#4703]
**Concisely describe the proposed feature**

log2() is much faster than ln(), and for some math calculation it is so important.  yes, log(x)/log_2 is a somehow hack solution but it is not fast enough....

**Describe the solution you'd like (if any)**
hanger for taichi.log2()

**Additional comments**

**Comment by bobcao3** [comment]
`log2` takes the same amount of hardware clock cycles as `ln`, that information can be found from AMD's GCN or RDNA ISA documentation and its compilers. It does make sense to provide `log2` in the math library.
