### ISSUE TITLE
AttributeError: module 'taichi' has no attribute 'var'

### ISSUE THREAD

**Issue by xorange** [taichi-dev/taichi#4732]
## Describe the bug
AttributeError: module 'taichi' has no attribute 'var'

## To Reproduce
``` bash
$ conda create -n games python=3.8
$ conda activate games
$ pip install taichi
```

```
 $ python
Python 3.8.13 (default, Mar 28 2022, 06:16:26) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import taichi as ti
[Taichi] version 0.9.2, llvm 10.0.0, commit 7a4d73cd, osx, python 3.8.13
>>> ti.init(debug=True)
[Taichi] Starting on arch=x64
>>> v = ti.var(ti.i32, shape=())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/games/lib/python3.8/site-packages/taichi/__init__.py", line 77, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'var'
```

I've tried with Python 3.8+taichi 0.9.2, Python 3.9 + Taichi 0.9, Python 3.9 + Taichi 0.8.
I've also checked out https://github.com/taichi-dev/taichi/issues/364 but I'm not using a nightly build nor do I have any TAICHI related ENVs.

Or you might tell me where is `ti.var` exported in taichi and I could try to locate the problem.

**Comment by knight42** [comment]
@xorange Hi, `ti.var` has been [deprecated](https://github.com/taichi-dev/taichi/issues/1500), please use `ti.field` instead. See also https://docs.taichi.graphics/lang/articles/field

**Comment by xorange** [comment]
Thanks for reply. I'll close this issue.
