### ISSUE TITLE
Taichi lang logo

### ISSUE THREAD

**Issue by TheaGong** [taichi-dev/taichi#4736]
![Taichi_lang_logo_readme](https://user-images.githubusercontent.com/100768747/162405540-21191b9d-d020-4822-b7cf-4c626f7557c3.png)

**Comment by gingerkidney** [comment]
Hi, the new logo seems fuzzy, could you provide a higher resolution one? @TheaGong

**Comment by TheaGong** [comment]
No problem, will try to upload again
