### ISSUE TITLE
Feature request for @ti.ad.no_grad

### ISSUE THREAD

**Issue by shwnyao** [taichi-dev/taichi#4747]
In many circumstances I need a kernel function whose autograd is not needed, such as [example](https://github.com/hzaskywalker/PlasticineLab/blob/ac1a2f7b0bbbe88706b51bf3aa9d72483e1d05b6/plb/engine/primitive/primive_base.py#L166-L176)

The current solution has always been using `@ti.ad.gradreplaced` and `@ti.ad.grad_for` which immediately return, but it makes the code very redundant. The problem gets worse when I need many more getters that need no autograd.

Therefore I propose that we have a `@ti.ad.no_grad` decorator to simplify the work. The code should be easy to implement. I could contribute if the Taichi team needs helpers.

**Comment by ailzhang** [comment]
This proposal sounds good to me! @shwnyao please feel free to send a pull request when you have time! Thanks a lot! cc: @erizmr

**Comment by erizmr** [comment]
Thanks @shwnyao !
