### ISSUE TITLE
nit: Merge Kernel.argument_names and argument_annotations

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#4749]
https://github.com/taichi-dev/taichi/blob/536cd14b024c1f00ec80fc68c1a78115f5e635ea/python/taichi/lang/kernel_impl.py#L157-L158

These two lists are often used together. We should create a small struct to hold all the argument (or parameter, more precisely) info and maintain a single list in `Kernel`.

**Comment by DongqiShen** [comment]
> We should create a small struct to hold all the argument (or parameter, more precisely) info and maintain a single list in `Kernel`.

Hi, I got a question here. I didn't know the meaning of these two lists, but I guess what your meaning is that we should put them together. For example, firstly, I defined a struct that is `struct argument {annotation, name}`. Secondly, I defined a list for this struct `argument = [{annotation_1, name_1}, {annotation_2, name_2}, ...]`.

If my understanding is correct, the element in these two lists is a one-to-one correspondence. 
I think I can do the issue if I am right or you can correct my misunderstanding.

Thanks.

**Comment by k-ye** [comment]
> If my understanding is correct, the element in these two lists is a one-to-one correspondence.

Yep, your understanding is correct! Sorry for any confusion here.

> I think I can do the issue if I am right or you can correct my misunderstanding.

Sounds great! Looking forward to your fix :-)

**Comment by k-ye** [comment]
Fixed by https://github.com/taichi-dev/taichi/pull/4753, thanks @DongqiShen !
