### ISSUE TITLE
Implicit type casting rules have been changed

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#4793]
After #4789, Taichi now has its own rules of implicit type casting, instead of simply following the behavior of C. The corresponding documentation has to be changed:
https://github.com/taichi-dev/taichi/blob/022456def2be5f592488ae983580aebb2f61525b/docs/lang/articles/basic/type.md?plain=1#L103

**Comment by FantasyVR** [comment]
Hi @strongoier, should we close this issue now?
