### ISSUE TITLE
Shifting operators should not adopt the same implicit conversion rule as other arithmetic operators

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#4795]
Shifting operators like `<<` should take the left-side type as its result type (`i8 << u32 = i8`) instead of following rules for other arithmetic operators (`i8 + u32 = u32`).

**Comment by yuanming-hu** [comment]
A not so minimal example to reproduce this issue (by @GCChen97, #4613):
```
@ti.func
def set_bit(switches, i, dt):
    switches  |= (ti.cast(1, dt) << i)
    return switches

@ti.kernel
def test():
    for _ in range(1):
        for i in range(8):
            eight_flags = ti.cast(0, ti.u8)
            eight_flags = set_bit(eight_flags, i, ti.u8)
            print(ti.cast(eight_flags, ti.i32))
test()
```

You will get a warning because `i8 << i32` leads to `i32`, which is later stored into `u8` (lose of precision).

**Comment by yuanming-hu** [comment]
The place to look at: https://github.com/taichi-dev/taichi/blob/6df23cb13063957ffe94669ffb6426f96ceccac2/taichi/transforms/type_check.cpp#L294

For shift operators we should use the left operand type as result type.
