### ISSUE TITLE
Taichi built from source takes too long time

### ISSUE THREAD

**Issue by BillXu2000** [taichi-dev/taichi#4821]
**Describe the bug**
When building taichi from source, it seems that the compilation phase is blocked at 
```
Linking CXX static library external/SPIRV-Cross/libspirv-cross-c.ac
```
This linking takes more than 5 minutes (before I end up this command).

**To Reproduce**
I built Taichi on Ubuntu 20.04.

commit 4512cccf2b927932b0e9eca42ab30b7e4a0eed83 works on my machine, and the next commit 7262bb0f7f1e3567e2bc43ac4eee0dc20fa79129 will trigger this problem.

PR #4716 between this two commits might be the cause of this problem.

**Comment by qiao-bo** [comment]
The linking phase works fine on my PC. Can you share your build flags as well?

**Comment by PGZXB** [comment]
@BillXu2000 Do you use gcc to build?
