### ISSUE TITLE
MoltenVK on Metal changes cwd to the python install directory with ti.init()

### ISSUE THREAD

**Issue by bsavery** [taichi-dev/taichi#4829]
**Describe the bug**
When using vulkan on macOS with moltenVK installed, initializing taichi will change the cwd.  It's a simple and easy to work around bug but really annoyed me when it couldn't find a local file ;)

**To Reproduce**

```py
import taichi as ti
import os

ti.init(arch=ti.metal) # switch to ti.vulkan
print(os.getcwd())
```

**Log/Screenshots**

With metal:
'/my_directory'

With vulkan 
[mvk-info] MoltenVK version 1.1.8, supporting Vulkan version 1.1.204.
        The following 72 Vulkan extensions are supported:
                VK_KHR_16bit_storage v1
                ..... lots of vulkan setup info
                
'/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/Resources'

**Comment by bsavery** [comment]
I can obviously workaround, but annoying!  Probably just needs to cache / pop the CWD when doing ti.init

**Comment by FantasyVR** [comment]
Hi @bsavery,  I think this is already solved in this PR: https://github.com/taichi-dev/taichi/pull/4812.

**Comment by k-ye** [comment]
Likely dup of https://github.com/taichi-dev/taichi/issues/4811?

**Comment by bsavery** [comment]
Definitely.  Thanks!  Sorry I should have searched more thoroughly
