### ISSUE TITLE
Simplify Taichi's Matrix implementation

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#4837]
**Concisely describe the proposed feature**

Right now Taichi's matrix implementation takes the combination of all these factors into account:

* Python vs Taichi scope
* Local or Global (i.e., Matrix within a field/Ndarray)
* Dynamic indexing or not
* Slicing or not

I'll see if there's a way to decouple the Mat impl. (cc @strongoier )

**Comment by k-ye** [comment]
I'm thinking of instantiating different types of Matrix implementations, depending on whether it is created inside Python or Taichi scope. Here are three ways I have come up with

1. Make `ti.Matrix` a (factory) function, pseudo code below:

```py
def Matrix(*args):
  if in_python_scope():
    return _PyMatImpl(*args)
  else:
    return _TiMatImpl(*args)
```

The downside is that, many places are already doing this check: `isinstance(m, ti.Matrix)`. So changing `Matrix` to a function could potentially break many things.

2. Let `ti.Matrix` have an `_impl` field, whereas `_impl` can be `_PyMatImpl` or `_TiMatImpl`. This can group operations of the same scope to the same class, which is great. Then `Matrix` is mostly a wrapper around `_impl`. The downside is that the code becomes more verbose, in that `Matrix` still has to implement the union of APIs supported in both Python and Taichi scopes. E.g.

```py
class _PyMatImpl:
  def op1_py_only(self):
    ...

class _TiMatImpl:
  def op2_ti_only(self):
    ...

class Matrix:
  def op1(self):
    self._impl.op1_py_only()

  def op2(self):
    self._impl.op2_py_only()
```

3. Adopting `__new__`

Python's `__init__` cannot return anything, but there's an escape hatch: `__new__`. See these issues of how to return subclasses from a seemingly base class's initializer:

* https://stackoverflow.com/questions/18218876/how-to-return-a-subclass-from-new-parameter
* https://stackoverflow.com/questions/28236516/python-subclassing-a-class-with-custom-new

This approach solves both 1 and 2. However, I'm not very familiar with `__new__`, and wonder in general, if this is a good use case. Any comment will be very helpful here! @Zheaoli @frostming

**Comment by frostming** [comment]
@k-ye All three practices can be seen in real-world projects, but have trade-offs.

1. If `isinstance` is widely used then we will discard this option
2. This one looks the cleanest to me.
3. This approach is the easiest for subclasses to reuse code from the base class, `django-rest-framework`'s `Serializer` uses this pattern.

To conclude, I vote for 2.

**Comment by Zheaoli** [comment]
@k-ye, All of the ways can be worked in the real world, but still slightly different here.

1. will widely depend on `isintance`
2. It Seems clean and debuggable to me
3. I think this approach is not friendly for debugging and IDE intelligence.

So, I vote for 2.

**Comment by k-ye** [comment]
@frostming @Zheaoli sweet, thanks folks! I'm also doing 2 in #4853

**Comment by ailzhang** [comment]
Hey @k-ye , would you mind elaborating a bit on our major use case for `ti.Matrix` in python scope? I can think of accessing/minor updates to the elements for now. (if this is true we also have a similar problem for `ti.field` I think? 
IIUC we care more about `ti.Matrix/field` in the taichi scope, if there're more complicated ops to be done in python scope, converting to numpy or torch and then convert it back seems reasonable?  Wdyt?

**Comment by k-ye** [comment]
Another thing that bothers me is that the Matrix behavior depends largely on the content inside the `entries`. It can be literals, `ti.Expr`, field/ndarray host accessors. And you have to track to different places to understand where these content come from.

**Comment by k-ye** [comment]
Hmm, I don't think having separate names will be a good idea for our users... It's consistent to keep them writing `ti.Matrix` without worrying too much in this case. Option 1 is unlikely the choice, because `isinstance(m, ti.Matrix)` is used not only in Taichi's codebase, unfortuantely.

**Comment by ailzhang** [comment]
@k-ye Hmm if we cannot change the name then option 2 seems fine. 
My main concern is that we union two different classes together (maybe interface/trait is more appropriate if we had it? 
For example, as a normal python user I'm used to do `dir(my_ti_Matrix_object)` to see what I can do with it and that'll give me a union of what py_matrix and ti_matrix can do.

**Comment by k-ye** [comment]
That can be controlled by `__dir__`. Also note that inside Taichi scope, you are really limited and should not do fancy Python stuff... We should probably make sure our documentation highlights the difference clearly.

**Comment by frostming** [comment]
> For example, as a normal python user I'm used to do dir(my_ti_Matrix_object) to see what I can do with it and that'll give me a union of what py_matrix and ti_matrix can do.

This can be solved by approach 3 but to keep it simple we can just raise `NotImplementError`.

**Comment by ailzhang** [comment]
@k-ye Yup I agree that we can work around it. I guess my point is when we refactor/simplify this Matrix implementation, we probably also want to take into consideration what users might do and what we want to show them. For example: 
```
import taichi as ti
ti.init()

@ti.kernel
def test():
    print(dir(ti.Matrix))

test()
```
We indeed allow python execution inside taichi scope(with a warning thrown) during compile time so this actually works :P ....
