### ISSUE TITLE
Building with TI_EXPORT_CORE:BOOL=ON failed

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#4846]
Bisected and found the root cause to be https://github.com/taichi-dev/taichi/pull/4716, @PGZXB you probably want to move https://github.com/taichi-dev/taichi/pull/4716/files#diff-a3917319b36617bdd5a229c4e02eeadcacda5e543c7d6b367385c627b9763f16R75 to somewhere else since they're not llvm-specific.?

To fix please make sure 
```
python setup.py clean && TAICHI_CMAKE_ARGS="-DTI_WITH_VULKAN:BOOL=ON -DTI_WITH_CUDA:BOOL=OFF -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_LLVM:BOOL=OFF -DTI_EXPORT_CORE:BOOL=ON" python3 setup.py build_ext
``` 
works? This is what we used for the deskop aot demo. :P

**Comment by bobcao3** [comment]
TI_EXPORT_CORE should be a part of the CI. We can probably spawn a separate task to just build it (no need to test it as of now, just make sure it builds). Also we probably need to have TI_WITH_LLVM=OFF to be included in CI as well

**Comment by ailzhang** [comment]
@bobcao3 was talking to @PGZXB about this ;) I had a PR for build only but abandoned it as we were considering adding an e2e android test. Looks like it's still useful so will resend it in a bit.
