### ISSUE TITLE
[Windows] Skip non-essential builds on AppVeyor

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#485]
**Concisely describe the proposed feature**

*We want to make AppVeyor build Taichi for Python 3.6 only for most commits, and Python 3.6/7/8 for commits with commit message starting with `[release]`.*

#### Context

Currently AppVeyor (our Windows CI service) takes too long  (~40min) to compile Taichi for Python3.6/7/8 together.
  
One property we can possibly make use of to accelerate AppVeyor: currently AppVeyor builds Taichi with Python 3.6/3.7/3.8 in serial, each taking 13 min, and 40 min in total. For most commits, we only need to build with Python 3.6. For releasing commits (e.g. those with message [release] v0.5.1), we build with all three versions of Python and upload the artifacts to PyPI.

**Describe the solution you'd like**
Execute a Python script 

https://github.com/taichi-dev/taichi/blob/83cf9c111db3ebd327dbeb1ec3a960978a587740/misc/appveyor_filter.py#L1

to test if this build is needed. 

**What needs to be done**
Implement this line
https://github.com/taichi-dev/taichi/blob/83cf9c111db3ebd327dbeb1ec3a960978a587740/appveyor.yml#L39

so that AppVeyor exits and thinks the build completes when `appveyor_filter.py` returns `0`.

It seems that `build_scripts` need to be written in Windows batch, which I have been struggling with. 

Also note that if any command returns non-zero error code, AppVeyor will exit and report a build failure instead of skipping the build. Therefore executing `%PYTHON% %TAICHI_REPO_DIR%\misc\appveyor_filter.py` in a standalone command (which already makes AppVeyor report build failure) and reusing `%errorlevel%` might not work.

**Comment by archibate** [comment]
`%PYTHON% %TAICHI_REPO_DIR%\misc\appveyor_filter.py || exit 0`.
Exit when `filter.py` return non-zero.
Should be considered as a whole line so AppVeyor can be happy :)

**Comment by yuanming-hu** [comment]
Thanks a lot to @archibate, this issue is now systematically resolved. I believe AppVeyor can serve the developer community without queuing now :-)
