### ISSUE TITLE
[ci] Windows machine failed in Cleanup process often

### ISSUE THREAD

**Issue by 0xzhang** [taichi-dev/taichi#4895]
When CI work, Windows machine failed. It happens many times from last night. It can work normal occasionally.

![windows cleanup failed](https://user-images.githubusercontent.com/33616362/166099884-53de9665-3d17-42d3-a89c-aab82ff52022.png)

And Windows machine's build process seems slow than other machines 2 times. Could it be faster?:joy:

**Comment by qiao-bo** [comment]
This should be fixed now. Let us know if there are further problems~
