### ISSUE TITLE
GGUI does not work with X-over-SSH

### ISSUE THREAD

**Issue by ShengdingHu** [taichi-dev/taichi#4905]
**Describe the bug**
Error runing voxel_art/main.py

<img width="968" alt="image" src="https://user-images.githubusercontent.com/32740627/166721279-37169247-1462-4991-b1e6-7c8dc5518e2c.png">

**To Reproduce**
I am new to Taichi, so I am sorry I can't figure out which part might give the bug. What did I do is that I run "ssh -XY xxx@xxx.xxx.xxx.xxx" with XQuartz, I use Taichi version 1.0.1,  The machine is Ubuntu 20.04, 

and I
```bash
cd voxel-art
python main.py
```

Update:
After I do some debug, I found that it's the following code that gives the error. 
```
# voxel-art/scene.py#Line112
        self.window = ti.ui.Window("Taichi Voxel Renderer",
                                   SCREEN_RES,
                                   vsync=True)

```

And previously I encounter the "glfw not initialized" error, I fix it by
```
sudo apt-get update -y && 
sudo apt-get install -y mesa-utils &&
sudo  apt install libglew-dev libglfw3-dev
```
After that the reported bug occurs, I don't know whether it is related to glfw. 

Note that no matter what architecture I choose (cuda/vulkan/cpu) I all encountered this error. 

Update:
I can run taichi with ti.GUI, but fail with ti.ui.Window

**Comment by bobcao3** [comment]
Taichi GGUI can not run over X-over-SSH because it uses Vulkan. You will need to run it locally, sorry about that.

**Comment by bobcao3** [comment]
Maybe we can add a cli-rendering option with voxel challenge. @k-ye @yuanming-hu

**Comment by ShengdingHu** [comment]
Sadly, I encountered other errors on my mac locally. I might post another issue for the problem.

**Comment by yuanming-hu** [comment]
> Maybe we can add a cli-rendering option with voxel challenge. @k-ye @yuanming-hu

Technically that's possible, but currently, the UI heavily relies on the user's adjustment of the camera. We likely need to add an API to allow setting camera position too. Maybe we do that in the next round of competition :-)
