### ISSUE TITLE
Error running voxel-art/main.py on mac locally

### ISSUE THREAD

**Issue by ShengdingHu** [taichi-dev/taichi#4906]
**Describe the bug**
I am transferring from issue #4905, I started running voxel-art locally on my mac. But I have a new bug when running ti.ui.Window

**To Reproduce**
My mac system info is 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/32740627/166848133-cfc89573-de4a-4093-b822-310306451c0f.png">

taichi==1.0.1

the minimum bug code is
```
import taichi as ti
SCREEN_RES = (1280, 720)
ti.init(arch=ti.gpu)
window = ti.ui.Window("Taichi Voxel Renderer",
                                   SCREEN_RES,
                                   vsync=True)  # this line have error
```
The error screenshot is  (very long, I add separator at the end of it )

## Begin error msg.

[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, osx, python 3.8.2
[Taichi] Starting on arch=metal
[mvk-info] MoltenVK version 1.1.9, supporting Vulkan version 1.1.211.
	The following 69 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_surface v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_swapchain_colorspace v4
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_trinary_minmax v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v34
		VK_NV_glsl_shader v1
[mvk-info] GPU device:
		model: Intel(R) Iris(TM) Plus Graphics
		type: Integrated
		vendorID: 0x8086
		deviceID: 0x8a53
		pipelineCacheUUID: 0000277D-0A0F-07D2-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 2.2
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance for Vulkan version 1.0.0, as requested by app, with the following 0 Vulkan extensions enabled:
[mvk-info] MoltenVK version 1.1.9, supporting Vulkan version 1.1.211.
	The following 69 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_surface v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_swapchain_colorspace v4
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_trinary_minmax v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v34
		VK_NV_glsl_shader v1
2022-05-05 08:33:49.036 python[30136:475708] -[__NSCFType name]: unrecognized selector sent to instance 0x6000020cde10
[E 05/05/22 08:33:49.036 475708] Received signal 11 (Segmentation fault: 11)

                            * Taichi Core - Stack Traceback *                             
==========================================================================================
|                       Module |  Offset | Function                                      |
|----------------------------------------------------------------------------------------|
*               taichi_core.so |     126 | taichi::Logger::error(std::__1::basic_string< |
                                         | char, std::__1::char_traits<char>, std::__1:: |
                                         | allocator<char> > const&, bool)               |
*               taichi_core.so |     228 | taichi::(anonymous namespace)::signal_handler |
                                         | (int)                                         |
*     libsystem_platform.dylib |      29 | (null)                                        |
*                          ??? |       0 | (null)                                        |
*            libMoltenVK.dylib |     228 | (null)                                        |
*               taichi_core.so |      37 | taichi::lang::vulkan::VulkanDevice::~VulkanDe |
                                         | vice()                                        |
*               taichi_core.so |      14 | taichi::lang::vulkan::VulkanDevice::~VulkanDe |
                                         | vice()                                        |
*               taichi_core.so |     730 | taichi::lang::vulkan::VulkanDeviceCreator::Vu |
                                         | lkanDeviceCreator(taichi::lang::vulkan::Vulka |
                                         | nDeviceCreator::Params const&)                |
*               taichi_core.so |    1434 | taichi::ui::vulkan::AppContext::init(taichi:: |
                                         | lang::Program*, GLFWwindow*, taichi::ui::AppC |
                                         | onfig const&)                                 |
*               taichi_core.so |      22 | taichi::ui::vulkan::Renderer::init(taichi::la |
                                         | ng::Program*, GLFWwindow*, taichi::ui::AppCon |
                                         | fig const&)                                   |
*               taichi_core.so |     204 | taichi::ui::vulkan::Window::init(taichi::lang |
                                         | ::Program*, taichi::ui::AppConfig const&)     |
*               taichi_core.so |     185 | taichi::ui::vulkan::Window::Window(taichi::la |
                                         | ng::Program*, taichi::ui::AppConfig const&)   |
*               taichi_core.so |     318 | taichi::ui::PyWindow::PyWindow(taichi::lang:: |
                                         | Program*, std::__1::basic_string<char, std::_ |
                                         | _1::char_traits<char>, std::__1::allocator<ch |
                                         | ar> >, pybind11::tuple, bool, bool, std::__1: |
                                         | :basic_string<char, std::__1::char_traits<cha |
                                         | r>, std::__1::allocator<char> >, taichi::Arch |
                                         | , bool)                                       |
*               taichi_core.so |     183 | taichi::ui::PyWindow* pybind11::detail::initi |
                                         | mpl::construct_or_initialize<taichi::ui::PyWi |
                                         | ndow, taichi::lang::Program*, std::__1::basic |
                                         | _string<char, std::__1::char_traits<char>, st |
                                         | d::__1::allocator<char> >, pybind11::tuple, b |
                                         | ool, bool, std::__1::basic_string<char, std:: |
                                         | __1::char_traits<char>, std::__1::allocator<c |
                                         | har> >, taichi::Arch, bool, 0>(taichi::lang:: |
                                         | Program*&&, std::__1::basic_string<char, std: |
                                         | :__1::char_traits<char>, std::__1::allocator< |
                                         | char> >&&, pybind11::tuple&&, bool&&, bool&&, |
                                         |  std::__1::basic_string<char, std::__1::char_ |
                                         | traits<char>, std::__1::allocator<char> >&&,  |
                                         | taichi::Arch&&, bool&&)                       |
*               taichi_core.so |     179 | pybind11::class_<taichi::ui::PyWindow> pybind |
                                         | 11::detail::argument_loader<pybind11::detail: |
                                         | :value_and_holder&, taichi::lang::Program*, s |
                                         | td::__1::basic_string<char, std::__1::char_tr |
                                         | aits<char>, std::__1::allocator<char> >, pybi |
                                         | nd11::tuple, bool, bool, std::__1::basic_stri |
                                         | ng<char, std::__1::char_traits<char>, std::__ |
                                         | 1::allocator<char> >, taichi::Arch, bool>::ca |
                                         | ll_impl<void, void pybind11::detail::initimpl |
                                         | ::constructor<taichi::lang::Program*, std::__ |
                                         | 1::basic_string<char, std::__1::char_traits<c |
                                         | har>, std::__1::allocator<char> >, pybind11:: |
                                         | tuple, bool, bool, std::__1::basic_string<cha |
                                         | r, std::__1::char_traits<char>, std::__1::all |
                                         | ocator<char> >, taichi::Arch, bool>::execute< |
                                         | pybind11::class_<taichi::ui::PyWindow>, 0>(py |
                                         | bind11::class_<taichi::ui::PyWindow>&)::'lamb |
                                         | da'(pybind11::detail::value_and_holder&, taic |
                                         | hi::lang::Program*, std::__1::basic_string<ch |
                                         | ar, std::__1::char_traits<char>, std::__1::al |
                                         | locator<char> >, pybind11::tuple, bool, bool, |
                                         |  std::__1::basic_string<char, std::__1::char_ |
                                         | traits<char>, std::__1::allocator<char> >, ta |
                                         | ichi::Arch, bool)&, 0ul, 1ul, 2ul, 3ul, 4ul,  |
                                         | 5ul, 6ul, 7ul, 8ul, pybind11::detail::void_ty |
                                         | pe>(void pybind11::detail::initimpl::construc |
                                         | tor<taichi::lang::Program*, std::__1::basic_s |
                                         | tring<char, std::__1::char_traits<char>, std: |
                                         | :__1::allocator<char> >, pybind11::tuple, boo |
                                         | l, bool, std::__1::basic_string<char, std::__ |
                                         | 1::char_traits<char>, std::__1::allocator<cha |
                                         | r> >, taichi::Arch, bool>::execute<pybind11:: |
                                         | class_<taichi::ui::PyWindow>, 0>(pybind11::cl |
                                         | ass_<taichi::ui::PyWindow>&)::'lambda'(pybind |
                                         | 11::detail::value_and_holder&, taichi::lang:: |
                                         | Program*, std::__1::basic_string<char, std::_ |
                                         | _1::char_traits<char>, std::__1::allocator<ch |
                                         | ar> >, pybind11::tuple, bool, bool, std::__1: |
                                         | :basic_string<char, std::__1::char_traits<cha |
                                         | r>, std::__1::allocator<char> >, taichi::Arch |
                                         | , bool)&, std::__1::integer_sequence<unsigned |
                                         |  long, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul |
                                         | , 8ul>, pybind11::detail::void_type&&) &&     |
*               taichi_core.so |      76 | void pybind11::cpp_function::initialize<void  |
                                         | pybind11::detail::initimpl::constructor<taich |
                                         | i::lang::Program*, std::__1::basic_string<cha |
                                         | r, std::__1::char_traits<char>, std::__1::all |
                                         | ocator<char> >, pybind11::tuple, bool, bool,  |
                                         | std::__1::basic_string<char, std::__1::char_t |
                                         | raits<char>, std::__1::allocator<char> >, tai |
                                         | chi::Arch, bool>::execute<pybind11::class_<ta |
                                         | ichi::ui::PyWindow>, 0>(pybind11::class_<taic |
                                         | hi::ui::PyWindow>&)::'lambda'(pybind11::detai |
                                         | l::value_and_holder&, taichi::lang::Program*, |
                                         |  std::__1::basic_string<char, std::__1::char_ |
                                         | traits<char>, std::__1::allocator<char> >, py |
                                         | bind11::tuple, bool, bool, std::__1::basic_st |
                                         | ring<char, std::__1::char_traits<char>, std:: |
                                         | __1::allocator<char> >, taichi::Arch, bool),  |
                                         | void, pybind11::detail::value_and_holder&, ta |
                                         | ichi::lang::Program*, std::__1::basic_string< |
                                         | char, std::__1::char_traits<char>, std::__1:: |
                                         | allocator<char> >, pybind11::tuple, bool, boo |
                                         | l, std::__1::basic_string<char, std::__1::cha |
                                         | r_traits<char>, std::__1::allocator<char> >,  |
                                         | taichi::Arch, bool, pybind11::name, pybind11: |
                                         | :is_method, pybind11::sibling, pybind11::deta |
                                         | il::is_new_style_constructor>(pybind11::class |
                                         | _<taichi::ui::PyWindow>&&, void (*)(pybind11: |
                                         | :detail::value_and_holder&, taichi::lang::Pro |
                                         | gram*, std::__1::basic_string<char, std::__1: |
                                         | :char_traits<char>, std::__1::allocator<char> |
                                         |  >, pybind11::tuple, bool, bool, std::__1::ba |
                                         | sic_string<char, std::__1::char_traits<char>, |
                                         |  std::__1::allocator<char> >, taichi::Arch, b |
                                         | ool), pybind11::name const&, pybind11::is_met |
                                         | hod const&, pybind11::sibling const&, pybind1 |
                                         | 1::detail::is_new_style_constructor const&):: |
                                         | 'lambda'(pybind11::detail::function_call&)::o |
                                         | perator()(pybind11::detail::function_call&) c |
                                         | onst                                          |
*               taichi_core.so |    4691 | pybind11::cpp_function::dispatcher(_object*,  |
                                         | _object*, _object*)                           |
*                    python3.8 |      72 | (null)                                        |
*                    python3.8 |     161 | (null)                                        |
*                    python3.8 |     730 | (null)                                        |
*                    python3.8 |     123 | (null)                                        |
*                    python3.8 |     427 | (null)                                        |
*                    python3.8 |     295 | (null)                                        |
*               taichi_core.so |      30 | (null)                                        |
*                    python3.8 |     161 | (null)                                        |
*                    python3.8 |     305 | (null)                                        |
*                    python3.8 |   48944 | (null)                                        |
*                    python3.8 |     439 | (null)                                        |
*                    python3.8 |     398 | (null)                                        |
*                    python3.8 |     233 | (null)                                        |
*                    python3.8 |     186 | (null)                                        |
*                    python3.8 |     295 | (null)                                        |
*                    python3.8 |     161 | (null)                                        |
*                    python3.8 |     305 | (null)                                        |
*                    python3.8 |   49410 | (null)                                        |
*                    python3.8 |     439 | (null)                                        |
*                    python3.8 |     366 | (null)                                        |
*                    python3.8 |     391 | (null)                                        |
*                    python3.8 |    3472 | (null)                                        |
*                    python3.8 |    1769 | (null)                                        |
*                    python3.8 |      57 | (null)                                        |
*                         dyld |     462 | (null)                                        |
==========================================================================================

Internal error occurred. Check out this page for possible solutions:

## End error msg
---------

**Additional comments**
I have to admit that I am new to the graphic rendering engines, I also tried vulkan. But it reports an error at 
```
ti.init(arch=ti.vulkan)
```
## Begin error msg
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, osx, python 3.8.2
[mvk-info] MoltenVK version 1.1.9, supporting Vulkan version 1.1.211.
	The following 69 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_surface v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_swapchain_colorspace v4
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_trinary_minmax v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v34
		VK_NV_glsl_shader v1
[mvk-info] GPU device:
		model: Intel(R) Iris(TM) Plus Graphics
		type: Integrated
		vendorID: 0x8086
		deviceID: 0x8a53
		pipelineCacheUUID: 0000277D-0A0F-07D2-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 2.2
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance for Vulkan version 1.0.0, as requested by app, with the following 0 Vulkan extensions enabled:
[Taichi] Starting on arch=vulkan
[mvk-info] MoltenVK version 1.1.9, supporting Vulkan version 1.1.211.
	The following 69 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_surface v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_swapchain_colorspace v4
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_trinary_minmax v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v34
		VK_NV_glsl_shader v1
[1]    30943 segmentation fault  python trydebug.py

## End error msg

And I run the examples in taichi/python/taichi/examples/rendering/, It works as normal, which uses `ti.gpu` in `ti.init` .

Moreover, I noticed another issue #4761, are they related?  On the surface there are some differences from my perspective.

Thanks! Looking forward to running the voxel-art soon.

**Comment by ailzhang** [comment]
Hey @ShengdingHu , @FantasyVR has exactly the same GPU as yours and #4761 might indeed be related as he has seen the error above occasionally as well. We've also seen a few other issues with GGUI on Intel graphics card listed in #4919 . Shall we track your issue in #4761 for now, thanks a lot!

**Comment by FantasyVR** [comment]
Hi @ShengdingHu , I encounter the same problems when using GGUI. It actually is a MoltenVK bug. It's solved [here](https://github.com/KhronosGroup/MoltenVK/issues/1580#issuecomment-1122965111). Taichi uses brew installed `libmoltenvk.dylib`, so the problem couldn't be solved instantly. You could download a new built `libmoltenvk.dylib` on my Mac and replace the old one in Taichi. The download link is [here](https://drive.google.com/file/d/1yd8zJl3JoA-aebrppWfI-snMoQUuoSe6/view?usp=sharing)

**Comment by ShengdingHu** [comment]
Thanks! It worked! Feel free to close the issue.
