### ISSUE TITLE
Very slow drawing (bad perfomance)

### ISSUE THREAD

**Issue by compik710** [taichi-dev/taichi#4922]
Hello! I ran into a performance issue.

In my original code, I needed to fill a certain area of pixels, but this slowed down performance... and i dont know why
Then I tried to write a small code with a simple fill, however... I was very surprised to see a very low fps for such a simple task.

For comparison 640x320 pixels:
![shot1](https://user-images.githubusercontent.com/68602173/167111763-801ea354-231d-4fd6-a7aa-7becb650df51.png)

And 1440x720 pixels:
![shot2](https://user-images.githubusercontent.com/68602173/167111849-99f9c5b2-7ad4-428a-9f54-4c92df4020e8.png)

My mini code:
`
import taichi as ti

ti.init(arch=ti.opengl)

n = 720 # 320 # for comparison I changed this line
pixels = ti.field(dtype=float, shape=(n * 2, n))

@ti.kernel
def paint():
    for i, j in pixels:
        pixels[i, j]=.5

gui = ti.GUI("Window", res=(n * 2, n))
gui.fps_limit=240

while 1:
    paint()
    gui.set_image(pixels)
    gui.show()
`

I need high fps for such simple tasks, but fps on image2, to small (((
Does anyone know how to solve the problem? Thank you!

**Comment by k-ye** [comment]
In case you don't have access to Vulkan, you might also want to take a look at `fast_gui`: https://docs.taichi-lang.org/lang/articles/gui_system#zero-copying-frame-buffer
