### ISSUE TITLE
unexpected behavior with Hilles-Steele scan 

### ISSUE THREAD

**Issue by bcolloran** [taichi-dev/taichi#4934]
I'm not sure if this is a bug of some kind, or just user error/misunderstanding of how Taichi is supposed to work, but I was surprised by the behavior in the code example below.

This snippet implements a simple Hilles-Steele scan and uses it to attempt get the cumulative sum of a 100000 element field filled with 1s.

The output is fine up until the 30720th entry in the array, after which the entries are incorrect, and non-derministic. For example, the last element of the output array should of course be 100000, but I've been seeing values from 210000 to 290000 ish.

The number 30720 looked suspicious to me, and indeed it's 16*1920, the latter of which is the number of CUDA cores available in my Nvidia RTX 2060.

I don't really know what is going wrong -- my best guess is that it seems to be some kind of race situation, in particular because of the appearance of that magic number 30720... maybe the hardware is saturated, and <something something> data race? But I'm not really sure why there would be a race condition -- I've certainly run parallel `for` loops over fields with many more elements than this without any issues.

This scan implementation is inspired by the `parallel_sort` function in `python/taichi/_kernels.py`, and I have noticed that that function includes a `sync()` call. I've tried putting `sync()` in a many different places with no change in the values I'm seeing, but I wonder if I need to use `sync()` somehow, or some other low-level runtime method like that?

Finally, in case it might be helpful for writing docs that guide other users away from whatever I am misunderstanding, I'll add a bit of background about why I found this behavior surprising (and, I guess relatedly, why I was surprised that a `sync()` function even exists, and was surprised it would be needed in `parallel_sort`): In my mental model of Taichi, and based on the examples I've looked at, I have been assuming that from the perspective of the python code calling the kernels, kernel invocations are inherently serial and synchronous. That is: if you have python code like...
```python
ti_kernel_1()
ti_kernel_2()
ti_kernel_3()
```
...then all of the GPU work associated with `ti_kernel_1` will finish before any of `ti_kernel_2`'s work starts, and all of `ti_kernel_2`'s work will finish before ti_kernel_3` starts, and it should not be possible to have data races between these kernels. The existence of the `sync()` function seem like a hint to me my mental model is not correct, because it seems like it would not be needed if all kernel invocations were serial and synchronous.

So I guess perhaps this is an area of the docs that might benefit from some clarification:
- when are kernels launched async/parallel vs sync/serial? and how is this controlled?
- when can kernel invocations result in race conditions between subsequent invocations? how can these race conditions be prevented?
- what does the `sync()` function do, and when is it needed?

Thanks as always for the great work on Taichi! I'm always learning something fun when I work with it :-) (And I'm sure I will learn a lot from whatever I'm misunderstanding in this example!)

### My non-working scan code

```python
import taichi as ti
import numpy as np

ti.init(arch=ti.gpu)

@ti.kernel
def fill_int(field: ti.template(), x: int):
    for i in field:
        field[i] = x


def prepare_HS_scan(in_field, out_field, ti_func):
    @ti.kernel
    def scan_stage(last: ti.template(), step: int):
        for i in last:
            out_field[i] = last[i] if i < step else ti_func(last[i - step], last[i])

    def scan():
        step = 1
        while step < N:
            last = in_field if step == 1 else out_field
            scan_stage(last, step)
            step = step * 2

    return scan


@ti.func
def ti_sum(a, b):
    return a + b


N = int(100000)
field_in = ti.field(ti.int32, shape=N)
fill_int(field_in, 1)

field_out = ti.field(ti.int32, shape=N)

scan1 = prepare_HS_scan(in_field=field_in, out_field=field_out, ti_func=ti_sum)

scan1()

field_out_np = field_out.to_numpy()

# last value in the array
# should be 100000, non-deterministic output from 220000 to 280000 ish
print(field_out[N - 1])

# first element of the arrays that doesn't match
# always 30720 on my machine, which is 1920*16 -- RTX2060 has 1920 cuda cores
print(np.argmin(np.equal(field_out_np, np.arange(1, N + 1))))
```

Example output from the above (including version and system info)
```
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.9.7
[Taichi] Starting on arch=cuda
290112
30720
```

**Comment by bobcao3** [comment]
That sync is for dealing with a previous bug in Vulkan. Speaking of Vulkan, can you try this on Vulkan as well so that we can narrow down the problem a bit. (If Vulkan also shows a wrong number we might have a CHI-IR level problem, if not then we have a CUDA runtime / codegen problem) Thanks!

**Comment by bcolloran** [comment]
Thanks for the fast reply @bobcao3!

Indeed, I get similar behavior with `ti.init(arch=ti.vulkan)`. Example output:
```
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.9.7
[Taichi] Starting on arch=vulkan
[I 05/08/22 21:11:43.047 140724] [vulkan_device_creator.cpp:pick_physical_device@363] Found Vulkan Device 0 (NVIDIA GeForce RTX 2060)
[I 05/08/22 21:11:43.047 140724] [vulkan_device_creator.cpp:pick_physical_device@363] Found Vulkan Device 1 (llvmpipe (LLVM 12.0.0, 256 bits))
[I 05/08/22 21:11:43.048 140724] [vulkan_device_creator.cpp:create_logical_device@431] Vulkan Device "NVIDIA GeForce RTX 2060" supports Vulkan 0 version 1.2.175
305088
30720
```

Just to see what would happen, I also decided to try it out with `ti.cpu`... in this case I got very different (incorrect) results. In case it will be helpful, here are some example outputs:
```
$ python scan_error.py 
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.9.7
[Taichi] Starting on arch=x64
41257076
4


$ python scan_error.py 
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.9.7
[Taichi] Starting on arch=x64
-1087188976
4


$ python scan_error.py 
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.9.7
[Taichi] Starting on arch=x64
919975044
4


$ python scan_error.py 
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.9.7
[Taichi] Starting on arch=x64
-1183775544
4


$ python scan_error.py 
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.9.7
[Taichi] Starting on arch=x64
-14705324
4
```
(that is with AMD Ryzen 5 2600 Six-Core Processor)

Please let me know if I can supply any more information! :-)

**Comment by bcolloran** [comment]
(Oh, one more quick question @bobcao3: just for my understanding, does your comment indicate that this behavior _is_ a bug, and not user error on my part in the code above? Thanks! :-) )

**Comment by bobcao3** [comment]
Just checked your code, it seems out_field might be used as both input and output in some cases? That might be why this produces non deterministic outputs

**Comment by bcolloran** [comment]
@bobcao3 you are of course entirely correct... well I feel foolish for taking your time! Thank you for your patience and help, and apologies for the noise!
