### ISSUE TITLE
How to return big sparse data to python scope?

### ISSUE THREAD

**Issue by jhonsonlaid** [taichi-dev/taichi#4937]
I have a big sparse field `x` to be returned to python scope. However, if I simply use `x.to_numpy()`, it results in too much overhead. The `to_numpy` operation is executed every frame, which reduces program performance greatly. I get a bit tricky way in my case (see the code).  Is there a more elegant and efficient way?

```python
import taichi as ti
import numpy as np

ti.init(arch=ti.cuda)


x = ti.field(ti.f32)
block = ti.root.pointer(ti.ij, (16, 2048))
pixel = block.bitmasked(ti.k, 2048)
pixel.place(x)


y = ti.field(ti.i32)
blocky = ti.root.dense(ti.i, 3)
pixely = blocky.dynamic(ti.j, 8)
pixely.place(y)


z = ti.field(ti.i32)
pixelz = ti.root.dynamic(ti.i, 3 * 8)
pixelz.place(z)


@ti.kernel
def activate():
    x[1, 1, 1] = 1
    x[2, 2, 2] = 1
    x[3, 3, 3] = 1
    x[4, 4, 4] = 1


@ti.kernel
def print_active():

    # ti.loop_config(parallelize=1) # ti.append() still not keep order
    for i, j, k in x:
        print(i, j, k)
        ti.append(pixely, 0, i)
        ti.append(pixely, 1, j)
        ti.append(pixely, 2, k)

    for i, j, k in x:
        ti.append(pixelz, 0, i * 100000000 + j * 10000 + k)


activate()
print_active()

# Works, Too much overhead
x = x.to_numpy()
print(x.nonzero())
# (array([1, 2, 3, 4], dtype=int64), array([1, 2, 3, 4], dtype=int64), array([1, 2, 3, 4], dtype=int64))

# Error, not keep order
print(y.to_numpy())
# [[1 3 2 4 0 0 0 0]
#  [3 2 4 1 0 0 0 0]
#  [1 3 2 4 0 0 0 0]]

# Works, but tricky. NOT Work, when to return float/more/larger values.
print(z.to_numpy())
# [100010001 200020002 400040004 300030003 ...]
```

PS: `ti.append`  ti.append only works on i32/f32 nodes, but cannot provide float values?

**Comment by bobcao3** [comment]
How sparse is the field? (We don't have a good builtin way to get sparse values out at this moment, you might need an compaction or export kernel of some sorts ...)

**Comment by jhonsonlaid** [comment]
> How sparse is the field? (We don't have a good builtin way to get sparse values out at this moment, you might need an compaction or export kernel of some sorts ...)

For ``16*2048 *2048``, the typical result is smaller than ``2048``. How to write a compaction or export kernel?

**Comment by bobcao3** [comment]
You can write a range for over the loop, and then write the index and value into a dense field

**Comment by jhonsonlaid** [comment]
> You can write a range for over the loop, and then write the index and value into a dense field

Do you mean a dense field like `x` in my code? It results in too much overhead.

**Comment by bobcao3** [comment]
No I didn't mean putting the entire thing into a dense node, I mean you create a new dense node to store the active indices with the data.

**Comment by jhonsonlaid** [comment]
In real cases, the **active indices** are  `some_other_func` results, whose **sizes and values are not predictable**,  so I use a large dense node or a dynamic node.  I have no idea how to use a small dense node to store active indices, could you show me example codes?

**Comment by bobcao3** [comment]
You can first have a kernel that counts the active indices.

Let's say you have a sparse field x,

```
def get_data_from_x():
    @ti.kernel
    def count_active():
        count = 0
        for i, j, k in x:
            count += 1
        return count
    @ti.kernel
    def transfer_data(data_indices : ti.any_arr(element_dim=1), data : ti.any_arr(element_dim=1)):
        count = 0
        for i, j, k in x:
            data_indices[count] = ti.Vector([i, j, k])
            data[count] = x[i, j, k]
            count += 1
    active_count = count_active()
    np_indices = np.zeros((active_count , 3))
    np_data = np.zeros(active_count)
    transfer_data(np_indices, np_data)
    return np_indices, np_data

**Comment by jhonsonlaid** [comment]
Thank you for your example code,  I have tried this method before, but  `count` doesn't work as expected, so I gave up. After some `print` debugging your code, I find `print(count)` after `count += 1` works as expected, so the code should be modified like this. And could you explain the `count` behavior in  `count_active()` ?
```
@ti.kernel
def count_active() -> ti.i32:
    count = 0
    for i, j, k in x:
        print(count)  # always 0
        count += 1
        print(count)  # 1, 2, 3, 4. But I don't know why
    print(count)  # 4
    return count


@ti.kernel
def transfer_data(data_indices: ti.any_arr(element_dim=1)):
    count = 0
    for i, j, k in x:
        # data_indices[count] = ti.Vector([i, j, k])   # Error, always transfer to data_indices[0]
        count += 1
        data_indices[count - 1] = ti.Vector([i, j, k]  # Works
```

**Comment by jim19930609** [comment]
It's actually caused by data conflict of "count". Taking the following kernel as an example:

```
@ti.kernel
def transfer_data(data_indices: ti.any_arr(element_dim=1)):
    count = 0 
    for i, j, k in x:
        count += 1
        data_indices[count-1] = ti.Vector([i, j, k]) 
```

Lowered to CHI IR as: 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/22334008/170182153-1c195fb0-25b1-4b75-9cdc-e4e215e45823.png">

Note that `$14` is the address corresponding to the variable `count`. The problem is that the two "consecutive" operations `atomic_add` and `global_load` are not atomic. If a thread got interrupted right after finishing `atomic_add`, the variable `count`'s value can keep increasing before the `global_load` is performed. 

That explains the weird values you might have noticed in `data_indices`:

<img width="126" alt="image" src="https://user-images.githubusercontent.com/22334008/170183014-2796d430-b7ac-4264-8b3c-286be2cddca7.png">

**Comment by jim19930609** [comment]
Thanks to @ailzhang's advice, you can probably try replacing `count += 1` with `old_count = ti.atomic_add(count, 1)`, then use `old_count` to index `np_indices`. 

I tried the following example locally and it seems to work with CUDA backend:

```
import taichi as ti
import numpy as np

ti.init(arch=ti.cuda, print_ir=True)

x = ti.field(ti.f32)
block = ti.root.pointer(ti.ij, (16, 2048))
pixel = block.bitmasked(ti.k, 2048)
pixel.place(x)

@ti.kernel
def activate():
    for i in range(64):
        x[0, i, i] = 1

@ti.kernel
def count_active() -> ti.i32:
    count = 0
    for i, j, k in x:
        count += 1
    return count

@ti.kernel
def transfer_data(data_indices: ti.any_arr(element_dim=1)):
    count = 0
    for i, j, k in x:
        old_count = ti.atomic_add(count, 1)
        data_indices[old_count] = ti.Vector([i, j, k])

if __name__ == "__main__":
    activate()

    counts = count_active()
    np_indices = np.zeros((counts, 3))

    transfer_data(np_indices)
    print(np_indices)
```
