### ISSUE TITLE
Intel(R) Xe Graphics (TGL GT2)" supports Vulkan 0 version 1.2.182 + Ubuntu 20.04 GGUI crashes after showing a few frames

### ISSUE THREAD

**Issue by FantasyVR** [taichi-dev/taichi#4952]

**Comment by ailzhang** [comment]
@FantasyVR I've confirmed this issue is fixed on the latest nightly. Would you mind help double check if you still have the machine? Thanks a lot!

**Comment by neozhaoliang** [comment]
@ailzhang This issue is exactly for reporting the problem on my laptop, I think we can close it now.
