### ISSUE TITLE
[Lang] Matrix Indexing a row returns a single element

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#4966]
For a `ti.Matrix`, I want to visit its rows by `m[0]`, `m[1]`, ..., etc. But this only returns the fisrt, second, ..., element in row majored order, and I can only use indexes in range `(0, nrows)`.

Example code:

```
import taichi as ti
from taichi.math import *
ti.init()

@ti.kernel
def test():
    m = mat2([[1, 2], [3, 4]])
    print(m[0])  # 1
    print(m[1])  # 3
    print(m[2])  # error

test()
```

**Comment by k-ye** [comment]
You can use `m[0, :]` to slice a portion of the matrix?

**Comment by neozhaoliang** [comment]
This is the result that slicing returns:

```
import taichi as ti
from taichi.math import *
ti.init()

@ti.kernel
def test():
    m = mat2([[1, 2], [3, 4]])
    print(m[0: ]) 
    print(m[1: ]) 

test()

[1.000000, 3.000000]
[3.000000
```
Not the expected results (should return the firse and second columns)

**Comment by k-ye** [comment]
Hmm, try `m[:, 0]` then. Meanwhile, this feels like a bug in the slicing semantics? @strongoier @mzmzm

**Comment by neozhaoliang** [comment]
`m[:, 0]` returns similar result:

```
import taichi as ti
from taichi.math import *
ti.init()

@ti.kernel
def test():
    m = mat2([[1, 2], [3, 4]])
    print(m[: 0])  # 1
    print(m[: 1])  # 3

test()
# [1.000000, 3.000000]
# [1.000000]
```

**Comment by strongoier** [comment]
@neozhaoliang The correct syntax is `m[0, :]` instead of `m[0: ]`.

**Comment by neozhaoliang** [comment]
Thanks, it works now.

Btw, for a matrix, shall we make `m[0, :]` also return a column vector which is a matrix of shape `(rows, 1)`, not a row vector?

```
print(m[0, :])
# [[1.000000, 2.000000]]
```

**Comment by strongoier** [comment]
> Btw, for a matrix, shall we make m[0, :] also return a column vector, which is a matrix of shape (rows, 1), not a row vector?

This seems reasonable. @mzmzm
