### ISSUE TITLE
[CI] Properly handle sccache file permission in Linux GPU workflow

### ISSUE THREAD

**Issue by qiao-bo** [taichi-dev/taichi#4967]
At the moment, we tar and copy the checked-out code from our GPU Linux job into the executed docker container. 
https://github.com/taichi-dev/taichi/blob/80f20f25279112bcdf012ece57de2033d8b046be/.github/workflows/testing.yml#L273
This was implemented some time ago for sccache handling (https://github.com/taichi-dev/taichi/pull/3559). We need a better way to handle this because this step introduces two major problems in our CI.

1. The specified PID and GID must match the buildbot's execution user. Note that the value 1000 as specified, typically this value is assigned to the first user on e.g., Ubuntu. In another words, if a buildbot has two users, and we use the second one to execute the docker container. We will not match the permissions in the file system and some errors such as `cannot write to metadata.tcb` will be reported.
2. This leaves our GPU Linux CI _dirty_. As we implicitly rely on the checkout code of the Linux job, which on our self hosted runner is of location `github-actions/_work/taichi/taichi`. This folder is not deleted between different runs. The problem now is analogous to Windows workflow.  

Welcome any suggestions!

**Comment by qiao-bo** [comment]
CC @ailzhang @frostming 

@lin-hitonami any idea of what are the alternatives to handle sccache?

**Comment by ailzhang** [comment]
cc: @feisuzhu fyi this might be an interesting issue for you - a great start to cleanup our docker related mess :P

**Comment by feisuzhu** [comment]
Issue is irrelevant now.
