### ISSUE TITLE
Replace Arch::x86_64 with Arch::cpu

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#497]
We may expand taichi into other ISA, eg. arm, mips, x86_32. They can have GPU too. Also I notice that we aren't really dependent on instruction sets, i.e. assembly codes. So I personally think `Arch::cpu` is better.

**Comment by yuanming-hu** [comment]
My feeling is that after adding more CPU backends we will need to slightly distinguish them from each other, so I prefer to keep `Arch::x86_64`.

For end-users, we can add `ti.cpu`, which automatically translates to `Arch::x86_64`, `Arch::arm`, `Arch::powerpc` etc. The same for `ti.gpu`.

**Comment by Psycho7** [comment]
Having `x86_64`, `arm`, `powerpc` etc. looks better for me, unless `cpu` can handle them all.

**Comment by k-ye** [comment]
FYI, I think we can have `Arch::cpu`. But it should be an arch router that picks `x86`, `x64`, `arm` etc  for the users depending on their hardware. Same for `Arch::gpu`, which does for `cuda`, `metal`, `opengl`, etc...
