### ISSUE TITLE
PaddlePaddle module causes random failure of "Illegal Instruction" on Linux CI build-bot

### ISSUE THREAD

**Issue by jim19930609** [taichi-dev/taichi#4973]
**Describe the bug**
Paddle module seems to introduce a random CI failure on the Linux built-bot. It fails at "ti diagnose" and reports a core dump with "Illegal Instructions". Refer to the log below for further information.

**To Reproduce**
CI-bot: Build and Test / Build and Test linux (CPU) (ubuntu-latest, py39, ON, cpu,cc)

Fails randomly.

**Log/Screenshots**
[full_log.txt](https://github.com/taichi-dev/taichi/files/8683692/full_log.txt)

![Screenshot from 2022-05-13 10-37-58](https://user-images.githubusercontent.com/22334008/168200459-c6ce845a-6829-4561-8cbc-b3c53468ace1.png)

**Diagnose**
The failure is triggered by "ti diagnose" and does not seem to enter the main function of "ti diagnose". Very likely it fails immediately at "import paddle", which does some dlopen and a "run_check()" running some simple paddle codes. 

So far, the top suspect is the MKL version used in PaddlePaddle fails to support some specific CPU architecture, and the randomness comes from the hardware of assigned CI machine. There are also other bug reports on "Illegal Instructions" with MKL: 

- https://ez.analog.com/wide-band-rf-transceivers/tes-gui-software-support-adrv9009-adrv9008-1-adrv9008-2/f/q-a/547905/adrv9009-profile-configuration-wizard-2-4---illegal-instruction-detected
- https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/illegal-instruction-error-with-newer-AMD-CPU/td-p/1147393
- https://www.mathworks.com/matlabcentral/answers/1665169-i-get-the-illegal-instruction-error-while-running-matlab-code-on-hpc

**Next Steps**
1. Switch to use release version of PaddlePaddle 
Right now our CI uses PaddlePaddle nightly-build. For stability purpose let's switch to use 2.3.0 release version of Paddle.
2. Add hardware info log on CI build-bot, so we can check the CPU architecture whenever it fails.
3. Try fetching the core dump file on the CI build-bot to verify if it fails inside "libmkl_core"
4. If it is an issue with MKL, install the openblas-version of PaddlePaddle. However that only supports python3.8 and there's more work to do:
`python3 -m pip install paddlepaddle==2.3.0 -f https://www.paddlepaddle.org.cn/whl/linux/openblas/noavx/stable.html`

**Comment by qiao-bo** [comment]
close this as paddle tests work ok now.
