### ISSUE TITLE
TypeError when using quantized_types

### ISSUE THREAD

**Issue by FantasyVR** [taichi-dev/taichi#4993]
**To Reproduce**
When running  `python misc/visualize_quant_types.py`, I got the `TypeError` error. The source code: [here](https://github.com/taichi-dev/taichi/blob/master/misc/visualize_quant_types.py).

**Log/Screenshots**

```
$python misc/visualize_quant_types.py
[Taichi] version 1.0.2, llvm 10.0.0, commit d49baf89, linux, python 3.8.11
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "misc/visualize_quant_types.py", line 12, in <module>
    fixed16 = ti.types.quantized_types.quant.fixed(frac=16, range=2)
TypeError: fixed() got an unexpected keyword argument 'range'
```

**Comment by strongoier** [comment]
Thanks for reporting this! It seems that the name of the parameter was accidentally changed in #3501. I'll fix it.
