### ISSUE TITLE
Custom LLVM headers fails to build with GCC 12

### ISSUE THREAD

**Issue by re-xyr** [taichi-dev/taichi#5021]
**Describe the bug**

The custom LLVM 10 for taichi contains code that uses `std::iterator`, which is a deprecated feature in C++17. When compiled against the standard library headers bundled with GCC 12, it errors out by default.

**To Reproduce**

Build the project on Linux with GCC 12 installed; clang would default to using GCC 12's headers.

**Log/Screenshots**

Errors like this are produced:

```
/home/daylily/.local/share/taichi-llvm/include/llvm/Support/YAMLParser.h:324:19: error:  'iterator<std::input_iterator_tag, llvm::yaml::Node, long, llvm::yaml::Node *, llvm::yaml::Node &>' is deprecated [-Werror, -Wdeprecated-declarations]
    : public std::iterator<std::input_iterator_tag, ValueT> {
                  ^
/home/daylily/.local/share/taichi-llvm/include/llvm/Support/YAMLParser.h:482:12: note: in instantiation of template class 'llvm::yaml::basic_collection_iterator<llvm::yaml::SequenceNode, llvm::yaml::Node>' requested here
  iterator begin() { return yaml::begin(*this); }
           ^
/usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/stl_iterator_base_types.h:127:12: note: 'iterator<std::input_iterator_tag, llvm::yaml::Node, long, llvm::yaml::Node *, llvm::yaml::Node &>' has been explicitly marked deprecated here
    struct _GLIBCXX17_DEPRECATED iterator
           ^
/usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/x86_64-pc-linux-gnu/bits/c++config.h:119:34: note: expanded from macro '_GLIBCXX17_DEPRECATED'
# define _GLIBCXX17_DEPRECATED [[__deprecated__]]
                                 ^
```

**Additional comments**

Arch Linux is affected by this because it is rolling release. Most other Linux distros are likely not impacted immediately. To circumvent this, pass `-Wno-error=deprecated-declarations` to clang.

**Comment by qiao-bo** [comment]
Thanks for raising the issue and providing remedy as well! I think this appears due to the use of 
https://github.com/taichi-dev/taichi/blob/fba92cf76f93668033678e91eb219ba9c9f4a1ef/cmake/TaichiCXXFlags.cmake#L57

Let's see if other distros such as Ubuntu 22.04 (with gcc 11.2) will also be affected, hopefully someone will verify this. Otherwise, maybe upgrading to llvm-12 could help!

**Comment by chuandongyan** [comment]
The gcc version is 11.2 on my Arch linux. @qiao-bo
