### ISSUE TITLE
[Refactor] Improve portability of AOT interfaces

### ISSUE THREAD

**Issue by PENGUINLIONG** [taichi-dev/taichi#5042]
Currently the only way to integrate taichi on any platform smoothly is to include taichi as a CMake subdirectory. While it might not be a problem in controllable environments, C++17 might not be enforced in distributed libraries.

We have already shipped `taichi_export_core` in 1.0.0 as a solution, but unfortunately the export library can be only built in certain environments. As anyone would guess, it breaks on Windows. Most of the problems source from the linkage with C++ runtime libraries, diverged compiler flags between library and user codes and mismatched C++ language version.

To eliminate such discontinuity between development and distribution, we need to tweak the building process for a bit:

1. The compiler flags (`TI_XXX`) should be fixated in a CMake generated header (and installed in the `INSTALL` target);
2. Any use of STL types in the headers containing `TI_DLL_EXPORT`, or the headers indirectly included by such have to be replaced with C types.

By statistics of commit `1532d9f29d1b4d8b5b1f53e08f14fb818e704355`, it's about the following headers:

- [x] taichi/aot/graph_data.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/aot/module_builder.h
- [ ] taichi/aot/module_data.h
- [x] taichi/aot/module_loader.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/backends/arch.h
- [ ] taichi/backends/cpu/aot_module_loader_impl.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/backends/device.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/backends/vulkan/aot_module_loader_impl.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/backends/vulkan/aot_utils.h
- [ ] taichi/backends/vulkan/vulkan_api.h
- [ ] taichi/backends/vulkan/vulkan_common.h
- [ ] taichi/backends/vulkan/vulkan_device.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/backends/vulkan/vulkan_device_creator.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/backends/vulkan/vulkan_loader.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/backends/vulkan/vulkan_utils.h
- [ ] taichi/codegen/spirv/kernel_utils.h
- [ ] taichi/codegen/spirv/snode_struct_compiler.h
- [ ] taichi/codegen/spirv/spirv_codegen.h
- [ ] taichi/common/core.h
- [ ] taichi/common/exceptions.h
- [ ] taichi/common/logging.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/common/platform_macros.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/common/ref_counted_pool.h
- [ ] taichi/common/serialization.h
- [ ] taichi/gui/gui.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/inc/archs.inc.h
- [ ] taichi/inc/binary_op.inc.h
- [ ] taichi/inc/constants.h
- [ ] taichi/inc/data_type.inc.h
- [ ] taichi/inc/expressions.inc.h
- [ ] taichi/inc/offloaded_task_type.inc.h
- [ ] taichi/inc/snodes.inc.h
- [ ] taichi/inc/statements.inc.h
- [ ] taichi/inc/unary_op.inc.h
- [ ] taichi/ir/expr.h
- [ ] taichi/ir/expression.h
- [ ] taichi/ir/frontend_ir.h
- [ ] taichi/ir/ir.h
- [ ] taichi/ir/mesh.h
- [ ] taichi/ir/offloaded_task_type.h
- [ ] taichi/ir/scratch_pad.h
- [ ] taichi/ir/snode.h
- [ ] taichi/ir/snode_types.h
- [ ] taichi/ir/statements.h
- [ ] taichi/ir/stmt_op_types.h
- [ ] taichi/ir/type.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/ir/type_factory.h
- [ ] taichi/ir/type_utils.h
- [ ] taichi/jit/jit_module.h
- [ ] taichi/lang_util.h
- [ ] taichi/math/math.h
- [ ] taichi/platform/windows/windows.h
- [ ] taichi/program/callable.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/program/compile_config.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/program/context.h
- [ ] taichi/program/function.h
- [ ] taichi/program/function_key.h
- [ ] taichi/program/kernel.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/program/kernel_profiler.h
- [ ] taichi/program/ndarray.h
- [ ] taichi/program/ndarray_rw_accessors_bank.h
- [ ] taichi/program/program.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/program/program_impl.h
- [ ] taichi/program/snode_expr_utils.h
- [ ] taichi/program/snode_rw_accessors_bank.h
- [ ] taichi/program/sparse_matrix.h
- [ ] taichi/runtime/llvm/mem_request.h
- [ ] taichi/runtime/runtime.h
- [ ] taichi/runtime/vulkan/runtime.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/struct/snode_tree.h
- [ ] taichi/system/dynamic_loader.h
- [ ] taichi/system/memory_pool.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/system/profiler.h
- [ ] taichi/system/threading.h
- [ ] taichi/system/timer.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/system/unified_allocator.h
- [ ] taichi/ui/backends/vulkan/app_context.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/ui/backends/vulkan/canvas.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/ui/backends/vulkan/gui.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/ui/backends/vulkan/renderable.h
- [ ] taichi/ui/backends/vulkan/renderables/circles.h
- [ ] taichi/ui/backends/vulkan/renderables/lines.h
- [ ] taichi/ui/backends/vulkan/renderables/mesh.h
- [ ] taichi/ui/backends/vulkan/renderables/particles.h
- [ ] taichi/ui/backends/vulkan/renderables/set_image.h
- [ ] taichi/ui/backends/vulkan/renderables/triangles.h
- [ ] taichi/ui/backends/vulkan/renderer.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/ui/backends/vulkan/scene.h
- [ ] taichi/ui/backends/vulkan/swap_chain.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/ui/backends/vulkan/vertex.h **(contains `TI_DLL_EXPORT`)**
- [ ] taichi/ui/common/app_config.h
- [ ] taichi/ui/common/camera.h
- [ ] taichi/ui/common/canvas_base.h
- [ ] taichi/ui/common/field_info.h
- [ ] taichi/ui/common/gui_base.h
- [ ] taichi/ui/common/renderable_info.h
- [ ] taichi/ui/common/scene_base.h
- [ ] taichi/ui/utils/utils.h
- [ ] taichi/util/bit.h
- [ ] taichi/util/io.h
- [ ] taichi/util/meta.h
- [ ] taichi/util/short_name.h
- [ ] taichi/util/str.h

**Comment by k-ye** [comment]
> Any use of STL types in the headers containing TI_DLL_EXPORT, or the headers indirectly included by such have to be replaced with C types.

+1. We need to start thinking about the public C/C++ API for AOT users.
