### ISSUE TITLE
@ti.kernel function new object will raise UserWarning on taichi 1.0.2

### ISSUE THREAD

**Issue by huoyushequ** [taichi-dev/taichi#5049]
**Describe the bug**
@ti.kernel function new object will raise UserWarning on taichi 1.0.2

**To Reproduce**

```py
import taichi as ti
ti.init(arch=ti.cpu)

@ti.data_oriented
class A:
    def __init__(self):
        pass
@ti.kernel
def f():
    a = A()
f()

```

**Log/Screenshots**

```
python3 test2.py 
[Taichi] version 1.0.2, llvm 10.0.0, commit 14f0acba, linux, python 3.9.7
[Taichi] Starting on arch=x64
/home/qiaoqian/work/taichilang/test2.py:14: UserWarning: Calling non-taichi function "A". Scope inside the function is not processed by the Taichi AST transformer. The function may not work as expected. Proceed with caution! Maybe you can consider turning it into a @ti.func?
  a = A()

```

**Comment by qiao-bo** [comment]
cc @strongoier @lin-hitonami

**Comment by strongoier** [comment]
This is expected behavior. Normally, data oriented classes are not expected to get instantiated inside kernels. Could you provide more details about your use case?

**Comment by huoyushequ** [comment]
Maybe it's not a bug anyway, but it's a natural way to create a new instance of class in the ti.kernel, then call the instance's ti.function to do something, is a better way to do something like that? Any suggestions?

**Comment by strongoier** [comment]
`@ti.data_oriented` is mainly for allowing your Python OOP programs to work together with Taichi kernels. See https://docs.taichi-lang.org/docs/odop for more details.

I guess your requirement is an advanced Taichi struct type with method support. Such feature is still under development, but will hopefully come soon. (See #4989)

**Comment by bsavery** [comment]
Hi @huoyushequ , as @strongoier mentioned in the pull request [#4989](https://github.com/taichi-dev/taichi/pull/4989) we are adding the ability to add a method to a struct (which you can create in a kernel).  Would this do what you want?

**Comment by huoyushequ** [comment]
that's more or less what i want, thank you. class in python is heavily used, wish the feature complished soon~
