### ISSUE TITLE
Better error message when try to declare tensors after kernel invocation #511

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#506]
**Concisely describe the proposed feature**
Make better error message when user try to declare variables after kernel/assign is called. eg.:
```python
import taichi as ti

x = ti.var(ti.i32, shape=())
x[None] = 1
y = ti.var(ti.i32, shape=()) # shouldn't define vars after x[None] = 1!
y[None] = 2
print(x[None], y[None])
```
You'll get a Segmentation Fault instead of a reasonable assertion failure.

**Describe the solution you'd like**
In `global_new()`, add
```
TI_ASSERT_INFO(!get_current_program()->any_kernel_compiled,
    "All tensors should be defined before any assignment, read, and kernel invocation");
```
In `Kernel::compile()`, add `get_current_program()->any_kernel_compiled = true;`.

**Additional comments**
The fault is because `parent` is null here:
https://github.com/taichi-dev/taichi/blob/a3a56ae9987c5f7465c2e9eabc88c4dcbd7914f3/taichi/transforms/type_check.cpp#L102
As mentioned in https://github.com/taichi-dev/taichi/pull/505#issuecomment-588644274.

**Comment by yuanming-hu** [comment]
Yeah I strongly agree that this can be really confusing for new users and should be fixed.  Apart from generating an assertion error, we should also do a test in the Python scope: https://github.com/taichi-dev/taichi/blob/1f9184385329793186c827668942e5308836edd3/python/taichi/lang/impl.py#L72

i.e. if `ti.get_runtime().materialized=True` then no more variables should be declared.

**Comment by archibate** [comment]
Should be solved now!
Closing...
