### ISSUE TITLE
Image I/O python bindings: `imread` and `imwrite` #515

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#507]
**Concisely describe the proposed feature**
I would like to add `imread` and `imwrite` to the compiler so that people can do image processing on taichi without installing other heavy libraries (eg. `cv2`, `plt`).

**Describe the solution you'd like**
See `stb_image.h` and `stb_image_write.h` in `external/include` (they're public area image I/O library) for related APIs.

**Additional comments**
Also notice that already used in GUI's `ImageBuffer` class, you can take a reference of it.
Also check `python/taichi/misc/gui.py`: `set_image()` for how data passing from Python to C++.
See `pydoc cv2` for prototypes of `imread` and `imwrite`.
May return numpy arrays for compatibility.
You can also add `auread/auwrite`, using https://github.com/nothings/stb/blob/master/stb_vorbis.c.

**Comment by yuanming-hu** [comment]
This is a great idea! I suggest that we use the functionalities of `stb_images` to load/store `numpy` arrays, which is already easy to use with Taichi tensors. For example,
`ti.imread('logo.png') -> np.ndarray((w, h, 3), np.uint8)` and `ti.imwrite(img, 'logo.png')`

**Comment by archibate** [comment]
Done there, closing now :)
