### ISSUE TITLE
Upgrade the Constant Folding pass

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#510]
**Concisely describe the proposed feature**
The constant folder works only for `DataType::i32` with `BinaryOpType::mul` and `BinaryOpType::sub`. We can systematically upgrade it.

**Describe the solution you'd like**
We may write the constant folder for each type and each operation, but it takes too much code to write them one by one. It would be better to have something like `val(DataType dt)` to avoid type checkings like `if (data_type == DataType::i32) return val.val_int32();`.

**Comment by yuanming-hu** [comment]
This will be very helpful! It is worth considering that we many many operations to constant fold:
 - add, mul, div, sub
 - sin, cos, tan, tanh
 - sqrt, pow, ...
 - ...

Implementing each operation for each data type can be very time consuming and error-prone.
A more systematic solution is to
 - JIT Compile the operation with operand types into a function and invoke that function to do constant fold
 - Or use the [LLVM interpreter](https://llvm.org/doxygen/classllvm_1_1Interpreter.html) to evaluate the result.

**Comment by archibate** [comment]
> It would be better to have something like `val(DataType dt)` to avoid type checkings like `if (data_type == DataType::i32) return val.val_int32();`.

Possible solution, use the union member `value_bits` in TypeConstant:
```cpp
      if (src_type == dst_type) {
        auto v = input.value_bits;
        new_constant.val_i32 = v;
        success = true;
      }
```

**Comment by archibate** [comment]
We can add `analysis/is_expr_const.cpp`:
```cpp
bool is_expr_const(Expr &&expr) {
  if (expr.is_pure_function())    // i.e. constexpr
    if (expr.oprand.all(is_expr_const))
      return true;
  return false;
}
```
