### ISSUE TITLE
More examples about exporting simulation data to files

### ISSUE THREAD

**Issue by tengzhang48** [taichi-dev/taichi#5105]
Hello,

I am new to taichi and would like to learn it for engineering simulations of deformable bodies. I already can find a lot of very good examples including fem, mpm, and mass-spring systems. Most examples have interactive GUI features, which is very nice in general. I also understand that this is an impressive feature of taichi by providing a simple and efficient visualization. However, I may run simulations on computer clusters that do not have direct GUI. It will be nice if there are more examples about exporting simulation data to files. I tried to modify the fem and mpm simulations to save the data in "ply" or "csv" format. But it is not very straightforward for me to modify it. "CSV" file is simple, but it may not be flexible to show the results. 

Thanks.

Best,
Teng

**Comment by strongoier** [comment]
Hi @tengzhang48. Have you tried exporting results to videos? This might be more straightforward.

Doc: https://docs.taichi-lang.org/docs/export_results#export-videos
Example: https://github.com/taichi-dev/taichi/blob/master/tests/python/examples/simulation/test_mpm99.py

**Comment by tengzhang48** [comment]
Hi Yi,

Thanks for your quick reply. I did not try to export results to videos yet. I tried to save simulation results in a series of images. For example, I tried to modify the fem99.py code by replacing the gui portion with the following ones

"init_mesh()
init_pos()
for s in range(1000):
    update_U()
    advance()
    if s%100 ==0:
        filename = f'fem_export{s}.png'
        ti.tools.imwrite(pos.to_numpy(), filename)
        print(f'Frame {s} is recorded in {filename}')"

I can obtain images but they seem not correct.

In addition, saving simulation data to files will be very helpful for the post-processing. For many cases, we need to examine the results not only visually but also more quantitatively. It will be nice if it can be saved in some other popular format, such as hdf5. I tried to save to ".ply" files. It works, but I am not very familiar with the format and software. From the demo, "plywriter" should be able to save element information as well, but I can not modify the fem code to achieve it. 

Thanks. 

Best,
Teng

**Comment by strongoier** [comment]
`pos` is not pixels - so unfortunately your attempt is unlikely to work. My suggestion is to use `ti.GUI(show_gui=False)` to still draw the image without showing the window, and then export images (or videos).

> Example: https://github.com/taichi-dev/taichi/blob/master/tests/python/examples/simulation/test_mpm99.py

This example illustrates the above method.

Regarding convenient ways to generate `.ply` files or other formats, could @FantasyVR help provide some input here?

**Comment by tengzhang48** [comment]
@strongoier Yes, the method you suggested works well. Thanks a lot. Looking forward to more suggestions on the data output.

Also, are there plans to include more functions to read FEM mesh in some format, such as gmsh?

**Comment by FantasyVR** [comment]
Hi @tengzhang48 . Have you ever tried to export `.ply` file according to this [doc](https://docs.taichi.graphics/docs/export_results#export-ply-files)? It shows you how to export your data as `.ply` and import it into `Houdini` or `Blender`.

**Comment by tengzhang48** [comment]
Yes, I tried to modified the fem99.py code. I added the following codes
"series_prefix = "fem_example.ply"

for s in range(1000):
    update_U()
    advance()
    if s%100 ==0:
        np_pos = np.reshape(pos.to_numpy(), (NV, 2))
        # create a PLYWriter
        writer = ti.tools.PLYWriter(num_vertices=NV)
        z = np.zeros(NV)
        writer.add_vertex_pos(np_pos[:, 0], np_pos[:, 1],z)
        writer.export_frame_ascii(s, series_prefix)
"
It can generate ply outputs. However, different frames have different number of points. This is strange to me. Also, some files cannot be imported into Blender while some can. I may make some simple mistakes here. Can you please take a look at the codes?

I noticed there are examples to out element faces. Is my understanding correct? But it is a little hard for me to follow the example to output the fem99 mesh/edge data. Also, how should I do if I would like to output more data, such as energy, stress etc?

Thanks.

**Comment by FantasyVR** [comment]
Hi @tengzhang48， sorry for the late reply. I tried to use the `ply` exporter to export the simulation mesh in `fem99.py`. The source code is [here](https://gist.github.com/FantasyVR/5cd9b76062a9b0fdaa0568a2040797f7).

After running the scripts, there are a lot `ply` files in your local directory. You could import the mesh sequence using Blender with [Stop-motion-OBJ](https://github.com/neverhood311/Stop-motion-OBJ) plugin. 

The animation below shows the imported mesh sequence:


https://user-images.githubusercontent.com/6712304/173246048-74e2b6b3-1cf5-41b0-8908-4ecdd4bc93b7.mov

**Comment by tengzhang48** [comment]
Thank @FantasyVR. I tried your code but still have errors. You can find the modified code here https://github.com/tengzhang48/tz/blob/master/fem99_ply.py

I also saved the images and found they are working.

The first frame output has more 4000 points although it should only have 1089.

**Comment by FantasyVR** [comment]
Hi @tengzhang48 , `fem99.py` uses autodiff to compute the gradient information.  You can change 

https://github.com/tengzhang48/tz/blob/e8e700d848136415899ddb9e3144c22b31c9f88f/fem99_ply.py#L101-L102

to 

https://gist.github.com/FantasyVR/5cd9b76062a9b0fdaa0568a2040797f7#file-fem99_export-py-L102-L105

```
    for i in range(30):
        with ti.Tape(loss=U):
            update_U()
        advance()
```

**Comment by tengzhang48** [comment]
Thanks for pointing this out. I am still learning the Taichi programming. I updated the code as you suggested https://github.com/tengzhang48/tz/blob/master/fem99_ply.py

I can import the ply files into Blender now. But The first frame still has more data points. This may not be an error as I am not familiar with this data format.
https://github.com/tengzhang48/tz/blob/master/example_000000.ply

**Comment by FantasyVR** [comment]
Hi @tengzhang48 , it's wried that the first frame has more data points. The outputs of your script running on my Mac have the same number of data points.  Maybe you could delete all `ply` files first and then re-run your script.

**Comment by strongoier** [comment]
Hi @FantasyVR, I ran the script and didn't ran into the reported issue.
@tengzhang48 You have to remove the old files first.

**Comment by tengzhang48** [comment]
Thanks a lot for your help @strongoier @FantasyVR . I still have the same problem. But I tried to use meshio to output other formats, such as vtk, and it works. A sample code is here [](https://github.com/tengzhang48/tz/blob/master/fem99_meshio.py). 

I am not sure how efficient for using meshio to output data, especially when they are large. Also, I feel meshio can be also used to read a FEM mesh and run the simulations in Taichi. Do you have any suggestions on this? My understanding is that some transitions from the numpy arrays to the Taichi data structure are needed.

**Comment by FantasyVR** [comment]
Hi @tengzhang48, the data is printed three times in [example_000000.ply](https://github.com/tengzhang48/tz/blob/master/example_000000.ply). The header information is correct. So I still suspect it's because the file is not cleared.  Could you recreate a new clean directory and rerun your script?


As for `meshio`, I'm not familiar with it. As far as I know,  in a FEM simulation, you need the positions of vertices and the topology information of each tetrahedron.  If you could import these data as numpy arrays, you could transform them to Taichi field shown as follow:
```
pos_ti = ti.Vector.field(3, ti.f32, num_vertices)
pos_np = numpy.arange(3 * num_vertices).reshape(num_vertices, 3)
pos_ti.from_numpy(pos_np)
```
Another way to initialized a Taichi field with numpy array is using a `kernel` function.

```
@ti.kernel
def init(pos_np: ti.types.ndarray()):
    for i in range(num_vertices):
        pos_ti[i] = ti.Vector([pos_np[i,0], pos_np[i,1], pos_np[i,2]])

init(pos_np)
```

**Comment by tengzhang48** [comment]
@FantasyVR @strongoier I think I found the problem. I got the correct results if I use serial simulations. If I use more than 1 cores, I will get additional output in the first output file. For more cores, I sometimes also got more points in later output files. I just use the following "mpirun -n 8 python3 fem99_ply_1.py"

Also, I did not find significant speed up if I use multiple cores. This probably is due to the small size of the problem. But I expect to have some changes for parallel and serial simulations.

Thank @FantasyVR for sharing the codes of changing numpy mesh data into taichi data. I will try this later this week.

**Comment by FantasyVR** [comment]
If you run the script using mpi `mpirun -n 8 python3 fem99_ply_1.py`, more than one thread writes data to the same file. And it's not what we expected. It would be best if you directly run with `python fem99_ply_1.py`.  Taichi will utilize multi-cores of your CPU. You could also use other backends with `ti.init(arch=ti.gpu)` to run parallel.

**Comment by tengzhang48** [comment]
Got it. This may also be the reason why I did not see speed changes when using different number of cores. 

For large simulations, I mostly run on computer clusters. I can specify the number of cores. Does this mean taichi will use the number of cores I request (8 or 32 etc)? Also, if I request two compute nodes with each having 128 cores, can taichi run parallel simulations on the two nodes? I think the two nodes are connected by InfiniBand.

I am mostly using cpu and still learning gpu computation. I will try gpu computation later.

**Comment by FantasyVR** [comment]
Hi @tengzhang48, this is a very good question. But it's not related to this ISSUE. Could you create another issue about using clusters of CPU cores?

If the exporting problem is already solved, you could directly close this issue.

**Comment by tengzhang48** [comment]
Sounds good. Thanks.
