### ISSUE TITLE
Make Vulkan and LLVM backends play together in the C++ library

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#5112]
Right now if we build the CPP codebase with both LLVM and Vulkan on, and then try to link that library for AOT usage. The produced binary would crash, at least on Linux.

**Comment by qiao-bo** [comment]
Update: This can be reproduced using the [implicit_fem](https://github.com/taichi-dev/taichi-aot-demo/tree/master/implicit_fem/desktop) app on Linux. When building with only Vulkan, works fine. When building with both Vulkan and LLVM enabled, the program crashed.

The crash point is
https://github.com/taichi-dev/taichi-aot-demo/blob/6e66f62ae3c79c6fe71d89cfd80be11f65024d84/implicit_fem/include/fem_app.h#L90

Error message: 
```
: CommandLine Error: Option 'help-list' registered more than once!
Segmentation fault (core dumped)
```

**Comment by qiao-bo** [comment]
close as this should be fixed
