### ISSUE TITLE
Drop the need for `ti.static` for python scope variables 

### ISSUE THREAD

**Issue by RodenLuo** [taichi-dev/taichi#5125]
If not causing too much overhead in other places (compatibility or compilation time etc.), the first code block can be favored over the second code block below and leave the rest to compilation optimization. 

### Future: 
```python
@ti.kernel
def test_static():
    if enable_projection:
        x[0] = 1
```

### Current: 
```python
@ti.kernel
def test_static():
    if ti.static(enable_projection):
        x[0] = 1
```

More in https://forum.taichi.graphics/t/ti-static-python/2632 in Chinese.

**Comment by RodenLuo** [comment]
This only applies when `enable_projection` is a python scope variable, and the philosophy will keep long that the python scope variable will be baked in as a value during compilation.

**Comment by yuanming-hu** [comment]
One two cents: it would still be helpful to distinguish compile-time branching from run-time branching. I would prefer the existing way which delivers more clarity.

**Comment by RodenLuo** [comment]
Makes sense! Thanks!
