### ISSUE TITLE
Enable Werror for TI_WITH_CUDA_TOOLKIT=ON

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#5133]
Performance benchmark job now uses gcc instead of clang-10 as host compiler. One blocker of moving to clang-10 is that we need to enable Werror when TI_WITH_CUDA_TOOLKIT is on. Once it's fixed we should use clang-10 for perf benchmark job as well.

**Comment by qiao-bo** [comment]
this is possible to fix in code. IIUC, the cupti source code is copied into our repo and we can just eliminate warning in the source.

**Comment by feisuzhu** [comment]
issue irrelevant now.
