### ISSUE TITLE
Atmoic min get wrong result on cuda backend when block_dim is 16

### ISSUE THREAD

**Issue by BillXu2000** [taichi-dev/taichi#5148]
**Describe the bug**
Atmoic min get wrong result on cuda backend when block_dim is 16.

**To Reproduce**
Run the code below. The expected answer is 1, but I got 0 on my computer.

```py
import taichi as ti

ti.init(arch=ti.cuda)

n = 16
x = ti.field(dtype=ti.f32, shape=n)

@ti.kernel
def test():
    hit_time = 1
    for i in x:
        ti.atomic_min(hit_time, 1)
    print(hit_time)

test()
```
Setting n to any number larger than 16, print value of `hit_time`, or replacing `for i in x` with `for i in range(n)` will get the right answer.
Especially, replacing `for i in x` with `for i in range(n)` will only change the block_dim in the final Taichi IR, and thus I think the bug might be at cuda codegen phase.

**Comment by BillXu2000** [comment]
Related (same) issue: #5142

**Comment by bobcao3** [comment]
Can you try to disable reduction optimization and see whether that fixes this?

**Comment by BillXu2000** [comment]
Disabling reduction optimization will fix this bug.
