### ISSUE TITLE
 what's the difference between the “pre-built, customized LLVM binaries” and that "Build LLVM 10.0.0 from source"?

### ISSUE THREAD

**Issue by qingshanxiaozi** [taichi-dev/taichi#5152]
I am trying to compile TaiChi from source code, and I have referd to the instructions from https://docs.taichi-lang.org/docs/dev_install/ .
While there are two methods provided in the part of “Install LLVM”，one is  “Install pre-built, customized LLVM binaries”， the other is “Build LLVM 10.0.0 from source”.  I wonder when do I need to compile LLVM from source code, and when do I need to use the "customized LLVM binaries", what exactly dose LLVM customizd for TaiChi?

**Comment by victoriacity** [comment]
Taichi uses customized compilation options to build LLVM. When your target machine architecture to run Taichi is included in the pre-built binary options, i.e., x86 Windows/Linux or MacOS, you can directly use the pre-built LLVM binaries. If your architecture is not included in the list of binaries, for example, NVIDIA Jetson, you will need to compile LLVM from source using the CMake options as specified in the dev install page.

**Comment by qingshanxiaozi** [comment]
> Taichi uses customized compilation options to build LLVM. When your target machine architecture to run Taichi is included in the pre-built binary options, i.e., x86 Windows/Linux or MacOS, you can directly use the pre-built LLVM binaries. If your architecture is not included in the list of binaries, for example, NVIDIA Jetson, you will need to compile LLVM from source using the CMake options as specified in the dev install page.

got it, thans.
