### ISSUE TITLE
ti.GUI() 窗口标题文字显示异常

### ISSUE THREAD

**Issue by pascal-lc** [taichi-dev/taichi#5179]
**Describe the bug**

Taichi `Version==1.0.3` 下 `ti.GUI()` 窗口标题文字显示异常，中英文以及数字字符均无法显示。

**To Reproduce**

Taichi 样例文件

* 99 行冰雪奇缘 `GUI` 窗口命令代码
```py
gui = ti.GUI("Taichi MLS-MPM-99", res=512, background_color=0x112F41)
```

* 弹簧-质点系统
```py
gui = ti.GUI(name='Explicit Mass Spring System',
                 res=(512, 512),
                 background_color=0xDDDDDD)
```

**Log/Screenshots**

命令行输出信息：

```
[Taichi] version 1.0.3, llvm 10.0.0, commit fae94a21, win, python 3.6.6
[I 06/15/22 16:33:11.707 1284] [shell.py:_shell_pop_print@33] Graphical python shell detected, using 
wrapped sys.stdout
[Taichi] Starting on arch=cuda
```
GUI 窗口效果：

* 问题窗口
![MLS-MPM-99](https://user-images.githubusercontent.com/49066376/173787606-f42e34d1-952e-4251-a6d0-4e283e4a6582.png)
![mass-spring](https://user-images.githubusercontent.com/49066376/173792772-c683587e-1367-4f51-97bc-1c97a37b3e34.png)

* 正常窗口
![MLS-MPM-99](https://user-images.githubusercontent.com/49066376/173788552-fa7ad03e-666a-42d0-a178-2ef9f804fbac.png)

因截图为静态画面需特别说明，问题窗口标题文字并非静态乱码，而是随着程序的运行不断变化。并且涉及到的文字乱码仅发现限于窗口标题，窗口内部文字正常。

**Additional comments**

**注意：** Bug 已于昨晚修复。Taichi 1.0.3 版本发布后 Taichi 内部便已经修复，更新需要发布在 1.0.4 版本，或者 build from master branch。

**Comment by bobcao3** [comment]
Fixed by #5155
