### ISSUE TITLE
Misuses of `std::forward`

### ISSUE THREAD

**Issue by sjwsl** [taichi-dev/taichi#5206]
There are some misuses of `std::forward` in the C++ codebase. For example

https://github.com/taichi-dev/taichi/blob/5a066fbcc9caddebfcc89c9ec7a4dc0a8902aaa3/taichi/llvm/llvm_program.h#L170
`args` is not passed by reference.

https://github.com/taichi-dev/taichi/blob/5a066fbcc9caddebfcc89c9ec7a4dc0a8902aaa3/c_api/src/taichi_core_impl.cpp#L32

`aot_module` is not passed by universal reference. (A more serious problem here is that `unique_ptr` should be passed by value because you're sure you want to transfer ownership. Users can't know whether the ownership is transferred by the interface if it is passed by rvalue reference).

In general, `std::forward` should only be used for perfect forwarding with universal reference. Although these misuses are not that harmful, I think it's better to eliminate them.

**Comment by turbo0628** [comment]
@jim19930609 Would you please look into this issue?
