### ISSUE TITLE
Testing  for libtaichi_export_core.so

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#5214]
After #5211 we now can build libtaichi_export_core.so along with normal python wheel, we should start thinking about how to building test suite on top of  libtaichi_export_core.so.
Note it's possible that we get rid of the extra `build_libtaichi_export` job and put tests in the normal jobs with `TI_WITH_EXPORT_CORE=ON`, which is much cleaner IMHO. 
cc: @PENGUINLIONG @qiao-bo @feisuzhu

**Comment by feisuzhu** [comment]
export core is now covered by Android AOT tests
