### ISSUE TITLE
Confusing kernel computation in taichi's mpm example

### ISSUE THREAD

**Issue by zhouxian** [taichi-dev/taichi#5215]
This code snippet is used for P2G/G2P conversion across multiple mpm example codes in the repo:
```python
    for p in x:
        Xp = x[p] / dx
        base = int(Xp - 0.5)
        fx = Xp - base
        w = [0.5 * (1.5 - fx)**2, 0.75 - (fx - 1)**2, 0.5 * (fx - 0.5)**2]
```
<img width="300" alt="image" src="https://user-images.githubusercontent.com/19647225/174699279-eb766634-9c32-4496-b669-cdbf4e541bde.png">

Referring to this image with a 3x3 grid, the lower left vertex has coordinate (0,0) and the lower left grid center has coordinate (0.5, 0.5), indexed with (0,0).
When computing the index for the base grid center (which i assume to be the centered one in the 9 grids), we want this mapping from the particle coordinate to the grid index (along either x and y axis):
1.7 -> 1
1.4 -> 1
0.9 -> 0
But the code above gives this mapping:
1.7 -> 1
1.4 -> 0
0.9 -> 0

After some investigation it looks like in an older version of taichi, the int casting is doing rounding, but now it's a flooring operation, so shall we remove the ```-0.5``` operation?

Also, the kernel function seems to be interpreting the base as the lower left grid, which means the correct base computation would  need an extra ```-1```: ```  base = int(Xp - 0.5) - 1```.

If we say, let's find directly the lower-left base of a given particle, then we would want to map 1.7 to index 0, but the code is not doing this either.

**Comment by FantasyVR** [comment]
Hi @zhouxian, to learn more about how this works. You can refer to this forum topic: https://forum.taichi.graphics/t/mpm88-fx-base/1584/10 and https://www.bilibili.com/read/cv16719283, https://www.bilibili.com/read/cv16719283.
