### ISSUE TITLE
Cannot close gui window in jupyter notebook

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5236]
Description:

I want to call `ti.GUI` or `ti.gui.WIndow` in a jupyter notebook to display a window, but then I cannot close that window unless force to kill the server. And for `ti.ui.Window`, it seems the kernel will crash and restart after a while.

Code:

```python
import taichi as ti
ti.init()

gui = ti.ui.Window("hello", res=(400, 400))
can = gui.get_canvas()

img = ti.Vector.field(3, float, (400, 400))
while gui.running:
    can.set_image(img)
    gui.show()
```

**Comment by neozhaoliang** [comment]
I found a solution here:

use `while not gui.get_event(ti.GUI.ESCAPE, ti.GUI.EXIT):` instead.

**Comment by ailzhang** [comment]
Reopening this issue since we either need to figure out why it's freezing with `gui.running` and fix it or update all examples to avoid using gui.running

**Comment by PENGUINLIONG** [comment]
`gui.destroy()` is all you need.

```diff
import taichi as ti
ti.init()

gui = ti.ui.Window("hello", res=(400, 400))
can = gui.get_canvas()

img = ti.Vector.field(3, float, (400, 400))
while gui.running:
    can.set_image(img)
    gui.show()

+gui.destroy()
```

**Comment by neozhaoliang** [comment]
That works, thanks!
