### ISSUE TITLE
vulkan backend raises `OpISub found inside function but outside basic block` when process reversed for loop

### ISSUE THREAD

**Issue by erizmr** [taichi-dev/taichi#5239]
Related issue #5221 
**Describe the bug**
The vulkan backend raises `OpISub found inside function but outside basic block` when process reversed for loop.

**To Reproduce**

```py
import taichi as ti

ti.init(arch=ti.vulkan, print_ir=True)

BATCH_SIZE = 5

loss = ti.field(float, shape=(), needs_grad=True)
b = ti.field(float, shape=(BATCH_SIZE, BATCH_SIZE))


@ti.kernel
def test_func():
    for i in range(BATCH_SIZE):
        for j in range(BATCH_SIZE):
            # loss[None] += b[0, 2]
            pass


with ti.ad.Tape(loss=loss):
    test_func()
```

**Additional comments**
This screenshot comes from [spriv_codegen.cpp](https://github.com/taichi-dev/taichi/blob/master/taichi/codegen/spirv/spirv_codegen.cpp#L1329). If we use 1330 replace the 1329, there is no runtime error... Maybe the key is to find a right place to insert the `sub` ?
![image (1)](https://user-images.githubusercontent.com/33411325/175305973-9f855950-e64a-4f93-adac-e06b135fab92.png)

**Comment by bobcao3** [comment]
Fixed by #5241
