### ISSUE TITLE
Ignore type hint if it's not primitive type, reference type or template

### ISSUE THREAD

**Issue by mudream4869** [taichi-dev/taichi#5240]
**Concisely describe the proposed feature**
Example:

```python
@ti.data_oriented
class Ray:
    def __init__(self, origin, direction):
        self.origin = origin
        self.direction = direction
    def at(self, t):
        return self.origin + t * self.direction

@ti.data_oriented
class Sphere:
    def __init__(self, center, radius, material, color):
        self.center = center
        self.radius = radius
        self.material = material
        self.color = color

    @ti.func
    def hit(self, ray: Ray, t_min=0.001, t_max=10e8):
        #            ^ Just a type hint for editor
        pass
```

**Describe the solution you'd like (if any)**
Currently, the taichi will throw exception:

```python
# kernel_imply.py
               if not id(annotation
                          ) in primitive_types.type_ids and not isinstance(
                              annotation, template) and not isinstance(
                                  annotation, primitive_types.RefType):
                    raise TaichiSyntaxError(
                        f'Invalid type annotation (argument {i}) of Taichi function: {annotation}'
                    )
```

Can the kernel just ignore the type hint which doesn't match these conditions?

**Comment by strongoier** [comment]
I think it is OK to ignore those annotations with no actual meanings in `ti.func`. The downside is that having both meaningful and meaningless may be confusing. WDYT @lin-hitonami ?

**Comment by lin-hitonami** [comment]
I don't think it's a good idea to ignore the type hints taichi cannot recognize when the type hints are sometimes meaningful. Also, the type hints of the taichi functions may become mandatory when the real function is ready.

**Comment by strongoier** [comment]
I agree with @lin-hitonami. Thanks for your suggestion @mudream4869, but the current design choice is to favor strictness.

**Comment by mudream4869** [comment]
This choice is reasonable and convincing.

**Comment by strongoier** [comment]
Yep :-)
