### ISSUE TITLE
add functions to determine inf and nan 

### ISSUE THREAD

**Issue by EnochZhu** [taichi-dev/taichi#5261]
When I got involved in numerical simulation, several unexpected float numbers came up. I would like to request ways to deal with inf and nan.
It seems that a modification to mathimpl.py will work 
`from math import ..., inf, nan
....
__all__=[....,"inf", "nan" ,...]
`
I tried several limited tests as:
`
@ti.func
def is_inf(a: ti.template()):
      # tiinf = 1 / ti.math.log2(1.0)  
      return a == ti.math.inf

@ti.func
def is_nan(a: ti.template()):
      # tinan = ti.sqrt(ti.math.log2(0.5))
      return a == ti.math.nan
`

`
def test_is_inf():
      ti.init(arch=ti.cpu, default_fp=ti.f32)  
    @ti.kernel
    def test():
        a = ti.Vector([1])
        b = ti.Vector([1e-40])
        tiinf = 1 / ti.math.log2(1.0)
        print(is_inf(a / b))
        assert is_inf(a[0] / b[0]) == 1
        assert is_inf(0) == 0
        assert is_inf(0.0) == 0
    test()

def test_is_nan():
    ti.init(arch=ti.cpu, default_fp=ti.f32)  
    @ti.kernel
    def test():
        assert is_nan(0) == 0
        assert is_nan(0.0) == 0
        tinan = ti.sqrt(ti.math.log2(0.5))
        assert is_nan(tinan) == 1
        tinan = ti.math.log2(0.5) / ti.math.log2(0.5)
        assert is_nan(tinan) == 1
    test()
`

**Comment by neozhaoliang** [comment]
@EnochZhu I think we should avoid using `x == math.nan` to check if  `x` is NaN?

**Comment by EnochZhu** [comment]
Great thanks
