### ISSUE TITLE
Remove TI_IMAGE_IO and TI_AMALGAMATED

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#528]
No longer needed since TI_AMALGAMATED is always false and TI_IMAGE_IO is always true.

**Comment by archibate** [comment]
Btw, is TI_OPENGL necessary? So CUDA users who don't want compile taichi with GL support can optionally disable them.

**Comment by yuanming-hu** [comment]
> Btw, is TI_OPENGL necessary? So CUDA users who don't want compile taichi with GL support can optionally disable them.

Yes, currently `TI_WITH_OPENGL` seems to work well.
