### ISSUE TITLE
Gradient of loss w.r.t. intermediate variable in kernel function

### ISSUE THREAD

**Issue by zhouxian** [taichi-dev/taichi#5284]
I am seeing some unexpected behavior when running the following snippet:
```python
import taichi as ti
ti.init()

x = ti.field(dtype=ti.f32, shape=(), needs_grad=True)
a = ti.field(dtype=ti.f32, shape=(), needs_grad=True)
b = ti.field(dtype=ti.f32, shape=(), needs_grad=True)


@ti.kernel
def func():
   a[None] = 2 * x[None]
   b[None] = a[None] + 1
   
x[None] = 1

with ti.Tape(loss=b):
   func()
print(a.grad[None], x.grad[None])
```

I am expecting to see x.grad[None] = 2.0 and a.grad[None] = 1.0, but it prints a.grad[None] = 0.0. I think the usage of variables in func() does not violate the rules in autodiff.
Is there any explanation of this? It seems autodiff only computes gradient for the variable that's only being read in the kernel function?

**Comment by erizmr** [comment]
Hi @zhouxian , the bug has been fixed by #5315. 
It will be delivered in next release. Or you can try `pip install -i https://pypi.taichi.graphics/simple/ taichi-nightly` to get the lastest commits.
