### ISSUE TITLE
[ci] Introduce clang-tidy

### ISSUE THREAD

**Issue by feisuzhu** [taichi-dev/taichi#5306]

**Comment by feisuzhu** [comment]
cc @ailzhang

**Comment by ailzhang** [comment]
FYI  we currently do clang-tidy in CI, but we could make it simpler. https://github.com/taichi-dev/taichi/blob/master/.github/workflows/testing.yml#L80

**Comment by ailzhang** [comment]
This is done btw we just need to enable more rules ;)
