### ISSUE TITLE
Which version of MPM code to use?

### ISSUE THREAD

**Issue by th555** [taichi-dev/taichi#5309]
Hello all,

I would like to use one of the MPM simulations available for Taichi to simulate 3D soft robots (preferrably Neo-hookean). I'm a bit overwhelmed by all the different options:

- [Taichi Elements](https://github.com/taichi-dev/taichi_elements)
- [DiffTaichi](https://github.com/taichi-dev/difftaichi)
- [ChainQueen](https://github.com/yuanming-hu/ChainQueen)
- [Taichi_MPM](https://github.com/yuanming-hu/taichi_mpm)
- [mpm3d.py](https://github.com/taichi-dev/taichi/blob/master/python/taichi/examples/simulation/mpm3d.py)

There seems to be a large overlap, but also significant differences (for example the type of materials implemented). Which of these programs is the most up-to-date/capable/extensible? Do they all use the same simulation method (which would be MLS-MPM if I'm not mistaken) or are there significant differences? I'd be grateful if someone could clear things up a bit.

**Comment by FantasyVR** [comment]
Hi @th555 , thanks for using Taichi in your project.

The simulation algorithm is indeed MLS-MPM. If you just want to simulate a 3d soft body, you can extend [mpm3d.py ](https://github.com/taichi-dev/taichi/blob/master/python/taichi/examples/simulation/mpm3d.py)as Neo-Hookean material).

If you want to control the simulation like a robot, you could use [DiffTaichi](https://github.com/taichi-dev/difftaichi) as your baseline.
