### ISSUE TITLE
CLion searches for headers in the parent directory of the repository

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#5318]
**Describe the bug**
I am using CLion to open the repository, and CLion automatically searches for header files in the parent directory of the repository root. Is there something wrong with my CLion or the CMake files?

**To Reproduce**
Place the repository inside a directory named "parent_directory", and "parent_directory" can be seen inside the header search paths.

**Log/Screenshots**
![image](https://user-images.githubusercontent.com/90667349/177078803-f8e7e22b-aa71-44b6-97f7-8aa6be3f39a9.png)

**Comment by qiao-bo** [comment]
I am not familiar with CLion, but some quick search shows me that it uses `include_directories` as a hint. Maybe try to add this in top-level CMakeLists.txt to see if the IDE works?

Nevertheless, Our CMake should not be tailored to how clion works. I wouldn't consider this as a bug ;/ 

`include_directories` works in global scope and should be replaced with `target_include_directories` as good practice. Maybe Clion can somehow search path based on targets?

**Comment by lin-hitonami** [comment]
> I am not familiar with CLion, but some quick search shows me that it uses `include_directories` as a hint. Maybe try to add this in top-level CMakeLists.txt to see if the IDE works?
> 
> Nevertheless, Our CMake should not be tailored to how clion works. I wouldn't consider this as a bug ;/
> 
> `include_directories` works in global scope and should be replaced with `target_include_directories` as good practice. Maybe Clion can somehow search path based on targets?

Other include directories are fine. It just adds the parent directory to the include path which shouldn't be in the include paths. I suspect that some instructions in the CMake files accidentally adds the parent directory to the include paths.
