### ISSUE TITLE
Possible causes for the segment fault error

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5342]
Almost every user has experienced the "Received signal 11 (Segmentation fault)" error when using Taichi, the error message says

```
Internal error occurred. Check out this page for possible solutions:
https://docs.taichi-lang.org/docs/install
```

But in that page we do not have a section collecting possible causes for segment faults yet. Shall we create such a list?

**Comment by turbo0628** [comment]
Signal 11 is SIGGEV which means abnormal termination: the program has a bug!

It is mostly triggered by illegal memory access (undefined memory, misaligned memory, out-of-bound access...). Many errors can cause this signal so if the error isn't trapped by TI_ERROR, the best thing to do is open gdb and see where it crashes.

**Comment by yuanming-hu** [comment]
Is "Internal error" the correct word here if many of the errors are actually introduced by users' buggy code?

**Comment by neozhaoliang** [comment]
It's like telling the user "Hey, something is wrong but we can't locate the error. Go there for a try, good luck!"

**Comment by yuanming-hu** [comment]
Exactly. Not a good user experience here. If it's the user's fault, we don't have to blame ourselves (which will not help the user resolve the issue.)

**Comment by neozhaoliang** [comment]
Yes. I mean we can add a such list as mentioned in the message, collecting some causes for such internal errors even it's the user' fault, and let users themselves to check it?

Or we just print the list instead of the error message?
