### ISSUE TITLE
Print both the source code and corresponding IRs in print_ir

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5343]
When enabling  `init(print_ir)=True`, the IR for a kernel is printed several times (maybe one for each block I guess?), shall we only print it once, if it's unchanged throughout the program?

Also, it would be more intuitive for user if the corresponding source code is also shown by side:

|||
|:---:|:---:|
|source code     |    printed IR |
 | kernel 1 |  ir for kernel 1 |
 | kernel 2 |  ir for kernel 2 |
 | ... | ... |

**Comment by turbo0628** [comment]
The IR is printed when a transformation is made. I agree we can add some argument option such as `print_final_ir=True` that only prints out one single IR. 

Tracing down the final generated IR to its Taichi source code is useful, but isn't that easy as there are some passes add statements implicitly, for example the BLS and TLS passes. Also, the matrix are currently force-expanded at frontend so you can never see them in the IR. I think this feature needs further discussions.

**Comment by neozhaoliang** [comment]
If it's not easy to show an exact correspondence between the code and its ir, can we just list out the kernel name and its  ir block?

**Comment by neozhaoliang** [comment]
Maybe something like this, WDYT?

----------------------------
Kernel name:    render(t: float)

IR block:

....
---------------------------
