### ISSUE TITLE
Execute the Taichi cpp examples

### ISSUE THREAD

**Issue by ritchesc** [taichi-dev/taichi#5352]
1, Build the Taichi from source code and CUDA/ cpp_test/cpp_examples and then run cpp_example, get below error:
./taichi_cpp_examples 
[E 07/07/22 10:57:33.499 45415] [codegen_llvm.cpp:create_offload_struct_for@1740] A bit-vectorized struct-for must loop over a bit array with a dense parent

terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)

anything wrong with my operations?

**Comment by strongoier** [comment]
It seems that `taichi_cpp_examples` was not compatible with a previous commit, but it should be fine now. Could you try latest master branch again?

**Comment by ritchesc** [comment]
My version:
commit c133fd4f7c516c1565973ed94c2f38b6d7aa3549 (HEAD -> master, origin/master, origin/HEAD)
Author: PENGUINLIONG <admin@penguinliong.moe>
Date:   Sat Jul 2 13:01:24 2022 +0800

    [AOT] Unity native plugin interfaces (#5273)
    
    * Unity native plugin interfaces
    
    * Add submit in render thread interface
    
    * Fixed submit callback returns
    
    * Support marshalling of void*
    
    * Relax user code from maintaining a valid allocation for DeviceAllocation
    
    * [pre-commit.ci] auto fixes from pre-commit.com hooks
    
    for more information, see https://pre-commit.ci
    
    * Revert "Relax user code from maintaining a valid allocation for DeviceAllocation"
    
    This reverts commit f58e072e556d9e41df12612818bcfe951c28a881.
    
    * Ensure `DeviceAllocation` is on stack
    
    * [pre-commit.ci] auto fixes from pre-commit.com hooks
    
    for more information, see https://pre-commit.ci
    
    * Removed API for Unity buffer import, use copy instead
    
    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

commit 31f46dd551fdd77a5e22313d0c2dc4d8942916b4

Just download taichi repo only one weeks.

**Comment by strongoier** [comment]
Ah thanks for providing the info. My point is that recent commits broke that example and fixed that again. Now the master branch should be fine.

**Comment by ritchesc** [comment]
Thanks for your feedback

**Comment by strongoier** [comment]
The tests are not meant to be run individually. See https://docs.taichi-lang.org/docs/master/contributor_guide#run-integration-tests for details.

**Comment by feisuzhu** [comment]
After refactoring, use `pytest tests/cpp` to run c++ tests.
