### ISSUE TITLE
Frontend kernel/function structure checking

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#536]
- Disallow return in ti.kernel
- Enforce exactly one return in ti.func
- Disallow function definition in ti.kernel and ti.func

**Comment by archibate** [comment]
If I want to add multi-return support, is there any suggestions?

**Comment by yuanming-hu** [comment]
> If I want to add multi-return support, is there any suggestions?

Oh that would be great! We might need to think about types:
```python
@ti.func
def foo(x):
  if x > 0:
    return int(x)
  else:
    return float(x)
```
We should do some type checking to prevent this from happening. One solution could be using type hints:
```python
@ti.func
def foo(x) -> float:
  if x > 0:
    return int(x)
  else:
    return float(x)
```

Note that we need an AST transform that translates the function above into 

```python
@ti.func
def foo(x) -> float:
  ret = float(0)
  if x > 0:
    ret = int(x)
  else:
    ret = float(x)
  return ret
```

Note that we probably also need to support `ti.Matrix`s.

**Comment by xumingkuan** [comment]
In the following case,
```python
@ti.all_archs
def test_return():

  @ti.kernel
  def kernel():

    @ti.func
    def func():
      return 233

    print(func())
    return 1

  print(kernel())
```
we will visit *both* `return` statements with `is_kernel = True`, and then visit `return 233` with `is_kernel = False`. 
How can we distinguish `return 233` in that it is inside `@ti.func` but not directly in `@ti.kernel`?

**Comment by yuanming-hu** [comment]
Please disallow function definition within taichi kernels as well :-)

**Comment by xumingkuan** [comment]
I think a solution may be first to check if the function has multi-return with different types, and if the answer is yes, raise an error to tell the user to convert these types explicitly.

**Comment by xumingkuan** [comment]
An example of allowing different return types with implicit conversions is https://github.com/xumingkuan/decaf-2019/blob/master/src/main/java/decaf/frontend/tree/Tree.java#L485 (`upperBound` refers to https://github.com/xumingkuan/decaf-2019/blob/master/src/main/java/decaf/frontend/type/Type.java#L97). But it would be confusing if we allow some implicit conversions (e.g. `i32` to `f64`, since the latter can represent all values of the former) but not some others (e.g. `i64` and `f32`, since we can't determine which type is "subtype" of the other).

**Comment by xumingkuan** [comment]
Ideally, we can support the following two cases at the same time:
```python
@ti.func
def foo(x) -> float:
  if x > 0:
    return int(x)
  else:
    return float(x)
```
```python
@ti.func
def foo(x):
  if x > 0:
    return float(int(x))
  else:
    return float(x)
```

**Comment by yuanming-hu** [comment]
I would actually challenge you guys to think about a bigger problem: how to support functions in Taichi IR. Currently, the function (`@ti.func`) calls are force-inlined, which has a few limitations such as potentially HUGE code size, and lack of recursion support. Ultimately we should consider compiling `ti.func` into a piece of Taichi IR (instead of a Python function that gets inlined), and then add a `ReturnStmt` as a new IR instruction.

**Comment by archibate** [comment]
Does IR have goto statements? If so, we can simulate function call stacks. Also sloved the problem that GLSL doesn't support recursion.

**Comment by yuanming-hu** [comment]
No, no goto supported. Simulating function call stacks is pretty advanced :-) For the first step, we should simply consider supporting CPU/CUDA where recursion is supported by the backend compiler.

It's more like a program representation issue within Taichi IR. For example, you might need to implement
 - `FuncDefStmt` which contains a function prototype and function body
 - `FuncCallStmt` with a function pointer (FuncDefStmt) and arguments
 - `ReturnStmt` with a return value

**Comment by archibate** [comment]
Correct. Let's simply make recursion a limitation for OpenGL backend for now. And FuncDefStmt is something like OffloadStmt?

**Comment by yuanming-hu** [comment]
Yeah sort of. We may also need a new IRNode (something like `TaichiProgram`) that wraps all the functions and the main function.

**Comment by yuanming-hu** [comment]
> Btw, do we need @ti.inlinefunc after that?

Yes, actually I suggest that we make functions inline by default unless marked as `ti.noinline`.

**Comment by archibate** [comment]
I believe main function (`ti.kernel`) should be treated as a normal function too, and `TaichiProgram` contains a pointer to that `IRNode`.

**Comment by k-ye** [comment]
I guess it's fairly easy to support `FuncDef`, `FuncCall` in source-to-source backends. But for LLVM ones, do you need to create your own calling conventions. Or maybe LLVM already handles that..?

**Comment by yuanming-hu** [comment]
> Or maybe LLVM already handles that..?

Exactly. LLVM already handles that. Nothing to worry about in that direction :-)

**Comment by archibate** [comment]
Btw, ti.kernel call ti.kernel how-to-forbid example:
https://github.com/taichi-dev/taichi/blob/cb551f3c9b448176d83ae247ad6ddbe91365311a/python/taichi/lang/kernel.py#L272-L274
