### ISSUE TITLE
Question on Data Structure

### ISSUE THREAD

**Issue by nullplay** [taichi-dev/taichi#5377]
Hi! While I was reading the data layout and structures of Taichi(https://docs.taichi.graphics/docs/master/layout), I wonder if these two are equivalent or not.
```
  ti.root.dense(ti.i, M).dense(ti.j, N).place(x)   # layoutA
  ti.root.dense(ti.ij, M*N). place(x)              # layoutB
```

In my mental model, layoutA creates the size of M + M\*N physical memory and layoutB creates the size of M*N physical memory. Therefore, they actually create different data structures. Is this right?

**Comment by strongoier** [comment]
IIUC these two are equivalent in the end. Could you explain where does the additional `M` come from?

**Comment by nullplay** [comment]
![Screen Shot 2022-07-13 at 2 55 17 PM](https://user-images.githubusercontent.com/14838106/178810086-bed76af7-0717-4176-83e2-a299eaf8f1f4.png)
I imagined these kinds of layouts for A and B.

**Comment by strongoier** [comment]
The "i dense" part in your graph only appears logically - there's no need for that in memory.

**Comment by nullplay** [comment]
Thanks!
