### ISSUE TITLE
More flexible usage of ti.field.

### ISSUE THREAD

**Issue by xuhao1** [taichi-dev/taichi#5380]
Hi there,
I am trying to develop a submap version of TaichiSLAM, this requires lots of local maps, each submap has sparse data structures for data storage. 
My first trial is to use a ti.data_oriented annotated class, each class contains the full local mapping function. But I found when I activate a new submap class, it always requires JIT to run again. This is very time-wasting. 
I also have tried some similar methods and I found when the input field for kernel changes (ti.template() has a different instance), then taichi calls JIT again and again. 
I found this is because passing fields with sparse data structure now need __ti.template()__ as annotated type. However, when the object is annotated by ti.template() changes, taichi recompiles the kernel. 
So this method does not work, related issue https://github.com/taichi-dev/taichi/issues/5376

The second attempt is to use a 4-dim data structure (ti.ijkl) the first index for submap id and the other 3 for XYZ in space.
However, I found it's not possible to struct-for in a specific submap like 
```python
for j, k, l, in TSDF[1]
```
because taichi does not support slicing a field.
So this way also seems not working.
My question is is that possible to avoid JIT (maybe force compile not to recompile when  arguments changes) or struct-for on a sliced data structure? Or does any other trick can solve my problem.

**Comment by xuhao1** [comment]
I found for the same kernel inputting ScalarField/VectorField (sparse) with the same size but different instance(address), it will cause recompiling. This also cause low performance. It looks like taichi uses pointer of ti.template() class as the hash and if address changes it will recompile the kernel.
For example, I wrap some algorithm and scalarfield data in a class and create different instances of this class https://github.com/taichi-dev/taichi/issues/5376. What I want is to avoid JIT (and also loading cache from disk) when to use a kernel with the same size/datatype.

Personally, I think this feature is also very important as people want to use taichi more flexibly. Also, it's essential to use taichi in an OOP way (every time of instancing a class needs JIT is too slow!). For me, it's necessary for implementing the submap feature in TaichiSLAM https://github.com/taichi-dev/taichi/issues/5380

A sample code:
```python
import taichi as ti
ti.init()

@ti.kernel
def test(x: ti.template()):
    #Do something with x
    pass

x = ti.field(dtype=ti.i32)
y = ti.field(dtype=ti.i32)
B0 = ti.root.pointer(ti.ijk, (3, 1, 1)).dense(ti.ijk, (1, 2, 2))
B0.place(x)

B1 = ti.root.pointer(ti.ijk, (3, 1, 1)).dense(ti.ijk, (1, 2, 2))
B1.place(y)

test(x)
#When calling test(y), taichi will recompile the kernel, this should be avoided.
test(y)

@ti.data_oriented
class AClass:
    def __init__(self) -> None:
        x = ti.field(dtype=ti.i32)
        B0 = ti.root.pointer(ti.ijk, (3, 1, 1)).dense(ti.ijk, (1, 2, 2))
        B0.place(x)
        self.x = x
        self.B0 = B0
    @ti.kernel
    def work(self):
        # do sth with self.x
        self.x[0, 1, 2] = 3

a = AClass()
a.work()

b = AClass()
#When calling b.work, taichi will recompile the kernel, this should be avoided.
b.work()
```

**Comment by feisuzhu** [comment]
Hi,

This seems to be 2 different issues, so could you please split this issue?

**Comment by feisuzhu** [comment]
(For tracking) The first problem is partially addressed at https://github.com/taichi-dev/taichi/issues/4401#issuecomment-1182854618

**Comment by xuhao1** [comment]
@feisuzhu of course.
