### ISSUE TITLE
Apply file lock before wrting offline cache to file

### ISSUE THREAD

**Issue by jim19930609** [taichi-dev/taichi#5385]
File lock is missing in the current implementation of file serializer. When running two or more Taichi programs simultaneously, this is gonna cause trouble in the following manner:
1. Mess up the `metadata.*` files, which are shared across kernels, fields (and processes of course).
2. Two or more standalone applications running the same kernel (helper kernels, kernel library, etc)

![2022-07-11 11-35-48 的屏幕截图](https://user-images.githubusercontent.com/22334008/178183906-7befe6f7-afee-4c29-bc1f-e1d48e8ff226.png)

**Comment by lin-hitonami** [comment]
Fixed in #5578
