### ISSUE TITLE
How to do garbage collection?

### ISSUE THREAD

**Issue by zhouxian** [taichi-dev/taichi#5418]
The following code raises GPU out-of-memory issue. However, if a is only assigned once, it works fine.
How do I collect garbage of the old a when assigning a to a new ti.field? Thanks!
```python
import taichi as ti
ti.init(ti.gpu)

a = ti.field(shape=(3000,10000), dtype=ti.f64)
a.fill(0)
a = ti.field(shape=(3000,10000), dtype=ti.f64)
a.fill(0)
```

**Comment by turbo0628** [comment]
It's just that you need to preserve more GPU memory for Taichi.

You should see the following line at the beginning of the error message
```
Consider using ti.init(device_memory_fraction=0.9) or ti.init(device_memory_GB=4) to allocate more GPU memory` failed
```

**Comment by zhouxian** [comment]
@turbo0628 no i don't think so...
As I said,  if a is only assigned once, it works. i.e. the following runs fine:
```python
import taichi as ti
ti.init(ti.gpu)

a = ti.field(shape=(3000,10000), dtype=ti.f64)
a.fill(0)
```

**Comment by erizmr** [comment]
Hi @zhouxian , there are some references for management of memory in the docs. Would you mind referring to https://docs.taichi.graphics/docs/layout/#manage-memory-occupancy ?

**Comment by zhouxian** [comment]
@erizmr Thanks! That looks helpful.
