### ISSUE TITLE
[ti.opengl] Slow window showing

### ISSUE THREAD

**Issue by compik710** [taichi-dev/taichi#5438]
While using taichi, I found a fps leak while using the gui.show() function. To test, I made the following code:

```py
import taichi as ti
import time

ti.init(arch=ti.opengl)

w,h=1920,1080
img = ti.Vector.field(3,ti.f32,(w,h))

gui = ti.GUI("Win", res=(w,h), fast_gui=True)
gui.fps_limit=1000

while gui.running:
	gui.get_event(gui.PRESS)
	if gui.is_pressed('c'):
		gui.running=False
		break
	
	gui.show()
```

Next, I ran the script, and got this fps:
![Screenshot 2022-07-17 19-35-23](https://user-images.githubusercontent.com/68602173/179394387-4f860168-3c7b-4318-b06d-5d4e17d259a6.png)

Terminal:
```
$ python3 taichi_test7.py 
[Taichi] version 1.0.4, llvm 10.0.0, commit 2827db2c, linux, python 3.10.4
[Taichi] Starting on arch=opengl
```

Why such low fps? The display process must take place in the video card and must be at least 1000 fps.
If the image constantly being loaded from RAM - this is pretty bad.

**Comment by neozhaoliang** [comment]
@compik710 

1. Setting `fast_gui=True` still requires copying the image data from gpu to cpu. It's not cost free.
2. Your resolution is 1920x1080, this also affects the performance.

Maybe you can try setting `gui = ti.GUI("Win", res=(w,h), fast_gui=True, vsync=False`?

**Comment by compik710** [comment]
@neozhaoliang 
I plan to make a game using taichi along with ti.opengl, so this screen resolution is required.
Why is it necessary to copy to the CPU? Why can't you leave a field in the video card? Please add a framebuffer like in OpenGL.

and vsync does not exist:
'''
TypeError: GUI.__init__() got an unexpected keyword argument 'vsync'
'''

**Comment by neozhaoliang** [comment]
@compik710 sorry my mistake, `vsync=True` options only works for `ti.ui.Window`.
I think you can use `ti.ui.Window` instead, it works like you said and does not require copying to cpu.

**Comment by compik710** [comment]
@neozhaoliang 
I tried to use ti.ui.Window, fps really increased!
But now set_image() doesn't work :face_with_spiral_eyes: 
```py
import taichi as ti
import time

ti.init(arch=ti.opengl)

w,h=1920,1080
img = ti.Vector.field(4,ti.f32,(w,h))

win = ti.ui.Window("Win", res=(w,h), vsync=False)
canvas = win.get_canvas()

while win.running:
	canvas.set_image(img)
	win.show()
```
Output:
```
RuntimeError: [spirv_ir_builder.cpp:get_primitive_type@292] Type u8 not supported.
GLFW Error 65537: The GLFW library is not initialized
```

**Comment by neozhaoliang** [comment]
Seems something is wrong with our opengl backend. @bobcao3 would you please have a look at this?

**Comment by compik710** [comment]
@neozhaoliang 
Yes it works. however, 2 months ago, the volcano was not working...
Do you think it's okay that I'll use the vulkan? Is vulkan preinstalled on all modern computers?
I need the game to run on most modern computers.

**Comment by neozhaoliang** [comment]
Yes vulkan is supported on most modern computes and  you can trust on it.

**Comment by compik710** [comment]
@neozhaoliang 
I will use vulkan, thank you very much!

**Comment by neozhaoliang** [comment]
Looking forward to your great work!
