### ISSUE TITLE
Got `__getitem__` error when passing ndarray as template.

### ISSUE THREAD

**Issue by Morcki** [taichi-dev/taichi#5452]
**Describe the bug**
When passing ti.ndarray as template arg, and try to get item value from the arg, it reports bug as below:
`AssertionError: __getitem__ cannot be called in Taichi-scope`

**Python Script**
the python script is as below:
```py
import taichi as ti

ti.init(arch=ti.cpu)

from taichi.types import ndarray_type
from taichi.types.annotations import template

@ti.kernel
def load_item_error(arr_src : template(), arr_dst : template()):
    for i, j in ti.ndrange(*arr_src.shape):
        arr_dst[i, j] = arr_src[i, j]

@ti.kernel
def load_item_correct(arr_src : ndarray_type.ndarray(), arr_dst : ndarray_type.ndarray()):
    for i, j in ti.ndrange(*arr_src.shape):
        arr_dst[i, j] = arr_src[i, j]

arr_0 = ti.ndarray(ti.f32, shape = (5, 10))
arr_1 = ti.ndarray(ti.f32, shape = (5, 10))

# report bug
load_item_error(arr_0, arr_1)

# correct case
# load_item_correct(arr_0, arr_1)
```

If I choose the `load_item_correct` kernel, it would be right without errors, It seems like there is something wrong in template().

**Comment by strongoier** [comment]
`ti.ndarray` shouldn't be passed in via `ti.template()`. The problem here is that the error message isn't helpful. Maybe we should throw a clear error in this case? @ailzhang
