### ISSUE TITLE
Better error message for using ggui on opengl backend

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5462]
Related issue #5438 

When using `ti.ui.Window` on `arch=opengl`, it reports error

```
RuntimeError: [spirv_ir_builder.cpp:get_primitive_type@292] Type u8 not supported.
GLFW Error 65537: The GLFW library is not initialized
```

Shall we make it more specify like "use ggui on opengl backend is not supported?"

**Comment by PENGUINLIONG** [comment]
Attempted to fix this problem but ended up that `set_image` wouldn't be working properly without a significent fix in the OpenGL backend (mainly to support Vulkan-OpenGL interop). Based on that the GGUI is implemented completely in Vulkan and Vulkan was introduced to replace OpenGL, if the user is able to launch GGUI I think it's better not to use the OpenGL backend. Ideally the OpenGL backend should be used only for deployment on old embedded devices.

But AFAIK there was a plan to implement Vulkan-OpenGL interop, so I'm gonna defer this fix to that point.
