### ISSUE TITLE
If condition must be int32 error

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5466]
To reproduce:

```python
import taichi as ti
ti.init(default_ip=ti.i64)

@ti.kernel
def test():
    for i in range(100):
        if i % 2 == 0:
            print(i)

test()
```
The above code reports error
```
taichi.lang.exception.TaichiTypeError: 
`if` conditions must be of type int32; found i64. Consider using `if x != 0` instead of `if x` for float values.
```

**Comment by yuanming-hu** [comment]
@strongoier I feel like the systematic solution here is to use `i1` (boolean). Do you have a timeline for this? :-) 

Related: https://github.com/taichi-dev/taichi/issues/577

**Comment by strongoier** [comment]
Currently we use `i32` to represent boolean and it is self-contained. The bug in this issue is due to wrong implementation, and can be easily fixed by #5487. `i1` is only a nice-to-have for now, and we may plan it in some future version like v1.3 or so.

**Comment by SuperWildFireFox** [comment]
while x<0 still has this error.pls fix it.

**Comment by SuperWildFireFox** [comment]
I used #5487,and if x<0 work will, but while x<0 still can not work

**Comment by SuperWildFireFox** [comment]
it will still happened in while loop

**Comment by strongoier** [comment]
Hi @SuperWildFireFox. Could you provide a code snippet with this error? Thanks.

**Comment by SuperWildFireFox** [comment]
`import taichi as ti

ti.init(default_ip=ti.i64)


@ti.kernel
def test():
    a = 20
    while a > 0:
        a -= 1


test()`

output:`while` conditions must be of type int32; found i64. Consider using `while x != 0` instead of `while x` for float values.

**Comment by SuperWildFireFox** [comment]
I used #5487 ,and It worked,if condition can work very well.but still have problem in while loop.

**Comment by SuperWildFireFox** [comment]
and thank you for your quick reply.

**Comment by SuperWildFireFox** [comment]
I also tried this:
```
import taichi as ti
ti.init(default_ip=ti.i64)


@ti.kernel
def test():
    a = 20
    while ti.cast(a > 0, ti.i32):
        a -= 1


test()
```
still output:
`while` conditions must be of type int32; found i64. Consider using `while x != 0` instead of `while x` for float values.

**Comment by SuperWildFireFox** [comment]
I really need a temporary solution,thanks.

**Comment by neozhaoliang** [comment]
Reopen this issue since the while condition needs also to be handled.

**Comment by strongoier** [comment]
@re-xyr Could you help take a look? Thanks.

**Comment by SuperWildFireFox** [comment]
Thanks very much.

**Comment by SuperWildFireFox** [comment]
After I applied this modification,I can use four int64 to simulate float256 and draw this in 10^-55 precision :)
Re:-0.6717536270481832370389902348813046305959745988723619134343491834092885898911496280
Im:0.4609205425545165168733304746281937721035176497122051662619296867035239619125442493
zoom:2.28E54
![frame_00372](https://user-images.githubusercontent.com/106422075/180963016-3791fded-715b-4231-b737-fac8caf909af.png)
Thanks again for your efficient bug fix.

**Comment by neozhaoliang** [comment]
@SuperWildFireFox Do you mind sharing your code? I'm interested in how you made the float256 arithmetic and how efficient the program runs.

**Comment by SuperWildFireFox** [comment]
Maybe one or two days later, I will release my code.It is just an experimental program, but the efficiency is satisfactory to me.

**Comment by SuperWildFireFox** [comment]
Here are the basic code:
https://github.com/SuperWildFireFox/MandelbrotZoom/blob/main/FLOAT/FLOAT256.py
