### ISSUE TITLE
Add descriptive names to fields

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5467]
When debugging the out of index error for fields, we don't have a descriptive name for the field:

```python
import taichi as ti
ti.init(debug=True)

x = ti.field(int, shape=(2, 2))

@ti.kernel
def test():
    x[3, 3] = 1

test()
```

The above code gives error
```
taichi.lang.exception.TaichiAssertionError: 
(kernel=test_c56_0) Accessing field (S2place<i32>) of size (2, 2) with indices (3, 3)
```

The name `test_c56_0` is quite obscure here, shall we use a more descriptive name for it?

**Comment by ailzhang** [comment]
FYI `test_c56_0` is kernel name, not field name :P

**Comment by neozhaoliang** [comment]
Reopen this issue as the current fix is a temporary solution. It simply prints the line number where the error occurs. We should better show the field name.

**Comment by yuanming-hu** [comment]
Thanks @neozhaoliang for tracking this. After experiencing the latest `taichi-nightly`, I feel like the current way of showing the exact line number is good enough for now. Showing the field name can be something with low priority.
