### ISSUE TITLE
Support syntax ti.f32(x), ti.f64(x) for variable x

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5470]
Currently only literals are allowed like `ti.f64(1.0)`, hope we can also support variables.

Example code:

```python
import taichi as ti
ti.init()

@ti.kernel
def test():
    x = ti.f64(1.0)
    y = ti.i64(x)

test()
```
Error message:
```
    y = ti.i64(x)
        ^^^^^^^^^
Type annotation can only be given to a single literal.
```

**Comment by yuanming-hu** [comment]
Related question: do we support vector/matrices? E.g.,

```python
a = ti.Vector([1, 2])
print(ti.f32(a))
```

**Comment by k-ye** [comment]
> Related question: do we support vector/matrices? E.g.,
> 
> ```python
> a = ti.Vector([1, 2])
> print(ti.f32(a))
> ```

What's the expectation of this cast...?

**Comment by neozhaoliang** [comment]
I think this is more like a syntax sugar to shorten the code, like numpy's `astype(np.uint8)` and `np.uint8(x)`. 
A practical example is if want to convert a list of floats in range [0, 1] to uint8 colors, then we can just write `ti.u8(255 * x)`.

**Comment by yuanming-hu** [comment]
> What's the expectation of this cast...?

Should be equivalent to `ti.cast(a, ti.f32)`.

**Comment by k-ye** [comment]
I see. From a C++ dev's perspective, `astype()` seems more intuitive to me. Otherwise I would assume the syntax to be cast  `vec3` to a `float` scalar.
