### ISSUE TITLE
Unify `ti.kernel` and `ti.classkernel`

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#548]
**Concisely describe the proposed feature**
Currently, people have to use `ti.kernel` to decorate kernel definitions outside classes and `ti.classkernel` for those inside `@ti.data_oriented` classes (See [here](https://taichi.readthedocs.io/en/latest/odop.html)). This increases the learning burden of newcomers. Maybe there's a smart way to use `ti.kernel` inside `data_oriented` classes as well.

**Additional comments**
If possible, maybe we can even remove the `@ti.data_oriented` decorator...

**Comment by k-ye** [comment]
i'm kind of interested in this, taking it... :p. FYI my idea is probably to test if the kernel being decorated belongs to a class or not

**Comment by yuanming-hu** [comment]
> test if the kernel being decorated belongs to a class or not

I tried to do this a couple of months ago, yet it turns out to be a bit challenging. Maybe you have good solutions :-)

**Comment by k-ye** [comment]
I found a way to check if the function passed in belongs to a class or not at kernel execution time. However, this leads to the `grad()` also being instantiated only after the kernel itself has been executed at least once. This broke a few tests where `grad()` is invoked directly, e.g.

https://github.com/taichi-dev/taichi/blob/cb551f3c9b448176d83ae247ad6ddbe91365311a/tests/python/test_offload.py#L82

Do you think it's reasonable to enforce that `grad()` should be invoked only after kernel invocation? If so, i think i can just go fix these tests...

**Comment by yuanming-hu** [comment]
> I found a way to check if the function passed in belongs to a class or not at kernel execution time. 

Cool! 

> Do you think it's reasonable to enforce that grad() should be invoked only after kernel invocation? If so, i think i can just go fix these tests...

That might be a restriction people don't want. There are a few cases where they only use the gradients...

**Comment by yuanming-hu** [comment]
After more googling, I find a new SO post that I didn't run into months ago: https://stackoverflow.com/questions/8793233/python-can-a-decorator-determine-if-a-function-is-being-defined-inside-a-class

Could this be used to test if the function passed is a class member function, at preprocessing time?

**Comment by k-ye** [comment]
jeez.... yep that's definitely better than my approach, i can try if it works...

**Comment by k-ye** [comment]
Fixed by #552
