### ISSUE TITLE
Possible improvement on the description of data layout 

### ISSUE THREAD

**Issue by houkensjtu** [taichi-dev/taichi#5491]
**Description**
[The description on the data layout](https://docs.taichi-lang.org/docs/layout#row-major-versus-column-major) only mentioned a case of a 2-D field, where the data axes were labeled as ```ti.i``` and ```ti.j```. 
```Python
ti.root.dense(ti.i, M).dense(ti.j, N).place(x)   # row-major
ti.root.dense(ti.j, N).dense(ti.i, M).place(y)   # column-major
```
It is unclear how users can handle a field of **more than 3 dimensions**. i.e.: Are ```ti.k```, ```ti.l```,  ```ti.m```, etc. valid expressions? 

**Background**
In numerical simulations, users might want to allocate a field of 4 dimensions, in which they can store a physical quantity (for example, density). The four dimensions typically stand for x, y, z, and t (time). The user wants to modify the data layout so that data access is optimized for elements that are close in space, while the time axis can be less important.

**Note**
It might be questionable whether it's necessary to create a 4 dimensions field. Some users handle the time axis by allocating a [double buffer](https://github.com/takah29/2d-fluid-simulator/blob/e4508c290324861a0b5df1306348c7bc42bc9941/solver.py#L10). How this double buffer approach compares to a fine-tuned 4 dimension data layout is **unclear**, and it might worth further discussion.

**Credit**
@yjhp1016 and @ly16302 brought up this question during our discussion on the usage of Taichi on the LBM method.

**Comment by yuanming-hu** [comment]
This is an extremely useful feature in scientific computing. I think there are two TODOs:
1. Verify whether the row-major and column-major specification method (using `ti.i` and `ti.j`)  works
2. Design a simpler syntax for this use case. For example,
```
v = ti.field(dtype=vec2, shape=(32, 64, 128), order='kij', layout=ti.Layout.SOA)
```
3. Add these to the doc so that users know such usage.

**Comment by strongoier** [comment]
> Verify whether the row-major and column-major specification method (using ti.i and ti.j) works

This one was fixed and presented during taichiCourse01.

**Comment by yuanming-hu** [comment]
Thanks @strongoier for confirming this. For the API, I'd prefer

```python
v = ti.field(dtype=vec2, shape=(32, 64, 128), order='kij', layout=ti.Layout.SOA)
u = ti.field(dtype=vec2, shape=(32, 64, 23, 22, 11), order='ijklm', layout=ti.Layout.AOS)
p = ti.field(dtype=vec2, shape=(32, 64, 23, 22, 11), order=(0, 1, 2, 3, 4, 5), layout=ti.Layout.AOS)

# For 2D arrays
a = ti.field(dtype=vec2, shape=(32, 64), order=ti.Order.row_major, layout=ti.Layout.AOS)
b = ti.field(dtype=vec2, shape=(32, 64), order=ti.Order.column_major, layout=ti.Layout.AOS)
```

WDTY? @houkensjtu @k-ye :-)

**Comment by houkensjtu** [comment]
I agree that this is a crucial feature for scientific computing users. As for the TODOs, I would suggest confirming the following items in addition to @yuanming-hu 's comments:
1. It's important to add contents in the doc that explain how a user could verify the results of a certain data layout.
2. For the API suggested by @yuanming-hu , are we going to replace the old ```ti.root.X``` expressions? It might be better to keep the old-style expressions since the syntax change seems pretty radical.
3. For the case of 2D arrays, I'm not sure if introducing ```ti.Order.row_major``` and ```ti.Order.column_major``` is more intuitive for users than simply saying ```order='ij'```... Maybe @k-ye and @strongoier can provide some thinking from a language designer's perspective.

**Comment by k-ye** [comment]
I agree that having `ti.ij` and `ji` seems enough already, and having many ways to the same thing could just confuse the users.

One nit is that I hope we can just use `order=ti.ijk` instead of `order='ijk'` (a `str`), it's basically the same principle:  there is just one way to do a thing.

**Comment by yuanming-hu** [comment]
> I agree that having ti.ij and ji seems enough already, and having many ways to the same thing could just confuse the users.

Sounds good. Let's discard the `ti.Order.row_major` proposal and stick to `ijk`.

> One nit is that I hope we can just use order=ti.ijk instead of order='ijk' (a str), it's basically the same principle: there is just one way to do a thing.

I worry that we'll need to enumerate the number of indices as the user's array gets more dimensionality. For `ti.ijkl` etc. we will need to introduce `24` constants... WDYT?

**Comment by k-ye** [comment]
> I worry that we'll need to enumerate the number of indices as the user's array gets more dimensionality. For ti.ijkl etc. we will need to introduce 24 constants... WDYT?

It's possible to automate the generation, much like how we generated swizzles 😆 https://github.com/taichi-dev/taichi/blob/master/python/taichi/lang/swizzle_generator.py

**Comment by yuanming-hu** [comment]
Yeah, that's very true. Two slight issues though:
 - Auto-generated symbols may confuse IDEs and result in edit-time warnings ("symbol not found")
 - Too many symbols in a class/namespace?

**Comment by k-ye** [comment]
Yeah agreed. I think the effort to support both `ti.ijk` and `'ijk'` is not that much, and str provides better flexibility :-)

**Comment by houkensjtu** [comment]
Thx @strongoier for helping us on this issue. As we can pass a string type ```order``` to a scalar, vector or matrix field constructor, I think the main request from our user is fulfilled (also suggested by @yuanming-hu ). Possible future development work can be:

1. Support the same ```order``` feature for a struct field
2. Update the description on data layout to explain this new feature

This issue will be closed for now unless we see further comment.

**Comment by houkensjtu** [comment]
It's reported during our SIG live discussion that the `order = ij` layout gives slightly better performance than the default layout. (Confirmed on M1 Macbook) To reproduce:
```python
ti.init(arch=ti.cpu, kernel_profiler=True)

n = 4096
m = 4096

a = ti.field(dtype=ti.i32, shape=(n, m)) # default layout
# a = ti.field(dtype=ti.i32, shape=(n, m), order='ij') # explicit row major

@ti.kernel
def foo():
    for i in range(n):
        for j in range(m):
            a[i, j] = i + j

for repeat in range(100): 
    foo()

ti.profiler.print_kernel_profiler_info() # explicit row-major gives slightly better performance. why?
```
It's expected that the default layout and the explicit `order=ij` layout should be identical, but it seems they are not. Any thoughts? @strongoier

**Comment by strongoier** [comment]
To avoid changing the behavior of existing code,
```python
a = ti.field(dtype=ti.i32, shape=(n, m)) # default layout
```
still equals to
```python
a = ti.field(dtype=ti.i32)
ti.root.dense(ti.ij, (n, m)).place(a)
```
New behavior is applied when `order` is set, and
```python
a = ti.field(dtype=ti.i32, shape=(n, m), order='ij') # explicit row major
```
equals to
```python
a = ti.field(dtype=ti.i32)
ti.root.dense(ti.i, n).dense(ti.j, m).place(a)
```
As you can see, the result `SNodeTree`s are different so the performance difference is possible.

**Comment by houkensjtu** [comment]
> As you can see, the result `SNodeTree`s are different so the performance difference is possible.

Thanks for the explanation! 

If I understand your point correctly, `ti.root.dense(ti.ij, (n, m)).place(a)` and `ti.root.dense(ti.i, n).dense(ti.j, m).place(a)` both results in a 2-D field  `a` (which is row-major), but the `SNodeTree`
 behind them are different, am I correct?

I think we had a paragraph in the documentation that described the same example:
https://docs.taichi-lang.org/docs/layout#layout-101-from-shape-to-tirootx

It appeared to me that the two statements are equivalent even in terms of `SNodeTree` structure. If they are not identical, maybe we should mention the difference explicitly in the doc. @strongoier @yuanming-hu

**Comment by strongoier** [comment]
> If I understand your point correctly, ti.root.dense(ti.ij, (n, m)).place(a) and ti.root.dense(ti.i, n).dense(ti.j, m).place(a) both results in a 2-D field a (which is row-major), but the SNodeTree
behind them are different, am I correct?

Yes. You're correct.

> If they are not identical, maybe we should mention the difference explicitly in the doc.

I think we should remove the sentences saying these two are equal. Could you help modify it? Thanks. @houkensjtu

**Comment by houkensjtu** [comment]
I tried to make a sketch to clarify the difference between `ti.root.dense(ti.ij, (n,m)).place(x)` and `ti.root.dense.(ti.i, n).dense(ti.j, m).place(x). 
<img width="683" alt="Screen Shot 2022-09-16 at 10 38 39" src="https://user-images.githubusercontent.com/2747993/190545525-305563dc-d09e-4af2-b99b-166d5c4398d0.png">
