### ISSUE TITLE
Rename CodeGenCPU/CUDA/WASM and CodeGenLLVMCPU/CUDA/WASM

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#5498]
**Concisely describe the proposed feature**
We now have `CodeGenCPU/CUDA/WASM` and `CodeGenLLVMCPU/CUDA/WASM` in the codebase, and it is hard to see the difference by just looking at the class names. 

**Describe the solution you'd like (if any)**
I propose that we rename `CodeGenCPU/CUDA/WASM` to `KernelCodeGenCPU/CUDA/WASM` and remane `CodeGenLLVMCPU/CUDA/WASM` to <s>`ModuleCodeGenCPU/CUDA/WASM`</s>`TaskCodeGenCPU/CUDA/WASM`  because `CodeGenLLVMCPU/CUDA/WASM` generate code of an offloaded task (or a whole kernel in WASM backend) to an LLVM module, and `CodeGenCPU/CUDA/WASM` generate code for a whole kernel using `CodeGenLLVMCPU/CUDA/WASM`.

**Comment by k-ye** [comment]
Out of curiosity, would a `KernelCodgen` produce one llvm module or several?

**Comment by lin-hitonami** [comment]
> Out of curiosity, would a `KernelCodgen` produce one llvm module or several?

`KernelCodeGen` produces several modules, and `ModuleCodeGen` produces one module.

**Comment by k-ye** [comment]
Sorry for the late reply.

It seems that the relationship seems a bit reversed to me, as I would expect that Module should contain Kernels, not the other way around. I feel like to properly describe this relationship, it might be better called Kernel and Task codegen?

**Comment by lin-hitonami** [comment]
> Sorry for the late reply.
> 
> It seems that the relationship seems a bit reversed to me, as I would expect that Module should contain Kernels, not the other way around. I feel like to properly describe this relationship, it might be better called Kernel and Task codegen?

Makes sense. Modules of many kernels can also be linked into an LLVM module. Then let us call them `KernelCodeGenXXX` and `TaskCodeGenXXX`.
