### ISSUE TITLE
Exception: Backend Arch.metal doesn't support dynamic index

### ISSUE THREAD

**Issue by lucywsq** [taichi-dev/taichi#5499]
When running the ti example "implicit_fem", it happened to report this error message:
[Taichi] version 1.0.3, llvm 10.0.0, commit fae94a21, osx, python 3.8.2
[Taichi] Starting on arch=metal

![image](https://user-images.githubusercontent.com/38712162/180415458-bf7f17be-2d7b-4ff2-be65-60719a371698.png)
![image](https://user-images.githubusercontent.com/38712162/180416246-c0d66cf6-8b6d-470f-93b7-603ab033417b.png)

**Comment by strongoier** [comment]
Dynamic indexing hasn't been supported on Metal yet. I'll send a PR to make it fallback to cpu so that the example can run on Metal.
