### ISSUE TITLE
Undefined behavior with gradients

### ISSUE THREAD

**Issue by samuela** [taichi-dev/taichi#550]
**Describe the bug**
According to https://taichi.readthedocs.io/en/latest/differentiable_programming.html,
> Taichi programs that violate this rule has an undefined gradient behavior.
>
> Note that currently the Taichi compiler is not able to detect such violation automatically - please be careful.

This seems super dangerous. Why can't we detect when Taichi is unable to calculate gradients correctly? As a user it'd be much safer to have Taichi reject programs that might work, rather than allow programs that will produce the wrong behavior.

**Comment by k-ye** [comment]
Closing this one by #553 . If you spot a case where the checker couldn't capture, please let me know, thx!

**Comment by samuela** [comment]
Thank you so much @k-ye ! This is really great.
