### ISSUE TITLE
Missing libtinfo.5.so on Ubuntu 19.04

### ISSUE THREAD

**Issue by tbarton16** [taichi-dev/taichi#551]
**Describe the bug**
Cannot find libtinfo. I installed libtinfo-dev and ncurses. Linux Ubuntu 19.01 cuda 10.1

**Log/Screenshots**

Share object taichi_core import failed. If you are on Windows, please consider installing "Microsoft Visual C++ Redistributable" (https://aka.ms/vs/16/release/vc_redist.x64.exe)
Traceback (most recent call last):
  File "diffmpm.py", line 1, in <module>
    import taichi as ti
  File "/home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.main import main
  File "/home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/main.py", line 6, in <module>
    from taichi.tools.video import make_video, interpolate_frames, mp4_to_gif, scale_video, crop_video, accelerate_video
  File "/home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/tools/video.py", line 3, in <module>
    import taichi.core as core
  File "/home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import tc_core, build, format, load_module, start_memory_monitoring, \
  File "/home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/core/util.py", line 189, in <module>
    import_tc_core()
  File "/home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/core/util.py", line 35, in import_tc_core
    raise e
  File "/home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/core/util.py", line 31, in import_tc_core
    import taichi_core as core
ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory

**To Reproduce**
Please post a sample code to reproduce the bug. The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the code short.

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**

**Comment by yuanming-hu** [comment]
It seems that `libtinfo.so.5` is missing. Are you using Ubuntu 18.10? Does this walkaround (https://github.com/microsoft/microsoft-r-open/issues/102) work for you?

**Comment by tbarton16** [comment]
No, if I do that I get a new error related to the ncurses version
`ImportError: /lib/x86_64-linux-gnu/libtinfo.so.5: version `NCURSES_TINFO_5.0.19991023' not found (required by /home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/core/../lib/taichi_core.so)
`

**Comment by yuanming-hu** [comment]
I see. Thanks for trying. Ubuntu 19.01 upgraded `libtinfo` from v5 to v6. Given that Most users are using `18.04`/`16.04`, we don't plan to upgrade `libtinfo` dependency.

However, if anyone has an idea to peel off the dependency on `libtinfo` or `libncurses`, that would be very helpful.

**Comment by tbarton16** [comment]
Where are these packages used? for display?

**Comment by yuanming-hu** [comment]
Yeah. Btw, could you try
```
sudo apt install libtinfo5
```
?

**Comment by tbarton16** [comment]
YAY! That worked i can `import taichi`. Thanks!
 Although now there is a runtime error in `diffmpm.py`
`[W 02/29/20 10:06:31.691] [taichi_llvm_context.cpp:module_from_bitcode_file@186] Bitcode loading error message:
Invalid bitcode signature
[E 02/29/20 10:06:31.691] [taichi_llvm_context.cpp:module_from_bitcode_file@188] Bitcode /home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/core/../lib/runtime_x64.bc load failure.
`
