### ISSUE TITLE
Potential Kernel Profiler Memory Leak

### ISSUE THREAD

**Issue by AppledoreM** [taichi-dev/taichi#5527]
**Describe the bug**
Kernel Profiler Memory Leak

**To Reproduce**
Here is a sample to reproduce, disabling the kernel profiler fixes the issue

```py
import taichi as ti
ti.init(arch=ti.cuda, random_seed = 0, kernel_profiler=True, device_memory_GB = 4.5, dynamic_index = False)
emptyField = ti.field(ti.i32, shape=())
if __name__ == "__main__":

    frame = 0
    while True:
        if frame == emptyField[None]:
            pass
        frame += 1
```

**Log/Screenshots**
![image](https://user-images.githubusercontent.com/29791930/180954752-f8c1b59f-1ed7-4e33-b230-a2a40dd82f9f.png)

```
$ python repro.py
[Taichi] version 1.0.4, llvm 10.0.0, commit 13983c78, linux, python 3.8.10
```

**Comment by qiao-bo** [comment]
If you print the kernel profiler info with `ti.profiler.print_kernel_profiler_info()` or just clear the data with `ti.profiler.clear_kernel_profiler_info()`, the occupied memory will be reset.
