### ISSUE TITLE
Dose Taichi support ResizableBAR or SmartMemmoryAccess?

### ISSUE THREAD

**Issue by EnochZhu** [taichi-dev/taichi#5530]

**Comment by lin-hitonami** [comment]
cc @turbo0628 @qiao-bo

**Comment by qiao-bo** [comment]
Hi, short answer is no. IIUC, these are very hw/vendor-specific features that are taken care of at the driver level. You need to tweak your bios setting and install gaming drivers etc to enable the effect. [[ref]](https://www.nvidia.com/en-us/geforce/news/geforce-rtx-30-series-resizable-bar-support/). We are in the process of supporting AMD GPU backends. If you can provide some example written in Taichi that can benefit from these features, we are happy to look further into it!

**Comment by bobcao3** [comment]
If you are using the Vulkan backend, it's possible that the driver is optimizing for this. This feature does not require any support, it may or may not already been optimized by the driver when accessing GPU memory @EnochZhu
