### ISSUE TITLE
[bug] quantaichi examples using deprecated Taichi interfaces 

### ISSUE THREAD

**Issue by jim19930609** [taichi-dev/taichi#5577]
From forum: https://forum.taichi.graphics/t/quantaichi-main/2803

Some quantaichi examples are broken due to the use of deprecated Taichi interfaces. 

Let's fix quantaichi examples then add a simple CI to monitor whether they're in sync with latest Taichi release (make it part of the release test?).

**Comment by strongoier** [comment]
It seems that my PR last month hasn't been merged yet (https://github.com/taichi-dev/quantaichi/pull/3) :-)
cc: @k-ye @yuanming-hu
