### ISSUE TITLE
Problems related to matrix multiplication by scalar

### ISSUE THREAD

**Issue by Morcki** [taichi-dev/taichi#5588]
**Describe the bug**
When try to multiply a scalar using one row of matrix, it will get just one result value instead of one row result value.

**To Reproduce**
Here is a test script:
```py
 import taichi as ti
 
 ti.init(arch=ti.cuda)
 
 @ti.kernel
 def test():
     mat = ti.Matrix([[1, 2, 3, 4],
                      [5, 6, 7, 8]])
 
     result_wrong = ti.Matrix([[mat[0] * 2],    # 2
                               [mat[1] * 4]])  # 20

     result_correct = ti.Matrix([[mat[0,:] * 2],   # 2, 4, 6, 8
                                 [mat[1,:] * 4]]) # 20, 24, 28, 32
     print(result_wrong)
     print(result_correct)    
 
 test()
```
In terms of common sense, users may want the result of `mat[0] * 2` to be [2, 4, 6, 8] instead of just [2].

**Comment by jim19930609** [comment]
Correct me if I were wrong @strongoier @AD1024, but I vaguely remember @AD1024 discussed this use case before and we decided to forbidden the implicit slicing of `mat[0]`, and users have to explicitly write `mat[0, :]` instead?

**Comment by strongoier** [comment]
Yep. We need to throw an error in the forbidden case and refer users to the correct version. @AD1024 Could you help with this?

**Comment by AD1024** [comment]
> Yep. We need to throw an error in the forbidden case and refer users to the correct version. @AD1024 Could you help with this?

Sure. I'll work on this :)
