### ISSUE TITLE
Access out-of-bound checking on CPU backends

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#561]
**Concisely describe the proposed feature**

Currently out-of-bound tensor accesses lead to undefined behavior. Oftentime taichi will just yield a wrong result without a loud failure. A lot of users complained about this. For example,

```python
ti.init(arch=ti.cuda, debug=True)

x = ti.var(ti.i32, shape=(8, 8, 8))

@ti.kernel
def boom():
  x[0, 0, 7] = 1 # OK
  x[0, 0, 8] = 1 # Access out of bound!
                 # Should trigger assertion failure instead of corrupting memory
                 # Should raise TaichiRuntimeError(
                 #      "Accessing Tensor of Size [8, 8, 8] with indices (0, 0, 8)")
```

**Describe the solution you'd like**
We can modify the codegen to add that check for every tensor access (before the `lower_access` IR pass) in debug mode.

***How to get the tensor bounds***: `[0, SNode::extractors[physical_index_position[i]].num_elements)`

***Code Generation***
First generate a set of compares for bound checking, and then summarize the results using `BinaryOp::and`. Pass the result to an `AssertStmt`. Note that `AssertStmt` now takes only a condition and a fixed message. Maybe we need to extend it with `(condition, format_str, values)` so that `Accessing Tensor of Size [8, 8, 8] with indices (0, 0, 8)` can be generated via `("Accessing Tensor of Size [8, 8, 8] with indices (%d, %d, %d)", input_i, input_j, input_k)`.

```C++
  int physical_index_position[taichi_max_num_indices]{};
  // physical indices are (ti.i, ti.j, ti.k, ti.l, ...)
  // physical_index_position[i] =
  // which physical index does the i-th virtual index (the one exposed to
  // programmers) refer to? i.e. in a[i, j, k], "i", "j", and "k" are virtual
  // indices.
```

******

**Additional comments**
 - [`pbf2d.py`](https://github.com/taichi-dev/taichi/blob/master/examples/pbf2d.py) sometimes crashes. It might be related to an access out-of-bound. Implementing this will help us diagnose.
 - The first step is to add bound checking on CPU (`x64`), and ultimately we may also want to implement that on GPUs. Taichi GPU programmers can, of course, switch back to CPUs to check for access out-of-bounds, which should work in most cases.

**Comment by archibate** [comment]
What's the influence on performance? Or this is default to off unless `ti.cfg.bound_detect = True`?

**Comment by yuanming-hu** [comment]
Correct, the asserts will only be enabled on debug mode.

**Comment by yuanming-hu** [comment]
Update: @xumingkuan is already working on this.

**Comment by xumingkuan** [comment]
`x[0, 0, 8] = 1` is a `GlobalPtrStmt *stmt` with `stmt->snodes.size() == 1`. I wonder if there is a case with `stmt->snodes.size() != 1` or if there is a case accessing tensor but the statement is not `GlobalPtrStmt`?

**Comment by yuanming-hu** [comment]
`stmt->snodes.size() != 1` is for vectorization, which is not supported now. Please just add an `TI_ASSERT(stmt->snodes.size() == 1)` there

**Comment by xumingkuan** [comment]
> First generate a set of compares for bound checking, and then summarize the results using `BinaryOp::and`. 

I only found `BinaryOpType::bit_and`. Shall I use it?

**Comment by yuanming-hu** [comment]
https://github.com/taichi-dev/taichi/blob/master/taichi/inc/binary_op.inc.h#L2

**Comment by xumingkuan** [comment]
> https://github.com/taichi-dev/taichi/blob/master/taichi/inc/binary_op.inc.h#L2

This is `add` :(

**Comment by yuanming-hu** [comment]
Oh sorry I thought you were talking about `add`. Yes, `bit_and` is fine.

**Comment by xumingkuan** [comment]
We can simplify `(111...1) and a` (a number with all bits set to 1) to `a` and `0 or a` to `a` in `alg_simp.cpp`, but we can't simplify `1 and a` to `a`. However, I think it strange to set the initial value of the result to `(111...1)`...

**Comment by yuanming-hu** [comment]
I wouldn't worry too much about that. The backend compiler can probably help with such simplification. Systematically fixing this needs adding `bool` or `u1` types to Taichi IR.

**Comment by xumingkuan** [comment]
How to change the behavior of `AssertStmt`? Now I can only find that the last function triggered in an assertion failure is https://github.com/taichi-dev/taichi/blob/master/taichi/program/program.cpp#L23.

**Comment by yuanming-hu** [comment]
Please extend `AssertStmt` to add in `fmt_string` and `args` fields. Then, on CPU backends, invoke a `sprintf` to get the formatted error message.

**Comment by xumingkuan** [comment]
After learning how to store a parameter pack as a variable for some time, I found that the class `AssertStmt` is probably required to be a template class in order to have a member variable like `std::tuple<Args...> args`. However, it raises compile error just by adding a line `template <typename... Args>` to the class. How can I fix it?

**Comment by yuanming-hu** [comment]
No, please do not make `AssertStmt` a template. There are much easier ways. Let's skype chat if you are available.

**Comment by xumingkuan** [comment]
https://github.com/taichi-dev/taichi/blob/master/taichi/runtime/llvm/runtime.cpp#L4
Why is it disabled on Windows?

**Comment by yuanming-hu** [comment]
I compile this file along with Taichi to let the compiler check if there's any compilation errors. MSVC has some compilation/linking errors at this stage, so I disabled Windows compilation.

Later the file will be compiled with `clang` into LLVM bit code. Note that when compiling this file to LLVM bit code `_WIN32` is not really defined.

**Comment by xumingkuan** [comment]
How to unpack the `std::vector<Stmt *>` to arguments of `sprintf`?

**Comment by yuanming-hu** [comment]
`call` supports a variable number of arguments: https://github.com/taichi-dev/taichi/blob/master/taichi/codegen/codegen_llvm.h#L775

**Comment by xumingkuan** [comment]
Both the arguments and the return value are of type `llvm::Value *`. How to allocate memory and get a proper `char *buffer` of type `llvm::Value *`? The size of the buffer can be determined by `snprintf(nullptr, 0, text, args...)`, I think.

**Comment by yuanming-hu** [comment]
I would simply allocate a global `char assert_msg_buffer[2048];` in `llvm/runtime.cpp` and get the pointer to that global variable.

**Comment by yuanming-hu** [comment]
I'm going to sleep now. Will be available after 9:30 am.

**Comment by xumingkuan** [comment]
Good night!

**Comment by xumingkuan** [comment]
After adding `exit(0)` after https://github.com/taichi-dev/taichi/blob/master/examples/pbf2d.py#L338, I got the following message:
```
[E 03/10/20 22:48:28.582] [program.cpp:taichi::lang::assert_failed_host@24] Assertion failure: Accessing Tensor of Size [1200, 100] with indices (8,, 69)

[E 03/10/20 22:48:28.582] [program.cpp:taichi::lang::assert_failed_host@24] Assertion failure: Accessing Tensor of Size [1200, 100] with indices (28, 97)

[E 03/10/20 22:48:28.582] [program.cpp:taichi::lang::assert_failed_host@24] Assertion failure: Accessing Tensor of Size [1200, 100] with indices (28, 68

[E 03/10/20 22:48:28.582] [program.cpp:taichi::lang::assert_failed_host@24] Assertion failure: Accessing Tensor of Size [1200, 100] with indices (12, 73)

[E 03/10/20 22:48:28.582] [program.cpp:taichi::lang::assert_failed_host@24] Assertion failure: Accessing Tensor of Size [1200, 100] with indices (12, 72)

[E 03/10/20 22:48:28.582] [program.cpp:taichi::lang::assert_failed_host@24] Assertion failure: Accessing Tensor of Size [1200, 100] with indices (28, 97)

[E 03/10/20 22:48:28.582] [program.cpp:taichi::lang::assert_failed_host@24] Assertion failure: Accessing Tensor of Size [1200, 100] with indices (28, 100)

[E 03/10/20 22:48:28.582] Received signal 22 (SIGABRT)

[E 03/10/20 22:48:28.582] [program.cpp:taichi::lang::assert_failed_host@24] Assertion failure: Accessing Tensor of Size [1200, 100] with indices (12, 87)


Process finished with exit code -1073740791 (0xC0000409)
```
Indices `(28, 100)` appear as expected.

Re-run the program produces different outputs, but each time there is sth with the 2nd index `100`.

I don't know why there are always these redundant outputs...

**Comment by yuanming-hu** [comment]
Interesting!! Yeah `(28, 100)` is clearly something suspicious. On the other hand, maybe it's time to add some basic test cases. Directly debugging the redundant outputs on `pbf2d.py` is likely inefficient. Those test cases will also help us monitor the long-term correctness of what you have done.

To avoid large changesets, I'll merge your PR as stage I, and after that please feel free to open another PR draft as stage II, with more unit tests.

**Comment by yuanming-hu** [comment]
Also, you probably need a lock for the buffer `char [2048]`. You can allocate a global `i32` as lock and make use of `locked_task`.

**Comment by xumingkuan** [comment]
I just found that https://github.com/taichi-dev/taichi/blob/master/examples/pbf2d.py#L266 is constantly failing in each run...

**Comment by yuanming-hu** [comment]
This might actually be one cause of your redundant outputs: multiple threads are using the buffer concurrently and your message gets messed up. You may also want to avoid error message formatting for valid accesses (just pass `cond` to `get_assert_msg`)

**Comment by yuanming-hu** [comment]
> I just found that https://github.com/taichi-dev/taichi/blob/master/examples/pbf2d.py#L266 is constantly failing in each run...

I also find a couple of other scripts failing. Let's add the lock first and see if there are any false positives.

**Comment by xumingkuan** [comment]
I found pbf2d.py can run successfully with the following changes:
```python
num_particles_x = 64
num_particles = 2048
max_num_neighbors = 128
```
Maybe `particle_neighbors.fill(-1)` needs `particle_neighbors` to have a size of power of 2 in each dimension.

**Comment by yuanming-hu** [comment]
Let me take a look into `Expr.fill`. Maybe there's something wrong with `struct-for` to `range-for` demotion.

**Comment by yuanming-hu** [comment]
I know what's wrong and I believe that's fixed locally. It's a false positive due to an issue in the optimizer.

In short: a `GlobalPtrStmt` gets move outside `if`, which safe-guards it from generating out-of-bound pointers. This is not causing any issue before since the `GlobalStoreStmt` is still in the `if` statement so the behavior is well-defined. Running tests to see if my fix breaks something else...

**Comment by yuanming-hu** [comment]
Fixed that false-positive case in master.

**Comment by yuanming-hu** [comment]
Going to sleep now. Will be available after 9:30 am tmr.

**Comment by yuanming-hu** [comment]
Closing this now as the basic functionality is up. Thanks to the contributions by @xumingkuan. To make this testable: #591
