### ISSUE TITLE
[bug] [aot] aot report bug on vulkan backend

### ISSUE THREAD

**Issue by Morcki** [taichi-dev/taichi#5699]
**Describe the bug**
When running kernels and export aot files at the same time under vulkan backend, it reports bug. However, under cuda backend, there is no error information. In other words, cannot run kernels and export kernels at the same time.

```py
# sample code here
import taichi as ti

arch=ti.vulkan
ti.init(arch=arch)

g_init_builder = ti.graph.GraphBuilder()
mod = ti.aot.Module(arch)


@ti.kernel
def init_data(test_arr : ti.types.ndarray(field_dim=1)):
    test_arr[0] = 0

arr = ti.ndarray(ti.f32, shape=2)
sym_arr = ti.graph.Arg(ti.graph.ArgKind.NDARRAY,
                                'arr',
                                ti.f32,
                                field_dim=1,
                                element_shape=())
init_data(arr)


g_init_builder.dispatch(init_data, 
                        sym_arr)

g_init = g_init_builder.compile()

mod.add_graph('init', g_init)
mod.save("./temp", '')
```

**Comment by ailzhang** [comment]
fyi after you construct and compile the graph you can run it via `g_init({'arr': arr})` and that's supposed to match the behavior in C++. 
But yea we should fix this :D

**Comment by Morcki** [comment]
yeah, not urgent for this cause I can handle it in other way. but we need to fix this a bit later.
