### ISSUE TITLE
Is there any example about 3-D rendering?

### ISSUE THREAD

**Issue by Novarizark** [taichi-dev/taichi#570]
I am a postdoc in atmospheric sciences. In the last several days, I tried to search tools to render a 3-D typhoon model (releasing particles given 3-D velocity fields), and found Taichi could be a good start. For a layman in computer vision, is there any example about Taichi on 3-D rendering?

**Comment by yuanming-hu** [comment]
If you want to render particles with motion blur then a good example would be https://github.com/taichi-dev/taichi/blob/master/examples/particle_renderer.py
