### ISSUE TITLE
Bug: "Font file not found"

### ISSUE THREAD

**Issue by doudou533** [taichi-dev/taichi#5714]
Traceback (most recent call last):
  File "/home/dou/Downloads/finger in fluid_HSW/main.py", line 23, in <module>
    gui.text('trig_pos = ' + str(x_disp[mark_particle_ind]), [0.2, 0.8],font_size=20, color=0x000000)
  File "/home/dou/anaconda3/envs/JAX-sw/lib/python3.9/site-packages/taichi/ui/gui.py", line 652, in text
    self.canvas.text(content, pos, font_size, color)
RuntimeError: [image_buffer.cpp:write_text@120] Font file not found: /home/dou/anaconda3/envs/JAX-sw/lib/python3.9/site-packages/taichi/_lib/runtime/../../assets/Go-Regular.ttf
[E 08/10/22 16:17:56.254 350471] [image_buffer.cpp:write_text@120] Font file not found: /home/dou/anaconda3/envs/JAX-sw/lib/python3.9/site-packages/taichi/_lib/runtime/../../assets/Go-Regular.ttf

**Comment by ailzhang** [comment]
@doudou533 which version of taichi do you have? IIRC this was fixed in #5063

**Comment by doudou533** [comment]
I have solved this problem. Just upgrade Taichi to the latest version.

**Comment by doudou533** [comment]
I have solved this problem. Just upgrade Taichi to the latest version.

**Comment by doudou533** [comment]
I have solved this problem. Just upgrade Taichi to the latest version.
