### ISSUE TITLE
Python style (pointer) assignment inside kernels

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#574]
**Concisely describe the proposed feature**
To prevent cluttering OOP code with ```self.```'s, it would be nice if the we could do python style assignment of variables inside kernels. This way local variables could point to the same data as a class members, but have a different (selfless) name.    

For example long finite difference equations would be a lot cleaner if we could assign variables like this, then use their shorter names on the rhs of equations
``` python
@ti.kernel
def compute_b():
  a, dx, dy = self.a, self.dx, self.dy
  for i,j in a:
    self.b[i,j] = (a[i+1,j] - 2.0*a[i,j] + a[i-1,j])/(dx*dx) \
                + (a[i,j+1] - 2.0*a[i,j] + a[i,j-1])/(dy*dy) 
```

**Describe the solution you'd like (if any)**
I think all that needs to be done would be to skip the AST assign transform in cases where we want to use python style (pointer) assignment instead of taichi style (value). But how could we identify these cases?

**Comment by yuanming-hu** [comment]
Good idea! Maybe we can use `ti.static`:
```python
a = ti.static(self.a)
dx = ti.static(self.dx)
dy = ti.static(self.dy)

#or simply
a, dx, dy = ti.static(self.a, self.dx, self.dy)
```

In AST transform (`visitAssign`), don't do anything if the RHS is `ti.static(...)`, just like static-for loops: https://github.com/taichi-dev/taichi/blob/master/python/taichi/lang/transformer.py#L271

**Comment by KLozes** [comment]
Seems like an easy solution! I'll implement it tonight and come up with a test.

**Comment by archibate** [comment]
Great! But before that, I'd like to suggest you to use another function `ti.just` other than `ti.static` to take the response of disabling transformation, since `ti.static` expect input to be `compile-time constant values, instead of <class 'taichi.lang.expr.Expr'>`. So we'd better to let `ti.static` to keep focus on compile-time optimization (eg. unrolling range for) and `ti.just` for no-transform signature.

**Comment by yuanming-hu** [comment]
> Great! But before that, I'd like to suggest you to use another function `ti.just` other than `ti.static` to take the response of disabling transformation, since `ti.static` expect input to be `compile-time constant values, instead of <class 'taichi.lang.expr.Expr'>`. So we'd better to let `ti.static` to keep focus on compile-time optimization (eg. unrolling range for) and `ti.just` for no-transform signature.

I would say `<class 'taichi.lang.expr.Expr>` is indeed a compile-time constant value for the Taichi compiler :-) Introduce `ti.just` might be one more keyword for programmers to memorize.

**Comment by archibate** [comment]
Can't make `ti.static` happy:
https://github.com/taichi-dev/taichi/blob/73b546fd67f266165781dc43b627b2e22d0bebc3/python/taichi/lang/impl.py#L293
See #575 if you have any suggestions to fix this.

**Comment by archibate** [comment]
Btw, do you think a compile-time `if` is necessary? I mean like `<?php` and `?>`, we may:
```
ti.macro_begin()
if xxx:
ti.macro_end()
  func1()
```
for compile time conditions, prints, etc.

**Comment by yuanming-hu** [comment]
> Can't make `ti.static` happy:
> https://github.com/taichi-dev/taichi/blob/73b546fd67f266165781dc43b627b2e22d0bebc3/python/taichi/lang/impl.py#L293-L295
> 
> 
> See #575 if you have any suggestions to fix this.

Let's add `ti.Expr` and `ti.Vector` to that list

**Comment by yuanming-hu** [comment]
> Btw, do you think a compile-time `if` is necessary? I mean like `<?php` and `?>`, we may:
> 
> ```python
> ti.macro_begin()
> if xxx:
> ti.macro_end()
>   func1()
> ```
> 
> for compile time conditions, prints, etc.

`if ti.static(x): ...` and `ti.static_print` do the jobs for your :-)

**Comment by archibate** [comment]
> > Can't make `ti.static` happy:
> > https://github.com/taichi-dev/taichi/blob/73b546fd67f266165781dc43b627b2e22d0bebc3/python/taichi/lang/impl.py#L293-L295
> > 
> > See #575 if you have any suggestions to fix this.
> 
> Let's add `ti.Expr` and `ti.Vector` to that list

Then a rude user can say: `for i in range(ti.static(x[None]))`.

**Comment by archibate** [comment]
> > Btw, do you think a compile-time `if` is necessary? I mean like `<?php` and `?>`, we may:
> > ```python
> > ti.macro_begin()
> > if xxx:
> > ti.macro_end()
> >   func1()
> > ```
> > 
> > 
> > for compile time conditions, prints, etc.
> 
> `if ti.static(x): ...` and `ti.static_print` do the jobs for your :-)

But `ti.macro_begin()` may do more! See this:
```py
ti.macro_begin()
x = input('tell me your age:')
ti.macro_end()
y = ti.just(input('hello?'))
```

**Comment by yuanming-hu** [comment]
> > > Can't make `ti.static` happy:
> > > https://github.com/taichi-dev/taichi/blob/73b546fd67f266165781dc43b627b2e22d0bebc3/python/taichi/lang/impl.py#L293-L295
> > > 
> > > See #575 if you have any suggestions to fix this.
> > 
> > 
> > Let's add `ti.Expr` and `ti.Vector` to that list
> 
> Then a rude user can say: `for i in range(ti.static(x[None]))`.

I see. Maybe we should also check if their entries are `global variables`.



> ```python
> ti.macro_begin()
> x = input('tell me your age:')
> ti.macro_end()
> y = ti.just(input('hello?'))
> ```
> 
> 
> We can't keep adding more new python-scope function to ti.static_input etc., can use macro guards instead to give more flexibility to user!

But on the other hand, why do the users need to input something during kernel compilation (which is supposed to be transparent to the users)? I don't think there's a need for this.

**Comment by archibate** [comment]
> > > > Can't make `ti.static` happy:
> > > > https://github.com/taichi-dev/taichi/blob/73b546fd67f266165781dc43b627b2e22d0bebc3/python/taichi/lang/impl.py#L293-L295
> > > > 
> > > > See #575 if you have any suggestions to fix this.
> > > 
> > > 
> > > Let's add `ti.Expr` and `ti.Vector` to that list
> > 
> > 
> > Then a rude user can say: `for i in range(ti.static(x[None]))`.
> 
> I see. Maybe we should also check if their entries are `global variables`.

How can I detect that? Is `global variables` expected to be a good constant for `range for`? Or you mean the constantness not by the variable value, but their pointer (address)?

**Comment by yuanming-hu** [comment]
Please see https://github.com/taichi-dev/taichi/blob/b0f72762fa64dfa3c266892e4608b70177742e1e/python/taichi/lang/matrix.py#L97

> Or you mean the constantness not by the variable value, but their pointer (address)?

Correct!
