### ISSUE TITLE
Lock metadata.lock failed

### ISSUE THREAD

**Issue by sunjinlongsir** [taichi-dev/taichi#5743]
import taichi as ti
ti.init(arch=ti.cpu)

提示：Lock C:/taichi_cache/ticache/metadata.lock failed

**Comment by qiao-bo** [comment]
Hi, can you please provide the full error log? and perhaps the output of `ti.diagnose`? thanks

**Comment by lin-hitonami** [comment]
This is only a false warning, and does not affect the execution of the Taichi program. I've removed the warning in #5747.
