### ISSUE TITLE
id(dtype) of builtin vectors not in real_type_ids

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5767]
To reproduce:

```python
import taichi as ti

vec3 = ti.math.vec3
print(id(vec3.dtype))
print(ti.types.primitive_types.real_type_ids)
```

The result gives

```
140376791869680
[140376797782384, 140376797803760, 140376797803888, 9489216]
```
The id of the `f32` type of vec3 is not in `ti.types.real_type_ids`.

This mismatch has the effect that the built-in`vec2/vec3/vec4` cannot be used as type hints since [this line of code](https://github.com/taichi-dev/taichi/blob/master/python/taichi/lang/kernel_impl.py#L723) checks the id of the needed type.

Shall we change that line referenced above in `kernel_impl.py` to the following?

```python
if needed.dtype in primitive_types.real_types:
```

**Comment by strongoier** [comment]
Some notes for people interested in the cause of this issue - 

The type of `default_fp` is actually `DataType` in C++, and a `DataType` stores a pointer to its actual `Type`. The actual `Type` is unique, but the `DataType` wrapper can be different.
