### ISSUE TITLE
ti.Texture Usage Question

### ISSUE THREAD

**Issue by helloworldstone** [taichi-dev/taichi#5793]
hi，everyone！

1. taichi v1.1.0  has supported ti.Texture. Does ti.Texture support vulkan aot?
I have write a ti.kernel and save aot like this，it reports this error: “**AssertionError: Need 0 inputs to instantiate the template parameters, got 4**”.  Shouldn't we set template_args? 
My sample code:

```py
@ti.kernel
def rgba2gray(
    rgbaTexture: ti.types.texture(num_dimensions=2),
    grayTexture: ti.types.rw_texture(num_dimensions=2, num_channels=1, channel_format=**ti.u8**, lod=0), 
    width: ti.i32, 
    height: ti.i32):
    for i, j in ti.ndrange(height, width):
        c = rgbaTexture.fetch(ti.Vector([i, j]), 0)
        gray = c.r * 0.299 + c.g * 0.587 + c.b * 0.114
        grayTexture.store(ti.Vector([i, j]), ti.Vector([gray, 0.0, 0.0, 0.0]))

    mod = ti.aot.Module(ti.vulkan)
    mod.add_kernel(rgba2gray,
                   template_args={
                        'rgbaTexture': inTexture,
                        'grayTexture': outTexture,
                        'width': width,
                        'height': height
                   })
    mod.save(dir_name, '')
```

2. When I  remove template_args values，it can save vulkan aot spv files,  but the metadata.json shows that rgbaTexture and grayTexture type are **fp32**.  Does this mean  texture type  must be fp32 when it takes as ti.kernel  input parameter ？

metadata.json:

      "scalar_args": {"2": {
          "dtype_name": "i32",
          "offset_in_args_buf": 8},"3": {
          "dtype_name": "i32",
          "offset_in_args_buf": 12}},
      "arr_args": {"0": {
          "dtype_name": "f32",
          "field_dim": 0,
          "element_shape": [],
          "shape_offset_in_args_buf": 0,
          "bind_index": 0},"1": {
          "dtype_name": "f32",
          "field_dim": 0,
          "element_shape": [],
          "shape_offset_in_args_buf": 4,
          "bind_index": 0}}}},

Thanks a lot!

**Comment by bobcao3** [comment]
They are not correctly supported in AOT yet, sorry

**Comment by PENGUINLIONG** [comment]
Actually yes, please consult the `python\taichi\examples\graph\texture_graph.py` example for detail :)

**Comment by ailzhang** [comment]
Closing via https://github.com/taichi-dev/taichi/issues/5793#issuecomment-1217376802
