### ISSUE TITLE
Is C API the recommended method for AOT deployment?

### ISSUE THREAD

**Issue by zh0ngtian** [taichi-dev/taichi#5798]
There is a warning when building libtaichi_export_core.so:

```
CMake Warning at cmake / TaichiExportCore.cmake :5 (message):
You are trying to build the taichi_export_core target, support for this
target will be deprecated in the future, pLease considering using the taichi_c_api target.
```
So is C API the recommended method for AOT deployment?

**Comment by PENGUINLIONG** [comment]
Yes, although we didn't publicly release the C-API, it has been a part of many demo projects already. A provisional documentation can be found here at https://deploy-preview-5736--docsite-preview.netlify.app/docs/master/taichi_core .
