### ISSUE TITLE
Build taichi with opengl off and vulkan on failed on master

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#5800]
To repro: `TAICHI_CMAKE_ARGS="-DTI_WITH_VULKAN:BOOL=ON -DTI_WITH_OPENGL:BOOL=OFF -DTI_BUILD_TESTS:BOOL=OFF -DTI_EXPORT_CORE:BOOL=ON -DTI_WITH_C_API:BOOL=ON" python setup.py develop`

IMHO the root cause is probably that vulkan_prog_impl/opengl_prog_impl should depend on spirv_codegen.  https://github.com/taichi-dev/taichi/issues/4832#issuecomment-1195088614 
cc: @qiao-bo

**Comment by qiao-bo** [comment]
Thanks for the hint. Actually, this is another example that our CI fails to cover all our build combinations. Perhaps we can set a build matrix in nightly?
