### ISSUE TITLE
[differentiable] make_adjoint pass should support mutable local variables and complex branching

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#581]
(need to come up with a systematic solution.)

**Comment by archibate** [comment]
Btw, what does `differentiable` mean? I guess it's related to kernel.grad()? Was this a unique feature of taichi but no others like tvm? Sounds interesting! A recent issue says `if` is not allowed in grad kernels, and I told him/her to use max/min instead. May be resolved by this issue?

**Comment by yuanming-hu** [comment]
> Btw, what does `differentiable` mean? I guess it's related to kernel.grad()?

Exactly!

> Was this a unique feature of taichi but no others like tvm?

Yes, because Taichi has an imperative mega-kernel design. This is different from coarser-grained systems such as tensorflow/Halide/tvm.

> A recent issue #571 says `if` is not allowed in grad kernels, and I told him/her to use max/min instead. Expected to be resolved by this issue?

True.


I think now I know how and will try to implement it tomorrow.
