### ISSUE TITLE
taichi v1.1.0 manylinux is twice larger than v1.0.4 wheels

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#5822]
v1.1.0 manylinux wheels are 47-53MB while v1.0.4 manylinux wheels are ~27MB.
See screenshots below: 
![Screenshot from 2022-08-18 17-52-55](https://user-images.githubusercontent.com/5248122/185366990-cc405954-238c-4bfb-9f1a-0c737aeea54e.png)
![Screenshot from 2022-08-18 17-51-25](https://user-images.githubusercontent.com/5248122/185367144-15f08390-20a6-46b9-9ecc-af1e1622a572.png)
link: https://pypi.org/project/taichi/1.1.0/#files

I haven't looked into this issue but it might worth some investigation to check if this is expected.

**Comment by ailzhang** [comment]
possibly due to llvm15 support? need double check tho.

**Comment by jim19930609** [comment]
Guess what, we mistakenly compiled C-API dylib and put it in "taichi-1.1.0.data". That's where the other half comes from :

![2022-08-26 16-53-57 的屏幕截图](https://user-images.githubusercontent.com/22334008/186866746-a8f9d6ef-1b90-4a51-a793-3251b1120afc.png)

**Comment by jim19930609** [comment]
The release pipeline reuses `.github/workflows/scripts/unix_build.sh` to build the wheel, and someone added this:

![2022-08-26 17-05-21 的屏幕截图](https://user-images.githubusercontent.com/22334008/186869149-0b4afb2b-2706-4844-9149-a50bc74b821e.png)

**Comment by jim19930609** [comment]
that someone....turns out to be me. let me push a fix
