### ISSUE TITLE
Support negative indexing in ti.field

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5829]
**Concisely describe the proposed feature**

I hope we can support negative indexing in a taichi field:

```python
x = ti.field(int, shape=(10, 10))
x.fill(1)
x[-1, -1]  # prints 0, but 1 is expected
```

so that one can quickly refer to an element at the end of a row/column in a field, without explicitly telling the shape of the field.

**Comment by yuanming-hu** [comment]
I'm afraid this cannot be supported, as it conflicts with coordinate offsets: https://docs.taichi-lang.org/docs/offset

**Comment by neozhaoliang** [comment]
Close this feature request issue since it may have conflicts with existing features.
