### ISSUE TITLE
Move vec2, vec3, vec4, mat2, mat3, mat4 to top-level namespace?

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5830]
**Concisely describe the proposed feature**

I suggest we move the small vector and matrix types defined [here](https://github.com/taichi-dev/taichi/blob/master/python/taichi/math/mathimpl.py#L15-L61) to top-level namespace, so that the users can write `ti.vec2`, `ti.vec3`, `ti.mat2`, etc.

The reasons supporting this change are:

1. In most scenarios, the users only use vectors of dimension <= 4 and matrices of order <= 4, these types occur at a very high frequency in applications.
2. Users think the current API `ti.math.vec3`too long and not heady, they prefer to define their own types `vec3 = ti. types.vector(3, float)`. I see these everywhere in the community's demos. This repetitive labor should be avoided.
3. Once we have this API change accepted, our official examples can be simplified a lot, writings like `ti.Vector([0.0, 0.0, 0.0])` can be simplified to `ti.vec3(0)`, and code like
    ```python
    ti.Vector([a[0], a[1], b[0], b[1]]).cast(int)
    ```
     can be simplified to `ti.ivec4(a, b)`

**Comment by yuanming-hu** [comment]
> Users think the current API `ti.math.vec3` too long and not heady

I believe you can actually write `tm.vec3` if you add a single line `import taichi.math as tm`?

**Comment by neozhaoliang** [comment]
> > Users think the current API `ti.math.vec3` too long and not heady
> 
> I believe you can actually write `tm.vec3` if you add a single line `import taichi.math as tm`?

Haa, that's a good point. As far as I know, very few users use that API maybe because they just don't know of it. We should make it better documented.

**Comment by yuanming-hu** [comment]
> We should make it better documented.

Absolutely!
