### ISSUE TITLE
cross build taichi v1.1.2 android so error

### ISSUE THREAD

**Issue by helloworldstone** [taichi-dev/taichi#5834]
hi，everyone!

I use this command to build taichi libtaichi_export_core.so android so on Mac os:

**python setup.py clean && TAICHI_CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=29 -DANDROID_ABI=arm64-v8a" python3 setup.py build_ext**

https://github.com/taichi-dev/taichi-aot-demo/tree/master/implicit_fem

It is ok with taichi v1.0.3. But taichi v1.1.2 occured some errors: 

taichi/runtime/program_impls/vulkan/libvulkan_program_impl.a(vulkan_program.cpp.o): In function `taichi::lang::VulkanProgramImpl::compile(taichi::lang::Kernel*, taichi::lang::OffloadedStmt*)':
/Users/taichi-rc-v1.1.2/taichi/runtime/program_impls/vulkan/vulkan_program.cpp:82: undefined reference to `taichi::lang::spirv::lower(taichi::lang::Kernel*)'
taichi/runtime/program_impls/vulkan/libvulkan_program_impl.a(vulkan_program.cpp.o): In function `taichi::lang::VulkanProgramImpl::compile_snode_tree_types(taichi::lang::SNodeTree*)':
/Users/taichi-rc-v1.1.2/taichi/runtime/program_impls/vulkan/vulkan_program.cpp:168: undefined reference to `taichi::lang::spirv::compile_snode_structs(taichi::lang::SNode&)'
taichi/runtime/program_impls/vulkan/libvulkan_program_impl.a(vulkan_program.cpp.o): In function `taichi::lang::VulkanProgramImpl::make_aot_kernel(taichi::lang::Kernel&)':
/Users/taichi-rc-v1.1.2/taichi/runtime/program_impls/vulkan/vulkan_program.cpp:198: undefined reference to `taichi::lang::spirv::lower(taichi::lang::Kernel*)'
taichi/runtime/program_impls/vulkan/libvulkan_program_impl.a(vulkan_program.cpp.o): In function `taichi::lang::VulkanProgramImpl::compile(taichi::lang::Kernel*, taichi::lang::OffloadedStmt*)':
/Users/taichi-rc-v1.1.2/taichi/runtime/program_impls/vulkan/vulkan_program.cpp:82: undefined reference to `taichi::lang::spirv::lower(taichi::lang::Kernel*)'
taichi/runtime/program_impls/vulkan/libvulkan_program_impl.a(vulkan_program.cpp.o): In function `taichi::lang::VulkanProgramImpl::compile_snode_tree_types(taichi::lang::SNodeTree*)':
/Users/taichi-rc-v1.1.2/taichi/runtime/program_impls/vulkan/vulkan_program.cpp:168: undefined reference to `taichi::lang::spirv::compile_snode_structs(taichi::lang::SNode&)'
taichi/runtime/program_impls/vulkan/libvulkan_program_impl.a(vulkan_program.cpp.o): In function `taichi::lang::VulkanProgramImpl::make_aot_kernel(taichi::lang::Kernel&)':
/Users/taichi-rc-v1.1.2/taichi/runtime/program_impls/vulkan/vulkan_program.cpp:198: undefined reference to `taichi::lang::spirv::lower(taichi::lang::Kernel*)'
taichi/runtime/gfx/libgfx_runtime.a(runtime.cpp.o): In function `taichi::lang::gfx::run_codegen(taichi::lang::Kernel*, taichi::lang::Device*, std::__ndk1::vector<taichi::lang::spirv::CompiledSNodeStructs, std::__ndk1::allocator<taichi::lang::spirv::CompiledSNodeStructs> > const&)':
/Users/taichi-rc-v1.1.2/taichi/runtime/gfx/runtime.cpp:696: undefined reference to `taichi::lang::spirv::KernelCodegen::KernelCodegen(taichi::lang::spirv::KernelCodegen::Params const&)'
/Users/taichi-rc-v1.1.2/taichi/runtime/gfx/runtime.cpp:698: undefined reference to `taichi::lang::spirv::KernelCodegen::run(taichi::lang::spirv::TaichiKernelAttributes&, std::__ndk1::vector<std::__ndk1::vector<unsigned int, std::__ndk1::allocator<unsigned int> >, std::__ndk1::allocator<std::__ndk1::vector<unsigned int, std::__ndk1::allocator<unsigned int> > > >&)'
taichi/runtime/gfx/libgfx_runtime.a(runtime.cpp.o): In function `~OptimizerOptions':
/Users/taichi-rc-v1.1.2/external/SPIRV-Tools/include/spirv-tools/libspirv.hpp:159: undefined reference to `spvOptimizerOptionsDestroy'
taichi/runtime/gfx/libgfx_runtime.a(runtime.cpp.o): In function `std::__ndk1::default_delete<spvtools::SpirvTools>::operator()(spvtools::SpirvTools*) const':
...
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libtaichi_python.so] Error 1
make[1]: *** [CMakeFiles/taichi_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../../build/libtaichi_export_core.so] Error 1
make[1]: *** [CMakeFiles/taichi_export_core.dir/all] Error 2
make: *** [all] Error 2

**So what should I do?
Thanks a lot!**

**Comment by ailzhang** [comment]
@helloworldstone sorry for the trouble, we were moving a few files around cleanup the dependencies. I believe this was fixed in https://github.com/taichi-dev/taichi/pull/5812/files, would you minding giving nightly a try? Thanks! 
(btw this has been added to CI so taichi master should always work with implicit_fem demo in taichi-aot-demo master
