### ISSUE TITLE
Is it possible for Taichi to be compatible with both numpy and tensorflow 2.0+

### ISSUE THREAD

**Issue by acse-sm321** [taichi-dev/taichi#5884]
**Proposed feature**
* I am tackling  CFD problem using  Tensorflow >  2.0 and numpy(), most of the functions combines both numpy and tf operations,  is it possible to make taichi kernel accelerate this kind of functions?  Say use  @ti.kernel  and it should compile and run
* I see not much materials about how to use taichi to work with Tensorflow, but can we make it possible? technically? or possibly other frameworks like  torch, or other hpc/distributed  libraries? say NCCL, or Deepspeed  etc.

**Comment by acse-sm321** [comment]
say, use AI techs to solve computer physics are quiet popular these years,  and parallel should give better performance,  if we can use taichi among those processes that would make a wonderful feature.

**Comment by bobcao3** [comment]
Taichi works with torch tensors natively (`field.to_torch()` and `from_torch()`)

**Comment by acse-sm321** [comment]
@bobcao3   Nice to know that,  cheers. But I think if taichi kernel could accelerate the functions without data type conversions that would be better, isn't it?  data type  conversions like this cost much time when we are running it on multi-CPU or GPU, and accuracy issue  sometimes, which we try to avoid. btw do you have any experience with some  other parallel libs + taichi?  Basically I know MPI (mpi4py) + taichi  works.

**Comment by ailzhang** [comment]
@acse-sm321 By data type conversions did you mean memcpy? Taichi does support running with torch tensors directly without copying its memory. See https://docs.taichi-lang.org/docs/external for more instructions!

**Comment by acse-sm321** [comment]
@ailzhang Cheers. Can't wait to do something wonderful with Taichi.

**Comment by ailzhang** [comment]
Closing as resolved, @acse-sm321 please feel free to open a new issue if you have followup questions.
