### ISSUE TITLE
Taichi Legacy cmake returning errors

### ISSUE THREAD

**Issue by aagrawal05** [taichi-dev/taichi#5895]
**Describe the bug**
When installing taichi from the legacy branch, lots of errors when building on cmake

**To Reproduce**
cloning and running install.py --> https://github.com/taichi-dev/taichi/blob/legacy/install.py
or equivalently from following https://github.com/taichi-dev/taichi/blob/5ab90f03ef37701506c7034c3f1955d225b39957/docs/installation.rst

**Log/Screenshots**
https://pastebin.com/xqGQc4iB

**Additional comments**
Running on Ubuntu 22.04

**Comment by strongoier** [comment]
Hi @aagrawal05. Could you try compiling with clang? My environment is Ubuntu 20.04 & clang++-8 and I can successfully build the legacy branch.

**Comment by aagrawal05** [comment]
Ok, edited the CMakeLists.txt and built again with clang++11. Gives a different error.
https://pastebin.com/Z4Tp3t90

**Comment by bobcao3** [comment]
> Ok, edited the CMakeLists.txt and built again with clang++14. Gives a different error. https://pastebin.com/Z4Tp3t90 Should I try again with a lower version of clang?

Yes, maybe clang 10 or 8 if possible!

**Comment by aagrawal05** [comment]
Ok, so I've tried with clang++11 which seems to be the lowest that 22.04 can install. I'll try building from source but is there any other way to compile this?

**Comment by strongoier** [comment]
Hi @aagrawal05. If you haven't succeeded yet, could you try Ubuntu 20.04 (in docker if you don't have another environment)?

**Comment by aagrawal05** [comment]
Alright, I'll try that. 
Sorry for not replying, got busy with some school work.
I'll update you guys whether I managed to get it working hopefully this week.

**Comment by strongoier** [comment]
I assume the problem has been resolved so I'm closing this issue. Feel free to reopen if you meet further problems.

**Comment by Hal-Zhaodong-Yang** [comment]
Are you able to solve the issue? I'm still having the same issue even switching to clang10 on ubuntu20.04 by changing the "g++" to "clang" in the `install.py`.
