### ISSUE TITLE
Direct element traverse for ti.field

### ISSUE THREAD

**Issue by houkensjtu** [taichi-dev/taichi#5923]
Currently, the fundamental way to traverse a `ti.field` is through indexing:
```python
f = ti.field(dtype=float, shape=(n,))
@ti.kernel
def init():
    # Struct-for
    for i in f:
        f[i] = 0.0
    # Or alternatively use a range-for
    for i in range(n):
        f[i] = 0.0 
```
However, a Python user might expect a more **Pythonic** way to traverse, namely:
```python
@ti.kernel
def init():
    for x in f:
        x = 0.0
```
Moreover, it will be expected that this way of access also works in a `StructField`:
```python
sphere_type = ti.types.struct(center=vec3, radius=float)
sphere_field = sphere_type.field(shape=(n,))
@ti.kernel
def init():
    for s in sphere_field:
        s.center = vec3(0,0,0)
```
I think this will be a "nice to have" rather than a "must have" feature :) Please let me know what you think.

**Comment by strongoier** [comment]
I think the problem here is backward-compatibility - you cannot distinguish the new syntax from the old syntax.
