### ISSUE TITLE
CI job with build matrix of different cmake options

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#5924]
Currently our build system supports multiple configs like `TI_WITH_LLVM, TI_WITH_VULKAN` etc, but we only test a few combos of them in CI pipeline. It'd be nice if we can add a CI job that builds taichi with different build configurations and probably just do a light test like `ti diagnose`. It'll be beneficial for AOT release as well as keeping our build system sane during refactors. 

related: #4832

cc: @feisuzhu @jim19930609 

Of course it's almost impossible to exhaustively test all the combinations so listing a few configs that we care the most

- [ ] TI_WITH_LLVM
- [ ] TI_WITH_OPENGL
- [ ] TI_WITH_VULKAN
- [ ] TI_WITH_CUDA
- [ ] TI_BUILD_TESTS
- [ ] TI_WITH_C_API

**Comment by feisuzhu** [comment]
This may be prohibitively expensive at the moment so I'm planning to enable it after the refactor of build pipeline and adding new buildbots.
