### ISSUE TITLE
make `ti test` only test for specific archs

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#600]
**Concisely describe the proposed feature**
Specify from command line to save time for backend developers.

**Describe the solution you'd like (if any)**

Plan A:
In python/taichi/main.py: `import argparse`
In command line: `ti test --arch=[arch(s)] [test(s)]`
e.g.: `ti test --arch=opengl,metal offload numpy`

Plan B:
Use the existing TI_ARCH spec way:
`export TI_ARCH=opengl; ti test`
Currently this will run for opengl **twice** since TI_ARCH overrides arch specified in `ti.init`.

Inputs are welcome.

**Additional comments**
As mentioned in https://github.com/taichi-dev/taichi/pull/545/#issuecomment-599171908

**Comment by yuanming-hu** [comment]
Great idea. I feel like plan A is better. I suggest we take this chance to start **gradually** switching from the original `if-elif` sequence to `argparse`.

https://github.com/taichi-dev/taichi/blob/d19c3411cdbbae5ac5367bf57af6896b583d6c51/python/taichi/main.py#L147-L170


For this issue, let's modify the `ti test` command only.

https://github.com/taichi-dev/taichi/blob/d19c3411cdbbae5ac5367bf57af6896b583d6c51/python/taichi/main.py#L120-L132

Maybe we should also unify `test`, `test_verbose`, `test_cpp` using `argparse` options etc?

**Comment by archibate** [comment]
--verbose or -v for test_verbose of course.
Then we want ti test --cpp-only or --python-only?

**Comment by yuanming-hu** [comment]
> Then we want ti test --cpp-only or --python-only?

Sounds good to me. We can also use `-c` and `-p` for short.

**Comment by yuanming-hu** [comment]
Well done by @archibate. Closing.
