### ISSUE TITLE
ti.Vector from a numpy array

### ISSUE THREAD

**Issue by mushroomfire** [taichi-dev/taichi#6003]
It should raise an error, but not!
![image](https://user-images.githubusercontent.com/77276727/188808074-5a5ab411-8435-4dd9-9c24-2e0189c9ccd2.png)

**Comment by yuanming-hu** [comment]
... or we support initializing `ti.Vector` from a numpy array

**Comment by YouJiacheng** [comment]
![image](https://user-images.githubusercontent.com/83971976/189497097-8e284f00-5b0b-4aa4-b90a-1b223edc2efa.png)

**Comment by neozhaoliang** [comment]
@mushroomfire Both `ti.Vector` and `ti.Matrix` support initializing from a NumPy.ndarray, this is a feature, not a bug.

https://github.com/taichi-dev/taichi/blob/master/python/taichi/lang/matrix.py#L434
