### ISSUE TITLE
[True for i in range(N)] compilation error

### ISSUE THREAD

**Issue by pigen01** [taichi-dev/taichi#6026]
**Describe the bug**
when initialize an array with `[True for i in range(N)]`, it reports a compilation error.

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
import taichi as ti 

ti.init()

@ti.kernel
def count_primes(N: int) -> int:
    is_prime = [True for i in range(N)]
    is_prime[0] = False 
    is_prime[1] = False
    for i in range(2, N):
        if is_prime[i]:
            for j in range(2*i, N, i):
                is_prime[j] = False 
    return sum(is_prime)

if __name__ == "__main__":
    import time 
    start = time.time()
    print(count_primes(10000000))
    print("{:.2f} s".format(time.time()-start))
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
$ python my_sample_code.py
[Taichi] mode=release
[Taichi] version 0.6.29, llvm 10.0.0, commit b63f6663, linux, python 3.8.3
[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.9.12
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "D:\python_projects\taichi_test\cout_primes.py", line 19, in <module>
    print(count_primes(10000000))
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\taichi\lang\kernel_impl.py", line 920, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiCompilationError:
On line 7 of file "D:\python_projects\taichi_test\cout_primes.py", in count_primes:
    is_prime = [True for i in range(N)]
                              ^^^^^^^^
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\taichi\lang\ast\ast_transformer_utils.py", line 24, in __call__
    return method(ctx, node)
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\taichi\lang\ast\ast_transformer.py", line 497, in build_Call
    node.ptr = func(*args, **keywords)
TypeError: 'Expr' object cannot be interpreted as an integer
```

**Comment by victoriacity** [comment]
Hi,

List comprehension only works in python-scope and does not work in Taichi scope. Here the code is trying to compile a list comprehension where `N` is a taichi-scope variable passed to the kernel, and therefore the compiler will throw an error. The list comprehension will compile if put outside the Taichi kernel, or with a python-scope variable in the list comprehension, such as
```python
N = 8
@ti.kernel
def ...():
    x = [True for i in range(N)]
```
But please not that any python-scope variable will be treated as constants when Taichi kernels are compiled such that modifying the value of the python-scope variable will not affect the result of the Taichi kernel.
