### ISSUE TITLE
Can not Taichi interact with other domain-specific python packages?

### ISSUE THREAD

**Issue by 17150934** [taichi-dev/taichi#6034]
Hi.
I would like to accelerate my codes by using Taichi.
But I meet a error when I add Taici to my codes. It seems that there is a conflict between the Taichi and my other domain-specific python packages. Like this:
`Traceback (most recent call last):

  File ~/plexe-pyapi/examples/brakedemo.py:162 in <module>
    main()

  File ~/anaconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py:920 in wrapped
    raise type(e)('\n' + str(e)) from None

TaichiTypeError: 
On line 103 of file "/home/vcdc/plexe-pyapi/examples/brakedemo.py", in main:
    plexe = Plexe()
    ^^^^^^^^^^^^^^^
Invalid constant scalar data type: <class 'plexe.plexe.Plexe'>`

The Plexe() comes from a python package :
`from plexe import Plexe`

So, I want to make sure that Can not Taichi interact with other domain-specific python packages?

**Comment by bobcao3** [comment]
If you are trying to use this within a the Taichi scope (ti.func and ti.kernel) then no it will not work. You can use them normally outside the taichi scope
