### ISSUE TITLE
Failed to init taichi

### ISSUE THREAD

**Issue by FantasyVR** [taichi-dev/taichi#6049]
**Describe the bug**
Failed to init taichi with `ti.init()`

**To Reproduce**
```py
import taichi as ti
ti.init()
```

**Log/Screenshots**
```
[Taichi] version 1.1.3, llvm 10.0.0, commit e3eb6be7, linux, python 3.8.13
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    ti.init()
  File "/home/py/code/taichi/python/taichi/lang/misc.py", line 455, in init
    impl.get_runtime().create_program()
  File "/home/py/code/taichi/python/taichi/lang/impl.py", line 318, in create_program
    self.prog = _ti_core.Program()
MemoryError: std::bad_alloc
```

**Additional comments**
After bisecting commits, I find that the first commit reports this bug is: e3eb6be73ee729ea05a207f97a71a8195f5d8771.
The bug is related to this line of code: https://github.com/taichi-dev/taichi/blob/eee2e895d7dc65262238a24f1625aa37d2757e7a/taichi/program/program.cpp#L81

**Comment by lin-hitonami** [comment]
Please delete the offline cache directory and try again. It should be located in `$HOME/.cache/taichi`.
