### ISSUE TITLE
how to render and visualize rocket landing scene

### ISSUE THREAD

**Issue by PaParaZz1** [taichi-dev/taichi#6058]
I have searched in github issues and awesome examples.

Our team wants to build a demo about rocket landing like what SpaceX did to visualize the behaviour of Reinforcement Learning Agent (like this [video](https://www.youtube.com/watch?v=49eIoaY8pVM)), but I don't know what kind of tools I can use to do a similar demo. Would you give some advices about this topic?

**Comment by moneyxueshe** [comment]
i remember that someone did that at 2d at bilibili ，but i can get it again,however you can do it using tensorflow or pytorch at kerbal space program

**Comment by PaParaZz1** [comment]
I have already trained a agent in PyTorch, and I want to do a demo to visualize the behaviour of this agent.

**Comment by erizmr** [comment]
Hi @PaParaZz1 , could you please provide more details about the data format of the agent? Is it a mesh/voxel/particle etc?

**Comment by neozhaoliang** [comment]
Taichi doesn't support rendering a "complex" rocket scene yet, what about mimicking a simple 2d scene, like gym:
https://github.com/openai/gym/blob/master/gym/envs/box2d/lunar_lander.py
