### ISSUE TITLE
Atomic min/max/bit_and/bit_or/bi_xor

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#606]
**Concisely describe the proposed feature**
Atomic min and max still needs to be implemented. 

**Describe the solution you'd like (if any)**
Looks like the most of the implementation will follow atomic add. Except that there is no nvvm intrinsics for atomic max. So can we use the same runtime functions as x64? Also I'm note sure about the demote atomic transform. Anything else to think about?

**Comment by yuanming-hu** [comment]
Yeah, this will be a very useful feature. 

> Looks like the most of the implementation will follow atomic add. Except that there is no nvvm intrinsics for atomic max. So can we use the same runtime functions as x64?

Yeah, according to NVVM doc there doesn't seem to be an `atomicMin`. For integer types, LLVM IR actually has an atomic min (note `%11`) which can be compiled into NVPTX:
```
; Function Attrs: convergent noinline nounwind optnone
define internal i32 @_ZL9atomicMinPii(i32*, i32) #0 {
  %3 = alloca i32*, align 8
  %4 = alloca i32, align 4
  %5 = alloca i32*, align 8
  %6 = alloca i32, align 4
  store i32* %0, i32** %5, align 8
  store i32 %1, i32* %6, align 4
  %7 = load i32*, i32** %5, align 8
  %8 = load i32, i32* %6, align 4
  store i32* %7, i32** %3, align 8
  store i32 %8, i32* %4, align 4
  %9 = load i32*, i32** %3, align 8
  %10 = load i32, i32* %4, align 4
  %11 = atomicrmw min i32* %9, i32 %10 seq_cst
  ret i32 %11
}
```

for `f32` and `f64`, we probably need to simulate it using `atomicCAS` just like `x64`.



> Also I'm not sure about the demote atomic transform.

`demote_atomic` is just used in cases where atomic operations can be safely replaced by an non-atomic `read-modify-write`. Currently we only use it in single-threaded CPU, but in the future we might have a smarter transform that does a better job, e.g.
```python3
for i in range(x):
  ti.atomic_min(x[i], 1) # No data-race even if parallellized
```

**Comment by archibate** [comment]
Also will atomic_bit_and/or helpful sometimes? GLSL has atomicAnd/Or for integers.

**Comment by archibate** [comment]
> Yeah, according to NVVM doc there doesn't seem to be an `atomicMin` intrinsics. For integer types, LLVM IR actually has an atomic min (note `%11`) which can be compiled into NVPTX:

Maybe LLVM knows how to convert it into lock-rw-unlock codes?

**Comment by yuanming-hu** [comment]
> Also will atomic_bit_and/or helpful sometimes? GLSL has atomicAnd/Or, also has atomicMax/Min for integers.



> > Yeah, according to NVVM doc there doesn't seem to be an `atomicMin` intrinsics. For integer types, LLVM IR actually has an atomic min (note `%11`) which can be compiled into NVPTX:
> 
> Maybe LLVM knows how to convert it into lock-rw-unlock codes?

Yes and yes :-)

**Comment by KLozes** [comment]
Cool, I'll go ahead and implement and atomic min/max and bit_and/or for the x64 and cuda backends. I may have a lot of time on my hands if my workplace closes :-0 .

**Comment by yuanming-hu** [comment]
Thanks to the great contribution by @KLozes, related features are implemented now.
