### ISSUE TITLE
Can the GUI of Taichi be updated to support drawing partial differential functions, writing markdown, or LaTeX?

### ISSUE THREAD

**Issue by moneyxueshe** [taichi-dev/taichi#6061]
**Concisely describe the proposed feature**
A clear and concise description of what you want. For example,
> I would like to add an Apple Metal backend to the compiler so that my Macbook GPU can be utilized.
i would like to have a gui of taichi that can draw funtion like matplotlib and write markdown or latex,if could do that, i think its a good substantiance of matlplotlib as the matplotlib's perfermance is so annoying when drawing  partial differential function like playing ppt and i would like to have a higher gui fps and  its better to run a 3d model freely. 
**Describe the solution you'd like (if any)**
A clear and concise description of what you want to achieve and implement.

**Additional comments**

**Comment by victoriacity** [comment]
Hi,

Taichi GUI is able to render plain or slightly styled text. Rendering equations or paragraphed text such as markdown or LaTex requires much more complex support from the GUI.

**Comment by neozhaoliang** [comment]
@moneyxueshe You can try to use another lib `manimgl` as the GUI to render equations and code, and use Taichi to generate the simulation.
