### ISSUE TITLE
when the gui can run at the inside of taichi.kernel

### ISSUE THREAD

**Issue by moneyxueshe** [taichi-dev/taichi#6087]
**Concisely describe the proposed feature**
A clear and concise description of what you want. For example,
> I would like to add an Apple Metal backend to the compiler so that my Macbook GPU can be utilized.
i want have a gui that can run at kernel,because its can't now i have to change my program ,but it have many problem to write as the taichi scope and python scope have many differnet to hinder the connection between them. 
**Describe the solution you'd like (if any)**
A clear and concise description of what you want to achieve and implement.
the gui should run normallly as like the program below
@ti.kernel
    def gui():
        gui = ti.GUI("gui", res=(res_x, res_y))
        while gui.running:
                 gui.set_image(pixels)
                 gui.show()

**Additional comments**

**Comment by bobcao3** [comment]
This would be basically impossible to do with the current setup...

**Comment by bobcao3** [comment]
You can not control the host side from the device side

**Comment by neozhaoliang** [comment]
Try about organize the kernel and GUI into a `ti.data_oritened` class.
