### ISSUE TITLE
Potential UB in union_cast?

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#609]
We access an inactive union member at https://github.com/taichi-dev/taichi/blob/1bd17f6f1507a07b1a8896511642f72eac19843b/taichi/inc/constants.h#L14

https://en.cppreference.com/w/cpp/language/union says 
> It's undefined behavior to read from the member of the union that wasn't most recently written. Many compilers implement, as a non-standard language extension, the ability to read inactive members of a union.

There are more discussions in https://stackoverflow.com/questions/11373203/accessing-inactive-union-member-and-undefined-behavior, but I don't know if our usage is among the defined ones.

**Comment by archibate** [comment]
Maybe we can use reinterpret_cast? What if sizeof(T) > sizeof(G)? How about to zero-initialize it first?

**Comment by yuanming-hu** [comment]
Yeah, I know this is UB according to the standard and clang seems to do a reasonable job.

> Maybe we can use reinterpret_cast? What if sizeof(T) > sizeof(G)? How about to zero-initialize it first?

Unfortunately, no, that will lead to a violation of the strict aliasing (https://stackoverflow.com/questions/98650/what-is-the-strict-aliasing-rule), which practically is a  more severe UB...
