### ISSUE TITLE
Add support for initial window position

### ISSUE THREAD

**Issue by brent-williams** [taichi-dev/taichi#6107]
Add support for initial window position in GUI and/or GGUI.  

Window position could be in the constructor alongside resolution.  The underlying imgui.ini could as well/instead
be used, currently on macOS Monterey the file is written but always with window name "Debug##Default" and 
the Pos key is sadly ignored if already present.

**Comment by ailzhang** [comment]
Closing via #6156, @brent-williams please feel free to give it a try and let us know if you have any followup questions!

**Comment by brent-williams** [comment]
Cheers @ailzhang, will check it out once 1.1.4 is released.  Wow nice turnaround speed!
