### ISSUE TITLE
Wrong result when doing mod on two uint32 values

### ISSUE THREAD

**Issue by Linyou** [taichi-dev/taichi#6118]
**Describe the bug**
Hi, I try to use two uint32 values to do a mod but found the result is incorrect.

**To Reproduce**
```py
pos = np.array([660, 241, 838])
pos_field = ti.field(ti.uint32, shape=(3))
pos_field.from_numpy(pos)

primes_field = ti.field(ti.uint32, shape=(3))
primes = np.uint32(np.array([1, 2654435761, 805459861]))
primes_field.from_numpy(primes)

map_size_field = ti.field(ti.uint32, shape=(1,))
size = np.uint32(np.array([524288]))
map_size_field.from_numpy(size)

@ti.kernel
def test_kernel():
    # map_size = ti.uint32(524288)
    for ind in range(1):
        result = ti.uint32(0)
        for i in ti.static(range(3)):
            result ^= (pos_field[i] * primes_field[i])
        
        result = result % map_size_field[0]
        print(result)
```

When  I use the **map_size**  instead of **map_size_field**, the result is correct, and the correct result should be 212107, but the code above gives 4294655115, which is almost an overflow for uint32.

Any idea what kind of bug this is, or I'm making some mistakes here?

**Comment by Linyou** [comment]
Also, if I use ti.math.mod() method, the result is 212224

**Comment by Linyou** [comment]
sdf

**Comment by Linyou** [comment]
I have tried #6128 and recompile taichi, the result is still the same. If I use `result % ti.uint32(524288)` directly, the result is right, but when I use the `result % map_size_field[0]` which is a field variable, it still gives `4294655115`.  Here is another test code that includes an `if` statement, which also produces the wrong result.

```py
@ti.kernel
def test_kernel():
    map_size = ti.uint32(0)
    for ind in range(1):
        result = ti.uint32(3583196299)
        if ind == 0:
            map_size = ti.uint32(524288)

        print(f"result: {result % map_size}")
```
`result: 4294655115`

This one is also wrong
```py
map_size_field = ti.field(ti.uint32, shape=(1,))
size = np.uint32(np.array([524288]))
map_size_field.from_numpy(size)
@ti.kernel
def test_kernel():
    result = ti.uint32(3583196299)

    print(f"result: {result % map_size_field[0]}")
```
`result: 4294655115`

This one is right

```py
@ti.kernel
def test_kernel():
    result = ti.uint32(3583196299)
    map_size = ti.uint32(524288)

    print(f"result: {result % map_size}")
```
`result: 212107`

**Comment by strongoier** [comment]
This is weird. On my end all these scripts give the correct result. Could you try `ti.init(ti.cuda, offline_cache=False)` to avoid using the previous compiled kernels?

**Comment by Linyou** [comment]
Yes! With `offline_cache=False`, the result is correct. Thanks! Great work.
