### ISSUE TITLE
Eliminate namespace macros

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#6147]
**Concisely describe the proposed feature**
Currently we have macros `TLANG_NAMESPACE_BEGIN/END` which are equivalent to `namespace taichi::lang {}`. The macros may confuse the first-time readers so let's change it to `namespace taichi::lang {}`.

**Comment by strongoier** [comment]
Is this part of #2198?

**Comment by lin-hitonami** [comment]
Yeah. I'll replace the macros some time later.
