### ISSUE TITLE
[gui] Add gif compression option 

### ISSUE THREAD

**Issue by houkensjtu** [taichi-dev/taichi#6183]
Currently, if a user export the results of a simulation as a gif animation according to the [method](https://docs.taichi-lang.org/docs/master/export_results#convert-video-to-gif) described in the documentation, most likely the size of the file will be tens of MB, which is certainly too heavy to upload to any web page. Since it's quite common for a user to use the resulting animation on a website, can we provide a simple compression option in the `ti gif` command to help the user to reduce the size of the gif file?

**Comment by neozhaoliang** [comment]
I would suggest making the command `ti gif` and `ti video` into one command

```
ti video script gui_name [options]
```

For example, if I want to make a video of the animation in `mpm88.py` rendered by the GUI  `mpm_gui`, I can run

```
ti video mpm88.py mpm_gui -framerate 30 -quality 15 ... result.gif 
```
This should be easy to implement, but may depend on some third-party modules like imageio and moviepy.

**Comment by ailzhang** [comment]
Closing via #6289
