### ISSUE TITLE
Format server authentication

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#620]
**Concisely describe the proposed feature**

![image](https://user-images.githubusercontent.com/6553256/77030412-d6421800-6974-11ea-8567-c1ff609a20df.png)

Currently the format server https://github.com/taichi-dev/taichi/blob/d192c6cb0a1e3ecdfb1609b90fbc28092b8f5e71/misc/format_server.py#L1 is limited by 60 github API queries per hour. We need to follow https://developer.github.com/v3/#rate-limiting to authenticate our API access to boost 60 to 5000.

(When we hit the 60 queries limit user sees no PR...)

**Additional comments**
You can start the server locally by `python3 misc/format_server.py`. Thanks!

**Comment by archibate** [comment]
Also helps to fliter out those PRs which is permitted by current login user #621.

**Comment by archibate** [comment]
Replaced by #621.
