### ISSUE TITLE
OpenCV Speedup potential?

### ISSUE THREAD

**Issue by kevinlinxc** [taichi-dev/taichi#6222]
Is there any speculation on whether Taichi can help with OpenCV functions, or maybe even just numpy array iterations?

**Comment by FantasyVR** [comment]
Hi @kevinlinxc, could you give us a more specific use case?

**Comment by Olinaaaloompa** [comment]
This blog may answer your question by explaining how Taichi works with OpenCV for image processing: 
https://docs.taichi-lang.org/blog/how-taichi-fuels-gpu-accelerated-image-processing-a-beginner-to-expert-guide

**Comment by kevinlinxc** [comment]
@Olinaaaloompa thank you for this article. I'm disappointed that the authors left out benchmarking the taichi boosted functions vs traditional functions. I will explore this in my own time. Thank you.
