### ISSUE TITLE
Compile taichi with command error

### ISSUE THREAD

**Issue by Jingzheng-Li** [taichi-dev/taichi#6254]
Dear Taichier, 

I follow the site 
https://docs.taichi-lang.org/docs/dev_install
to build taichi with develop type. However, I have encounter some "undefined reference" problem near the end of the cmake compilation.

Errors are as below:

-- Build files have been written to: /home/jingzheng/Coding/Taichi/taichi/_skbuild/linux-x86_64-3.8/cmake-build
[603/606] Linking CXX executable /home/jingzheng/Coding/Taichi/taichi/build/taichi_cpp_examples
FAILED: /home/jingzheng/Coding/Taichi/taichi/build/taichi_cpp_examples 
: && /usr/bin/clang++ -DTI_ISE_NONE -std=c++17 -fsized-deallocation -Wno-deprecated-declarations -Wall  -Werror  -Wno-ignored-attributes  -Wno-nullability-completeness  -Wno-unused-private-field  -Wno-unneeded-internal-declaration  -DTI_ARCH_x64 -march=nehalem -DTI_PASS_EXCEPTION_TO_PYTHON -DTI_INCLUDED -DTI_WITH_LLVM -DTI_WITH_CUDA -DTI_WITH_CC -DTI_WITH_METAL -DTI_WITH_OPENGL -O3 -DNDEBUG -rdynamic  -Wl,--exclude-libs=libLLVMCore.a -Wl,--exclude-libs=libLLVMExecutionEngine.a -Wl,--exclude-libs=libLLVMInstCombine.a -Wl,--exclude-libs=libLLVMOrcJIT.a -Wl,--exclude-libs=libLLVMRuntimeDyld.a -Wl,--exclude-libs=libLLVMTransformUtils.a -Wl,--exclude-libs=libLLVMBitReader.a -Wl,--exclude-libs=libLLVMBitWriter.a -Wl,--exclude-libs=libLLVMObject.a -Wl,--exclude-libs=libLLVMScalarOpts.a -Wl, ......
```
/usr/bin/ld: taichi/runtime/program_impls/opengl/libopengl_program_impl.a(opengl_program.cpp.o): in function `taichi::lang::OpenglProgramImpl::compile(taichi::lang::Kernel*, taichi::lang::OffloadedStmt*)':
opengl_program.cpp:(.text+0x5e): undefined reference to `taichi::lang::gfx::CacheManager::load_or_compile(taichi::lang::CompileConfig*, taichi::lang::Kernel*)'
/usr/bin/ld: taichi/runtime/program_impls/opengl/libopengl_program_impl.a(opengl_program.cpp.o): in function `taichi::lang::OpenglProgramImpl::get_cache_manager()':
opengl_program.cpp:(.text+0x5a5): undefined reference to `taichi::lang::gfx::CacheManager::CacheManager(taichi::lang::gfx::CacheManager::Params&&)'
/usr/bin/ld: taichi/runtime/program_impls/opengl/libopengl_program_impl.a(opengl_program.cpp.o): in function `taichi::lang::OpenglProgramImpl::make_aot_kernel(taichi::lang::Kernel&)':
opengl_program.cpp:(.text+0xdab): undefined reference to `taichi::lang::gfx::CacheManager::load_or_compile(taichi::lang::CompileConfig*, taichi::lang::Kernel*)'
/usr/bin/ld: taichi/runtime/program_impls/opengl/libopengl_program_impl.a(opengl_program.cpp.o): in function `taichi::lang::OpenglProgramImpl::dump_cache_data_to_disk()':
opengl_program.cpp:(.text+0xf5b): undefined reference to `taichi::lang::gfx::CacheManager::clean_offline_cache(taichi::lang::offline_cache::CleanCachePolicy, int, double) const'
/usr/bin/ld: opengl_program.cpp:(.text+0xf6e): undefined reference to `taichi::lang::gfx::CacheManager::dump_with_merging() const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
[604/606] Building CXX object CMakeFiles/taichi_python.dir/taichi/python/export_lang.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/jingzheng/.local/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/home/jingzheng/.local/lib/python3.8/site-packages/skbuild/cmaker.py", line 680, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/home/jingzheng/.local/lib/python3.8/site-packages/skbuild/cmaker.py", line 704, in make_impl
    raise SKBuildError(

An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release -- -j16
  Install target:
    install
  Source directory:
    /home/jingzheng/Coding/Taichi/taichi
  Working directory:
    /home/jingzheng/Coding/Taichi/taichi/_skbuild/linux-x86_64-3.8/cmake-build
Please check the install target is valid and see CMake's output for more information.

Am I doing something wrong or missing something? Many thanks in advance

**Comment by neozhaoliang** [comment]
Do you have the llvm binary installed, and configurared the environment variable correctly?

**Comment by Jingzheng-Li** [comment]
Thank you very much for your quick reply. My system environment is Ubuntu20.04,
About llvm, I just follow the first two steps and add llvm to PATH such that
```
$ echo $PATH
/home/jingzheng/.local/bin:**/home/jingzheng/Coding/taichi-llvm/bin**:/home/jingzheng/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin ...
```
Is it necessary to build llvm from source?

About environment variable, I only set CXX to be Clang such that: export CXX=/path/to/clang++, and leave everything to be default.

Here is my full compilation log. Thanks a lot again!
https://docs.qq.com/doc/DRkV3ZFJJTVpaQUNY

**Comment by neozhaoliang** [comment]
I guess the path should be like `/home/jingzheng/Coding/taichi-llvm/bin:`?

**Comment by Jingzheng-Li** [comment]
> I guess the path should be like `/home/jingzheng/Coding/taichi-llvm/bin:`?

Sorry, that's my bad, I just want to make the font bold, and it doesn't seem to be in the format I want (hahaha...). I have changed my last comment, where the PATH is exactly like what you said.

**Comment by neozhaoliang** [comment]
Let's check your build step by step:

1. Clone the Taihi repo *recursively* using `git clone --recursive https://github.com/taichi-dev/taichi`.
2. Install `clang++ <= 11`, download the llvm binary to your local disk, and set the environment variable (looks ok in your above reply)
3. `cd taichi` and run `python3 -r requirements_dev.txt`.
4. run `python3 setup.py develop`.

**Comment by PGZXB** [comment]
Hi, @Jingzheng-Li

Building taichi with `-DTI_WITH_VULKAN:BOOL=ON` can solve your problem temporarily if you have installed the Vulkan SDK. 
But in fact, this is a bug... I'm **fixing** it. Thanks for your reporting!
**You can build the latest source code after the #6257 is merged.**

**Comment by Jingzheng-Li** [comment]
Many thanks for your remind, this fixed my problem and I can compile taichi right now!
