### ISSUE TITLE
Kernel fails to write to ti.types.ndarray if it is a numpy ndarray view

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#6305]
**Describe the bug**
```py
import taichi as ti
import numpy as np

ti.init(arch=ti.gpu)

@ti.kernel
def fill(img: ti.types.ndarray()):
    img[0] = 1

a = np.zeros(shape=(2, 2))[:, 0] # Creates an ndarray view here, I guess

fill(a)
print(a) # [0. 0.]

b = a.copy()
fill(b)
print(b) # [1. 0.]
```

**Output**

```
[Taichi] version 1.1.3, llvm 10.0.0, commit 0a7ff865, linux, python 3.8.10
[Taichi] Starting on arch=cuda
[0. 0.]
[1. 0.]
```

Perhaps we should loudly emit an run-time error message when passing in an **ndarray view** and simultaneously writing to it?

**Comment by ailzhang** [comment]
@yuanming-hu there're indeed two issues in our numpy array interaction that #6376 tries to fix, shall we continue discussion for this issue on that PR review directly? ;)
