### ISSUE TITLE
LLVM kernel AOT got skipped for the second time

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#6309]
To repro:
Run the following command twice: 
```
 TAICHI_AOT_FOLDER_PATH=/tmp/aot python tests/cpp/aot/python_scripts/taichi_sparse_test.py
```
You'll notice that after the first run everything is normal (/tmp/aot/metadata.json has all kernel info in it) but after the second run kernel infos disappeared in `metadata.json`, also the `.ll` files for kernels are not generated. 

first time: 
![Screenshot from 2022-10-13 10-53-02](https://user-images.githubusercontent.com/5248122/195488006-8be437f6-85fd-4cc0-b1a9-d6bdeb54c797.png)

second: 
![Screenshot from 2022-10-13 10-52-14](https://user-images.githubusercontent.com/5248122/195487901-bd4e3d81-10d8-4e89-b1a9-84d892ca649f.png)

cc: @jim19930609 @PGZXB

**Comment by PGZXB** [comment]
Thanks @ailzhang 

A feature of offline cache causes the bug of AOT 😂. I'm fixing it.
