### ISSUE TITLE
Refactor ASTTransformer.visit_For

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#631]
Its logic is currently too complex and correctness no longer trivial. This might lead to potential bugs such as #630 that are hard to find. Better break it down into multiple smaller pieces.

https://github.com/taichi-dev/taichi/blob/532ea3340e8c8201c97c768110be907038df7a17/python/taichi/lang/transformer.py#L277

@xumingkuan This will be your first task next week :-)

**Comment by yuanming-hu** [comment]
Valid combinations:
```
for i, j in x
for I in ti.groued(x)
for i in range(n)
for i, j in ti.ndrange(n)
for I in ti.grouped(ti.ndrange(n, m))
for i in ti.static(range(n))
for i, j in ti.static(ti.ndrange(n))
for I in ti.static(ti.gropued(ti.ndrange(n, m)))
```

**Comment by xumingkuan** [comment]
Is `for I in ti.static(ti.grouped(x))` or `for I in ti.grouped(ti.static(x))` allowed?

**Comment by yuanming-hu** [comment]
No. Thanks for asking.

**Comment by yuanming-hu** [comment]
Thanks to the great contribution by @xumingkuan, this issue is resolved.
