### ISSUE TITLE
does Dynamic Snode support vulkan backend?

### ISSUE THREAD

**Issue by xzy210** [taichi-dev/taichi#6328]
I run official code for dynamic snode, it runs well on cpu backend but reports Runtime error  on vulkan backend 
"RuntimeError: [D:/a/taichi/taichi/taichi/codegen/spirv/spirv_codegen.cpp:visit@384] Not supported."

**Comment by bobcao3** [comment]
At this moment it doesnt. You can use the CUDA backend

**Comment by xzy210** [comment]
> At this moment it doesnt. You can use the CUDA backend

thank you for your answer
