### ISSUE TITLE
ti.sqrt has lower precision on CUDA than on CPU

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#6346]
**Concisely describe the proposed feature**
```py
import taichi as ti

ti.init(arch=ti.gpu, default_fp=ti.f64)

@ti.kernel
def cal():
    x = 0.8
    print(ti.sqrt(x * x), ti.sin(x), ti.cos(x), ti.exp(x), ti.log(x))

cal()

#######################

ti.init(arch=ti.cpu, default_fp=ti.f64)

cal()
```

Output:

```
[Taichi] version 1.1.3, llvm 10.0.0, commit 0a7ff865, linux, python 3.8.10
[Taichi] Starting on arch=cuda
0.800000190735 0.717356090900 0.696706709347 2.225540928492 -0.223143551314
[Taichi] Starting on arch=x64
0.800000000000 0.717356090900 0.696706709347 2.225540928492 -0.223143551314
```

**Additional comments**
It seems that only `ti.sqrt` has a different result. Maybe `ti.sqrt` only has `f32` precision on `f64` inputs?

Source: https://forum.taichi-lang.cn/t/topic/3302

**Comment by strongoier** [comment]
This is a known issue (#2572). Shall we turn off `fast_math` by default?

**Comment by neozhaoliang** [comment]
As this is a potentially serious cause of precision problems, shall we make it a section in the article "debugging", or put it into FAQ?
