### ISSUE TITLE
Remove power-of-two padding in struct compilers

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#635]
**Concisely describe the proposed feature**
Currently, nodes dimensionalities being non-POT will be promoted to the closest bounding POT. For example

```python3
ti.dense(ti.ijk, 65).place(a)
```

leads to a data structure of size `128x128x128`. This is a huge waste of space for dense data structures.

**Describe the solution you'd like (if any)**
We used to use the bounding POT to allocate tensor memory in the LLVM backends. Now we can switch to real tensor size. The bounding POT value will still be used for core functionalities such as `refine_coordinates`.

**Comment by k-ye** [comment]
Hmm, if I continue to use the example in https://github.com/taichi-dev/taichi/issues/593#issuecomment-599503782

> Say we have the following hierarchy:
> 
> ```
> root.dense(ti.i, 3).dense(ti.i, 5)
> ```

> Now we can switch to real tensor size.

Which means we allocate precisely `3x5=15` memory? Then for index `7`, its refined coordinate will be `(S1@0, S2@7)`. And when we access `S2` from `S1`, there would be an overflow? Or does LLVM backends no longer access the leaf node from root in this hierarchical way?

**Comment by yuanming-hu** [comment]
> Hmm, if I continue to use the example in [#593 (comment)](https://github.com/taichi-dev/taichi/issues/593#issuecomment-599503782)
> 
> > Say we have the following hierarchy:
> > ```
> > root.dense(ti.i, 3).dense(ti.i, 5)
> > ```
> 
> > Now we can switch to real tensor size.
> 
> Which means we allocate precisely `3x5=15` memory? Then for index `7`, its refined coordinate will be `(S1@0, S2@7)`. And when we access `S2` from `S1`, there would be an overflow? Or does LLVM backends no longer access the leaf node from root in this hierarchical way?

You are right. Maybe I should make it clearer: we should only do this for *top-level* SNode for an index. For example `root.dense(ti.i, 3).dense(ti.i, 8)` should be allocated precisely.

Assuming i32 division/mod is unacceptable in address computation, maybe we should directly **forbid** the use of `dense(ti.i, 5)` in `root.dense(ti.i, 3).dense(ti.i, 5)`, since *batched by 5 elements* in memory cannot be implement without `i / 5` and `i % 5`, even if we pad...

**Comment by k-ye** [comment]
Ah, now I get it..

I'd still suggest us to still support Non-POT sizes just via padding? Feels like less restriction to the users. .. (But I guess users should be mindful that nested snodes are mostly for optimization purposes, so that they should avoid creating sizes that are both large and NPOT?)
