### ISSUE TITLE
`ti.ndrange` does not check for number of parameters

### ISSUE THREAD

**Issue by houkensjtu** [taichi-dev/taichi#6351]
**Describe the bug**
`ti.ndrange` does not report an error or warning even when the number of parameters does not match.

**To Reproduce**

```py
import taichi as ti

ti.init(arch=ti.cpu)

@ti.kernel
def iter():
    for i in ti.ndrange(1, nx):  # Taichi scope
        print(i)

iter()  # 0,1,2,3,4,5,6,7

for i in ti.ndrange(1, nx):  # Python scope
    print(i)  # (0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7)
```

As shown in the code example above, a user who is unfamiliar with `ti.ndrange`'s syntax might expect the printing result of `iter()` to be `1, 2, 3, 4, 5, 6, 7`; however, since `ti.ndrange` requires a parentheses for each index and the users forgot to include one, the results might be unexpected. It's probably better to give a warning or error message when the number of index does not match the parameters in `ti.ndrange`.

It's also confusing that the same syntax yields different results for Taichi scope and Python scope. If this kind of mismatch is allowed (with a warning but not an error), then the current behavior in Python scope seems to be more reasonable than the results in Taichi scope.

**Comment by lin-hitonami** [comment]
In fact the use of the ndrange-for in Python scope is a use of grouped ndrange-for... I've come up with an idea that we treat the use of ndrange-for with only one loop variable but has many dimensions automatically as a grouped ndrange-for (maybe we can do the same thing on the struct for too). In this way the syntax of Python and Taichi can be united, and the `ti.grouped` decorator can be deprecated. WDYT @yuanming-hu @ailzhang @strongoier

**Comment by yuanming-hu** [comment]
For ndrange deprecating `ti.grouped` may be an option.

For struct-fors, if we deprecate `ti.grouped`, what would be the type for `i` in `for i in x` where `x` is a 1-D field? Is that a scalar or a 1D vector? :-)

If we only deprecate it for `ndrange` then there may be some inconsistency between two for loops.

**Comment by lin-hitonami** [comment]
> For struct-fors, if we deprecate `ti.grouped`, what would be the type for `i` in `for i in x` where `x` is a 1-D field? Is that a scalar or a 1D vector? :-)
What about a subclass of `ti.Expr` which can have subscript? We can let `i[0]` return `i`?

**Comment by yuanming-hu** [comment]
TBH, that would be a little tricky to understand...

**Comment by lin-hitonami** [comment]
> TBH, that would be a little tricky to understand by users, given it's neither a scalar nor a vector...

It is actually a scalar and a vector.

**Comment by lin-hitonami** [comment]
Given this only happens when there is only one loop variable and the field has only one dimension, I think it is not that hard to understand......

**Comment by strongoier** [comment]
I agree that we should not mix scalar and vector together.
