### ISSUE TITLE
Taichi example karman_vortex_street.py broken by PR 6360

### ISSUE THREAD

**Issue by jim19930609** [taichi-dev/taichi#6387]
https://github.com/taichi-dev/taichi/pull/6360 forbids looping over a 2-dimensional ti.ndrange() with a single loop index, which is incompatible with what documented in the official doc: https://docs.taichi-lang.org/api/taichi/lang/_ndrange/#taichi-lang-ndrange, thus breaks `karman_vortex_street.py`

![2022-10-20 09-42-16 的屏幕截图](https://user-images.githubusercontent.com/22334008/196837938-19a10e05-3e5f-4af8-b021-aa651149dd4e.png)

Please verify if we want to move forward with the new restrictions on ti.ndrange() and then fix `karman_vortex_street.py` + update the doc.

**Comment by houkensjtu** [comment]
I think the following code in `karman_vortex_street.py` was a mistake by the author rather than an intentional usage of the `loop_2d_as_1d()` syntax described in our documentation. Therefore, I suggest we move forward with the new restriction and fix `karman_vortext_street.py` (as follows)

**Comment by lin-hitonami** [comment]
Maybe we should first make it a warning and deprecate it, and then make it an error after a few versions.

**Comment by jim19930609** [comment]
> Maybe we should first make it a warning and deprecate it, and then make it an error after a few versions.

+1 for deprecation warning first

**Comment by neozhaoliang** [comment]
I'll update the code in Karman vortex to avoid using a single index in ndrange.
