### ISSUE TITLE
Replace pybind11

### ISSUE THREAD

**Issue by PGZXB** [taichi-dev/taichi#6395]
(Related `issue`: https://github.com/taichi-dev/taichi/issues/4830)

#### Motivation
Because of the high overhead of pybind11 (see [ailzhang/c_ext_for_py](https://github.com/ailzhang/c_ext_for_py)), using a more efficient method to export the Taichi core APIs to Python is necessary.

#### Preliminary Solution
* Replace `pybind11` with `ctypes` or `cpython` (or others) for **HOT** Taichi core APIs first, e.g., `make_const_expr_int`, `expr_*` and so on.
* THINKING...

#### TODO
THINKING...

#### Performance
...

#### Appendix
Counting API calls during run examples or tests (*very ugly charts*; ignore `get_max_num_indices` and `pop_python_print_buffer`):
Source code: [PGZXB:dev-profile-ticore-APIs](https://github.com/PGZXB/taichi/tree/dev-profile-ticore-APIs)
![image](https://user-images.githubusercontent.com/52557189/196911300-d2d62ef7-0d1c-4dcb-b61e-95e281ef6d0a.png)

**Comment by PGZXB** [comment]
> FYI, is it possible to quickly try nanobind as suggested in [#4830 (comment)](https://github.com/taichi-dev/taichi/issues/4830#issuecomment-1108078524)?

Thanks. @k-ye 
> Python 3.8+: nanobind heavily relies on [PEP 590 vector calls](https://www.python.org/dev/peps/pep-0590) that were introduced in version 3.8.
 
But the nanobind [only support Python3.8+](https://github.com/wjakob/nanobind#dependencies)?

And I'm thinking about whether we should standardize the APIs to be used to build new frontends, which require the stable C-APIs. And if we have the C-APIs, we can bind them to Python by using ctypes.

**Comment by bobcao3** [comment]
https://github.com/bobcao3/taichi/blob/dart-native/c_api/include/taichi/frontend_ir.h

Here was a half-made attempt to build a Taichi compiler C-API used to bind to Dart (and because it's CAPI it should be able to go everywhere)

**Comment by PGZXB** [comment]
> https://github.com/bobcao3/taichi/blob/dart-native/c_api/include/taichi/frontend_ir.h
> 
> Here was a half-made attempt to build a Taichi compiler C-API used to bind to Dart (and because it's CAPI it should be able to go everywhere)

Awesome work! I want to bind Taichi to my programming language that I have been developing in my spare time, but we don't have standard and stable APIs to build Taichi AST.

**Comment by bobcao3** [comment]
I think a critical part of experience is to reduce launch overhead. The API surface for launching kernels is quite a bit smaller than the AST APIs. Starting from there could be easier?

**Comment by PGZXB** [comment]
Thanks for your suggestion!

> I think a critical part of experience is to reduce launch overhead.

Agree. 

> The API surface for launching kernels is quite a bit smaller than the AST APIs. Starting from there could be easier?

Yes, starting from small part of APIs is easier.

> As a result I'd view this issue more to identify hotspots in py->c interaction and migrate them to cpython/ctypes step by step in a measurable way. We can probably employ cpython/ctypes in the critical parts for perf gain and keep some components in pybind11 to enjoy the ready-to-use C++ features. -- https://github.com/taichi-dev/taichi/issues/4830#issuecomment-1114438618

My preliminary thought is similar with @ailzhang's

**Comment by PGZXB** [comment]
I extend the @ailzhang's `c_ext_for_py` to test `nanobind` (source code: [PGZXB:c_ext_for_py](https://github.com/PGZXB/c_ext_for_py/tree/pgzxb-dev)).

The result of testing is....🤔
```shell

```

**Comment by yuanming-hu** [comment]
Note on the benchmark data: don't just test functions that take a simple `std::vector<int>` as input :-)

IIRC The pybind11 overhead mainly comes from RTTI (`isinstance` in pybind11 can take `~50 us`). Such overhead may come from testing argument types & casting to the Taichi kernel argument list.

I guess using a simple C API can significantly reduce the overhead.

A while (2 years?) ago I wrote a simple test script:

https://github.com/taichi-dev/taichi/blob/f573176e9398be9b56c8021d12e74aad2bab59b4/misc/demo_launch_overhead.py#L1-L19

On my end (M1 Mac) such kernel tasks 8e-6s, more than 5x overhead from @PGZXB's result above. It is also worth looking into what else contributes to the 8e-6s overhead.
