### ISSUE TITLE
C/C++ API should have better documentation

### ISSUE THREAD

**Issue by dio-exploded** [taichi-dev/taichi#6408]
There should be a document, or just a comment in the header file, to clarify the meaning of parameters.
For example, in
```
ti::NdArray<T>::write(const T *src, size_t size) const
```
```size``` actually means size in bytes. However without any explanation, I read it as size of array. This cost me an hour in debugging.
Either changing the name ```size``` to ```size_of_bytes```, or changing ```const T *src``` to ```const void *src```, will work for me. But I would appreciate a better explanation on these APIs.

**Comment by ailzhang** [comment]
I agree this `count` is a better name for this(will send a quick fix) and I guess the real feature request here is documentation for the C++ wrapper. 
cc: @PENGUINLIONG

**Comment by PENGUINLIONG** [comment]
> I agree this `count` is a better name for this(will send a quick fix) and I guess the real feature request here is documentation for the C++ wrapper. 
> 
> cc: @PENGUINLIONG 

will actually change to void*! Thanks for the report.

**Comment by yuanming-hu** [comment]
> will actually change to void*! Thanks for the report.

Do we have an API using count? I feel like when people are using ndarray with a specific type, it's rare to use a `size` that's not a multiple of `sizeof(T)`. Therefore it should be helpful to foolproof this case by using `count`.

**Comment by PENGUINLIONG** [comment]
> > will actually change to void*! Thanks for the report.
> 
> Do we have an API using count? I feel like when people are using ndarray with a specific type, it's rare to use a `size` that's not a multiple of `sizeof(T)`. Therefore it should be helpful to foolproof this case by using `count`.

oof sry i didn't see the entire thread. yes i initially added the api with typed input for the exact same reason. and obviously i forgot to make the size count in items. 🥲
