### ISSUE TITLE
More C++ API examples of textures

### ISSUE THREAD

**Issue by YuCrazing** [taichi-dev/taichi#6414]
**Concisely describe the proposed feature**

Texture-related functions in C++ APIs are very convenient, however, there are not many examples. I hope there are at least three examples to demonstrate:
1. how to initialize a `Texture` object from a `NdArray`.
2. how to initialize a `Texture` object from host data.
3. how to render a `Texture` object in a vulkan renderer.

**Comment by ailzhang** [comment]
FYI I think https://github.com/taichi-dev/taichi-aot-demo/pull/54 already satisfy this feature request, changing the owner of this issue ;)
