### ISSUE TITLE
Need to add mutex to TypeFactory methods 

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#6570]
**Describe the bug**
Currently only `get_primitive_type` has a mutex (https://github.com/taichi-dev/taichi/blob/55c9f91e355df100183e6b2f76f0e414a86e4704/taichi/ir/type_factory.cpp#L16). Maybe we need to add mutex to other methods too.

**Comment by jim19930609** [comment]
Correct me if I were wrong, but I remember the multi-thread compilation works on concurrent code generation for offloaded tasks, in which stage the CHI IR should already been finalized? 

In that sense, theoretically there shouldn't be any new types to be created and the multi-threads should use TypeFactory in a read-only manner?

**Comment by lin-hitonami** [comment]
There are some usages of TypeFactory in passes used in `offload_to_executable` stage which are executed in parallel. The passes also change the IR, and I'm not sure if the types are all already created.
