### ISSUE TITLE
taichi/outputs/tmp takes up too much space

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#659]
This folder takes up 27GB space on my laptop, with hundreds of folders (e.g. `taichi/outputs/tmp/task-2020-03-25-18-23-41-r06636`) in it, each of which contains a `taichi_core.pyd` of size ~42MB.

Since the folder is named `tmp`, I think it's safe to manually delete it. Shall we delete it automatically, or does it provide some information so we should keep it as long as the disk space is sufficient?

**Comment by archibate** [comment]
Maybe we want to `ln -s /tmp tmp`?

**Comment by yuanming-hu** [comment]
On windows, we create sandboxes under development mode. It's safe to delete them.
