### ISSUE TITLE
Separation of offline cache from AOT infrastructure

### ISSUE THREAD

**Issue by PENGUINLIONG** [taichi-dev/taichi#6604]
Currently the offline cache system to multiple backends depends on the AOT infrastructure while the AOT infra in undergoing a major refactorization to store AOT metadata files in JSON instead of TCB binaries. In this case, these two barely related subsystems *should* be isolated.

To clarify, I'm not saying that the offline cache system *should not* utilize the AOT infra but the current impl is mimicking the behavior of filesystem accesses of AOT modules. Ideallyl, offline cache should realize that by invocations to the AOT system interfaces.

cc @ailzhang @PGZXB

**Comment by PGZXB** [comment]
Agree. I will refactor the implementation of offline cache.

FYI, in fact, the LLVM AOT depends on LLVM Offline Cache lol.

**Comment by PGZXB** [comment]
>Ideallyl, offline cache should realize that by invocations to the AOT system interfaces.
Based on my *long practice*, the Offline Cache must hack the AOT if use the AOT infra, so the new implementation will not depend on AOT.

**Comment by PGZXB** [comment]
Done.
Related PR: https://github.com/taichi-dev/taichi/pull/7409
