### ISSUE TITLE
Simplify `dense.bitmasked` to `bitmasked`

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#663]
**Concisely describe the proposed feature**

Right now, `bitmasked` is a decorator on `dense` SNode. We can separate that so that `bitmasked` becomes its own SNode type. This came up from #661 . @KLozes also did the same thing for `pointer` in #462.

**Comment by yuanming-hu** [comment]
Thanks! I'll fix `bitmasked` garbage collection and zero filling on CPU/CUDA after this. Then we can ship the brand new `bitmasked` node with v0.5.9 :-)

**Comment by k-ye** [comment]
#676  did this for LLVM backends
