### ISSUE TITLE
GUI is slow

### ISSUE THREAD

**Issue by feisuzhu** [taichi-dev/taichi#6708]
Empty GUI loop consumes an entire core and couldn't keep up with 60fps

![2022-11-22-232933_2024x432_scrot](https://user-images.githubusercontent.com/857880/203354477-9b98c856-e0f1-4cdc-b0e2-ed0dd2152d3c.png)

**Comment by bobcao3** [comment]
Please use GGUI if possible (`ti.ui.Window`). Old GUI is CPU rendered and I don't think there is any parallelization

**Comment by bobcao3** [comment]
And we probably won't update or maintain old GUI anymore
