### ISSUE TITLE
Result of the example jacobian is abnormal

### ISSUE THREAD

**Issue by PGZXB** [taichi-dev/taichi#6733]
Run `ti example jacobian`:

![image](https://user-images.githubusercontent.com/52557189/203903067-f9f326c2-29b2-4e41-bee7-c5d05d763f7a.png)

**Comment by erizmr** [comment]
Was wondering on which version of Taichi does this bug happen?

**Comment by PGZXB** [comment]
Current master (73b3256dc2f504e540e31348ee466dd04d636ed8)

**Comment by PGZXB** [comment]
#6849 has fixed the bug.
