### ISSUE TITLE
[metal] Performance Improvements for `bitmasked`

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#678]
- [x] Currently, Metal's `listgen` will launch a group of threads whose size is equal to that of the total numbers of SNodes. This could be very inefficient.  Try [grid-stride loops](https://devblogs.nvidia.com/cuda-pro-tip-write-flexible-kernels-grid-stride-loops/) to balance the load.
- [x] Also adopt the grid-stride loop pattern to implement `struct_for` kernels.
- [x] If the immediate parent of a leaf `place` is a `bitmasked`, instead of appending the active `bitmasked` elements into `ListManager`, we might want to just loop through all the possible coordinates and check which are active directly (This is how LLVM backends implement it?). This is because the appending to `ListManager` is expensive, as it uses atomic operations.

**Comment by yuanming-hu** [comment]
> * This is how LLVM backends implement it?

Right. In LLVM ListManager only generates `8x8x8` leaf blocks (instead of every `1x1x1` leaf voxels). This allows the list generation overhead to be amortized by `8x8x8=512` voxels.
