### ISSUE TITLE
[RFC] Roadmap to minimize libtaichi_c_api.so library size

### ISSUE THREAD

**Issue by jim19930609** [taichi-dev/taichi#6793]
We roughly planed three stages to optimize the library size for libtaichi_c_api.so:
- Function level linking
- Symbol rearrangement and clean up
- Customized C-API features pruning

# 1. Turn on function-level linking
## 1.1 Convert CMake OBJECT targets to STATIC targets
Removes unnecessary entry files that compiles into libtaichi_c_api.so

[Before]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/22334008/205221958-0e58cc7e-4b33-4ea7-a38d-68339399c5b3.png">

[After]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/22334008/205222135-559241c1-71fa-4c25-9f02-77ee2be4bc28.png">

## 1.2 Apply version script to libtaichi_c_api.so
Convert unnecessary global symbols to local symbols, leading to more optimization opportunities.
[Before]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/22334008/205222164-349cc48e-f621-4e59-8535-2298b65f39e6.png">

[After]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/22334008/205222200-26165a73-a186-4031-8141-7d6598994878.png">

## 1.3 Add compile option `-ffunction-sections`, `-fdata-sections` and link option `--gc-sections`
Turns on function level linking eventually.
[Before]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/22334008/205222247-354363d3-8553-4949-addc-515d65d0fade.png">

[After]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/22334008/205222277-1161c4a6-3856-4a65-87dd-761282fa69f3.png">

Based on some experiment results, after turning on function-level-linking, we're expecting ~80% code size reduction from 12 MB to 1.7 MB (Vulkan C-API library, https://github.com/taichi-dev/taichi/pull/6388)

# 2. Symbol rearrangement and clean up
Further detect and clean up redundant symbols via symbol analysis (tooling: https://github.com/google/bloaty)

Symbol class | Symbol keyword | Size / KB | Side notes / KB
-- | -- | -- | --
libtaichi_c_api.so | [Total Size] | 1700 |  
 
RTTI + vtable | "vtable for" | 27 |  
RTTI + vtable | "typeinfo name for" | 9 |  
RTTI + vtable  | "typeinfo for" | 16 |  
  | [Sum] | 52 |  
 
Vulkan | "vkapi::" | 39 | [std::_Sp_counted_ptr]: 5[DeviceObjVk]: 23[vkapi::create_xxxx]: 11
Vulkan | "taichi::lang::vulkan" | 173 | [VulkanStream]: 11[VulkanDevice]: 69[VulkanSurface]: 10[VulkanCommandList]: 32[VulkanResourceBinder]: 16[VulkanPipeline]: 18[VulkanRenderPass]: 3[Helper Functions]: 12
Vulkan | "vma" | 3 | [external] VulkanMemoryAllocatorvmaAllocateMemoryForBuffervmaAllocateMemoryForImage
Vulkan | "Vma" | 60 | [VmaBlockVector]: 8[VmaBlockMetadata]: 26[VmaAllocator_T]: 18[VmaVector + VmaPoolAllocator + VmaJsonWriter]: 8
Vulkan | "volk" | 29 | [external] volkvolkGenLoadInstance
Vulkan | "taichi::lang::gfx" | 43 |  
  | [Sum] | 350 |  
 
SpirV | "taichi::lang::spirv" | 24 | [Internal]
SpirV | "spv" | 11 | [external] SPIRV-Tools
SpirV | "spdlog::" | 84 | [external] spdlogspdlog::details::R_formatter
  | [Sum] | 119 |  
 
Taichi | "taichi::" | 90 | [taichi::BinarySerializer]: 18[taichi::zip]: 6[taichi::lang::aot]: 19[Ndarray]: 3[Type]: 15[Device]: 9[Logger]: 4[Rest]: 12
 
Redundant | "fmt::v6" | 112 | [external]
Redundant | "tinfl" | 8 | [external] miniz (compression)
Redundant | "glfw" | 114 | [external] glfw
Redundant | "mz_" | 8 | [external] miniz (compression)
  | [Sum] | 242 |  
 
Standard Library | "std::" | 20 | Standard library
Standard Library | "_GLOBAL__sub_I" | 47 | Iostream related
  | [Sum] | 67 |  
 
  |   |   |  
Sections | .rodata | 178 | const strings
Sections | .gcc_exept_table | 456 | Exception handles
Sections | .rela.dyn | 13.7 
Sections | .dynstr | 4.57 
Sections | .dynsym | 4.64 
Sections | ... | ... |  
  | [Sum] | 673 |  
  |   |   |  
CAPI | [Sum] | 25 |  
Rest | [Sum] | 63 | Third-party libraries[spirv_reflect] ParseDescriptorBlockVariable

# 3. Customized C-API features
In certain situations, library size can be the killing blocker to ship a product. Therefore we should provide options to further remove unimportant features to further reduce the library size. Some possible options are:
1. Remove C++ exceptions handling and turn on `fno-except`
2. Remove RTTI information and turn on `fno-rtti`
3. Prune useless C-API interfaces to the user.

**Comment by ailzhang** [comment]
cc: @ghuau-innopeak

**Comment by jim19930609** [comment]
After turning on function level linking for libtaichi_c_api.so with https://github.com/taichi-dev/taichi/pull/6840/ as well as stripping the debug info with https://github.com/taichi-dev/taichi/pull/6845, significant code size reduction was observed:

<meta charset="utf-8"><div data-page-id="doxcnNICic9d3Y701Erpudsv7fh" data-docx-has-block-data="true"><div>

  | Size (Original) | Size (Optimized)
-- | -- | --
Vulkan | 14 MB | 1.5 MB
Vulkan + LLVM | 82 MB | 51 MB

libtaichi_c_api.so built with LLVM does not benefit that much from function level linking, mainly because libLLVM.a is not compiled with `-ffunction-sections -fdata-sections`. We'll have that fixed later.

TODO List:
1. Recompile third-party libraries with `-ffunction-sections -fdata-sections`, especially LLVM
2. Turn on function level linking for `taichi_python.so` as well, which has two prerequisite tasks:
- Resolve circular dependencies: https://github.com/taichi-dev/taichi/issues/6838
- Migrate OBJECT targets to STATIC targets in Taichi build system
