### ISSUE TITLE
[RFC] Replace JIT evaluator (on device) in constant folding pass with a minimal CHI IR interpreter on host

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#6834]
## Background:

Currently when we do constant folding we have[ this JIT evaluator](https://github.com/taichi-dev/taichi/blob/master/taichi/transforms/constant_fold.cpp#L25-L72) which creates another taichi kernel and then compile and run on the fly and then inject the evaluated result back to the original compilation process. And this JIT evaluator kernel runs on the exact same device as initiated taichi arch. 

## Goal:

We want to replace this JIT evaluator on device with a minimal CHI IR interpreter running on host. The main motivation is: 
- Currently JIT evaluator only handles unary cast op and binary ops, these ops are pretty lightweight, creating a taichi kernel and evaluating them on the device often creates overhead. 
- Well the main motivation is actually simplify the codebase, esp. compiling JIT evaluator kernels requires a different compileconfig than its parent compilation and it has been a headache to maintain this. Replacing it with a small interpreter on host can greatly simplify the process. And we have this [arithmetic interpreter prototype](https://github.com/taichi-dev/taichi/blob/master/taichi/analysis/arithmetic_interpretor.cpp) from @k-ye. 

## Planned steps

- [ ] Add tests for arithmetic interpreter to make sure it's still behaving correctly
- [ ] Expand binary op coverage in arithmetic interpreter so that we can replace the binary jit evaluator kernels
- [ ] Support unary cast in arithmetic interpreter so that we can replace the unary jit evaluator kernels
- [ ] There might be some precision issues since we now evaluate on host instead of taichi device, we think the precision issue is tolerable and we'll just "fix" the tests failures as they show up.

**Comment by bobcao3** [comment]
Do we even need an interpreter to do this? IMO we can just do something similar to `alg_simp` and do some pattern matching. We can reference NIR's simplify pass design

**Comment by strongoier** [comment]
> Do we even need an interpreter to do this? IMO we can just do something similar to alg_simp and do some pattern matching. We can reference NIR's simplify pass design

I agree that we don't need an interpreter here. It seems that the arithmetic interpreter prototype mentioned above has two main parts:
1. Skeleton code of an interpreter;
2. Pattern matching rules for arithmetic evaluation.

IMO part 2 can be useful; part 1 is unnecessary. So my suggestion here is to copy & complete part 2 into the constant folding pass.

**Comment by ailzhang** [comment]
Yup that sounds good to me! Code isn't complicated so we just port them over.
