### ISSUE TITLE
`ti test` to run single C++ test

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#684]
**Concisely describe the proposed feature**
For now `ti test` only supports single python tests. We may want to make it support C++ tests too.

**Describe the solution you'd like (if any)**
Avoid throwing a file-not-found error in https://github.com/taichi-dev/taichi/blob/763e8be8d76e22ca2f362650e5a53e9b7d4f6ea7/python/taichi/main.py#L153, and modify https://github.com/taichi-dev/taichi/blob/763e8be8d76e22ca2f362650e5a53e9b7d4f6ea7/python/taichi/main.py#L61. I'm not sure what to do when there are files with the same name in python tests and C++ tests.

**Additional comments**
`ti test python` and `ti test cpp` used to work to run all python/C++ tests. Are they deprecated?

**Comment by yuanming-hu** [comment]
We can probably use `ti test -c/--cpp` or `ti test -p/--python` for testing cpp and python only. Then filenames/test case names can follow these options.

> **Additional comments**
> `ti test python` and `ti test cpp` used to work to run all python/C++ tests. Are they deprecated?

Yes.

**Comment by archibate** [comment]
Note: currently we can use `ti test xxx.py` to test only python.

**Comment by xumingkuan** [comment]
Thanks to @archibate, this is well implemented.
