### ISSUE TITLE
Increasing the maximum amount of field indices allowed

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#6900]
I found myself writing the this line of code yesterday:
```
            self.configuration_ids = ti.field(
                int, shape=(3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2))
```
Of course, it didn't work because taichi currently constraints the maximum amount of indices to 8. Would it be possible to increase this limit to 12 or 16?

**Comment by AmesingFlank** [comment]
Created #6901 to increase this limit to 12, but please let me know if there are any concerns, or if you think we should go directly to 16.

**Comment by strongoier** [comment]
It's fine from my point of view.
