### ISSUE TITLE
What's the best way to extract a vector from a matrix?

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#6902]
I tried slicing the matrix:
```py
@ti.kernel
def k():
    m = ti.Matrix([[0,1], [2,3]])
    print(m[0, :])

k() 
```
But this gives me a matrix instead of a vector, that is, it prints `[[0, 1]]` instead of `[0, 1]`.

**Comment by strongoier** [comment]
In the past vectors and matrices in taichi were mixed together so the semantics of slicing was not well designed. We'd better make the result `[0, 1]` (numpy also does so). WDYT @jim19930609

**Comment by jim19930609** [comment]
Yep, sounds good to me
