### ISSUE TITLE
`len()` cannot be applied to `ti.Vector()` types with `real_matrix` enabled

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#6915]
This no longer works starting from #6801 
```py
@ti.kernel
def k():
    v = ti.Vector([1,2,3])
    print(ti.static(len(v)))

k()
```
The error thrown is 
```
Traceback (most recent call last):
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\ast\ast_transformer_utils.py", line 25, in __call__
    return method(ctx, node)
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\ast\ast_transformer.py", line 542, in build_Call
    node.ptr = func(*args, **keywords)
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\impl.py", line 1062, in static
    raise ValueError(
ValueError: Input to ti.static must be compile-time constants or global pointers, instead of <class 'taichi.lang.expr.Expr'>
```
I prefer `len()` over `v.n`, because `len()` can also be applied to tuple types. So I could write
```py
@ti.func
def f(v):
    len(v) ..
```
and this would work for both `ti.Vector()`s and lists/tuples.

The workaround I used before #6885 is to do `ti.init(real_matrix = False)`, but this no longer works after the switch is removed.

**Comment by AmesingFlank** [comment]
@strongoier @jim19930609 Would appreciate your help on this! What would be the best way to implement `len()` for real matrices? If you give me some instructions I can try to implement that and submit a PR :D

**Comment by jim19930609** [comment]
Looks like it's a fairly simple fix, let me push a PR in a minute~
