### ISSUE TITLE
How much temporary memory is required by `.to_numpy()`?

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#6924]
I was under the impression that `to_numpy()` would consume at most 1x of the memory being copied. 
However, this code fails, which shows that it consumes even more than 2x 
```py
ti.init(ti.cuda, device_memory_GB=7)

# 0.5 GB * sizeof(ti.f32) = 0.5 GB * 4 = 2GB
x = ti.field(ti.f32, shape=int(0.5 * 10**9))

x.to_numpy()
```
error message:
```
Traceback (most recent call last):
  File "C:\Users\ldfra\Code\Taichi\taichi\test.py", line 8, in <module>
    x.to_numpy()
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\util.py", line 310, in wrapped
    return func(*args, **kwargs)
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\field.py", line 302, in to_numpy
    tensor_to_ext_arr(self, arr)
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\kernel_impl.py", line 953, in wrapped
    return primal(*args, **kwargs)
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\kernel_impl.py", line 880, in __call__
    return self.runtime.compiled_functions[key](*args)
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\kernel_impl.py", line 805, in func__
    raise e from None
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\kernel_impl.py", line 802, in func__
    t_kernel(launch_ctx)
RuntimeError: [taichi/rhi/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void * *,unsigned __int64>::operator ()@88] CUDA Error CUDA_ERROR_OUT_OF_MEMORY: out of memory while calling malloc (cuMemAlloc_v2)
```
So I'm wondering just how much memory I need to reserve in order to use `to_numpy()`?

**Comment by AmesingFlank** [comment]
Doesn't seem to be a problem with `ti.vulkan` though.

**Comment by bobcao3** [comment]
That's interesting... The Vulkan and DX11 backend may need 2 extra buffers. First is a on-GPU plain buffer that is copied into from the SNode tree, and then the on GPU plain buffer is copied using Vulkan copy commands (i.e. DMA) onto a device-visible host plain buffer. The host plain buffer is then finally memcpy-ed into numpy array. There is some room for optimization in this process, but it will make it more complex. As for what CUDA backend is doing here, it's quite baffling

**Comment by jim19930609** [comment]
This is an implementation bug with CUDA backend. 

While arg-loading external data containers such as numpy arrays, we used to allocate temporary device memory in-place instead of reusing the pre-allocated memory: 

<img width="675" alt="image" src="https://user-images.githubusercontent.com/22334008/209922425-31db61e7-4356-44ed-9519-c6764bee9f56.png">

So if you set `device_memory_GB=5`, it's likely gonna work.

I'll push a fix for that.

**Comment by AmesingFlank** [comment]
ah I see, interesting. Many thanks for the fix!
