### ISSUE TITLE
Don't hash the pointer to the real function when generating the offline cache key

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#6929]
**Describe the bug**
When we get the offline cache key, we use the value of `Function *` as the key of the real function. However, this changes when we reset Taichi. We should use the hash key of the IR of the real function instead.

https://github.com/taichi-dev/taichi/blob/9cbc59a2021be4487c39754a14936357e8b19ad1/taichi/analysis/gen_offline_cache_key.cpp#L243

**Comment by PGZXB** [comment]
https://github.com/taichi-dev/taichi/blob/9cbc59a2021be4487c39754a14936357e8b19ad1/taichi/analysis/gen_offline_cache_key.cpp#L509-L519

**Comment by PGZXB** [comment]
However, the algorithm that generates the AST key for the real function is indeed wrong. See https://github.com/taichi-dev/taichi/issues/6877. I will redesign it.

**Comment by lin-hitonami** [comment]
Okay, I missed that part.
