### ISSUE TITLE
The rasterizer example runs < 15 FPS

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#6950]
In the past the rasterizer example can run 60 FPS. Now it can only run < 15 FPS.

After bisecting I find that the problem have existed since commit acc2cb0. The change to `fill()` in #6892 accidentally causes this issue. I'll send a PR to fix it.

**Comment by turbo0628** [comment]
I have also observed sharp performance regression in filling large ndarrays after 1.0.0, seems we have some other bottlenecks. I'll post a chart when the benchmark finishes.

**Comment by strongoier** [comment]
Interesting. That sounds like another problem. What about tracking this in another issue?
