### ISSUE TITLE
How to set full screen mode with ggui?

### ISSUE THREAD

**Issue by uyolo1314** [taichi-dev/taichi#6979]
How to set full screen mode with ggui?

**Comment by amakiir** [comment]
Someone please correct me if this is inaccurate, but from what I have seen normal full screen mode is not yet available with the GGUI.

But it is possible to get a windowed full screen mode by setting the resolution (`res`) to the resolution of the monitor and the  position of the window (`pos`) to `(0,0)`.

**Comment by PENGUINLIONG** [comment]
Hi! GGUI currently doesn't support full screen presentation. One blocker is that some 2D examples does depend on a specific resolution (or aspect ratio) to present correctly. We have a plan to improve GGUI in the recent couple of months so we might support this feature in the future. :)
