### ISSUE TITLE
[doc] Make installation guide more detailed in our docs

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#703]
As mentioned in #701, ubuntu 16.04 users have a hard time solving deps.
I also had a hard time setting up taichi developer environment.
Maybe we should have a more detailed installation guide, specific to different version of ubuntu's, which will definitely make users and contributors' easier to start with our project.

**Comment by archibate** [comment]
First of all,
> Note: This is NOT for installing the Taichi programming language. Unless you are building a legacy project based on the legacy Taichi library (e.g. taichi_mpm and spgrid_topo_opt) you should always install Taichi using pip.

If this is legacy one, then why we put it in the **head** of user's installation guide? We could remove it or move into other sections like dev_install.

**Comment by archibate** [comment]
Also note in dev_install:
> Make sure you have LLVM 8.0.1 built from scratch (Download).

The download link is to the llvm's offical release, maybe we can use the same pre-compiled llvm package as CI use? Or not?

**Comment by zerollzeng** [comment]
yes it's a problem, I mention in #660 , maybe maintain a docker develop environment is a good idea. since not everyone use ubuntu and dependency of taichi maybe confict with other project

**Comment by zerollzeng** [comment]
and by the way, GUI is NOT a problem because we can mount x11 to docker

**Comment by archibate** [comment]
replaced by #747
