### ISSUE TITLE
ti.sym_eig on identity matrix returns nan

### ISSUE THREAD

**Issue by xuan-li** [taichi-dev/taichi#7092]
**Describe the bug**
ti.sym_eig on identity matrix returns nan.

**To Reproduce**
```
import taichi as ti

ti.init()
@ti.kernel
def test():
    A = ti.Matrix([[1., 2., 3.], [2., 3., 4.], [3., 4., 8.]])
    I = ti.Matrix.identity(ti.f32,3)
    eig, V = ti.sym_eig(I)
    print(V)
    eig1, V1 = ti.sym_eig(A)
    print(V1)

test()
```

**Output**
```
[[-nan, -nan, -nan], [-nan, -nan, -nan], [-nan, -nan, -nan]]
[[0.325306, 0.231804, -0.916757], [0.466246, 0.804128, 0.368771], [0.822673, -0.547398, 0.153510]]
```

**Comment by jim19930609** [comment]
With some investigations from @neozhaoliang, it looks like an internal implementation error with our `sym_eig()` interface

**Comment by neozhaoliang** [comment]
@xuan-li Hi, Thanks for finding this bug, the problem is due to in this line, the term `norm` is zero, and we didn't handle this case properly:
https://github.com/taichi-dev/taichi/blob/master/python/taichi/_funcs.py#L341
@FantasyVR Could you please have a look?

**Comment by neozhaoliang** [comment]
I suspect in these lines, indices 1 and 2 are exchanged compared with the reference code (lines 74-77 in `dsyevc3.c`):
https://github.com/taichi-dev/taichi/blob/master/python/taichi/_funcs.py#L317-L320
