### ISSUE TITLE
Slicing vectors with negative indices returns wrong result

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#7096]
Consider this code segment
```py
@ti.kernel
def k(i:int):
    x = ti.Vector([i, i+1, i+2])
    print(x[:-1])

k(0)
```
it prints out
```
[]
```

**Comment by jim19930609** [comment]
I don't think we ever supported "-1" in either indexing or slicing. Shall I convert this issue to a feature request then?

**Comment by AmesingFlank** [comment]
> I don't think we ever supported "-1" in either indexing or slicing. Shall I convert this issue to a feature request then?

That makes sense. The reason it felt more like a bug than a feature was that there was no warning messages. Notice that I didn't enable dynamic indexing, so the index is a compile-time constant and the compiler should be able to produce a warning about it being negative, yet it did not.
