### ISSUE TITLE
Why the image data structure is WHC?

### ISSUE THREAD

**Issue by uyolo1314** [taichi-dev/taichi#7097]
The traditional image library is HWC, but why taichi's image data structure is WHC?

**Comment by jim19930609** [comment]
Hi uyolo1314, 
May I know what API functions you used with HWC image involved? Thanks!

**Comment by uyolo1314** [comment]
https://github.com/taichi-dev/taichi/blob/b523daf0a935c230928c60ada0b3da98b3f257ba/python/taichi/examples/simulation/fractal.py#L1-L35
For official example, the output image data structure is WHC.
In my code, columns index is related to rows data, and image data structure is HWC.
