### ISSUE TITLE
difftaichi/examples/diffmpm3d.py breaks on 1.4.0

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#7106]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
# sample code here
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
$ python diffmpm3d.py
[Taichi] version 1.4.0, llvm 15.0.4, commit 9c6acb5f, linux, python 3.10.0
[Taichi] Starting on arch=cuda
/home/lin/anaconda3/envs/p310/lib/python3.10/site-packages/taichi/__init__.py:77: DeprecationWarning: ti.ext_arr is deprecated. Please use ti.types.ndarray instead.
  warnings.warn(
/home/lin/anaconda3/envs/p310/lib/python3.10/site-packages/taichi/types/ndarray_type.py:80: DeprecationWarning: The element_dim and element_shape arguments for ndarray will be deprecated in v1.5.0, use matrix dtype instead.
  warnings.warn(
n_particles 30495
n_solid 30495
/home/lin/anaconda3/envs/p310/lib/python3.10/site-packages/taichi/lang/common_ops.py:21: DeprecationWarning: a.atomic_add(b) is deprecated. Please use ti.atomic_add(a, b) instead.
  warnings.warn(
i= 0 loss= -0.0  per iter 8.70s
i= 1 loss= -0.0  per iter 0.50s
i= 2 loss= -0.0  per iter 0.60s
i= 3 loss= -0.0  per iter 0.60s
i= 4 loss= -0.0  per iter 0.60s
i= 5 loss= -0.0  per iter 0.60s
i= 6 loss= -0.0  per iter 0.60s
i= 7 loss= -0.0  per iter 0.59s
i= 8 loss= -0.0  per iter 0.60s
i= 9 loss= -0.0  per iter 0.60s
i= 10 loss= -0.0  per iter 0.60s
i= 11 loss= -0.0  per iter 0.60s
i= 12 loss= -0.0  per iter 0.60s
i= 13 loss= -0.0  per iter 0.60s
i= 14 loss= -0.0  per iter 0.60s
i= 15 loss= -0.0  per iter 0.60s
i= 16 loss= -0.0  per iter 0.60s
i= 17 loss= -0.0  per iter 0.60s
i= 18 loss= -0.0  per iter 0.60s
i= 19 loss= -0.0  per iter 0.60s
```

**Additional comments**
If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by jim19930609** [comment]
`diffmpm3d.py` seems to be already broken before `f735fe180 [Lang] Enable real_matrix and real_matrix_scalarize by default (#6801)`. @erizmr can you take a look at this one? Thanks!

**Comment by jim19930609** [comment]
Seems to be broken in taichi v1.2.0

**Comment by erizmr** [comment]
The bug is induced by the name alias between global field and function arguments. Fixed by https://github.com/taichi-dev/difftaichi/pull/63.
