### ISSUE TITLE
Forum to discuss problems

### ISSUE THREAD

**Issue by mathusalem2020** [taichi-dev/taichi#719]
Dear all, 

As a lay person, I am trying to pick up the taichi framework. I am encountering a few, possibly simple issues. Is there a dedicated forum where one can ask questions ? I suppose this thread is for the core development. 

Kind regards, 
 math

**Comment by k-ye** [comment]
Feel free to post your questions here, I don't think there's specific restrictions around what types of questions can be asked..

**Comment by archibate** [comment]
In fact we already have forums, see https://forum.taichi.graphics.
