### ISSUE TITLE
dataclass in the for loop not showing the right value

### ISSUE THREAD

**Issue by donglai96** [taichi-dev/taichi#7255]
Hi all,

This might be a silly question but I think I don't understand the multiple for-loops here.

The data class called inside the third for loop is not showing the right value as I expect. I learned from the tutorial that the outermost loop will be parallelized, and others are the same with python. But that did not happen either.

I am wondering why the inside value is not changing but keeps its initial value.
Thank you! The code is as follows:

```python
import taichi as ti

ti.init()
Np = 3
Nw = 2
Nt = 5

@ti.dataclass
class Particle:
    r: ti.types.vector(3, ti.f64)
    t: ti.f64
    @ti.func
    def initParticles(self,x,y,z):
        self.r = ti.Vector([x,y,z])
        self.t = 0



particles = Particle.field(shape = (Np,))

dr = 0.1
dw = 0.3

@ti.kernel
def init():
    for n in range(Np):
        particles[n].initParticles(0,0,dr * n)
        
@ti.kernel
def simulate():
    for n in range(Np):
        for t in range(Nt):
            #rr = particles[n].r
            print('time***',t )
            print('r outside',particles[n].r)
            for m in range(Nw):
                print('r inside',particles[n].r) # why particles [n].r here showing particles' init value

            particles[n].r +=ti.Vector([0,0,1])
                
init()
simulate()
```

The result is 

> [Taichi] Starting on arch=arm64
time*** 0
r outside [0.000000000000, 0.000000000000, 0.000000000000]
r inside [0.000000000000, 0.000000000000, 0.000000000000]
r inside [0.000000000000, 0.000000000000, 0.000000000000]
time*** 1
r outside [0.000000000000, 0.000000000000, 1.000000000000]
r inside [0.000000000000, 0.000000000000, 0.000000000000]
r inside [0.000000000000, 0.000000000000, 0.000000000000]
time*** 2
r outside [0.000000000000, 0.000000000000, 2.000000000000]
r inside [0.000000000000, 0.000000000000, 0.000000000000]
r inside [0.000000000000, 0.000000000000, 0.000000000000]
time*** 3
r outside [0.000000000000, 0.000000000000, 3.000000000000]
r inside [0.000000000000, 0.000000000000, 0.000000000000]
r inside [0.000000000000, 0.000000000000, 0.000000000000]
time*** 4
r outside [0.000000000000, 0.000000000000, 4.000000000000]
r inside [0.000000000000, 0.000000000000, 0.000000000000]
r inside [0.000000000000, 0.000000000000, 0.000000000000]
time*** 0
r outside [0.000000000000, 0.000000000000, 0.100000001490]
r inside [0.000000000000, 0.000000000000, 0.100000001490]
r inside [0.000000000000, 0.000000000000, 0.100000001490]
time*** 1
r outside [0.000000000000, 0.000000000000, 1.100000001490]
r inside [0.000000000000, 0.000000000000, 0.100000001490]
r inside [0.000000000000, 0.000000000000, 0.100000001490]
time*** 2
r outside [0.000000000000, 0.000000000000, 2.100000001490]
r inside [0.000000000000, 0.000000000000, 0.100000001490]
r inside [0.000000000000, 0.000000000000, 0.100000001490]
time*** 3
r outside [0.000000000000, 0.000000000000, 3.100000001490]
r inside [0.000000000000, 0.000000000000, 0.100000001490]
r inside [0.000000000000, 0.000000000000, 0.100000001490]
time*** 4
r outside [0.000000000000, 0.000000000000, 4.100000001490]
r inside [0.000000000000, 0.000000000000, 0.100000001490]
r inside [0.000000000000, 0.000000000000, 0.100000001490]
time*** 0
r outside [0.000000000000, 0.000000000000, 0.200000002980]
r inside [0.000000000000, 0.000000000000, 0.200000002980]
r inside [0.000000000000, 0.000000000000, 0.200000002980]
time*** 1
r outside [0.000000000000, 0.000000000000, 1.200000002980]
r inside [0.000000000000, 0.000000000000, 0.200000002980]
r inside [0.000000000000, 0.000000000000, 0.200000002980]
time*** 2
r outside [0.000000000000, 0.000000000000, 2.200000002980]
r inside [0.000000000000, 0.000000000000, 0.200000002980]
r inside [0.000000000000, 0.000000000000, 0.200000002980]
time*** 3
r outside [0.000000000000, 0.000000000000, 3.200000002980]
r inside [0.000000000000, 0.000000000000, 0.200000002980]
r inside [0.000000000000, 0.000000000000, 0.200000002980]
time*** 4
r outside [0.000000000000, 0.000000000000, 4.200000002980]
r inside [0.000000000000, 0.000000000000, 0.200000002980]
r inside [0.000000000000, 0.000000000000, 0.200000002980]

**Comment by AmesingFlank** [comment]
This looks like a bug in TLS optimization. I wrote more about it here: #7263. For now, you can work around this issue by doing `advanced_optimization = False` in `ti.init()`

**Comment by lin-hitonami** [comment]
We can follow-up this on #7263. Closing this.
