### ISSUE TITLE
(Vulkan?) `Assertion failed: (m_pMetadata->IsEmpty()` running poisson_disk_sampling.py

### ISSUE THREAD

**Issue by feisuzhu** [taichi-dev/taichi#7266]
![2023-01-31-111352_933x272_scrot](https://user-images.githubusercontent.com/857880/215653910-e496730d-3182-4e33-8939-bfceafc08bed.png)
https://github.com/taichi-dev/taichi/actions/runs/4043351667/jobs/6952173166

**Comment by feisuzhu** [comment]
poisson_disk_sampling is not enabled in CI for now

**Comment by bobcao3** [comment]
Is this using GGUI?

**Comment by feisuzhu** [comment]
> Is this using GGUI?

Yes IIUC

![2023-01-31-160905_802x586_scrot](https://user-images.githubusercontent.com/857880/215702605-9e68f657-2c6f-4a3f-8e33-5d84986f82c7.png)

**Comment by feisuzhu** [comment]
We should escalate this issue since it is blocking https://github.com/taichi-dev/taichi/pull/7252 which is from an external contributer.
