### ISSUE TITLE
How does taichi speed up python code include numpy？

### ISSUE THREAD

**Issue by sanbuphy** [taichi-dev/taichi#7272]
【The following are all CPU-based scenarios】

Can I understand that taichi compiles the python code in advance and puts it in memory for use by hardware devices? 

Then numpy just gave him the operator for high-performance computing？

I want to know whether it is faster to use taichi alone or can it be faster in combination with taichi and numpy？

Thank you very much.

**Comment by neozhaoliang** [comment]
@sanbuphy Hi, not sure whether if you have read this doc: https://docs.taichi-lang.org/docs/accelerate_python

In principle, on the CPU, Taichi does not accelerate your numpy functions, for example, `np.sin`, `np.sum` or `np.linalg.inv`, and Taichi is not going to replace these numpy functionalities. Taichi can be used to accelerate your operations on numpy arrays when you want to implement your own function that numpy does not meet your need.

**Comment by sanbuphy** [comment]
> @sanbuphy Hi, not sure whether you have read this doc: https://docs.taichi-lang.org/docs/accelerate_python
> 
> In principle, Taichi does not accelerate your numpy functions, for example, `np.sin`, `np.sum` or `np.linalg.inv`, and Taichi is not going to replace these numpy functionalities. Taichi can be used to accelerate your operations on numpy arrays when you want to implement your own function that numpy does not meet your need.

Thank you. yes i had read this doc. but  i don't know that  why Taichi can be accelerate your operation. 
For example, I have several numpy arrays, I do some operations on him, and then this operation loops 2000 times.
It may not work in single time by taichi, but it can be accelerated by taichi when i repeat it so many cycles. (taichi acceleate my loop operations . Is my understanding correct? Then how does taichido it?

Thank you very much.

**Comment by neozhaoliang** [comment]
I have updated my answer: Taichi cannot accelerate your numpy functions.

**Comment by sanbuphy** [comment]
> @sanbuphy I have updated my answer.

Thank you for your answer, the last question I am curious about, 
for example, I do 10,000 numpy calculation operations in a loop, for this loop（only think about loop）, can taichi help me speed up?

**Comment by neozhaoliang** [comment]
> for example, I do 10,000 numpy calculation operations in a loop, for this loop（only think about loop）, can taichi help me speed up?

No.

**Comment by sanbuphy** [comment]
> > for example, I do 10,000 numpy calculation operations in a loop, for this loop（only think about loop）, can taichi help me speed up?
> 
> I think NO.

OK，I get it ,Thank you for your reply
