### ISSUE TITLE
Error when running an example after building from source in M1: symbol not found on flat namespace

### ISSUE THREAD

**Issue by JettChenT** [taichi-dev/taichi#7298]
**Describe the bug**
When attempting to build Taichi from source for development on a M1 Macbook Pro, in a similar fashion to https://github.com/taichi-dev/taichi/issues/4213 , the build worked out fine but I encountered the following error when attempting to run any of the examples:
```
ImportError: dlopen(/Users/jettchen/codes/taichi/python/taichi/_lib/core/taichi_python.cpython-39-darwin.so, 0x000A): symbol not found in flat namespace (_LLVMInitializeAArch64AsmParser)
```

Note: compared to the aforementioned issue, I encountered the symbol `_LLVMInitializeAArch64AsmParser` not being found, instead of `__ZN4llvm10CallbackVH6anchorEv`

### To reproduce
The Steps I followed:
1. Installed LLVM for Mac M1 and set the environment variable as according to [devoper docs](https://docs.taichi-lang.org/docs/dev_install#install-llvm)
2. Copied the extracted `taichi-llvm-15-m1` folder to home directory and set the corresponding environment variables
3. Created a separate Conda environment: `conda create --name taichi-dev python=3.9` and activated it
4. Ran the commands in section [Build Taichi From Source](https://docs.taichi-lang.org/docs/dev_install#build-taichi-from-source)
5. Ran an example in the examples folder

### Additional Info
Device information: MacBook Pro (13-inch, M1, 2020)
Running any taichi program via `pip install taichi` works fine on my local machine.

**Comment by bobcao3** [comment]
Could it be possible that conda installed a different version of LLVM10 and that got confused with the Taichi version? Can you check whether the LLVM_DIR env is correct in the conda environment?

**Comment by JettChenT** [comment]
Thanks for the response!
In my conda environment, executing `echo "$LLVM_DIR"` gives `/Users/jettchen/taichi-llvm`,  which is the correct directory I unpacked `taichi-llvm-15-m1`in.

**Comment by bobcao3** [comment]
Oh right! If you are on a M1 macbook pro, iirc anaconda don't actually have native M1 version yet (or its M1 version is wonky). I tried it a few days ago and it didn't work at all. You would probably need to use the `miniforge3` instead of the full anaconda3

**Comment by JettChenT** [comment]
tysm! Didn't know there was a difference between different distributions of conda.
Using `miniforge3` instead of anaconda worked on my computer.
