### ISSUE TITLE
ti.pow() can not use  a negative variable as exponent

### ISSUE THREAD

**Issue by Linyou** [taichi-dev/taichi#7304]
**Describe the bug**
Python dies when using a negative exponent variable in `ti.pow()`, but the kernel would work as expected if the exponent is a negative constant.

**To Reproduce**
This one would make the Python kernel die:
```py
@ti.kernel
def test():
    ex = 0
    result = ti.pow(2, ex-1)
    print("result: ",  result)
    
test()
```
this one is fine:
```py
@ti.kernel
def test():
    result = ti.pow(2, -1)
    print("result: ",  result)
    
test()
```

and this one would give a not allowed error:
```py
@ti.kernel
def test():
    ex = -1
    result = ti.pow(2, ex)
    print("result: ",  result)
    
test()
```
```
[E 02/05/23 16:11:54.056 35349] [constant_fold.cpp:visit@151] Negative exponent in pow(int, int) is not allowed.
```

**Comment by strongoier** [comment]
This is expected. See https://docs.taichi-lang.org/api/taichi/#taichi.pow for details. For your purpose, you can write `ti.pow(2.0, ex - 1)` instead.

**Comment by Linyou** [comment]
Thanks！
