### ISSUE TITLE
u64 field can't be assigned values greater than 2 ** 63

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#7313]
**Describe the bug**
u64 field can't be assigned values greater than 2 ** 63

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
import taichi as ti
ti.init()
a = ti.field(ti.u64, shape=())
a[None] = 2 ** 63
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lin/taichi/python/taichi/lang/util.py", line 310, in wrapped
    return func(*args, **kwargs)
  File "/Users/lin/taichi/python/taichi/lang/field.py", line 362, in __setitem__
    self.host_accessors[0].setter(value, *self._pad_key(key))
  File "/Users/lin/taichi/python/taichi/lang/field.py", line 418, in setter
    snode.write_int(key, value)
TypeError: write_int(): incompatible function arguments. The following argument types are supported:
    1. (self: taichi._lib.core.taichi_python.SNode, arg0: List[int], arg1: int) -> None

Invoked with: <taichi._lib.core.taichi_python.SNode object at 0x1278aadf0>, (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 9223372036854775808
```

**Comment by bobcao3** [comment]
Same is true for `u32`

**Comment by lin-hitonami** [comment]
#7319 uses the uint writer when the type is unsigned , and uses the int writer when the type is signed. However, this leads to another problem: currently in our tests there are many usages that assign negative numbers to unsigned fields (the uint writer can't take negative inputs so it fails). Should we silently allow this or give a warning message? Prohibiting this may not be a good idea since this may break many user codes (for example, assigning -1 to an unsigned number is quite common). Also, do we need to give a warning when the user assigns a number greater than the maximum value of a signed int to the signed field? @ailzhang @strongoier @jim19930609 
Since currently we don't check it inside kernels I think maybe we can just allow it silently?

**Comment by strongoier** [comment]
IMO it's OK to just allow it silently.
