### ISSUE TITLE
Regarding the HelloWorld Julia Set example code for loop issue

### ISSUE THREAD

**Issue by mmmovania** [taichi-dev/taichi#7335]
The HelloWorld Julia Set example code shown in the documentation and readme is running a for loop 1000000 times and calls the paint function on a GUI. This works but when you try to close your GUI window, it gives a RuntimeError  
```
Exception has occurred: RuntimeError
Window close button clicked, exiting... (use `while gui.running` to exit gracefully)
```
A better way would have been to let it run until the GUI is open. So something like this should be better.
```
i = 1
while gui.running:
    paint(i * 0.03)
    gui.set_image(pixels)
    gui.show()
    i=i+1
```
This closes the GUI window and application gracefully without any error.

**Comment by neozhaoliang** [comment]
Thank you for pointing out this nit! This will be fixed by the above PR.
