### ISSUE TITLE
conflict with vector initialized using np array element

### ISSUE THREAD

**Issue by zhouxian** [taichi-dev/taichi#7353]
**Describe the bug**
I recently upgraded from 1.1 to 1.4.1, and the following code snippet spits out an error which didn't occur in previous versions.
**To Reproduce**
```py
import numpy as np
import taichi as ti
ti.init()

x = ti.Vector.field(3, dtype=ti.f32, shape=())
a = np.array([1,2,3], dtype=np.float32)
b = ti.Vector([0, a[2], 0], dt=ti.f32)

@ti.kernel
def bar():
    foo()

@ti.func
def foo():
    print(ti.max(x[None], b))

bar()
```
And the following error occurs.
```
    print(ti.max(x[None], b))
          ^^^^^^^^^^^^^^^^^^
Element type of the matrix is invalid.
```
If I simply change `b` to `b = ti.Vector([0, 3, 0], dt=ti.f32)`, it works fine.

Is this a bug or some expected behavior?
Thanks!

**Comment by jim19930609** [comment]
Looks like it's an error wrt using numpy array elements, you can simply do: `b = ti.Vector([0, a.tolist()[1], 0], dt=ti.f32)` as a quick fix. Meanwhile, I'm gonna investigate it further.

**Comment by jim19930609** [comment]
okay it's a bug, we should duplicate the logic for `np.integer` for floating point numbers as well.

![截图 2023-02-15 09-46-08](https://user-images.githubusercontent.com/22334008/218906255-31a457fb-adfe-4a11-8945-6e71630c05bf.png)

**Comment by zhouxian** [comment]
Ok thanks! Looking forward to the next update.
