### ISSUE TITLE
[ir] Fix illegal intermediate IRs

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#739]
The new `verify` pass (#731) finds some IRs illegal in the process of `compile_to_offloads()`.

We may want to make each IR legal after `typecheck()`, so that we can uncomment https://github.com/taichi-dev/taichi/pull/731#discussion_r406554459 and find potential bugs in IR transform passes as early as possible.

Or, less probably, some IRs cannot become "legal" in the sense of current `verify` pass. If this happens, let's discuss what to do then.

List of tests to fix:
- [x] test_ad_if
- [x] test_atomic
- [x] test_grouped
- [x] test_local_atomics
- [x] test_loops
- [x] test_offload_cross
- [x] test_sparse_deactivate
- [x] test_sparse_parallel

**Comment by yuanming-hu** [comment]
Great - we are moving towards a more structured/well-defined IR system! Thanks for working on this.

**Comment by xumingkuan** [comment]
We can't do `verify` whenever `typecheck`, as `make_adjoint` calls `typecheck` when the IR is illegal. Maybe we can manually add some `verify`s in `compile_to_offloads`.
