### ISSUE TITLE
Better README page?

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#740]
I tried to think about what new users would think when they stumble into this repo, and it feels a bit too technical now... I really like the old page where it showed a few cool examples, which are both illustrative and appealing.

Maybe it's good to show off a few screenshots/GIFs from `mpm88.py` and `sdf_renderer.py`, and also show the code of `fractal.py`, so that people can immediately get an idea of how Taichi is used?

**Comment by yuanming-hu** [comment]
Great idea! I'm rather occupied today and will start this item tomorrow.
