### ISSUE TITLE
GGUI number input box

### ISSUE THREAD

**Issue by chunleili** [taichi-dev/taichi#7428]
Currently, the ggui input only support the slider, like this:

![image](https://user-images.githubusercontent.com/48758868/220828533-011e14cc-5fc5-4f47-9cba-a5060cf1568e.png)

What is annoying is that this slider doesnt support the direct input of numbers.

Could you add a number input box in ggui? Belowing one would be a desired state:

![image](https://user-images.githubusercontent.com/48758868/220828299-c182eacc-40c5-4f4a-97b6-01f02ff9564a.png)

that I marked in a red rectanle is the feature I wanted, including:
1. A radio button
2. A input box with "+/-"
3. A triplet input box
4. A slider also supporting direct input of number.
5. (finally) a simple input box of number

This is from the ggui online example:

https://pthom.github.io/imgui_manual_online/manual/imgui_manual.html

**Comment by PENGUINLIONG** [comment]
You can press control and click on the slider to edit its numeric value.

**Comment by PENGUINLIONG** [comment]
Since it's not longer active for a month I'm closing this.
