### ISSUE TITLE
Cant run any code that involves taichi.

### ISSUE THREAD

**Issue by matyklug18** [taichi-dev/taichi#745]
**Describe the bug**
i cant run any code that involves taichi. any demos just crash with the following error:

**Log/Screenshots**
https://pastebin.com/ADP4uskw

**To Reproduce**
really anything that involves taichi. crashes on this line: `gui.set_image(pixels)` while trying to follow https://taichi.readthedocs.io/en/latest/hello.html for example. any demos do that too.

**Comment by xumingkuan** [comment]
https://github.com/taichi-dev/taichi/blob/d9a803a3fd1e58aeb253602fbed8bcdd857e4d44/taichi/runtime/llvm/runtime.cpp#L108

Should this be `i32 vprintf`?

**Comment by archibate** [comment]
I thought this was already fixed in #477 ?

**Comment by matyklug18** [comment]
fixed in https://github.com/taichi-dev/taichi/pull/750
