### ISSUE TITLE
Texture load in @ti.func

### ISSUE THREAD

**Issue by afiretony** [taichi-dev/taichi#7464]
Hi,
I have a question related with texture load in Taichi.
In example `python/taichi/examples/rendering/simple_texture.py`, the texture object is declared out of taichi scope, and passed as `ti.types.texture` type to @ti.kernel function. It seemed that the texture will be converted to `taichi.lang._texture.TextureSampler` object type. 
My question is that how can use texture method like `sample_lod` or `fetch` in @ti.func?

**Comment by bobcao3** [comment]
You need to pass the texture in `@ti.template` (pass-by-reference)

**Comment by afiretony** [comment]
Hi @bobcao3 , thanks for answering!
Could you elaborate what do you meant to pass in `ti.template`?
This is what I tried to do but not works:

```
texture = ti.Texture(ti.Format.r32f, (n, n, n))

@ti.kernel
def paint(t: ti.f32, n: ti.i32):
    for i, j in pixels:
        uv = ti.Vector([i / res[0], j / res[1], t])
        c = ti.math.vec4(0.0)
        c = sample_tex(texture, uv)
        pixels[i, j] = [c.r, c.r, c.r]

@ti.func
def sample_tex(tex:ti.template(), uv):
    tex.sample_lod(uv, 0.0)
```

AttributeError: 'Texture' object has no attribute 'sample_lod'

**Comment by bobcao3** [comment]
You would also need to pass the texture into the kernel. Taichi textures can not be captured through global varaibles

**Comment by afiretony** [comment]
Hey @bobcao3 thanks, do you mean
```
@ti.kernel
def paint(t: ti.f32, tex: ti.types.texture(num_dimensions=3), n: ti.i32):
    for i, j in pixels:
        uv = ti.Vector([i / res[0], j / res[1], t])
        c = ti.math.vec4(0.0)
        c = sample_tex(tex, uv)
        pixels[i, j] = [c.r, c.r, c.r]

@ti.func
def sample_tex(tex:ti.template(), uv):
    tex.sample_lod(uv, 0.0)
```
But still gets error:
Traceback (most recent call last):
  File "playground.py", line 93, in <module>
    main()
  File "playground.py", line 86, in main
    paint(t,texture, n)
  File "C:\Users\\Anaconda3\envs\taichi\lib\site-packages\taichi\lang\kernel_impl.py", line 974, in wrapped
    return primal(*args, **kwargs)
  File "C:\Users\\Anaconda3\envs\taichi\lib\site-packages\taichi\lang\kernel_impl.py", line 901, in __call__
    return self.runtime.compiled_functions[key](*args)
  File "C:\Users\\Anaconda3\envs\taichi\lib\site-packages\taichi\lang\kernel_impl.py", line 826, in func__
    raise e from None
  File "C:\Users\\Anaconda3\envs\taichi\lib\site-packages\taichi\lang\kernel_impl.py", line 823, in func__
    t_kernel(launch_ctx)
RuntimeError: [type_factory.cpp:taichi::lang::promoted_type@222] Assertion failure: a->is<TensorType>() && b->is<TensorType>()

**Comment by bobcao3** [comment]
Hmmmmm. That seems like a bug? Let me check

**Comment by ailzhang** [comment]
@afiretony sorry for the late reply, this is not a bug since your `ti.func` is missing a return but we didn't do well in error reporting lol. 

This works for me: 
```
@ti.func
def sample_tex(tex: ti.template(), uv):
    return tex.sample_lod(uv, 0.0)

@ti.kernel
def paint(t: ti.f32, pixels: ti.types.ndarray(ndim=2),
          tex: ti.types.texture(num_dimensions=2)):
    for i, j in pixels:
        uv = ti.Vector([i / res[0], j / res[1]])
        warp_uv = uv + ti.Vector(
            [ti.cos(t + uv.x * 5.0),
             ti.sin(t + uv.y * 5.0)]) * 0.1
        c = ti.math.vec4(0.0)
        if uv.x > 0.5:
            # c = tex.sample_lod(warp_uv, 0.0)
            c = sample_tex(tex, warp_uv)
        else:
            c = tex.fetch(ti.cast(warp_uv * 128, ti.i32), 0)
        pixels[i, j] = [c.r, c.r, c.r, 1.0]
```
Let us know if you have followup questions! We'll try to improve the error message here.

**Comment by afiretony** [comment]
Thank you @ailzhang for pointing that out! Didn't notice such an obvious mistake here hahaha.
