### ISSUE TITLE
GGUI Metal support

### ISSUE THREAD

**Issue by jarmitage** [taichi-dev/taichi#7477]
Similar to https://github.com/taichi-dev/taichi/issues/3077, it would be great if we could use `GGUI` with Metal as the backend.

For a specific use case, I would like to use PyTorch on macOS which uses Metal (https://developer.apple.com/metal/pytorch/), in conjunction with the new `ndarray` https://docs.taichi-lang.org/docs/ndarray, and then use `GGUI` to visualise the results

**Comment by ailzhang** [comment]
Hey @jarmitage this should already work with ndarrays on the latest master, would you minding giving the latest nightly a try and see if it fits your case? 
```
pip install -i https://pypi.taichi.graphics/simple/ taichi-nightly
```

**Comment by jarmitage** [comment]
Thanks @ailzhang, how would I visualise the results though if combining taichi and torch using Metal?

**Comment by ailzhang** [comment]
@jarmitage you can use `my_ndarray.from_torch(my_torch_tensor)` to transfer data from torch to taichi before visualizing it using GGUI. 
Note `from_torch` on CUDA backend this is copy-free but on metal it involves a memcpy, shouldn't hurt perf too much tho.

**Comment by jarmitage** [comment]
I believe this can be closed now, see:

https://github.com/taichi-dev/taichi/releases/tag/v1.7.0
