### ISSUE TITLE
Typo in Doc Home, Advanced Programming, Data-Oriented Class

### ISSUE THREAD

**Issue by NextoneX** [taichi-dev/taichi#7486]
I run the code in `Another memory recycling example:`, and the **last** line of code in the example has an error:
~~~python
import taichi as ti

ti.init()

@ti.data_oriented
class Calc:
    def __init__(self):
        self.x = ti.field(dtype=ti.f32, shape=8)

    @ti.kernel
    def func(self, temp: ti.template()):
        for i in range(8):
            temp[i] = self.x[i * 2]

    def call_func(self):
        fb = ti.FieldsBuilder()
        temp = ti.field(dtype=ti.f32)
        fb.dense(ti.i, 8).place(temp)
        tree = fb.finalize()
        self.func(temp)
        tree.destroy()


a = Calc()
for i in range(16):
    a.x[i] = i
a.call_func()

# a.y causes an error!!!!
print(a.y)  # [ 5. 13. 21. 29.]
~~~

I don't know what `a.y` means, which causes an error in my IDE. Class `Calc` does not have such data.

Actually, I feel confused about this example. I don't know what `tree` or `fb` is for, maybe this part of the document needs to be rewritten.

**Comment by NextoneX** [comment]
Another typo was found in the example of `Inheritance of Data-Oriented classes`, where the output of `print(b.count())` is actually 20.
`print(b.count())  # 1` should be changed to `print(b.count())  # 20`.
However, It doesn't matter. Just a small mistake.

**Comment by FantasyVR** [comment]
Hi @NextoneX , sorry for the confusion, the example code of `Another memory recycling example:`  needs to be improved. 

1. To know more about `fb` and `tree`, please see [Manual field allocation and destruction](https://docs.taichi-lang.org/docs/master/layout#manual-field-allocation-and-destruction). And we will refer to it in this doc.
2. The output of `print(b.count())  # 1` is not correct, thanks for your comments.
