### ISSUE TITLE
Passing structures to and from kernels

### ISSUE THREAD

**Issue by neilger** [taichi-dev/taichi#7516]
I'm struggling with gettings structs into and out of a Taichi kernel. For example, I need a kernel that scans a large vector field and finds the limits (xmin/xmax, ...). 

I've tried all the permutations I can think of for defining the data structure with ti.dataclass, ti.type.struct, and Python dicts, and for passing it in and out with class names or ti.template(); I get type errors for all of them.

What's the recommended way to pass a data structure with named fields into and out of a kernel? Can that be done by reference so that it can be edited? Or is it not possible? My current work-around is to just use an array, and define global variables that are names of the array locations (xmin=0, xmax=1, ...).

**Comment by yuanming-hu** [comment]
Good point... IIRC, we don't support writing out struct arguments (i.e., pass by reference) in a kernel yet. It's true that `ti.ndarray` is by reference.

One potential solution for your case though: let the kernel return a `ti.Vector` with your max/min:

```python
vec2 = ti.math.vec2

def minmax() -> vec2:
    ...
    return vec2(min, max)
```

**Comment by neilger** [comment]
@yuanming-hu glad to hear that you are working on this. Returning a vector is my current work-around, but quickly becomes unwieldy when there are many named attributes to refer to.

**Comment by Datamance** [comment]
@yuanming-hu is there an issue where we can follow the development of this feature? @neilger's idea is a nice workaround, but it would be great to be able to explicitly pass struct fields into kernels.
