### ISSUE TITLE
A bug in GGUI Docs

### ISSUE THREAD

**Issue by wangyian-me** [taichi-dev/taichi#7522]
In the GGUI Docs (ggui.md), it obtains the image from window using ```img = window.get_image_buffer()```. But the object `ti.ui.Window` has no such function as shown in API. 

Maybe change it to ```img = window.get_image_buffer_as_numpy()```.

**Comment by FantasyVR** [comment]
Thanks @wangyian-me . You are correct. I will update the doc immediately.
