### ISSUE TITLE
Can we use taichi to speed up Open3D?

### ISSUE THREAD

**Issue by ChenQX1** [taichi-dev/taichi#7591]
I am working with Open3D to process 3D data. but it's a bit slow when data points are dense.
I am wondering whether we can speed it up by taichi, because most ops in Open3D are matrix manipulations.
any advice would be appreciated. thanks!

**Comment by ChenQX1** [comment]
> Please specify which part of the Open3D code you want to accelerate. Other people may not have experience with Open3D. Also, Taichi is not aimed at accelerating all matrix operations.

hi, i hope to accelerate this method `open3d.geometry.PointCloud.compute_point_cloud_distance`, do you have any idea?
thx

**Comment by neozhaoliang** [comment]
I think it's better to post the link to the source code, or directly post the code for matrix ops here?

**Comment by ChenQX1** [comment]
> I think it's better to post the link to the source code, or directly post the code for matrix ops here?

pls refer to this https://github.com/isl-org/Open3D/blob/master/cpp/open3d/geometry/PointCloud.cpp

i think the function is `std::vector<double> PointCloud::ComputePointCloudDistance` .

i am not familiar with cpp, sorry..

**Comment by neozhaoliang** [comment]
It seems the code is mainly about searching in a kdtree, not matrix operations?

**Comment by ChenQX1** [comment]
> It seems the code is mainly about searching in a kdtree, not matrix operations?

yeah... it seems like a search procedure by KNN.
i see that taichi can accelerate LCS(it's also a searching algorithm, right?), and Fibnacci computation. can it also help KNN?

**Comment by neozhaoliang** [comment]
No. Taichi cannot compile your open3d cpp code. This repo might help: https://github.com/xuhao1/TaichiSLAM

**Comment by neozhaoliang** [comment]
I'm closing this, feel free to reopen it if you have new questions on Open3D acceleration.
