### ISSUE TITLE
Compile to .pyd file

### ISSUE THREAD

**Issue by ustcfdm** [taichi-dev/taichi#7637]
Is it possible to compile taichi code into `.pyd` file? The purpose is to protect source code when I want share my program with others. I tried to compile a python file with taichi code into a pyd file using [nuitka](https://github.com/Nuitka/Nuitka). It worked for pure python part, but raised an error for taichi part.

**Comment by ustcfdm** [comment]
I raised a same issue in Nuitka repo. Details are here: https://github.com/Nuitka/Nuitka/issues/2132

**Comment by ustcfdm** [comment]
@neozhaoliang Thanks for your suggestion. I am wondering whether there is Python API for Taichi AOT? This should also a solution for me.

**Comment by neozhaoliang** [comment]
What about use some third-party libs to obfuscate your python code?

**Comment by ustcfdm** [comment]
This is a solution, but not my preference. Since Taichi needs the source code to compile, obfuscation does not really protect code. I would prefer AOT for Python API if possible.

**Comment by neozhaoliang** [comment]
The AOT module gives shader output that can be called by C++. The shader output is obfuscated but can still be analyzed by AI. So I doubt AOT would be the ideal solution.

**Comment by ustcfdm** [comment]
I see. This may beyond my understanding and requirement. 😮 It will be okay as long as there is no `.py` files somehow.

**Comment by ailzhang** [comment]
@ustcfdm btw AOT is supported on Windows ;) Feel free to give it a try and let us know if you hit any issues!

**Comment by ailzhang** [comment]
Closing as resolved, please feel free to reopen if you have followup questions!
