### ISSUE TITLE
[DOC]example in data orient class don't know what does mean, and also incorrect in demo output 

### ISSUE THREAD

**Issue by lgyStoic** [taichi-dev/taichi#7655]
In this link https://docs.taichi-lang.org/docs/data_oriented_class

Another memory recycling example:
```
import taichi as ti

ti.init()

@ti.data_oriented
class Calc:
    def __init__(self):
        self.x = ti.field(dtype=ti.f32, shape=16)
        self.y = ti.field(dtype=ti.f32, shape=4)

    @ti.kernel
    def func(self, temp: ti.template()):
        for i in range(8):
            temp[i] = self.x[i * 2] + self.x[i * 2 + 1]
        for i in range(4):
            self.y[i] = ti.max(temp[i * 2], temp[i * 2 + 1])

    def call_func(self):
        fb = ti.FieldsBuilder()
        temp = ti.field(dtype=ti.f32)
        fb.dense(ti.i, 8).place(temp)
        tree = fb.finalize()
        self.func(temp)
        tree.destroy()


a = Calc()
for i in range(16):
    a.x[i] = i
a.call_func()
print(a.y)  # [ 5. 13. 21. 29.]
```

in this code block I don't know what's meaning, and cannot inference by the context, is there anyone can explain about this ?

**Comment by jim19930609** [comment]
It's basically trying to show that you can create and destroy a `ti.field` and its underlying memory inside a `data_oriented` class method:

```
    def call_func(self):
        fb = ti.FieldsBuilder()
        temp = ti.field(dtype=ti.f32)
        fb.dense(ti.i, 8).place(temp)
        tree = fb.finalize()
        self.func(temp)
        tree.destroy()
```

Here we created `temp` using a `FieldsBuilder` and further destroyed it after done running the kernel `self.func(temp)`, `tree.destroy()`. 

Honestly, this is a bit off the topic of `data_oriented` class.

**Comment by lgyStoic** [comment]
> It's basically trying to show that you can create and destroy a `ti.field` and its underlying memory inside a `data_oriented` class method:
> 
> ```
>     def call_func(self):
>         fb = ti.FieldsBuilder()
>         temp = ti.field(dtype=ti.f32)
>         fb.dense(ti.i, 8).place(temp)
>         tree = fb.finalize()
>         self.func(temp)
>         tree.destroy()
> ```
> 
> Here we created `temp` using a `FieldsBuilder` and further destroyed it after done running the kernel `self.func(temp)`, `tree.destroy()`.
> 
> Honestly, this is a bit off the topic of `data_oriented` class.

I'am sorry about maybe I paste wrong code....In this doc link, I  saw the context on website is like this
![7b2c1ecc-b8a6-48e5-8cdc-a0fb757ad77c](https://user-images.githubusercontent.com/4526646/227824319-26a53d1d-d5d6-4fd5-95f2-6ec396b02fc0.jpeg)

there is even no idea about what is Y variable in class ....so the output is cause an assertion error....Maybe I copied the code from another way, accidentily the code I pasted upper is correct....

**Comment by jim19930609** [comment]
Ah I see, yup there used to be an issue with the example code in the doc, but it's been fixed in the latest master branch. You can switch to the `develop` tab to view the latest doc:

![截图 2023-03-27 11-31-58](https://user-images.githubusercontent.com/22334008/227834217-3ad4a926-087b-47fc-b18e-3e37fa51bfc7.png)

Do apologize for the mistake
