### ISSUE TITLE
How to use multiple GPU cards at a same machine？

### ISSUE THREAD

**Issue by Nanase-Nishino** [taichi-dev/taichi#7664]
export CUDA_VISIBLE_DEVICES=[UUID0, UUID1]
UUID = nvidia-smi -L (GPU-212e2fd1-0ba4-620e-d8b6-1xxxxxxxxx)

export TI_VISIBLE_DEVICE=[UUID0, UUID1](same as CUDA_VISIBLE_DEVICES)

still only one gpu has been used.

then we set arch=ti.vulkan

become C+G type.

**Comment by turbo0628** [comment]
Hi @Nanase-Nishino 

My first guess is that you should just specify `export CUDA_VISIBLE_DEVICES=0` in one process (or shell), and `export CUDA_VISIBLE_DEVICES=1` in another process (or shell) for the other GPUs. Current Taichi version doesn't support auto assigning kernels to multiple GPUs.

Furthermore, could you give out some more specific use cases regarding multi-card computations? Thanks!

**Comment by Nanase-Nishino** [comment]
thanks for ur quickly reply!
Ur first suggest sounds great and means more than multi-card for me.
But sorry for the next question, i am a fresh of taichi and linux.
How to specify two CUDA_VISIBLE_DEVICES for two processes?
The environment is ubuntu20.04, py3.8, pycharm remote sever and powershell.
before this, i set env by powershell and run code by pycharm remote.

**Comment by turbo0628** [comment]
Do you need to let the two GPUs cooperate? 

If yes, then it's really troublesome. You might want to use MPI4Py or something to make the communication. We have a [blog post](https://docs.taichi-lang.org/blog/scale-taichi-programs-with-mpi4py) on it that solves a big stencil. 

If no, things are rather straightforward, you can choose to use python's multiprocessing module and put your taichi function calls inside each process. The envs can be set in their own child process. This [stackoverflow answer](https://stackoverflow.com/questions/24642811/set-env-var-in-python-multiprocessing-process) is a good reference.

**Comment by Nanase-Nishino** [comment]
> 

thanks a lot！
I has done it successfully！
