### ISSUE TITLE
[question] document code about ndarray not work, and not know why

### ISSUE THREAD

**Issue by lgyStoic** [taichi-dev/taichi#7702]
the document code throw an error, but I check my taichi version and document is match

https://docs.taichi-lang.org/docs/v1.4.1/ndarray

```
arr = ti.ndarray(dtype=ti.math.vec3, shape=(4, 4))

```

![image](https://user-images.githubusercontent.com/4526646/228894246-34eb3b3e-052c-450d-a1ad-89edbe269030.png)

by the way, taichi version is 1.4.1

**Comment by lgyStoic** [comment]
try to debug this problem ...I try to output the dtype in Ndarray...

![image](https://user-images.githubusercontent.com/4526646/228899196-dd35b8b6-d2cb-45bc-8c8c-47c5a735ae95.png)

I found actually my type is ti.u8 and all_type is contain u8 ... so the branch wiil enter the line
```
return ScalarNdarray(dtype, shape)
```
that is correct ... But actually is not ... it run pass through , and try to init an vectorndarry...

So it there any problem with my taichi ? I build from source in tag rc-1.4.1....

**Comment by jim19930609** [comment]
Looks like you forgot to `ti.init(...)` before creating the Ndarray? 

On the other hand, Taichi should really improve its error reporting system.

**Comment by lgyStoic** [comment]
> Looks like you forgot to `ti.init(...)` before creating the Ndarray?
> 
> On the other hand, Taichi should improve its error reporting system real hard.
that is the point... because document said ndarray can also run in python scope..so always fogort that init operation....

**Comment by turbo0628** [comment]
Shall we improve the error message hint in this situation?
