### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by Wang-Yile** [taichi-dev/taichi#7710]
I hope Taichi can support Python 3.11 as soon as possible, so that it can be compatible with my development environment.
I have just switched from Python 3.10 to Python 3.11.

The **PEP 657** in Python 3.11 has been very helpful for my debugging!

I hope keen community members can help me realize this. Welcome your contribution!

**Comment by ailzhang** [comment]
@Wang-Yile FYI @feisuzhu has added python3.11 support in our CI pipeline and we'll release a 3.11 whl starting from the next release (v1.6.0), cheers! 
Btw if you are okay with using a nightly build of taichi, we release a py3.11 version in it continuously there already ;) 
https://github.com/taichi-dev/taichi#installation

**Comment by Wang-Yile** [comment]
@ailzhang thanks
