### ISSUE TITLE
No taichi package on linux

### ISSUE THREAD

**Issue by kazimuth** [taichi-dev/taichi#772]
**Describe the bug**
The build seems to be broken on linux and there's no `taichi` package available.

**Log/Screenshots**
```
radical@phenocryst ~> pip search taichi
taichi (0.5.11)                    - The Taichi Programming Language
taichi-nightly (0.5.11)            - The Taichi Programming Language
taichi-gpu-nightly (0.0.59)        - The Taichi Programming Language
taichi-nightly-cuda-10-1 (0.5.10)  - The Taichi Programming Language
taichi-nightly-cuda-10-0 (0.5.10)  - The Taichi Programming Language

radical@phenocryst ~> pip install --user taichi
ERROR: Could not find a version that satisfies the requirement taichi (from versions: none)
ERROR: No matching distribution found for taichi
```

**To Reproduce**
Try to install on a linux box.

You can also go to https://pypi.org/simple/taichi/ to see available downloads; as you can see, there's only windows and mac installs.

Workaround: use taichi-nightly for now. (Side note, there's also no `taichi-nightly` for python 3.8, not sure what's up with that.)

**Comment by yuanming-hu** [comment]
Thanks for reporting. Yes, please use `taichi-nightly` for now. We will release v0.5.12 for all environments.

**Comment by yuanming-hu** [comment]
@kazimuth I uploaded `taichi` v0.5.11 on Linux with Python 3.6/3.7/3.8. Let me know if that works for you. v0.5.12 with full platform support will be released tonight. Thanks for your patience!

**Comment by kazimuth** [comment]
[Looks like stuff is up!](https://pypi.org/simple/taichi/) although i don't see packages for 0.5.12-osx-python3.[7,8] yet -- but maybe they're just not finished building.

**Comment by yuanming-hu** [comment]
Thanks! All 9 packages are up now. The OS X built bot crashed last night for some reason...
