### ISSUE TITLE
[CLI] Run examples from CLI (e.g. `python3 -m taichi example mpm88`)

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#775]
**Concisely describe the proposed feature**
While implementing #740, I realized maybe it will be helpful for users to directly run the examples after they install `taichi`, without download any other files. This can be implemented via something like
```
python3 -m taichi example game_of_life
python3 -m taichi example stable_fluids
python3 -m taichi example mpm88
```

**Comment by archibate** [comment]
I guess `ln -s ../examples python/`?
Btw, how about also taichi.tests.XXX?

**Comment by yuanming-hu** [comment]
I think it's easier if we simply add an `example` command to`ti`/`python -m taichi`.

**Comment by archibate** [comment]
We also want user able to see/modify the example codes for better convinence.

**Comment by rexwangcc** [comment]
> I think it's easier if we simply add an example command toti/python -m taichi.

It sounds like a good starting point for me to understand how Taichi CLI is engineered, so I'd like to pick up this task if it's not taken yet.

**Comment by yuanming-hu** [comment]
> > I think it's easier if we simply add an example command toti/python -m taichi.
> 
> It sounds like a good starting point for me to understand how Taichi CLI is engineered, so I'd like to pick up this task if it's not taken yet.

Thank you for helping with this! This will simplify how end-users run Taichi examples. Just two notes:
 - We are on our way to get rid of the ad-hoc `if-elif-else` branches in `main.py`. New commands should ideally be added to the argparser: https://github.com/taichi-dev/taichi/blob/91b8164e4a881d7d588daf02ca5083e097fa0fec/python/taichi/main.py#L158

- The `examples` folder is not yet shipped with PyPI. Please modify somewhere around here https://github.com/taichi-dev/taichi/blob/91b8164e4a881d7d588daf02ca5083e097fa0fec/python/build.py#L82 so that we ship it together with the PyPI package.

**Comment by rexwangcc** [comment]
Thanks for the pointers!! 

Yeah, it's probably better to move away from the elif cases and take advantage of the built-in argparse, and let it populate the help messages for us... For `examples`, i was thinking about using the `data_files` originaly, let me take a closer look into `build.py`. Also, I will make sure to open draft PR at the early stage so folks can stop me before it's going off normal :)

**Comment by yuanming-hu** [comment]
Finally we can close this, thanks to the great contribution by @rexwangcc.
