### ISSUE TITLE
poor performance on cuda

### ISSUE THREAD

**Issue by liblaf** [taichi-dev/taichi#7763]
I implemented a naive Adam solver and tested it on CPU and Cuda. It turns out that the calculations on my laptop CPU are even faster than on the RTX 3090! However, the kernel time on Cuda is indeed much lower than on CPU (although still not up to my expectations).

Maybe it is a problem with my implementation.

Source code and test data can be found [here](https://github.com/liblaf/taichi-extras/tree/main/examples/deformation_transfer).

**Comment by bobcao3** [comment]
Just to do some sanity check... Can you try this code on the Vulkan backend as well?

**Comment by liblaf** [comment]
@bobcao3 I retested the task on some different backends and here are the results. These results look weird to me. Could the poor performance on cuda be due to a CPU bottleneck?

### On Local Machine (i7-1260P, no dedicated GPU)

| Arch   | Time             | Compile Time | Kernel Time   |
| ------ | ---------------- | ------------ | ------------- |
| x64    | `0:01:25.128130` | `325.730 ms` | `46.535 s`    |
| vulkan | `0:20:01.814735` | `14.127 ms`  | Not Available |

### On Remote Server (E5-2683 v3, RTX 3090)

| Arch   | Time             | Compile Time | Kernel Time   |
| ------ | ---------------- | ------------ | ------------- |
| cuda   | `0:01:25.572995` | `567.996 ms` | `8.679 s`     |
| vulkan | `0:02:02.939205` | `41.185 ms`  | Not Available |
| x64    | `0:04:35.204867` | `633.295 ms` | `189.465 s`   |

**Comment by liblaf** [comment]
close as stale

**Comment by xiaobo-lab** [comment]
I tried too, why vulkan so fast? I have been using cuda，it is too slow!
