### ISSUE TITLE
cache filed not generated

### ISSUE THREAD

**Issue by zhouxian** [taichi-dev/taichi#7769]
Minimal example:
```python
import taichi as ti

ti.init(arch=ti.gpu, device_memory_GB=8, debug=False)
window = ti.ui.Window('x', (128, 128), vsync=True, show_window=False)
# window2 = ti.ui.Window('x2', (128, 128), vsync=True, show_window=False) # if we uncomment this, cache files won't be generated


# x = ti.field(dtype=ti.f32, shape=10, needs_grad=True)

@ti.kernel
def funcc():
    print(2)

funcc()
```
I noticed cache file is not generated in various cases. This is a minimal example to reproduce it. If we uncomment the code for creating `window2`, there won't be cache files generated.

**Comment by zhouxian** [comment]
@ailzhang Yes exactly. Sorry for not making it clear.

**Comment by ailzhang** [comment]
cc: @PGZXB to take a look ;)

**Comment by ailzhang** [comment]
@zhouxian Hi, the root cause here is that we don't yet support multiple Window instance yet, I'll send a PR to throw out an error when the second window is initiated. sorry you might have to work around it for now.

**Comment by zhouxian** [comment]
@ailzhang Thanks for helping looking into this! I can try to avoid launch multiple windows, but the offline cache files fail to be generated in various cases. Sadly I am not able to reproduce with a minimal example, but in a kind of big codebase we are developing which also involves custom torch tensors, the offline cache is not working. I suspect it is due to some non proper destruction of torch tensors at exit. But is there anyway for us to manually save the offline cache file so that it does not rely on a clean exit?

**Comment by zhouxian** [comment]
@ailzhang @PGZXB Any idea on this? Thanks!

**Comment by PGZXB** [comment]
@zhouxian Sorry for my late reply! I think you could insert `ti.reset()` at the end of your code, in which the offline cache files will be dumped. But I'm not sure if this method will work.

**Comment by ailzhang** [comment]
@zhouxian would you mind giving https://github.com/taichi-dev/taichi/pull/7812 a try locally and see if it solves your problem? Thanks!

**Comment by zhouxian** [comment]
ti.reset solves my problem! Thanks for the help.
