### ISSUE TITLE
Deactivate bitmasked segfaults on cpu?

### ISSUE THREAD

**Issue by kazimuth** [taichi-dev/taichi#778]
**Describe the bug**
Trying to deactivate a bitmasked var segfaults on python3.7 / linux / x86_64 / cpu. Although it's possible I'm using it wrong?

**To Reproduce**
```python
import taichi as ti

ti.init(arch=ti.x64)

a = ti.var(ti.i32)

a_a = ti.root.bitmasked(ti.i, 4)
a_b = a_a.dense(ti.i, 4)
a_b.place(a)

@ti.kernel
def deactivate():
    ti.deactivate(a_a, 0)
    # or: ti.deactivate(a.parent().parent(), 0)

deactivate() # segfault
# segfaults if you initialize first too
```

**Comment by k-ye** [comment]
It crashed at `node_gc` https://github.com/taichi-dev/taichi/blob/f0d6bd70f90f51cf2aa39cb2ed716e8a7acf0f11/taichi/runtime/llvm/runtime.cpp#L1115-L1117

`NodeAllocator` is only allocated for `pointer` and `dynamic`, but not `bitmasked` SNodes

https://github.com/taichi-dev/taichi/blob/f0d6bd70f90f51cf2aa39cb2ed716e8a7acf0f11/taichi/program/program.cpp#L214-L231

Therefore `node_allocators[snode_id]` is `nullptr`. I will make a fix.
