### ISSUE TITLE
M1 release needs zstd to work

### ISSUE THREAD

**Issue by feisuzhu** [taichi-dev/taichi#7807]
`pip install taichi` on a clean M2 mac needs libzstd.

Can be workarounded by `brew install zstd`

**Comment by ailzhang** [comment]
@feisuzhu there was a similar issue in https://github.com/taichi-dev/taichi/issues/7483, which requires we re-build prebuilt llvm without zstd IIUC. May I transfer that one to you haha?

**Comment by feisuzhu** [comment]
> @feisuzhu there was a similar issue in #7483, which requires we re-build prebuilt llvm without zstd IIUC. May I transfer that one to you haha?

OK, I'll handle this
