### ISSUE TITLE
[bug] `cuDeviceGetDefaultMemPool` is being used on older drivers

### ISSUE THREAD

**Issue by qmdxcube** [taichi-dev/taichi#7826]
**Describe the bug**
Function cuDeviceGetDefaultMemPool not found for GeForce RTX 2060

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
import taichi as ti
import meshtaichi_patcher as Patcher

ti.init(arch=ti.cuda,kernel_profiler=True)

if __name__ == '__main__':
	print(1)
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
[Taichi] version 1.5.0, llvm 15.0.1, commit 7b885c28, win, python 3.10.9
[E 04/17/23 11:09:22.656 3152] [dynamic_loader.cpp:taichi::DynamicLoader::load_function@32] Function cuDeviceGetDefaultMemPool not found


[W 04/17/23 11:09:22.657 3152] RuntimeError: '[dynamic_loader.cpp:taichi::DynamicLoader::load_function@32] Function cuDeviceGetDefaultMemPool not found' occurred when detecting cuda, consider adding `TI_ENABLE_CUDA=0`  to environment variables to suppress this warning message.
[W 04/17/23 11:09:22.657 3152] [misc.py:adaptive_arch_select@772] Arch=[<Arch.cuda: 5>] is not supported, falling back to CPU
[Taichi] Starting on arch=x64
1
[Finished in 0.7s]

```

**Additional comments**
If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.

![1 (2)](https://user-images.githubusercontent.com/67142522/232399518-d477a8fd-ab75-4167-a1f1-3fd3ec9a3358.png)
![2 (2)](https://user-images.githubusercontent.com/67142522/232399563-469b9f3c-8bed-4017-b9d2-1bf253d006c0.png)
![3 (2)](https://user-images.githubusercontent.com/67142522/232399601-2da3538e-68a7-44ec-bc47-932c06e83192.png)

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by feisuzhu** [comment]
Thanks for reporting this!

`cuDeviceGetDefaultMemPool` is first introduced in CUDA v11.2, so could you try upgrading your CUDA toolkit and try again ?

**Comment by feisuzhu** [comment]
If you don't want to install CUDA toolkit, just upgrade the graphics driver to a more recent one could suffice too.

**Comment by qmdxcube** [comment]
Thanks for your quick reply. I will try these two methods.

**Comment by qmdxcube** [comment]
I upgraded the graphics driver and it works now. Thanks!

**Comment by bobcao3** [comment]
This should provide a warning of not up to date drivers and instead of crashing fall back to non-pooled allocation
