### ISSUE TITLE
Taichi Kernels are 8-9x slower than CUDA kernels.

### ISSUE THREAD

**Issue by rahul-goel** [taichi-dev/taichi#7842]
**Describe the bug**
Taichi kernel is 8-9x slower than CUDA kernel when I'm using it to compute and manipulate torch tensors.

**To Reproduce**
Please run `python benchmark.py` to run the compare the two kernels. This does not meet the 20 line limit since I am sharing CUDA code as well.
Pytorch, taichi, nvcc, pybind11 needs to be installed to run this.

I've put the files in a github gist:
https://gist.github.com/rahul-goel/58c8e4935b0c4f5e7021a095a056bdae

**Log/Screenshots**
![image](https://user-images.githubusercontent.com/54021162/232758757-b7e53444-4c46-4063-a1c6-b20a4c2f27eb.png)

Taichi version details:
[env_info.txt](https://github.com/taichi-dev/taichi/files/11261012/env_info.txt)
```
[Taichi] version 1.5.0, llvm 15.0.4, commit 7b885c28, linux, python 3.9.15
```

**Comment by rahul-goel** [comment]
Thanks for assigning someone to this issue. I face this problem in some other kernels I implemented as well.
Please let me know if you need any assistance with this. I am ready to help.

**Comment by rahul-goel** [comment]
I think the problem is when I am passing the torch tensors to the kernel! Even if I keep the kernel code as empty, the time taken barely changes. So the problem must be in the interfaces of torch and taichi.

**Comment by zxlbig** [comment]
> I think the problem is when I am passing the torch tensors to the kernel! Even if I keep the kernel code as empty, the time taken barely changes. So the problem must be in the interfaces of torch and taichi.
According to my profiling results, 95% of the performance difference comes from the launch overhead of Taichi and CUDA, and the data transfer between Taichi and PyTorch only accounts for a very small amount of time.
here's the profling data
```
Taichi Time:   0.000102
CUDA Time:     0.000010
real Taichi Time:   0.000093
```
"Taichi time" includes both data convert between taichi and torch and Taichi kernel time. And "real Taichi Time" is 9 times slower than cuda. even if kernel is small

**Comment by rahul-goel** [comment]
Thank you for looking into this.

So, the problem is in the kernel launch which should not be the case ideally. Hopefully, the problem can be found and resolved soon.

**Comment by oliver-batchelor** [comment]
Two things:
1) You need to call torch.cuda.synchronize() before you measure the end time to get a fair timing.

2) The taichi code in the first iteration includes the JIT for compiling the kernel, so ideally that is not included.

**Comment by rahul-goel** [comment]
Response to point 2: Yes, I've tested without the JIT time as well and the problem of slow kernel remained and that is why I raised the issue.

Response to point 1: Thank you for pointing out `torch.cuda.synchronize()`. I found a [nice blog](https://www.speechmatics.com/company/articles-and-news/timing-operations-in-pytorch) explaining why this should be used. Upon adding this synchronization step after both the CUDA kernel launch and Taichi kernel launch, I am seeing that Taichi is performing better than the CUDA kernels. 🤯

If this was the only problem why Taichi was performing slow, please feel free to close the issue. Thank you for your time and effort.

I have some follow up questions: Does Taichi launch the kernel and move on to perform other computations? If the computations (be it in Taichi or in PyTorch) rely on the kernel being finished, does it wait for the older kernel to finish? Is there a place where I could read up on these intrinsic details to understand them better?
