### ISSUE TITLE
The generation of spirv array type is wrong

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#7855]
**Describe the bug**
https://github.com/taichi-dev/taichi/blob/db13138bc646e81563ce598a80883b1b9ef5d60c/taichi/codegen/spirv/spirv_types.cpp#L456-L458
We should pass the shape as a spirv value of int immediate number instead of an int literal.

**Comment by bobcao3** [comment]
ouch... How did it compile and work on all these GPUs tho

**Comment by bobcao3** [comment]
Oh... right we don't declare arrays but rather runtime arrays
