### ISSUE TITLE
How to build ios static C-API library?

### ISSUE THREAD

**Issue by helloworldstone** [taichi-dev/taichi#7935]
Hi,  taichi v1.5.0 has supported Apple's Metal API. But how to build ios static C-API library with metal?
Thanks!

**Comment by feisuzhu** [comment]
Sorry for the late reply.

Please try `python build.py ios` in Taichi repo.

**Comment by feisuzhu** [comment]
Please `export PY=3.10`

**Comment by feisuzhu** [comment]
You are not using `master` branch I think ?

The script is not capable of building iOS libs at v1.5.0

**Comment by feisuzhu** [comment]
Closing as solved.
