### ISSUE TITLE
[ir] Support GEP for in autodiff for reading vector / matrix in args buffer

### ISSUE THREAD

**Issue by bobcao3** [taichi-dev/taichi#7952]
Currently vector / matrix are compiled as structs in the arguments and thus not supported by autodiff (because lacking implementation for GEP)

**Comment by ailzhang** [comment]
@bobcao3 are you asking for differentiable vector/matrix support? Or can you give an example of the code that you'd like to work?

**Comment by lin-hitonami** [comment]
We can revert https://github.com/taichi-dev/taichi/commit/5cd1407b0057019f2e48f5569fec30a8dc540213 if it is not easy to support.
