### ISSUE TITLE
It seems a error in the FAQ-How do I compute the minimum/maximum of a field?

### ISSUE THREAD

**Issue by Nanase-Nishino** [taichi-dev/taichi#7958]
The doc is:
How do I compute the minimum/maximum of a field?
Use ti.automic.min/max instead of ti.min/max. For example:

for i in x:
   ret = ti.atomic_min(ret, x[i])

but in the doc of ti.atomic_min,  store the result in x, and return the old value of x.
So the code should be changed to:

for i in x:
   ti.atomic_min(ret, x[i])

**Comment by neozhaoliang** [comment]
Yes, it's indeed an error in the doc, thank you for reporting!
