### ISSUE TITLE
Generate aot file failed when use both rw_texture and ndarray in ti.kernel

### ISSUE THREAD

**Issue by helloworldstone** [taichi-dev/taichi#7976]
Hi, when I use both rw_texture and ndarray in ti.kernel, an error is reported when generating the aot file：

`[W 05/10/23 19:38:18.222 1784794] [spirv_codegen.cpp:spriv_message_consumer@2278] input
[441:0:0] Id is 0
[E 05/10/23 19:38:18.222 1784794] [spirv_codegen.cpp:run@2371] SPIRV optimization failed
Traceback (most recent call last):
  File "/Users/xxx/test_taichi_tex_buf.py", line 43, in <module>
    test_texture_buf(ti.vulkan)
  File "/Users/xxx/test_taichi_tex_buf.py", line 39, in test_texture_buf
    m.add_graph("taichi_kernel_test", g)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/taichi/aot/module.py", line 173, in add_graph
    self._aot_builder.add_graph(name, graph._compiled_graph)
RuntimeError: [spirv_codegen.cpp:run@2371] SPIRV optimization failed`

Is it because the code I wrote is wrong ？ Or ti.kernel does not support simultaneous use rw_texture and ndarray？

Demo Code:

```
        import numpy as np
            import taichi as ti

    def test_texture_buf(arch):
        ti.init(arch=arch)
        width  = 1080
        height = 1920
        @ti.kernel
        def taichi_kernel_test(
        in_ten:ti.types.rw_texture(num_dimensions=2, fmt=ti.Format.rgba8, lod=0),
        out_ten: ti.types.rw_texture(num_dimensions=2, fmt=ti.Format.rgba8, lod=0),
        in_ten_buf: ti.types.ndarray(dtype=ti.u8, ndim=2),
        height: ti.i32,
        width: ti.i32,
        ):
        for i, j in ti.ndrange(height, width):
            in_num = in_ten.load(ti.Vector([j, i]))
            in_num.x = in_num.x + in_ten_buf[i, j]
            out_ten.store(ti.Vector([j, i]), in_num)

    arg_0 = ti.graph.Arg(tag=ti.graph.ArgKind.RWTEXTURE,
                         name="in_ten",
                         fmt=ti.Format.rgba8,
                         ndim=2)
    arg_1 = ti.graph.Arg(tag=ti.graph.ArgKind.RWTEXTURE,
                         name="out_ten",
                         fmt=ti.Format.rgba8,
                         ndim=2)
    arg_2  = ti.graph.Arg(ti.graph.ArgKind.NDARRAY, "in_ten_buf",  dtype=ti.u8, ndim=2)
    arg_3 = ti.graph.Arg(ti.graph.ArgKind.SCALAR, "height", ti.i32)
    arg_4 = ti.graph.Arg(ti.graph.ArgKind.SCALAR, "width", ti.i32)

    g = ti.graph.GraphBuilder()
    g.dispatch(taichi_kernel_test, arg_0, arg_1, arg_2, arg_3, arg_4)
    g = g.compile()

    # save
    m = ti.aot.Module(arch)
    m.add_graph("taichi_kernel_test", g)
    m.save("models_taichi_kernel_test")

    if __name__ == "__main__":
        test_texture_buf(ti.vulkan)
```

Taichi Version: v1.5.0

**Comment by bobcao3** [comment]
This is likely a bug
