### ISSUE TITLE
[AOT] no taichi_c_api.lib in taichi Windows c_api 

### ISSUE THREAD

**Issue by Xayah-Hina** [taichi-dev/taichi#7977]
I want to integrate taichi into a native C++ application. However, after `find_package(Taichi REQUIRED)` and `target_link_libraries(${EXAMPLE_NAME} PRIVATE Taichi::Runtime)`, there is a error:

```
ninja: error: 'C:/Users/Administrator/AppData/Local/Programs/Python/Python310/Lib/site-packages/taichi/_lib/c_api/lib/taichi_c_api.lib', needed by 'taichi/01-version/01-version.exe', missing and no known rule to make it
```

I check the directory `taichi/_lib/c_api/`, there is no `lib` dir. However, I test the same project in M1 MacOS, it works because macOS taichi build has this library.

I wonder if there is any solution for taichi windows AOT development? Thanks~ : )

**Comment by bobcao3** [comment]
It should be a dynamic library (DLL) instead of a static one.

**Comment by Xayah-Hina** [comment]
> It should be a dynamic library (DLL) instead of a static one.

Thanks for the reply~ I followed [TaichiAotByExamples](https://github.com/PENGUINLIONG/TaichiAotByExamples), and have set `-DTAICHI_C_API_INSTALL_DIR="C:/Users/Administrator/Desktop/taichi_c/taichi/_lib/c_api"` in Cmake, but still encountered the error showed below.
```
ninja: error: 'C:/Users/Administrator/AppData/Local/Programs/Python/Python310/Lib/site-packages/taichi/_lib/c_api/lib/taichi_c_api.lib', needed by 'taichi/01-version/01-version.exe', missing and no known rule to make it
```

I follow the same operations in macOS, and get the right result. So, how can I link the taichi_c_api.dll instead for Windows applications?

Thank you : )

**Comment by feisuzhu** [comment]
@Xayah-Hina I've fixed the build script to include import lib in Windows wheels, please try latest master.
