### ISSUE TITLE
method call error

### ISSUE THREAD

**Issue by DreadInside** [taichi-dev/taichi#8002]
(I use Google translate)
Hello, I am getting this error while importing taishi_hlsl.
P.S. I am not a programmer, I just wrote code according to the guide and ran into an error.
In my opinion, this does not look like what could have happened on my part, but I may be wrong.
Sorry if this is the case, I tried to find the root of the problem, but python doesn't report enough information,
so I can't find the file where Matrix is ​​originally declared to check its attributes

pygame 2.4.0 (SDL 2.26.4, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
[Taichi] version 1.6.0, llvm 15.0.1, commit f1c6fbbd, win, python 3.11.2
[TaiGLSL] version 0.0.12
Traceback (most recent call last):
  File "E:\Username\Crea\Programming\python\projects\tunel_shader\main.py", line 4, in <module>
    import taichi_glsl
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\taichi_glsl\__init__.py", line 10, in <module>
    from .hack import *
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\site-packages\taichi_glsl\hack.py", line 11, in <module>
    _old_element_wise_binary = ti.Matrix._element_wise_binary
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Matrix' has no attribute '_element_wise_binary'

**Comment by bobcao3** [comment]
We no longer support Taichi GLSL

**Comment by DreadInside** [comment]
Then is there any information anywhere what the latest version of taichi works with taich_GLSL?

**Comment by neozhaoliang** [comment]
@DreadInside Hi, taichi_glsl is now a deprecated package; all its functionalities are moved to the `taichi.math` submodule:
`https://docs.taichi-lang.org/api/taichi/math/`.
