### ISSUE TITLE
you can try "ti ticache clean" but ticache is not a valid command

### ISSUE THREAD

**Issue by Nanase-Nishino** [taichi-dev/taichi#8015]
taichi 1.5 
report a warnning and you can try "ti ticache clean -p {dir}"
but it should be "ti cache clean"

**Comment by ailzhang** [comment]
@Nanase-Nishino Nice catch! would you mind sending a quick fix for it? Thanks!

**Comment by Nanase-Nishino** [comment]
> @Nanase-Nishino Nice catch! would you mind sending a quick fix for it? Thanks!

Of course! I will send a pr about this issue.
