### ISSUE TITLE
[misc] imread bug, snowing image

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#802]
**Describe the bug**
imread cannot read jpg/png properly that are not generated by imwrite.

**Log/Screenshots**

![Screenshot_20200423_230620](https://user-images.githubusercontent.com/20640597/80115259-1ec5a480-85b7-11ea-818e-85a1be9c1dee.png)

**To Reproduce**

```py
import taichi as ti
img = ti.imread('misc/logo.png')
ti.imshow(img)
```

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**

**Comment by archibate** [comment]
Maybe we want to share the same as `gui.show(f'{frame}.png')`?

**Comment by yuanming-hu** [comment]
Could you add more details here? Again, the issue description needs a lot more work. Please first fix the issue description. Thanks.

**Comment by archibate** [comment]
Found problem! It's axis flip!
