### ISSUE TITLE
[bug] llvm ICmpInst assert fail when using if statement with non 32bit int value

### ISSUE THREAD

**Issue by Dinngger** [taichi-dev/taichi#8024]
**Describe the bug**
llvm ICmpInst assert fail when using if statement with non 32bit value.

**To Reproduce**

```py
import taichi as ti

ti.init(arch=ti.gpu)

@ti.kernel
def my_test(x: ti.u8): # any non 32bit int type.
    if x:
        print(1)

my_test(1)
```

**Log/Screenshots**

```
$ python3 ti_icmp.py 
[Taichi] version 1.6.0, llvm 15.0.4, commit f1c6fbbd, linux, python 3.8.10
[Taichi] Starting on arch=cuda
python3: /home/dev/.cache/ti-build-cache/llvm15/include/llvm/IR/Instructions.h:1191: void llvm::ICmpInst::AssertOK(): Assertion `getOperand(0)->getType() == getOperand(1)->getType() && "Both operands to ICmp instruction are not of the same type!"' failed.
Aborted (core dumped)
```

**Additional comments**
Both cpu and cuda backend raise this error. Vunkan works will with this kernel.

**Comment by lin-hitonami** [comment]
It seems that this bug is already fixed in the latest master. You can install the nightly build (by `pip install -i https://pypi.taichi.graphics/simple/ taichi-nightly`) or wait for the next release. If the problem persists even after installing the nightly build, please contact us again.
