### ISSUE TITLE
[CUDA on Windows] slim_libdevice not found

### ISSUE THREAD

**Issue by Kugelstadt** [taichi-dev/taichi#807]
When I use the CUDA backend on Windows 10 I get the following error message when I run any of the examples:

[Taichi] mode=release
[Taichi] version 0.5.12, supported archs: [cpu, cuda], commit f0d6bd70, python 3.7.6
[E 04/17/20 09:20:48.290] [llvm_context.cpp:taichi::lang::module_from_bitcode_file@178] Bitcode file (C:\anaconda3\lib\site-packages\taichi\core\../lib/slim_libdevice.10.bc) not found.

The taichi/lib floder does not contain a file slim_libdevice.10.bc

**Comment by archibate** [comment]
Me too. Although I didn't installed CUDA at all, it shows `supported archs: [cpu, cuda]`.
I thought we will fallback to cpu when libcuda not found? @yuanming-hu

**Comment by e493956170** [comment]
same problem in anaconda. Is there a solution?

**Comment by e493956170** [comment]
it seems you should download the file to this path "Anaconda3\Lib\site-packages\taichi\lib" manually.
This file can be found in "taichi/external/cuda_libdevice/".

Problem solved for me anyway.

.

**Comment by yuanming-hu** [comment]
@Kugelstadt @e493956170 Thanks for reporting this. I just now released v0.5.14 - could you try this version and let me know if this issue is fixed on your ends?

**Comment by Kugelstadt** [comment]
@yuanming-hu Yes it works. Thank you very much.
