### ISSUE TITLE
The same program can run on taichi1.5.0, but will report error on 1.6.0

### ISSUE THREAD

**Issue by Tau1191** [taichi-dev/taichi#8078]
the error reported as follow
![e022d7217237f5c6b2e9d956738ad97](https://github.com/taichi-dev/taichi/assets/125369579/4a0aed6c-9e78-4fb3-80a2-5ecacf7fb734)

**Comment by Tau1191** [comment]
the windows system, win 10

**Comment by jim19930609** [comment]
Hi Tau1191, can you provide a minimal program to reproduce this issue? Thanks!

**Comment by Tau1191** [comment]
https://github.com/Tau1191/Taichi_Question.git
thanks for your effort.
looking forward your reply!

**Comment by Tau1191** [comment]
https://github.com/Tau1191/Taichi_Question.git
thanks for your effort.
looking forward your reply!

**Comment by jim19930609** [comment]
Modified the code a bit further, here's the minimal code to reproduce:

```
import taichi as ti
import numpy as np

ti.init(arch=ti.gpu)

vel = ti.Vector.field(2, dtype=ti.f64, shape=(100, 100))

@ti.func
def foo(i, j, l):
    tmp = 1.0 / vel[i, j][l]
    return tmp

@ti.kernel
def collide():
    tmp0 = foo(0, 0, 0)
    print(tmp0)

collide()
```
