### ISSUE TITLE
Print the IR after every sub-pass of the full-simplify pass

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#8112]
**Concisely describe the proposed feature**
Currently we don't print the IR after every sub-pass of the full-simplify pass because it will be too long. However, I sometimes need them when debugging. So maybe we can add a new flag in the CompileConfig to print them.

**Comment by ailzhang** [comment]
Since `print_ir` is mainly for developers I guess it might be okay to just dump every sub-pass as well. One nit is the parallel compilation sometimes interferes the order of outputted IR that makes it harder to read so devs need to change number of compilation workers as well :D

**Comment by lin-hitonami** [comment]
> One nit is the parallel compilation sometimes interferes the order of outputted IR that makes it harder to read so devs need to change number of compilation workers as well :D
How about setting compilation workers to 1 when `print_ir=True` is enabled?

**Comment by ailzhang** [comment]
@lin-hitonami Yep that works too!
