### ISSUE TITLE
Add `ndim` attribute for `field` and `ndarray`

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#8202]
Can we add a `ndim` attribute for `field` and `ndarray` like [numpy.ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ndim.html)?

For example:

```python
x = ti.field(int, shape=(1, 2, 3, 4))
y = ti.ndarray(int, shape=(1, 2, 3, 4))

x.ndim  # 4
y.ndim  # 4
```

**Comment by ailzhang** [comment]
SG! This can be simply the length of `shape` I think.

**Comment by ailzhang** [comment]
@neozhaoliang would you mind sending a PR when you have time? Thanks!
