### ISSUE TITLE
Error in code optimization for print

### ISSUE THREAD

**Issue by listerily** [taichi-dev/taichi#8224]
**Describe the bug**
During multiple kernel calls, the value of an element in a ndarray might change. However we embedded its value in the IR, making print statement printed the wrong value.

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
import taichi as ti
import numpy as np

ti.init(arch=ti.cpu)

arr_ = np.zeros(shape=(10,), dtype=float)


@ti.kernel
def test(arr: ti.types.ndarray_type.ndarray()):
    print(arr_[2])


arr_[2] = 1.14
test(arr_)
arr_[2] = 5.14
test(arr_)

```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
[Taichi] version 1.7.0, llvm 15.0.4, commit 47d5b137, linux, python 3.8.10
[Taichi] Starting on arch=x64
1.140000
1.140000
```

**Additional comments**
This is because the value of `arr[2]` is unexpectedly embedded into ir. Optimized ir output:
```
kernel {
  $0 = offloaded  
  body {
    <f32> $1 = const 1.14
    print $1, "\n"
  }
}
```

**Comment by lin-hitonami** [comment]
We only support using ndarrays that are passed into the kernel as arguments, so you can't use `arr_` in the taichi kernel which is a global variable outside the kernel.
