### ISSUE TITLE
how can access taichi aot kernel return value?

### ISSUE THREAD

**Issue by lgyStoic** [taichi-dev/taichi#8239]
like this
```
@ti.kernel
def reduce_sum_kernel(f: ti.types.ndarray(dtype=ti.f32, ndim=1))->ti.f32:
    sum = 0.0
    for i in f:
        sum += f[i]
    return sum
```
the simple reduce_sum code , which must have an return value, 
but I search the document ,cannot find an API to get the return value after aot launch...

Is there a way to get the return value ? only can use an ti.Ndarray passed by reference?  it's not convenience

**Comment by ailzhang** [comment]
@lgyStoic We didn't mention this in the doc since retrieving return value to host requires a hard sync and may hit performance (sometimes unnecessarily). But if you're fine with the sync cost, here's an example of getting the return value https://github.com/taichi-dev/taichi/blob/d666e7f9a877145ad0bd0732760b662138179c4a/tests/cpp/aot/llvm/kernel_return_aot_test.cpp#L31

**Comment by lgyStoic** [comment]
> @lgyStoic We didn't mention this in the doc since retrieving return value to host requires a hard sync and may hit performance (sometimes unnecessarily). But if you're fine with the sync cost, here's an example of getting the return value
> 
> https://github.com/taichi-dev/taichi/blob/d666e7f9a877145ad0bd0732760b662138179c4a/tests/cpp/aot/llvm/kernel_return_aot_test.cpp#L31

It's ok, I need access the result for check if correct, and I count time after  runtime->wait, it's accurate, right?

**Comment by ailzhang** [comment]
@lgyStoic Yup!

**Comment by lgyStoic** [comment]
> @lgyStoic Yup!

I checked the code, but found this return value can only get by using LaunchContextBuilder class, but to taichi_c_api, the file header is not public,  context cannot directly access by user's code, Is there another convinence way to let this reduce demo work?
I think there maybe an solution, I can sum up all value to first element of ti.Ndarray, and access this first element when kernel launch finish. But I don't know ,this method will harmful to performence of not ?
```
@ti.kernel
def reduce_sum_kernel(f: ti.types.ndarray(dtype=ti.f32, ndim=1)):
    sum = 0.0
    for i in f:
        sum += f[i]
    f[0] = sum
```

**Comment by ailzhang** [comment]
@lgyStoic No it's not exposed via taichi c api but your workaround is the recommended way to do it. Ndarray is supposed to be the container for exchanging data between host and taichi kernels.
