### ISSUE TITLE
ti.ui.Scene render individual triangles instead of a mesh

### ISSUE THREAD

**Issue by kurt-rhee** [taichi-dev/taichi#8247]
**Concisely describe the proposed feature**
I have a set of polygons which represents solar panels which are being rotated in 3D space.  Currently in order to render these polygons I need to convert them to individual meshes and then add thousands of meshes to my scene.  I would like to instead have the ability to render many individual triangles.

**Describe the solution you'd like (if any)**
I like the way that many particles can be added to a scene at once using scene.particles.  I would like if we had a similar functionality for scene.triangles

**Additional comments**
Thank you very much for your help and consideration!

**Comment by bobcao3** [comment]
You can add them as a big single mesh or use the instanced mesh feature

**Comment by kurt-rhee** [comment]
Thanks for your answer @bobcao3, I might not totally understand how meshes work.  I don't think I can add them as a single big mesh since each polygon is one mesh made up two triangles and every polygon is spatially disjoint from every other polygon.

As for instanced mesh, i found this in the documentation:  https://docs.taichi-lang.org/api/taichi/#taichi.MeshInstance.  Is there anything else I can use to attempt to understand how to use it?

Thank you!

**Comment by bobcao3** [comment]
> Thanks for your answer @bobcao3, I might not totally understand how meshes work.  I don't think I can add them as a single big mesh since each polygon is one mesh made up two triangles and every polygon is spatially disjoint from every other polygon.
> 
> As for instanced mesh, i found this in the documentation:  https://docs.taichi-lang.org/api/taichi/#taichi.MeshInstance.  Is there anything else I can use to attempt to understand how to use it?
> 
> Thank you!

There's no constraint that a mesh needs to be connected. A mesh is just a list of triangles, they can be wherever with whatever connectivity you wish

**Comment by kurt-rhee** [comment]
Oh wow thank you for that information I didn't know that.  I will give this a try.  Is there a way to specify the connectivity within Scene.mesh?

**Comment by kurt-rhee** [comment]
Hello, that was very very helpful.  I believe I have this almost working.  Below is a picture where I am attempting to draw all of my polygon as a series of triangles in a mesh.  In order to keep it simple I have limited the indices to just two polygons.  (aka four triangles comprised of 8 unique vertices and 12 indices.)

![image](https://github.com/taichi-dev/taichi/assets/33131958/a5edbe09-5064-4ebd-be8c-214deb847029) 

I think that the mesh is attempting to connect all of the vertices, is it possible to specify to the mesh which vertices are connect into triangles and which ones are not?

![image](https://github.com/taichi-dev/taichi/assets/33131958/beaf2ded-a10f-4557-92ca-4ce3ad357d3d)

**Comment by bobcao3** [comment]
do you have the camera setup? You need to have the `ti.ui.Camera` setup and pointing at the mesh

**Comment by kurt-rhee** [comment]
Yes I have the camera setup and pointing at the mesh, the grey rectangular blob pictured in the comment above is what is being rendered instead of the triangle.

Interestingly, if I only render one triangle (vertices.shape[0] == 3) and (indices.shape[0] == 3) the triangle renders correctly.  If I have multiple triangles, I get the blob shapes instead.

I also get the blob shape if I define all of my vertices, but only have 3 indices defined to the mesh.  This makes me think that perhaps I am not defining my indices or vertices correctly, but I am not sure what I am doing incorrectly.

**Comment by kurt-rhee** [comment]
This is working!  It turns out I mis-ordered the vertices in my taichi field

![image](https://github.com/taichi-dev/taichi/assets/33131958/c0b27840-5c0c-4b68-8a3e-fd612e47372b)
