### ISSUE TITLE
Taichi aot vulkan cannot support Ndarray with  u8 type

### ISSUE THREAD

**Issue by lgyStoic** [taichi-dev/taichi#8253]
I  want to do some image process project with taichi aot, and deploy to mobile devices.,
But I encounter a problem,  whichi is vulkan cannot support u8 type, but most image is CV8U type..
![image](https://github.com/taichi-dev/taichi/assets/4526646/f6a8b75c-c758-444d-80a1-d56181e99997)

So I want to ask, if  Taichi will support vulkan u8 type or not in the future?
If not support, how to avoid the type cast in real project..

**Comment by bobcao3** [comment]
Hi, what's your GPU currently? The vulkan backend supports u8 if your GPU supports it (unless this is disabled for AOT? @PENGUINLIONG  for confirmation).

Before that, for images, if it's rgba8u you can just reinterpret it as an u32 array, which each u32 value encodes a color

**Comment by PENGUINLIONG** [comment]
It's by default off for AOT. With the old interface you need to declare `ti.DeviceCapability.spirv_with_int8` in `ti.Module`'s `caps` param. For `ti build` you need to declare a global variable called `
REQUIRED_CAPS
` for that.

**Comment by lgyStoic** [comment]
> It's by default off for AOT. With the old interface you need to declare `ti.DeviceCapability.spirv_with_int8` in `ti.Module`'s `caps` param. For `ti build` you need to declare a global variable called `REQUIRED_CAPS` for that.

u32. for rgbu8 image is a good idea!
