### ISSUE TITLE
[Lang] `x and y` no evaluate `y` if `x == 0`

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#832]
**Concisely describe the proposed feature**

In `ti.logical_and(lhs, rhs)`, don't evaluate `rhs` if we found `lhs is False`. (逻辑短路, such feature also exists in python and c++)

**Describe the solution you'd like (if any)**

**Additional comments**
```py
import taichi as ti
ti.init()

x = ti.var(ti.i32, ())

@ti.func
def hello():
    print(233)
    return 666

@ti.kernel
def kern():
    x[None] = x[None] and hello()

x[None] = 0
kern()
```
obtains:
```
[debug] 233 = 233
```
what we want is:
```
(no output)
```

**Comment by yuanming-hu** [comment]
Thanks, but at a high level we probably should not do shortcut here. In high-performance computing, people would rather have a predictable instruction flow, especially on out-of-order processors.
