### ISSUE TITLE
[Been solved] When using the sparse solver to solve linear equation **Ax=b**, if the b is float64, the result x is not correct

### ISSUE THREAD

**Issue by dj199187** [taichi-dev/taichi#8328]
**Describe the bug**
When using the sparse solver to solve linear equation **Ax=b**, if the b is float64, the solving result **x** is not correct, no matter using CPU or GPU backend.

**To Reproduce**
import taichi as ti

ti.init(arch=ti.cpu, default_fp=ti.f32)  # In taichi v1.6, gpu computing only support f32
n = 4
K = ti.linalg.SparseMatrixBuilder(n, n, max_num_triplets=100)
b = ti.ndarray(ti.f64, shape=n)   # b should be ti.f32, otherwise, the x solved from Ax=b is not correct 

@ti.kernel
def fill(A: ti.types.sparse_matrix_builder(), b: ti.types.ndarray(), interval: ti.i32):
    for i in range(n):
        A[i, i] += 2.0
        if i % interval == 0:
            b[i] += 1.0

fill(K, b, 3)
A = K.build()
solver = ti.linalg.SparseSolver(solver_type="LLT")
solver.analyze_pattern(A)
solver.factorize(A)
x = solver.solve(b)
isSuccess = solver.info()
print(">>>> Solve sparse linear systems Ax = b with the solution x:")
print(x.to_numpy())
print(f">>>> Computation was successful?: {isSuccess}")
# outputs:
# >>>> Solve sparse linear systems Ax = b with the solution x:
# [0.00390625   0.         0.         0.        ]
# The correct x should be:
# [0.5 0.  0.  0.5]
# >>>> Computation was successful?: True

```py
# sample code here
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
$ python my_sample_code.py
[Taichi] mode=release
[Taichi] version 0.6.29, llvm 10.0.0, commit b63f6663, linux, python 3.8.3
...
```

**Additional comments**
If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by houkensjtu** [comment]
Hello @dj199187 ! 
1. First, I'd like to point out that the data type of `SparseMatrix` and `ndarray` should always match, so avoid mixing `ti.f32` and `ti.f64` together in one computation. 
2. Next, the reason why you're getting an incorrect result when switch `b` to ti.f64 is that we need to specify the data type of the `SparseSolver`:
```
solver = ti.linalg.SparseSolver(solver_type="LLT", dtype=ti.f64)
```
On my machine, this yields the correct answer [0.5 0 0 0.5]. Again, all data type should match in the whole computation.

And it's true that we should have mentioned this detail in our documentation. Thank you for your valuable feedback!

**Comment by dj199187** [comment]
Thanks for your answer @houkensjtu.
Following your suggestion, I modified the code as:
(1) Uniformed the data type as ti.f64 in the whole program  
(2) Specified the data type of the SpaeseSolver as ti.f64
But the problem sitll remains on my machine. I also tried the other factrorization method like "LU", and doesn't work either.

Could you please have a further check on the following code:
`import taichi as ti

ti.init(arch=ti.cpu, default_fp=ti.f64)  # In taichi v1.6, gpu computing only support f32
n = 4
K = ti.linalg.SparseMatrixBuilder(n, n, max_num_triplets=100)
b = ti.ndarray(ti.f64, shape=n)   # b should be ti.f32, otherwise, the x solved from Ax=b is not correct


@ti.kernel
def fill(A: ti.types.sparse_matrix_builder(), b: ti.types.ndarray(), interval: ti.i32):
    for i in range(n):
        A[i, i] += 2.0
        if i % interval == 0:
            b[i] += 1.0


fill(K, b, 3)
A = K.build()
solver = ti.linalg.SparseSolver(solver_type="LLT", dtype=ti.f64)
solver.analyze_pattern(A)
solver.factorize(A)
x = solver.solve(b)
isSuccess = solver.info()
print(">>>> Solve sparse linear systems Ax = b with the solution x:")
print(x.to_numpy())
print(f">>>> Computation was successful?: {isSuccess}")
# outputs:
# >>>> Solve sparse linear systems Ax = b with the solution x:
# [0.     0.         0.         0.        ]
# The correct x should be:
# [0.5 0.  0.  0.5]
# >>>> Computation was successful?: True
`

**Comment by houkensjtu** [comment]
Sorry for my incomplete answer. You also need to specify the data type of SparseMatrix itself:
```
K = ti.linalg.SparseMatrixBuilder(n, n, max_num_triplets=100, dtype=ti.f64)
```
This should solve the problem. Please let me know if the issue persists. Thanks!

**Comment by houkensjtu** [comment]
Feel free to ask if you have any further questions! Closing this thread for now.
