### ISSUE TITLE
Support calling a kernel function from another kernel function

### ISSUE THREAD

**Issue by mutexstream** [taichi-dev/taichi#8332]
**Concisely describe the proposed feature**
A clear and concise description of what you want. For example,
> I would like taichi to support calling a kernel function from another kernel function. Not being able to call kernel functions from another kernel limits the ability to use taichi to build libraries. Since the library caller can invoke library functions which may be kernels.

**Comment by lin-hitonami** [comment]
We do not support it currently. You can only call `ti.func` inside `ti.kernel`.
