### ISSUE TITLE
Importing Taichi without stdout output

### ISSUE THREAD

**Issue by rmmr** [taichi-dev/taichi#8334]
Importing taichi as follows

```
import taichi as ti
```

the stdout receives `[Taichi] version 1.6.0, llvm 15.0.4, commit f1c6fbbd, linux, python 3.10.12`

I tried to wrap the import as follows:

```
with open(os.devnull, "w") as devnull:
    with contextlib.redirect_stdout(devnull):
        import taichi as ti
```

Then the stdout receives `[I 08/26/23 11:30:47.825 17489] [shell.py:_shell_pop_print@23] Graphical python shell detected, using wrapped sys.stdout`

Is there any way to prevent this?

**Comment by lin-hitonami** [comment]
We do not have a flag to disable it now. However you can delete this line in your Taichi package, then it won't print the header.

https://github.com/taichi-dev/taichi/blob/aa0619fb1a27edb93a22a449f7ec3ced6864e070/python/taichi/_lib/utils.py#L172
