### ISSUE TITLE
Is it possible to do Linked Lists in Taichi with garbage collection?

### ISSUE THREAD

**Issue by kurt-rhee** [taichi-dev/taichi#8359]
My linked list implementation must be garage collected.

- Searching Google
I found the following article which refers to dynamic snodes, but my understanding is that fields/snodes are not garbage collected.
https://docs.taichi-lang.org/blog/acclerate-collision-detection-with-taichi

- Searching [existing issues](https://github.com/taichi-dev/taichi/issues)
I could not find any examples of linked lists
![image](https://github.com/taichi-dev/taichi/assets/33131958/4ca0c2b6-0da4-4222-aaf1-b10cfd655026)

- Searching [Taichi Doc](https://docs.taichi-lang.org/)
Same as google search

- Searching [Taichi Forum](https://forum.taichi.graphics/)
No results found for "Linked List" in forum.

**Comment by jim19930609** [comment]
Hi @kurt-rhee, I don't think there's internal support for linked lists in Taichi. The closest I can think of is to fake one with SnodeTree like `ti.root.dense().dense().dense()`. But as you mentioned, it doesn't support customized GC at all.

**Comment by kurt-rhee** [comment]
Understood thank you!
