### ISSUE TITLE
module 'taichi' has no attribute 'VideoManager'

### ISSUE THREAD

**Issue by WenzhiShao** [taichi-dev/taichi#8370]
coed:
videoManager = ti.VideoManager(output_dir="./video", framerate=24, automatic_build=False) # got error
gui = ti.GUI(background_color=0x222222)
colors = [0xFF0000, 0x00FFFF, 0x0000FF, 0xFFFF00, 0xFF00FF, 0x00FF00]

#note 
already searched in Google and issues

怀疑是接口变了，如果可以请告诉我新版本的接口

**Comment by jim19930609** [comment]
Let me check v1.6.0's release note

**Comment by lin-hitonami** [comment]
It has changed to `ti.tools.VideoManager` according to [v1.6.0's release note](https://github.com/taichi-dev/taichi/releases/tag/v1.6.0).
