### ISSUE TITLE
Enhance `ti.init(arch=...)` and add `ti.gpu`

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#840]
**Concisely describe the proposed feature**
We should let the `arch` argument of `ti.init` take a list of archs, e.g. `[ti.cuda, ti.x64]`, and then pick the first supported arch in the list. If nothing is supported in the list, we print a warning message and use `host_arch`.

**Describe the solution you'd like (if any)**
Simply modify the logic in `ti.init`.

**Additional comments**
With this feature, we can define `ti.gpu = [ti.cuda, ti.metal, ti.opengl]` so that the new Metal and OpenGL backend will be used automatically in the examples, after changing `ti.init(arch=ti.cuda)` to `ti.init(arch=ti.gpu)`.

**Comment by archibate** [comment]
Nice, with this, non-cuda users will experience our opengl backend! I wish we could getting a lot of feedbacks!

**Comment by archibate** [comment]
Done in #843
