### ISSUE TITLE
Vector + Vector = Matrix?

### ISSUE THREAD

**Issue by ringohoffman** [taichi-dev/taichi#8411]
**Describe the bug**
`Matrix` operations from `taichi.lang.ops` (like `__add__`) only return `Matrix`, even for `Vector` results.

It is bc of these lines in [`_unary_operation`](https://github.com/taichi-dev/taichi/blob/bcd623fddccde980a01c2a9bb4facb56862cc26e/python/taichi/lang/ops.py#L120), [`_binary_operation`](https://github.com/taichi-dev/taichi/blob/bcd623fddccde980a01c2a9bb4facb56862cc26e/python/taichi/lang/ops.py#L133), and [`_ternary_operation`](https://github.com/taichi-dev/taichi/blob/bcd623fddccde980a01c2a9bb4facb56862cc26e/python/taichi/lang/ops.py#L146).

[`__matmul__` will return a `Vector` if `len(shape) == 1`](https://github.com/taichi-dev/taichi/blob/bcd623fddccde980a01c2a9bb4facb56862cc26e/python/taichi/lang/matrix_ops.py#L269-L271). Can we do something similar for these? It could be like

```python
result = python_op(...)
return Vector(result) if len(result.shape) == 1 else Matrix(result)
```

**To Reproduce**

```py
import taichi.math

v = taichi.math.vec3(1)
type(v + v)  # taichi.lang.matrix.Matrix
```

**Comment by lin-hitonami** [comment]
`Vector` is a derived class of `Matrix`, with `ndim` set to `1`. As long as `ndim` is set to 1, it is treated as a vector regardless of whether its class is `Vector` or `Matrix`. This is due to the refactoring of the Vector and Matrix class, but you can ignore this because it doesn't affect anything.

**Comment by bobcao3** [comment]
so... not a bug?
