### ISSUE TITLE
Macosx High Power Occupancy

### ISSUE THREAD

**Issue by KarryCharon** [taichi-dev/taichi#8434]
**Describe the bug**
Run example script cause high power occupy, even if python exited

**Log/Screenshots**
<img width="2052" alt="image" src="https://github.com/taichi-dev/taichi/assets/49889381/23141824-cfaf-4005-8677-c94d51e10710">

```
$ python some_example_like_mpm.py
[Taichi] version 1.7.0, llvm 15.0.7, commit 2fd24490, osx, python 3.10.8
[Taichi] Starting on arch=metal
```

**Comment by bobcao3** [comment]
I don't think this is something we can do anything about... It's probably just macos bumping up the power state after running GPU workloads
