### ISSUE TITLE
[Bug] [Sparse] Particles disappear in `example/particle_renderer.py`

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#847]
**Describe the bug**
Particles disappear in `example/particle_renderer.py`

**Log/Screenshots**
![Screenshot from 2020-04-22 15-18-06](https://user-images.githubusercontent.com/6553256/80024078-83480d00-84ac-11ea-9e15-584af69eb462.png)

**To Reproduce**
Checkout c4e5b694 (v0.5.13) and run `example/particle_renderer.py`
b9b9e484 works well (v0.5.12)

![Screenshot from 2020-04-22 16-14-17](https://user-images.githubusercontent.com/6553256/80029169-5f88c500-84b4-11ea-81d7-a9aaa86abc53.png)

**Narrowing down**
588e504b correctly renders the particles, but 5fd30e61cbe482483925cb73c5c3b2109540d76f does not.

**Comment by yuanming-hu** [comment]
@xumingkuan I did a binary search manually through the git history. It seems to me that something in 5fd30e61cbe482483925cb73c5c3b2109540d76f changed the renderer behavior. Could you take a closer look? Thank you in advance!

**Comment by xumingkuan** [comment]
I just found that https://github.com/taichi-dev/taichi/commit/5fd30e61cbe482483925cb73c5c3b2109540d76f causes IRPrinter to crash if I set `print_ir=True`... So there must be malformed IRs. I will fix it this evening.

**Comment by xumingkuan** [comment]
Interestingly, IRPrinter doesn't crash in the current master.
