### ISSUE TITLE
get rid of unnecessary generate_commit_hash.py

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#856]
**Concisely describe the proposed feature**

Currently `generate_commit_hash.py` is called each build. Even if no source files changed, `make` still restarts and link `libtaichi_core.so` again.

**Describe the solution you'd like (if any)**
1. Make it only called for each `git commit`, if no change in commit hash detected, don't run  `generate_commit_hash.py`.
2. We can move it from C++ to Python. So that `libtaichi_core.so` don't need to rebuild to include that commit hash number.

**Additional comments**

**Comment by xumingkuan** [comment]
It's not unused -- whenever we `import taichi`, the commit hash is shown on the screen.

**Comment by archibate** [comment]
We only need run it one time per commit. Sometimes even if no file changed, it builds again.

**Comment by yuanming-hu** [comment]
Again, @archibate, please follow the community rule and clearly describe your issue. Remember that you are working in a **team**, and the lack of issue description has led to some misunderstanding here.

**Comment by yuanming-hu** [comment]
Thanks for clarifying. I would provide option 3 which might be easier:

3. In `generate_commit_hash.py`, read file `taichi/common/commit_hash.h` first and try to parse the commit hash. If the value is the same as the new git commit hash, do not write the file. If the file is not written, `make` will not relink.

**Comment by archibate** [comment]
> If the file is not written, `make` will not relink.

`ninja` did. Even if I delete the whole content of `get_commit_hash.py`.
```
(comic) [bate@archit taichi]$ nc
ninja: Entering directory `build'
[1/3] cd /tmp/taichi/build && python3 /home/bate/Develop/taichi/misc/generate_commit_hash.py
Building commit 3206dbd52d1d0a380e37a7d80a6ad852090fc71f
```
It already knows there are 3 targets to do. Oops.
