### ISSUE TITLE
[Metal][Discussion] Thoughts on how to support `dynamic` on Metal

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#860]
**Concisely describe the proposed feature**

I think @yuanming-hu and I have touched on this idea a few times now. There is a way to support the `dynamic` SNode, without introducing a whole memory allocator mechanism to the Metal backend. Of course this comes with the cost of a low and inefficient memory utilization.

**Describe the solution you'd like (if any)**

If we think of `dynamic` just as an interface, then it enables us to have different implement strategies, depending on whether the backend can easily support dynamic memory allocation.

At its core, `dynamic` can be viewed as a `dense` plus an atomic counter `next` to denote its current size:

* `append(x)`: `data[next] = x; ++next`
* `clear()`: `next = 0`

AFAICT, dynamic memory allocation makes this structure more memory efficient, but it doesn't bring new functionalities.

If we shift the responsibility to the users for deciding the upper bound of the number of elements per `dynamic` SNode, then Metal backend could just pre-allocate the upper bound amount of memory. We can use the existing sparsity Runtime infra (which supports `bitmasked`) to generate the active elements for `dynamic` as well.

**Additional comments**

If I am able to find out a way to implement locking on Metal, maybe I can also add the entire memory allocation + GC mechanism as well. However, from what we've found in #710, supporting that isn't a trivial thing...

**Comment by yuanming-hu** [comment]
I agree that if we set an upper bound onf the length of each `dynamic` node, then implementing it will be way easier than what the LLVM backend does. The LLVM backend dynamically allocates trunks (e.g. 256) of elements in the form of a linked list.

**Comment by archibate** [comment]
Implement `dynamic` SNode without runtime memory allocation? This may also apply to OpenGL!
Why is the approach inefficient? If I understanding correct, this may due to the memory layout:
```
| Dense | D     y      n       a       m      i      c | Dense | D     y      n       a       m      i      c | Dense |
```
breaking the memory locality?
What about:
```
| Dense | D     y      n | Dense | D     y | Dense |        a       m      i      c | n      a      m |
```
?
I.e. Append on require, not have to be contigious.
What do you think?

**Comment by k-ye** [comment]
> Why is the approach inefficient?

It is **memory** inefficient, because we need to pre-allocate the max size, instead of allocating a small one first, then gradually allocating more and more.

> What do you think?

It seems that you are allocating `Dense` at runtime? That might invalidate a lot of the SNode hierarchy computations at compilation.

What I mean:

```
| Dense | D   y   n   *   *   *   * |
                      ^-- next = 3

append('a')
append('m')

| Dense | D   y   n   a   m   *   * |
                              ^-- next = 5

clear()

| Dense | *   *   *   *   *   *   * |
          ^-- next = 0

```
