### ISSUE TITLE
module 'taichi' has no attribute 'gpu'

### ISSUE THREAD

**Issue by GeoffreyPlitt** [taichi-dev/taichi#865]
Running on Mac 10.15.4 / Python 3.7.7
19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

```
fractal.py 
[Taichi] mode=release
[Taichi] version 0.5.14, supported archs: [cpu, metal], commit 9a3bb30b, python 3.7.7
Traceback (most recent call last):
  File "fractal.py", line 3, in <module>
    ti.init(arch=ti.gpu)
AttributeError: module 'taichi' has no attribute 'gpu'
```

How do I troubleshoot this?

**Comment by archibate** [comment]
For now please use `ti.cuda` instead of `ti.gpu`.
Sorry for the confuse! We added `ti.gpu` feature recently. And updated documentions for that usage, however, we haven't releases that yet.
@yuanming-hu Maybe we should update `readthedocs` only after release? So that users won't get confused by not-released-yet features.

**Comment by GeoffreyPlitt** [comment]
Do you guys have a stable branch that excludes unreleased features?

**Comment by archibate** [comment]
No, we don't have a stable branch yet. Thanks for the idea! Currently `master` serves as the developing branch. And we use tags for stable release instead.

My suggestions:
1. Create a `stable` branch.
2. Contributor PRs compares from `contributor:patch-xxx` to `master`, squash before merge.
3. When release, make a PR compares from `master` to `stable`, squash before merge.
4. And the `stable` commit history should looks like:
```
[release] v0.5.15 (#1002)
[release] v0.5.14 (#1001)
[release] v0.5.13 (#1000)
...
```
Should be helpful when tracking bugs. What do you think?

**Comment by GeoffreyPlitt** [comment]
Sounds great
