### ISSUE TITLE
[example] Bugs in `pbf2d.py` example

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#872]
**Describe the bug**

There are a few bugs I'm aware of about the `pbf2d.py` example

* [x] It crashes on Metal because the particles initialization used `double` instead of `float32`
* [ ] IIRC, on my old MBP, drawing the rectangle boundary would crash

https://github.com/taichi-dev/taichi/blob/d7b9c4d083ad972c62f02ff6a08356ca60161f9c/examples/pbf2d.py#L289-L291

I also remember that someone complained about another place of crashing, but we never dug into it. Please feel free to post it here if you encounter it next time.

**Comment by xumingkuan** [comment]
I think #558 should have fixed a bug about boundaries. Are we still drawing anything out of bound?

**Comment by k-ye** [comment]
Thanks! Sorry for the confusion, but it wasn't the canvas boundary I was referring to, but this drawing call:

https://github.com/taichi-dev/taichi/blob/d7b9c4d083ad972c62f02ff6a08356ca60161f9c/examples/pbf2d.py#L289-L291

IIRC, I saw this crashed on my MBP 2015 model..
