### ISSUE TITLE
[Bug] Python scope access not working in debug mode

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#886]
**Describe the bug**
Python scope accessors are returning 0 when debug mode is turned on. Work fine when debug is off though. Im pretty sure this bug popped up today. 

**To Reproduce**
``` python

import taichi as ti
ti.init(arch=ti.x64, debug=True)

x = ti.var(ti.f32, shape=())

x[None] = 10.0
assert x[None]==10.0
```

**Comment by yuanming-hu** [comment]
Thanks for pointing this out. I know what's wrong - fixing...
