### ISSUE TITLE
[ir] spererate `UnaryOpType::cast` into `cast_value` and `cast_bits`

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#889]
**Concisely describe the proposed feature**
I'd like to spererate `UnaryOpType::cast` into two type: `cast_value` and `cast_bits`, so that no `cast_by_value` entry required and simplify codegen logic.

**Describe the solution you'd like (if any)**
Simply rename them, and tweak logic in the backend codegens, jit evaluators, etc. to simpler.

**Additional comments**
Helps logic simplification for `JITEvaluatorId` in #839.

**Comment by yuanming-hu** [comment]
Good point - I think this is an improved design. Please go ahead :-)

We may also need to add a `bool UnaryOpStmt::is_cast() const` helper.

Thanks.
