### ISSUE TITLE
[misc] Fractal code in readme should be updated

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#893]
Now we use `ti.gpu` instead of `ti.cuda`, so https://github.com/yuanming-hu/public_files/blob/master/graphics/taichi/fractal_code.png should be updated like
https://github.com/taichi-dev/taichi/blob/cecb7ca43a52e4b5826d86e991c10dc6117aac2c/examples/fractal.py#L3

**Comment by yuanming-hu** [comment]
Thanks! Now it's updated.
