### ISSUE TITLE
Squash `clear_list` calls into one kernel?

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#915]
**Concisely describe the proposed feature**

Right now, before launching a kernel that iterates over a sparse tensor, Taichi will generate a series of 

```cpp
clear_list(s1);
element_listgen(s1);
clear_list(s2);
element_listgen(s2);
...
```

@yuanming-hu  I think we can have a single kernel for all the `clear_list()` calls along the tree?

This idea came from #896 , where the user has noticed a slower performance when using sparse tensors, due to the overhead. I don't think `clear_list()` is the major overhead here, but having as fewer kernels as possible might always be a good thing..

**Comment by yuanming-hu** [comment]
Let me tell you a secret: after #742 we will have kernel fusion and this can be done automatically :-)

**Comment by k-ye** [comment]
Haha great! 😆
