### ISSUE TITLE
[中文社区] TaichiCon: Taichi开发者线上技术交流会 (第零届)

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#929]
We are hosting an online event *TaichiCon* to share our development experiences. This time the event is in Chinese and we plan to host one in English as well very soon :-)

本次线上活动共4个演讲。每个演讲为10分钟展示和5分钟Q&A。一个小时的演讲部分结束后有自由讨论时间。

1. Taichi的过去，现在，和未来
摘要：简要介绍Taichi项目的历史、高层设计、简短的Taichi使用教程、社区现状和项目愿景。
讲者介绍：胡渊鸣 (github id: @yuanming-hu，知乎id：胡渊鸣)是麻省理工学院(MIT)计算机科学三年级博士生。研究方向是编译器和计算机图形学。爱好是写代码、摄影、吃火锅。家乡是世界美食之都江苏扬州。

2. Taichi中间表示(IR)上的全局优化
摘要：简要介绍全局优化与局部优化的区别、带来的性能提升，以及实现过程中遇到的一些困难。
讲者介绍：徐明宽 (github id: @xumingkuan )是清华大学交叉信息研究院的大三本科生。以前研究理论计算机科学，但在CCF大学生计算机系统与程序设计竞赛上获得冠军后发现自己可能更擅长这一方面。爱好是写代码、打游戏、看番。家乡是首都北京。以前拿过IOI金牌。

3. Taichi的Metal后端设计
摘要：介绍下如何从零上手，做成一个新的Metal后端；以及分享一些Metal后端的问题与可改进之处。
讲者介绍：匡冶（github id: @k-ye ，知乎：西半球饭桶 ），毕业于清华大学精仪系，并辅修计算机，现居东京。爱好是写代码与跑步。今年一月曾决心添加一项旅游，已泡汤。家乡同为北京。

4. Taichi的OpenGL后端设计
摘要：简要介绍OpenGL后端的设计思路，遇到的困难，解决方案与感想。以及一些关于开发者基础建设(infrastructure)和代码可维护性(maintainability)的思考。
讲者介绍：彭于斌 (github&shadertoy id: @archibate，知乎id: 幼儿园理化笙) 是<del>英国剑桥大学</del>上海建桥学院信息技术学院的一年级大学生。研究方向是计算机图形学和操作系统。爱好是v+音乐，坎巴拉太空计划。家乡是魔都上海。

**欢迎世界各地的开源爱好者们（计算机图形学、编译器、高性能计算等）参加！**

Zoom链接：https://mit.zoom.us/j/92580112198 (限员300人，请提前安装好Zoom)
 - 进入会议室后，请尽量备注姓名和公司名称，如 胡渊鸣（麻省理工学院）、张三（ABC公司）。
 - 进入活动请保持静音，如有问题欢迎在聊天区文字提出。
 - 本活动全程不开摄像头。

活动时间：

北京时间 5月17日周日 上午 10:00-11:00
东京时间 5月17日周日 上午 11:00-12:00
新西兰时间 5月17日周日 下午 15:00-16:00
美国东部时间 5月16日周六 晚上 10:00-11:00
美国西部时间 5月16日周六 晚上 7:00-8:00

(一小时正式活动结束后为自由讨论)

 广告：我们欢迎各位同学加入Taichi社区一起开发、学习、成长。给Taichi贡献的方式不一定是写代码
 - [翻译中文文档](https://github.com/taichi-dev/taichi-docs-zh-cn/issues)
 - 修正文档里面的Typo(请直接开PR)
 - 帮忙组织未来的TaichiCon (请给yuanming@mit.edu发邮件) 
 - 负责版本发布(请给yuanming@mit.edu发邮件)
 - 甚至点一下Star

都是对Taichi有意义的贡献。

@StephenArk30 @jackalcooper

-------------------------------------------------------------
Notes to speakers：
 - 本次活动主题比较轻松，所以讲者介绍不用特别严肃，这样能吸引到更多开发者来参加
 - Slides建议用英文（这样活动结束以后放在网上，不说中文的同学也可以看:-）
 - 演讲建议用中文
 - 4个演讲的顺序按照前端，中间表示，后端进行，这样逻辑连贯一些
 - 本草案接受各种建议，欢迎提出 :-)

**Comment by k-ye** [comment]
我感觉Metal和OpenGL的设计非常相似，而且OpenGL更广为人知一些。因此我想把我的主题改成“如何为Taichi添加一个新后端”，介绍下添加backends时需要考虑哪些东西？

**Comment by archibate** [comment]
Thank you! TBH I most infrastructures are copied from Metal at the first place.. But surely they are getting different over time, e.g. grid-stride-loop vs runtime-group-size-spec.

**Comment by yuanming-hu** [comment]
> 我感觉Metal和OpenGL的设计非常相似，而且OpenGL更广为人知一些。因此我想把我的主题改成“如何为Taichi添加一个新后端”，介绍下添加backends时需要考虑哪些东西？

可以呀！标题和内容本来就是自定义的，我只是给一个初始的proposal。后面我们还会有这样的活动（可能一个月、两个月一次？看看第一次效果再决定吧），所以也不一定要把一切在10分钟之内讲完，能把一个小主题讲清楚就很好。



> Thank you! TBH most infrastructures are copied from Metal at the first place.. But surely they are getting different over time, e.g. grid-stride-loop vs runtime-group-size-spec.

Sounds good! 那二位自己协调一下吧，两个backends肯定有很不一样的地方。我们可以在这个thread里面分享work in progress的slides，这样确保分享内容不要太重复。

活动前几天我们找个时间（~20min）线上连线一下，看看zoom的连接、分享屏幕啥的是否都正常。

**Comment by k-ye** [comment]
@archibate @yuanming-hu 你有兴趣主讲具体backend中的技术细节吗？比如codegen怎么工作的，snode怎么被compile成glsl structs的，shaders怎么执行的，各个模块怎么设计的等等？我觉得metal和opengl两个里面有一个讲了这些就足够了，而观众可能更熟悉opengl？

**Comment by yuanming-hu** [comment]
我在第一部分可以high-level讲一下struct compiler和codegen的结构以及LLVM(CPU,CUDA)里面大概是怎么处理的，具体OpenGL backend里面的设计就交给@archibate了？



> 我觉得metal和opengl两个里面有一个讲了这些就足够了，而观众可能更熟悉opengl？

这倒也是。我之前一直以为metal类似OpenGL，后来发现还包含了CUDA...我觉得可以多花1分钟介绍下Metal，应该挺多人感兴趣的。现在国内很多公司给iPhone开发应用，就得用Metal走GPU。

**Comment by yuanming-hu** [comment]
我最后更新了一下，如果大家没有问题，我22小时之后就post到知乎啦！

**Comment by yuanming-hu** [comment]
知乎通知：https://zhuanlan.zhihu.com/p/139627994  欢迎各位网友参加！

**Comment by archibate** [comment]
没问题，Many thanks! 我要开始做ppt了。note: slides represents `PowerPoint` if I'm understanding correct.

**Comment by yuanming-hu** [comment]
> 没问题，Many thanks! 我要开始做ppt了。BTW `slides` means `PowerPoint` if I'm understanding correct.

Right, or Keynote on Mac, or beamer in Latex (pdf).



> > 这样活动结束以后放在网上，不说中文的同学也可以看
> 
> 其实也可以使用中文演示文稿，只要到时放到网上的时候翻译一下就可以了。

Sure that's fine too. I'm just trying to be lazy and make one copy of slides only...

**Comment by jackalcooper** [comment]
可以开启zoom的录屏功能然后上传至 YouTube 吗

**Comment by zhiyaluo** [comment]
Hi，我可以使用bilibili来转播吗？Zoom限制300人数有可能会少了。

**Comment by yuanming-hu** [comment]
> 可以开启zoom的录屏功能然后上传至 YouTube 吗

我们会的，谢谢建议！


> Hi，我可以使用bilibili来转播吗？Zoom限制300人数有可能会少了。

Sounds good. 谢谢！

**Comment by ZzhAlan** [comment]
紧盯微信讨论群的建立

**Comment by yuanming-hu** [comment]
Everything is here: https://github.com/taichi-dev/taichicon (It took Bilibili a while to approve our conference video...)

**Comment by Txusheng** [comment]
赞一个！各位开发者辛苦了！
