### ISSUE TITLE
[refactor] Reduce compilation time by splitting and shortening headers

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#933]
**Concisely describe the proposed feature**
Currently compliling taichi takes too long time can be a great resistance for contributors especially when your work involving common headers like `ir.h` or `lang_util.h` (I guess @xumingkuan suffers this most).

**Describe the solution you'd like (if any)**
1. reduce length of these common headers by removing unused functions and classes.
2. move some of the inline functions in `.h` to `.c`, and then `.h` only holds function declaration.
3. split a large header like `ir.h` into multiple headers, since only part of the functions are used.
4. some common utils may use macros instead of inline functions to reduce c++ lexer's pain.

**Additional comments**
It's slowing down recently. Not sure what added to these headers caused this.

TODO: add compile-time test/comparison result here.

Update: I also found that `clang-8` is 5x slower than `clang-7`.

**Comment by xumingkuan** [comment]
Thanks for proposing this! I think we can try to remove this as the first task:

https://github.com/taichi-dev/taichi/blob/d4a9c18ce3fd39a3c7e448825c9c8ff38a342295/taichi/ir/ir.h#L1555-L1556

It's virtually increasing the length of ir.h.

**Comment by k-ye** [comment]
Covered in #2203
