### ISSUE TITLE
[metal] Large SNode size could break Metal backend

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#975]
**Describe the bug**

This test (added in https://github.com/taichi-dev/taichi/pull/945) broke the Metal backend:

https://github.com/taichi-dev/taichi/blob/bcd856015663d05c22eccab120352391420d011b/tests/python/test_offset.py#L5-L11

Note that the test itself is perfectly fine. Metal failed in this case because it couldn't allocate a large enough buffer to hold `Runtime`, which contains the `ListManager` that manages the sparsity information.

This is an unfortunate result because, unlike the LLVM backend, Metal couldn't yet do dynamic memory allocation. So it tried to allocate a huge chunk of memory for `ListManager` at startup time.

I don't think this can be properly fixed until we figure out a way to allocate memory inside the kernel. But as a work around, we can at least avoid allocating any memory for `ListManager` if there is no sparse SNode.

**Comment by yuanming-hu** [comment]
Oh, `128**4` is probably too large. Maybe I should reduce `128` to `16` for a quick temprary solution?

**Comment by k-ye** [comment]
That's fine, I sent out #976 as a workaround... :)

**Comment by k-ye** [comment]
Reopen this, I need to propagate the fact of whether we have allocated additional memory for holding sparsity info to `metal::KernelManager::init_runtime()`, otherwise there is a memory overflow here...

https://github.com/taichi-dev/taichi/blob/562e1f1111bb664718fc9ea8dbffcb1cbcf3a72c/taichi/backends/metal/kernel_manager.cpp#L580-L585
