### ISSUE TITLE
[Backend] DirectX (D3D11, HLSL) Backend

### ISSUE THREAD

**Issue by quadpixels** [taichi-dev/taichi#992]
**Concisely describe the proposed feature**
I would like to add a DirectX (I'm thinking of D3D11 for now) backend to the compiler so that I can have one more way to utilize the integrated GPU in my laptop.

**Describe the solution you'd like (if any)**
I feel inclined to follow the OpenGL backend's approach (emitting GLSL source) since HLSL (the shader language used by D3D11 and D3D12) is similar to GLSL in many ways.

**Additional comments**
I had been working on a little game with both D3D11 and OpenGL rendering paths, and it appears to me that in Windows, the overhead for creating buffers and issuing draw calls with D3D11 is much lower than with OpenGL (by profiling with GPUView and RenderDoc), so I'm curious if DX can bring a slightly better user experience for Taichi in Windows.
I will start by studying the existing backends (standing on the shoulders of the giants)  (:

**Comment by yuanming-hu** [comment]
Welcome on board! Adding a DirectX backend would be great for Windows users.

I think following the OpenGL backend's implementation shoulds reasonable. I'm not familiar with DirectX, but HLSL sounds like the only mature way to create DX shaders. There are other projects like https://github.com/microsoft/DirectXShaderCompiler - not sure if they provide a more useable alternative approach for shader code generation (e.g. compiling LLVM IR to DX shaders, if there's any chance...)

> I will start by studying the existing backends (standing on the shoulders of the giants) (:

Experts on this are @archibate and @k-ye. If you speak Chinese, welcome to our 0-th TaichiCon event: https://zhuanlan.zhihu.com/p/139627994 We will share some development experience there and uploaded the slides after the event :-)

**Comment by quadpixels** [comment]
Thanks! Yes I actually attended the 0th TaichiCon evnet (:
I remember a participant noted SPIR-V, and potential paths to support multiple backends such as from Vulkan to D3D12 & OpenGL & WebGL, and I feel that might be great for a long-term plan (b/c I'm not familiar with Vulkan) ..
I guess my priority now might be to have something woring first so I'll try to come up with something with D3D11 and HLSL. Archibate and K-ye's presentation gave me a lot of inspirations & I will read into the Taichi language and try to get started.    (:

**Comment by k-ye** [comment]
Nice! FYI, all the backends are in this directory: https://github.com/taichi-dev/taichi/tree/master/taichi/backends (you probably already know)..

**Comment by quadpixels** [comment]
Some updates after all the super long delay (sorry about the delay) as well as some notes for myself:

I'm still using a snapshot from November 2020, I'll sync the code some time later.

- HLSL is very similar to GLSL, I'm copying a lot of stuff from the OpenGL backend
- The nested structure of program & kernel of the OpenGL backend and maybe the DX backend:
  - `CompiledProgram` and `CompiledProgram::Impl`
    - multiple `CompiledKernel` and `CompiledKernel::Impl`'s
      - A `GLProgram` and maybe a `DXProgram`
        - A `GLuint` representing the OpenGL compute shader; or in DX, a `ID3D11ComputeShader*`
- Kernel build steps:
  1. Structural nodes are generated in the "materialize_layout" step.
  2. Populated syntax tree is passed into the `IRVisitor`, using the SNode information generated in the previous step.
- During program launch:
  - A program has multiple kernels (1 kernel = 1 GL shader or 1 DX shader)
  - Arguments in a `taichi::lang::Context` are written to the VRAM by the CPU
  - Actual data are written to the VRAM by the CPU by `write_snode` kernels; this feels similar to on-device `memcpy`s in CUDA
- The write and read buffers are similar between these two APIs
  - In the OpenGL backend they are declared as `layout(std430, binding = 0) buffer data_i32 { int _data_i32_[]; };`
  - In DX, I will use `RWStructuredBuffer<int> _data_i32_ : register(u0);`
- Debugging workflow
  - I have a batch file storing all the environmental variables then I can do `%PYTHON% laplace.py`
  - To attach the Visual Studio debugger to a console program, I click on the command prompt window to "pause" the currently running Taichi program then use the "attach to process" command in VS. There seems to be a way to launch the debugger from the command line just like one would launch gdb so one wouldn't have to "pause" the program by clicking into the cmd window.

I come to appreciate how much work the existing Taichi infrastructure has done for creating new backends. Plus, GLSL shares a lot of similarities with HLSL, which is also extremely helpful.
I have part of the Laplace example working (writing initial data to the buffers), will aim at getting the whole example working for the current step, then try to understand more of the code base.

**Comment by bobcao3** [comment]
Potentially very useful thing is to have the LLVM IR compile to SPIRV, and use [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross) to cross compile to all platforms (it is capable of compiling to GLSL, HLSL, and Metal Shading Language). I'm not familiar with taichi's code generation flow, but for most cross platform game engines SPIRV Cross has been the choice.

**Comment by bobcao3** [comment]
Can you compare the taichi IR generated? Looks like a hlsl codegen bug.

**Comment by bobcao3** [comment]
Just as a causion, I recently added a loop code motion thing, that may
change things a bit. Can you try turning it off?

**Comment by quadpixels** [comment]
Ah I think I found the cause: I did not redirect the output in the JITted kernel correctly. It is not because of the newly-added loop motion feature since my code base is not that new yet.

The Constant Fold step generates JIT kernels when the compiler evaluates certain expressions:

Input:
```
...
    <i32> $23 = const [122]
    <i32> $24 = div $22 $23
    <i32> $25 = const [0]
    <i32> $26 = cmp_lt $22 $25
    <i32> $27 = cmp_lt $23 $25
    <i32> $28 = mul $24 $23
    <i32> $29 = cmp_ne $26 $27
    <i32> $30 = cmp_ne $22 $25
    <i32> $31 = cmp_ne $28 $22
...
```

Output:
```
    <i32> $23 = const [122]
    <i32> $24 = div $22 $23
    <i32> $25 = const [0]
    <i32> $26 = cmp_lt $22 $25
    <i32> $110 = const [0]
    <i32> $28 = mul $24 $23
    <i32> $29 = cmp_ne $26 $110     <---  $110 is the return value of "jit_evaluator_0"
    <i32> $30 = cmp_ne $22 $25
    <i32> $31 = cmp_ne $28 $22
```

My return value were not correctly redirected to the return buffer, causing $110 to take a wrong value. I saw Archibate left comments like "consider use _rets_{}_ instead of _args_{}_" next to KernelReturnStmt and now I can kind of see why.

The Loop Code Motion sounds interesting, I need to rebase to the latest to try it out. :D

**Comment by quadpixels** [comment]
Added the AtomicAdd operations and found HLSL and GLSL atomic ops look very similar, almost identical syntax (`operation(reference, old, new)`) and limitations (can only operate on integer-typed buffers, and for HLSL only `RWByteAddressBuffer` and not structured buffers like `RWStructuredBuffer<int>`)

During this process I copied the "atomic add of floating point numbers" approach from the OpenGL backend.

Got one new error: to_numpy() throws a "RuntimeError: invalid map<K, T> key" error, maybe I've corrupted something on the Python side? Encountered this a few days ago and now it's the blocker towards showing something on the GUI, so looking into this as well (in addition to rebasing..)

**Comment by yuanming-hu** [comment]
> Got one new error: to_numpy() throws a "RuntimeError: invalid map<K, T> key" error, maybe I've corrupted something on the Python side?

I've never encountered this error, so it's indeed very weird. Note that "invalid map<K, T> key" may actually be a C++ error when you use `std::map` in C++ - Taichi forwards uncaptured C++ errors to Python as a `RuntimeError` :-)

**Comment by quadpixels** [comment]
I realized it was because I haven't correctly compiled the `matrix_to_ext_arr_c18_0` kernel that is used to support the `to_numpy()` method, after adding support for that kernel, the error goes away and to_numpy() starts working.

I compared the results between the DXX backend and the OpenGL backend after 1 frame and the distance looks small enough; however I'm getting some bigger errors after more than a few frames .. will take a look at what's happening.

**Comment by quadpixels** [comment]
It did seem to be because of the problem in locking: Should have been using atomic operations for both acquiring a lock and releasing a lock; the error was caused by using a plain write to release the lock. Switching to an atomic exchange seems to fix it.

There are still some errors left, I think the error was more pronounced when I accidentally have a lot of particles overlap by generating the initial pattern like this (due to not having random number generator yet):
```
def init():
  for i in range(N_PARTICLES):
    x[i] = [ (i * 3 % 100) / 100 * 0.4 + 0.3,
             (i * 17 % 100) / 100 * 0.4 + 0.5 ]  # This gives lots of overlapping particles
```
When there is less overlap the errors look smaller though.

Performance is _very low_ for now: one call to the `substep` kernel takes 25ms, which is more than 10x slower than the OpenGL backend on my device (8550U & UHD620). I'm wondering if the locking procedure is too inefficient or if there are overheads on the non-kernel execution stuff. Wondering what can be found out by profilers, or what would happen if I make a standalone program and copy & paste the generated kernel into it.

The result looks reasonable ... for now? Would be easier to tell if I can fix the performance issue.
![towards mpm88](https://user-images.githubusercontent.com/1406681/121662681-7db7d880-ca5a-11eb-85f0-c3bda5734604.png)

**Comment by bobcao3** [comment]
Try the Intel Graphics Performance Analyzer and get a GPU trace maybe?

**Comment by quadpixels** [comment]
Sure, I'll try the graphics performance analyzer. \
Found a new bug: when running on an NVIDIA GPU I'm encountering some problems in the way bits are interpreted. \
For example: integer 10 is 0x0000000A, while 0x0000000A interpreted as floating point number is 1.40129846432e-44, a very small floating point number. \
When I write 10.0 to a vector and read it back I get 10.0 on the iGPU and got very small floating point numbers on the NVIDIA GPU. \
Very much likely I made some errors in the structured buffers and those errors only manifest on certain platforms... and this could be hurting performance as well so they need to be corrected.

**Comment by bobcao3** [comment]
Maybe check whether your buffer type and layout match between host and
shaders, it sounds like a floating point value is converted to an integer
in this case.

**Comment by quadpixels** [comment]
Narrowed the cause down a bit:\
Not sure what I'm seeing but the kernel seems to be using stale values sometimes ..

Problematic run on a desktop PC with a dGPU:
```
(Right before launching a SNode Writer kernel)
Checking args_f32
as int: 0 1186414996 0 0 0 0 0 0
as float: 0 23456.8 0 0 0 0 0 0      <--- Should write 23456.8 to x[0].y
data_f32 first 100 elts:12345.7 12345.7 0 ...  <-- For some reason 12345.7 (previously written value) is written to x[0].y
args_f32 first 8 elts:0 12345.7 0 0 0 0 0 0
```

Compare this to a normal run on a laptop with an iGPU:
```
Checking args_f32
as int: 0 1186414996 0 0 0 0 0 0
as float: 0 23456.8 0 0 0 0 0 0
data_f32 first 100 elts:12345.7 23456.8 0 ...    <--- 23456.8 is correctly written to x[0].y
args_f32 first 8 elts:0 23456.8 0 0 0 0 0 0
```

Looks like the args_f32 buffer never got updated. This seems to affect all operations that involve the usage of the args_f32 buffer (JIT kernels produce invalid values like infinity, and snode reader return values are completely off).
And more interestingly this only happens on one PC and not the other ...

**Comment by quadpixels** [comment]
Hmm it turns out the cause was I `Map`'ed a resource and forgot to `Unmap` it
Some GPUs will allow this to happen while some other GPUs will refuse to work ...
Adding an `Unmap` fixed it :D

**Comment by quadpixels** [comment]
Seems the issue with wrong results with > 1 blocks is due to coherence across blocks and may be fixed with the [`globallycoherent`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-rwbyteaddressbuffer) suffix.
Now investigating the issue with >= 8K particles.

**Comment by quadpixels** [comment]
I would want to build a small test bench (a test program) for "replaying" the mpm program, basic idea is: 1) the test program creates a DX11 context, 2) export the kernels and build the kernels in the test program, 3) dump the buffers from a running Taichi instance, 4) load the buffer in the test program and execute the kernels, 5) perhaps render the dataset with DX11.
The flow is somewhat similar to this: https://taichi.readthedocs.io/en/stable/export_kernels.html but not automated for now.
This would allow attaching RenderDoc and maybe some other profilers to it, as well as manually inspecting performance problems.

**Comment by yuanming-hu** [comment]
Sounds like the Ahead-of-time compilation/runtime system that @k-ye and his team is working on :-)

**Comment by quadpixels** [comment]
Roughly done, being able to look at a Kernel in RenderDoc is what I wanted to do a few weeks ago :D
Will look more closely at the results later.
![image](https://user-images.githubusercontent.com/1406681/129588009-65eb2748-d9c2-4b80-a43b-be2626502b07.png)

Simple MSVS 2019 project is also attached if anyone is interested in taking a look: 
[TaichiPlayground.zip](https://github.com/taichi-dev/taichi/files/6993527/TaichiPlayground.zip)

**Comment by yuanming-hu** [comment]
Fantastic!

**Comment by bobcao3** [comment]
It seems the DX11 backend is completed & working now. Performance optimizations etc. can open a new issue to track
