### ISSUE TITLE
[misc] benchmarks/run.py fail in v0.6.4

### ISSUE THREAD

**Issue by TroyZhai** [taichi-dev/taichi#999]
The run.py is changed in v0.6.4 but it fails to run due to a really minor issue.

error:
![image](https://user-images.githubusercontent.com/7610945/82136369-61e70080-9861-11ea-82bc-e19231465058.png)

L56-L62 of run.py:
![image](https://user-images.githubusercontent.com/7610945/82136365-5562a800-9861-11ea-8b7f-76684f7ee00a.png)

In L59 the benchmark_dir is set to "" (empty string) and thus os.listdir in L60 fails. I think the correct path here should be "." instead of "".

**Comment by archibate** [comment]
Thank for pointing out! Sorry about introducing the bug, I always run on repo root directory so didn't notice the problem.. Either use `os.path.abspath(...)` or `os.path.join(ti.get_repo_dir(), 'benchmarks')` solve the problem.
This also raise a question that, can we run `ti test` in non-repo-root directory?

**Comment by TroyZhai** [comment]
> This also raise a question that, can we run `ti test` in non-repo-root directory?

Well IMHO, it's a nice feature to have but really no big deal for users.
